Change logic for routing withdraw requests
department-of-veterans-affairs/caseflow pull request #14278
Opened 2020-05-13 18:53 UTC by sahalliburton

Resolves #14129 

### Description
Reverses the check of empty representatives to check whether the representative is part of a Vso and route to service organization location

### Acceptance Criteria
- [ ] Code compiles correctly

2020-05-18 07:22 UTC, tomas-nava requested changes
I think this is looking good! I've requested a few changes.

Also, #14129 isn't fully resolved by this PR; I think we should say it Connects instead. Once we've completed #14297, we'll be able to resolve.

### the way it works before this PR is merged
```markdown
if there is no representative
then assign the appeal to location *81* (case storage)
else assign the appeal to location *55* (service organization)
```
**What's missing:** Appeals with private agent/attorney and state/regional VA organization representatives are being assigned to location 55 instead of 81.

### the way it will work after this PR merges
```markdown
if the POA/representative type is a VSO
then assign the appeal to location *55* (service organization)
else assign the appeal to location *81* (case storage)
```
**What's missing:** Appeals with non-colocated VSO representatives will be assigned to location 55 instead of 81.

### the way it must work before we can resolve
(after #14297)
```markdown
if the POA/representative type is a colocated VSO
then assign the appeal to location *55* (service organization)
else assign the appeal to location *81* (case storage)
```

### edit
This now resolves #14297 as well as #14129 as of 77884f31a783bc5d697af642b74ebaa017ec1ed6

2020-09-25 00:50 UTC, tomas-nava commented
This is blocked because the location is being updated twice every time a hearing is withdrawn; once in `ScheduleHearingTask.withdraw_hearing` when the hearing is withdrawn, and then in `HearingTask.when_child_task_completed` after the `ScheduleHearingTask` is closed. The two locations may conflict (as they do in the test: `spec/models/tasks/schedule_hearing_task_spec.rb:202`)

2020-10-29 19:08 UTC, tomas-nava reviewed
removing the request changes requirement

2020-10-29 19:09 UTC, tomas-nava approved these changes
really removing the request changes requirement

2020-10-30 15:07 UTC, ferristseng approved these changes
LGTM! Tests look great! :shipit:

2020-10-30 15:07 UTC, ferristseng commented on spec/models/tasks/hearing_task_spec.rb
> +          expect { subject }.to change { vacols_case.reload.bfcurloc }.from(loc_caseflow).to(loc_transcription)
Whoa, TIL `change...from...to`!

2020-11-03 15:38 UTC, lund5000 commented
@tomas-nava We have approval from John Gosnell to release this to production.

2020-11-03 17:20 UTC, merged