Wd/13106/business line
department-of-veterans-affairs/caseflow pull request #15116
Opened 2020-08-31 14:49 UTC by wdrougas-tista

Resolves #{13106}

### Description
Added copy text to show user number of cases completed in last week for Non-Comp decision reviews

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

### User Facing Changes
 - [X] Screenshots of UI changes added to PR & Original Issue

<img width="1065" alt="Screen Shot 2020-08-31 at 10 46 11 AM" src="https://user-images.githubusercontent.com/63597932/91733484-93b57600-eb77-11ea-817a-4a814525c5f7.png">

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy 
* [ ] Write a separate story (within the same file) for each discrete variation of the component

2020-09-03 23:36 UTC, jcq requested changes
A couple of comments/questions, but largely good!

The only other thing is that my guess is you don't actually want to include the `dump.rdb` file in this commit — not sure how that got modified, but seems unrelated...?

2020-09-03 23:36 UTC, jcq commented on client/COPY.json
> +  "QUEUE_PAGE_COMPLETE_TASKS_DESCRIPTION": "Cases completed (last 7 days):",
Did we confirm that we wanted to change this in the place that it already existed in addition to the place where you were adding it?

2020-09-03 23:36 UTC, jcq commented on client/app/nonComp/components/NonCompTabs.jsx
> +        description={COPY.QUEUE_PAGE_COMPLETE_TASKS_DESCRIPTION}
Do we really want to add this to the "In progress" tab in addition to the "Completed" tab?

2020-09-03 23:36 UTC, jcq commented on client/app/nonComp/components/NonCompTabs.jsx
> +NonCompTabsUnconnected.propTypes = {
hooray for proptypes!

2020-09-03 23:36 UTC, jcq commented on client/app/nonComp/components/NonCompTabs.jsx
> +      <div className="cf-noncomp-queue-completed-task">{this.props.description ?? null}</div>
This syntax will still display the `<div>` regardless of if there are contents. It might be better to make the whole thing conditional...?

```jsx
{this.props.description && 
<div className="cf-noncomp-queue-completed-task">{this.props.description}</div>
}
```

2020-09-03 23:36 UTC, jcq commented on client/app/styles/_noncomp.scss
> +  margin-bottom: 20px;
This style would be the reason you likely want to make the rendering of the whole `div` conditional — otherwise you have a 20px gap w/o content

2020-09-04 12:07 UTC, wdrougas-tista commented on client/COPY.json
> +  "QUEUE_PAGE_COMPLETE_TASKS_DESCRIPTION": "Cases completed (last 7 days):",
@jcq Yeah when looking at the [batteam](https://dsva.slack.com/archives/CHX8FMP28/p1578493701009900) issue that raised this it confirms this

2020-09-04 12:08 UTC, wdrougas-tista commented on client/app/nonComp/components/NonCompTabs.jsx
> +        description={COPY.QUEUE_PAGE_COMPLETE_TASKS_DESCRIPTION}
Yeah good point, I imagine not

2020-09-04 12:22 UTC, wdrougas-tista commented on client/app/nonComp/components/NonCompTabs.jsx
> +      <div className="cf-noncomp-queue-completed-task">{this.props.description ?? null}</div>
Yeah makes sense

2020-09-04 17:32 UTC, jcq approved these changes

2020-09-04 21:09 UTC, merged