Display hearing type on case details
department-of-veterans-affairs/caseflow pull request #15145
Opened 2020-09-02 17:47 UTC by rubaiyat22

Resolves #15021

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy 
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR

2020-09-02 19:12 UTC, rubaiyat22 commented on client/app/queue/utils.js
> +      readableHearingRequestType: appeal.attributes.readable_hearing_request_type,
`sanitizedHearingRequestType` was not being used anywhere

2020-09-04 19:06 UTC, tomas-nava requested changes
This is looking great! I think, though, that if a hearing is scheduled, we want to display the type of that hearing, or the type of the most recently held hearing if it has a disposition. So if I've got a central or video hearing that's been converted to virtual, I should see "Virtual" as the hearing type.

2020-09-04 21:01 UTC, rubaiyat22 commented on app/models/appeal.rb
> +    return hearings.last.readable_request_type if !hearings.empty?
Tomas and I spoke async and decided that for now we should just evaluate request type based on the original request and not consider scheduled hearings. this [commit](https://github.com/department-of-veterans-affairs/caseflow/pull/15145/commits/b9d01e273cf874d2cb05ecf7252c969cc6bfd501) undoes some changes related to that. We will talk about this further with design and follow up from there.

2020-09-04 21:03 UTC, rubaiyat22 commented on spec/models/appeal_spec.rb
>      context "no hearings have been scheduled" do
left this context as is for when we introduce evaluating request type based on scheduled hearings

2020-09-04 22:08 UTC, tomas-nava approved these changes
approve!

2020-09-05 02:10 UTC, merged