Shalliburton/14895 connect schedule veteran rspec
department-of-veterans-affairs/caseflow pull request #15215
Opened 2020-09-10 20:19 UTC by sahalliburton

### Description
Stacked PR Part 3

Adds/updates backend feature tests for the schedule veteran hearing directly workflow

2020-09-10 20:20 UTC, sahalliburton commented on client/app/hearings/components/ScheduleVeteran.jsx
> +  const requestType = selectedHearingDay?.regionalOffice === 'C' ? HEARING_REQUEST_TYPES.C : HEARING_REQUEST_TYPES.V;
Fixes an issue with the way the requestType is set

2020-09-10 20:21 UTC, sahalliburton commented on client/app/hearings/components/ScheduleVeteranForm.jsx
> +            <ReadOnly spacing={0} label="Regional Office" text={HEARING_REQUEST_TYPES.C} />
The value here should always be Central because in this block we already know the hearing type is `virtual` (Line 55)

2020-09-10 20:22 UTC, sahalliburton commented on client/app/hearings/components/ScheduleVeteranForm.jsx
> +                regionalOffice={ro}
Needs the regional office key to display different default radio buttons

2020-09-10 20:22 UTC, sahalliburton commented on client/app/hearings/components/ScheduleVeteranForm.jsx
> +                value={hearing.hearingDay || initialHearingDate}
Test was failing when the initial hearing date was not passed

2020-09-10 20:23 UTC, sahalliburton commented on client/app/hearings/components/VirtualHearings/AppellantSection.jsx
> +            name="appellantTz"
`name` is needed so capybara can find the element, label will change what is displayed to the user

2020-09-10 20:23 UTC, sahalliburton commented on client/app/hearings/components/VirtualHearings/RepresentativeSection.jsx
> +            label="POA/Representative Timezone"
Same as appellant section

2020-09-10 20:24 UTC, sahalliburton commented on spec/feature/hearings/postpone_hearing_spec.rb
> +      scenario "when rescheduling to Virtual hearing" do
This is the only real new test here, the rest of the changes are just refactoring to shared tests

2020-09-10 20:27 UTC, sahalliburton commented on spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
> +  shared_examples "scheduling a virtual hearing" do
Again this is the only real new test, the rest are just to refactor into shared tests so we can check both with and without the feature flag enabled

2020-09-16 16:15 UTC, ferristseng requested changes
LGTM except for the one possible merge conflict I noted, which may be responsible for the test failures? Otherwise, the tests all look great!

2020-09-16 16:15 UTC, ferristseng commented on spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
> +    it_behaves_like "an appeal where there is an open hearing"
Nice! I like the usage of `shared_examples` here

2020-09-16 16:46 UTC, sahalliburton commented on client/test/data/hearings.js
> +  regionalOffice: 'RO17',
yeah that does make more sense, just updated to reflect

2020-09-16 16:52 UTC, ferristseng approved these changes

2020-09-16 16:53 UTC, merged