Create ChangeHearingRequestTypeTask
department-of-veterans-affairs/caseflow pull request #15213
Opened 2020-09-10 20:10 UTC by ferristseng

Resolves #14899

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2020-09-15 14:35 UTC, ferristseng commented on .rubocop.yml
> +  Enabled: false
Disable this rubocop to let us include task trees inside our coding documentation

2020-09-15 14:36 UTC, ferristseng commented on app/repositories/appeal_repository.rb
> -    def create_schedule_hearing_tasks
Migrating this method and dependencies to the `HearingTaskTreeInitializer` class I created since it seems to make sense there

2020-09-16 00:36 UTC, tomas-nava requested changes

2020-09-16 14:29 UTC, ferristseng commented on .rubocop.yml
> +  Enabled: false
I think my preference would be to keep it disabled -- it's kind of strange to enforce only ascii in comments since most computers support it now.

2020-09-16 14:32 UTC, ferristseng commented on client/constants/TASK_ACTIONS.json
> +  },
yeah, I intended this mostly to be placeholder stuff -- maybe I can make that more explicit

2020-09-16 14:35 UTC, ferristseng commented on app/services/hearing_task_tree_initializer.rb
> +        ChangeHearingRequestTypeTask.find_or_create_by!(**create_args, parent: schedule_hearing_task)
I wasn't aware that there could be multiple `HearingTask` trees, but that makes sense!

2020-09-16 15:47 UTC, tomas-nava commented on app/services/hearing_task_tree_initializer.rb
> +        ChangeHearingRequestTypeTask.find_or_create_by!(**create_args, parent: schedule_hearing_task)
I don't think there can be multiple _open_ `HearingTask` trees, but I don't think using `find_or_create_by` this way discriminates.

2020-09-16 16:21 UTC, tomas-nava approved these changes
approve!

with a couple non-blocking suggestions

2020-09-16 16:21 UTC, tomas-nava commented on spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
> +      expect(page).not_to have_content(ChangeHearingRequestTypeTask.label)
You could get rid of these two expectations and add a
```ruby
expect(ScheduleHearingTask.count).to eq(0)
```
to quiet the Code Climate errors.

2020-09-16 16:21 UTC, tomas-nava commented on app/models/tasks/change_hearing_request_type_task.rb
> +
```suggestion
##
# Task created when a hearing coordinator visits the Case Details page of an appeal with a
# Travel Board hearing request. Gives the user the option to convert that request to a video
# or virtual hearing request so it can be scheduled in Caseflow.
```

2020-09-16 16:25 UTC, ferristseng commented on spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
> +      expect(page).not_to have_content(ChangeHearingRequestTypeTask.label)
With this, I wanted to make sure the tasks were showing on the first load too. I was running into an issue when I implemented it at first where the tasks weren't showing in the frontend even though they were created on the backend!

2020-09-16 18:35 UTC, merged