Reset virtual hearing states on cancel
department-of-veterans-affairs/caseflow pull request #15230
Opened 2020-09-14 15:22 UTC by rubaiyat22

Resolves #15131

### Description
- reset virtual hearing state when `cancel` is clicked on conversion page to prevent virtual hearing fields from being disabled

### Testing Plan
1. Enable feature toggle on rails console `FeatureToggle.enable!(:full_page_video_to_virtual, users: [User.find_by(css_id: "BVASYELLOW")])` and `FeatureToggle.enable!(:schedule_virtual_hearings_for_central, users: [User.find_by(css_id: "BVASYELLOW")])`
2. Login as `BVASYELLOW`
3. Go to http://localhost:3000/hearings/schedule and pick a video or central hearing day
4. Click on `Virtual` on hearing type dropdown on details
5. See that the conversion form opens
6. click `cancel` on lower left corner and see that the virtual hearing fields on details page are not disabled

2020-09-16 17:42 UTC, sahalliburton commented on client/app/hearings/components/Details.jsx
> +          onClick={converting ? () => {
I am not sure if this is needed anymore with recent changes to this component

2020-09-21 15:09 UTC, rubaiyat22 commented on client/app/hearings/components/Details.jsx
> +          onClick={converting ? () => {
made an update!

2020-09-21 15:41 UTC, sahalliburton requested changes
When I was testing this, before I convert to a Virtual hearing for the first time if I take the following steps I get an issue:

1. Following the test steps to get to a Central hearing and select the dropdown to convert to Virtual
1. Change the hearing time which should have been previously unselected
1. Click the cancel button to go back to the hearing details
1. Click the dropdown again to convert the hearing to Virtual
1. See that the hearing time is filled out and click the `Convert to Virtual Hearing` button
1. The virtual hearing for me was not scheduled and it only updated the hearing time

Can you test again on your side and see if you experience the same issues?

Thanks!

2020-09-21 19:41 UTC, sahalliburton commented on client/app/hearings/components/Details.jsx
> +          onClick={converting ? () => {
I believe that `resetState` function is setup to receive a payload with which to reset the state meaning it can be used to reset the state with the initialState on cancel and on submit it can be reset with the new hearing payload returned from the API. I think it still makes sense to keep this logic in the resetState function and just update the submit function to pass the new hearing data, unless there is something happening async that would make it so we shouldnt be doing that, what do you think?

2020-09-21 21:01 UTC, rubaiyat22 commented on client/app/hearings/components/Details.jsx
> +          onClick={converting ? () => {
I think we could do that. There are some other places where resetState is being called and I'm wondering if i should just make it optional to dispatch `RESET_HEARING` in `resetState`

2020-09-22 14:35 UTC, rubaiyat22 commented on client/app/hearings/components/Details.jsx
> +          onClick={converting ? () => {
made updates in this commit https://github.com/department-of-veterans-affairs/caseflow/pull/15230/commits/63736cd5e572ec7edeb86fa753d49e4e2074b5e7

2020-09-22 14:36 UTC, rubaiyat22 commented on client/app/hearings/components/Details.jsx
> +          reset={() => resetState(initialHearing)}
turns out the modal was having the same issue so this resolved it

2020-09-22 16:16 UTC, sahalliburton approved these changes
LGTM!

2020-09-22 16:17 UTC, sahalliburton commented on client/app/hearings/components/Details.jsx
> +          onClick={converting ? () => {
Thanks for making this change and adding the check for whether the hearing object was passed, I think this will prevent any other strange state issues

2020-09-22 17:10 UTC, merged