Automate fix for RedistributedCase::CannotRedistribute Sentry alert
department-of-veterans-affairs/caseflow pull request #15248
Opened 2020-09-15 20:55 UTC by ajspotts

Resolves #14705

### Description
This fix allows for legacy appeals that have closed actionable (non-Root or TrackVeteran tasks) to be automatically redistributed.  Prior to this, the 🦇 team would have to manually redistribute these cases when [notified](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/7524/) by the `RedistributedCase::CannotRedistribute` Sentry alert.  

### Acceptance Criteria
- [ ] Legacy appeals with closed actionable tasks are automatically redistributed

### Testing Plan
1. Find an appeal ready to be distributed and give it a task that would send it back to distribution
```ruby
# What case will be distributed next?
vacols_id = VACOLS::CaseDocket.distribute_nonpriority_appeals(User.third,"not_genpop", nil, 1000, false, dry_run: true).first["bfkey"]
# Let's create a previous distribution for this case
distribution = FactoryBot.build(:distribution, judge: User.third)
distribution.save(validate: false)
distribution.distributed_cases.create(
        case_id: vacols_id,
        priority: false,
        docket: "legacy",
        ready_at: VacolsHelper.normalize_vacols_datetime(Time.zone.now),
        docket_index: "123",
        genpop: false,
        genpop_query: "any"
      )

appeal = LegacyAppeal.find_or_create_by_vacols_id(vacols_id)
HearingTask.create!(appeal: appeal).completed!
appeal.reload.treee
LegacyAppeal 26 (legacy)   │ ID   │ STATUS    │ ASGN_BY │ ASGN_TO │ UPDATED_AT
└── HearingTask            │ 2701 │ completed │         │ Bva     │ 2020-09-15 17:35:54 UTC │
```
2. Lets see what happens when we distribute the case (make sure it is being properly redistributed)
```ruby
VACOLS::Case.find_by(bfkey: vacols_id).bfcurloc
=> "81"
distribution = FactoryBot.build(:distribution, judge: User.third)
distribution.save(validate: false)
LegacyDocket.new.distribute_nonpriority_appeals(distribution)
VACOLS::Case.find_by(bfkey: vacols_id).bfcurloc
=> "AABSHIRE"
```
3. Open a task on the appeal, indicating that it is being worked in caseflow
```ruby
HearingTask.create!(appeal: appeal)
appeal.reload.treee
LegacyAppeal 26 (legacy)  │ ID   │ STATUS    │ ASGN_BY │ ASGN_TO │ UPDATED_AT              
├── HearingTask           │ 2701 │ completed │         │ Bva     │ 2020-09-15 17:35:54 UTC │
└── HearingTask           │ 2702 │ assigned  │         │ Bva     │ 2020-09-15 17:41:25 UTC │
```
4. Lets see what happens when we distribute the case (case with active actionable task should remain in caseflow)
```ruby
VACOLS::Case.find_by(bfkey: vacols_id).update(bfcurloc: "81")
=> "81"
distribution = FactoryBot.build(:distribution, judge: User.third)
distribution.save(validate: false)
LegacyDocket.new.distribute_nonpriority_appeals(distribution)
VACOLS::Case.find_by(bfkey: vacols_id).bfcurloc
=> "CASEFLOW"
```

2020-09-15 21:11 UTC, ajspotts commented on app/services/redistributed_case.rb
Crux of the fix - we check the legacy appeal for closed actionable tasks and allow for redistribution if that is the case

2020-09-15 21:12 UTC, ajspotts commented on app/services/redistributed_case.rb
> -        vacols_id: case_id,
Update out sentry alert to use tags per Yoom's [suggestion](https://github.com/department-of-veterans-affairs/caseflow/issues/14705#issuecomment-660366257)

2020-09-15 21:20 UTC, ajspotts commented on app/models/task.rb
>    end
Provide a `closed?` method to check if an appeal has open tasks.

2020-09-15 21:21 UTC, ajspotts commented on app/models/task.rb
> +  end
Update `open?` to return the inverse of `closed?`

2020-09-16 15:55 UTC, yoomlam reviewed
Some considerations

2020-09-16 15:55 UTC, yoomlam commented on app/models/task.rb
>    # properties of the task will not change.
I think these comments should be attached to the `active?` method. See https://github.com/department-of-veterans-affairs/caseflow/pull/9169/files

2020-09-16 15:55 UTC, yoomlam commented on app/models/task.rb
> +  end
Thought, not suggestion: Alternative is to use `open_statuses` directly. Related ticket: #12916.

2020-09-16 15:55 UTC, yoomlam commented on app/models/task.rb
>    end
I presume in lieu of a `closed?` method, we used `!open?` historically. So the question is should we continue that trend or start using `closed?`?

2020-09-16 15:55 UTC, yoomlam commented on app/models/task.rb
> +  # does not include on_hold
Not sure we really need this comment since we can easily check:
```
    def active_statuses
      [Constants.TASK_STATUSES.assigned, Constants.TASK_STATUSES.in_progress]
    end
```
Related ticket: #12916.

2020-09-16 17:22 UTC, ajspotts commented on app/models/task.rb
>    end
I think because for tasks, we have corresponding methods for `active_statuses` -> `active?` and `open_statuses` -> `open?` that it follows that `closed_statuses` should have `closed?`

2020-09-16 17:22 UTC, ajspotts commented on app/models/task.rb
> +  # does not include on_hold
Perhaps, I'm updating the `active?` method comments per your earlier suggestion and I don't think the additional clarity hurts at all

2020-09-16 22:55 UTC, yoomlam requested changes
Some comments, suggestions, and questions.

2020-09-16 22:55 UTC, yoomlam commented on app/services/redistributed_case.rb
> +    # redistribute if there are either no relevant tasks or if they are completed or cancelled
```suggestion
    # redistribute if there are no relevant tasks or if they are all completed or cancelled
```

2020-09-16 22:55 UTC, yoomlam commented on spec/models/distribution_spec.rb
>          end
I believe you've converted this context into the subsequent context on lines 298-322. I think the point of this context is to ensure that an alert is sent, so you need to change the case to be illegit rather than changing the intent of the test.

2020-09-16 22:55 UTC, yoomlam commented on app/services/redistributed_case.rb
> +    return true if legacy_appeal_relevant_tasks.blank? || legacy_appeal_relevant_tasks.all?(&:closed?)
```suggestion
    return true if legacy_appeal_relevant_tasks.all?(&:closed?)
```
`all?` returns `true` on an empty array.

2020-09-16 22:55 UTC, yoomlam commented on spec/services/redistributed_case_spec.rb
> +          expect(subject.ok_to_redistribute?).to eq true
Did you check with Hunter that this is now the desired intended behavior?

2020-09-16 22:55 UTC, yoomlam commented on spec/services/redistributed_case_spec.rb
> +          expect(subject.ok_to_redistribute?).to eq true
Did you check with Hunter that this is now the desired intended behavior?

2020-09-18 19:41 UTC, ajspotts commented on spec/services/redistributed_case_spec.rb
> +          expect(subject.ok_to_redistribute?).to eq true
Yes, when we have a closed actionable (non TrackVeteranTask or RootTask) we want to automatically redistribute

2020-09-18 19:49 UTC, ajspotts commented on spec/services/redistributed_case_spec.rb
> +          expect(subject.ok_to_redistribute?).to eq true
Yes, per her comments [here](https://dsva.slack.com/archives/CJL810329/p1600269896134100?thread_ts=1600204474.126100&cid=CJL810329).  We previously checked if there were [closed hearing tasks](https://github.com/department-of-veterans-affairs/caseflow/blob/af4d7f50d5a2e7eeceb609fdbbcd18e708615695/app/services/redistributed_case.rb#L40) but we have simplified that to checking for all closed tasks

2020-09-18 20:18 UTC, ajspotts commented on spec/models/distribution_spec.rb
>          end
In regard to this, we actually no longer are expecting alerts to be sent. Simply: if there are open tasks -> move case to caseflow, if there are no open tasks -> redistribute to judge.  That said to be on the safe (per Hunter's recommendation), if there _are_ any fall-through cases which we have not anticipated they will hit the alert. However since we don't know what they are I'm not sure how to write a test for them.

I instead will update this closer to the original intent, which is checking for an illegit redistribution (appeal with open tasks) which as outlined will be sent to caseflow.

2020-09-18 20:30 UTC, yoomlam commented on spec/models/distribution_spec.rb
>          end
Ok got it! To test, you can mock/stub `ok_to_redistribute?` to return false with an appeal with all closed tasks so that the Sentry alert code will execute.

2020-09-18 22:27 UTC, yoomlam approved these changes

2020-09-21 12:45 UTC, merged