Connect backend and frontend for convert hearing type page
department-of-veterans-affairs/caseflow pull request #15314
Opened 2020-09-24 20:36 UTC by ferristseng

Resolves #15159

### Description

WIP

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

2020-09-28 15:00 UTC, ferristseng commented on app/controllers/tasks_controller.rb
> +    invalid_record_error(error.record)
I was using this to test the error handling code on the frontend. I figured it probably makes sense to JSONify any validation errors regardless, so I kept it in the PR.

2020-09-28 15:01 UTC, ferristseng commented on app/models/hearing_day.rb
> +  REQUEST_TYPES = Constants::HEARING_REQUEST_TYPES.with_indifferent_access.freeze
I moved these mappings to a JSON constants file so the frontend would have access to them too.

2020-09-28 15:03 UTC, ferristseng commented on client/app/hearings/components/VirtualHearings/AppellantSection.jsx
> +  const appellantName = hearing?.appellantIsNotVeteran ?
I made this based on the `appellantIsNotVeteran` flag, which is how we determine whether or not to use appellant vs. veteran in other places.

2020-09-28 15:04 UTC, ferristseng commented on client/app/hearings/constants.js
> -export const HEARING_REQUEST_TYPES = {
I removed this and preferred directly importing `VIDEO_HEARING`, `CENTRAL_OFFICE_HEARING`, and `VIRTUAL_HEARING`. We declare these kinds of mappings in a bunch of different places, so I'm trying to consolidate where possible.

2020-09-29 16:12 UTC, sahalliburton commented on client/app/hearings/components/VirtualHearings/AppellantSection.jsx
> +  const appellantName = hearing?.appellantIsNotVeteran ?
Thanks thats a much better way to check

2020-09-29 16:50 UTC, sahalliburton requested changes
LGTM, I tested both scenarios and when geomatched it does show the regional office and when not it shows the correct text. There is just one issue I noticed and that is when the hearing is converted to travel, I need to refresh the page in order to see the hearing type change to "Virtual"

2020-09-29 22:18 UTC, ferristseng commented
> There is just one issue I noticed and that is when the hearing is converted to travel, I need to refresh the page in order to see the hearing type change to "Virtual"

It looks like this is an issue because the appeal never gets refreshed after the change is made. I updated the submit call to delete the appeal from the store, which forces the case details page to do a full reload of the appeals data.

https://github.com/department-of-veterans-affairs/caseflow/pull/15314/commits/2ac01b3031cd3a104cfa5878e6a3e986176058c5

2020-09-30 14:35 UTC, sahalliburton approved these changes
LGTM

2020-09-30 15:15 UTC, merged