Display hearing request type column on assign hearings table
department-of-veterans-affairs/caseflow pull request #15312
Opened 2020-09-24 18:42 UTC by rubaiyat22

Resolves #15059

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2020-09-24 18:44 UTC, rubaiyat22 commented on spec/feature/hearings/assign_hearings_table_spec.rb
> +# frozen_string_literal: true
most of this file was ported over from `spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb` and left untouched

2020-09-24 18:44 UTC, rubaiyat22 commented on spec/feature/hearings/assign_hearings_table_spec.rb
> +  context "Hearing Request Type column" do
new tests from here down

2020-09-24 18:45 UTC, rubaiyat22 commented on spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
> +##
Only change in this file was to port some tests over to `spec/feature/hearings/assign_hearings_table_spec.rb`

2020-09-24 23:55 UTC, tomas-nava requested changes
This looks excellent!

I made a few suggestions, only one of which is blocking (show **"former Travel"** in the column instead of **"formally Travel"**). 

Related to that, though, I think we should replace **"formally"** everywhere with **"former"** or **"formerly"**, to be consistent with what we're displaying to the user. Unfortunately that includes columns in the `cached_appeal_attributes` table.

2020-09-24 23:55 UTC, tomas-nava commented on app/controllers/hearings/schedule_hearing_tasks_controller.rb
>      # of getting the value through the `Appeal` instance.
```suggestion
    # optimization that fetches these values from the `CachedAppeal` table,
    # where they are already cached for filtering. The `TaskColumnSerializer` is
    # "aware" of these optimizations, and will serialize the cached values instead
    # of getting them through the `Appeal` instance.
```

2020-09-24 23:55 UTC, tomas-nava commented on client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
> +      {isFormallyTravel ? <span>{`formally Travel, ${hearingRequestType}`}</span> : <span>{hearingRequestType}</span>}
```suggestion
      {isFormallyTravel ? <span>{`former Travel, ${hearingRequestType}`}</span> : <span>{hearingRequestType}</span>}
```
[the design](https://www.figma.com/proto/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=7050%3A20&scaling=min-zoom) shows this as "former Travel"

2020-09-24 23:55 UTC, tomas-nava commented on client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
> +      },
I like how you made this its own component.

2020-09-24 23:55 UTC, tomas-nava commented on spec/feature/hearings/assign_hearings_table_spec.rb
> +  context "Hearing Request Type column" do
could we have a simple test to validate that the columns display as expected for an AMA appeal as well?

2020-09-25 14:41 UTC, rubaiyat22 commented on spec/feature/hearings/assign_hearings_table_spec.rb
> +  context "Hearing Request Type column" do
Done!

2020-09-25 16:51 UTC, tomas-nava approved these changes
approve!

2020-09-25 18:00 UTC, merged