[WIP] Add filter by veteran ID to /jobs
department-of-veterans-affairs/caseflow pull request #15342
Opened 2020-09-29 02:54 UTC by meckilabritt-navapbc

Resolves #13359

### Description
Add a search field on the "Background Jobs" admin page to filter results by veteran file number.

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Search field added to the rendered page
- [ ] Async jobs controller handles the query by returning only the matching job(s)

### Testing Plan
1. Navigate to `/jobs`
2. In the search bar, input a veteran's file number
3. Verify that the results displayed on the job page are only for the veteran file number search input

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---
<img width="1271" alt="Screen Shot 2020-09-28 at 7 49 38 PM" src="https://user-images.githubusercontent.com/68879427/94507342-62ef4d80-01c4-11eb-89f1-c06774bf9e84.png">
|
Screen Shot 2020-09-28 at 7.49.27 PM

2020-10-06 13:56 UTC, nanotone commented on app/services/asyncable_jobs.rb
> +      jobs = jobs.select { |job| job.try(:veteran_file_number) == veteran_file_number }
I was wondering why, in your PR screenshots, each DecisionDocument was displayed with a veteran file number, even though the model doesn't have a `veteran_file_number`.

Turns out, in the `asyncable_ui_hash` method which serializes models to be sent to the frontend, somebody has already figured out a more [clever way](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/asyncable.rb#L255) of doing this try(). Wanna give that approach a go?

2020-10-06 14:33 UTC, nanotone commented on spec/feature/intake/jobs_search_spec.rb
> +  let(:dd) { create(:decision_document) }
Aha, I think I know why the tests are getting bounced from `/jobs` to `/help` -- it's because the user authentication line isn't actually getting evaluated. But the reason is subtle.

RSpec `let` blocks are only evaluated on-demand, i.e. when the value of the variable is needed by something else. `intake_user` is referenced by `hlr` and `hlr2`, but neither of those are referenced by any other code, so none of these will be evaluated.

Replacing `let` with `let!` will [force the block to be run](https://relishapp.com/rspec/rspec-core/v/3-7/docs/helper-methods/let-and-let) before the test.

2020-10-06 17:27 UTC, meckilabritt-navapbc commented on app/services/asyncable_jobs.rb
> +      jobs = jobs.select { |job| job.try(:veteran_file_number) == veteran_file_number }
Something like 
`jobs.select { |job| job.try(:veteran).try(:file_number) == veteran_file_number }`?

2020-10-06 18:09 UTC, nanotone commented on app/services/asyncable_jobs.rb
> +      jobs = jobs.select { |job| job.try(:veteran_file_number) == veteran_file_number }
Yep, that's precisely what I had in mind!

2020-10-06 22:27 UTC, meckilabritt-navapbc commented on spec/feature/intake/jobs_search_spec.rb
> +  let(:dd) { create(:decision_document) }
Will also fix how the factory since putting a binding.pry after `visit(jobs)` shows Veteran is listed as 'Unknown'

2020-10-07 20:11 UTC, nanotone requested changes
This looks pretty good overall!

There's a tricky edge case that I was able to produce by trying to apply both a klass filter and a veteran file number filter at the same time:
1. Load up a couple HLR jobs
2. Click on DecisionDocument filter -- it should show 0 jobs
3. Do a search for a veteran with one of those HLR jobs -- it should still show 0 jobs because the DecisionDocument filter is still on, but it shows the DecisionDocument filter with the matching HLR job:

<img width="747" src="https://user-images.githubusercontent.com/282869/95381979-f1478b80-08b6-11eb-9efd-05bf3bdd3ad7.png">

I think the easiest way to get around this is to clear the DecisionDocument filter when doing a veteran search. After all, if the user is searching for a specific veteran, there will typically only be a few results even without the klass filter.

2020-10-07 20:11 UTC, nanotone commented on client/app/asyncableJobs/pages/JobsPage.jsx
> +      noResultsMessage = <h2>'There are no pending jobs.'</h2>;
Probably don't need that extra pair of single quotes, in both L141 and L143.

2020-10-07 20:18 UTC, nanotone commented on spec/feature/intake/jobs_search_spec.rb
> +    fcontext "when Veteran file number is not associated with a job" do
Remember to remove the focus from this context as well.

Maybe we should have a Dangerbot warning whenever `fdescribe` and `fcontext` are seen in a spec file.

2020-10-08 05:03 UTC, meckilabritt-navapbc commented on client/app/asyncableJobs/pages/JobsPage.jsx
> +      noResultsMessage = <h2>'There are no pending jobs.'</h2>;
Noted. This is also why the test was probably failing

2020-10-08 05:07 UTC, meckilabritt-navapbc commented on spec/feature/intake/jobs_search_spec.rb
> +    fcontext "when Veteran file number is not associated with a job" do
Good catch. I think a dangerbot for focus blocks in tests would be a quick approach. How can that be added?

2020-10-14 17:52 UTC, nanotone reviewed
Nice! I really like how the overall structure of this turned out, and have just a few cosmetic comments.

@jcq Would you mind giving the frontend part of this a once-over? There's two tricky aspects of this:
- The same Rails route is used for the initial React-on-Rails page, and subsequent XHRs, which change the state of the page.
- The URL can't contain the query because PII, and therefore XHR is needed to transmit the query as a header instead.

Ideally we'd get rid of the React-on-Rails props and rely on XHR for all data, but I think that would be an extra chunk of work for some other time.

2020-10-14 17:52 UTC, nanotone commented on client/app/asyncableJobs/pages/JobsPage.jsx
> +      `Veteran file '${this.state.veteranFileNumber}'.`}</h2>;
JSX has a nifty way to deal with this kind of interpolation! Something like

```jsx
<h2>There are no pending jobs for Veteran file {this.state.veteranFileNumber}.</h2>
```

2020-10-14 17:52 UTC, nanotone commented on client/app/asyncableJobs/pages/JobsPage.jsx
> +    } else if (rowObjects.length === 0) {
`rowObjects.length === 0` appears in both `if`s here, and the second is in the `else` of the first, so perhaps this could benefit from a little reorganization.

How about the rowObjects check on the outside, and an if/else check for veteranFileNumber on the inside?

2020-10-14 17:52 UTC, nanotone commented on client/app/asyncableJobs/pages/JobsPage.jsx
> +      removeClassFilter: false
Maybe it's just me, but the name `removeClassFilter`, phrased as an imperative verb, is a bit confusing as a state variable. I see why it's needed, because `asyncableJobKlass` is set by React-on-Rails as a prop and can't be changed. Not sure what a better name would be, but maybe at least an explanatory comment could help here?

2020-10-14 17:58 UTC, meckilabritt-navapbc commented on client/app/asyncableJobs/pages/JobsPage.jsx
> +    } else if (rowObjects.length === 0) {
This makes sense! I'll refactor

2020-10-14 18:49 UTC, meckilabritt-navapbc commented on client/app/asyncableJobs/pages/JobsPage.jsx
> +      removeClassFilter: false
Perhaps `shouldRemoveClassFilter` is a clearer variable name?

2020-10-14 21:50 UTC, jcq commented
> Nice! I really like how the overall structure of this turned out, and have just a few cosmetic comments.
> 
> @jcq Would you mind giving the frontend part of this a once-over? There's two tricky aspects of this:
> 
> * The same Rails route is used for the initial React-on-Rails page, and subsequent XHRs, which change the state of the page.
> * The URL can't contain the query because PII, and therefore XHR is needed to transmit the query as a header instead.
> 
> Ideally we'd get rid of the React-on-Rails props and rely on XHR for all data, but I think that would be an extra chunk of work for some other time.

I guess my qualm/question would be how likely is it that we set aside time/space in the future to redo how the rest of the filtering is done? The UX implemented here for the veteran ID is so nice and responsive, it makes the rest of the filtering feel *REALLY* bad. 

Totally fine with going with whatever you all (or Sally) think is best, but I think it's worth it to just take this opportunity to just do all of the filtering via a unified AJAX search. My fear is if we don't, it might remain this way for years into the future. 🤷‍♀️

2020-10-14 22:44 UTC, nanotone commented
>Totally fine with going with whatever you all (or Sally) think is best, but I think it's worth it to just take this opportunity to just do all of the filtering via a unified AJAX search. My fear is if we don't, it might remain this way for years into the future. 🤷‍♀️

Okay, I think the way to go is to create a follow-up ticket for exactly this purpose, so that the current PR can be limited to implementing filter-by-ID. @meckilabritt-navapbc expressed interest in working on more React/Rails architecture stuff, so the current setup won't necessarily remain in place for years.

2020-10-14 22:46 UTC, nanotone approved these changes
:shipit: 🚀

2020-10-14 23:20 UTC, merged