Edit EP Claim Labels | Adds back "type" to request issue
department-of-veterans-affairs/caseflow pull request #15346
Opened 2020-09-29 17:38 UTC by Sjones352

Connects #15236

### Description
This pr adds  "type" to request issue so that we can hardcode whether the issue is a rating issue or a nonrating issue. It also backfills RequestIssue type to be "RequestIssue".

### Database Changes
*Only for Schema Changes*

* [x] String Type (added) for request_issues
* [x] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
(https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [x] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [x] #Backfill RequestIssue type to be "RequestIssue"
* [x] #Add type to request issue, with the default value of "RequestIssue"

2020-09-29 19:01 UTC, leikkisa approved these changes
Also tested the deployment in UAT

2020-09-29 19:09 UTC, nanotone requested changes
My overall concern is that there doesn't have to be two migrations, when a single one seems sufficient.

As UAT/preprod demonstrated earlier, when the second migration of a commit fails, weird things can happen. Additionally, I think we should be trying to avoid the intermediate situation of having a `type` column that hasn't yet been filled in with `RequestIssue`.

@yoomlam do you have opinions on this?

2020-09-29 19:09 UTC, nanotone commented on db/migrate/20200929170305_backfill_request_issue_type.rb
> +  def change
I know we're basing this off [prior art](https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/migrate/20200610001554_backfill_claimant_type.rb), but I don't actually think `change` is the right method here, since it's supposed to generate the rollback operation automatically. However, there is no rollback here.

So maybe this one should be `up`, and there there could be an empty `down` method?

2020-09-29 19:11 UTC, nanotone commented on db/migrate/20200929170305_backfill_request_issue_type.rb
> +  def change
Shortcut to the docs! https://guides.rubyonrails.org/active_record_migrations.html#using-the-change-method

2020-09-29 20:44 UTC, yoomlam commented on db/migrate/20200929170305_backfill_request_issue_type.rb
> +  def change
The PR template has this AC:
> * [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))

If a `def change` cannot be rollbacked to the exact DB state before the `migrate`, then the change should be split up into `up` and `down` methods. Even for simple changes, I had to that here:
https://github.com/department-of-veterans-affairs/caseflow/blob/54ca7c47ffb1c61c6bba54ca2f25f9f7e18845f4/db/migrate/20200904140217_change_special_issue_lists_comment.rb#L2-L11

2020-09-29 21:22 UTC, Sjones352 commented on db/migrate/20200929170305_backfill_request_issue_type.rb
> +  def change
@yoomlam and @yang so I did `rails db:rollback STEP=2` to rollback to recent master migration. Changed the name from type to request_issue_type. Lastly I did a `rake db:migrate:redo STEP=2` to run the last 2 migrations. I also double checked my local and I don't see any type error anymore. Please let me know if it is okay to merge.

2020-09-29 21:33 UTC, yoomlam commented on db/migrate/20200929170305_backfill_request_issue_type.rb
> +  def change
If the intent to use STI (mentioned [here](https://dsva.slack.com/archives/C2ZAMLK88/p1601387002024800?thread_ts=1601380220.018900&cid=C2ZAMLK88)), the column should be named `type` by convention.

2020-09-30 14:03 UTC, Sjones352 commented on db/migrate/20200929170305_backfill_request_issue_type.rb
> +  def change
@nanotone and @yoomlam  I think it's safe to merge this pr. Yesterday it was failing because the migration was wrong. It should have been `type` instead of request_issue_type on the Backfill migration. Sally has tested this pr in UAT and it's passing. If it fails in UAT once merged, we can revert the pr again.

2020-09-30 14:15 UTC, yoomlam commented on db/migrate/20200929170305_backfill_request_issue_type.rb
> +  def change
Since this kind of code has worked in the past and you have a backup plan to revert if needed, I say go for it!

2020-09-30 14:39 UTC, nanotone commented on db/migrate/20200929170305_backfill_request_issue_type.rb
> +  def change
>Since this kind of code has worked in the past
If we're in the habit of basing new code off similar past code, then I think it's equally important to make sure that this code is good to base future code off of. It's almost ready to merge, with a couple tweaks:

I ran `db:rollback` and saw the same change as roll-forward; i.e. set all types to RequestIssue. It's not broken, but could we please switch the `change` to an `up`, and add an empty `down` method? Unless somebody has an argument against doing so.

2020-09-30 14:43 UTC, nanotone commented
I'm also still curious as to why this should be two separate migrations (something subtle about transactions?) but it's fine to leave it as two.

2020-09-30 16:39 UTC, nanotone approved these changes
LGTM! 🚀

2020-09-30 17:00 UTC, merged