Added logic to prevent adding tasks to a dispatched appeal
department-of-veterans-affairs/caseflow pull request #15374
Opened 2020-10-02 16:48 UTC by sahalliburton

Resolves #15363 

### Description
Adds logic to prevent a ChangeHearingRequestTask from being created when visiting the case details page of a dispatched appeal.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. First open a rails console and locate a dispatched LegacyAppeal: `id=LegacyAppeal.all.select{|x| !x.active?}.first`
1. Next login as user `BVASYELLOW`
1. Visit the case details page for that appeal: `http://localhost:3000/queue/appeals/{id}`
1. Ensure that you do not get a dropdown for the change hearing request type

2020-10-05 20:12 UTC, ferristseng requested changes

2020-10-05 20:12 UTC, ferristseng commented on spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
> +    scenario "it does not create a ChangeHearingRequestTypeTask for dispatched appeals" do
This test is failing for me too locally. I think it's because the `status` is `nil`

```
[24] pry(#<TasksForAppeal>)> appeal.status
=> nil
```

`status` is a field on the VACOLS case, so the test setup might need to change to reflect that maybe?

2020-10-07 19:03 UTC, ferristseng approved these changes
LGTM! 🚢

2020-10-15 20:30 UTC, merged

2020-10-15 23:10 UTC, tomas-nava commented
I found a couple of cases where we had created tasks for dispatched appeals, and destroyed them:

```ruby
# find the cases
> ots = ChangeHearingRequestTypeTask.open
> las = ots.map(&:appeal)
> pp las.reject(&:active?).map { |la| "#{la.id}/#{la.vacols_id}: #{la.active?}" }
=> ["147397/2334469: false",
    "697335/3804638: false"]

# verify the first one
> la = LegacyAppeal.find(147397)
> la.treee(:id, :status, :created_at)
#                                              ┌───────────────────────────────────────────────┐
# LegacyAppeal 147397 (legacy) ─────────────── │ ID      │ STATUS    │ CREATED_AT              │
# └── RootTask                                 │ 1180498 │ on_hold   │ 2020-10-02 17:09:10 UTC │
#     └── HearingTask                          │ 1192955 │ on_hold   │ 2020-10-13 12:28:33 UTC │
#         └── ScheduleHearingTask              │ 1192956 │ on_hold   │ 2020-10-13 12:28:33 UTC │
#             └── ChangeHearingRequestTypeTask │ 1192957 │ assigned  │ 2020-10-13 12:28:33 UTC │
#                                              └───────────────────────────────────────────────┘

# destroy tasks on the first one
> Task.find(1192955).destroy!
> la.treee(:id, :status, :created_at)
#                               ┌───────────────────────────────────────────────┐
# LegacyAppeal 147397 (legacy)  │ ID      │ STATUS    │ CREATED_AT              │
# └── RootTask                  │ 1180498 │ on_hold   │ 2020-10-02 17:09:10 UTC │
#                               └───────────────────────────────────────────────┘

# verify the second one
> la = LegacyAppeal.find(697335)
> la.treee(:id, :status, :created_at)
#                                              ┌───────────────────────────────────────────────┐
# LegacyAppeal 697335 (legacy) ─────────────── │ ID      │ STATUS    │ CREATED_AT              │
# └── RootTask                                 │ 1140929 │ completed │ 2020-09-11 12:56:18 UTC │
#     └── HearingTask                          │ 1183192 │ on_hold   │ 2020-10-05 19:23:02 UTC │
#         └── ScheduleHearingTask              │ 1183193 │ on_hold   │ 2020-10-05 19:23:02 UTC │
#             └── ChangeHearingRequestTypeTask │ 1183194 │ assigned  │ 2020-10-05 19:23:02 UTC │
#                                              └───────────────────────────────────────────────┘

# destroy tasks on the second one
> Task.find(1183192).destroy!
> la.treee(:id, :status, :created_at)
#                               ┌───────────────────────────────────────────────┐
# LegacyAppeal 697335 (legacy)  │ ID      │ STATUS    │ CREATED_AT              │
# └── RootTask                  │ 1140929 │ completed │ 2020-09-11 12:56:18 UTC │
#                               └───────────────────────────────────────────────┘


# confirm that the appeals are still in the closed location
> VACOLS::Case.connection.exec_query("SELECT * FROM brieff WHERE bfkey = '2334469'").to_a.first["bfcurloc"]
=> "99"

> VACOLS::Case.connection.exec_query("SELECT * FROM brieff WHERE bfkey = '3804638'").to_a.first["bfcurloc"]
=> "99"
```

2020-10-16 23:29 UTC, tomas-nava commented
found one more that snuck in pre-merge
```ruby
# find the cases
> ots = ChangeHearingRequestTypeTask.open
> las = ots.map(&:appeal)
> pp las.reject(&:active?).map { |la| "#{la.id}/#{la.vacols_id}: #{la.active?}" }
["1221500/4042695: false"]

# verify
> la = LegacyAppeal.find(1221500)
> la.treee(:id, :status, :created_at)

                                             ┌───────────────────────────────────────────────┐
LegacyAppeal 1221500 (legacy) ────────────── │ ID      │ STATUS    │ CREATED_AT              │
├── RootTask                                 │ 935039  │ completed │ 2020-06-04 17:53:20 UTC │
│   └── HearingTask                          │ 1200574 │ on_hold   │ 2020-10-16 14:53:50 UTC │
│       └── ScheduleHearingTask              │ 1200575 │ on_hold   │ 2020-10-16 14:53:50 UTC │
│           └── ChangeHearingRequestTypeTask │ 1200577 │ assigned  │ 2020-10-16 14:53:50 UTC │
├── FoiaColocatedTask                        │ 990046  │ cancelled │ 2020-06-30 21:20:48 UTC │
│   └── FoiaTask                             │ 990047  │ cancelled │ 2020-06-30 21:20:48 UTC │
│       └── FoiaTask                         │ 1106412 │ cancelled │ 2020-08-21 16:06:36 UTC │
└── FoiaColocatedTask                        │ 1135701 │ completed │ 2020-09-09 15:31:50 UTC │
    └── FoiaTask                             │ 1135702 │ completed │ 2020-09-09 15:31:50 UTC │
        └── FoiaTask                         │ 1135978 │ completed │ 2020-09-09 17:12:55 UTC │
                                             └───────────────────────────────────────────────┘

# destroy
> Task.find(1200574).destroy!
> la.treee(:id, :status, :created_at)

                               ┌───────────────────────────────────────────────┐
LegacyAppeal 1221500 (legacy)  │ ID      │ STATUS    │ CREATED_AT              │
├── RootTask                   │ 935039  │ completed │ 2020-06-04 17:53:20 UTC │
├── FoiaColocatedTask          │ 990046  │ cancelled │ 2020-06-30 21:20:48 UTC │
│   └── FoiaTask               │ 990047  │ cancelled │ 2020-06-30 21:20:48 UTC │
│       └── FoiaTask           │ 1106412 │ cancelled │ 2020-08-21 16:06:36 UTC │
└── FoiaColocatedTask          │ 1135701 │ completed │ 2020-09-09 15:31:50 UTC │
    └── FoiaTask               │ 1135702 │ completed │ 2020-09-09 15:31:50 UTC │
        └── FoiaTask           │ 1135978 │ completed │ 2020-09-09 17:12:55 UTC │
                               └───────────────────────────────────────────────┘

# move to closed location
> VACOLS::Case.connection.exec_query("SELECT * FROM brieff WHERE bfkey = '4042695'").to_a.first["bfcurloc"]
=> "CASEFLOW"

> VACOLS::Case.batch_update_vacols_location(LegacyAppeal::LOCATION_CODES[:closed], ['4042695'])
> VACOLS::Case.connection.exec_query("SELECT * FROM brieff WHERE bfkey = '4042695'").to_a.first["bfcurloc"]
=> "99"
```