Edit EP Claim Labels | Add End Product Update model
department-of-veterans-affairs/caseflow pull request #15383
Opened 2020-10-06 14:57 UTC by Sjones352

Connects  #15330

### Description
This pr adds a new End Product Update table and model

### Acceptance Criteria
- [ ] DB migration to add EndProductUpdate
  - [ ] Timestamps
  - [ ] User ID
  - [ ] EndProductEstablishment ID
  - [ ] Original code
  - [ ] New code
  - [ ] Original decision review ID
  - [ ] Status (success/error)
  - [ ] Error
  - [ ] IDs of active request issues on the end product establishment

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR

2020-10-06 17:00 UTC, leikkisa reviewed
Added some comments on your comments ;-)

2020-10-06 21:49 UTC, nanotone reviewed
Bigger question: wouldn't we want EPU to be an Asyncable? Similar to all the other objects that track VBMS operations which might fail and need retries. In which case, the table would need a handful of Asyncable fields.

2020-10-06 21:49 UTC, nanotone commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.bigint :original_decision_review_id, comment: "The original ID of the decision review that this request issue belongs to"
It seems that you'd also want an `t.string :original_decision_review_type` field so that in Ruby you can just do `epu.original_decision_review`. Since decision reviews are stored in 3 separate tables.

2020-10-06 22:00 UTC, yoomlam requested changes
Some wording suggestions

2020-10-06 22:00 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.integer :active_request_issue_ids, null: false, comment: "An array of the active request issue IDs when a user has finished editing a decision review. Used to keep track of which request issu
```suggestion
      t.integer :active_request_issue_ids, null: false, array: true, comment: "A list of active request issue IDs when a user has finished editing a decision review. Used to keep track of which request issues may have been impacted by the update."
```

2020-10-06 22:39 UTC, leikkisa commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.bigint :original_decision_review_id, comment: "The original ID of the decision review that this request issue belongs to"
Oh yeah, that was an eng discussion piece since that's won't change if we create a new decision review (and then would be available on the EPE).  But I agree, it doesn't hurt to add it and it'll be more intuitive, and slot into Rails magic more easily.

2020-10-06 22:52 UTC, leikkisa reviewed
Adding some responses to other comments, and I also updated the AC on the original ticket to reflect comments, and also be specific about which values are nullable (let's put a null: false on the other ones).

I think it's also a good idea to add an index by updated_at.

2020-10-06 22:52 UTC, leikkisa commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.bigint :original_decision_review_id, comment: "The original ID of the decision review that this request issue belongs to"
That's a good question, down the road there's one type of edit that would result in creating a new decision review, and moving the end product establishment to the new one. We would only use this field if that happens.

2020-10-06 22:52 UTC, leikkisa commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.string :status, comment: "This shows whether the attempt to update the end product was successful or whether it resulted in an error"
Good comment, we've included possible values in comments in the past. Your shortlist is a good guess!

2020-10-06 22:52 UTC, leikkisa commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.string :error, comment: "The error captured if end product update has failed."
We're just using "error" elsewhere in the code, but I don't have a strong opinion on it. I'll add that this would be from BGS instead of VBMS.

2020-10-06 22:52 UTC, leikkisa commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.string :original_code, comment: "This is an original code before the update was submitted (just in case someone edits an end product twice)"
I don't think ` (in case someone edits an end product twice)` is really necessary in the comment.

2020-10-06 22:52 UTC, leikkisa commented on app/models/end_product_update.rb
> +class EndProductUpdate < ApplicationRecord
Don't forget to add the rails association here and in EndProductEstablishment so that we can easily access them.  The EndProductUpdate would be a `belongs_to` to the EndProductEstablishment, and EndProductEstablishment would have a `has_many` EndProductUpdates.

You could do the same for the `original_decision_review`

2020-10-06 23:23 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.bigint :original_decision_review_id, comment: "The original ID of the decision review that this request issue belongs to"
I see. How about this: 
```suggestion
      t.bigint :original_decision_review_id, comment: "The original ID of the decision review that this end product update belongs to; has a non-nil value only if a new decision_review was created."
```
Should there be a `new_decision_review_id` column (along with a `new_decision_review_type`)?

2020-10-06 23:24 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.string :error, comment: "The error captured if end product update has failed."
```suggestion
      t.string :error, comment: "The error message captured from BGS if the end product update failed."
```

2020-10-06 23:26 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.string :original_code, comment: "This is an original code before the update was submitted (just in case someone edits an end product twice)"
I concur.
```suggestion
      t.string :original_code, comment: "The original end product code before the update was submitted"
```

2020-10-07 15:18 UTC, nanotone requested changes
This is getting close! Added a couple more suggestions.

2020-10-07 15:18 UTC, nanotone commented on app/models/end_product_update.rb
> +  belongs_to :end_product_establishment
It would be useful to also have an `original_decision_review` association here, as @leikkisa suggested.

2020-10-07 15:18 UTC, nanotone commented on db/migrate/20201005190456_create_end_product_update.rb
> +class CreateEndProductUpdate < ActiveRecord::Migration[5.2]
One of the DB Migration checklist items is

>Have your migration classes inherit from `Caseflow::Migration`

It doesn't make a huge difference here, but would be nice to set a good example.

2020-10-07 15:18 UTC, nanotone commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.bigint :end_product_establishment_id, comment: "The end product establishment id used to track the end product being updated"
Is there any circumstance in which the EPE would be null? I can't think of any, and if not then this column could use a `null: false`.

2020-10-07 15:18 UTC, nanotone commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.bigint :end_product_establishment_id, comment: "The end product establishment id used to track the end product being updated"
Also, @yoomlam what do you think about strongly recommending that appropriate foreign keys be added when creating columns? I think it'd be nice to have them for `user_id` and `end_product_establishment_id` here.

2020-10-07 15:28 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.bigint :end_product_establishment_id, comment: "The end product establishment id used to track the end product being updated"
Agree. If we are 100% certain that an association must exist, then please add a foreign key: https://guides.rubyonrails.org/active_record_migrations.html#foreign-keys

2020-10-07 19:20 UTC, nanotone requested changes

2020-10-07 19:20 UTC, nanotone commented on db/schema.rb
> +  add_foreign_key "end_product_updates", "end_product_establishments", column: "end_product_establishment_id"
These lines need to be added to the migration itself, since this file is auto-generated.

When I run the migration locally, it deletes these two lines.

2020-10-07 19:20 UTC, nanotone commented on db/migrate/20201005190456_create_end_product_update.rb
> +class CreateEndProductUpdate < Caseflow::Migration[5.2]
`Caseflow::Migration` already [inherits a version](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/caseflow/migration.rb#L5) so the `[5.2]` is not needed.

2020-10-07 19:34 UTC, yoomlam commented
I like how [this article](https://semaphoreci.com/blog/2017/08/16/polymorphic-associations-in-rails.html) includes tests to ensure their polymorphic association migration works as desired.

2020-10-07 20:23 UTC, yoomlam commented
Did some playing around and came up with this (posting for future reference; commented out code shows the code I was able to remove):
```ruby
class CreateEndProductUpdate < Caseflow::Migration
  disable_ddl_transaction!  # See Note 2 below
  def change
    create_table :end_product_updates, comment: "Updates the claim label for end products established from Caseflow" do |t|
      # t.integer :user_id, comment: "The ID of the user who makes an end product update."
      # t.bigint :end_product_establishment_id, null: false, comment: "The end product establishment id used to track the end product being updated"
      # t.bigint :original_decision_review_id, null: false, comment: "The original ID of the decision review that this end product update belongs to; has a non-nil value only if a new decision_review was created."
      # t.string :original_decision_review_type, null: false, comment: "The original decision review type that this end product update belongs to"
      t.string :status, null: false, comment: "Status after an attempt to update the end product; expected values: 'success', 'error', ..."
      t.string :error, null: false, comment: "The error message captured from BGS if the end product update failed."
      t.string :original_code, comment: "The original end product code before the update was submitted"
      t.string :new_code, comment: "The new end product code the user wants to update to."
      t.integer :active_request_issue_ids, null: false, array: true, default: [], comment: "A list of active request issue IDs when a user has finished editing a decision review. Used to keep track of which request issues may have been impacted by the update."

      t.timestamps null: false

      t.references :user, null: false, foreign_key: true
      t.references :end_product_establishment, null: false, foreign_key: true
      # t.index ["user_id"], name: "index_end_product_updates_on_user_id"
      # t.index ["end_product_establishment_id"], name: "index_end_product_updates_on_end_product_establishment_id"

      # Note 1: polymorphic reference cannot have a foreign_key
      # Note 2: strong_migrations warns to create the index separately (below), so set 'index: false' here
      t.references :original_decision_review, null: false, polymorphic: true, index: false, references: :decision_review
    end

    # Adding index separately as strong_migrations suggests
    add_index :end_product_updates, [:original_decision_review_type, :original_decision_review_id], algorithm: :concurrently, name: "index_epupdates_on_decision_review_type_and_decision_review_id"

    # Could not set the comment when calling `t.references` above, so doing it here
    change_column_comment :end_product_updates, :original_decision_review_id, "The original ID of the decision review that this end product update belongs to; has a non-nil value only if a new decision_review was created."
    change_column_comment :end_product_updates, :original_decision_review_type, "The original decision review type that this end product update belongs to"
    change_column_comment :end_product_updates, :user_id, "The ID of the user who makes an end product update."
    change_column_comment :end_product_updates, :end_product_establishment_id, "The end product establishment id used to track the end product being updated"

    # Not needed due to `t.references` above
    # add_foreign_key "end_product_updates", "users", column: "user_id"
    # add_foreign_key "end_product_updates", "end_product_establishments", column: "end_product_establishment_id"
  end
end
```

Benefits:
* creates columns with correct types (e.g., `bigint user_id`)
* automatically add indices and `add_foreign_key`

2020-10-07 20:25 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.integer :user_id, comment: "The ID of the user who makes an end product update."
```suggestion
      t.bigint :user_id, comment: "The ID of the user who makes an end product update."
```

2020-10-07 20:26 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.integer :active_request_issue_ids, null: false, array: true, default: [], comment: "A list of active request issue IDs when a user has finished editing a decision review. Used to keep track o
```suggestion
      t.bigint :active_request_issue_ids, null: false, array: true, default: [], comment: "A list of active request issue IDs when a user has finished editing a decision review. Used to keep track of which request issues may have been impacted by the update."
```

2020-10-07 20:30 UTC, nanotone commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.integer :user_id, comment: "The ID of the user who makes an end product update."
I don't really mind either way, but why use bigint on foreign key fields where the foreign column (`user.id`) is just an integer?

2020-10-07 20:40 UTC, nanotone commented
@yoomlam In your suggested `t.references :original_decision_review` line, what does the `references: :decision_review` argument do? As far as I understand, it should have no effect for polymorphic references.

2020-10-07 20:41 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.integer :user_id, comment: "The ID of the user who makes an end product update."
I don't have a good reason except that Rails used `bigint` when I used `t.references :user, null: false, foreign_key: true` in https://github.com/department-of-veterans-affairs/caseflow/pull/15383#issuecomment-705173743

2020-10-07 20:45 UTC, yoomlam commented
> @yoomlam In your suggested `t.references :original_decision_review` line, what does the `references: :decision_review` argument do? As far as I understand, it should have no effect for polymorphic references.

It points to the table that `original_decision_review` is referring to. Leaving it out doesn't seem to change the resulting `schema.rb`, but it's nice to have that reference be explicit since the column has a different name.

2020-10-07 20:46 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.string :original_decision_review_type, null: false, comment: "The original decision review type that this end product update belongs to"
Based on the comment, these 2 columns can be null.
```suggestion
      t.bigint :original_decision_review_id, null: true, comment: "The original ID of the decision review that this end product update belongs to; has a non-nil value only if a new decision_review was created."
      t.string :original_decision_review_type, null: true, comment: "The original decision review type that this end product update belongs to"
```

2020-10-07 20:47 UTC, nanotone commented
>It points to the table that original_decision_review is referring to. Leaving it out doesn't seem to change the resulting schema.rb, but it's nice to have that reference be explicit since the column has a different name.

Yeah, that's my point: there is no original `decision_reviews` table, since it's polymorphic.

2020-10-07 20:50 UTC, yoomlam commented
> > It points to the table that original_decision_review is referring to. Leaving it out doesn't seem to change the resulting schema.rb, but it's nice to have that reference be explicit since the column has a different name.
> 
> Yeah, that's my point: there is no original `decision_reviews` table, since it's polymorphic.

Ah, right. Updated the code in my comment.

2020-10-07 21:33 UTC, Sjones352 commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.integer :user_id, comment: "The ID of the user who makes an end product update."
@yoomlam do I have run ```add_index :end_product_updates, [:original_decision_review_type, :original_decision_review_id], algorithm: :concurrently, name: "index_epupdates_on_decision_review_type_and_decision_review_id"``` outside of the change method because I am getting this error `PG::ActiveSqlTransaction: ERROR:  CREATE INDEX CONCURRENTLY cannot run inside a transaction block` Do I need to create new change method as suggested by `https://thoughtbot.com/blog/how-to-create-postgres-indexes-concurrently-in`

2020-10-07 21:35 UTC, Sjones352 commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.integer :user_id, comment: "The ID of the user who makes an end product update."
NVM, I had to include `disable_ddl_transaction!`

2020-10-07 22:00 UTC, yoomlam commented on db/migrate/20201005190456_create_end_product_update.rb
> +class CreateEndProductUpdate < ActiveRecord::Migration[5.2]
```suggestion
class CreateEndProductUpdate < Caseflow::Migration
```

2020-10-07 23:03 UTC, Sjones352 commented on db/migrate/20201005190456_create_end_product_update.rb
> +class CreateEndProductUpdate < ActiveRecord::Migration[5.2]
I changed this back toActiveRecord because of this comment here https://github.com/department-of-veterans-affairs/caseflow/pull/15383#discussion_r501253628

2020-10-07 23:08 UTC, nanotone commented on db/migrate/20201005190456_create_end_product_update.rb
> +class CreateEndProductUpdate < ActiveRecord::Migration[5.2]
Oh, my comment was more to say that you can just do

```ruby
class CreateEndProductUpdate < Caseflow::Migration
```

without the `[5.2]` at the end. I still think it's better to use `Caseflow::Migration` over `ActiveRecord::Migration[5.2]`.

2020-10-08 13:56 UTC, nanotone commented on db/migrate/20201005190456_create_end_product_update.rb
> +      t.string :error, null: false, comment: "The error message captured from BGS if the end product update failed."
One last nit from me: I noticed that you changed these from nullable to null:false. Not sure about `status`, but it seems that at least `error` should be nullable.

2020-10-08 15:28 UTC, nanotone approved these changes
Looks ready for :shipit: to me!

2020-10-08 15:35 UTC, yoomlam approved these changes
Nice!

2020-10-08 16:20 UTC, merged