Paula/15446 intake permissions
department-of-veterans-affairs/caseflow pull request #15516
Opened 2020-10-28 18:05 UTC by pbradin

Resolves #15446 

### Description
User story: As a Senior VSR, if I try to intake a new AMA form, I should be prevented from doing so.

### Acceptance Criteria
- [ ] Add a method in the BGS Service to fetch a user's security profile, default the application to "CASEFLOW" (see tech notes)
- [ ]  Add a method in the User class that fetches the user's security profile using the method above, and returns the user's job title, or nil
- [ ] New AC (added after testing) - rescue BGS::ShareError and BGS::PublicError and return nil. These are errors that can get returned with invalid inputs, or a user that doesn't have access to the system.
- [ ] During intake /intake, check if the current user's job title is "Senior Veterans Service Representative" and if so, return false for verify access, which will show the "Not authorized" screen
- [ ] Include screenshot(s) in the Github issue and update comments on the [Intake user-facing error alerts deck](https://docs.google.com/presentation/d/1zYdLPwTJ7aXqT4oR3l3p0sYarT64t0A5VxtY3lTf4fE/edit#slide=id.p)
- [ ] Update documentation: [Intake permissions](https://github.com/department-of-veterans-affairs/caseflow/wiki/Intake-Permissions)
- [ ] Add a feature test in "intake_spec"

2020-10-28 18:49 UTC, pbradin commented
Screenshot:
<img width="819" alt="intake_screenshot" src="https://user-images.githubusercontent.com/23639439/97482561-b1f7e200-192c-11eb-9768-a37a6e4b8a41.png">

2020-10-28 21:23 UTC, nanotone requested changes
This looks really good! All I had were a handful of nitpicks.

2020-10-28 21:23 UTC, nanotone commented on app/models/user.rb
> +    security_profile.dig(:job_title)
If security_profile is `nil` (meaning, one of those two BGS errors was rescued) then this will raise NoMethodError because `nil` doesn't have `dig`. If you use `&.`, the safe navigation operator, that'll catch this situation.

2020-10-28 21:23 UTC, nanotone commented on spec/models/user_spec.rb
> +        expect(user.deny_access_svsr).to eq(true)
There's a cute RSpec matcher for this: `expect(...).to be_truthy` 😉

2020-10-28 21:23 UTC, nanotone commented on app/models/user.rb
> +  end
Naming suggestion for this method: the User class alone doesn't care whether SVSR's should be denied access (to what?), it's Intake that cares. What if this method were just called `svsr?` -- that way `IntakesController#verify_access` is the class that knows SVSR's should be denied.

2020-10-28 21:23 UTC, nanotone commented on spec/models/user_spec.rb
> +      it "Senior Veterans Service Representative" do
RSpec convention is to make this line read like an English sentence (excluding the `do`). So the bit inside the quotes normally starts with a verb 🤷

2020-10-28 21:26 UTC, nanotone commented on app/services/external_api/bgs_service.rb
> +        applications: "CASEFLOW"
Oops, missed this on my first time around. `stations_id` and `applications` each have an extra "s", which is why CodeClimate is complaining about this method.

2020-10-29 16:36 UTC, leikkisa reviewed
I agree with Yang's comments - this looks really good! Just some minor comments, and fixing Code climate.

2020-10-29 16:36 UTC, leikkisa commented on app/models/user.rb
> +    security_profile.dig(:job_title)
Or you could return an empty object `{ }` instead of nil

2020-10-29 16:36 UTC, leikkisa commented on app/models/user.rb
> +  end
I like Yang's suggestion. Also, elsewhere in the User model the pattern is more like "can_do_something?".  So you could make a method like "can_intake_decision_reviews?" or something along those lines.

2020-10-29 20:58 UTC, pbradin commented on app/models/user.rb
> +  end
would something like this work?  Adding on to the "intake_user?" method?
`def intake_user?`
`    roles && (roles.include?("Mail Intake") || roles.include?("Admin Intake")) || (!roles.include?("Senior Veterans Service Representative"))`
`end`
Or a completely new method?

2020-10-29 20:59 UTC, pbradin commented on spec/models/user_spec.rb
> +        expect(user.deny_access_svsr).to eq(true)
be_truthy... looks much cleaner that way

2020-10-29 21:00 UTC, pbradin commented on app/services/external_api/bgs_service.rb
> +        applications: "CASEFLOW"
oops, thanks!

2020-10-29 21:14 UTC, nanotone commented on app/models/user.rb
> +  end
`intake_user?` is used by other parts of the codebase (i.e. the IDT API) so I'm hesitant to fiddle with it. Sally's suggestion of `can_intake_decision_reviews?` sounds good, and it'd be fine just to invert this `deny_access_svsr` method and rename it.

2020-10-30 19:25 UTC, pbradin commented on app/models/user.rb
> +    security_profile.dig(:job_title)
returning empty object

2020-10-30 20:08 UTC, pbradin commented on app/models/user.rb
> +  end
changed deny_access_svsr to be a can_intake_decision_reviews? method and inverted it a bit

2020-10-30 20:09 UTC, pbradin commented on spec/models/user_spec.rb
> +        expect(user.deny_access_svsr).to eq(true)
changed method so check is now for falsey

2020-10-30 22:40 UTC, nanotone approved these changes
Looks good! I'm ✅ but with a couple suggestions:

- One note about the unused variable warning, in BGSService
- Before you add the `Ready to merge` label, could you update the PR title to just be a short phrase? It helps tidy up the final commit log, which shows up in #appeals-deployment

2020-10-30 22:40 UTC, nanotone commented on app/services/external_api/bgs_service.rb
> +  def get_security_profile(username:, station_id:, application: "CASEFLOW")
A couple of the CodeClimate complaints are due to the fact that `application` is a variable up here, but it never gets used because it's a hash key (I think?) down on line 239. Since this is the Caseflow repo, it's probably fine to just leave out the variable here, so the value is always "CASEFLOW".

2020-11-02 16:27 UTC, pbradin commented on app/services/external_api/bgs_service.rb
> +  def get_security_profile(username:, station_id:, application: "CASEFLOW")
So quick question here:  CodeClimate also complained about "station_id" for the same reason.  So would I leave that variable out too?  Like this?
`def get_security_profile(username:)`

2020-11-02 20:25 UTC, nanotone commented on app/services/external_api/bgs_service.rb
> +  def get_security_profile(username:, station_id:, application: "CASEFLOW")
Rubocop and Reek raise two equivalent complaints about `station_id` in the fakes file. I don't see it complaining about `station_id` in this file though, so you can leave it.

It's normal for a fake implementation to disregard some of its arguments. To shush the linters, prepend the names of the unused arguments with `_`, e.g. for `_benefit_type` [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/fakes/bgs_service.rb#L177)

2020-11-04 20:02 UTC, leikkisa commented
@pbradin Okay - tested in UAT! It's good to go 👍 . Updating the branch should fix the Rspec test.

2020-11-04 21:20 UTC, merged

2020-12-15 15:50 UTC, yoomlam commented on app/models/user.rb
> +    BGSService.new.get_security_profile(
Should a new BGSService be created every time or should this be memoized?

2020-12-15 16:41 UTC, nanotone commented on app/models/user.rb
> +    BGSService.new.get_security_profile(
`BGSService.new` is pretty cheap; as far as I can tell, the only work it does is check that `RequestStore[:current_user]` has a usable value. There are a bunch of places where we create a new instance every time, i.e. any time a model uses the `BgsService` concern.