Update Cache job runtime fixes
department-of-veterans-affairs/caseflow pull request #15577
Opened 2020-11-05 03:50 UTC by rubaiyat22

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2020-11-06 15:33 UTC, rubaiyat22 commented on spec/jobs/update_cached_appeals_attributes_job_spec.rb
> -          allow(bgs).to receive(:fetch_person_by_ssn)
it no longer makes a call to `fetch_person_by_ssn` to get the file number

2020-11-06 16:38 UTC, yoomlam requested changes
First pass of suggestions. Will continue to ponder improving the overall flow.

2020-11-06 16:38 UTC, yoomlam commented on app/services/cached_appeal_service.rb
> +  end
3 suggestions. 
* rename method for clarity
* shorten Task query
* more efficient array appending: https://stackoverflow.com/questions/1801516/how-do-you-add-an-array-to-another-array-in-ruby-and-not-end-up-with-a-multi-dim
```suggestion
  def append_appeals_with_open_schedule_hearing_tasks(appeal_ids, appeal_type)
    appeal_ids_with_open_sched_hearing_task = ScheduleHearingTask.open
      .where(appeal_id: appeal_ids, appeal_type: appeal_type)
      .pluck(:appeal_id)
      .uniq
    appeal_ids_with_schedule_hearing_tasks.push(*appeal_ids_with_open_sched_hearing_task)
  end
```

2020-11-06 16:38 UTC, yoomlam commented on app/services/cached_appeal_service.rb
> +  end
Wondering if you can pass this around as a local variable (and as an argument to methods) rather than storing this instance variable as the state of this service.

2020-11-06 16:38 UTC, yoomlam commented on app/services/cached_appeal_service.rb
> +    warning_msgs << "#{LegacyAppeal.name} #{appeal_id}: #{error}" if warning_msgs.count < 100
```suggestion
    warning_msgs << "LegacyAppeal #{appeal_id}: #{error}" if warning_msgs.count < 100
```

2020-11-06 16:38 UTC, yoomlam commented on app/services/cached_appeal_service.rb
> -    bgs_poa&.representative_name || appeal.representative_name
`RequestStore.store[:application]` returns `queue_job` if manually running in prod's Rails console. See https://github.com/department-of-veterans-affairs/caseflow/issues/15416#issuecomment-715438940

2020-11-06 16:38 UTC, yoomlam commented on app/services/cached_appeal_service.rb
> +  def map_vacols_id_to_appeal_id(legacy_appeals)
Rename method to reflect that it is change this service's state
```suggestion
  def append_vacols_id_appeal_id_mapping(legacy_appeals)
```

2020-11-06 16:51 UTC, rubaiyat22 commented on app/services/cached_appeal_service.rb
> +  end
yes i thought about that as well. i don't like having this as state of the service either but i was going back and forth because it requires passing this as parameter to multiple methods. I can definitely make those changes though

2020-11-06 16:55 UTC, yoomlam commented on app/services/cached_appeal_service.rb
> +  end
If you don't mind converting it into a local variable, that will make [the refactor](https://dsva.slack.com/archives/CJL810329/p1604681399114800?thread_ts=1604675634.111000&cid=CJL810329) easier.

2020-11-06 17:22 UTC, yoomlam commented on app/services/cached_appeal_service.rb
> +  end
I also think there's a potential problem. Both `cache_ama_appeals` (for AMA) and `cache_legacy_appeal_postgres_data`/`cache_legacy_appeal_vacols_data` (for Legacy) call `append_appeals_with_open_schedule_hearing_tasks`, which only stores the `appeal_id` without the `appeal_type`. This means that AMA and Legacy appeal ids are clashing with each other. If `cache_ama_appeals` is called first, there will be AMA appeal ids in `appeal_ids_with_open_sched_hearing_task` when either of the Legacy methods are called, so there will be extra (AMA) appeal ids that are not relevant to Legacy appeals.

2020-11-06 17:38 UTC, yoomlam commented on spec/services/cached_appeal_service_spec.rb
> +  context "does not cache hearing related fields in the absence of an open ScheduleHearingTask" do
```suggestion
  context "in the absence of an open ScheduleHearingTask" do
```

2020-11-06 17:39 UTC, yoomlam commented on spec/services/cached_appeal_service_spec.rb
> +      it "does not cache hearing related fields", :aggregate_failures do
TIL: `aggregate_failures`  Nice!

2020-11-06 22:43 UTC, rubaiyat22 commented on app/services/cached_appeal_service.rb
> +  end
I converted both `appeal_ids_with_schedule_hearing_tasks` and `vacols_id_to_appeal_id_mapping` into local variables so this should not be an issue anymore

2020-11-09 17:29 UTC, yoomlam approved these changes
1 consideration but LTGM!

2020-11-09 17:29 UTC, yoomlam commented on app/services/cached_appeal_service.rb
> +  end
Consider deleting this method since it is only called once and is only 1 line of code.

2020-11-09 22:55 UTC, merged