Only allocate CO dockets once per week
department-of-veterans-affairs/caseflow pull request #15593
Opened 2020-11-10 15:56 UTC by rubaiyat22

Resolves https://vajira.max.gov/browse/CASEFLOW-252

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2020-11-10 19:01 UTC, ferristseng commented on spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
> +        expect(subject.count).to eq(25) # 26 wednesdays between 2018-04-01 and 2018-09-30; 1 holiday on Wed, July 4
Should we pick a different CO day if the Wednesday falls on a holiday for the week?

2020-11-10 19:17 UTC, rubaiyat22 commented on spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
> +        expect(subject.count).to eq(25) # 26 wednesdays between 2018-04-01 and 2018-09-30; 1 holiday on Wed, July 4
i think we should!

2020-11-10 19:20 UTC, rubaiyat22 commented on spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
> +        expect(subject.count).to eq(25) # 26 wednesdays between 2018-04-01 and 2018-09-30; 1 holiday on Wed, July 4
this will require a bit more work but i can do that and tag you back

2020-11-10 19:22 UTC, ferristseng commented on spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
> +        expect(subject.count).to eq(25) # 26 wednesdays between 2018-04-01 and 2018-09-30; 1 holiday on Wed, July 4
excellent, thank you! everything else looks great!

2020-11-10 21:43 UTC, rubaiyat22 commented on spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
> +        expect(subject.count).to eq(25) # 26 wednesdays between 2018-04-01 and 2018-09-30; 1 holiday on Wed, July 4
made those changes

2020-11-10 22:33 UTC, ferristseng requested changes
I think I found an edge case and noted some other small tweaks.

Regrading the edge case, I noticed in one of the tests, the schedule period ends on a Thursday, so I'm wondering if it's possible to have a schedule period end on any day of the week? If so, I think the edge case I mention is worth raising to St*ve, and getting input on from the Board.

2020-11-10 22:33 UTC, ferristseng commented on app/services/hearing_schedule/generate_hearing_days_schedule.rb
> +      if CO_DAYS_OF_WEEK.include?(scheduled_for.cwday) && holiday?(scheduled_for)
I think this should also check if `co_not_available?`. We could also do a sanity check here for `weekend?` but that might not be totally necessary.

2020-11-10 22:33 UTC, ferristseng commented on app/services/hearing_schedule/generate_hearing_days_schedule.rb
> +      if CO_DAYS_OF_WEEK.include?(scheduled_for.cwday) && holiday?(scheduled_for)
There might be an edge case here that this doesn't handle if the end of the schedule period ends on a date that is before Wednesday (Monday or Tuesday). I'm not sure if this would ever come up in practice, but it might be good to still code for.

This also could be a non-issue because the Wednesday would appear in the subsequent schedule period...but then the date arithmetic logic in `get_fallback_date_for_co` might need to be bounded to the schedule period.

2020-11-10 22:33 UTC, ferristseng commented on spec/controllers/hearings/schedule_periods_controller_spec.rb
> +      expect(JSON.parse(response.body)["hearings"].size).to eq(365)
I was trying to calculate why this went from 427 => 365. I think this should be 364?

21 weeks between 2018-01-01 and 2018-06-01
3 fewer days per week
21 * 3 = 63
427 - 63 = 364

I assumed the 365 was due to a Wednesday holiday before, but it looks like the tests are still passing

2020-11-12 15:44 UTC, rubaiyat22 commented on spec/controllers/hearings/schedule_periods_controller_spec.rb
> +      expect(JSON.parse(response.body)["hearings"].size).to eq(365)
here's the calculation that i did which returned 364
previously before this change there were 68 invalid dates (meaning `valid_day_to_schedule_co(scheduled_for)` returned false; collected by running the loop)
there are 152 weekdays in total between 2018-01-01 and 2018-06-01 (https://www.timeanddate.com/date/workdays.html?d1=1&m1=1&y1=2018&d2=1&m2=6&y2=2018&ti=on&) 
152 - 68 = 84 
there are 22 wednesdays between 2018-01-01 and 2018-06-01
84 - 22 = 62 
62 is the total number of difference between prev and current version
let me know if you'd like to look at this together

2020-11-12 17:26 UTC, rubaiyat22 commented on app/services/hearing_schedule/generate_hearing_days_schedule.rb
> +      if CO_DAYS_OF_WEEK.include?(scheduled_for.cwday) && holiday?(scheduled_for)
Spoke to Steve and we decided this is fine as is for now

2020-11-13 15:42 UTC, ferristseng commented on spec/controllers/hearings/schedule_periods_controller_spec.rb
> +      expect(JSON.parse(response.body)["hearings"].size).to eq(365)
ok, I think this math checks out. I think I was not accounting for 22 wednesdays!

2020-11-13 15:45 UTC, ferristseng commented on app/services/hearing_schedule/generate_hearing_days_schedule.rb
> +
I think there still needs to be a check here to ensure that fallback date falls within the schedule period. The example is if the schedule period starts on a Thursday, the fallback date could be computed as Monday, due to the call to `beginning_of_week`

2020-11-13 16:15 UTC, ferristseng approved these changes
🚢 LGTM!

2020-11-13 17:35 UTC, merged