CAVC Remand: Litigation Support Form (Front End)
department-of-veterans-affairs/caseflow pull request #15597
Opened 2020-11-10 21:38 UTC by ajspotts

Resolves #14795

### Description
Creates a new Post-dispatch actions area on the Case Details page which houses the Add Cavc Remand option.  This option is only available to member of the `CavcLitigationSupport` org and is also hidden behind the `cavc_remand` feature toggle.

Also creates the new Cavc Intake Form, which in conjunction with the work completed in #15351 and #15469 will allow Cavc litigation users to create a new Cavc appeal stream.

### Acceptance Criteria
- [ ] Please put this work behind the feature toggle: CAVC_Remand
- [ ] This feature should be accessible to the following user groups: Litigation Support
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Start CAVC Remand Documentation to describe what cavc remand features caseflow supports (to be updated as more cavc functionality is added)
- [ ] Add CAVC Court Order Button to Case Details page of a Dispatched/Completed appeal that presents the form in a new top section
- [ ] Litigation Support user can add receipt date to the form
- [ ] Litigation Support user can designate the type of remand (JMR, JMPR) on the form 
- [ ] Litigation Support user can enter dates for
  - [ ] Court decision
  - [ ] Judgement 
  - [ ] Mandate
- [ ] Litigation Support user can select issues required to be decided on in the new appeal stream
- [ ] Confirmation Modal appears with the following copy when the form is completed & submitted (confirmation message may not be true at the end of this ticket until new appeal stream and 90 day letter task portions have been implemented): 
        - You have successfully created a CAVC Remand case
           This has generated a Send 90 Day Letter task in your team's queue
- [ ] Ensure users can copy and paste values from the cavc website without modifying data (see [here](https://github.com/department-of-veterans-affairs/caseflow/issues/14795#issuecomment-722592391) for how to get to the publicly available records)

### Testing Plan
1. Go to ...

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

2020-11-17 22:23 UTC, hschallhorn commented on app/controllers/cavc_remands_controller.rb
> +    cavc_remand = CavcRemand.create!(create_params)
We were not actually creating the remand, need a ! or a save!

2020-11-17 22:23 UTC, hschallhorn commented on app/controllers/cavc_remands_controller.rb
> +    render json: { cavc_remand: cavc_remand, cavc_appeal: cavc_appeal }, status: :created
Add the newly created appeal to the response

2020-11-17 22:23 UTC, hschallhorn commented on app/controllers/cavc_remands_controller.rb
> +      msg = "Only CAVC Litigation Support users can create CAVC Remands"
Limit to cavc lit support

2020-11-17 22:24 UTC, hschallhorn commented on app/controllers/cavc_remands_controller.rb
> +    params.permit(required_params).merge(params.permit(decision_issue_ids: []))
Mild clean up to help debug errors

2020-11-17 22:24 UTC, hschallhorn commented on app/views/queue/index.html.erb
> +      cavc_remand: FeatureToggle.enabled?(:cavc_remand, user: current_user)
Make sure our front end can read our toggles!

2020-11-17 22:31 UTC, hschallhorn requested changes
Some initial reviewing

2020-11-17 22:31 UTC, hschallhorn commented on client/app/queue/AddCavcRemandView.jsx
> +    showErrorMessage,
TODO: es lint was very unhappy about these two as they were conflicting with https://github.com/department-of-veterans-affairs/caseflow/pull/15597/files#diff-b85b25230374ea05c80f39f554df6373cfd640c751c1d4c1006729284730821aR14

2020-11-17 22:31 UTC, hschallhorn commented on client/app/queue/AddCavcRemandView.stories.js
> +export const Default = Template.bind({});
TODO: Get storybook up and running

2020-11-17 22:31 UTC, hschallhorn commented on client/app/queue/CaseDetailsView.jsx
> +  const appealIsDispatched = tasks.some((task) => task.type === 'BvaDispatchTask' && task.closedAt !== null);
we should have access to appeal here. appeal.status === "dispatched"

2020-11-17 22:31 UTC, hschallhorn commented on client/app/queue/PostDispatch.jsx
> +const PostDispatch = (props) => {
Can we name this something more descriptive? Like CaseDetailsPostDispatchActions?

2020-11-17 22:31 UTC, hschallhorn commented on spec/controllers/cavc_remands_controller_spec.rb
> -          params.delete(:cavc_docket_number)
Was mucking with params in other tests, simply set to nil instead

2020-11-17 22:32 UTC, hschallhorn commented on spec/controllers/cavc_remands_controller_spec.rb
> +          cavc_count = Appeal.court_remand.count
ensure we're actually creating the remand and appeal

2020-11-17 22:32 UTC, hschallhorn commented on spec/controllers/cavc_remands_controller_spec.rb
> +    let(:appeal_id) { appeal.uuid }
the controller actually expects the uuid, not id

2020-11-17 22:33 UTC, hschallhorn commented on app/controllers/cavc_remands_controller.rb
> +    params.merge!(created_by_id: current_user.id, updated_by_id: current_user.id, appeal_id: appeal.id)
override the provided appeal id as it is actually the uuid

2020-11-17 22:34 UTC, hschallhorn commented on app/controllers/cavc_remands_controller.rb
> +    @appeal ||= Appeal.find_by_uuid(params[:appeal_id])
This was creating a legacy case any time the Appeal was not found : (

2020-11-18 15:29 UTC, hschallhorn commented on app/controllers/cavc_remands_controller.rb
> +    ]
Mild clean up to help debug errors

2020-11-18 15:31 UTC, hschallhorn commented on app/models/cavc_remand.rb
> +  validates :represented_by_attorney, inclusion: { in: [true, false] }
`presence: true` checks `.blank?` (not `.nil?` as I thought) which is true for false. using inclusion is the preferred way to check for presence of a boolean

2020-11-18 15:32 UTC, hschallhorn commented on app/models/cavc_remand.rb
> +  validate :decision_issue_ids_match_appeal_decision_issues, if: -> { remand? && jmr? }
Don't just check subtype here, ensure type is remand as well

2020-11-19 14:37 UTC, hschallhorn commented on spec/feature/queue/cavc_task_queue_spec.rb
> +        expect(page).to have_content COPY::CAVC_INSTRUCTIONS_ERROR
Thinking validating fields and hiding/showing remand types (below) could be pulled out into jest testing as they don't rely on being integrated with the back end is is more testing how the component acts. thoughts?

2020-11-19 14:37 UTC, hschallhorn commented on spec/feature/queue/cavc_task_queue_spec.rb
> +        expect(page).to have_content COPY::CAVC_SUB_TYPE_LABEL
the aforementioned below!

2020-11-19 16:04 UTC, ajspotts commented on spec/feature/queue/cavc_task_queue_spec.rb
> +        expect(page).to have_content COPY::CAVC_INSTRUCTIONS_ERROR
Agreed! Checking form values & toggle show behavior are 💯 limited to FE and imo are perfect for Jest testing

2020-11-20 19:17 UTC, hschallhorn commented on client/test/data/stores/queueStore.js
> +    }
Resolves some errors using this mocked data with queue flow page

2020-11-20 19:18 UTC, hschallhorn commented on client/test/data/appeals.js
> +  ],
add some decision issues to our mocked data to be displayed in storybook and tested with jest

2020-11-20 19:20 UTC, hschallhorn commented on client/test/app/queue/AddCavcRemandView.test.js
> +    expect(cavcForm).toMatchSnapshot();
auto generates [snapshot](https://github.com/department-of-veterans-affairs/caseflow/pull/15597/files#diff-dbc421c3938295ad63dfa0d98265f07a3d8c454f36e4fe4df7108e6ea236cbd5) to be compared to future runs of the test. Snapshot may need to be `rm`'d and regenerated if the ui change

2020-11-20 19:20 UTC, hschallhorn commented on client/constants/CAVC_JUDGE_FULL_NAMES.json
> +  "William S. Greenberg"
sorted!

2020-11-20 19:31 UTC, hschallhorn commented on client/app/styles/react/_select-dropdown.scss
> +    max-width: 46rem;
matches the max width for our other inputs across caseflow. (wowee was this fun to track down: https://github.com/uswds/uswds/blob/918d0f6bdc41d542ebaead106d7e7584fedcc378/src/stylesheets/components/_forms.scss#L46)

BEFORE|AFTER
---|---
<img width="681" alt="Screen Shot 2020-11-20 at 1 03 48 PM" src="https://user-images.githubusercontent.com/45575454/99842000-0f064280-2b3d-11eb-84c6-0a5d58c78f80.png">|<img width="682" alt="Screen Shot 2020-11-20 at 1 03 34 PM" src="https://user-images.githubusercontent.com/45575454/99842001-0f064280-2b3d-11eb-9745-84ddf1494cc1.png">

2020-11-25 19:30 UTC, hschallhorn commented on client/test/app/hearings/components/__snapshots__/HearingTypeConversion.test.js.snap
> +      ],
All these snapshot diffs are due to changing the default data these tests use https://github.com/department-of-veterans-affairs/caseflow/pull/15597/files#diff-f1851bcb163b04e5f9699bf9cb9feaafb8b9f6c1a8879317cab0381e9053a999R73-R81

2020-11-26 16:25 UTC, hschallhorn commented on client/app/queue/AddCavcRemandView.jsx
> +        remand_subtype: type === CAVC_DECISION_TYPES.remand ? subType : null,
don't pass subtype to the back end if remand is not selected

2020-11-26 16:25 UTC, hschallhorn commented on client/app/queue/AddCavcRemandView.jsx
> +      {type === CAVC_DECISION_TYPES.remand && remandTypeField }
do not show remand type selection if type is not remand

2020-11-26 16:27 UTC, hschallhorn commented on client/test/app/queue/AddCavcRemandView.test.js
> +    expect(cavcForm).toMatchSnapshot();
Just kidding! `jest --updateSnapshot` is the way to go!

2020-11-26 16:42 UTC, hschallhorn commented on client/test/data/stores/queueStore.js
> +    modals: {}
Resolves some errors using this mocked data with queue flow page

2020-11-26 16:43 UTC, hschallhorn commented on client/test/data/stores/queueStore.js
> +      },
sets the ui initial state!

2020-11-26 17:31 UTC, hschallhorn commented on spec/feature/queue/users_management_spec.rb
> +        expect(page).to have_content(COPY::USER_MANAGEMENT_DROPDOWN_TEXT)
fixes flake from the addition of select-dropdown [width limit](https://github.com/department-of-veterans-affairs/caseflow/pull/15597/files#r527927054)

2020-11-26 18:21 UTC, hschallhorn commented on spec/feature/queue/users_management_spec.rb
> +        visit "/user_management"
I swear this flake will be the end of me.

2020-11-26 18:22 UTC, hschallhorn commented on spec/feature/queue/users_management_spec.rb
> +        visit "/user_management"
fixes flake from the addition of select-dropdown [width limit](https://github.com/department-of-veterans-affairs/caseflow/pull/15597/files#r527927054)

2020-11-30 17:43 UTC, hschallhorn commented on client/test/app/queue/AddCavcRemandView.test.js
> +    expect(cavcForm).toMatchSnapshot();
https://jestjs.io/docs/en/snapshot-testing

2020-12-03 16:46 UTC, hschallhorn commented on client/app/queue/AddCavcRemandView.jsx
> +}));
Currently includes all types. Do we want to break out death dismissal and straight reversal?

2020-12-03 16:47 UTC, hschallhorn commented on client/app/queue/AddCavcRemandView.jsx
> +}));
Currently includes all subtypes. Should we break out mdr?

2020-12-03 18:26 UTC, lomky commented on client/app/queue/AddCavcRemandView.jsx
> +import _ from 'lodash';
Instead of importing all of lodash, we should grab the functions we need! (thanks @jcq!)

2020-12-03 20:34 UTC, ajspotts commented on client/app/queue/AddCavcRemandView.jsx
> +}));
Were you thinking of doing this by adding logic to conditionally render based on type?  I don't believe we can remove them from the constants file as they're being utilized in other places.  Alternatively we could just not use the constants file.

2020-12-03 20:34 UTC, ajspotts commented on client/app/queue/AddCavcRemandView.jsx
> +}));
Same question as above

2020-12-03 22:27 UTC, hschallhorn commented on client/app/queue/AddCavcRemandView.jsx
> +}));
Could easily filter out these options as well by checking a feature toggle passed to the front end. Or pass supported types to the front end. Definitely not remove them from constants. Passing supported types to the front end would also give us a nice function to validate on when creating the actual remand. Thought this PR is getting a little long.

2020-12-07 14:51 UTC, lomky commented
Testing notes:

 - The vet suggested only has dispatched appeals already remanded. instead I created a dispatched appeal with request and decision issues:
```ruby
FactoryBot.create(:request_issue, 
                  :with_rating_decision_issue, 
                  decision_review: FactoryBot.create(:appeal, :dispatched),
                  veteran_participant_id: "123",  
                  contested_rating_issue_profile_date: Time.zone.today)
```

2020-12-07 15:08 UTC, lomky approved these changes
:astonished: :tada: :shipit:

2020-12-07 16:15 UTC, merged