add JudgeTeam admin method
department-of-veterans-affairs/caseflow pull request #15696
Opened 2020-12-15 17:23 UTC by ajspotts

Resolves #13993

### Description
When queried, a JudgeTeam object should be aware that there is only a single admin for the team, and that admin is the judge lead. 

### Acceptance Criteria
- [ ] Tests pass

### Testing Plan
Tests pass

2020-12-15 22:33 UTC, ajspotts commented on app/models/organizations/judge_team.rb
> +  end
our new method, simply allowing our code to query JudgeTeams for the team admin

2020-12-15 22:34 UTC, ajspotts commented on app/models/organizations_user.rb
> +  end
helper method to check if we are dealing with a JudgeTeam with an admin

2020-12-15 22:35 UTC, ajspotts commented on app/models/organizations_user.rb
> +      end
check if the org is a previously created JudgeTeam (which by default is created with an admin), if so we return an error

2020-12-15 22:35 UTC, ajspotts commented on client/COPY.json
> +  "JUDGE_TEAM_ADMIN_ERROR": "Cannot add more than one admin to a judge team",
new error message for attempting to add an additional admin to JudgeTeam

2020-12-16 00:51 UTC, ajspotts commented on spec/models/user_spec.rb
> +        allow(judge).to receive(:judge_in_vacols?).and_return(false)
test previously created a second admin for the JudgeTeam which we no longer allow, updated to check for the single admin

2020-12-16 23:21 UTC, n1zyy commented on app/models/organizations/dvc_team.rb
> +  alias admin dvc
Not obvious from this, but `dvc` above this is `admins.first` which is the same implementation as in JudgeTeam.

2020-12-16 23:21 UTC, n1zyy commented on spec/models/organizations/dvc_team_spec.rb
> +        expect(DvcTeam.first.admin).to eq(dvc)
I was torn on whether to change these or not. But moving them to `.admin` gets us normalized on that being the pattern, and still implicitly tests `admins.first` since that's the literal implementation of the method.

2020-12-16 23:21 UTC, n1zyy commented on app/models/organizations/dvc_team.rb
> +  alias admin dvc
This is vaguely out of scope. We'd initially looked at whether DvcTeam and JudgeTeam were sufficiently similar to be descent from a new superclass under Organization, but they don't seem to have a whole lot in common. But we can still make `admin` a standard between them.

2020-12-18 20:02 UTC, hschallhorn commented on app/models/organizations_user.rb
> +      end
Do we want to add an additional validation for DVC teams or is that out of scope?

2020-12-18 20:05 UTC, hschallhorn requested changes
We're ensuring other users cannot be made an admin of a judge team with these changes. Can we also ensure that judge adminship cannot be revoked? Below is where we revoke adminship https://github.com/department-of-veterans-affairs/caseflow/blob/43562ed9e75b14c6f949802521da9df6a4214c2b/app%2Fmodels%2Forganizations_user.rb#L23-L25
Below is how we ensure judges are not removed from their own team https://github.com/department-of-veterans-affairs/caseflow/blob/43562ed9e75b14c6f949802521da9df6a4214c2b/app%2Fmodels%2Forganizations_user.rb#L27-L33

2020-12-21 22:15 UTC, n1zyy commented on app/models/organizations_user.rb
> -  # Use instead: organization.add_user(user)
`add_user_to_organization` does not exist anywhere in our codebase, so this can go.

2020-12-22 17:38 UTC, hschallhorn commented on app/models/organizations_user.rb
> +    # mwagner - Won't this prevent BVA from removing extra judges right now?
> #13993 suggests that BVA is going to clean up JudgeTeams with more than one judge. It seems this code will prevent that. 🤔

The board is going to clean these up by removing adminship of non judges on the team. So we 
1. will not be hitting this function (will be using hitting `remove_admin_rights_from_user`)
2. will fail the condition of `organization.judge.eql?(user)` as the users are not the judges of this team

2020-12-22 17:40 UTC, hschallhorn commented on app/models/organizations_user.rb
> +  end
I approve! Let's instead call this something more generic as what we're checking doesn't have anything to do with _removing_ a user per se. Maybe something along the lines of `user_is_judge_of_team?`

2020-12-22 17:41 UTC, hschallhorn commented on spec/models/organizations_user_spec.rb
> +  describe ".remove_user_from_organization" do
💪  hell yes

2020-12-22 17:55 UTC, hschallhorn approved these changes
Looks good! Nice test additions as well! Ran through the following tests

```ruby
# To disable any weirdness with old half implemented code
FeatureToggle.disable!(:judge_admin_scm)

judge = User.third
judge_team = JudgeTeam.for_judge(judge)
atty = User.first
OU = OrganizationsUser

# Judge team can only have one admin
OU.make_user_admin(atty, judge_team)
# Caseflow::Error::ActionForbiddenError: Cannot add more than one admin to a judge team

# Judge's cannot have their adminship removed

```

2020-12-22 18:00 UTC, hschallhorn approved these changes
Looks good! Nice test additions as well! Ran through the following tests

```ruby
# To disable any weirdness with old half implemented code
FeatureToggle.disable!(:judge_admin_scm)

judge = User.third
judge_team = JudgeTeam.for_judge(judge)
atty = User.first
OU = OrganizationsUser

# Judge team can only have one admin ✅ 
OU.make_user_admin(atty, judge_team)
# Caseflow::Error::ActionForbiddenError: Cannot add more than one admin to a judge team

# Judges cannot be removed from their own teams ✅ 
Caseflow::Error::ActionForbiddenError: Cannot remove a judge from their judge team.
# Caseflow::Error::ActionForbiddenError: Cannot remove a judge from their judge team.

# Judges cannot have their adminship removed ✅ 
OU.remove_admin_rights_from_user(judge, judge_team)
# Caseflow::Error::ActionForbiddenError: Cannot remove adminship from a judge on their team
```

2020-12-22 20:05 UTC, merged