Bgantick/caseflow 285 edit nod meta
department-of-veterans-affairs/caseflow pull request #15705
Opened 2020-12-17 19:12 UTC by bgantick

Resolves #15511 

### Description
Model and migration for edit NOD date metadata. Enables storage of NOD date changes.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

2020-12-21 22:49 UTC, yoomlam requested changes
Some suggestions

2020-12-21 22:49 UTC, yoomlam commented on db/migrate/20201215215458_create_nod_date_edit.rb
> +    create_table :nod_date_edits do |t|
For consistency with tables like `request_issues_updates` and `end_product_updates`:
```suggestion
    create_table :nod_date_updates do |t|
```

2020-12-21 22:49 UTC, yoomlam commented on db/migrate/20201215215458_create_nod_date_edit.rb
> +      t.references "appeal", null: false, foreign_key: true, comment: "Appeal that NOD date is being edited for"
Grammar:
```suggestion
      t.references "appeal", null: false, foreign_key: true, comment: "Appeal for which the NOD date is being edited"
```

2020-12-21 22:49 UTC, yoomlam commented on db/migrate/20201215215458_create_nod_date_edit.rb
> +      t.date "new_value", null: false, comment: "Value after update"
```suggestion
      t.date "old_date", null: false, comment: "Date before update"
      t.date "new_date", null: false, comment: "Date after update"
```
Makes it clear in SQL queries that we are working with dates.

2020-12-22 21:41 UTC, yoomlam commented on app/models/nod_date_update.rb
> +  include HasSimpleAppealUpdatedSince
I think you should remove `include HasSimpleAppealUpdatedSince` and instead, add `nod_date_updates` to this list: https://github.com/department-of-veterans-affairs/caseflow/blob/db248a58395a5a884e083f0ade83d86a55ed7cf9/app/queries/appeals_updated_since_query.rb#L17-L25

Reason: this `NodDateUpdate` associated with `Appeal` is just tracking information similar to other items in the list. When the NOD date (aka `receipt_date`), the appeal's `updated_at` will also be updated, so have that is sufficient to detected appeals that have been updated since some date.

2020-12-22 21:54 UTC, yoomlam commented on db/migrate/20201215215458_create_nod_date_update.rb
> +      t.references "user", null: false, foreign_key: true, comment: "User that created this record"
Let's add a comment to the table:
```suggestion
      t.references "user", null: false, foreign_key: true, comment: "User that updated the NOD date"
```

2020-12-22 21:54 UTC, yoomlam commented on db/migrate/20201215215458_create_nod_date_update.rb
> +    create_table :nod_date_updates do |t|
```suggestion
    create_table :nod_date_updates, comment: "Tracks changes to an AMA appeal's receipt date (aka, NOD date)" do |t|
```

2020-12-22 21:54 UTC, yoomlam commented on db/migrate/20201215215458_create_nod_date_update.rb
> +      t.string "change_reason", null: false, comment: "Reason for change - entry_error or new_info"
Trivial suggestion
```suggestion
      t.string "change_reason", null: false, comment: "Reason for change: entry_error or new_info"
```

2020-12-22 22:23 UTC, yoomlam approved these changes
LGTM!

2020-12-23 17:11 UTC, pbradin approved these changes
LGTM!  Migrate/Rollback successful.

2020-12-23 17:15 UTC, merged