[WIP] Add new tables for unrecognized appellants and their POAs
department-of-veterans-affairs/caseflow pull request #15710
Opened 2020-12-17 22:42 UTC by nanotone

Connects #15573

### Description
This is one possible approach to modeling the new data requirements for unrecognized appellants:
- If the appellant is not a known dependent or CorpDB attorney, we need to store their details:
  - Whether they are a person or an organization (entity type)
  - Contact details (slight difference depending on entity type)
  - Their POA, who might be
    - A known CorpDB attorney, or
    - Another unrecognized entity
      - who might be a person or an organization (entity type)
      - and has their own contact details (again, slight difference depending on entity type)

@leikkisa wrote down some initial schema ideas in #15573, and we ended up hashing out some possibilities.

Given the following observations:
- The contact details have a large number of fields.
- They're mostly the same for person vs organization (people can have up to 4 parts to their name)
- Unrecognized appellants and unrecognized POAs have the same entity type options, and accordingly, the same fields for contact details.

This approach makes a few decisions:
- Associating the unrecognized appellant with the OtherClaimant subclass
- A single details table for all 4 combinations of entity role (appellant or POA) X entity type (person or org)
  - Lightweight Ruby logic, instead of STI, to differentiate persons from orgs
  - A single `name` column that's required, and 3 optional fields for person names, instead of 5 all-optional fields
  - A `HasUnrecognizedEntityDetail` concern to attach these details to an appellant, POA, and possibly other models in the future
- An extra table associating unrecognized appellants to their unrecognized POAs
  - I'm least fond of this, because the `unrecognized_power_of_attorneys` table owns no actual information
  - A `unrecognized_appellant.unrecognized_poa_id` column would be a cleaner 2-table approach, schema wise, but may require some trickier ActiveRecord code.

Example Rails console session demonstrating the ergonomics of this approach:
```ruby
> app = Appeal.find(appeal_id)
=> #<Appeal...>
> claimant = app.claimant
=> #<OtherClaimant...>
> ua = claimant.unrecognized_appellant
=> #<UnrecognizedAppellant...>
> ua.name
=> "Bob"
> poa = ua.power_of_attorney
=> #<UnrecognizedPowerOfAttorney...>
> poa.street_address_1
=> "9 Someplace Rd"
```

### Acceptance Criteria
- [ ] Code compiles correctly

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

2020-12-21 22:05 UTC, yoomlam requested changes
I think having more convenience methods at the `Claimant` level would help me understand the table relationships (an unrecognized claimant having an unrecognized POA) and so that we don't have to know to call `claimant.unrecognized_appellant` and `ua.power_of_attorney`. I'd like to be able to treat all `appeal.claimant` the same when possible (`appeal.claimant.first_name`) and be able to access the POA from the appeal (`appeal.power_of_attorney`). Note this potential problem in the current PR: `ua.name != appeal.claimant.name`.

Please add RSpecs for each new model. Plus FactoryBots for these models would be great! See https://github.com/department-of-veterans-affairs/caseflow/blob/a33e191e4d2a692f2c316c4ed99f622537fb0125/spec/models/tasks/cavc_task_spec.rb#L22

Could you write up example SQL queries to show the Reporting Team how to access unrecognized parties, somewhere in
https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary#caseflow-intake?

2020-12-21 22:05 UTC, yoomlam commented on db/migrate/20201217154643_add_unrecognized_appellant_tables.rb
> +      t.string :email
Interesting that phone is not required.

2020-12-23 19:07 UTC, nanotone commented on db/migrate/20201217154643_add_unrecognized_appellant_tables.rb
> +      t.string :email
It's optional in the design for this new flow, and that seems okay, as the Board relies far more heavily on address.

2020-12-23 19:14 UTC, nanotone commented on db/migrate/20201217154643_add_unrecognized_appellant_tables.rb
> +      t.string :name, null: false, comment: "Name of organization, or first name or mononym of person"
I'm hoping that the comment here provides ample guidance about the overloading of this field. In Ruby-land, everything is handled automatically by inspecting the `party_type` attribute.

2020-12-23 19:19 UTC, nanotone commented on app/models/concerns/has_unrecognized_entity_detail.rb
> +# to a model that "owns" it. The owner must implement an `unrecognized_entity_detail` method, which
I did want to, but decided that actually implementing a check would be far more effort than it's worth, since the concern code executes before the model defines any of its methods. This doesn't bother me; without the method, this concern flat-out won't work, and raises a straightforward `NoMethodError`.

2020-12-23 19:19 UTC, nanotone commented on db/schema.rb
> +  create_table "unrecognized_entity_details", comment: "Name and contact details for an unrecognized person or organization", force: :cascade do |t|
Changed!

2020-12-24 15:18 UTC, nanotone commented
@yoomlam
I went in and added the associations and delegations to the models so that an OtherClaimant with an unrecognized appellant will return all the expected values when generic-claimant methods are called. Here's a non-exhaustive list of such calls:

```ruby
claimant.name
claimant.first_name
claimant.address
claimant.power_of_attorney
claimant.representative_name
appeal.power_of_attorney
appeal.representative_name
```

Factories are now included, and Rspecs too -- although there is hardly any logic to speak of, as it's almost all associations and delegations.

2020-12-27 22:26 UTC, leikkisa approved these changes
Amazing job on a really challenging problem! ⭐ ⭐ ⭐ ⭐ ⭐ 

I utilized the rails association in one more place (happy to talk to you about it but I prefer it). Note to self, we need to update the claimant table not null for participant ID.  Other than that, I think there's going to be some more future work, but I think this is an amazing start!

2020-12-27 22:43 UTC, merged