Add MDR to CAVC Remand Entry Form
department-of-veterans-affairs/caseflow pull request #15751
Opened 2021-01-05 20:16 UTC by lomky

Resolves #15384 / [CASEFLOW-94](https://vajira.max.gov/browse/CASEFLOW-94)

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to (a realistic task tree, dispatched, AMA case)
2. Hit `+ Add CAVC Remand`
3. Fill out the form, **skipping Judge selection, judgement date, and mandate date**
4. Confirm that the infobox appears when MDR is selected
5. Hit submit - confirm Judgement Date and Mandate Date **do not** display a JS validation error requiring input
6. Fill out Judge, Judgement Date, and Mandate Date
   - Judgement Date and Mandate date are still required for the _back end_ validation - will be fixed in [CASEFLOW-97](https://vajira.max.gov/browse/CASEFLOW-97)
7. Hit submit and confirm the success message has the MDR wording, and the CAVC section lists the `Type`: `Memorandum Decision on Remand (MDR)`
   - Again, we are not checking if the MDR flow created the right tasks - that's later in the epic!

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

**Info box on MDR selection**
![image](https://user-images.githubusercontent.com/6129479/103581015-2dd05680-4ea9-11eb-8c11-13b9c513737b.png)

**New Success detail**
![image](https://user-images.githubusercontent.com/6129479/103580950-1729ff80-4ea9-11eb-84b7-f73f44c1b0dc.png)

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

2021-01-07 15:55 UTC, lomky commented
re: jest tests - the primary functionality in this PR (the functionality of the MDR radio button) is already covered in the Jest test. I'd like to add checks for the infobox and validation behavior details, but consider those nice-to-have

2021-01-07 23:25 UTC, yoomlam requested changes
Nice!  Some suggestions.

Regarding AC "Verify Confirmation modal is presented on users queue page upon clicking submit on the entry form with the MDR copy", I'm thinking this should be "Verify Confirmation ~modal~ *banner* is presented on ~users queue~ *case details* page upon clicking submit ...".

2021-01-07 23:25 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.stories.js
> +  mdrToggled: true
Don't need this line since it is set to `true` on line 14.
```suggestion
```

2021-01-07 23:25 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.stories.js
>      dismissalToggled: false,
I would rename all the `*Toggled` to `*Feature` because I initially read `mdrToggled` as representing if the MDR radio button was toggled.

2021-01-08 14:29 UTC, lomky commented on client/COPY.json
> +  "MDR_SELECTION_ALERT_BANNER": "Choosing MDR will set a 90-day hold on this case starting from the Court's decision date listed above. The hold is to wait for the Court's judgement and mandate. This
How about:

```suggestion
  "MDR_SELECTION_ALERT_BANNER": "Choosing MDR will set a 90-day hold on this case starting from the Court's decision date listed above. The hold is to wait for the Court's judgement and mandate dates. This remand case will be accessible in your organization's Assigned tab and will return to the team's Unassigned tab when the 90-days are over or the hold is manually ended, at which point the judgement and mandate dates can be entered.",
```

2021-01-08 14:30 UTC, lomky commented on client/COPY.json
> +  "CAVC_REMAND_MDR_CREATED_DETAIL": "This has generated an MDR task in your teams On Hold tab and will return to the unassigned tab after 90 days from the court decision date",
```suggestion
  "CAVC_REMAND_MDR_CREATED_DETAIL": "This has generated an MDR task in your team's Assigned tab and will return to the Unassigned tab after 90 days from the court decision date",
```

2021-01-08 14:37 UTC, yoomlam commented on client/COPY.json
> +  "MDR_SELECTION_ALERT_BANNER": "Choosing MDR will set a 90-day hold on this case starting from the Court's decision date listed above. The hold is to wait for the Court's judgement and mandate. This
Sounds good! The hyphen in `when the 90-days are over` is not needed.

2021-01-08 14:45 UTC, yoomlam approved these changes
LGTM! Nice small PR.

2021-01-08 15:15 UTC, merged