Mkerns/caseflow 557 get updated bgs data
department-of-veterans-affairs/caseflow pull request #15772
Opened 2021-01-11 20:39 UTC by mkerns355

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-01-28 15:52 UTC, bgantick commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    warm_veteran_attr_for_priority_distributions
Should add reporting for changes to `send_job_report`

2021-02-09 17:27 UTC, yoomlam requested changes

2021-02-09 17:27 UTC, yoomlam commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    datadog_segment = "warm_veteran_attr_for_priority_distributions"
```suggestion
```

2021-02-09 17:27 UTC, yoomlam commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    datadog_report_time_segment(segment: datadog_segment, start_time: start_time)
```suggestion
    datadog_report_time_segment(segment: "warm_veteran_attribs_for_priority_distributions", start_time: start_time)
```

2021-02-09 17:27 UTC, yoomlam commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    datadog_report_time_segment(segment: datadog_segment, start_time: start_time)
You're recording the `start_time` here. Is the end time or elapsed time logged?

2021-02-09 17:27 UTC, yoomlam commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    ).uniq
This is easier to read:
```suggestion
    genpop_distro_case_ids = DistributedCase.where(distribution_id: @genpop_distributions.pluck(:id)).pluck(:case_id)
    veterans_refreshed += Veteran.update_veteran_attr_service.warm_veteran_cache_for_appeals(genpop_distro_case_ids)
    veterans_refreshed.uniq
```

2021-02-09 17:27 UTC, yoomlam commented on app/models/veteran.rb
> +  def refresh_attr
```suggestion
  def refresh_attributes
```

2021-02-09 17:27 UTC, yoomlam commented on app/models/veteran.rb
> +    def update_veteran_attr_service
```suggestion
    def update_veteran_attributes_service
```

2021-02-09 17:27 UTC, yoomlam commented on app/services/update_veteran_attr_service.rb
> +class UpdateVeteranAttrService
```suggestion
class UpdateVeteranAttributesService
```

2021-02-09 17:27 UTC, yoomlam commented on app/services/update_veteran_attr_service.rb
> +  def warm_veteran_cache_for_appeals(appeal_ids)
```suggestion
  def update_veterans_for_appeals(appeal_ids)
```

2021-02-09 17:27 UTC, yoomlam commented on app/services/update_veteran_attr_service.rb
> +      appeal = Appeal.find_appeal_by_uuid_or_find_or_create_legacy_appeal_by_vacols_id(appeal_id)
Are you sure you want to create new legacy appeals if they don't exist?

2021-02-09 17:27 UTC, yoomlam commented on app/models/veteran.rb
> +    # if veteran could not be found. Raise exception and don't return, just ignore.
Don't we want to be notified if the Veteran for an appeal doesn't exist in BGS?

2021-02-09 17:27 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +    let(:date_of_death) { nil }
```suggestion
    let(:veteran) { create(:veteran) }
```

2021-02-09 17:27 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +    let!(:veterans_refreshed) { Array([veteran.file_number]) }
```suggestion
    let(:veterans_refreshed) { Array([veteran.file_number]) }
```

2021-02-09 17:27 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +      expect(subject.last).to eq "#{veterans_refreshed.count} veterans have been refreshed"
Note that since you set `@updated_veterans` on line 334, `veterans_refreshed.count` will always be 1.

2021-02-09 17:27 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +      expect { subject }.not_to raise_error
You should check the return value of `subject`.

2021-02-09 17:27 UTC, yoomlam commented on spec/services/update_veteran_attr_service_spec.rb
> +  let(:sam_date_of_death) { "2021-1-26" }
Don't create these extraneous variables unless you use them more than once.

2021-02-09 17:27 UTC, yoomlam commented on spec/services/update_veteran_attr_service_spec.rb
> +  end
Let the factory generate the attributes, which you don't really care what the values is.
```suggestion
  let(:veteranBob) {create(:veteran)}
```

2021-02-10 16:23 UTC, mkerns355 commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    datadog_report_time_segment(segment: datadog_segment, start_time: start_time)
I was going for the elapsed time. Is there a better way to do this?

2021-02-10 16:28 UTC, mkerns355 commented on app/models/veteran.rb
> +    # if veteran could not be found. Raise exception and don't return, just ignore.
Yes if the veteran doesn't exist I want to be alerted but I don't want the process to stop running through the rest of the veterans.

2021-02-10 16:43 UTC, mkerns355 commented on app/services/update_veteran_attr_service.rb
> +      appeal = Appeal.find_appeal_by_uuid_or_find_or_create_legacy_appeal_by_vacols_id(appeal_id)
Would there be a case in which that could happen?

2021-02-10 17:32 UTC, yoomlam commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    datadog_report_time_segment(segment: datadog_segment, start_time: start_time)
Nevermind. I misinterpreted what this line was doing.

2021-02-10 17:44 UTC, yoomlam commented on app/models/veteran.rb
> +    # if veteran could not be found. Raise exception and don't return, just ignore.
You can log it to a string and include it in the final report like this: https://github.com/department-of-veterans-affairs/caseflow/blob/7467a46b5204bd84c25760e2356761829de85076/app/jobs/warm_bgs_caches_job.rb#L195-L202

2021-02-10 17:50 UTC, yoomlam commented on app/services/update_veteran_attr_service.rb
> +      appeal = Appeal.find_appeal_by_uuid_or_find_or_create_legacy_appeal_by_vacols_id(appeal_id)
I don't know, but `UpdateVeteranAttrService#warm_veteran_cache_for_appeals` can be called by anything in any context. So perhaps the question is how do you want this service to be used? When a veteran's attributes are updated for a given appeal, is the appeal expected to already exist? If so, don't try to create it -- so create a method called `find_appeal_by_uuid_or_legacy_appeal_by_vacols_id` that doesn't create an appeal.

2021-02-10 20:38 UTC, mkerns355 commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +      expect(subject.last).to eq "#{veterans_refreshed.count} veterans have been refreshed"
Yes I know that was as intended.

2021-02-10 21:06 UTC, mkerns355 commented on app/models/veteran.rb
> +    # if veteran could not be found. Raise exception and don't return, just ignore.
Hey Yoom isn't the Raven.capture_exception(error) capturing if any error occurs on the veteran refresh?

2021-02-10 21:16 UTC, yoomlam commented on app/models/veteran.rb
> +    # if veteran could not be found. Raise exception and don't return, just ignore.
Line 457 only runs for `ActiveRecord::RecordNotFound` errors, as seen in line 456.

2021-02-10 21:48 UTC, mkerns355 commented on app/models/veteran.rb
> +    # if veteran could not be found. Raise exception and don't return, just ignore.
Are there cases where a veteran could exist in Caseflow but not in BGS?

2021-02-10 22:20 UTC, yoomlam commented on app/models/veteran.rb
> +    # if veteran could not be found. Raise exception and don't return, just ignore.
Since we can't control the data in BGS, it is possible for someone to delete or modify a Veteran in BGS. We have had out-of-sync problems in the past.

2021-02-12 16:45 UTC, bgantick commented on app/services/update_veteran_attr_service.rb
> +      appeal = Appeal.find_appeal_by_uuid_or_find_or_create_legacy_appeal_by_vacols_id(appeal_id)
Added new method to the appeal model for this

2021-03-05 20:08 UTC, yoomlam requested changes
Some suggestions

2021-03-05 20:08 UTC, yoomlam commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    veterans_refreshed += Veteran.update_veteran_attribs_service.update_veterans_for_appeals(genpop_distro_case_ids)
Let's minimize the number of DB queries:
```suggestion
    distro_case_ids = DistributedCase.where(distribution_id: (@tied_distributions + @genpop_distributions).pluck(:id)).pluck(:case_id)
    veterans_refreshed = Update_veteran_attribs_service.update_for_appeals(distro_case_ids)
```

2021-03-05 20:08 UTC, yoomlam commented on app/models/appeal.rb
> +
No longer need this if you use my suggestion in `app/services/update_veteran_attribs_service.rb`.

2021-03-05 20:08 UTC, yoomlam commented on app/models/veteran.rb
> +
Not needed
```suggestion
```

2021-03-05 20:08 UTC, yoomlam commented on app/services/update_veteran_attribs_service.rb
> +    appeal = Appeal.find_appeal_by_uuid_or_find_legacy_appeal_by_vacols_id(appeal_id)
```suggestion
  def update_for_appeal(appeal)
```

2021-03-05 20:27 UTC, yoomlam commented on app/models/veteran.rb
> +      # no nothing
```suggestion
      # do nothing
```

2021-03-05 20:30 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +    let(:veterans_refreshed) { Array([veteran.file_number]) }
Why would we expect this veteran to be refreshed? This vet is not associated with the appeals being distributed.

2021-03-05 20:35 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +      expect(subject.last).to eq "#{veterans_refreshed.count} veterans have been refreshed"
`DistributedCase.count => 0` so 0 veterans should have been refreshed, right?

2021-03-05 20:38 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +    let(:ready_priority_bfkey) { "12345" }
Not used
```suggestion
```

2021-03-05 20:39 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +    let(:ready_priority_uuid) { "bece6907-3b6f-4c49-a580-6d5f2e1ca65c" }
Not needed
```suggestion
```

2021-03-05 20:39 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +          uuid: ready_priority_uuid,
Not needed
```suggestion
```

2021-03-05 20:45 UTC, yoomlam commented on spec/jobs/push_priority_appeals_to_judges_job_spec.rb
> +    end
There's a lot of copy and pasted lines. Use nested `context` and methods to DRY it up:
* https://en.wikibooks.org/wiki/Ruby_on_Rails/Getting_Started/Don%C2%B4t_repeat_yourself
* https://thevaluable.dev/dry-principle-cost-benefit-example/
* https://zverok.github.io/blog/2017-01-22-dry-rspec.html

2021-03-05 20:49 UTC, yoomlam commented on spec/services/update_veteran_attribs_service_spec.rb
> +  let(:appeal2) { create(:appeal, veteran_file_number: veteranSam.file_number) }
Easier and shorter to read
```suggestion
  let(:appeal) { create(:appeal, veteran: veteranBob) }
  let(:appeal2) { create(:appeal, veteran: veteranSam) }
```

2021-03-05 20:52 UTC, yoomlam commented on spec/services/update_veteran_attribs_service_spec.rb
> +      veteranBob.unload_bgs_record # force it to reload from BGS
Test passes even if this line is deleted. Why is this line needed?

2021-03-05 20:57 UTC, yoomlam commented on spec/services/update_veteran_attribs_service_spec.rb
> +end
Here are the scenarios that I think need to be tested:
1. vet has no DOD
2. vet has different/obsolete DOD compared to that in BGS
3. vet has same DOD as in BGS

2021-03-05 20:59 UTC, bgantick commented on app/models/appeal.rb
> +
I believe this was added in response to a previous suggestion, but I'll refactor `update_veteran_attribs_service`

2021-03-05 20:59 UTC, yoomlam commented on spec/services/update_veteran_attribs_service_spec.rb
> +  let(:veteranSam) { create(:veteran) }
The reason for having 2 vets is not obvious in the test.

2023-03-09 15:56 UTC, closed without merging