Enable CAVC MDR appeal stream creation
department-of-veterans-affairs/caseflow pull request #15788
Opened 2021-01-15 17:58 UTC by ajspotts

Resolves [CASEFLOW-92](https://vajira.max.gov/browse/CASEFLOW-92)

### Description
Update the CAVC controller and model to allow for the creation of the MDR subtype.

### Acceptance Criteria
- [ ] The "Add a Court Remand" form on dispatched appeals now allows for the creation of MDR CAVC remand appeal streams.

### Testing Plan
1. Create a ready for CAVC appeal, note the `stream_docket_number` so you can search for the appeal in the UI.
```ruby
original_appeal = FactoryBot.create(:appeal, 
                           :dispatched, 
                           associated_judge: JudgeTeam.first.judge, 
                           associated_attorney: JudgeTeam.first.attorneys.first)
FactoryBot.create_list(:request_issue, 2,                                                                                  
            :rating,                                                                                            
            :with_rating_decision_issue,                                                                           
            decision_review: original_appeal,                                                                               
            veteran_participant_id: Veteran.first.participant_id,                                                        
            contested_issue_description: "issue_description",                                                              
            notes: "issue_notes")
```
2. Login as a CAVC lit support user
3. Search for the dispatched appeal you just created and select it
4. Click the "+ Add CAVC Remand" button in the "Post-Despatch actions" section
5. Fill out the "Add a Court Remand" form, note that an MDR remand does not require entry of a judgement or mandate date however they may be entered if they do exist
6. Open up the Network tab of your Chrome devtools and Submit the form
7.  Check that you received a 201 response from the backend (`appeals/<uuid>/cavc_remand`) confirming the creation of the MDR stream, also note the success banner in the UI confirming a MDR creation
8. Navigate to http://localhost:3000/search and search for the docket number of your original appeal and confirm you can see the newly created MDR appeal stream

### Code Documentation Updates
- [ ] CAVC Remand wiki already [states](https://github.com/department-of-veterans-affairs/caseflow/wiki/CAVC-Remands#supported-remand-subtypes) the support of MDR remands

2021-01-15 18:18 UTC, ajspotts commented on spec/controllers/cavc_remands_controller_spec.rb
> +      it "creates the CAVC remand and new appeal" do
Not loving the naming between the `shared_examples` and `it` block (seems redundant).  Open to suggestions!

2021-01-15 21:38 UTC, yoomlam commented
During testing, I noticed the `CavcTask` is assigned to BVA -- should it be assigned to `CavcLitigationSupport`?
```
```

2021-01-15 22:07 UTC, yoomlam requested changes
Nice test script!

2021-01-15 22:07 UTC, yoomlam commented on spec/controllers/cavc_remands_controller_spec.rb
> +        context "with unrequired judgement and mandate date parameters" do
Less confusing to me -- and to @n1zyy who is pairing as I review this ;)
```suggestion
        context "with judgement and mandate date parameters" do
```

2021-01-15 22:07 UTC, yoomlam commented on spec/feature/queue/cavc_task_queue_spec.rb
> +          expect(page).not_to have_content "#{COPY::CASE_DETAILS_CAVC_MANDATE_DATE}: #{date}"
Just check for the non-existence of the labels (in case there's a different date).
```suggestion
          expect(page).not_to have_content "#{COPY::CASE_DETAILS_CAVC_JUDGEMENT_DATE}:"
          expect(page).not_to have_content "#{COPY::CASE_DETAILS_CAVC_MANDATE_DATE}:"
```

2021-01-15 22:08 UTC, yoomlam commented on spec/controllers/cavc_remands_controller_spec.rb
> +      it "creates the CAVC remand and new appeal" do
Looks fine to me.

2021-01-19 15:29 UTC, ajspotts commented
> During testing, I noticed the `CavcTask` is assigned to BVA -- should it be assigned to `CavcLitigationSupport`?
> 
> ```
>                                                   ┌───────────────────────┐
> Appeal 1050 (E 210114-1049 Court Remand) ──────── │ ASGN_TO               │
> └── RootTask                                      │ Bva                   │
>     └── DistributionTask                          │ Bva                   │
>         └── CavcTask                              │ Bva                   │
>             └── SendCavcRemandProcessedLetterTask │ CavcLitigationSupport │
>                                                   └───────────────────────┘
> ```

Based upon the [AC](https://github.com/department-of-veterans-affairs/caseflow/pull/15304#issue-492485747) from the PR where we added that [functionality](https://github.com/department-of-veterans-affairs/caseflow/blob/6598094ecd763a48b758280d74948214b21a9526/app/models/tasks/cavc_task.rb#L42) I believe this is the correct behavior

2021-01-20 16:03 UTC, lomky commented on spec/controllers/cavc_remands_controller_spec.rb
> +        expect(response_body["cavc_appeal"]["source_appeal_id"]).not_to eq(source_appeal.id)
I think this stems from an overzealous find and replace on my part in another PR. Fixing!

2021-01-20 17:38 UTC, yoomlam requested changes
Some considerations

2021-01-20 17:38 UTC, yoomlam commented on app/controllers/cavc_remands_controller.rb
> +      REQUIRED_PARAMS - [:judgement_date, :mandate_date]
Convert this into a constant?

```ruby
  REQUIRED_PARAMS_FOR_MDR = (REQUIRED_PARAMS - [:judgement_date, :mandate_date]).freeze
```
```suggestion
      REQUIRED_PARAMS_FOR_MDR
```

2021-01-20 17:38 UTC, yoomlam commented on spec/controllers/cavc_remands_controller_spec.rb
> +        expect(response_body["cavc_appeal"]["appeal_id"]).not_to eq(source_appeal.id)
Can we check what `response_body["cavc_appeal"]["appeal_id"]` should be equal to, rather than not equal to?

2021-01-20 18:33 UTC, lomky commented on spec/controllers/cavc_remands_controller_spec.rb
> +        expect(response_body["cavc_appeal"]["appeal_id"]).not_to eq(source_appeal.id)
So, I think what we're doing here is enough. We're checking "is the appeal ID different, the stream docket number the same, and the type remand" which feels sufficient to me to prove that we've created a new cavc appeal in the context of a Controller spec.

2021-01-20 18:38 UTC, yoomlam commented on spec/controllers/cavc_remands_controller_spec.rb
> +        expect(response_body["cavc_appeal"]["appeal_id"]).not_to eq(source_appeal.id)
Should `response_body["cavc_appeal"]["appeal_id"]` be `nil`?

2021-01-20 18:44 UTC, yoomlam commented on spec/controllers/cavc_remands_controller_spec.rb
> +        expect(response_body["cavc_appeal"]["appeal_id"]).not_to eq(source_appeal.id)
How about this:
```suggestion
        expect(response_body["cavc_appeal"]["id"]).to eq(CavcRemand.find(response_body["cavc_remand"]["id"]).remand_appeal_id)
```
I think you'll have to update this branch to get `remand_appeal_id` to be non-nil.

2021-01-20 19:59 UTC, yoomlam commented on app/controllers/cavc_remands_controller.rb
> +      REMAND_REQUIRED_PARAMS + JMR_REQUIRED_PARAMS
I still don't like that we're creating a new array with every call to `required_params_by_subtype` but maybe I'm pre-optimizing.

2021-01-20 20:01 UTC, yoomlam commented on spec/feature/queue/cavc_task_queue_spec.rb
> +          expect(page.has_no_content?("#{COPY::CASE_DETAILS_CAVC_MANDATE_DATE}:")).to eq(true)
Nice!

2021-01-20 20:03 UTC, yoomlam approved these changes
👍

2021-01-20 20:03 UTC, yoomlam commented on app/controllers/cavc_remands_controller.rb
> +      REMAND_REQUIRED_PARAMS + JMR_REQUIRED_PARAMS
I still don't like that we're creating a new array with every call to `required_params_by_subtype` but maybe I'm pre-optimizing.

2021-01-20 21:30 UTC, merged