Paula/WIP Caseflow-200-add-edit-reasons
department-of-veterans-affairs/caseflow pull request #15786
Opened 2021-01-15 01:45 UTC by pbradin

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-01-22 01:09 UTC, meckila-navapbc commented on client/app/queue/components/EditNodDateModal.jsx
> +  const handleCancel = () => onCancel();
Since the onCancel getting passed to the modal is an immediately invoked function, it doesn't need to be called in another immediately invoked function.

2021-01-22 13:46 UTC, bgantick requested changes

2021-01-22 13:46 UTC, bgantick commented on app/controllers/nod_date_updates_controller.rb
> +  def update
lost some validation here (see https://github.com/department-of-veterans-affairs/caseflow/wiki/Controller-Schemas). `update_nod_date` used this: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/schemas/appeals_schemas.rb

2021-01-22 16:06 UTC, pbradin commented on client/app/queue/components/EditNodDateModal.jsx
> +  const handleCancel = () => onCancel();
done

2021-01-25 19:23 UTC, bgantick requested changes

2021-01-25 19:23 UTC, bgantick commented on client/test/app/queue/components/EditNodDateModal.test.js
> +  it('should disable submit button when date is valid and updated and no reason has not been selected', () => {
```suggestion
  it('should disable submit button when date is valid and updated and a reason has not been selected', () => {
```

2021-01-25 19:23 UTC, bgantick commented on client/test/app/queue/components/EditNodDateModal.test.js
> +  it('should disable submit button reason has been selected and date is not valid', () => {
```suggestion
  it('should disable submit button if a reason has been selected and date is not valid', () => {
```

2021-01-25 19:55 UTC, bgantick approved these changes

2021-01-25 20:11 UTC, meckila-navapbc commented
Re-verified that this works locally

2021-01-25 20:42 UTC, meckila-navapbc approved these changes
LGTM

2021-01-25 21:00 UTC, merged