Added convert to virtual for video hearings
department-of-veterans-affairs/caseflow pull request #15805
Opened 2021-01-20 18:52 UTC by sahalliburton

Resolves [CASEFLOW-210](https://vajira.max.gov/browse/CASEFLOW-210)

### Description

Gives Hearing Coordinators the ability to convert the hearing request type on any appeal applying the same workflow as was used to convert Travel Board request types implemented in #15314. 

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Users are able to successfully convert hearing request types from Central Office/Video to Virtual

### Testing Plan

1. Shadow user `BVASYELOW`: http://localhost:3000/test/users
2. Navigate to the hearing schedule: http://localhost:3000/hearings/schedule
3. Click the "Schedule Veterans" button
4. Search for "St. Petersburg, FL" in the Regional Office dropdown and navigate to the "AMA Veterans Waiting" tab
5. Select 1 of the Veterans from the list to navigate to their case details page
6. Once the case details page loads, check the actions dropdown for the Convert to Virtual Hearing action and select that
7. Review the conversion page and based on whether you selected the Central Office or another regional office, you should see a message at the top indicating in which queue this request will be
8. Click the Convert to Virtual Hearing button
9. Ensure you receive a success banner and that the action to Convert to Virtual Hearing is no longer available
10. Ensure that the Hearing Request type in the claims header now says Virtual
11. Scroll down and check that there is a ChangeHearingRequestType indicating the conversion
12. Scroll back up and click the Schedule Veteran action and ensure that the Virtual option is preselected

### Code Documentation Updates
- [x] Add or update code comments at the top of the class, module, and/or component.

### Database Changes
*Only for Schema Changes*

* [x] Column comments updated
* [x] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [x] DB schema docs updated with `make docs` (after running `make migrate`)
* [x] #appeals-schema notified with summary and link to this PR

2021-01-20 19:05 UTC, sahalliburton commented on app/models/appeal.rb
> +  has_paper_trail only: [:changed_request_type], on: [:update]
Adds paper trail to AMA appeals the same as in https://github.com/department-of-veterans-affairs/caseflow/commit/b90be408b2c3566c0ae8509690cd72e1693ab7cc

2021-01-20 19:05 UTC, sahalliburton commented on app/models/appeal.rb
> +  def current_hearing_request_type(readable: false)
These are the PaperTrail methods used to display the case timeline details

2021-01-20 19:06 UTC, sahalliburton commented on app/models/tasks/schedule_hearing_task.rb
> +      if params[:business_payloads][:values][:changed_request_type].present?
If the payload includes the changed request type, apply that workflow instead of the schedule veterans workflow

2021-01-20 19:06 UTC, sahalliburton commented on app/models/tasks/schedule_hearing_task.rb
> +  def create_schedule_hearing_tasks(params)
This method encapsulates the logic to either create or cancel the scheduled hearing

2021-01-20 19:07 UTC, sahalliburton commented on app/models/tasks/schedule_hearing_task.rb
> +  def change_hearing_request_type(params, current_user)
This method encapsulates the logic that passes control to the child ChangeHearingRequestTypeTask model

2021-01-20 19:07 UTC, sahalliburton commented on spec/feature/hearings/convert_hearing_request_type/edit_hearsched_spec.rb
> +# frozen_string_literal: true
I consolidated the convert hearing request type feature tests into 1 file separated by the hearing request type

2021-01-20 19:08 UTC, sahalliburton commented on spec/feature/hearings/convert_hearing_request_type/edit_hearsched_spec.rb
> +      FeatureToggle.enable!(:convert_travel_board_to_video_or_virtual)
This is the feature toggle applied to the convert travel board hearing requests, I am not sure if we want to rename this @ferristseng?

2021-01-21 15:43 UTC, ferristseng requested changes
Looks really great overall, and the tests look awesome! I think we might want to refactor the request type logic for appeal and legacy appeal into a Concern or another class if that's possible since it's really similar for both.

2021-01-22 22:49 UTC, ferristseng approved these changes
LGTM! Thanks for making all the changes

2021-01-25 15:20 UTC, merged