Omit the Virtual Hearing RO from list of cities we test sorting
department-of-veterans-affairs/caseflow pull request #15817
Opened 2021-01-22 00:02 UTC by n1zyy

It has a null city which breaks the test. It should never be anyone's
closest office, though, so just omit it.

Resolves #15816

### Description
Fixes a flaky test. The virtual hearing office was recently added to `REGIONAL_OFFICE_INFORMATION.json`, but has a null city.

2021-01-22 00:05 UTC, n1zyy commented on spec/models/task_pager_spec.rb
> +      let(:virtual_hearing_ro_key) { ['R'] }
Unnecessary variable assignment just to try to make `RegionalOffice::ROS - ['R']` more understandable.

2021-01-22 14:43 UTC, yoomlam commented on spec/models/task_pager_spec.rb
> +        # Virtual Hearing "RO" has no city and should be omitted here:
```suggestion
        # Virtual Hearing "R" has no city and should be omitted here:
```

2021-01-22 14:44 UTC, yoomlam commented on spec/models/task_pager_spec.rb
> +        # Virtual Hearing "RO" has no city and should be omitted here:
```suggestion
        # Regional Office "R" (Virtual Hearing) has no city and should be omitted here:
```

2021-01-22 14:47 UTC, yoomlam commented on spec/models/task_pager_spec.rb
> +        # Virtual Hearing "RO" has no city and should be omitted here:
I don't think changing the test is the right solution if the `subject` (`TaskPager.new(arguments).task_page_count`) is able to handle null values. Shouldn't we update `expected_order` to handle null values?

2021-01-22 14:49 UTC, yoomlam requested changes
See comment.

2021-01-22 23:17 UTC, n1zyy commented on spec/models/task_pager_spec.rb
> +        # Virtual Hearing "RO" has no city and should be omitted here:
This seemed awfully reasonable when I talked to you this morning, but it seems like it might actually be more complicated.

To validate the concept, I changed the offending line to this:

```ruby
RegionalOffice::CITIES[task.appeal.closest_regional_office][:city].upcase.tr(" ", "_") rescue nil
```

Not the prettiest code, but wanted to see that it worked before making it more careful. This failed:

```
  1) TaskPager.sorted_tasks when sorting by closest regional office column sorts by regional office city
     Failure/Error:
       expected_order = created_tasks.sort_by do |task|
         RegionalOffice::CITIES[task.appeal.closest_regional_office][:city].upcase.tr(" ", "_") rescue nil
       end

     ArgumentError:
       comparison of NilClass with String failed
     # ./spec/models/task_pager_spec.rb:382:in `sort_by'
     # ./spec/models/task_pager_spec.rb:382:in `block (4 levels) in <top (required)>'
```

It looks like `sort_by` doesn't like a literal nil.


I changed it to `rescue ""`. Surprisingly, that affected the results:

```
  1) TaskPager.sorted_tasks when sorting by closest regional office column sorts by regional office city
     Failure/Error: expect(subject.map(&:appeal_id)).to eq(expected_order.map(&:appeal_id))

       expected: [1, 14, 6, 9, 13, 3, 8, 5, 10, 2, 4, 11, 12, 7]
            got: [14, 6, 9, 13, 3, 8, 5, 10, 2, 4, 11, 12, 7, 1]

       (compared using ==)
     # ./spec/models/task_pager_spec.rb:385:in `block (4 levels) in <top (required)>'
```

It seems like null values may actually be problematic here, but I pretty quickly ended up in TaskSorter code scratching my head.

Part of the reason I went with just removing virtual hearings is that @ferristseng had suggested they would never be anyone's closest office and that it therefore didn't really make sense to include them in the "when sorting by closest regional office column" test case. I'm inclined to either go with that approach, or to punt this for someone more familiar with the TaskSorter and expected behavior here.

2021-01-22 23:26 UTC, yoomlam commented on spec/models/task_pager_spec.rb
> +        # Virtual Hearing "RO" has no city and should be omitted here:
Ok. How about adding a code comment to that effect, then I'll approve?

2021-01-26 19:46 UTC, yoomlam approved these changes

2021-01-26 20:20 UTC, merged