Mkerns/caseflow 199 add warning message
department-of-veterans-affairs/caseflow pull request #15830
Opened 2021-01-25 21:42 UTC by mkerns355

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-01-26 14:45 UTC, bgantick requested changes
One small change

2021-01-26 14:45 UTC, bgantick commented on client/app/queue/components/EditNodDateModal.jsx
> +      { showWarning ? <Alert
Looks like you'll need some margin below the warning..
|Design|Component|
|--|--|
|![Screen Shot 2021-01-26 at 9 39 49 AM](https://user-images.githubusercontent.com/640182/105859821-f2620d00-5fba-11eb-9c69-7f1803ca8e35.png)|<img width="491" alt="Screen Shot 2021-01-26 at 9 39 57 AM" src="https://user-images.githubusercontent.com/640182/105859847-f8f08480-5fba-11eb-94a5-d22d6a05c00e.png">|

2021-01-26 14:46 UTC, bgantick commented on client/app/queue/components/EditNodDateModal.jsx
> +      { showWarning ? <Alert
Could probably adjust the line height on the text too

2021-01-27 19:48 UTC, mkerns355 commented on client/app/queue/components/EditNodDateModal.jsx
> +      { showWarning ? <Alert
Done.

2021-01-27 20:59 UTC, bgantick approved these changes

2021-01-28 15:55 UTC, merged