CASEFLOW-419 AddCavcDatesModal
department-of-veterans-affairs/caseflow pull request #15845
Opened 2021-01-28 19:44 UTC by ajspotts

Resolves [CASEFLOW-419](https://vajira.max.gov/browse/CASEFLOW-419)

### Description
Adds the `AddCavcDatesModal` which users will encounter after selecting the "Remand ready for 90-day letter" task.

### Acceptance Criteria
- [x] Code compiles correctly
- [x] Tests pass
- [x] Please put this work behind the feature toggle: mdr_cavc_remand (not necessary as FT will go an task action that directs to modal)
- [x] This feature should be accessible to the following user groups: CAVC Litigation Support (determined by access to CAVC appeal)
- [x] Include screenshot(s) in the Github issue if there are front-end changes
- [x] Update documentation: CAVC Remand
- [x] New page to enter judgement date and mandate date and instructions is presented when 'remand ready for 90 day letter' is selected
  - date fields are date pickers - required
  - instructions field is open text box - required
  - validation errors show if these are not entered when the user submits
Submit success banner copy:
"You have successfully created a CAVC Remand case
This has generated a 90 day letter task in your organizations queue"

### Testing Plan
1. run `AddCavcDatesModal.test.js`
2. run `make storybook` to view component

### Code Documentation Updates
- [x] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [x] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)

Form|Form with errors
---|---
![Screen Shot 2021-01-28 at 2 39 31 PM](https://user-images.githubusercontent.com/18618189/106189724-a8be2180-6176-11eb-9f87-dcded0f33a55.png)|![Screen Shot 2021-01-28 at 2 40 47 PM](https://user-images.githubusercontent.com/18618189/106190014-0ce0e580-6177-11eb-8c20-d010bdeb68d6.png)

2021-01-28 19:46 UTC, ajspotts commented on client/test/app/queue/AddCavcRemandView.test.js
> +    });
unrelated, however realized that `AddCavcRemandView` wasn't testing to verify instructions so added it in

2021-01-29 16:52 UTC, yoomlam commented on client/COPY.json
> +  "ADD_CAVC_DATES_TITLE": "Add Court dates",
Do you want to through "CAVC" in here somewhere like?
```suggestion
  "ADD_CAVC_DATES_TITLE": "Add CAVC mandate dates",
```
You can ask Ann-Marie when you demo it.

2021-01-29 16:54 UTC, ajspotts commented on client/COPY.json
> +  "ADD_CAVC_DATES_TITLE": "Add Court dates",
Yea dunno, going off of the [designs](https://www.figma.com/file/8noUqRbvCJzdpwkSNCb8lZ/CAVC-Remand-Designs?node-id=882%3A625)

2021-01-29 17:00 UTC, yoomlam commented on client/app/queue/AddCavcDatesModal.jsx
> +      catch((err) => showErrorMessage({ title: 'Error', detail: JSON.parse(err.message).errors[0].detail }));
Do we have a test that ensures this request actually updates the DB? Or how do we manually test it?

2021-01-29 17:03 UTC, ajspotts commented on client/app/queue/AddCavcDatesModal.jsx
> +      catch((err) => showErrorMessage({ title: 'Error', detail: JSON.parse(err.message).errors[0].detail }));
I believe that test will need to be written as part of [CASEFLOW-98](https://vajira.max.gov/browse/CASEFLOW-98) Create mandate receipt workflow for MDR as that will add the actual task action and routing that will enable the entire workflow.

2021-01-29 17:11 UTC, yoomlam requested changes
Ran `cd client; yarn test:jest test/app/queue/AddCavcDatesModal.test.js`
Played with Storybook at http://192.168.44.26:6006/?path=/story/queue-addcavcdatesmodal--default

Do we have to use the word "intake" in "Complete the details below to intake this Court remand for further processing"? How about "register" instead? 🤷

2021-01-29 17:11 UTC, yoomlam commented on client/app/queue/AddCavcDatesModal.jsx
> + *                                       associated decision issues on the appeal from state
```suggestion
 *  - @param {string}   appealId         The id of the appeal we are updating this cavc remand for.
```

2021-01-29 17:11 UTC, yoomlam commented on client/app/queue/AddCavcDatesModal.jsx
> + *  - @param {Object[]} decisionIssues   Issues pulled from state to allow the user to select which are being remanded
```suggestion
```

2021-01-29 17:11 UTC, yoomlam commented on client/app/queue/AddCavcDatesModal.jsx
> +  const validInstructions = () => instructions && instructions.length > 0;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
```suggestion
  const validInstructions = () => instructions?.length > 0;
```

2021-01-29 17:11 UTC, yoomlam commented on client/app/queue/AddCavcDatesModal.jsx
> +      catch((err) => showErrorMessage({ title: 'Error', detail: JSON.parse(err.message).errors[0].detail }));
Also is `showErrorMessage` tested anywhere? Can we simulate a response in Storybook?

2021-01-29 17:11 UTC, yoomlam commented on client/app/queue/AddCavcDatesModal.jsx
> +      {error && <Alert title={error.title} type="error">{error.detail}</Alert>}
Should this be at the top of the modal instead?

2021-01-29 17:16 UTC, ajspotts commented on client/app/queue/AddCavcDatesModal.jsx
> +      {error && <Alert title={error.title} type="error">{error.detail}</Alert>}
Because of how the `Alert` component is [written](https://github.com/department-of-veterans-affairs/caseflow/blob/54a0e4696af94540c7b994378170cffff6945205/client/app/components/Alert.jsx#L7), it will always render at the top of the page

2021-01-29 17:17 UTC, ajspotts commented on client/app/queue/AddCavcDatesModal.jsx
> +  const validInstructions = () => instructions && instructions.length > 0;
good catch!

2021-01-29 17:18 UTC, yoomlam submitted a review, later dismissed

2021-01-29 17:18 UTC, yoomlam commented on client/app/queue/AddCavcDatesModal.stories.js
> +  parameters: { controls: { expanded: true } },
Perhaps we can cause the `Alert` to appear using `controls`.

2021-01-29 17:18 UTC, yoomlam commented on client/test/app/queue/AddCavcDatesModal.test.js
> +      // component.find('#Add-Court-dates-button-id-1').simulate('click');
```suggestion
```

2021-01-29 17:18 UTC, yoomlam commented on client/test/app/queue/AddCavcDatesModal.test.js
> +});
How about adding a test that checks for the `Alert` component?

2021-01-29 17:18 UTC, ajspotts commented on client/app/queue/AddCavcDatesModal.jsx
> +      catch((err) => showErrorMessage({ title: 'Error', detail: JSON.parse(err.message).errors[0].detail }));
No we need an actual response from the backend, so same answer

2021-01-29 17:20 UTC, ajspotts commented on client/COPY.json
> +  "ADD_CAVC_DATES_TITLE": "Add Court dates",
Holding off on this one as I believe it's best to go off what design has mocked up unless @araposo-tistatech would like it changed

2021-01-29 17:21 UTC, yoomlam commented on client/app/queue/AddCavcDatesModal.jsx
> +      {error && <Alert title={error.title} type="error">{error.detail}</Alert>}
Hmmm. That code says "Scroll to top" but I'll take your word for it.

2021-01-29 17:22 UTC, ajspotts commented on client/test/app/queue/AddCavcDatesModal.test.js
> +      // component.find('#Add-Court-dates-button-id-1').simulate('click');
remnants from pairing 🤦

2021-01-29 17:26 UTC, ajspotts commented on client/test/app/queue/AddCavcDatesModal.test.js
> +});
Not sure how to do that here as we can't trigger the alert without the form submission.

2021-02-02 19:14 UTC, ajspotts commented on client/app/queue/AddCavcDatesModal.jsx
> +  const submit = () => new Promise((resolve) => {
create a `Promise` as `QueueFlowModal` is expecting one on [submit](https://github.com/department-of-veterans-affairs/caseflow/blob/4ea9294c7137b17d018883a0d7757f46200d388f/client/app/queue/components/QueueFlowModal.jsx#L42)

2021-02-02 21:05 UTC, ajspotts commented on client/test/app/queue/AddCavcDatesModal.test.js
> +
setup our [spy](https://jestjs.io/docs/en/jest-object) and `Promise`

2021-02-02 21:05 UTC, ajspotts commented on client/test/app/queue/AddCavcDatesModal.test.js
> +      simulate('change', { target: { value: instructions } });
update our form with some values

2021-02-02 21:05 UTC, ajspotts commented on client/test/app/queue/AddCavcDatesModal.test.js
> +    });
mock our BE `requestSave` call

2021-02-02 21:10 UTC, ajspotts commented on client/test/app/queue/AddCavcDatesModal.test.js
> +});
Added the 'submits successfully' test that will check for proper form submission.  Checking for the `Alert` component within the scope of this test isn't feasible as that component will not render until the `/queue` view where the user is redirected.  That test should be part of the feature test

2021-02-03 15:06 UTC, lomky approved these changes
:tada:

2021-02-03 16:20 UTC, merged