Check 'bgs_record_found?' before formatting the zip_code
department-of-veterans-affairs/caseflow pull request #15853
Opened 2021-02-01 16:08 UTC by charleyf

Resolves #15175

### Description
Minimal change to address problem with zip_code, see notes in 15175.

2021-02-01 21:32 UTC, yoomlam commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Can you add a test, if one doesn't already exists, that handles this scenario.

2021-02-01 21:34 UTC, yoomlam requested changes
Add a quick rspec to maintain high test code coverage.

2021-02-01 21:40 UTC, yoomlam commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Wondering if you should just `return ""` so that it's clear the rest of the method is irrelevant?
```suggestion
    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : return ""
```
Another question: do other callers of `zip_code` handle empty string appropriately?

2021-02-01 21:52 UTC, charleyf commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Ah, good point. I just added and pushed a test for this.

2021-02-01 22:04 UTC, charleyf commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Would pulling that return out into a guard clause like this make sense?
```
  def zip_code
    return "" if !bgs_record_found? 

    zip_code = bgs_record&.[](:zip_code)
    zip_code ||= (@address_line3 if (@address_line3 || "").match?(Address::ZIP_CODE_REGEX))
```

2021-02-01 22:05 UTC, yoomlam commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Yup! Even better!

2021-02-01 22:06 UTC, charleyf commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
I'm not sure about the callers of `zip_code`. I was making the assumption that an empty string would be better than an error, I'll see what I can find.

2021-02-01 22:06 UTC, yoomlam commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Have any commentary on this?
> Another question: do other callers of zip_code handle empty string appropriately?

2021-02-01 22:11 UTC, yoomlam commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Sometimes returning `nil` is the better option. For example, `nil` could represent it being not available from BGS, whereas an empty string may mean that BGS has an empty string saved in the zip code field, which may indicate some other interpretation. Whatever the decision, just ensure that callers of `zip_code` are aware of the possibility to return empty string -- they may want to react differently if `nil` is returned. 🤷

2021-02-01 22:20 UTC, charleyf commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Thanks! That's really helpful. I misunderstood what `zip_code` was returning. I thought it used to always return an empty string (nope).

Looking through the `veterans_spec.rb` file there are other tests that explicitly expect zip_code to be nil. Changing this to return nil is much more consistent with what it was doing AND what the tests expect. Thanks!

2021-02-01 22:27 UTC, yoomlam commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Please also check callers of `zip_code` in our application code (outside our tests) to see how they are reacting to `nil` versus some other value, which may or may not be a valid zip code. A quick grep shows that both Caseflow Hearings and Intake use `zip_code`; I recommend posting this PR to #appeals-engineering to get more 👀 on this.

2021-02-03 19:31 UTC, charleyf commented on app/models/veteran.rb
> +    zip_code = bgs_record_found? ? bgs_record&.[](:zip_code) : ""
Putting my notes here before posting to #appeals-engineering as Yoom suggested.

I looked through the ruby/rails code and it looks to me like we already expect zip to be nil in address.rb. I don't see any obvious effects in the other three files that seemed likely candidates: veteran.rb, appeal.rb, legacy_appeal.rb. Long notes are below.


I looked through the javascript code and as far as I can tell (long form notes below), zip_code is displayed only in a way that's not sensitive to the difference between an empty string, like this:
`<span>{city}, {state} {zip} {country === 'USA' ? '' : country}</span>`
The one exception is AddressForm.jsx, which is only used by AddClaimantPage.jsx, which is a foxtrot WIP.

**Backend Notes (from searching 'zip' in files with names containing 'rb'):**
```
# Uses zip
veteran.rb - This is the file I changed, I don't see any adverse effects.
appeal.rb - Delegates zip to veteran.rb, no obvious effect from this change
legacy_appeal.rb - Delegates zip to veteran.rb, no obvious effect from this change
address.rb - Deals with zips, already expects zip to be nil (rather than "")
# Never checks the value of zip
veteran_serializer.rb - Renames zip, doesn't care about the value stored.
veteran_details_serializer.rb - Renames zip, doesn't check the value.
address_mapper.rb - Renames zip, doesn't check the value.
```

**Frontend Notes (from searching 'zip' in files with names containing 'js'):**
```
// Display only
IssueRemandReasonsOptions.jsx - Using lodash's _.zip
AssignHearingModal.jsx - Displays zip as string
Address.jsx - Displays zip as string
utils.js - Renames variable, doesn't change zip
constants.js - Using lodash's _.zip
ErrorAlert.jsx - Reacts to zip, not sensitive to this change.
DailyDocketRowDisplayText.jsx - Displays zip as string
AssignHearingsFields.jsx - Displays zip as string
// Display only, uses Address.jsx
RepresentativeSection.jsx - Passes zip to Address.jsx, display only
AppellantSection.jsx - Passes zip to Address.jsx, display only
ScheduleVeteran.jsx - Sends zip to ScheduleVeteranForm.jsx
ScheduleVeteranForm.jsx - Passes it to Address.jsx
Address.jsx - Displays zip as string (there are two versions of this file, they display zip in the same way)
// Using location zip, not veteran
AppealHearingLocations.jsx - Not using the veteran zip code, using location zip code.
// Allows editing
AddressForm.jsx - Only used by the AddClaimantPage, as far as I can tell this form is non-functional (Continue never lights up).
```

2021-03-02 21:34 UTC, charleyf commented
> Add a quick rspec to maintain high test code coverage.

Afternoon Yoom, I think that [8367914](https://github.com/department-of-veterans-affairs/caseflow/pull/15853/commits/8367914de82495f025827750e02fc90e2d258baa) adds the requested rspec and completes the changes requested?

2021-03-03 15:41 UTC, yoomlam commented
@n1zyy Could you take a look at this and provide some input? I appreciate your thoroughness.

2021-03-03 16:37 UTC, yoomlam commented
This PR looks good to me. I'll let @n1zyy approve the PR once he examines callers of `zip_code`.

2021-03-03 16:52 UTC, n1zyy approved these changes
Approved with a couple trivial suggestions:

2021-03-03 16:52 UTC, n1zyy commented on spec/models/veteran_spec.rb
> +          expect(subject.zip_code).to eq nil
```suggestion
        it "returns nil when accessing zip_code" do
          expect(subject.zip_code).to be_nil
```

I'm satisfied with this test as covering the change you made. It's also clear that you did your due diligence on what uses the return value of this.

Two really pedantic suggestions here:
* I'd take "and no errors" out of the description because we're not explicitly asserting that; to me it sort of implies a `.not_to raise_exception(ExceptionClass)` assertion. (Really only useful in tests where we want to assert that we _do_ raise something.)
* While `.to eq nil` is entirely valid, the previous case uses `.to be_nil`.

Digression: that got me curious. The previous test also uses `.to eq(true)` instead of `.to be_true`, which feels contradictory.

`.be_nil` is apparently more common than `eq nil` on the project:

```
mattwagner@Matts-MacBook-Pro caseflow % ag ".to eq nil" | wc -l
      97
mattwagner@Matts-MacBook-Pro caseflow % ag ".to be_nil" | wc -l
     754
```

But that's not the same for true values, which overwhelmingly use `eq`:

```
mattwagner@Matts-MacBook-Pro caseflow % ag 'to be_true' | wc -l
       3
mattwagner@Matts-MacBook-Pro caseflow % ag 'to eq true' | wc -l
     206
```

But, apparently, when it's _false_, the opposite is true:

```
mattwagner@Matts-MacBook-Pro caseflow % ag 'to eq false' | wc -l
     129
mattwagner@Matts-MacBook-Pro caseflow % ag 'to be_false' | wc -l
     215
```

I'm not sure what lesson to take away from this. 😆 We should maybe find a standard, but in the meantime I'd go with Wikipedia's [consistency within articles policy](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Consistency_within_articles) / [retaining the existing variety](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Retaining_the_existing_variety) policy for sticking with one.

2021-03-03 16:54 UTC, yoomlam approved these changes

2021-03-03 19:30 UTC, merged