WIP adding Different select box
department-of-veterans-affairs/caseflow pull request #15915
Opened 2021-02-18 17:14 UTC by ajspotts

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-02-18 18:03 UTC, lomky commented on client/app/queue/AddCavcRemandView.jsx
> +
oh this was supposed to be deleted!

2021-02-24 17:15 UTC, ajspotts commented on client/test/app/queue/AddCavcRemandView.test.js
> +
As the mandate & judgement dates will now be hidden by default, we must make them show for the test by manually selecting "No" for the "Are judgement and mandate dates provided?" field

2021-02-24 17:17 UTC, ajspotts commented on client/app/queue/AddCavcRemandView.jsx
> +  }, [isMandateSame, decisionDate]);
every time the `isMandateSame` checkbox or decision date field is altered we want to update the judgement and mandate dates

2021-02-24 17:20 UTC, ajspotts commented on client/app/queue/AddCavcRemandView.jsx
> +        mandate_date: (remandType() && mdrSubtype()) || !mandateAvailable() ? null : mandateDate,
if it is an mdr or the user has selected "No" on the "Are judgement and mandate dates provided?" field for straight reversal or death dismissal we send null, otherwise send the selected dates

2021-02-24 18:38 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> +  const mandateSame = () => Boolean(isMandateSame);
Why not use `isMandateSame` directly and remove this line?

2021-02-24 18:53 UTC, ajspotts commented on client/app/queue/AddCavcRemandView.jsx
> +  const mandateSame = () => Boolean(isMandateSame);
I suppose that it probably is a redundant check, updating

2021-02-24 19:13 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> -  // We accept ‐ HYPHEN, - Hyphen-minus, − MINUS SIGN, – EN DASH, — EM DASH
Why remove this comment line?

2021-02-24 19:19 UTC, ajspotts commented on client/app/queue/AddCavcRemandView.jsx
> -  // We accept ‐ HYPHEN, - Hyphen-minus, − MINUS SIGN, – EN DASH, — EM DASH
Accidental from a merge conflict fix - re-adding!

2021-02-24 21:36 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> +        mandate_date: (remandType() && mdrSubtype()) || !mandateAvailable() ? null : mandateDate,
I think you mean this:
```suggestion
        judgement_date: ((remandType() && mdrSubtype()) || !mandateAvailable()) ? null : judgementDate,
        mandate_date: ((remandType() && mdrSubtype()) || !mandateAvailable()) ? null : mandateDate,
```
A test would have caught this bug.

2021-02-24 21:36 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> +        mandate_date: (remandType() && mdrSubtype()) || !mandateAvailable() ? null : mandateDate,
Really appreciate this comment expressing the intent of the code.

2021-02-24 21:37 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> +        remand_subtype: remandType() ? subType : null,
Great minds! I did this in my PR as well: https://github.com/department-of-veterans-affairs/caseflow/pull/15931/files#diff-b85b25230374ea05c80f39f554df6373cfd640c751c1d4c1006729284730821aL354

2021-02-24 21:39 UTC, yoomlam commented on client/COPY.json
> +  "CAVC_REMAND_MANDATE_DIFFER_DESCRIPTION": "Same as Court's decision date",
Nit: `DIFFER` inconsistent with "Same"
```suggestion
  "CAVC_REMAND_MANDATE_DATES_LABEL": "Judgement and mandate date",
  "CAVC_REMAND_MANDATE_DATES_SAME_DESCRIPTION": "Same as Court's decision date",
```

2021-02-24 21:40 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> +  const mandateSameField = <>
Nit
```suggestion
  const mandateDatesSameField = <>
```

2021-02-24 21:40 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> +      name="remand-different-toggle"
```suggestion
      name="mandate-dates-same-toggle"
```

2021-02-24 21:41 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> +    errorMessage={highlightInvalid && !validJudgementDate() && !isMandateSame ? COPY.CAVC_JUDGEMENT_DATE_ERROR : null}
```suggestion
    errorMessage={(highlightInvalid && !validJudgementDate() && !isMandateSame) ? COPY.CAVC_JUDGEMENT_DATE_ERROR : null}
```

2021-02-24 21:41 UTC, yoomlam commented on client/app/queue/AddCavcRemandView.jsx
> +    errorMessage={highlightInvalid && !validMandateDate() && !isMandateSame ? COPY.CAVC_MANDATE_DATE_ERROR : null}
```suggestion
    errorMessage={(highlightInvalid && !validMandateDate() && !isMandateSame) ? COPY.CAVC_MANDATE_DATE_ERROR : null}
```

2021-02-24 21:49 UTC, yoomlam requested changes
Some nits and suggestions.
How about adding a test that fills in the mandate dates, mark the "Same as Court's decision date" checkbox true, fills in the dates with different dates, unmarks the checkbox, and submits? The test would expect the dates to be the same.

2021-02-24 22:27 UTC, ajspotts commented
> Some nits and suggestions.
> How about adding a test that fills in the mandate dates, mark the "Same as Court's decision date" checkbox true, fills in the dates with different dates, unmarks the checkbox, and submits? The test would expect the dates to be the same.

The "Same as Court's decision date" is checked by default so the dates can only be selected when it us unchecked (false). I'm attempting to write a test that captures the behavior of selecting checkbox, adding dates, reselecting checkbox then submitting but I'm having trouble getting the checkbox reselected.  Thinking it's because it's already passed this portion of the form and can't re-locate the element.  I've recorded a screen capture of the behavior you're looking for is this sufficient for you? 
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/18618189/109074217-78aa6580-76c5-11eb-8135-7a961bbc6a2e.gif)

2021-02-24 22:54 UTC, yoomlam commented
> > Some nits and suggestions.
> > How about adding a test that fills in the mandate dates, mark the "Same as Court's decision date" checkbox true, fills in the dates with different dates, unmarks the checkbox, and submits? The test would expect the dates to be the same.
> 
> The "Same as Court's decision date" is checked by default so the dates can only be selected when it us unchecked (false). I'm attempting to write a test that captures the behavior of selecting checkbox, adding dates, reselecting checkbox then submitting but I'm having trouble getting the checkbox reselected. Thinking it's because it's already passed this portion of the form and can't re-locate the element. I've recorded a screen capture of the behavior you're looking for is this sufficient for you?
> ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/18618189/109074217-78aa6580-76c5-11eb-8135-7a961bbc6a2e.gif)

2021-02-24 23:21 UTC, yoomlam approved these changes
🎉 Nice work!

2021-02-24 23:25 UTC, yoomlam commented on spec/feature/queue/cavc_task_queue_spec.rb
> +          fill_in "mandate-date", with: later_date
Maybe add a comment before these lines to state that these dates are expected to be ignored because we're toggling the checkbox?

2021-02-24 23:26 UTC, ajspotts commented on spec/feature/queue/cavc_task_queue_spec.rb
> +          fill_in "mandate-date", with: later_date
Good idea!

2021-02-25 05:20 UTC, merged