Persistent case details banner for docket switch
department-of-veterans-affairs/caseflow pull request #15939
Opened 2021-02-26 14:00 UTC by wdrougas-tista

Resolves [Jira 872](https://vajira.max.gov/browse/CASEFLOW-872)

### Description
Persistent banner is rendering on case details page for both the new and old appeal stream after a partial grant and on the old appeal stream after a full grant

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

2021-03-01 23:51 UTC, wdrougas-tista commented
<img width="839" alt="Screen Shot 2021-03-01 at 6 50 26 PM" src="https://user-images.githubusercontent.com/63597932/109575110-2bf8cd00-7abf-11eb-9172-1e676a20cc89.png">

2021-03-02 15:42 UTC, nanotone requested changes
Just some suggestions on the backend/serializer portion!

2021-03-02 15:42 UTC, nanotone commented on app/models/appeal.rb
> +    DocketSwitch.find_by(old_docket_stream_id: self.id)
Since an appeal can conceivably be switched to multiple new streams, and case details page will eventually want to address that as well, it might be nice to get ahead and lay the foundation here.

If you use `where` instead of `find_by` ActiveRecord will return all of them.

2021-03-02 15:42 UTC, nanotone commented on app/models/serializers/work_queue/appeal_serializer.rb
> +  end
Since the `docket_switch` includes the `old_docket_stream`, and the `switched_docket` includes the `new_docket_stream` it might make sense to tidy this up and keep the data DRY.

It looks like all the frontend needs is the disposition and source/destination UUIDs, so you could get a lot of mileage out of this [docket switch serializer](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/docket_switches_controller.rb#L35).

2021-03-03 02:07 UTC, wdrougas-tista commented
@nanotone Changes have been pushed!

2021-03-03 15:00 UTC, nanotone approved these changes
Hi Will, I have a few cosmetic and testing comments but I'll approve this. Great work!

2021-03-04 22:41 UTC, merged