Added time slot component behind feature flag
department-of-veterans-affairs/caseflow pull request #15936
Opened 2021-02-25 17:11 UTC by sahalliburton

Resolves [CASEFLOW-955](https://vajira.max.gov/browse/CASEFLOW-955)

### Description
Adds 2 new components `TimeSlot` and `TimeSlotButton` and hides the new components behind a feature flag. Additionally, there is placeholder calls to the backend for when we connect this PR

### Acceptance Criteria
- [x] put work behind feature toggle
- [x] one storybook component for a single button which will display as design (time, issue count, appeal type, poa name, disable flag)
- [x] another storybook component that displays list of above buttons given a list of data
  - list of data would include available slots + taken slots 
  - available slots would be generated based on the 8:30 RO time start time to 3:30 est end time
- [x] taken slots should be disabled
  - use fake data (collaborate with the person working https://vajira.max.gov/browse/CASEFLOW-954 on data format) to generate button components on the fly
- [x] When a hearing is scheduled for a custom time that does not match a time slot, hide any time slot buttons that are less than one hour after the custom time (e.g., after a 12:15pm custom time the 12:30pm button would be hidden but 1:30pm and all buttons after would be visible)
- [x] allow the toggle of old style dropdown
- [x] Time permitting: do the Redux work described in CASEFLOW-956

### Testing Plan
1. Shadow user `BVASYELLOW`: http://localhost:3000/test/users
2. Navigate to the hearings app and click "Schedule Veterans"
3. Search for "St. Petersburg FL" in the list and choose one of the veterans in the AMA waiting tab
4. Click the "Schedule Veteran" button from the dropdown
5. Ensure that you are still able to schedule a veteran with the existing radio buttons
6. On the rails console, enable the feature flag: `FeatureToggle.enable!(:enable_hearing_time_slots)`
7. Repeat steps 2 - 5
8. Ensure that this time you see the new time slot options

### User Facing Changes
 - [x] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---
-- | <img width="997" alt="Screen Shot 2021-02-25 at 9 01 02 AM" src="https://user-images.githubusercontent.com/61989526/109189724-2dd23180-7749-11eb-913b-47a251944ea3.png">
-- |<img width="1031" alt="Screen Shot 2021-02-25 at 9 01 13 AM" src="https://user-images.githubusercontent.com/61989526/109189751-36c30300-7749-11eb-807d-8f8caa23dee1.png">

### Code Documentation Updates
- [x] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [x] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [x] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [x] Write a separate story (within the same file) for each discrete variation of the component

2021-02-26 01:48 UTC, rubaiyat22 requested changes
This is looking really good! 
i had some blocking suggestions that i think need to addressed. The rest are some suggestions which are non blocking.

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +      return (time.includes(slot.hearingTime) && slot.full) || !hours.includes(slot.hearingTime.split(':')[0]);
According to the AC, only slots occurring one hour after a custom hearing time should be filtered out, not before:
> When a hearing is scheduled for a custom time that does not match a time slot, hide any time slot buttons that are less than one hour after the custom time (e.g., after a 12:15pm custom time the 12:30pm button would be hidden but 1:30pm and all buttons after would be visible)

E.g. 10:45 custom time should not filter out 10:30.
<img width="687" alt="Screen Shot 2021-02-25 at 8 13 38 PM" src="https://user-images.githubusercontent.com/20735998/109240709-f80f6600-77a5-11eb-89be-df3053a58d8c.png">

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +      return (time.includes(slot.hearingTime) && slot.full) || !hours.includes(slot.hearingTime.split(':')[0]);
This does not filter out slots that occur within one hour as per the AC:
>When a hearing is scheduled for a custom time that does not match a time slot, hide any time slot buttons that are less than one hour after the custom time (e.g., after a 12:15pm custom time the 12:30pm button would be hidden but 1:30pm and all buttons after would be visible)

E.g. 8:45 and 9:30 are within one hour of each other yet both appear.
<img width="711" alt="Screen Shot 2021-02-25 at 8 08 02 PM" src="https://user-images.githubusercontent.com/20735998/109240269-2e001a80-77a5-11eb-8851-244e7acfaa52.png">

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +      return (time.includes(slot.hearingTime) && slot.full) || !hours.includes(slot.hearingTime.split(':')[0]);
I think `time.includes(slot.hearingTime) && slot.full` is redundant b/c `const time` == `scheduledHearings.map((hearing) => hearing.hearingTime);` (L509) and `slot.full` == `scheduledHearings.map((hearing) => hearing.hearingTime).includes(slot.hearingTime)` (L504),
so this check should just be `slot.full`.

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +  return _.sortBy(slots, 'hearingTime');
We should return slots only upto 3:30 EST by default as per AC:
>available slots would be generated based on the 8:30 RO time start time to 3:30 est end time

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +      const hours = scheduledHearings.map((hearing) => hearing.hearingTime.split(':')[0]);
Following lines can be moved out of the loop and done at the start instead of processing for ever slot.

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +      full: scheduledHearings.map((hearing) => hearing.hearingTime).includes(slot.hearingTime),
Instead of calculating `full` here, you could add it as a field to each hearing in `scheduledHearings` ahead of time, it would save from doing this map/filter.
Alternatively, since you're implicitly relying on `slot.hearingTime` to be `undefined` for available slots to set this `full`value, you can just test `slot.hearingTime !== undefined` or something similar.

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/hearings/components/scheduleHearing/TimeSlotButton.jsx
> +export const TimeSlotButton = ({
I don't know if this should be different but i noticed that when i hovered over selected slots it does not show the time
<img width="360" alt="Screen Shot 2021-02-25 at 8 28 34 PM" src="https://user-images.githubusercontent.com/20735998/109241943-3a39a700-77a8-11eb-9aa9-3b299250f4b7.png">

2021-02-26 01:48 UTC, rubaiyat22 commented on app/views/hearings/index.html.erb
> +  userCanViewTimeSlots: FeatureToggle.enabled?(:enable_hearing_time_slots, user: current_user),
do you need this here? I'm not seeing it used anywhere in the hearings app

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/queue/QueueApp.jsx
> +          <ScheduleVeteran
I'm not sure if this is the scope of the ticket but with the toggle on i could not schedule the veteran for a hearing as it would not let me submit.
![captured (3)](https://user-images.githubusercontent.com/20735998/109242621-702b5b00-77a9-11eb-81c7-20f799e194df.gif)

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/components/common/actions.js
> +export const fetchScheduledHearings = () => (dispatch) => {
This is obviously not part of this PR but I'm curious where would we would add the code that makes the request to fetch the hearing times?

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/components/common/actionTypes.js
> +  REQUEST_SCHEDULED_HEARINGS: 'REQUEST_SCHEDULED_HEARINGS',
nitpick:
`REQUEST_SCHEDULED_HEARINGS` and `REQUEST_SCHEDULED_HEARINGS` could renamed to  `SET_SCHEDULE_HEARING_TIMES_PAYLOAD` and `REQUEST_SCHEDULED_HEARINGS_TIMES`

2021-02-26 01:48 UTC, rubaiyat22 commented on client/app/queue/QueueApp.jsx
> +          <ScheduleVeteran
I experienced the same thing when switching back to a custom dropdown as well (with feature toggle on)

2021-02-26 15:21 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +export const setTimeSlots = (hearings) => {
Because this function determines important logic, could you write just some unit tests for it with different scenarios perhaps you would add to client/test/app/hearings/components/scheduleHearing/TimeSlot.test.js

2021-02-26 15:21 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +  // Filter the hearing time options by 30 minutes increments or filled hearing times
This comment is a bit misleading to me. i think it could say something like "Filter the hearing time options that have '30' in them or filled hearing times"

2021-02-26 22:08 UTC, sahalliburton commented on client/app/hearings/components/scheduleHearing/TimeSlotButton.jsx
> +export const TimeSlotButton = ({
Thanks for catching that I was able to fix this by adding a hover class

2021-02-26 22:08 UTC, sahalliburton commented on client/app/queue/QueueApp.jsx
> +          <ScheduleVeteran
Thanks for noticing this, it turns out I was passing the wrong function to the TimeSlot component, it should be fixed now

2021-02-26 22:10 UTC, sahalliburton commented on client/app/components/common/actions.js
> +export const fetchScheduledHearings = () => (dispatch) => {
The code for sending the request would live in this function and would wrap the second dispatch in the async call to the endpoint you setup, something like: 

```
dispatch({ type: request_action })

ApiUtil.get('/endpoint', (data) => {
   dispatch({ type" success_action, payload: data.hearings })
}
```

2021-03-01 16:43 UTC, rubaiyat22 approved these changes
LGTM! approved with one blocking comment about the slot algo but it's a small fix

2021-03-01 16:43 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +      return interval >= 0 && interval <= 60;
```suggestion
      return interval >= 0 && interval < 60;
```
i think this should be strictly less than 60 because otherwise it does not show the `10:30` slot.
<img width="760" alt="Screen Shot 2021-03-01 at 11 15 59 AM" src="https://user-images.githubusercontent.com/20735998/109525468-8c681a00-7a7f-11eb-9525-6b452e2bda1a.png">

2021-03-01 16:43 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +import HEARING_TIME_OPTIONS from '../../constants/HEARING_TIME_OPTIONS';
```suggestion
```
you can remove this now

2021-03-01 16:43 UTC, rubaiyat22 commented on client/app/hearings/components/scheduleHearing/TimeSlot.jsx
> +  const hearingTimeId = `hearing-time-${hearing?.scheduledTimeString}`;
I saw a warning about two buttons with the same schedueldTimeString getting a warning. I think we could use the hearing day id here as an unique identifier
<img width="664" alt="Screen Shot 2021-03-01 at 11 35 51 AM" src="https://user-images.githubusercontent.com/20735998/109528018-482a4900-7a82-11eb-951a-f1d6842a2c41.png">

2021-03-01 16:43 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +export const setTimeSlots = (hearings) => {
thanks for adding the tests!

2021-03-01 17:11 UTC, rubaiyat22 commented on client/app/hearings/utils.js
> +    key: `${slot?.externalId}-${slot?.hearingTime}`,
I'm currently not returning that as a data point but let's add it as part of the integration ticket unless you think i should add it her ehttps://github.com/department-of-veterans-affairs/caseflow/pull/15930

2021-03-01 17:12 UTC, sahalliburton commented on client/app/hearings/utils.js
> +    key: `${slot?.externalId}-${slot?.hearingTime}`,
No I think it makes sense to add it in the next ticket because then we can just write tests against it there

2021-03-01 19:10 UTC, merged