Add receipt date validation to grant docket switch form
department-of-veterans-affairs/caseflow pull request #15960
Opened 2021-03-03 22:06 UTC by meckila-navapbc

Resolves [CASEFLOW-1055](https://vajira.max.gov/browse/CASEFLOW-1055)

### Description
Add validation for receipt date 

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. TBA

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-03-03 23:29 UTC, jcq commented on client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
> +          errorMessage={errors.receiptDate?.message}
I think this will solve the issue:
```js
errorMessage={touched.receiptDate && errors.receiptDate?.message}
```

2021-03-03 23:31 UTC, jcq commented on client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
> +          errorMessage={errors.receiptDate?.message}
Where `touched` comes from `formState`: 

```js
const { isValid, touched } = formState;
```

This actually is perhaps a better way to handle `isValid` as well, as the docs recommend this syntax:
https://react-hook-form.com/api/#formState

2021-03-04 00:57 UTC, meckila-navapbc commented on client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
> +          errorMessage={errors.receiptDate?.message}
@jcq Thank you. Using form state is working.

2021-03-05 18:38 UTC, meckila-navapbc commented on client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
> +          errorMessage={touched.receiptDate && isDirty && errors.receiptDate?.message}
Added isDirty as leaving form field would trigger validation message:
<img width="895" alt="Screen Shot 2021-03-05 at 10 38 28 AM" src="https://user-images.githubusercontent.com/68879427/110159006-f691ff00-7d9e-11eb-8c02-ed3bae57bd23.png">

2021-03-05 18:47 UTC, meckila-navapbc commented on client/test/app/queue/docketSwitch/DocketSwitchReviewRequestForm.test.js
> -    const disposition = 'partially_granted';
This code was not getting used in the test

2021-03-05 19:06 UTC, jcq commented on client/test/app/queue/docketSwitch/DocketSwitchReviewRequestForm.test.js
> +    const futureDate = new Date().getDate() + 1;
This needs to be an ISO-formatted string, so something like this would work:

```js
// Add to imports
import { add, format } from 'date-fns';

// This will generate a string of correct format for 5 days in future
const futureDate = format(add(new Date(), { days: 5 }), 'yyyy-MM-dd');
```

2021-03-05 19:50 UTC, jcq commented on client/test/app/queue/docketSwitch/DocketSwitchReviewRequestForm.test.js
> +
So in addition to the `change` event, you'll need to trigger it to think the form field has been `touched`. You should be able to do so via this:

```js
await fireEvent.blur(screen.getByLabelText(/receipt date/i));
```

2021-03-05 22:21 UTC, jcq requested changes
Looking good! Just one suggested improvement

2021-03-05 22:21 UTC, jcq commented on client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
> +  receiptDate: yup.date().required().
I think adding this (in addition to everything you have) to the schema for `receiptDate` might make it slightly better:

```js
  nullable().
  transform((value, origValue) => origValue === '' ? null : value).
```

2021-03-05 22:21 UTC, jcq commented on client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
> +  receiptDate: yup.date().required().
This should prevent this error from showing up:
```
receiptDate must be a `date` type, but the final value was: `Invalid Date` (cast from the value `""`).
```

2021-03-05 22:53 UTC, meckila-navapbc commented on client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
> +  receiptDate: yup.date().required().
Ah, I had tried a variation of this but without the nullable portion!

2021-03-05 23:47 UTC, jcq approved these changes
Looks good!

2021-03-06 01:05 UTC, merged