Rewrite Alert karma test for jest
department-of-veterans-affairs/caseflow pull request #15972
Opened 2021-03-08 21:13 UTC by meckila-navapbc

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Test should check alert type renders properly
- [ ] Test should check that 
- [ ] Test should check window scrolls to top if `scrollOnAlert` set to true

2021-03-08 21:41 UTC, jcq requested changes
Looking really good! I'd say we should add a snapshot to each test case just to be comprehensive, as well as a call to `jest-axe` for each as well

2021-03-08 23:56 UTC, jcq commented on client/test/app/components/Alert.test.js
> +  describe('shows correct alert type', () => {
Actually, this is a prime candidate for using Jest's `describe.each` functionality ([see docs](https://jestjs.io/docs/en/api#describeeachtablename-fn-timeout)).

You can probably do something like this:

```js
describe('Alert', () => {
  const title = 'This is a title';
  const types = ['error', 'info', 'success', 'warning'];

  describe.each(types)('alert type: %s', (type) => {
    const props = { title, type };

    it(`renders correctly for ${type}`, () => {
      const component = render(<Alert {...props} />);

      expect(component).toMatchSnapshot();
    });

    it(`passes a11y testing for ${type}`, async () => {
      const { container } = render(<Alert {...props} />);

      const results = await axe(container);

      expect(results).toHaveNoViolations();
    });
  });
});
```

You could actually likely restructure things to put all of your tests in there, and really DRY out your code (which would probably make CodeClimate happy)

2021-03-09 00:56 UTC, jcq commented on client/test/app/components/Alert.test.js
> +    const props = { title, message, type };
The DRYing of the code is great! 

The only issue is that you ended up losing having a test that covers a version w/o the `message` prop

2021-03-09 00:57 UTC, jcq approved these changes
Looking really good! I think you want to add back one set of tests for the variation where `message` prop is undefined, but other than that should be GTG!

2021-03-09 01:45 UTC, meckila-navapbc commented on client/test/app/components/Alert.test.js
> +    const props = { title, message, type };
Noted. Added test to check when message is undefined

2021-03-09 02:30 UTC, merged