Karinamzalez/1059 task labels
department-of-veterans-affairs/caseflow pull request #15980
Opened 2021-03-09 17:18 UTC by karinamzalez

Resolves https://vajira.max.gov/browse/CASEFLOW-1059

### Description
- [x] docket switch mail task marked as completed in db
- [x] docket switch ruling task AND decision tasks (granted/denied) marked as completed in db
- [x] update completed docket switch task copy from "decision drafted by an attorney" to
	- [x] when granted: "Docket Switch Completed"
	- [x] when denied: "Docket Switch Denied" 
- [x] update completed mail task copy to "Docket Switch Mail Task Completed"

### User Facing Changes

 BEFORE|AFTER

<img width="424" alt="before_screenshot" src="https://user-images.githubusercontent.com/14364118/110510510-dd53c000-80c8-11eb-8875-4c911699f9e6.png"> | <img width="612" alt="Screen Shot 2021-03-09 at 11 01 53 AM" src="https://user-images.githubusercontent.com/14364118/110510433-cb721d00-80c8-11eb-8bb5-ba4cd42ada1a.png">

2021-03-10 14:32 UTC, wdrougas-tista requested changes
Just a couple small changes but otherwise looks good!

2021-03-10 14:32 UTC, wdrougas-tista commented on app/workflows/docket_switch/task_handler.rb
> +
Everything looks good here but the `DocketSwitchRulingTask` was not updating to "completed" here. I think it has to do with the use of `where` here which will return an array with the `DocketSwitchRulingTask` inside it and so the `.update` call wasn't saving. The code below worked for me 

If you use a `find_by` that will give you the object itself

```
    decision_task = DocketSwitchGrantedTask.find_by(appeal: old_docket_stream, assigned_to_type: "User") || DocketSwitchDeniedTask.find_by(appeal: old_docket_stream, assigned_to_type: "User")

    if decision_task
      decision_task.update(status: Constants.TASK_STATUSES.completed)
      # if switch is granted or denied, then ruling task should also be completed
      DocketSwitchRulingTask.find_by(appeal: old_docket_stream).update(status: Constants.TASK_STATUSES.completed)
    end
```

2021-03-10 16:50 UTC, nanotone commented on app/workflows/docket_switch/task_handler.rb
> +
Remember that as per the new task tree structure (see [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1612376085529/6daa6e6d8fee6e9b42da4a4a0cd1be59c0dc9884)) there are two Granted or Denied tasks. One way to query for all of them, without the awkwardness of `||`ing together two queries, is to use their shared superclass:

```ruby
DocketSwitchAbstractAttorneyTask.where(appeal: old_docket_stream)
```

and ActiveRecord will magically give you all Granted or Denied tasks.

Also, I think you don't need the `if decision_task`, since this method will only be called when there's a ruling task and granted-or-denied tasks to be closed.

2021-03-10 17:46 UTC, wdrougas-tista commented on app/workflows/docket_switch/task_handler.rb
> +
Scratch my previous comment above. The issue appears to be that I'm not hitting the `completed_docket_switch_tasks` method when the Docket switch is denied. All of Yang's recommendations are working as well

2021-03-10 18:35 UTC, nanotone commented on app/models/task.rb
> +    "#{type.titleize} completed"
Since you've overridden `timeline_title` for the two subclasses, I think this change can be left out. It would affect the default implementation for around 100 other classes, so I'm a bit hesitant to include it in a bugfix PR.

2021-03-17 19:18 UTC, karinamzalez commented on app/workflows/docket_switch/task_handler.rb
> +
@wdrougas-tista The DocketSwitchRulingTask was getting completed -- it just had a timeline title that read "Decision signed by judge". Checked in with Rutvi to ask if I should update this and I've updated the timeline title to read "Docket Switch Ruling Task". Should be more straight forward now :)

2021-03-18 18:15 UTC, nanotone approved these changes
Just verified that the Ruling and Attorney tasks get correctly completed at the end of the full deny flow. 🎉 🚀

2021-03-18 18:56 UTC, closed without merging