Add hearing to original_request_type/changed_request_type database fields and accompanying code
department-of-veterans-affairs/caseflow pull request #16049
Opened 2021-03-25 18:10 UTC by Jeremy1026

Resolves #15880

### Description
Renamed `original_request_type` to `original_hearing_request_type` and `changed_request_type` to `changed_hearing_request_type` in the database and throughout the codebase.

### Acceptance Criteria
- [ ] Code compiles correctly

### Database Changes

* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR

2021-03-29 16:50 UTC, ajspotts approved these changes
Nice changes lgtm!

2021-04-01 18:42 UTC, rubaiyat22 requested changes
Thanks for making those changes. I have some blocking suggestions but lmk if you have any questions.

2021-04-01 18:42 UTC, rubaiyat22 commented on app/models/legacy_hearing.rb
> +  def original_hearing_request_type
This method should stay as `original_request_type` as we know when it is the hearing request type because it'll be referred to something like `hearing.original_request_type`

2021-04-01 18:42 UTC, rubaiyat22 commented on app/models/hearing.rb
> +  alias original_hearing_request_type request_type
This method should stay as `original_request_type` as we know when it is the hearing request type because it'll be referred to something like `hearing.original_request_type`

2021-04-02 14:24 UTC, Jeremy1026 commented on app/models/hearing.rb
> +  alias original_hearing_request_type request_type
Made the revision to put back this back.

2021-04-02 14:24 UTC, Jeremy1026 commented on app/models/legacy_hearing.rb
> +  def original_hearing_request_type
Made the revision to put back this back.

2021-04-05 18:10 UTC, merged