EP Claim Label Add success alert and redirect to Case Earch Page after edit
department-of-veterans-affairs/caseflow pull request #16054
Opened 2021-03-26 01:41 UTC by meckila-navapbc

Resolves [CASEFLOW-365](https://vajira.max.gov/browse/CASEFLOW-365)

### Description
Add redirect to search page after EP Claim label edit and show success alert

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Page redirects to **Veteran Case Search**
- [ ] Success alert appears at top of search page 

### Testing Plan
1. Search for to a supplemental claim or higher level review that has been established
2. Click **Review Type** link
3. Click **Edit Claim Label**
4. Submit edit
5. Verify that page redirects to **Veteran Case Search** and success alert appears on page

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---
<img width="1155" alt="Screen Shot 2021-03-25 at 6 37 34 PM" src="https://user-images.githubusercontent.com/68879427/112564862-40b44200-8d99-11eb-8cc0-f3605890fb90.png">|TBA

2021-03-31 22:26 UTC, nanotone requested changes
Left a few suggestions, including one possible approach on the veteran ID issue.

2021-03-31 22:26 UTC, nanotone commented on client/app/intakeEdit/actions/edit.js
> +        history.back();
I don't think `history.back()` will always necessarily send the user to the veteran search results page -- for example, when I navigate to the edit-issues page directly from a fresh tab, `history.back()` just returns to a blank page.

I also took a look at the Redux store for the edit-issues page, and didn't see a veteran ID anywhere. Fortunately, since this code is in the response handler for a brand new backend endpoint, we can just send the veteran ID from the backend. Look at how wasteful this [response payload](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/claim_review_controller.rb#L35) is!

Lemme know if you want to pair on this approach; it's pretty straightforward but has fingers in many disparate pies... (?)

2021-03-31 22:26 UTC, nanotone commented on spec/feature/intake/edit_ep_claim_labels_spec.rb
> +      sleep 1
Now that the frontend actually reacts to the XHR, there's probably a neat Capybara trick to say "wait until the frontend has changed" because `sleep 1` is pretty undesirable.

2021-03-31 23:27 UTC, meckila-navapbc commented on client/app/intakeEdit/actions/edit.js
> +        history.back();
@nanotone Ah, I didn't consider coming from a fresh tab. Would like to pair. I can start by looking at the `EndProductUpdate` model

2021-03-31 23:46 UTC, meckila-navapbc commented on client/app/intakeEdit/actions/edit.js
> +        history.back();
Actually was able to pass id from the claim review.veteran

2021-04-01 21:51 UTC, nanotone approved these changes
The changes look good! Once the ❌s in the automated checks are cleared, this is ready to merge. Lemme know if you want help clearing them.

2021-04-02 14:15 UTC, merged

2021-04-02 16:10 UTC, meckila-navapbc commented
@nanotone Thank you for adding that fix! I see it's merged into master now