WIP: Eileen/15220 validate one task open
department-of-veterans-affairs/caseflow pull request #16072
Opened 2021-03-30 20:48 UTC by eileen-nava

Resolves #15220 

### Description
Add a validation that ensures only one `JudgeAssignTask` can be created at a time. This functionality can be extended to other tasks where there should only be one, such as `ChangeHearingDispositionTask`.  I am leaving that work for another PR.

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] No existing tests break
- [ ] There is test coverage for the new validation
- [ ] It is still possible to reassign a judge to a case through the UI

### Testing Plan
1. Ensure that automated tests pass.
2. While running the site locally, test the reassign judge scenario
- Switch to user BVAAABSHIRE (VACO)
- Find an appeal that has a JudgeAssignTask already associated with it
- In the “currently active tasks” section, select “re-assign judge”
![ReassignJudge](https://user-images.githubusercontent.com/80347702/113054344-4d5cdf80-9177-11eb-9cde-f4f601b659c3.png)
- Ensure that you can still re-assign a judge without getting any error messages
3. Through rails console, test that a second JudgeAssignTask cannot be made for the same appeal

2021-03-31 16:03 UTC, eileen-nava commented
Question for reviewers: 

The change I made broke capybara tests.  I think the spec in `/spec/feature/queue/judge_assignment_spec.rb` has [incorrect setup](https://github.com/department-of-veterans-affairs/caseflow/blob/eileen/15220-validate-one-task-open/spec/feature/queue/judge_assignment_spec.rb#L49).  Here is the error message I got

```
  1) Judge assignment to attorney and judge Can move appeals between attorneys submits draft decision
     Failure/Error: check judge_task_one.id.to_s, allow_label_click: true
     
     Capybara::ElementNotFound:
       Unable to find visible checkbox "1" that is not disabled
     # ./spec/feature/queue/judge_assignment_spec.rb:69:in `block (4 levels) in <top (required)>'
     # ./spec/support/feature_helper.rb:60:in `step'
     # ./spec/feature/queue/judge_assignment_spec.rb:67:in `block (3 levels) in <top (required)>'
```

When I looked at this test set-up, it creates two judge assign tasks for the same appeal and judge[ in lines 51 & 52](https://github.com/department-of-veterans-affairs/caseflow/blob/eileen/15220-validate-one-task-open/spec/feature/queue/judge_assignment_spec.rb#L51).

````
      judge_task_one = create(:ama_judge_assign_task, :in_progress, assigned_to: judge_one.user, appeal: appeal_one)
      judge_task_two = create(:ama_judge_assign_task, :in_progress, assigned_to: judge_one.user, appeal: appeal_two)
````

I _think_ I could preserve spirit of the test by deleting the `judge_task_two` from line 52 and[ all its related assertions](https://github.com/department-of-veterans-affairs/caseflow/blob/eileen/15220-validate-one-task-open/spec/feature/queue/judge_assignment_spec.rb#L70), but keeping the set-up and assertions for `judge_task_one`.  I plan on taking the same approach to fixing the broken tests in the context [“encounters an error assigning a case,”](https://github.com/department-of-veterans-affairs/caseflow/blob/eileen/15220-validate-one-task-open/spec/feature/queue/judge_assignment_spec.rb#L210) which also creates multiple `JudgeAssignTask`s for the same judge and appeal.

I'd appreciate feedback on this, please!

2021-04-19 21:07 UTC, eileen-nava commented on app/models/task.rb
> +    return @latest_attorney_case_review if defined?(@latest_attorney_case_review) && !@latest_attorney_case_review.nil?
`defined?(@latest_attorney_case_review)` will return true if `@latest_attorney_case_review=nil`.  This seems less than desirable. 🤔

2021-04-19 21:21 UTC, eileen-nava commented on app/models/task.rb
> +        task_to_validate.save(validate: false)
I also looked up ways to [skip a specific validation](https://stackoverflow.com/questions/8881712/skip-certain-validation-method-in-model), but decided to instead use `.save(validate: false)` within a conditional.

2021-04-19 21:29 UTC, eileen-nava commented on app/workflows/judge_assign_task_creator.rb
> +  def close_distribution_tasks_for_appeal
I had to expose this previously private method so that I could call it in the `hearing_request_case_distributor.rb`.

2021-04-21 13:14 UTC, n1zyy reviewed
I owe this a proper review, but was excited to see it so I jumped in before I had time to devote to a full review.

I left a couple few inline comments, but overall this looks awesome!

2021-04-21 13:14 UTC, n1zyy commented on spec/models/appeal_spec.rb
> +      subject { appeal.assigned_judge }
🤔 Can we pull this `subject` up a level if it's the same in both contexts?

2021-04-21 13:14 UTC, n1zyy commented on spec/models/dockets/hearing_request_docket_spec.rb
> +    context "when an appeal already has a distribution" do
😍

2021-04-23 14:19 UTC, yoomlam requested changes
This is a tough ticket. I gave some feedback and will revisit after your updates and when I have more time to think about your solution.

2021-04-23 14:19 UTC, yoomlam commented on app/models/task.rb
> +
I seems odd to define a validation method here when it's not used in this class. Maybe a `Concern` is more appropriate.

2021-04-23 14:19 UTC, yoomlam commented on app/workflows/hearing_request_case_distributor.rb
> +    current_judge_assign_tasks = appeal.tasks.select { |task| task.type == JudgeAssignTask.name && task.open? }
```suggestion
    current_judge_assign_tasks = appeal.tasks.open.where(type: :JudgeAssignTask)
```

2021-04-23 14:19 UTC, yoomlam commented on app/workflows/hearing_request_case_distributor.rb
> +    if current_judge_assign_tasks.empty?
```suggestion
    if current_judge_assign_tasks.blank?
```
See https://blog.appsignal.com/2018/09/11/differences-between-nil-empty-blank-and-present.html

2021-04-23 14:19 UTC, yoomlam commented on app/workflows/hearing_request_case_distributor.rb
> +    end
At first glance, I'm thinking this logic should go into `JudgeAssignTaskCreator` -- the `hearing_request_case_distributor` shouldn't need to know how to do all this.

2021-04-23 14:19 UTC, yoomlam commented on app/workflows/judge_assign_task_creator.rb
> +  def close_distribution_tasks_for_appeal
You can undo this if you moved the new logic from `hearing_request_case_distributor.rb` to this class.

2021-04-23 14:19 UTC, yoomlam commented on spec/jobs/update_cached_appeals_attributes_job_spec.rb
> +        create(:ama_judge_assign_task, appeal: appeal)
Why was this change made?

2021-04-23 14:19 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +    let!(:task2) { create(:ama_judge_assign_task, assigned_to: judge2, appeal: appeal) }
Rather than exposing these `let` variables outside the context, keep the `context ".assigned_judge"` and create subcontexts within it.

2021-04-23 14:19 UTC, yoomlam commented on spec/models/concerns/task_tree_render_module_spec.rb
> +      ama_judge_assign_task.update(status: Constants.TASK_STATUSES.cancelled)
Why is this needed?

2021-04-23 14:19 UTC, yoomlam commented on spec/services/legacy_appeals_with_no_vacols_case_spec.rb
> +          create(:legacy_appeal, :with_judge_assign_task) { |legapp| legapp.reload.tasks.each(&:cancelled!) }
Why was this change made? Did this change fix a failed test?

2021-04-26 14:59 UTC, yoomlam commented
Eileen's notes: https://hackmd.io/@mGFT9b9_R6WJvEipbrJIjA/rJfAr9iVd

2021-04-26 22:32 UTC, yoomlam commented on app/models/task.rb
> +        task_to_validate.save(validate: false)
A problem with this is that ALL validations are disabled, which is probably not what you want.

2021-04-26 22:35 UTC, yoomlam commented on app/models/task.rb
> +    target_tasks = tasks.select { |task| task.type == type && task.open? }
See PR #16169 for a better way to query tasks

2021-04-27 13:48 UTC, eileen-nava commented
> Eileen's notes: https://hackmd.io/@mGFT9b9_R6WJvEipbrJIjA/rJfAr9iVd

I'm responding with a brief summary of my PR in response to Yoom's question in slack.

Here is a brief summary of my approach to this PR.  Of the approaches [outlined in “Discussion of 15220”](https://hackmd.io/f7RDOLSuTFiPsk-dEsJP_Q), it is the most related to “My Initial Approach.”

I wrote a task validation that fails on create if more than one `JudgeAssignTask` exists for an appeal.  In order to preserve the reassign flow, I added the method `handle_task_count_validation` to the method `reassign`.  If a task fails to save and throws the error associated with there being more than one `JudgeAssignTask` task for the same appeal, [the task will still save.](https://github.com/department-of-veterans-affairs/caseflow/pull/16072/files#diff-4095b65754098dce7229824782d43e80a7cb3f0fe45aa245102593760b51a24bR564.) What’s tricky is that I use the method `.save(validate: false)`, which doesn’t call any validations.  If a task fails to save for multiple reasons, this implementation might introduce an error.  I can’t think of any concrete cases where this would happen, but I am going to try to locally reproduce this scenario.

2021-04-29 15:09 UTC, eileen-nava commented on spec/jobs/update_cached_appeals_attributes_job_spec.rb
> +        create(:ama_judge_assign_task, appeal: appeal)
Since an appeal should only have one `JudgeAssignTask` at a time, it doesn't make sense for there to be eight `JudgeAssignTask`s assigned to the same appeal.  Since I thought this setup was incorrect, I edited it to have only one `JudgeAssignTask` associated with the appeal.

2021-04-29 15:22 UTC, eileen-nava commented on spec/services/legacy_appeals_with_no_vacols_case_spec.rb
> +          create(:legacy_appeal, :with_judge_assign_task) { |legapp| legapp.reload.tasks.each(&:cancelled!) }
Yes, this test was failing before I called `.reload` on the appeal.  Before I added the `.reload` call, the setup did not cancel all of the appeal’s tasks, because `legapp.tasks` did not return all of the appeal’s associated tasks.
I reverted the change after merging in the latest master, and the test now passes.  I will revert the change, since it is no longer necessary.
Full disclosure: I’m not sure why this change is no longer needed.

2021-04-29 15:26 UTC, eileen-nava commented on spec/models/concerns/task_tree_render_module_spec.rb
> +      ama_judge_assign_task.update(status: Constants.TASK_STATUSES.cancelled)
Without line 123
```
ama_judge_assign_task.update(status: Constants.TASK_STATUSES.cancelled)
```

line 124 makes the test fail on the `no_multiples_of_noncancelled_task` validation, because line 124 causes the appeal to have more than one open `JudgeAssignTask` at the same time
```
create(:ama_judge_assign_task, appeal: appeal, parent: nil, created_at: 1.day.ago.round)
```

2021-05-03 21:19 UTC, eileen-nava commented on app/models/task.rb
> +    save!(status: Constants.TASK_STATUSES.cancelled)
I reflected and decided to keep this validation in `task.rb`, rather than placing it in a concern.  When I read the Caseflow wiki’s [documentation on concerns](https://github.com/department-of-veterans-affairs/caseflow/wiki/Backend-Pattern-Concern), “Best Practices” says 
* Concerns should focus on a single capability shared by unrelated objects

Since the different types of tasks are not unrelated, I don’t think concerns are appropriate for this scenario.  Of course, I’d be open to other opinions.

2021-05-06 16:23 UTC, eileen-nava commented
@yoomlam I implemented the changes we discussed and got all automated  checks passing.  I also locally tested the PR and ensured the desired functionality works.  This PR is ready for re-review now.

2021-05-19 13:18 UTC, yoomlam commented on app/models/task.rb
> +      end
👍

2021-05-19 14:11 UTC, yoomlam requested changes
Reviewed non-Rspec code.
There are other callers of `JudgeAssignTaskCreator#call` -- wondering why you only changed HearingRequestCaseDistributor.

2021-05-19 14:11 UTC, yoomlam commented on app/workflows/judge_assign_task_creator.rb
> +  def manage_judge_assign_tasks_for_appeal
What's your reasoning for this method name?
https://medium.com/hackernoon/naming-the-things-in-programming-230590016f00

Why I ask:
* We're in a class called `JudgeAssignTaskCreator`, so the `judge_assign_tasks` part doesn't add much meaning
* neither does the `for_appeal` part.
* `manage` is vague and means much more (to me) than what this method is doing.

With that said, I wonder if this method is better as a `private` method where you check for existing open JATask within the `call` method like so:
```ruby
def call
  ...
  open_judge_assign_task = @appeal.tasks.open.find_by_type(:JudgeAssignTask)
  reassign_existing_open_task if open_judge_assign_task
  call
  ...
end
```

In other words, does the caller of `JudgeAssignTaskCreator` need to know when to call `call` vs. `manage_judge_assign_tasks_for_appeal`?

2021-05-19 14:11 UTC, yoomlam commented on app/models/task.rb
> +    Thread.current.thread_variable_set(:skip_duplicate_validation, true)
Add a code comment to explain why you're skipping validation in this situation.

2021-05-19 14:11 UTC, yoomlam commented on spec/models/task_spec.rb
> +    end
Purpose of this change?

2021-05-27 15:51 UTC, eileen-nava commented on app/models/task.rb
> +    end
Good call! 👍

2021-06-02 19:44 UTC, eileen-nava commented on app/workflows/hearing_request_case_distributor.rb
> -
To me, it felt weird for the `hearing_request_case_distributor.rb` to have a method called `create_judge_assign_task_for_appeal`.  That seems like something that `judge_assign_task_creator` would do.  I wouldn’t expect the `hearing_request_case_distributor.rb`  to have that much knowledge about a `judge_assign_task`, because it feels like tangled code.  

I’m also okay with reverting this change if you don’t agree with it.  I think the pushback to my above concern is that `create_judge_assign_task_for_appeal` doesn't couple `hearing_request_case_distributor.rb` to `judge_assign_task_creator`, because it relies on logic that is defined in `judge_assign_task_creator`, rather than putting that logic in `hearing_request_case_distributor.rb` itself.

I hope the above was clear.

2021-06-02 20:23 UTC, eileen-nava commented on app/workflows/judge_assign_task_creator.rb
> +  def manage_judge_assign_tasks_for_appeal
I agree that the method's name is confusing.  I removed it and refactored to use `call`, along with the proposed private method of `reassign_existing_open_task `.

2021-06-02 20:32 UTC, eileen-nava commented on spec/models/task_spec.rb
> +    end
I think rubocop made this change when I ran `rubocop -a`.

2021-06-02 20:53 UTC, eileen-nava commented on app/workflows/hearing_request_case_distributor.rb
> -
I reverted the change. 🤷‍♀️

2021-06-21 18:18 UTC, yoomlam commented on spec/jobs/update_cached_appeals_attributes_job_spec.rb
> +        create(:ama_judge_assign_task, appeal: appeal)
That makes sense. By that same logic, line 22 should probably be modified to only have 1 open `bva_dispatch_task`.

2021-06-21 18:31 UTC, yoomlam commented on app/workflows/judge_assign_task_creator.rb
> +    @task = @appeal.tasks.open.find_by_type(:JudgeAssignTask)
I think you can reduce the number of queries by removing line 34 and replacing the implementation of the `task` method with `find-or-create` code.

Alternatively, you can do something like this if desired:
```suggestion
    new_task, old_task, new_children = open_judge_assign_task.reassign({
                                      assigned_to_type: @judge.class.name,
                                      assigned_to_id: @judge.id,
                                      appeal: appeal
                                    }, current_user)
    new_task
```

2021-06-21 18:38 UTC, yoomlam commented on spec/models/concerns/task_tree_render_module_spec.rb
> +      ama_judge_assign_task.update(status: Constants.TASK_STATUSES.cancelled)
```suggestion
      ama_judge_assign_task.cancelled!
```

2021-06-21 18:50 UTC, yoomlam commented on app/models/task.rb
> +  end
```suggestion
  def open_task_type_already_exists?
    if appeal.reload.tasks.open.of_type(type).any?
      # I don't see other calls to `errors.add` in this class. Wondering if it is needed if we call `fail`
      errors.add(:type, COPY::INVALID_MULTIPLE_TASKS)
      # Should we fail? -- see method `status_is_valid_on_create`
      fail Caseflow::Error::InvalidStatusOnTaskCreate, task_type: type, message: COPY::INVALID_MULTIPLE_TASKS
    end
  end
```

2021-06-21 18:57 UTC, yoomlam commented on app/models/task.rb
> +  end
```suggestion
  def check_for_open_task_type?
    !Thread.current.thread_variable_get(:skip_duplicate_validation)
  end
```

I'm also tempted to rename `skip_duplicate_validation` to `check_for_open_task_type` and reverse all the boolean logic, but that's a personal preference to ease readability for me.

2021-06-21 21:23 UTC, yoomlam commented on app/models/task.rb
> +    # JudgeAssignTask is reassigned, more than one task must exist at the same time.
```suggestion
    # task is reassigned, more than one open task of the same type must exist during the reassignment.
    # After reassignment, only one open task of the same type should exist.
```

2021-06-21 21:29 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +        end
`before(:each)` is the default when calling `before`

```suggestion
        before { task2.cancelled! }
```

2021-06-21 21:32 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +        end
`task2` and `task3` have the same `assigned_to`. Should `task3` be assigned to `judge3` and
```suggestion
        it "should know the right assigned judge" do
          expect(subject).to eq judge3
        end
```

2021-06-21 21:39 UTC, yoomlam commented on spec/models/tasks/judge_task_spec.rb
> +  describe "no_multiples_of_open_task_type" do
```suggestion
  describe "#open_task_type_already_exists?" do
```

2021-06-21 21:40 UTC, yoomlam commented on spec/models/tasks/judge_task_spec.rb
> +    let(:stream_type) { Constants.AMA_STREAM_TYPES.original }
These are not needed:
```suggestion
```

2021-06-21 21:51 UTC, yoomlam reviewed
All files reviewed! Almost there.

2021-06-23 21:35 UTC, eileen-nava commented on app/workflows/judge_assign_task_creator.rb
> +    @task = @appeal.tasks.open.find_by_type(:JudgeAssignTask)
I refactored to something like the second option.  Also, while refactoring this class, I noticed that the `JudgeAssignTaskCreator` `task` method does not seem to be used anywhere in our codebase.  Curious.

2021-06-23 22:17 UTC, eileen-nava commented on app/models/task.rb
> +  end
I don’t see any validation methods in Caseflow that end with a ? and the method doesn’t return a boolean.  This makes me hesitant to rename the method to end with a ?.
Is there another name without a `?` ending that you prefer?  Maybe `task_type_is_not_open` or `only_open_task_of_type`.

Also, I used `errors.add` because I thought it was standard for custom validations (documentation [here](https://guides.rubyonrails.org/active_record_validations.html#performing-custom-validations)) but if `fail` is preferred for Caseflow, I can refactor to use `fail`.

2021-06-23 22:29 UTC, eileen-nava commented on spec/models/tasks/judge_task_spec.rb
> +    let(:stream_type) { Constants.AMA_STREAM_TYPES.original }
🤦‍♀️ Indeed!

2021-06-23 22:43 UTC, eileen-nava commented on app/models/task.rb
> +  end
> I'm also tempted to rename skip_duplicate_validation to check_for_open_task_type and reverse all the boolean logic, but that's a personal preference to ease readability for me.
Hmm, interesting idea.  I will think this over and look at implementing it.

2021-06-24 19:25 UTC, yoomlam commented on app/workflows/judge_assign_task_creator.rb
> +    @task = @appeal.tasks.open.find_by_type(:JudgeAssignTask)
Do you can what the return value of this method is -- it's not used anywhere? If not, remove the last line.

2021-06-24 19:26 UTC, eileen-nava commented on app/models/task.rb
> +  end
Update: I switched using `fail` and `Caseflow:Error` because it led to more user-friendly errors.  Here is what currently displays if a user attempts to twice perform the same action for a case in two different windows.

<img width="1792" alt="Screen Shot 2021-06-24 at 11 55 19 AM" src="https://user-images.githubusercontent.com/80347702/123320878-56ecae00-d500-11eb-849d-53eac58ee93a.png">

I'm currently trying to edit the `detail` prop in the `FlowModal` so that the display is less repetitive.  I'm not sure why title and details are currently the same.  I'm referring to [this PR ](https://github.com/department-of-veterans-affairs/caseflow/pull/14437)for guidance.

2021-06-24 19:27 UTC, yoomlam commented on app/models/task.rb
> +    if appeal.reload.tasks.open.of_type(type).count >= 1
```suggestion
    if appeal.reload.tasks.open.of_type(type).any?
```

2021-06-24 19:38 UTC, yoomlam commented on app/workflows/judge_assign_task_creator.rb
> +
Let's pair on this method. There are a couple of things I want to point out and we can address them while pairing.

2021-06-24 19:43 UTC, eileen-nava commented on app/models/task.rb
> +  end
UPDATE: I fixed the error display.  Feedback on the error message is welcome.  I [modeled it off the wording](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/caseflow/error.rb#L242) from the `DuplicateUserTask` error.
<img width="881" alt="Screen Shot 2021-06-24 at 3 36 10 PM" src="https://user-images.githubusercontent.com/80347702/123322770-b2b83680-d502-11eb-97cb-ff201c6d0f4b.png">

2021-06-24 19:49 UTC, eileen-nava commented on app/workflows/judge_assign_task_creator.rb
> +
@yoomlam Sounds good. 👍   I am in sprint planning 4-5:30 pm EST today but I'm free after that.  I also am free Friday morning anytime before 12:30 pm EST and Friday afternoon after 3 pm EST.

2021-06-24 19:51 UTC, yoomlam commented on lib/caseflow/error.rb
> +  class InvalidMultipleOpenTasksOfSameType < SerializableError
```suggestion
  class MultipleOpenTasksOfSameTypeError < SerializableError
```

2021-06-24 19:51 UTC, yoomlam commented on spec/fixes/investigate_duplicate_judge_assign_task_spec.rb
> +        expect(page).to have_content("This appeal cannot have more than one open task of type JudgeAssignTask")
🎉

2021-06-24 19:51 UTC, yoomlam commented on spec/models/tasks/judge_task_spec.rb
> +    end
Less indirection and more readable:
```suggestion
    context "when one judge assign task is open" do
      it "throws an error when a second judge assign task is created" do
        expect { create(:ama_judge_assign_task, assigned_to: judge, appeal: appeal) }.to raise_error do |error|
          expect(error).to be_a(ActiveRecord::RecordInvalid)
        end
      end
    end
```

2021-06-24 21:45 UTC, yoomlam approved these changes
Woohoo!

2021-06-24 21:46 UTC, eileen-nava commented
@yoomlam Here is the expected error message.

2021-06-25 18:15 UTC, eileen-nava commented
@yoomlam I consulted design about the error message wording after getting the PR approved by Ann-Marie during a demo.  Below is the current wording.

<img width="898" alt="Screen Shot 2021-06-25 at 2 13 20 PM" src="https://user-images.githubusercontent.com/80347702/123468364-a645e380-d5bf-11eb-9a25-73969cf80775.png">

I will merge this after the build passes.

2021-06-25 18:17 UTC, yoomlam commented
@eileen-nava I think that message may be too specific. If the validation fails for other scenarios, this error message (mentioning "closing the window" and "previous window") is confusing.

2021-06-25 18:19 UTC, eileen-nava commented
> @eileen-nava I think that message may be too specific. If the validation fails for other scenarios, this error message (mentioning "closing the window" and "previous window") is confusing.

Good point.  I'll check in with design again.  Thank you!

2021-06-25 19:38 UTC, eileen-nava commented
Here is the current error message.
<img width="1197" alt="Screen Shot 2021-06-25 at 3 31 38 PM" src="https://user-images.githubusercontent.com/80347702/123476909-51a86580-d5cb-11eb-98e6-0f524e0b4d4c.png">

2021-06-25 21:40 UTC, merged