Granted Substitution Basics Form
department-of-veterans-affairs/caseflow pull request #16099
Opened 2021-04-07 19:44 UTC by jcq

Connects [CASEFLOW-1043](https://vajira.max.gov/browse/CASEFLOW-1043)

### Description
This begins the frontend portion of the Granted Substitution functionality, adding the form to set the basic parameters of the substitution.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-04-08 02:15 UTC, n1zyy commented on client/app/queue/grantedSubstitution/GrantedSubstitutionBasicsForm.jsx
> +    max(new Date(), 'Date cannot be in the future').
This lien was my addition what I saw in the yup docs. 🤞 this is best practice?

2021-04-08 02:15 UTC, n1zyy commented on client/app/queue/grantedSubstitution/GrantedSubstitutionBasicsForm.jsx
> +        </p>
Does anyone object to me doing this while this is WIP?

2021-04-08 02:15 UTC, n1zyy commented on client/app/queue/grantedSubstitution/routes.jsx
> +        <GrantedSubstitutionBasicsView />
I think we probably want to rename all of this per https://github.com/department-of-veterans-affairs/caseflow/pull/16095

If the board thinks calling it "granted" substitution is confusing, it might be best for us to kill off the name in the code before it takes root, and call this `<SubstituteAppellantBasicsView />` or something. I'm not going to make that change tonight, though.

2021-04-15 18:09 UTC, jcq commented on app/controllers/appeals_controller.rb
> +        params: { relationships: params["relationships"] }
Adding this as a way to _optionally_ include relationships info from the `VeteranSerializer` -- most of the time this will not be relevant, and it requires a call to BGS so would be a performance hit

2021-04-15 18:09 UTC, jcq commented on app/models/serializers/work_queue/veteran_serializer.rb
> +      # Intake::RelationshipSerializer.new(object).serializable_hash[:data][:attributes]
Removing this commented code...

2021-04-15 18:10 UTC, jcq commented on app/views/queue/index.html.erb
> +      recognized_granted_substitution_after_dd: FeatureToggle.enabled?(:recognized_granted_substitution_after_dd, user: current_user)
This is the feature toggle specified for this work

2021-04-15 18:11 UTC, jcq commented on client/COPY.json
> +  "SUBSTITUTE_APPELLANT_SELECT_APPELLANT_SUBHEAD": "Complete the details below to create the appeal for the substitute for this case.",
Most steps use the same copy for the subhead, so we ended up just referencing this multiple times rather than duplicating the copy over and over

2021-04-15 18:12 UTC, jcq commented on client/app/components/DateSelector.jsx
> +    // Test the input against the date regex above. The regex matches
I don't remember updating this, but spelling fixes make me happy

2021-04-15 18:12 UTC, jcq commented on client/app/queue/CaseDetailsPostDispatchActions.jsx
> +const buttonContainer = css({
accounting for possibility of multiple buttons now

2021-04-15 18:14 UTC, jcq commented on client/app/queue/CaseDetailsPostDispatchActions.jsx
> +  addCavcRemand: PropTypes.bool,
We need to handle permissions both outside of this component (for its display or not) as well as inside for the conditional display of the specific buttons. In order to not duplicate the various lookups necessary, we simply can use the already-established conditionals as props to control button display in here

2021-04-15 18:16 UTC, jcq commented on client/app/queue/CaseDetailsView.jsx
> +  const supportCavcRemand =
Most changes to this point are simply code formatting/linting; the following lines are where real changes were made

2021-04-15 18:17 UTC, jcq commented on client/app/queue/QueueApp.jsx
> +              {substituteAppellantRoutes.page}
This is the only relevant portion of the changes to this file

2021-04-15 18:17 UTC, jcq commented on client/app/queue/reducers.js
> +  substituteAppellant: substituteAppellantReducer,
tell the Queue Redux store about our new slice!

2021-04-15 18:18 UTC, jcq commented on client/app/queue/substituteAppellant/SubstituteAppellantContainer.jsx
> +  // 'Select POA',
Temporarily removed until later work brings this back

2021-04-15 18:18 UTC, jcq commented on client/app/queue/substituteAppellant/SubstituteAppellantContainer.jsx
> +        title: `${idx + 1}. ${title}`,
Made the step numbering dynamic given that POA portion is temporarily hidden

2021-04-15 18:20 UTC, jcq commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsView.jsx
> +    history.push(`/queue/appeals/${appealId}/substitute_appellant/tasks`);
This will change to routing to POA page in later work, but for now we're skipping straight to tasks

2021-04-15 18:26 UTC, jcq commented on client/app/queue/substituteAppellant/poa/SubstituteAppellantPoaForm.jsx
> +/* eslint-disable */
This file is a stub for future work; we're temporarily disabling linting until that time.

2021-04-15 18:26 UTC, jcq commented on client/app/queue/substituteAppellant/poa/SubstituteAppellantPoaView.jsx
> +/* eslint-disable */
This file is a stub for future work; we're temporarily disabling linting until that time.

2021-04-15 18:26 UTC, jcq commented on client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
> +/* eslint-disable */
This file is a stub for future work; we're temporarily disabling linting until that time.

2021-04-15 18:26 UTC, jcq commented on client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
> +/* eslint-disable */
This file is a stub for future work; we're temporarily disabling linting until that time.

2021-04-15 18:27 UTC, jcq commented on client/app/queue/substituteAppellant/routes.jsx
> +    <SubstituteAppellantContainer />
Not much here, since we moved nested routing into `SubstituteAppellantContainer`

2021-04-15 18:28 UTC, jcq commented on client/app/queue/substituteAppellant/substituteAppellant.slice.js
> +export const fetchRelationships = createAsyncThunk(
This is an async Redux action that fetches relationship data for the veteran on the specified appeal

2021-04-15 18:28 UTC, jcq commented on client/app/queue/substituteAppellant/substituteAppellant.slice.js
> +export const completeSubstituteAppellant = createAsyncThunk(
This is a stub for the action that will be used in CASEFLOW-1118

2021-04-15 18:29 UTC, jcq commented on client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
> +/* eslint-disable */
This file is a stub for future work; we're temporarily disabling linting until that time.

2021-04-15 18:29 UTC, jcq commented on client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
> +/* eslint-disable */
This file is a stub for future work; we're temporarily disabling linting until that time.

2021-04-15 18:29 UTC, jcq commented on spec/feature/queue/substitute_appellant/shared_setup.rb
> +
Deleting this blank line...

2021-04-15 18:30 UTC, jcq commented on spec/feature/queue/substitute_appellant/shared_setup.rb
> +RSpec.shared_context("with Clerk of the Board user") do
Since we will likely reuse tests in a number of contexts I split this out into its own file for us to include as needed

2021-04-15 19:16 UTC, yoomlam commented on client/app/queue/CaseDetailsPostDispatchActions.jsx
> +  const { appealId, addCavcRemand, addSubstitute } = props;
Personal preference: I kinda don't like the `addCavcRemand, addSubstitute` variable names. How about `includeCavcRemand` and `includeSubstitute`?

2021-04-15 19:20 UTC, yoomlam commented on client/app/queue/CaseDetailsView.jsx
> +  marginBottom: '3rem',
Why add the comma?

2021-04-15 19:21 UTC, yoomlam commented on client/app/queue/CaseDetailsView.jsx
> +  );
I personally like the single-line versions.

2021-04-15 19:24 UTC, yoomlam commented on client/app/queue/CaseDetailsView.jsx
> +      ['Clerk of the Board', 'Intake'].includes(organization.name)
Can we reference constants here? I'm thinking of the scenario where they want to change the `name`: If we hard code these strings, we'd have to update the code.

2021-04-15 19:26 UTC, yoomlam commented on client/app/queue/CaseDetailsView.jsx
> +    );
With so many syntax changes, I would advocate putting them in a separate PR next time to keep PRs like this smaller.

2021-04-15 19:31 UTC, yoomlam commented on client/app/queue/CaseDetailsView.jsx
> +      ['Clerk of the Board', 'Intake'].includes(organization.name)
Also, I believe today's conversation says Intake will not be involved, so that should be removed. Check with Product.

2021-04-15 19:32 UTC, yoomlam commented on client/app/queue/CaseDetailsView.jsx
> +        )}
Personally, I prefer the one-liner.

2021-04-15 19:35 UTC, yoomlam commented on client/app/queue/substituteAppellant/SubstituteAppellantContainer.jsx
> +        </Route>
Would be nice to generalize this: turn `sections` into a hash and iterate through the `sections` to create routes.

2021-04-15 19:40 UTC, yoomlam commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +export const SubstituteAppellantBasicsForm = ({
So the `Form` file is the React component and the `View` file retrieves values for the form. Are there other reasons to split the page into 2 files?

2021-04-15 19:42 UTC, yoomlam commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +          name="substitutionDate"
I need a tutorial on `inputRef`, `name`, `register`, and how they affect `existingValues`. There's magic that I'm not aware of.

2021-04-15 19:46 UTC, yoomlam commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +  loadingRelationships = false,
Why is the default `false`?

2021-04-15 19:52 UTC, yoomlam commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +        )}
Given the if-then-else nature of this, I would have defined a `relationshipsSection` constant before the `return` and then simply have
```jsx
{relationshipsSection}
```
instead of checking `loadingRelationships` multiple times.

2021-04-15 20:03 UTC, yoomlam commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsView.jsx
> +    formData: existingValues,
What is this `formData: existingValues` doing?

2021-04-15 20:04 UTC, jcq commented on client/app/queue/CaseDetailsView.jsx
> +  marginBottom: '3rem',
We updated linting rules a while back to always prefer trailing commas — this was just automated systems adding missing trailing commas

2021-04-15 21:07 UTC, jcq commented on client/app/queue/CaseDetailsView.jsx
> +    );
Fair point — most of these happened due to automatic code formatting being run — none of these formatting changes were manually done. 😅

2021-04-15 21:08 UTC, jcq commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +export const SubstituteAppellantBasicsForm = ({
That's basically it — separation of concerns between presentational component and connected component

2021-04-15 21:10 UTC, jcq commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +  loadingRelationships = false,
Good question — while the default behavior in context is that triggers the load upon first visiting the page, as far as the _form_ is concerned, there's no reason that it needs to default to that (and it is controlled entirely externally via props)

2021-04-15 21:12 UTC, jcq commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsView.jsx
> +    formData: existingValues,
This is a form of [destructuring](https://davidwalsh.name/destructuring-alias) where you alias to a new variable name. I just wanted it to be abundantly clear that we were dealing with existing data rather than defaults, etc

2021-04-15 21:15 UTC, jcq commented on client/app/queue/CaseDetailsPostDispatchActions.jsx
> +  const { appealId, addCavcRemand, addSubstitute } = props;
Sounds good — updating!

2021-04-15 21:18 UTC, jcq commented on client/app/queue/CaseDetailsView.jsx
> +  );
I'm torn, but sort of also prefer the single-line versions. This was more automated formatting from linter rules

2021-04-15 21:21 UTC, jcq commented on client/app/queue/CaseDetailsView.jsx
> +      ['Clerk of the Board', 'Intake'].includes(organization.name)
We could create an `ORGANIZTIONS.json` file under `constants` and pull from that both here and for setting the name in `ClerkOfTheBoard` model...?

2021-04-15 21:38 UTC, jcq commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +        )}
Changed it a bit to account for just a single true/false for `loadingRelationships`... maybe better?

2021-04-15 21:38 UTC, yoomlam commented on client/app/queue/substituteAppellant/substituteAppellant.slice.js
> +      throw error;
How will this be presented to the user? What will the user see when this error occurs?

2021-04-15 21:40 UTC, yoomlam commented on client/app/queue/substituteAppellant/substituteAppellant.slice.js
> +  extraReducers: {
Need to read up on `extraReducers` vs `reducers`.

2021-04-15 21:42 UTC, jcq commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +          name="substitutionDate"
This is part of the magic of the management being done by [React Hook Form](https://react-hook-form.com/). We're using uncontrolled form components (by way of `register` to `inputRef`, and the `name` prop is how React Hook Form determines values (both default and current), validation, and more. Some more info is avail [on the CF wiki](https://github.com/department-of-veterans-affairs/caseflow/wiki/Frontend-Form-Management), but also happy to give more info anytime!

2021-04-15 21:44 UTC, jcq commented on client/app/queue/substituteAppellant/substituteAppellant.slice.js
> +  extraReducers: {
Easiest way to think of it (lifted [from docs](https://redux-toolkit.js.org/api/createSlice#extrareducers)) is that `extraReducers` references "external" actions not defined within the slice itself. So the state of the slice can be updated based on actions from elsewhere (in this case, the async thunks)

2021-04-15 21:46 UTC, yoomlam commented on client/app/queue/CaseDetailsView.jsx
> +      ['Clerk of the Board', 'Intake'].includes(organization.name)
Sounds good.

2021-04-15 21:49 UTC, yoomlam commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +  loadingRelationships = false,
Let's remove the default since it is inconsequential and expected to be set externally.

2021-04-15 21:50 UTC, yoomlam commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
> +          name="substitutionDate"
I highly appreciate the links. I'll review them soon.

2021-04-15 21:56 UTC, yoomlam requested changes
I learned a lot from this PR!

2021-04-15 22:08 UTC, yoomlam commented on client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsView.jsx
> +    formData: existingValues,
Gotcha.. you're renaming `formData` as `existingValues`.

2021-04-15 22:10 UTC, jcq commented on client/app/queue/substituteAppellant/substituteAppellant.slice.js
> +      throw error;
For now we'll just end up with empty `relationships` array, which will cause the "no existing relationships found" message to display. Can def alter this UX based on design and/or user feedback.

2021-04-16 13:30 UTC, yoomlam approved these changes
🎉  I have no feedback blocking approval except for removing Intake and renaming `currentUserOnCotbOrIntake`.
https://github.com/department-of-veterans-affairs/caseflow/pull/16099#discussion_r614338005

2021-04-16 16:35 UTC, merged