Add Power of Attorney Refresh Button to Case Details
department-of-veterans-affairs/caseflow pull request #16132
Opened 2021-04-16 15:17 UTC by Jeremy1026

Resolves [CASEFLOW-867](https://vajira.max.gov/browse/CASEFLOW-867)

### Description
Adds a button on to the Case Details page to refresh the Power of Attorney. Shows status of the refresh after clicking the button. Refreshes are limited to once every 10 minutes for each Power of Attorney.

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Tests pass
  
### Testing Plan
- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

Refresh Button:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2308626/115045827-e2b0e100-9ea4-11eb-852f-db5b28d94ac6.png">

Banner showing successful update:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2308626/115046151-27d51300-9ea5-11eb-939b-4864ade27fd9.png">

Banner showing timeout restrictions are in affect:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2308626/115046168-2c013080-9ea5-11eb-8b30-9df6062901c0.png">

2021-04-20 14:55 UTC, bgantick requested changes

2021-04-20 14:55 UTC, bgantick commented on client/app/queue/reducers.js
> +// const poaSyncDateUpdates = (state, action) => {
Remove if not being used

2021-04-20 14:55 UTC, bgantick commented on client/app/queue/constants.js
> +  // POA_SYNC_DATE_UPDATES: 'POA_SYNC_DATE_UPDATES',
Remove if not being used

2021-04-20 14:55 UTC, bgantick commented on client/app/queue/components/PoaSyncDate.jsx
> +// import { editAppeal, poaSyncDateUpdates } from '../QueueActions';
Remove if not being used

2021-04-20 14:55 UTC, bgantick commented on client/app/queue/QueueActions.js
> +// export const poaSyncDateUpdates = (appealId, poaSyncDate) => ({
Remove if not being used

2021-04-23 15:15 UTC, Jeremy1026 reviewed
Resolved first round of review comments.

2021-04-23 15:24 UTC, Jeremy1026 reviewed
Made requested updates.

2021-04-23 15:24 UTC, Jeremy1026 commented on client/app/queue/reducers.js
> +// const poaSyncDateUpdates = (state, action) => {
Removed

2021-04-23 15:25 UTC, Jeremy1026 commented on client/app/queue/constants.js
> +  // POA_SYNC_DATE_UPDATES: 'POA_SYNC_DATE_UPDATES',
Removed

2021-04-23 15:25 UTC, Jeremy1026 commented on client/app/queue/components/PoaSyncDate.jsx
> +// import { editAppeal, poaSyncDateUpdates } from '../QueueActions';
Removed

2021-04-23 15:25 UTC, Jeremy1026 commented on client/app/queue/QueueActions.js
> +// export const poaSyncDateUpdates = (appealId, poaSyncDate) => ({
Removed

2021-04-28 20:22 UTC, bgantick requested changes

2021-04-28 20:22 UTC, bgantick commented on app/controllers/appeals_controller.rb
> +  def update_power_of_attorney
I'm not seeing logic anywhere to remove a POA if one isn't found via BGS (see https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#update-or-delete-bgs-power-of-attorney-poa)

2021-04-28 20:26 UTC, Jeremy1026 commented on app/controllers/appeals_controller.rb
> +  def update_power_of_attorney
That wasn't part of the original ticket. Might be worth a new ticket, but don't think it should be added to this one, especially not at this point.

2021-04-28 20:29 UTC, bgantick commented on app/controllers/appeals_controller.rb
> +  def update_power_of_attorney
I would consider that part of a "successful" POA refresh

2021-05-04 12:43 UTC, Jeremy1026 commented on app/controllers/appeals_controller.rb
> +  def update_power_of_attorney
The deletion when `:not_found` has been added, including a test for this situation.

2021-05-04 15:24 UTC, ajspotts commented on client/app/queue/components/PoaRefreshButton.jsx
> +    poa_last_synced_at: PropTypes.string,
don't believe we need this propType in this file

2021-05-04 15:30 UTC, ajspotts commented on client/app/queue/PowerOfAttorneyDetail.jsx
> +      error: loadingPowerOfAttorney?.error,
Is this trailing comma necessary?

2021-05-04 15:41 UTC, Jeremy1026 commented on client/app/queue/components/PoaRefreshButton.jsx
> +    poa_last_synced_at: PropTypes.string,
Resolved in e9e4867

2021-05-04 15:41 UTC, Jeremy1026 commented on client/app/queue/PowerOfAttorneyDetail.jsx
> +      error: loadingPowerOfAttorney?.error,
Removed in 9d83b3c

2021-05-05 17:54 UTC, ajspotts approved these changes
LGTM! 🎉

2021-05-05 18:00 UTC, merged