Veteran#find_or_create_poa is now a thing
department-of-veterans-affairs/caseflow pull request #16148
Opened 2021-04-21 12:41 UTC by n1zyy

### Description
On Bat Team, we very, very often run:

```ruby
v = appeal.veteran
poa = BgsPowerOfAttorney.find_or_create_by_file_number(v.file_number)
```

It feels like a Veteran object should know how to retrieve its POA.
This is mostly meant as a convenience for people in the console.

Now you can run:
```ruby
v = appeal.veteran
poa = v.find_or_create_poa
```

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] People agree this would be convenient, rather than a weird hack only I would ever use

### Testing Plan
This can be tested pretty simply in the console:

```
v = Veteran.last
poa = v.find_or_create_poa
```

2021-04-21 14:23 UTC, jcq approved these changes
Seems good to me, but I'd def appreciate others more opinionated about Ruby/Rails conventions to weigh in on convenience methods like this. 

You know, like the backend functional lead or something 😉

2021-04-21 14:48 UTC, eileen-nava approved these changes
This looks good to me. 👍

2021-04-21 17:47 UTC, yoomlam requested changes
Please add a corresponding test to maintain high test coverage

2021-04-23 02:57 UTC, n1zyy commented on spec/models/veteran_spec.rb
> +  end
This test is intentionally a little bit sparse: the method only exists to call `BgsPowerOfAttorney.find_or_create_by_file_number(file_number)` in a more convenient way, so we simply test that that's what happens.

`BgsPowerOfAttorney.find_or_create_by_file_number` is already tested separately: https://github.com/department-of-veterans-affairs/caseflow/blob/5d0bf14c9747fc9440f70afcdcebe8a38c3f9a8e/spec/models/bgs_power_of_attorney_spec.rb#L69-L129

2021-04-23 02:58 UTC, n1zyy commented
@yoomlam - Good call. Added! 👍

2021-04-23 03:07 UTC, n1zyy commented
@jcq 

> Seems good to me, but I'd def appreciate others more opinionated about Ruby/Rails conventions to weigh in on convenience methods like this.

Yang had some good input here, on how there's a [console_methods.rb helper](https://github.com/department-of-veterans-affairs/caseflow/blob/5d0bf14c9747fc9440f70afcdcebe8a38c3f9a8e/lib/helpers/console_methods.rb). But, talking it over with Team Victor which is working with this code the most, there was some discussion that perhaps this _should_ be the way to fetch a POA.

2021-08-12 01:05 UTC, yoomlam commented
@n1zyy What do you want to do with this PR?

2022-01-21 18:48 UTC, closed without merging