Charley/caseflow 1115 use db values for timeslot calculation
department-of-veterans-affairs/caseflow pull request #16161
Opened 2021-04-22 20:46 UTC by charleyf

[CASEFLOW-1115](https://vajira.max.gov/browse/CASEFLOW-1115) will be done across multiple PRs:
- Backend changes ([16147](https://github.com/department-of-veterans-affairs/caseflow/pull/16147)), adds db columns, falls back to existing behavior for number_of_slots and begins_at (slot_length_minutes has no existing behavior in db).
- Only show slots when scheduling virtual hearings ([16150](https://github.com/department-of-veterans-affairs/caseflow/pull/16150)).
- UI Fixes PR ([16149](https://github.com/department-of-veterans-affairs/caseflow/pull/16149)), stop using HearingTime to fix various bugs (temporary fix until we replace with custom time modal).
- Slot recalculation PR (XXXX), branch is based on UI Fixes PR, accept new db values and calculate slots based on them.

### Description
This PR reworks the slot calculation to be much more flexible. As part of that, all of the slot calculation logic has been moved into it's own utils file and reworks the tests.

2021-04-23 18:56 UTC, sahalliburton requested changes
This looks like it is heading in the right direction, however there were a few issues I noticed during testing:

1. I am not sure if this is related to your changes, but I was not able to choose a virtual hearing day for the Oakland RO I had to choose a Video day
2. When selecting a custom time, the options started at 11:15 AM PDT (see screenshot)
3. On the scheduled veterans page the time shown (5:30 PDT) is not the time I chose (8:30 PDT) (see screenshot)
4. On the daily docket page the time is also shown incorrectly as above  (see screenshot)

Let me know if you have any questions or need any help

2021-04-23 18:56 UTC, sahalliburton commented on client/app/hearings/utils.js
> +const calculateAvailableTimeslots = ({ numberOfSlots, slotLengthMinutes, beginsAt, roTimezone, hearings }) => {
Can we re-combine these functions back into 1? It is a bit hard to read what is going on and we should probably only split the functions if there is separate testable functionality that is being provided

2021-04-26 15:59 UTC, charleyf commented on client/app/hearings/utils.js
> +const calculateAvailableTimeslots = ({ numberOfSlots, slotLengthMinutes, beginsAt, roTimezone, hearings }) => {
> This looks like it is heading in the right direction, however there were a few issues I noticed during testing:
> 
> 1. I am not sure if this is related to your changes, but I was not able to choose a virtual hearing day for the Oakland RO I had to choose a Video day
> 2. When selecting a custom time, the options started at 11:15 AM PDT (see screenshot)
> 3. On the scheduled veterans page the time shown (5:30 PDT) is not the time I chose (8:30 PDT) (see screenshot)
> 4. On the daily docket page the time is also shown incorrectly as above  (see screenshot)
> 
> Let me know if you have any questions or need any help

Thanks Stephen! I believe these are all addressed.

1. This is not related to this work. There are some restrictions around that I don't quite understand. I confirmed this using the UI.
2. + 4. This was a label formatting problem caused by depending on the Operating System (local) timezone which is why I wasn't seeing it. Reproduced by changing my OS timezone and resolved by changing the label formatting. Thanks for finding this!!!
3. I thought this was the expected behavior, but revisiting it seems clearly wrong. Changed this and it simplified the code nicely as well.

2021-04-26 16:00 UTC, charleyf commented
> This looks like it is heading in the right direction, however there were a few issues I noticed during testing:
> 
> 1. I am not sure if this is related to your changes, but I was not able to choose a virtual hearing day for the Oakland RO I had to choose a Video day
> 2. When selecting a custom time, the options started at 11:15 AM PDT (see screenshot)
> 3. On the scheduled veterans page the time shown (5:30 PDT) is not the time I chose (8:30 PDT) (see screenshot)
> 4. On the daily docket page the time is also shown incorrectly as above  (see screenshot)
> 
> Let me know if you have any questions or need any help

Thanks Stephen! I believe these are all addressed.

1. This is not related to this work. There are some restrictions around that I don't quite understand. I confirmed this using the UI.
2. and 4. This was a label formatting problem caused by depending on the Operating System (local) timezone which is why I wasn't seeing it. Reproduced by changing my OS timezone and resolved by changing the label formatting. Thanks for finding this!!!
3. I thought this was the expected behavior, but revisiting it seems clearly wrong. Changed this and it simplified the code nicely as well.

2021-04-26 16:01 UTC, charleyf commented on client/app/hearings/utils.js
> +const calculateAvailableTimeslots = ({ numberOfSlots, slotLengthMinutes, beginsAt, roTimezone, hearings }) => {
I was attempting to simplify things and did not. Thanks for pointing this out, I moved everything back into the loop format they were in.

2021-04-27 16:19 UTC, sahalliburton commented on client/app/hearings/utils.js
> +    numberOfSlots: numberOfSlots ? numberOfSlots : defaultNumberOfSlots,
Minor nit, but these could be changed into or assignments like `numberOfSlots: numberOfSlots || defaultNumberOfSlots,`

2021-04-27 16:21 UTC, sahalliburton commented on client/app/hearings/utils.js
> +    // Combine all the conditions that make a slot unavailable
Minor nit, but this could be combined into 1 line

2021-04-27 16:33 UTC, sahalliburton approved these changes
LGTM, thanks for making those changes!

2021-04-28 15:41 UTC, sahalliburton reviewed
LGTM, but there is still an issue with the custom time dropdown starting at 5:15 local time and only going to 1:45

<img width="970" alt="Screen Shot 2021-04-28 at 8 38 42 AM" src="https://user-images.githubusercontent.com/61989526/116432498-7f587480-a7fd-11eb-9f4b-a2ba469b0d67.png">

2021-04-29 16:40 UTC, closed without merging