Karinamzalez/caseflow 1339 [WIP]
department-of-veterans-affairs/caseflow pull request #16179
Opened 2021-04-27 15:52 UTC by karinamzalez

Resolves #1339

### Description

2021-04-27 23:13 UTC, meckila-navapbc reviewed
I left a few comments but you made have made changes locally since this is still WIP!

2021-04-28 17:40 UTC, karinamzalez commented on client/app/intake/addPOA/AddPoaPage.jsx
> +  const emailValidationError = errors.emailAddress && ERROR_EMAIL_INVALID_FORMAT;
I could be! But the default error message provided by react hook form doesn't match up with the copy provided by design :)

2021-04-28 17:41 UTC, karinamzalez commented on client/app/intake/addPOA/utils.js
> +    mode: 'onBlur',
So the inline error message doesn't as soon as the user starts typing -- more user friendly to have it render once they've finished typing :)

2021-04-28 20:43 UTC, meckila-navapbc commented on client/app/intake/addPOA/AddPoaPage.jsx
> +  const emailValidationError = errors.emailAddress && ERROR_EMAIL_INVALID_FORMAT;
Ah got it

2021-04-28 22:35 UTC, meckila-navapbc commented on client/app/intake/addPOA/AddPoaPage.jsx
> +  const emailValidationError = errors.emailAddress && ERROR_EMAIL_INVALID_FORMAT;
My mistake. I hadn't realized this was the string for the message until I scrolled further down. Adding `Message` to the variable name may make it clear

2021-04-28 23:20 UTC, meckila-navapbc commented on client/app/intake/addPOA/utils.js
> +    mode: 'onBlur',
I'm wondering if we want the user to have to click out of a field if they're _not_ adding a email. This is also why the rspecs are failing, we don't tab out of the input

2021-04-30 18:48 UTC, meckila-navapbc requested changes

2021-04-30 18:48 UTC, meckila-navapbc commented on client/app/intake/addClaimant/utils.js
> +    mode: 'onBlur',
For the sake of scope, we should keep the mode `onChange` until searchableDropdown has an onblur prop we can properly wire up.

2021-04-30 18:48 UTC, meckila-navapbc commented on spec/feature/intake/non_veteran_claimants_spec.rb
> +
Switching back to `onChange` means blur_from will no longer be needed

2021-04-30 22:27 UTC, karinamzalez commented on client/app/intake/addClaimant/utils.js
> +    mode: 'onBlur',
yeah happy we came to this conclusion because the onBlur effects were getting out of hand 😅-- should we add an issue to address this next sprint? 👀

2021-04-30 23:14 UTC, meckila-navapbc approved these changes

2021-05-03 17:05 UTC, merged