WIP | Substitute Appellant | Task Selection Table
department-of-veterans-affairs/caseflow pull request #16192
Opened 2021-04-30 18:42 UTC by jcq

Connects [CASEFLOW-1406](https://vajira.max.gov/browse/CASEFLOW-1406)

### Description
This implements the `TaskSelectionTable` component within the existing `SubstituteAppellantTasksForm` component to allow the user to select which task(s) to reopen during substitution.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

2021-05-12 20:40 UTC, yoomlam commented on .nvmrc
> +12.18.4
Ran into this problem:
```
15:35:32 rails.1  | started with pid 85536
15:35:32 client.1 | started with pid 85537
15:35:32 client.1 | nodenv: version `12.18.4' is not installed (set by )
15:35:33 client.1 | exited with code 1
15:35:33 system   | sending SIGTERM to all processes
15:35:33 rails.1  | terminated by SIGTERM
```
Trying to diagnose:
```
> nodenv version
system (set by /Users/yoomlam/.nodenv/version)

> ls -al /Users/yoomlam/.nodenv/versions/
total 0
drwxr-xr-x  4 yoomlam  staff  128 Dec 16  2019 .
drwxr-xr-x  4 yoomlam  staff  128 Sep 16  2019 ..
drwxr-x---  9 yoomlam  staff  288 Dec 16  2019 12.13.0
drwxr-xr-x  9 yoomlam  staff  288 Sep 17  2019 6.11.5
```
Deleting `.nvmrc` allowed me to run.
Correct fix:
```
nodenv install $(cat .nvmrc)
```

2021-05-12 21:57 UTC, yoomlam requested changes
Nice work! I'll continue my review tomorrow. Until then, I left some comments to consider.

2021-05-12 21:57 UTC, yoomlam commented on .nvmrc
> +12.18.4
@jcq says to pull this out of this PR.

2021-05-12 21:57 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +    }
Add more comments to explain why "we only want completed and cancelled tasks"

2021-05-12 21:57 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +    }
Seems like this and the `!task.closedAt` below could be refactored as a `filter` operation, which would reduce the size (and complexity) of this code block.

2021-05-12 21:57 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
> +    return formatTaskData(allTasks);
The name `formatTaskData` doesn't imply any filtering. Hmmm... thinking of a better name. See my comment where `formatTaskData` is defined.

2021-05-12 21:57 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +export const formatTaskData = (taskData) => {
This function name should convey that filtering, sorting, and state is being applied to the `taskData`. How about `prepTaskDataForUI`? I know it's vague but "format" implies less than what is actually happening.
@jcq Thoughts?

2021-05-12 21:57 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
> +    return newIds;
Is this return value being used? If so where and how?

2021-05-12 21:57 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
> +      [...(ids ?? []), checkedId];
Add a comment that describes what these 3 lines are doing.

2021-05-12 21:57 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
> +    return <p>There are no tasks available to reopen</p>;
```suggestion
    return <p>There is no task available to reopen.</p>;
```

2021-05-12 21:57 UTC, yoomlam commented on client/COPY.json
> +  "SUBSTITUTE_APPELLANT_TASK_SELECTION_DESCRIPTION": "Listed below are all the tasks from the original appeal. The distribution task will always be selected by default and cannot be unselected to ens
Copy changes: https://dsva.slack.com/archives/C01BKL4CCRL/p1620855578035900?thread_ts=1620840441.023600&cid=C01BKL4CCRL

2021-05-13 14:40 UTC, pbradin commented on client/COPY.json
> +  "SUBSTITUTE_APPELLANT_TASK_SELECTION_DESCRIPTION": "Listed below are all the tasks from the original appeal. The distribution task will always be selected by default and cannot be unselected to ens
Changes made.

2021-05-13 14:49 UTC, pbradin commented on .nvmrc
> +12.18.4
done

2021-05-13 15:33 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/utils.js
> +export const formatTaskData = (taskData) => {
Renamed as suggested.

2021-05-13 15:33 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
> +    return formatTaskData(allTasks);
Renamed as suggested

2021-05-13 15:35 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
> +    return <p>There are no tasks available to reopen</p>;
updated as suggested

2021-05-13 18:20 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
> +  taskIds: yup.array(yup.string()),
changing this to number

2021-05-13 18:22 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
> +      taskId: PropTypes.oneOfType[(PropTypes.string, PropTypes.number)],
taskIds are strings as stored in Redux coming from serializer. We are changing them to treat them as numbers within this; this just helped us avoid the possibility of prop-types warnings.

2021-05-13 18:37 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
> +    return newIds;
Yes, added comment

2021-05-13 18:37 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
> +      [...(ids ?? []), checkedId];
added comment

2021-05-13 19:05 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +// allItems is object keyed to taskId
> allItems is object keyed to taskId

I don't think this is necessarily the case. Isn't the last parameter determining the key into `allItems`?

2021-05-13 19:06 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +// Generic function to determine if a task is a descendent of another task
```suggestion
// Generic function to determine if a task (`current`) is a descendent of another task (`target`)
```

2021-05-13 19:08 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return isDescendant(allItems, target, parent);
Shouldn't the 4th argument be passed in as well?

2021-05-13 19:09 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  const parent = allItems[current.parentId];
It doesn't seem like the code handles the case where `parent` is null.

2021-05-13 19:14 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return false;
```suggestion
  return alwaysDisabled.includes(taskInfo.type);
```

2021-05-13 19:17 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return taskInfo.type === 'DistributionTask';
Inconsistency: `shouldDisable` uses `includes` whereas this method uses `===`. It's not clear why they use different approaches.

2021-05-13 19:24 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      const task = { type: 'SomeOtherTask' };
This is unrealistic since we'll never have that task type. Can we randomly select from a list of task types that doesn't include `DistributionTask`?

2021-05-13 19:24 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      const task = { type: 'SomeOtherTask' };
This is unrealistic since we'll never have that task type. Can we randomly select from a list of task types that doesn't include `DistributionTask`?

2021-05-13 19:28 UTC, yoomlam commented on client/test/data/queue/substituteAppellant/tasks.js
> +export const sampleEvidenceSubmissionTasks = () => {
These are more than just EWSTasks, right? If so, rename the function.

2021-05-13 19:29 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      expect(filtered.length).toBeLessThan(tasks.length);
Can't the lengths be equal if there's nothing to filter out?

2021-05-13 19:30 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +    it('prefers org tasks', () => {
```suggestion
    it('returns only org tasks', () => {
```

2021-05-13 19:33 UTC, yoomlam commented on client/test/data/queue/substituteAppellant/tasks.js
> +      id: idx + 1,
Add a comment to explain why are we offsetting the id by 1.

2021-05-13 19:33 UTC, yoomlam commented on client/test/data/queue/substituteAppellant/tasks.js
> +// };
Delete?

2021-05-13 19:34 UTC, yoomlam commented on spec/feature/queue/substitute_appellant/shared_setup.rb
> +      # tasks table"
```suggestion
      # tasks table
```

2021-05-13 19:36 UTC, yoomlam commented on spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
> +             stream_type: "original",
Wondering if you really need these 2 lines since those are the default.

2021-05-13 19:37 UTC, yoomlam requested changes
Review complete. Left some suggestions.

2021-05-13 19:50 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/utils.js
> +// allItems is object keyed to taskId
Updated comment

2021-05-13 19:50 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return isDescendant(allItems, target, parent);
With updated code, it properly defaults to taskId

2021-05-13 19:59 UTC, pbradin commented on client/test/data/queue/substituteAppellant/tasks.js
> +export const sampleEvidenceSubmissionTasks = () => {
This simply returns tasks that are potentially appropriate for Evidence Submissions.  Will have similar setup for Hearings.

2021-05-13 21:08 UTC, pbradin commented on spec/feature/queue/substitute_appellant/shared_setup.rb
> +      # tasks table"
updated as suggested

2021-05-13 21:11 UTC, pbradin commented on spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
> +             stream_type: "original",
I have refactored this so docket_type is now a variable and I've removed stream_type.

2021-05-13 21:14 UTC, pbradin commented on client/test/data/queue/substituteAppellant/tasks.js
> +// };
I believe this was a placeholder for later, so I was hesitant to delete it.  But we can always put it back.  Consider it gone.

2021-05-13 21:18 UTC, pbradin commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      const task = { type: 'SomeOtherTask' };
changed to real task

2021-05-13 21:19 UTC, pbradin commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      const task = { type: 'SomeOtherTask' };
changed to real task

2021-05-13 21:19 UTC, pbradin commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +    it('prefers org tasks', () => {
changed as requested.

2021-05-13 21:22 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return taskInfo.type === 'DistributionTask';
Updated return to same format as "shouldDisable"

2021-05-13 21:43 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
> +      taskId: PropTypes.oneOfType[(PropTypes.string, PropTypes.number)],
Do we want to update the serializer to send numbers instead of strings?

2021-05-13 21:45 UTC, jcq commented on client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
> +      taskId: PropTypes.oneOfType[(PropTypes.string, PropTypes.number)],
While that might be a good idea, we weren't sure what other code might rely on assumption that they are currently strings and decided that breaking/fixing that would likely be out of scope for this. 😅

2021-05-13 21:45 UTC, yoomlam commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return isDescendant(allItems, target, parent);
But it shouldn't use the default. It should use the 4th argument, right?

2021-05-13 21:49 UTC, jcq commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return isDescendant(allItems, target, parent);
The 4th argument to `isDescendant` is optional; if provided, it can be a configuration object that allows for overriding the field used for id — if not it now specifies that it would use `taskId`.

2021-05-13 21:50 UTC, jcq commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return isDescendant(allItems, target, parent);
So yeah, we could certainly add the 4th argument here if we wanted to be explicit, but it would just pass the same as what is already default.

2021-05-13 21:55 UTC, jcq commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return isDescendant(allItems, target, parent);
@pbradin Oh! I see what @yoomlam is getting at... while it's totally fine to use the default when calling `isDescendant` from the "outside", it would break during the recursive calls if something other than the default had been specified. 

So we should probably change the return to something like this:
```js
 return isDescendant(allItems, target, parent, {id} );
 
```

2021-05-13 21:58 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      const task = { type: 'EvidenceSubmissionWindowTask' };
This only tests one other task whereas the `it` description says "for others". There's a list of real tasks in client/test/data/queue/substituteAppellant/tasks.js. You can iterate through that list and call `expect(shouldAutoSelect(task)).toBe(false)` for each item in the list. Do the same for `shouldDisable` below.

2021-05-13 22:00 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      expect(filtered.length).toBeLessThan(tasks.length);
For this test, we expect something to be filtered out.

2021-05-13 22:01 UTC, yoomlam commented on client/test/data/queue/substituteAppellant/tasks.js
> +export const sampleEvidenceSubmissionTasks = () => {
Ah, so a better name would be `sampleTasksForEvidenceSubmissionDocket`.

2021-05-13 22:04 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      const task = { type: 'SomeOtherTask' };
See new comment

2021-05-13 22:04 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      const task = { type: 'SomeOtherTask' };
See new comment

2021-05-13 22:07 UTC, yoomlam commented on spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
> +             stream_type: "original",
`stream_type` seems to still be there.

2021-05-13 22:13 UTC, pbradin commented on client/test/data/queue/substituteAppellant/tasks.js
> +export const sampleEvidenceSubmissionTasks = () => {
Yes, JC said the same thing and that there's a lot of places to change that in various PRs... so I think we're going to wait until we work on Hearings to change that.

2021-05-13 22:16 UTC, pbradin commented on client/test/data/queue/substituteAppellant/tasks.js
> +      id: idx + 1,
the array index (idx) is zero-based, so we just incremented by one so that we had more realistic (non-zero) IDs.  Adding comment to the code.

2021-05-13 22:18 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  const parent = allItems[current.parentId];
Updating line 4 to if (!current?.parentId) so it addresses this.

2021-05-13 22:18 UTC, yoomlam commented on client/test/data/queue/substituteAppellant/tasks.js
> +export const sampleEvidenceSubmissionTasks = () => {
Maybe I'm not understanding. `sampleEvidenceSubmissionTasks` is introduced in this PR, right? If so, the only changes would be files already being changed in this PR.
The current function name is very misleading.

2021-05-13 22:22 UTC, pbradin commented on spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
> +             stream_type: "original",
I thought it created an rspec issue when I took it out; it didn't.  So it's now gone again.

2021-05-13 23:51 UTC, pbradin commented on client/test/data/queue/substituteAppellant/tasks.js
> +export const sampleEvidenceSubmissionTasks = () => {
It's introduced in this PR but used by Eileen's PR and I think JC's PR, which build off of this one.  I can change it.  They'll just need to address it on their end too.

2021-05-14 00:22 UTC, pbradin commented on client/test/data/queue/substituteAppellant/tasks.js
> +export const sampleEvidenceSubmissionTasks = () => {
this has been changed.

2021-05-14 00:23 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return isDescendant(allItems, target, parent);
this has been changed as JC described.

2021-05-14 02:25 UTC, pbradin commented on client/test/data/queue/substituteAppellant/tasks.js
> +export const sampleEvidenceSubmissionTasks = () => {
Updated on my end

2021-05-14 02:25 UTC, pbradin commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  return isDescendant(allItems, target, parent);
updated to match JC's suggestion

2021-05-14 02:26 UTC, pbradin commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +      const task = { type: 'EvidenceSubmissionWindowTask' };
This has been updated to include the other tasks and iterating through that list.

2021-05-14 12:56 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +  const nonDistributionTask = ['JudgeAssignTask',
```suggestion
  const nonDistributionTasks = ['JudgeAssignTask',
```

2021-05-14 12:58 UTC, yoomlam commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +        const nonDt = { type: task };
```suggestion
      nonDistributionTaskTypes.forEach((taskType) => {
        const nonDt = { type: taskType };
```

2021-05-14 13:00 UTC, yoomlam approved these changes
Great work! Remaining comments are non-blocking.

2021-05-14 13:10 UTC, pbradin commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +  const nonDistributionTask = ['JudgeAssignTask',
done

2021-05-14 13:10 UTC, pbradin commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +        const nonDt = { type: task };
done

2021-05-14 13:30 UTC, merged