Unrecognized Appellant with Listed POA not Showing
department-of-veterans-affairs/caseflow pull request #16204
Opened 2021-05-04 20:19 UTC by wdrougas-tista

Resolves [Caseflow-1467](https://vajira.max.gov/browse/CASEFLOW-1467)

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-05-05 20:22 UTC, nanotone requested changes
I don't think `appeal.appellant_is_not_veteran` is the appropriate check to nullify these. The appellant could be a recognized dependent, in which case their POA _is_ fetched from BGS and might have an email address or last sync time.

The `power_of_attorney` method gets delegated (without additional Ruby logic) to `UnrecognizedAppellant`, so perhaps the better place to make these null is to add null implementations to `AttorneyPowerOfAttorney` and `UnrecognizedPowerOfAttorney`.

2021-05-06 18:08 UTC, meckila-navapbc commented on app/models/attorney_power_of_attorney.rb
> +  def representative_email_address
Should theses methods also be in UnrecognizedPowerOfAttorney as well?

2021-05-06 18:22 UTC, wdrougas-tista commented on app/models/attorney_power_of_attorney.rb
> +  def representative_email_address
`UnrecognizedPowerOfAttorney` already has them

2021-05-06 18:35 UTC, meckila-navapbc commented on app/models/attorney_power_of_attorney.rb
> +  def representative_email_address
Got it. I see`poa_last_synced_at` but not r`epresentative_email_address`. Is it not needed because the `representative_type` is just "Unrecognized Representative"?

2021-05-06 19:27 UTC, nanotone commented on app/models/attorney_power_of_attorney.rb
> +  def representative_email_address
UnrecognizedPowerOfAttorney does have the email address, it's just implemented as an alias to an existing ActiveRecord attribute.

2021-05-06 19:35 UTC, meckila-navapbc commented on app/models/attorney_power_of_attorney.rb
> +  def representative_email_address
Ah I misunderstood, I thought we had to return nil for the `email_address` there as well.

2021-05-06 19:38 UTC, nanotone approved these changes
I'll go ahead and ✅ this, but with one more ask:

The new rspec actually passes without the bugfix, which means it's not testing for the bug scenario. I think that's because it's inside the generic "when Veteran is not the appellant" context block. There's a more specific "when appellant is an attorney or unlisted claimant" context block that might be more suitable.

2021-05-06 19:39 UTC, meckila-navapbc approved these changes

2021-05-07 14:34 UTC, merged