CASEFLOW-1431 Create tasks for new Substitution appeal
department-of-veterans-affairs/caseflow pull request #16209
Opened 2021-05-05 17:30 UTC by yoomlam

Resolves [CASEFLOW-1431](https://vajira.max.gov/browse/CASEFLOW-1431)

As Clerk of the Board user, when I confirm who the substitute appellant is and select the tasks to create, I want a new appeal to be created and the tasks I selected to be active and routed to the appropriate teams so that the appeal can be decided.

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly
-   After the user selects confirm on the review and confirm page
    -   the selected tasks are created and assigned to the appropriate organizations
        -   If non-colocated IHP task selected verify the IHP task is assigned to substitutes POA
        -   if evidence submission window is selected timed hold should end on the calculated date in [CASEFLOW-1082](https://vajira.max.gov/browse/CASEFLOW-1082 "Add Review & Confirm Page for Substitution")
    -   all typical parent tasks are created or are in existence for the user-selected task
-   -   verify tasks from source appeal are copied over and displayed in the case timeline
    -   the granted substitution date is added to the about the appellant section (see subtask)
    -   the user is taken to the Case Details (see subtask)
-   verify that the new task tree has been properly created

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

2021-05-13 13:49 UTC, yoomlam commented on spec/models/appellant_substitution_spec.rb
> +        end
Some test contexts do not have a EvidenceSubmissionWindowTask, in which case don't add this param.

2021-05-13 13:49 UTC, yoomlam commented on spec/models/appellant_substitution_spec.rb
> +        end
Only expect these task types to be created, which does not include post-distribution tasks.

2021-05-13 13:49 UTC, yoomlam commented on app/workflows/initial_tasks_factory.rb
> +      end
Refactored to address rubocop complaint about too many `elsif` blocks.

2021-05-13 13:49 UTC, yoomlam commented on app/workflows/initial_tasks_factory.rb
> +    fail "Expecting only tasks assigned to organizations" if source_tasks.map(&:assigned_to_type).include?("User")
These should not trigger as long as the frontend enforces these constraints, but it's good to codify these preconditions in case the frontend changes in the future.

2021-05-13 13:49 UTC, yoomlam commented on app/workflows/initial_tasks_factory.rb
> +    end
We may need to treat hearing tasks specially (like ESWTask and IHPTask), but for now just call `copy_with_ancestors_to_stream`.

2021-05-13 13:49 UTC, yoomlam commented on app/workflows/initial_tasks_factory.rb
> +      source_task.copy_with_ancestors_to_stream(@appeal, extra_excluded_attributes: ["status"])
Don't copy task's `status` value to the new task.

2021-05-13 13:49 UTC, yoomlam commented on lib/helpers/sanitized_json_configuration.rb
> +            records[Task].assigned_to_org.map(&:assigned_to)
Use `Organization.unscoped` to include inactive organizations when exporting.

2021-05-13 13:49 UTC, yoomlam commented on lib/helpers/sanitized_json_configuration.rb
> +      },
Reordering so that `OrganizationsUser.retrieval` is called before `Organization.retrieval`.

2021-05-17 20:38 UTC, yoomlam commented on app/controllers/appellant_substitutions_controller.rb
> +    task_params: {}
Non-primitive values uses a different syntax -- see https://stackoverflow.com/questions/16549382/how-to-permit-an-array-with-strong-parameters.

2021-05-17 20:38 UTC, yoomlam commented on client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
> +      taskId: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
Fix for a browser console warning.

2021-05-17 20:38 UTC, yoomlam commented on client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
> +    }
I anticipant we'll have to add other task creation parameters in the future. Do that here.

2021-05-17 20:38 UTC, yoomlam commented on client/app/queue/substituteAppellant/substituteAppellant.slice.js
> +    }
Update Redux with the result of calling `refreshAppellantPoa`

2021-05-18 16:30 UTC, jcq requested changes
I think the main flag around functionality is to ensure we're handling time zones in such a way that we don't end up with the evidence submission window ending a day prior to when it should

2021-05-18 16:30 UTC, jcq commented on spec/models/appellant_substitution_spec.rb
> +    context "when source appeal has ScheduleHearingTask and EvidenceSubmissionWindowTask" do
Should we have separate tests/contexts for the different docket types? This seems to be adding a `ScheduleHearingTask` to an `evidence_submission` docket appeal; while it's probably sufficient for testing the desired functionality, it might be clearer to folks down the line if we maybe separate and make more explicit?

2021-05-18 16:54 UTC, yoomlam commented on app/workflows/initial_tasks_factory.rb
> +    # An InformalHearingPresentationTask is only created if
Or I got distracted.
`An InformalHearingPresentationTask is only created for appeal.representatives`

2021-05-18 16:57 UTC, yoomlam commented on spec/records/appeal-21430.json
> +      "summary": "<p><strong>Contentions</strong>&nbsp;</p>\n<p><span style=\"color: rgb(0,0,255);\">Quis et beatae fuga architecto et non eligendi.</span></p>\n<p><strong>Evidence</strong>&nbsp;</p>
No, it's randomly generated using a template -- see `SanitizationTransforms#obfuscate_sentence`.

2021-05-18 16:58 UTC, yoomlam commented on client/app/queue/substituteAppellant/substituteAppellant.slice.js
> +    }
Thanks to your help!

2021-05-18 17:04 UTC, yoomlam commented on spec/models/appellant_substitution_spec.rb
> +    context "when source appeal has ScheduleHearingTask and EvidenceSubmissionWindowTask" do
Separating it into another context adds more RSpec lines than may be worth the benefit. How about I change the appeal to a `hearing` docket?

2021-05-18 18:35 UTC, yoomlam commented on app/workflows/initial_tasks_factory.rb
> +                                         end_date: evidence_submission_hold_end_date)
I spent a good bit of time on this. Setting hours to 12 feels hack-y or at least arbitrary. I'm open to a discussion, but here are some reasons for using UTC:
* https://thoughtbot.com/blog/its-about-time-zones says to "Always work with UTC."
* `EvidenceSubmissionWindowTask#timer_ends_at` returns the desired end hold date in UTC. If we specify a time, it may appear that we intended a specific time, which we don't.
* Specifying a time can delay `TaskTimerJob` from causing the timer to end and assigning the task.

2021-05-18 18:40 UTC, jcq commented on spec/models/appellant_substitution_spec.rb
> +    context "when source appeal has ScheduleHearingTask and EvidenceSubmissionWindowTask" do
Yeah, I think that can work; it covers the hardest of the use cases w/o potentially confusing folks in the future

Totally fine to have the other stuff covered by the sanitized data

2021-05-18 18:45 UTC, jcq commented on app/workflows/initial_tasks_factory.rb
> +                                         end_date: evidence_submission_hold_end_date)
Totally agree about always preferring to work in UTC; I guess the main issue is that the current frontend code isn't doing the same, and since it isn't specifying a time, we're ending up with the window ending a day earlier than expected. Due to the offset, it wouldn't _actually_ likely negatively impact the actual process since it would end after normal VA business hours in the US, but my main concern is that a user who looks at it might be confused as to why it's off by a day.

2021-05-18 18:46 UTC, jcq commented on app/workflows/initial_tasks_factory.rb
> +                                         end_date: evidence_submission_hold_end_date)
Now that I think about it, however... can users actually see the end date in the UI? It occurs to me that I don't actually know how/where to find that w/o the console

2021-05-18 18:54 UTC, yoomlam commented on app/workflows/initial_tasks_factory.rb
> +                                         end_date: evidence_submission_hold_end_date)
I don't believe they can see it. Even if they could, I _might_ argue that the frontend should interpret this particular timestamp properly, i.e., as a UTC date and ignoring the time component.

2021-05-20 16:50 UTC, jcq commented on app/workflows/initial_tasks_factory.rb
> +                                         end_date: evidence_submission_hold_end_date)
Will create another ticket to adjust the frontend code to pass along a full ISO date/time string that specifies the date w/ tz offset.

2021-05-20 16:51 UTC, jcq approved these changes
Approved, though we will create a follow-up ticket to change frontend handling of date/time string

2021-05-21 21:54 UTC, yoomlam commented
Waiting for [CASEFLOW-1575](https://vajira.max.gov/browse/CASEFLOW-1575) to allow demo-ing of user-selected IHPTask.
[Slack](https://dsva.slack.com/archives/CJL810329/p1621628622133100?thread_ts=1621613660.118300&cid=CJL810329)

2021-05-26 20:02 UTC, merged