Mkerns/caseflow 1384 ihp task cancellation
department-of-veterans-affairs/caseflow pull request #16233
Opened 2021-05-10 14:43 UTC by mkerns355

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-05-12 14:46 UTC, bgantick commented on app/models/bgs_power_of_attorney.rb
> +  after_save :update_ihp_task, if: :saved_change_to_poa_participant_id?
Should we add a feature toggle here (cc: @ajspotts)?

2021-05-12 18:09 UTC, bgantick requested changes

2021-05-12 18:09 UTC, bgantick commented on app/models/tasks/informal_hearing_presentation_task.rb
> +    # parent.on_hold!
```suggestion
```

2021-05-12 18:09 UTC, bgantick commented on app/models/tasks/informal_hearing_presentation_task.rb
> +      TrackVeteranTask.sync_tracking_tasks(appeal)
This only accounts for the happy path where the parent task of the cancelled IHP task is same as the new IHP task. Manual intervention might still be needed for outliers/edge-cases. Unsure we need to do anything here, just noting (cc @ajspotts)

2021-05-12 18:09 UTC, bgantick commented on lib/fakes/constants/BGS_SERVICE.json
> +  "UPDATED_POA_NAME": "Bruce Wayne"
Are we using this?

2021-05-12 18:09 UTC, bgantick commented on lib/fakes/bgs_service.rb
> +
Are we using this?

2021-05-12 18:09 UTC, bgantick commented on lib/fakes/bgs_service.rb
> +    record ||= updated_power_of_attorney_record if file_number == UPDATED_POA_FILE_NUMBER
Remove?

2021-05-12 18:09 UTC, bgantick commented on lib/fakes/bgs_service.rb
> +  UPDATED_POA_FILE_NUMBER = ""
Remove?

2021-05-12 18:46 UTC, Jeremy1026 commented on app/models/bgs_power_of_attorney.rb
> +  after_save :update_ihp_task, if: :saved_change_to_poa_participant_id?
I believe we decided this didn't need its own toggle since it is already behind poa_refresh, tangibly.

2021-05-12 18:46 UTC, Jeremy1026 commented on lib/fakes/constants/BGS_SERVICE.json
> +  "UPDATED_POA_NAME": "Bruce Wayne"
+1

2021-05-12 18:46 UTC, Jeremy1026 commented on lib/fakes/bgs_service.rb
> +
+1

2021-05-12 18:46 UTC, Jeremy1026 commented on lib/fakes/bgs_service.rb
> +    record ||= updated_power_of_attorney_record if file_number == UPDATED_POA_FILE_NUMBER
+1

2021-05-12 18:46 UTC, Jeremy1026 commented on lib/fakes/bgs_service.rb
> +  UPDATED_POA_FILE_NUMBER = ""
+1

2021-05-12 18:46 UTC, Jeremy1026 commented on app/models/tasks/informal_hearing_presentation_task.rb
> +    # parent.on_hold!
+1

2021-05-12 18:46 UTC, Jeremy1026 commented on app/models/tasks/informal_hearing_presentation_task.rb
> +    # parent = appeal.tasks.open.where(type: :InformalHearingPresentationTask).first.parent
+1

2021-05-12 19:44 UTC, ajspotts commented on app/models/bgs_power_of_attorney.rb
> +  after_save :update_ihp_task, if: :saved_change_to_poa_participant_id?
If the ask is should we put it behind the poa_refresh FT - then if it isn't already then I would say to be safe yes

2021-05-12 19:48 UTC, ajspotts commented on app/models/tasks/informal_hearing_presentation_task.rb
> +      TrackVeteranTask.sync_tracking_tasks(appeal)
Agreed - manual task tree inspections will still be necessary on certain occasions. If we notice consistent behavior in terms of other paths down the road that we can emulate in the code then we can file tech debt tickets to compensate.

2021-05-12 20:34 UTC, mkerns355 commented on app/models/bgs_power_of_attorney.rb
> +  after_save :update_ihp_task, if: :saved_change_to_poa_participant_id?
The only area that I'm not sure is behind a FT is during page load. Will confirm before closing PR.

2021-05-13 14:08 UTC, bgantick commented on app/models/bgs_power_of_attorney.rb
> +  after_save :update_ihp_task, if: :saved_change_to_poa_participant_id?
This wouldn't be behind a feature toggle through other POA refresh work, as this would be triggered by any change to poa_participant_id (via manual intervention, on intake, etc).

2021-05-20 20:23 UTC, bgantick approved these changes

2021-05-20 21:45 UTC, merged