[WIP] Show substitution granted date; adds AppellantSubstitution factory
department-of-veterans-affairs/caseflow pull request #16244
Opened 2021-05-13 14:47 UTC by n1zyy

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-05-14 20:20 UTC, n1zyy commented on spec/feature/queue/case_details_spec.rb
> +        end
I moved most of this existing section into a "The 'Add Substitute' button" section. We're already in a "substitute appellant" describe block.

2021-05-14 20:20 UTC, n1zyy commented on spec/feature/queue/case_details_spec.rb
> +      context "when there is a substitute appellant" do
This context is the only new test here.

2021-05-14 20:20 UTC, n1zyy commented on client/app/queue/CaseDetailsView.jsx
> +              substitutionDate={appeal.appellantSubstitution?.substitution_date}
So the linter is yelling at me because this last param is `substitution_date`, not camelCase. But that's how it's returned from the backend. What's the best way of dealing with this? Renaming the returned parameters to camelCase feels absurd to me.

2021-05-17 15:09 UTC, eileen-nava requested changes
Overall, this looks good to me!  I did make a suggestion for how to fix the linter error that you pointed out.  Please address that before merging.

2021-05-17 15:09 UTC, eileen-nava commented on client/app/queue/CaseDetailsView.jsx
> +              substitutionDate={appeal.appellantSubstitution?.substitution_date}
How about this? 
```
              substitutionDate={appeal.appellantSubstitution && appeal.appellantSubstitution.substitution_date}
```

This didn't cause any linter errors for me locally, and it displays the desired information.

2021-05-17 15:09 UTC, eileen-nava commented on spec/feature/queue/case_details_spec.rb
> +      context "when there is a substitute appellant" do
Thanks for pointing this out!

2021-05-18 19:29 UTC, eileen-nava approved these changes
Thanks for making the requested changes.  This looks good to me.

2021-05-19 16:49 UTC, n1zyy commented
Demoed this to Ann-Marie last week. Marking as being ready for merge!

2021-05-19 17:10 UTC, merged