Add front end validation to receipt date field
department-of-veterans-affairs/caseflow pull request #16280
Opened 2021-05-21 17:29 UTC by nweinmeister

Resolves CASEFLOW-1566

### Description
Add validation to the receipt date field to ensure that the date entered is not prior to the AMA start date

### Acceptance Criteria
- If a user enters a date prior to the AMA start date, chooses unrecognized claimant, and tries to move to next step, they should receive an error informing them that the receipt date cannot be before the AMA date

### Testing Plan
1. Start an NOD appeal
2. On the review page, enter a receipt date prior to 02/19/2019
3. Choose Yes for Claimant other than someone listed
4. Choose claimant not listed
5. Click continue to next step
6. See that there is an error on the receipt date field

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

2021-05-21 19:09 UTC, nweinmeister commented on client/app/intake/pages/review.jsx
> +    is: REVIEW_OPTIONS.APPEAL.key,
Only validate if it's an appeal:
1. Appeals are the only option where the receipt date issue is a bug (adding a new claimant)
2. To keep this PR small, if we want to add this check to the other form types, we can roll out one at a time, since it requires redux updates, and spec fixes since a lot of the specs are expected the backend validation to go through and adding a front end check prevents it from making to the back end

2021-05-24 15:43 UTC, nanotone requested changes
I added a couple of high-level comments for my first pass at this. They might lead to a little re-structuring but I don't think it'll be drastic.

2021-05-24 15:43 UTC, nanotone commented on client/app/intake/reducers/appeal.js
> +  case ACTIONS.SET_RECEIPT_DATE_ERROR:
Have you looked at using the existing action called `SUBMIT_REVIEW_FAIL` which sets error states for the review page?

I'm not categorically opposed to adding a new action, but one nice thing about using the existing action is that it's already implemented for the 5 form types, and it's conceivable that HLRs and SCs will eventually make use of the fix in this PR.

2021-05-24 15:43 UTC, nanotone commented on client/app/intake/pages/review.jsx
> +import moment from 'moment';
Moment is [deprecated](https://momentjs.com/docs/), so when adding a new import we usually try to go with [date-fns](https://date-fns.org/) -- there are a bunch of examples elsewhere in the frontend codebase where that gets used.

2021-05-24 15:51 UTC, nweinmeister commented on client/app/intake/pages/review.jsx
> +import moment from 'moment';
Ah thanks for pointing that out, will switch that out 👍

2021-05-24 16:44 UTC, nweinmeister commented on client/app/intake/reducers/appeal.js
> +  case ACTIONS.SET_RECEIPT_DATE_ERROR:
Just looked at switching to use `SUBMIT_REVIEW_FAIL` instead. I think I could force it to work, but it would involve adding an additional layer on top of the yup validation to shape the errors in a way that matches the payload expected by `SUBMIT_REVIEW_FAIL`. 
There is a `validateReviewData` that currently exists in util that does some simple front end validation, but the reason I chose to not use this in the first place is to try to use yup validation instead of our own custom validation. Yups simple to use and easy to test so I always feel like that's a little safer to use than custom validations but let me know what you think @nanotone

2021-05-24 17:50 UTC, nweinmeister commented
Closing this and using https://github.com/department-of-veterans-affairs/caseflow/pull/16283/files instead. Will want to revisit switching Yup for frontend validation at a later date.

2021-05-25 16:52 UTC, Sjones352 commented on spec/feature/intake/review_page_spec.rb
> +    before { FeatureToggle.enable!(:non_veteran_claimants) }
Can you add a  `after { FeatureToggle.disable!(:use_ama_activation_date) }` for both feature toggles

2021-05-25 16:57 UTC, nweinmeister commented on spec/feature/intake/review_page_spec.rb
> +    before { FeatureToggle.enable!(:non_veteran_claimants) }
done 👍

2021-05-25 19:33 UTC, leikkisa approved these changes
Nice job striking a balance, this looks great. I tested out a bunch of different permutations locally as well, and it seems like everything is working well.

2021-05-25 19:33 UTC, leikkisa commented on spec/feature/intake/review_page_spec.rb
> +    before { FeatureToggle.enable!(:non_veteran_claimants) }
Just for context, the feature toggles don't automatically reset themselves, so it can impact other tests.  These could be combined into one before and one after block too, but this is okay too.

2021-05-25 20:35 UTC, merged