Refactor intake forms to add Yup validations
department-of-veterans-affairs/caseflow pull request #16291
Opened 2021-05-25 20:36 UTC by nweinmeister

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-05-26 14:12 UTC, nweinmeister commented on client/app/intake/components/SelectClaimant.jsx
> +          errorMessage={claimantError || props.errors?.['claimant-options']?.message}
On all these `errorMessage`s, check for the old error first (server side validation error) then render the yup error if none. That way we maintain server validation alerts if anything slips through the yup validations.

2021-05-26 14:13 UTC, nweinmeister commented on client/app/intake/components/SelectClaimant.jsx
> +const selectClaimantValidations = () => ({
Export this yup snippet to be shared by any of the forms using the select claimant input since it's slightly more complex than just string.required.

2021-05-26 14:16 UTC, nweinmeister commented on client/app/intake/pages/rampElection/review.jsx
> +  ...receiptDateInputValidation()
I chose to keep the RAMP election validations minimal because:
1. I don't fully understand the workflow yet
2. There's a few tests that expect you to be able to submit a ramp election after only filling out the receipt date in order to render back end validations. Next iteration would be adding the additional RAMP election date validation

2021-05-26 14:17 UTC, nweinmeister commented on client/app/intake/pages/receiptDateInput.jsx
> +const ReceiptDateInput = ({
Just a wrapper for all the shared usage of the receipt date input. Includes the validation schema for the receipt date so that we can share that in all the separate review pages schemas.

2021-05-26 14:18 UTC, nweinmeister commented on client/app/intake/pages/review.jsx
> +    <form
Adding a form wrapper to capture the submit feature of yupResolver and react useForm.

2021-05-26 14:20 UTC, nweinmeister commented on client/app/intake/pages/review.jsx
> +const ReviewNextButton = (props) => {
Made this a functional component and removed submission logic from the button. Needed to (and made more sense) to have submission logic in the Review component. The button is now just a submit button which will trigger the yup validations on submit.

2021-05-28 21:39 UTC, leikkisa requested changes
Overall this looks great! I'm a big fan of this refactor and some of the additional refactoring you did as well.

I have one primary change request, that at least the ama flag be turned to TRUE for the HigherLevelReview and SupplementalClaim forms (which are AMA, as opposed to RAMP).

There's another small front-end error you can take a look at as well, it seems low priority (especially since I think it would only impact RAMP).

2021-05-28 21:39 UTC, leikkisa commented on client/app/intake/pages/receiptDateInput.jsx
> +    {
In case you're curious, the RAMP election receipt date validation uses the same AMA_ACTIVATION_TEST date, (although not the refiling).  This can be found in `RampElection.validate_receipt_date` which calls `RampReview.validate_receipt_date_not_before_ramp`. It shouldn't be necessary to add it to Yup with the backend validation still in place though.

2021-05-28 21:39 UTC, leikkisa commented on client/app/intake/pages/review.jsx
> +const schemaMappings = {
Nice, I like how you did all of this

2021-05-28 21:39 UTC, leikkisa commented on client/app/intake/pages/appeal/review.jsx
> +  'different-claimant-option': yup.string().required(CLAIMANT_ERRORS.blank),
Hmm, I don't love using the CLAIMANT_ERRORS here for other things, it's just a bit confusing for readability.  Maybe it'd be useful to make a generic blank error?

2021-05-28 21:39 UTC, leikkisa commented on client/app/intake/pages/receiptDateInput.jsx
> +    errorMessage={receiptDateError || errors?.['receipt-date']?.message}
I think that when the receiptDateError is set from the backend, after the date is updated it is not clearing the receiptDateError, so it's not showing the new error. For example, if you start a Ramp Election from a too old date to a new old date, it still shows the too old date error. I can add a screenshot.

This may be able to be addressed by clearing it onChange, or maybe switching the order of these.

2021-05-28 21:39 UTC, leikkisa commented on client/app/intake/pages/supplementalClaim/review.jsx
> +  ...receiptDateInputValidation()
I think this needs the `true` flag for the AMA validation, it does not seem to be working on the Supplemental Claim review page.

2021-05-28 21:39 UTC, leikkisa commented on client/app/intake/pages/higherLevelReview/review.jsx
> +  ...receiptDateInputValidation()
Same, comment, I think this needs the `true` flag. It's really just RAMP that doesn't.

2021-05-28 21:39 UTC, leikkisa commented on client/app/intake/pages/receiptDateInput.jsx
> +    errorMessage={receiptDateError || errors?.['receipt-date']?.message}
This may also be able to be addressed through adding it to the Yup schema, for Ramp Election it's the same as the AMA_ACTIVATION_TEST date. For the RAMP Refiling, it has to be later than the Ramp Election receipt date, so a little more complicated. The backend validation is working well for these, just not re-setting once the date changes.

This seems like a super edge case error that has a low impact, so I don't feel it's required to address it, but it may not be that bad.

2021-05-28 21:41 UTC, leikkisa commented
I took some screenshots of what worked great too, but here are a couple of bug screenshots:

Minimum AMA receipt date validation not working on claim review pages (HigherLevelReview and SupplementalClaim):
![Screen Shot 2021-05-28 at 2 28 32 PM](https://user-images.githubusercontent.com/6589610/120044477-c8e5dc00-bfc2-11eb-9c4b-c1327eb3221e.png)


RAMP - error doesn't show future error after past error shown first (low priority).
![Screen Shot 2021-05-28 at 2 18 04 PM](https://user-images.githubusercontent.com/6589610/120044424-afdd2b00-bfc2-11eb-9846-0c1b391f1ff7.png)

2021-06-01 13:27 UTC, nweinmeister commented on client/app/intake/pages/appeal/review.jsx
> +  'different-claimant-option': yup.string().required(CLAIMANT_ERRORS.blank),
Yea I was sorta thinking the same thing but wasn't sure. I'll create a generic blank error to use here.

2021-06-01 13:39 UTC, nweinmeister commented on client/app/intake/pages/receiptDateInput.jsx
> +    errorMessage={receiptDateError || errors?.['receipt-date']?.message}
I think it makes sense switching to use the Yup validation error first, and then the backend error, at least for the receipt date since we're going to continue to rely on some backend validation. I'll switch the order for this one, good catch!

2021-06-01 13:42 UTC, nweinmeister commented on client/app/intake/pages/review.jsx
> +const schemaMappings = {
Thanks!

2021-06-01 15:47 UTC, nweinmeister commented on client/app/intake/pages/supplementalClaim/review.jsx
> +  ...receiptDateInputValidation()
So I gave this another try just to be sure, but there's some feature tests that expect the backend validation to get triggered for these review pages, so I'll have to update the tests to add the additional validation to these. I'm suggesting that we do that in a subsequent PR to keep this one from ballooning anymore. The AMA validation still occurs for these review pages, just only on the backend. Also, since there's no option to add a claimant for these, the original bug will not occur either.

2021-06-01 15:54 UTC, nweinmeister commented on client/app/intake/pages/receiptDateInput.jsx
> +    {
Yea I'd like to look into that too as next steps, see how much validation we can include in the front end that is.

2021-06-01 17:19 UTC, leikkisa approved these changes
Re-tested and everything seems to be working perfectly. Thanks for the updates! I added one minor non-blocking comments on the date constants.

2021-06-01 17:19 UTC, leikkisa commented on client/app/intake/constants.js
> +export const GENERIC_FORM_ERRORS = {
Haha, nice, thanks!

2021-06-01 17:19 UTC, leikkisa commented on client/app/intake/pages/higherLevelReview/review.jsx
> +  ...receiptDateInputValidation(true)
Tested and it's working 👍

2021-06-01 17:19 UTC, leikkisa commented on client/test/app/intake/pages/review.test.js
>  const BEFORE_AMA_TEST_DATE = '10/31/2017'
Ideally these dates in the test file would be connected to the shared DATES.json constants file, there are examples of importing those elsewhere. Those files are able to be access by both the front and back-ends.

2021-06-01 22:04 UTC, meckila-navapbc approved these changes

2021-06-01 23:50 UTC, merged