fetch bgs_poa appeals by claimant_participant_id
department-of-veterans-affairs/caseflow pull request #16350
Opened 2021-06-09 20:54 UTC by ajspotts

Resolves [CASEFLOW-1709](https://vajira.max.gov/browse/CASEFLOW-1709)

### Description
We had been incorrectly searching for appeals by the `poa_participant_id` in `BgsPowerOfAttorney` when deciding appeals IHP tasks to update.  This PR changes it so that we are correctly searching for appeals by the claimant_participant_id

### Acceptance Criteria
- [ ] Code compiles correctly

2021-06-09 21:00 UTC, bgantick commented on app/models/bgs_power_of_attorney.rb
> +    Appeal.where(veteran_file_number: file_number, claimant_participant_id: claimant_participant_id)
How is `claimant_participant_id` determined for an appeal? I'm not seeing it in the appeal model or schema for appeals.

2021-06-09 21:10 UTC, ajspotts commented on app/models/bgs_power_of_attorney.rb
> +    Appeal.where(veteran_file_number: file_number, claimant_participant_id: claimant_participant_id)
For AMAs (could be mistaken) but perhaps it is the `claimant_participant_id` on the [end_product_establishment](https://github.com/department-of-veterans-affairs/caseflow/blob/9fc0d64317c89d72c6de550632376137c106a226/db/schema.rb#L585) as I believe an EPE is needed to create a new AMA appeal.

For Legacy I see [this method](https://github.com/department-of-veterans-affairs/caseflow/blob/9fc0d64317c89d72c6de550632376137c106a226/app/models/legacy_appeal.rb#L1012) on the model which in return seems to check the Person model.

2021-06-10 21:25 UTC, ajspotts commented on app/models/bgs_power_of_attorney.rb
> +    Appeal.where(veteran_file_number: file_number, claimant_participant_id: claimant_participant_id)
Update: per @bgantick's original point we do not have direct access to the `claimant_participant_id` on an appeal.  What we are able to do instead within BgsPowerOfAttorney is use the associate claimants to find the appropriate appeals  - `decision_review_type: "Appeal"` -  and subsequently filter for the active appeal (Claimant's can only have one active appeal at a time).

2021-06-11 12:59 UTC, bgantick requested changes

2021-06-11 12:59 UTC, bgantick commented on app/models/bgs_power_of_attorney.rb
> +    claimants.select(decision_review_type: "Appeal")
Should this be something like:
```suggestion
    claimants.select { |c| c.decision_review_type == "Appeal" }
```
Also, this only gets the claimant. We don't have the appeal yet.

2021-06-11 14:37 UTC, ajspotts commented on app/models/bgs_power_of_attorney.rb
> +    claimant = claimants.select { |c| c.decision_review_type == "Appeal" }
Good catch here @bgantick, `claimants.select(decision_review_type: "Appeal")` returned an `Unsupported argument type: Hash` error 😱

2021-06-11 14:37 UTC, ajspotts commented on app/models/bgs_power_of_attorney.rb
> +    Appeal.where(id: claimant.first.decision_review_id)
I believe this give us the appeals we want, which we then filter for only active ones in `update_ihp_task`

2021-06-11 14:44 UTC, bgantick commented on app/models/bgs_power_of_attorney.rb
> +    Appeal.where(id: claimant.first.decision_review_id)
Do we want to return all appeals instead of just the one for `claimant.first` (`claimant` could return multiple claimants)? I don't know if there's a real-world scenario where this would happen.

2021-06-11 16:14 UTC, bgantick commented on app/models/bgs_power_of_attorney.rb
> +    appeal_claimants.each { |claimant| returned_appeals << Appeal.where(id: claimant.decision_review_id) }
need to return `returned_appeals` here

2021-06-11 16:19 UTC, ajspotts commented on spec/models/bgs_power_of_attorney_spec.rb
> -      after { FeatureToggle.enable!(:poa_auto_ihp_update) }
unnecessary to re-enable the FeatureToggle at this point

2021-06-11 16:24 UTC, Jeremy1026 commented on spec/models/bgs_power_of_attorney_spec.rb
> -      after { FeatureToggle.enable!(:poa_auto_ihp_update) }
Shouldn't we tear back down once this specific test is complete, especially since this toggle is re-enabled at the beginning in the next test. Kind of a "leave no trace" mindset.

2021-06-11 16:27 UTC, ajspotts commented on spec/models/bgs_power_of_attorney_spec.rb
> -      after { FeatureToggle.enable!(:poa_auto_ihp_update) }
After looking at this one with @leikkisa, she posited that each instance runs individually and in fact re-enabling afterward could potentially inject flakes

2021-06-11 16:28 UTC, Jeremy1026 commented on spec/models/bgs_power_of_attorney_spec.rb
> -      after { FeatureToggle.enable!(:poa_auto_ihp_update) }
Ok, good enough for me.

2021-06-11 16:30 UTC, Jeremy1026 commented on app/models/bgs_power_of_attorney.rb
> +    appeal_claimants = claimants.select { |appeal_claimant| claimant.decision_review_type == "Appeal" }
You changed the variable name for the loop to `appeal_claimant`, but didn't change it when you use it and its still `claimant`.

2021-06-11 16:31 UTC, Jeremy1026 approved these changes

2021-06-11 17:55 UTC, merged

2021-06-29 14:58 UTC, yoomlam commented on app/models/bgs_power_of_attorney.rb
> +    appeal_claimants = claimants.select { |appeal_claimant| appeal_claimant.decision_review_type == "Appeal" }
Suggest pushing query to the database
```ruby
appeal_claimants = claimants.where(decision_review_type: "Appeal")
```

2021-06-29 15:01 UTC, yoomlam commented on app/models/bgs_power_of_attorney.rb
> +    end
```ruby
returned_appeals = Appeal.where(id: appeal_claimants.pluck(:decision_review_id))
```

2021-06-29 15:09 UTC, ajspotts commented on app/models/bgs_power_of_attorney.rb
> +    appeal_claimants = claimants.select { |appeal_claimant| appeal_claimant.decision_review_type == "Appeal" }
Yep `where` seems to be preferable [in terms of performance](https://stackoverflow.com/questions/34034571/rails-when-to-use-activerecords-where-and-select)