Enable Substitution for Hearing Appeals w/ Feature Toggle
department-of-veterans-affairs/caseflow pull request #16418
Opened 2021-06-28 16:58 UTC by jcq

Connects [CASEFLOW-1485](https://vajira.max.gov/browse/CASEFLOW-1485)

### Description
This enables support for the `hearings_substitution_death_dismissal` feature toggle, by which we will control display the "Add Substitution" button for hearing-docket appeals after death dismissal.

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] "Add Substitution" button shows/works for `hearing` appeals if feature toggle is enabled
- [ ] Button does not show for `hearing` appeals if feature toggle off

### Testing Plan
1. Confirm that button does not show when feature toggle is not enabled
2. Enable `hearings_substitution_death_dismissal` feature toggle
3. Confirm button shows/works for hearing-docket appeal

2021-06-28 16:58 UTC, jcq commented on app/views/queue/index.html.erb
> +      hearings_substitution_death_dismissal: FeatureToggle.enabled?(:hearings_substitution_death_dismissal, user: current_user)
This allows us to send it to the frontend

2021-06-28 16:59 UTC, jcq commented on client/app/queue/CaseDetailsView.jsx
> +    (appeal.docketName !== 'hearing' || props.featureToggles.hearings_substitution_death_dismissal) &&
Update our existing conditional

2021-06-28 16:59 UTC, jcq commented on spec/feature/queue/substitute_appellant/shared_setup.rb
> +RSpec.shared_context("with recognized_granted_substitution_after_dd feature toggle") do
Rename this existing context to be more specific

2021-06-28 18:51 UTC, jcq commented on db/seeds/substitutions.rb
> +        %w[direct_review evidence_submission hearing].each do |docket_type|
Whoops, this was a mistake in original seeds — should be singular `hearing` rather than plural

2021-06-28 20:21 UTC, eileen-nava requested changes
I think that the functionality for non-admin COB users needs to be tweaked.  However, the functionality works well for admin COB users. 👍

2021-06-28 20:21 UTC, eileen-nava commented on client/app/queue/CaseDetailsView.jsx
>      (userIsCobAdmin || appeal.decisionIssues.some(decisionHasDismissedDeathDisposition)) &&
This allows the non-admin COB user to add a substitute if at least one of the decision issues has the disposition of `dismissed_death`.  I don't think that matches the below AC.
>The Clerk of the Board Non-Admin user is able to view and select adding a substitute on dispatched appeal for a Veteran on the hearings docket if the following is met: 
All issue dispositions "Dismissed, Death" 

Screenshots from an appeal where I made one decision issues `dismissed_death`.  I don't know why the decision issues still display as allowed on the front-end, you can see in the terminal that one of them is now `dismissed_death`:
<img width="1768" alt="Screen Shot 2021-06-28 at 4 15 52 PM" src="https://user-images.githubusercontent.com/80347702/123698844-93841680-d82c-11eb-8198-8c37643a6757.png">

<img width="1768" alt="Screen Shot 2021-06-28 at 4 17 02 PM" src="https://user-images.githubusercontent.com/80347702/123698966-b7475c80-d82c-11eb-9c30-e4bc2e1b12fb.png">

2021-06-28 21:04 UTC, jcq commented on spec/feature/queue/substitute_appellant/shared_setup.rb
>      FeatureToggle.enable!(:recognized_granted_substitution_after_dd)
Totally! I think the weird difference between the two was a quirk of how I originally created it; I thought it would involve a longer line than it did, and then forgot to just clean it up to be consistently formatted. 😅

2021-06-28 21:04 UTC, jcq commented on spec/feature/queue/substitute_appellant/shared_setup.rb
> +    FeatureToggle.enable!(:hearings_substitution_death_dismissal)
Nope, just forgot to consistently format. Fixing!

2021-06-28 21:11 UTC, jcq commented on client/app/queue/CaseDetailsView.jsx
>      (userIsCobAdmin || appeal.decisionIssues.some(decisionHasDismissedDeathDisposition)) &&
This is a good catch — while it's not specific to this ticket/PR, it is a bit of logic that seems to not match exactly with the AC as explicitly stated. _In theory_ it shouldn't actually have a real effect, as there shouldn't ever be cases where only some issues have had `dismissed_death`, but clarity around how we want to handle this would be good. I'll verify w/ Ann-Marie and possibly update the logic here accordingly.

2021-06-29 19:58 UTC, eileen-nava approved these changes
Approved!

2021-06-29 19:58 UTC, eileen-nava commented on client/app/queue/substituteAppellant/caseDetails/utils.js
> +        appeal.decisionIssues.every(decisionHasDismissedDeathDisposition)) &&
🎉

2021-06-29 19:58 UTC, eileen-nava commented on client/test/app/queue/substituteAppellant/caseDetails/utils.test.js
> +  describe('with sensible defaults', () => {
🎩 💁‍♀️ to the word sensible.

2021-06-29 19:58 UTC, eileen-nava commented on client/test/app/queue/substituteAppellant/caseDetails/utils.test.js
> +describe('shouldSupportSubstituteAppellant', () => {
Good work testing thoroughly! 🙌

2021-06-29 20:25 UTC, merged