Attorney Claimant Bug Fix - Claim Establishment
department-of-veterans-affairs/caseflow pull request #16488
Opened 2021-07-14 17:17 UTC by wdrougas-tista

### Description
As part of the Attorney Fees work, Caseflow Intake now allows users to select an attorney claimant from a list of attorneys available in the Corporate database. This creates an `AttorneyClaimant` record in Caseflow DB upon submission of the Intake and stores the `participant_id` of the `PrivateBar` that attorney belongs to. This results in a failure when attempting to establish Board Grant Claims in VBMS because we are not using a valid participantPersonId. 

The Board determined that VBA needs to pay the attorney and the claim will need to created using the Veteran's participant ID, even though the attorney is the claimant, as this is a payment issue related to the Veteran’s benefits.

2021-07-19 20:21 UTC, nanotone reviewed
Good catch, I was curious whether there'd be any hiccups in BGEs for Attorney Fees cases.

Question: why does the DecisionReview also need the new code? If it's just being used for the BGE logic, I think it would be good to try to de-duplicate the code. If it's not, I don't think it makes sense for `claimant_participant_id` to return not-the-claimant's PID.

2021-07-20 12:24 UTC, wdrougas-tista commented
> Good catch, I was curious whether there'd be any hiccups in BGEs for Attorney Fees cases.
> 
> Question: why does the DecisionReview also need the new code? If it's just being used for the BGE logic, I think it would be good to try to de-duplicate the code. If it's not, I don't think it makes sense for `claimant_participant_id` to return not-the-claimant's PID.

The thought here was in case there were remand supplemental claims generated on Appeals with an Attorney Claimant. Haven't seen an example of this yet though

2021-07-20 14:08 UTC, nanotone commented
I have two somewhat conflicting thoughts about this.

First, is that since the logic is the same in both classes, you could just have the BGE delegate `claimant_participant_id` to its `appeal` to DRY up the code.

But second, I worry that there might be other code that calls one of these methods, expecting the actual claimant's PID rather than the PID to be used during EP establishment. I guess you could just leave a comment in there, and let people call `claimant.participant_id` directly if they want.

Thoughts?

2021-07-20 16:59 UTC, wdrougas-tista commented
Yeah i'd imagine it's a very unique situation when someone would need the `AttorneyClaimant` PID right? But I think your second point is well put and it would be safer to just leave a comment informing folks that this change is to facilitate EP establishment. I'll go ahead and add comments

2021-07-20 19:09 UTC, nanotone requested changes
Small nitpicks, but this is pretty much there.

2021-07-20 19:09 UTC, nanotone commented on app/models/board_grant_effectuation.rb
> +    claimant.is_a?(AttorneyClaimant) ? veteran&.participant_id : claimant&.participant_id
In light of this comment, it seems like this logic is just a consequence of `DecisionReview#claimant_participant_id` since the reasoning is the same. (In a sense, BGEs are just the way Appeals get established in VBMS)

So what do you think about replacing this method with a

```delegate :claimant_participant_id, to: :appeal```

2021-07-20 19:09 UTC, nanotone commented on app/models/decision_review.rb
> +    # EPs with an AttorneyClaimant need to be established with the veteran's participant ID, per BVA
Since you got this guidance from Jane, would it be "per BVA" or should it be "per VBA" or maybe "per OAR"?

2021-07-20 19:12 UTC, wdrougas-tista commented on app/models/board_grant_effectuation.rb
> +    claimant.is_a?(AttorneyClaimant) ? veteran&.participant_id : claimant&.participant_id
👍

2021-07-20 19:12 UTC, wdrougas-tista commented on app/models/decision_review.rb
> +    # EPs with an AttorneyClaimant need to be established with the veteran's participant ID, per BVA
Jane is the one who informed me of this, but she mentioned it came from the Board, what do you think?

2021-07-20 19:23 UTC, nanotone commented on app/models/decision_review.rb
> +    # EPs with an AttorneyClaimant need to be established with the veteran's participant ID, per BVA
Oh, that's unexpected because I don't think the Board really cares about Participant IDs at all, but yeah feel free to leave it in that case.

2021-07-20 19:31 UTC, nanotone approved these changes
LGTM! Ready to merge once tests/checks are happy.

2021-07-20 20:20 UTC, merged