WIP: Enable users with access to correct issues on a substitute appeal
department-of-veterans-affairs/caseflow pull request #16509
Opened 2021-07-19 20:53 UTC by eileen-nava

Resolves [jira ticket 1764](https://vajira.max.gov/browse/CASEFLOW-1764), which states that BvaIntake and COB users should be able to edit substitute appeal's issues through the "correct issues" link.  Before this PR, a bug made that impossible.

### Description

During a slack call I had with Ann-Marie and Paula on Wednesday, July 7, Ann-Marie demonstrated that intake users select request issues' decision dates during the intake process.  She also stated that when request issues are copied over to a substitute appeal, the request issues should retain their original decision date.

Previously, request issues' decision dates were set to equal "nil" during the substitute appellant process. Previous code [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/appellant_substitution.rb#L77). I discussed this with Yoom on a call Monday, July 17, and he said he thinks that line 77 was a bug.  He did suggest reaching out to Foxtrot about this, as they have the most domain knowledge around request issues.  I asked in slack for Foxtrot to confirm my [understanding of request issue decision dates](https://dsva.slack.com/archives/C54QCEHAL/p1626726976108200).

Also, I want to share [a previous helpful slack conversation with Yang](https://dsva.slack.com/archives/CJL810329/p1625680764377900) about request issue decision dates.  He stated that if it is a non-rating request issue, there should always be a decision date.  There will sometimes be request issues in the wild that don't have decision dates, which is tech debt for Foxtrot.

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] All automated tests pass
- [ ] A COB and BvaIntake user can click "correct issues" on a substitute appeal and successfully edit request issues

### Testing Plan
1. Switch to being a Clerk of the Board user that also belongs to the BvaIntake group.
2. Create an appeal that has both request and decision issues.
3. Go through the appellant substitution flow and click on "Correct issues" on the substitute appeal's case details page.
4. Confirm that you can click on "Correct issues" without seeing any error messages.
5. Confirm that you can delete an issue.

2021-07-20 20:16 UTC, eileen-nava commented on app/controllers/claim_review_controller.rb
> +    "Caseflow::Error::MissingDecisionDate" => COPY::CLAIM_REVIEW_EDIT_ERROR_MISSING_DECISION_DATE,
On line 340 in `approx_decision_date_of_issue_being_contested` in the `request_issue.rb`, I switched from using `MissingDecisionDate` to `Caseflow::Error::MissingDecisionDate` because I think it's better to have errors standardized and in one place, aka `lib/caseflow/error.rb`.  

I think it's a bit odd to have errors trigger certain copy to be displayed, rather than displaying the message associated with the error.  However, I left `EDIT_ERRORS` mostly intact because this ticket does not focus on this aspect of the codebase, and I'm not super familiar with the decision to create `EDIT_ERRORS`.  That being said, I'd be interested to hear other developers' thoughts about.

2021-07-20 20:17 UTC, eileen-nava commented on app/models/appellant_substitution.rb
> -        request_issue_copy.decision_date = nil
☝️ The room where it happens.

2021-07-22 20:19 UTC, jcq requested changes
I'm worried that we should pull out the refactoring of the `MissingDecisionDate` as out-of-scope due to there being a lot of other similarly scoped errors that aren't being addressed

2021-07-22 21:14 UTC, eileen-nava commented on app/controllers/claim_review_controller.rb
> +    "Caseflow::Error::MissingDecisionDate" => COPY::CLAIM_REVIEW_EDIT_ERROR_MISSING_DECISION_DATE,
@jcq I hear you that we should either move all errors defined in `RequestIssue` to `lib/caseflow/error.rb`, or none.  I will undo the change I made and bring up centralizing errors at another time.  Maybe I could bring it up with the backend working group?

2021-07-22 21:54 UTC, eileen-nava commented
@jcq I responded to your feedback and reverted to having the error `MissingDecisionDate` defined in `request_issue.rb`.  What do we want the user to see if they click "correct issues" for an appeal where a request issue is missing a decision date?

I tried using the `render_error` method  that's defined in `appeals_controller.rb`.  Here's an image of the result, which I don't love.
<img width="1789" alt="Screen Shot 2021-07-22 at 5 45 43 PM" src="https://user-images.githubusercontent.com/80347702/126714204-5ba56a79-ee88-4dd1-866a-a40ea3a10f04.png">




Then I tried using the `handle_non_critical_error()` method that is defined in `application_controller.rb`.  Again, they see only the error, and can't interact with anything that should be on the page.
<img width="1789" alt="Screen Shot 2021-07-22 at 5 50 15 PM" src="https://user-images.githubusercontent.com/80347702/126714327-8bcf59a3-2d61-4fdc-8e99-e336ff8b1d04.png">


Thoughts?

2021-07-23 13:56 UTC, jcq requested changes
Great work on this so far — I think we can simplify the backend even more and not worry about error handling at that point. We already have a lot of error handling being done on the edit page, and I think we can just add a bit more there in order to get error messages to display nicely (see comment below).

2021-07-23 13:56 UTC, jcq commented on app/controllers/appeals_controller.rb
> +    end
I think the better way to handle this (and address the questions you had around error formatting) is to not actually fail here. If we let this go through, we'll end up in React in the `IntakeEditFrame` component. This in turn sets up various routes for either happy path or other sorts of errors/blocks. 

You can see [existing code](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/intake/pages/addIssues.jsx#L202-L205) in `addIssues.jsx` that checks various conditions and redirects if something is supposed to prevent editing.

You could add logic into `willRedirect` and `redirect` class methods, or (to avoid complicating already-large conditionals) you could just simply add a conditional within the `render` method (probably just above the linked line?) that returns a `<Redirect>` component that drops the user over onto a route that you can define in `IntakeEditFrame`. For that I'd look at the existing routes that simply show messages, and try to just mimic that.

2021-07-23 16:07 UTC, eileen-nava commented
Here is the error message that a user will see when they attempt to edit an appeal where one or more request issues has no decision date.

<img width="1789" alt="Screen Shot 2021-07-23 at 12 06 15 PM" src="https://user-images.githubusercontent.com/80347702/126810390-0fddf8d2-efab-414e-80fa-6451c27211c5.png">
I reached out to @araposo-tistatech and @rutvigupta-design  about this error message via slack.  Rutvi okayed the error message.  (Thanks again, Rutvi!)

2021-07-23 16:56 UTC, jcq approved these changes
I think the only remaining change is updating a test that is checking for an error that we're no longer throwing. 

Also see comment re the `nil` vs `fail` in the block that should never be reached. 😄 

Great work on this! Approving to unblock!

2021-07-23 16:56 UTC, jcq commented on app/models/request_issue.rb
> -      fail MissingDecisionDate, id
Is there any case where going back to failing with this error would be better than `nil`?

2021-07-23 16:56 UTC, jcq commented on client/app/intake/pages/addIssues.jsx
> +    }
This could/should be memoized so that it doesn't recompute on every render, but all the other conditionals in this component suffer from the same issue, so it's not worth spending additional time on this.

2021-07-23 16:56 UTC, jcq commented on client/app/intakeEdit/IntakeEditFrame.jsx
> +                  />
👍

2021-07-23 16:56 UTC, jcq commented on spec/models/request_issue_spec.rb
> +          expect(error).to be_a(RequestIssue::MissingDecisionDate)
This may not still be happening...?

2021-07-23 17:12 UTC, eileen-nava commented on app/models/request_issue.rb
> -      fail MissingDecisionDate, id
Yes, there is.  I found two earlier [connected](https://github.com/department-of-veterans-affairs/caseflow/pull/10351) [PRs](https://github.com/department-of-veterans-affairs/caseflow/issues/10070) that display an error if a request issue has no decision date, since "it's likely because they have a locked rating."  That makes me wonder why there was a  `# in theory we should never get here` comment in the request issue, but alrighty.

Seven tests broke in CircleCI because of this.  EEP!  I'm now trying to figure out how to tell if a request issue has a locked rating.  My plan is to add a conditional in this method that will `fail MissingDecisionDate, id` if the request issue has a locked rating.

2021-07-23 17:14 UTC, eileen-nava commented on app/models/request_issue.rb
> -      fail MissingDecisionDate, id
Yes, there is. I found two earlier [connected](https://github.com/department-of-veterans-affairs/caseflow/pull/10351) [PRs](https://github.com/department-of-veterans-affairs/caseflow/issues/10070) that display an error if a request issue has no decision date, since "it's likely because they have a locked rating." This makes me think that the comment `# in theory we should never get here` was inaccurate or out of date.

Seven tests broke in CircleCI because of this. EEP! I'm now trying to figure out how to tell if a request issue has a locked rating. My plan is to add a conditional in this method that will call `fail MissingDecisionDate, id` if the request issue has no decision date and has a locked rating.

2021-07-23 17:23 UTC, jcq submitted a review, later dismissed
Pending fixes for automated tests...

2021-07-28 17:40 UTC, barshirtcliff commented on app/models/request_issue.rb
> -      fail MissingDecisionDate, id
The logic around this is really gnarly.  I'm having a lot of trouble following `is_unidentified` in all its usages, and if it is true, we return nil.  It does make sense to me that if it's not unidentified (whatever that means), and there is a rating but no decision_date available, there should be an error, but I wonder if instead of breaking the workflow we could do something to let bat team know there's a crazypants data situation deserving a looksie.  Could this be added to the many error logs we monitor somehow without making a 500 error?

2021-07-29 16:16 UTC, eileen-nava commented on app/models/request_issue.rb
> -      fail MissingDecisionDate, id
Thanks for looking at this, Bar.  There is currently [an alert](https://dsva.slack.com/archives/C54QCEHAL/p1625652023488200) in the appeals-foxtrot channel that surfaces non-rating request issues that lack a decision date. Since there is an alert for this in the appeals-foxtrot channel, I don’t think we need add another error log - let me know if you think otherwise.

Also, the schema has [information about`is_unidentified`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/schema.rb#L1244) - I hope it's helpful.

2021-07-30 02:41 UTC, n1zyy approved these changes
One extremely minor suggestion to consider. Otherwise, LGTM!

FWIW: I feel like this is a model of what PR descriptions should be. Trying to connect the Jira ticket and the code was tricky, but having this explanation made it much clearer and easy to test. Thanks!

2021-07-30 13:50 UTC, merged