Added email template logic
department-of-veterans-affairs/caseflow pull request #16503
Opened 2021-07-19 13:37 UTC by sahalliburton

Resolves [CASEFLOW-1669](https://vajira.max.gov/browse/CASEFLOW-1669)

Part 2 of the stack

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb`
* [ ] Run `make docs` (after running `make migrate`) to update DB schema docs
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-07-20 15:52 UTC, charleyf reviewed
### I'm reviewing this in two parts:
1. Verify that the virtual hearings stayed the same. I'm done with this, adding a comment with findings shortly.
2. Verify that the new templates look as expected. Working on this now.

2021-07-20 16:16 UTC, charleyf commented
### Part 1: Verify That Virtual Hearing Emails Didn't Change
I reviewed this visually and with a diff. I believe that **virtual hearing emails did not change in any problematic way.**

**Things that did change and I think are okay:**
- Virtual representative reminder emails have a line changed to: "You have a client scheduled for a virtual hearing with a Veterans Law Judge of the Board of Veterans' Appeals." which is an AC so I believe is an acceptable change.
- The diff shows A few blank lines added/removed _in the html markup_ which doesn't have a visual effect I can see.
- Because we generate a new fake hearing for each rake, the uuid, pin, and conference ID are different when diffing. This is expected.

This next section is a detailed write up of how I got to those conclusions.


**Save html files for master and pr branch**
- Generate emails from master branch
```zsh
git checkout master
bundle exec rake emails:virtual_hearings:sample
```
- Generate 7 files into `caseflow/tmp` : `cancellation_*.html`, `confirmation_*.html`, `reminder_*.html`
```
zsh bundle exec rake emails:virtual_hearings:sample
```
- Move those 7 files into a directory called 'master_branch_emails'
- Checkout the PR branch `git checkout shalliburton/CASEFLOW-1669-email-logic # (the PR branch)`
- Generate the same 7 files `bundle exec rake emails:virtual_hearings:sample`
- Move those into a directory called 'pr_branch_emails'

**Verify via code:**
Use 'diff' (or GUI diff in VSCode) to compare each set of files in the 'master_branch_emails' and 'pr_branch_emails' directories.

**Verify visually:**
Open both versions of each email in chrome tabs, toggle back and forth between the tabs.

2021-07-20 17:58 UTC, charleyf requested changes
### Part 2: New Templates Review
I found a few places where the email generated didn't match the AC. Suggested code changes to fix.

Once those are fixed I'd like to go through all of this again after giving my eyes a break. Lots of details to look at.

I tested by saving the emails to html (thanks for the commands Stephen!) and reviewing the HTML markup.
```zsh
bundle exec rake "emails:hearings:reminder[video]"
# Then create tmp/video_emails directory, and move
# tmp/reminder_Appellant.html and tmp/reminder_Representative.html into it
bundle exec rake "emails:hearings:reminder[central]"
# Then create tmp/central_emails directory, and move
# tmp/reminder_Appellant.html and tmp/reminder_Representative.html into it
bundle exec rake "emails:hearings:reminder[virtual]"
# Then create tmp/virtual_emails directory, and move
# tmp/reminder_Appellant.html and tmp/reminder_Representative.html into it
```

2021-07-20 17:58 UTC, charleyf commented on app/helpers/hearings/calendar_template_helper.rb
>      end
Since these now take 'hearing's rather than 'virtual_hearing's we should probably drop the 'virtual' in the name:
- `central_office_display_time_for_virtual_hearing` -> `central_office_display_time_for_hearing`

2021-07-20 17:58 UTC, charleyf commented on lib/tasks/emails.rake
>    namespace :virtual_hearings do
Since this is not only for virtual any more
```suggestion
  namespace :hearings do
```

2021-07-20 17:58 UTC, charleyf commented on app/views/hearing_mailer/_appellant_reminder.html.erb
> +  <% end %>
The text for Central/Video is different at the end, "meet with you in person." vs "meet with you via video conference."
```suggestion
  <% if @virtual_hearing.present? %>
    You're scheduled for a virtual hearing with a Veterans Law Judge of the Board of Veterans' Appeals.
  <% elsif @hearing&.request_type == "V" %>
    You're scheduled for a hearing with a Veterans Law Judge of the Board of Veterans' Appeals. You will arrive at
    <%= @hearing&.hearing_location_or_regional_office&.full_address %> and the Judge will meet with you via video conference.
  <% elsif @hearing&.request_type == "C" %>
       You're scheduled for a hearing with a Veterans Law Judge of the Board of Veterans' Appeals. You will arrive at
    <%= @hearing&.hearing_location_or_regional_office&.full_address %> and the Judge will meet with you in person.
  <% end %>>
```

2021-07-20 17:58 UTC, charleyf commented on app/views/hearing_mailer/_appellant_reminder.html.erb
> +    <% if @virtual_hearing.nil? %>
I'm not sure what this if is doing?

I see an outer if/else that tests `if @virtual_hearing.present?`, is there a situation where `@virtual_hearing` is not `present` and also not `nil`?

2021-07-20 17:58 UTC, charleyf commented on app/views/hearing_mailer/_representative_reminder.html.erb
> +    <% end %>
As written, the virtual hearing text never appears because virtual hearings have a request type of "C" or "V". Fix by testing `virtual_hearing.present?` first.
```suggestion
    <% if @virtual_hearing.present? %>
      You have a client scheduled for a virtual hearing with a Veterans Law Judge of the Board of Veterans' Appeals.
    <% elsif @hearing&.request_type ==  "C" %>
      You have a client scheduled for a hearing at the VA Central Office with a Veterans Law Judge of the Board of Veterans' Appeals.
    <% elsif @hearing&.request_type == "V" %>
      You have a client scheduled for a hearing at a VA Regional Office with a Veterans Law Judge of the Board of Veterans' Appeals.
    <% end %
```

2021-07-20 19:36 UTC, sahalliburton commented on app/views/hearing_mailer/_appellant_reminder.html.erb
> +  <% end %>
this was implemented in the other branch so I pulled it into this one

2021-07-20 19:36 UTC, sahalliburton commented on app/views/hearing_mailer/_representative_reminder.html.erb
> +    <% end %>
this was implemented in the other branch so I pulled it into this one

2021-07-20 19:36 UTC, sahalliburton commented on app/views/hearing_mailer/_appellant_reminder.html.erb
> +    <% if @virtual_hearing.nil? %>
this was implemented in the other branch so I pulled it into this one

2021-07-21 14:23 UTC, charleyf commented
✅  Approved, I think this is ready with a few notes:
- There's a lot of permutations and details in this work. I'm assuming/hoping that Tango/I will get another chance to comb through these (using real data?) next sprint before we send them to users.
- ACs link to a document with <Full Appellant Name> in representative emails. That will be done later in [this work](https://vajira.max.gov/browse/CASEFLOW-385).
- The location name "Central" on the appellant email for Central could be clearer and less ominous. This is definitely later work.

What I did to Re-Verify:
- Repeated the rake steps above to generate all the emails and move them into new directories.
- Opened each email in chrome
    - Compared it to the pdf in the Jira ticket.
    - Compared it to the ACs in the Jira ticket.
    - Read it carefully line by line.
- Added a `binding.pry` in the rake task and verified that `email.subject` is what we'd expect. We didn't change it in this work, so this was probably unnessecary.

2021-07-21 14:24 UTC, charleyf approved these changes

2021-07-21 15:08 UTC, merged