[WIP] CASEFLOW-1499
department-of-veterans-affairs/caseflow pull request #16531
Opened 2021-07-22 15:42 UTC by n1zyy

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb`
* [ ] Run `make docs` (after running `make migrate`) to update DB schema docs
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-07-23 00:57 UTC, n1zyy commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  'AssignHearingDispositionTask',
This was referred to as "Select Hearing Disposition" in the Jira ticket. Want to confirm my mapping here is correct.

2021-07-23 00:57 UTC, n1zyy commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  'ScheduleHearingTask',
Similarly, this was called "Schedule Veteran Task" in Jira, and want to make sure this is also the correct thing to use here.

2021-07-23 00:57 UTC, n1zyy commented on client/app/queue/substituteAppellant/tasks/utils.js
> +};
This is duplicative of what's in [Paula's PR](https://github.com/department-of-veterans-affairs/caseflow/pull/16524/files) (it is, in fact, stolen from her PR), but I've moved code around above and below so there's a decent chance of a merge conflict. I am happy to help resolve it if I'm not the one that gets stuck with it.

2021-07-23 00:57 UTC, n1zyy commented on client/app/queue/substituteAppellant/tasks/utils.js
> +  // disable the same things. But this code can be improved.
@jcq and I talked a fair bit about this.

This isn't code I'm particularly proud of. For every task in the list, we call this method, which looks through the array of task types potentially up to 3 times, and if it enters one of them, it will run through the array of related types.

*But*, it executes nearly instantaneously. It's unlikely that there will ever be more than perhaps 10 items to run through, so we're talking about a couple hundred iterations of a loop looking at stuff in memory, worst case. If we try to write this in the "efficient" way our brains want to, it gets really unreadable.

Separately: I initially erred in making this an `if ... else` construct. Multiple boxes can be checked, and we need to compute the total set to be excluded. But, by happenstance, this configuration works fine. EvidenceSubmissionWindowTask and TranscriptionTask disable the exact same fields, so the fact that we miss an iteration of "and then do the exact same thing again" doesn't matter. Selecting either of them will disable ScheduleHearingTask, so that can't be selected along with them. And if you instead select ScheduleHearingTask, it disables both of the other two ones.

So, tl;dr, this code is mildly embarrassing, but it also works fine. If someone has a thoughtful refactor I'm all ears, but for now I'd rather skew towards wasting some microseconds of CPU time versus inscrutable code.

2021-07-23 00:57 UTC, n1zyy commented on client/app/queue/substituteAppellant/tasks/utils.js
> +      disabled: shouldDisable(task) || shouldDisableBasedOnTaskType(task.type, selectedTaskTypes)
This initially read:

```ruby
disabled: task.disabled || shouldDisableBasedOnTaskType(task.type, selectedTaskTypes)
```

This turned out to be really problematic. Once a box was disabled, it would never be un-disabled. Calling `shouldDisable` gets us the expected behavior. (If some day there's a third way to disable boxes on the form, this will be a much bigger headache.)

2021-07-23 00:57 UTC, n1zyy commented on client/app/queue/substituteAppellant/tasks/utils.js
> +    disabled: shouldDisable(taskInfo),
This second param was never actually being used.

2021-07-23 00:57 UTC, n1zyy commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +  describe('disabledTasksBasedOnSelections', () => {
A handful of different thoughts here.

As my comment on the test for `disabledTasksBasedOnSelections` at the top of this section says, these two tests are _highly_ duplicative. Technically, one tests the boolean returned, and the other tests that the task was actually disabled. Is there any value in keeping both of them, or should we remove the first one, since any problems would also surface here?

Second, in both tests, the three `describe` conditions share very similar code. If this were Ruby where I'm much more comfortable refactoring, I'd have written a little method like `expectDisabled(array_of_task_types)` and `expectNotDisabled(array_of_task_types)`. While there is perhaps some value to very explicitly spelling out what we expect, it looks like a lot of copypasta to me. (Also: can confirm, the second and third describe blocks _are_ copypasta.)

2021-07-23 00:57 UTC, n1zyy commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +    describe('when ScheduleVeteranTask is selected', () => {
```suggestion
    describe('when ScheduleHearingTask is selected', () => {
```

D'oh! Will fix in the AM.

2021-07-23 00:57 UTC, n1zyy commented on spec/factories/appeal.rb
> +    end
This trait does not work and should be removed.

The other two are helpful and used in the testing instructions here. It's debatable just how much non-appeal stuff we want to cram into the Appeal factory. The way we talk about appeals, "Give me an appeal with an ESW task and a deceased veteran so we can test substitutions" makes a lot of sense, but I worry about this becoming a kitchen sink of weird things.

2021-07-23 00:57 UTC, n1zyy commented on spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
> +      context "with hearing docket" do
Unrelated fix: this came up while pairing.

2021-07-23 01:16 UTC, n1zyy commented
This patch is currently adding a useless `disabled=""` attribute in an existing snapshot. Need to look into why in the morning.

2021-07-28 01:35 UTC, n1zyy commented on client/app/queue/substituteAppellant/tasks/utils.js
> +};
This method is merely moved up from the old lines 82-85 because it's used below.

2021-07-28 01:35 UTC, n1zyy commented on client/app/queue/substituteAppellant/tasks/utils.js
> -
Just moved up to new lines 90-92.

2021-07-28 01:35 UTC, n1zyy commented on client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantTasksForm.test.js.snap
> +                      disabled=""
I actually don't understand why this is happening, but I updated the snapshot since it _is_. 🤷

2021-07-28 01:35 UTC, n1zyy commented on client/test/data/queue/substituteAppellant/tasks.js
> +};
I implemented this to just tack onto `sampleTasksForEvidenceSubmissionDocket()` because I'm returning an unrealistic set of tasks here to demo the form behavior in the storybook, but the existing method was used in multiple places.

I appear to have written this small bit of JS code correctly on my first attempt???

2021-07-28 01:35 UTC, n1zyy commented on spec/factories/appeal.rb
> +
I'm having second thoughts about adding these.

They're handy because I wanted to use them for demo, and my instructions for manual review mention these. But they're not actually used in any code or tests. If it weren't _my_ code, I'd probably argue that adding code because we might want to use it some time later is probably a bad idea. Think I should remove these?

2021-07-28 16:23 UTC, jcq requested changes
Fully tested in Storybook, and LGTM

See note re the oddity of adding hearing-related tasks to a list of tasks from `evidence_submission` docket; maybe it might be good to not include the evidence submission ones (though you still need things like `DistributionTask`) just for clarity sake?

2021-07-29 20:23 UTC, barshirtcliff approved these changes
lgtm!

2021-07-29 20:23 UTC, barshirtcliff commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +    describe('when an EvidenceSubmissionWindow task is selected', () => {
while I appreciate thoroughness, this... is a lot.  the mechanics of the method you wrote work the same for all three types, so I think just one of these describe sections is adequate.  beyond that we're copying over the working code, verbosely.

2021-07-29 20:23 UTC, barshirtcliff commented on client/test/app/queue/substituteAppellant/tasks/utils.test.js
> +  describe('disabledTasksBasedOnSelections', () => {
oh look, we had the same thought!  Yes remove bloat-test pls.

2021-07-29 20:23 UTC, barshirtcliff commented on client/test/data/queue/substituteAppellant/tasks.js
> +};
it's test data, and the comment clarifies that it's unrealistic.  I think it's good.

2021-07-29 20:23 UTC, barshirtcliff commented on spec/factories/appeal.rb
> +    end
yus

2021-07-29 20:23 UTC, barshirtcliff commented on spec/factories/appeal.rb
> +
keep 'em, I'll use them.

2021-07-29 20:26 UTC, n1zyy commented on client/test/data/queue/substituteAppellant/tasks.js
> +};
Oh, for historical context: I changed this method based on JC's comment; JC was right for the previous code, and now Bar is right in response to the updated code. :)

2021-07-30 20:36 UTC, n1zyy commented
Just demoed to Ann-Marie and JC. The issue Bar spotted on Friday turned out to have been surprisingly hard to fix, but we've banged on it a bunch and it works. Yay!

2021-07-30 20:40 UTC, merged