Implement add half day dockets and scheduling
department-of-veterans-affairs/caseflow pull request #16560
Opened 2021-07-28 20:36 UTC by rubaiyat22

Resolves https://vajira.max.gov/browse/CASEFLOW-1597
WIP
### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb`
* [ ] Run `make docs` (after running `make migrate`) to update DB schema docs
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-07-30 19:53 UTC, rubaiyat22 commented on spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
> -      context "with schedule direct to video/virtual feature disabled" do
I removed these tests because the feature toggle is already enabled and i did not think it was necessary to add more test for it.

2021-08-02 17:46 UTC, odonnadieu commented on client/app/hearings/components/DocketStartTimes.jsx
> +    let halfDayAmLabel = `Half-Day AM (5 slots at ${amTime} AM ${zoneName} / ${amTimeInEastern} Eastern)`;
Is there a way to know the number of slots that would constitute a half day?

2021-08-04 14:49 UTC, charleyf commented
I'm working through this and found a structural change I'd recommend. Basically, I think that the `<ReadOnly>` component and its logic that are in `HearingTime` right now should be a new component.

In this PR currently:
- `HearingTime` renders a `ReadOnly` component if it gets passed a non-null `hearingStartTime`
- `ScheduleVeteranForm` passes `hearingStartTime` to `HearingTime`. This is the only place that `hearingStartTime` can get passed to `HearingTime`.

I'd suggest:
- The code that was added to `HearingTime` could be it's own component (`ReadOnlyTimeWithZone`?).
- `ScheduleVeteranForm` could decide (near line 182) to either render `HearingTime` or that new component based on the presence of `hearingStartTime`

2021-08-04 18:23 UTC, charleyf requested changes
I'm seeing a problem with `hearing.scheduledTimeString` being `null` unexpectedly and blocking form submission without a visible error.
- I suspect that splitting the HearingTime component will help solve this.
- The error is coming from `ScheduleVeteran:249`.
 
Steps to reproduce:
- Create a half day docket using the directions in the testing plan.
- Go to the [schedule page](http://localhost:3000/hearings/schedule/assign?tab=amaAssignHearingsTab&regional_office_key=RO43&page=1) for an RO.
- Find a veteran to schedule (I'm using AMA veterans in Oakland).
- Get to the [scheduling form](http://localhost:3000/queue/appeals/d8639b63-a6b2-41ce-8e83-0c42fc748ea7/tasks/2143/schedule_veteran)
- Select type "Video"
- Select the RO with your half day. Don't select that half day yet.
- Select a full (normal) video day.
- Select the half day you created.
- Click 'Schedule', you'll get an error about hearing location (even if you filled it in). I think this is existing behavior though.
- Fill in the hearing location, then click "Schedule" again. This time nothing will happen and  no error will appear.
- You can see what's going on by switching the hearing day back to a "normal" video day and noting the "Please select a hearing time" error message.

2021-08-04 21:29 UTC, rubaiyat22 commented on client/app/hearings/components/DocketStartTimes.jsx
> +    }
I made that refactor in this commit https://github.com/department-of-veterans-affairs/caseflow/pull/16560/commits/07ca80769ad34a89606ff8aa828d4f6e94727602

2021-08-04 21:30 UTC, rubaiyat22 commented on client/app/hearings/components/modalForms/HearingTime.jsx
>  import { css } from 'glamor';
Made changes in this commit https://github.com/department-of-veterans-affairs/caseflow/pull/16560/commits/891c5d4f1ef7daee1c9be4edd53c06f4e3258621 which also resolves 
>I'm seeing a problem with hearing.scheduledTimeString being null unexpectedly and blocking form submission without a visible error.

2021-08-05 13:45 UTC, charleyf commented on client/app/hearings/components/modalForms/HearingTime.jsx
>  import { css } from 'glamor';
Just confirmed that this is now resolved.

2021-08-05 13:57 UTC, charleyf commented on client/app/hearings/components/DocketStartTimes.jsx
> +    }
Looks good ✅

2021-08-05 14:30 UTC, charleyf requested changes
Happy to work through this with you.

Found a timezone issue: DocketStartTimes is always sending `begins_at` as "08:30" or "12:30" (eastern) which when an RO in a west-coast timezone (Oakland) is selected `begins_at` should be sent as "11:30" or "15:30" (eastern). Details below should clarify this.

This is a PM docket, when you add a hearing_day it says: "5 slots at 12:30pm Pacific / 3:30pm Eastern"
```ruby
# In the UI for scheduling a hearing, when that video half day is selected
"12:30 PM Pacific / 3:30 PM Eastern"
hearing_day.first_slot_time # correct according to testing notes
=> "12:30"
hearing_day.begins_at # # This says 12:30pm eastern, which I think is incorrect
=> "2021-09-06T12:30:00-04:00"
```

This is a AM docket, when you add a hearing_day it says:  "5 slots at 8:30am Pacific / 11:30pm Eastern"
```ruby
# In the UI for scheduling a hearing, when that video half day is selected
8:30 AM Pacific / 11:30 AM Eastern
hearing_day.first_slot_time # correct according to testing notes
=> "08:30"
hearing_day.begins_at # This says 8:30am eastern, which I think is incorrect
=> "2021-09-10T08:30:00-04:00"
```

This is happening because:
- models/hearing_day:179 assumes that the time string is in eastern zone
- DocketStartTimes:61-68 we are always sending "08:30" or "12:30" for half days, which are implicitly in eastern zone.
- There may also need to be a change in ReadOnlyHearingTimeWithZone:24-26 to keep that displaying correctly.

2021-08-05 18:17 UTC, charleyf approved these changes

2021-08-05 18:23 UTC, charleyf commented
✅  This looks good to me!

If you are able to hold off on 'ready-to-merge' until standup tomorrow I'm hoping I'll have time to do one more full pass of testing/poking. Wouldn't expect to find anything big, but one more pass with fresh eyes seems worthwhile to me.

2021-08-06 17:15 UTC, merged