WIP: 2075/limit jdr atty tasks
department-of-veterans-affairs/caseflow pull request #16586
Opened 2021-08-03 21:16 UTC by eileen-nava

**This is a draft PR.  It is ready for feedback but not for a full review from other engineers.**

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb`
* [ ] Run `make docs` (after running `make migrate`) to update DB schema docs
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-08-03 21:19 UTC, eileen-nava commented on app/models/task.rb
> +    self.skip_check_for_only_open_task_of_type = true
It's necessary to use `self` here, because if I just write `skip_check_for_only_open_task_of_type = true`, the `only_open_task_of_type` validation will still get called on line 576 in the `tap` block.

2021-08-03 21:33 UTC, eileen-nava commented on app/models/task.rb
> -      # does not leak outside of this method
Since we are no longer using thread-local variables here, we don't have to worry about any thread-local variables leaking outside of this method.  As a result, I removed the ensure block.

2021-08-03 21:37 UTC, eileen-nava commented on app/models/tasks/judge_decision_review_task.rb
> +  validate :only_open_task_of_type, on: :create,
I decided to use `on: :create` instead of `before_create` in the spirit of consistency.  If anyone reviewing this has a strong preference for `before_create`, I'd be open to hearing your thoughts.

2021-08-03 21:37 UTC, eileen-nava commented on app/models/tasks/judge_decision_review_task.rb
> -  def verify_user_task_unique
Now that the task uses `: only_open_task_of_type`, this method is no longer needed.

2021-08-04 16:24 UTC, yoomlam commented on app/models/task.rb
> +    self.skip_check_for_only_open_task_of_type = true
I think the alternative is to use `@skip_check_for_only_open_task_of_type`.

2021-08-04 16:24 UTC, yoomlam commented on app/models/task.rb
> -      # does not leak outside of this method
Do you think you need to reset `skip_check_for_only_open_task_of_type`?

2021-08-09 23:01 UTC, eileen-nava commented
Via slack, Yoom had encouraged me to answer the below question on my own:

> When you verbally explained this bug to me and showed its timeline in logs, you noted that one JudgeAssignTask changed status from cancelled to completed, which is an invalid flow. Do you want me to write code to ensure that this change in status is impossible? Or are the expanded validations sufficient to prevent the bug from recurring?

My understanding is that when a judge completes a `JudgeAssignTask`, this creates an `AttorneyTask`.  If a judge reassigns a `JudgeAssignTask` in one tab and then completes the now-cancelled `JudgeAssignTask` in a second tab, the action in the second tab will attempt to create a second `AttorneyTask`.  Due to the new validation on `AttorneyTask`, that action will now fail, and the `JudgeAssignTask` won’t change status from `cancelled` to `completed`.

2021-08-09 23:16 UTC, eileen-nava commented on app/models/task.rb
> -      # does not leak outside of this method
I went back and forth on resetting `@skip_check_for_only_open_task_of_type`.  Since the validation only gets called on create, I didn’t think leaving `@skip_check_for_only_open_task_of_type` as true would cause the validation to be incorrectly skipped in situations where it should be called.  I would think differently if it were a validation that should be called on update.  However, it also feels strange to *not* reset the variable `@skip_check_for_only_open_task_of_type` if it isn’t being used, so I decided to reset it.

2021-08-09 23:23 UTC, eileen-nava commented
@yoomlam PR ready for review.  TY!

2021-08-09 23:26 UTC, eileen-nava commented on app/models/tasks/docket_switch/docket_switch_abstract_attorney_task.rb
> +  def only_open_task_of_type
This felt odd even as I typed it, but it was necessary to maintain the docket switch flow.  Maybe we should check with the board that we want to allow multiple `DocketSwitchDeniedTask` and `DocketSwitchGrantedTask` instances for one appeal?

2021-08-10 16:21 UTC, yoomlam commented on spec/feature/queue/judge_assignment_spec.rb
> +          "and this action cannot be completed.")
Let's change this error message to:
```suggestion
        expect(page).to have_content("This appeal already has an open JudgeDecisionReviewTask "\
          "and this action cannot be completed.")
```

2021-08-10 16:26 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +    before do
```suggestion
    let!(:attorney_case_review2) do
```

2021-08-10 16:27 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +      expect(subject).to_not eq attorney_case_review1
Given the change above, revert this back to actually check the return value as stated in the `it` description.

2021-08-10 16:28 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +      appeal.reload
Why is this needed?

2021-08-10 16:30 UTC, yoomlam commented on spec/feature/queue/task_queue_spec.rb
> -
I'm curious as to the purpose of this task if it doesn't affect the test.

2021-08-10 16:33 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +        task.update!(status: Constants.TASK_STATUSES.completed)
```suggestion
        task.completed!
```

2021-08-10 16:35 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +        appeal.tasks.open.of_type("AttorneyTask").last.update!(status: Constants.TASK_STATUSES.cancelled)
```suggestion
        task2.cancelled!
```

2021-08-10 16:40 UTC, yoomlam commented on spec/models/tasks/judge_task_spec.rb
> +        it "should not violate the only_open_task_of_type validation" do
```suggestion
        it "does not violate the only_open_task_of_type validation" do
```

2021-08-10 16:40 UTC, yoomlam commented on spec/models/tasks/judge_task_spec.rb
> +      context "when a judge decision review task is reassigned successfully" do
```suggestion
      context "when the judge decision review task is reassigned" do
```

2021-08-10 16:41 UTC, yoomlam commented on spec/models/tasks/judge_task_spec.rb
> +      context "when a judge assign task is reassigned successfully" do
```suggestion
      context "when the task is reassigned" do
```

2021-08-10 16:41 UTC, yoomlam commented on spec/models/tasks/judge_task_spec.rb
> +      context "when a judge assign task is reassigned successfully" do
```suggestion
      context "when the task is reassigned" do
```

2021-08-10 16:43 UTC, yoomlam requested changes
Minor suggestions.
Very nice work! A side-effect is that now, our tests are more realistic (only 1 open task of certain type at a time).

2021-08-10 16:54 UTC, yoomlam commented
Related feature test: PR #16582

2021-08-10 19:25 UTC, eileen-nava commented on app/models/tasks/docket_switch/docket_switch_abstract_attorney_task.rb
> +  def only_open_task_of_type
Ann-Marie directed me to Foxtrot.  Slack response from Yang:

> I believe there should only ever be two open DocketSwitchAbstractAttorneyTasks on an appeal, parent assigned to COTB and child assigned to a user.

Yang also noted that @jcq created this task tree structure.  I'll check with JC about this when he is back from PTO.

For now, overriding the validation seems fine.

2021-08-10 19:28 UTC, eileen-nava commented on spec/feature/queue/judge_assignment_spec.rb
> +          "and this action cannot be completed.")
The current error message was suggested by design in a slack conversation with @mbaenatan and @rutvigupta-design.  I'd appreciate their thoughts on any changes.

2021-08-10 19:40 UTC, eileen-nava commented on spec/models/appeal_spec.rb
> +      appeal.reload
In retrospect, it's not.  I think I thought it was needed to make the task status changes go into effect and not set off the validation, but that doesn't make sense.  Past Eileen was wrong!  Present Eileen will delete `appeal.reload`.

2021-08-10 20:02 UTC, eileen-nava commented on spec/feature/queue/task_queue_spec.rb
> -
I read through the [relevant PR ](https://github.com/department-of-veterans-affairs/caseflow/pull/9673)and it seems this task was added to ensure that `placed_on_hold_at` would work.
> "quick". added an extra test in there to make sure `placed_on_hold_at` works as well.

2021-08-11 16:45 UTC, yoomlam approved these changes
🥇

2021-08-16 21:30 UTC, merged