Saved poa/appellant emails to database
department-of-veterans-affairs/caseflow pull request #16618
Opened 2021-08-12 18:31 UTC by sahalliburton

Resolves [CASEFLOW-2025](https://vajira.max.gov/browse/CASEFLOW-2025)

**PR Stack**

[Part 1](https://github.com/department-of-veterans-affairs/caseflow/pull/16616)
Part 2
[Part 3]()

### Description

Modifies the Schedule Veteran form to include the representative and appellant email fields for all hearing request types.

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] When entered for Video and Central hearings, email addresses are saved to the database

Hearing Type | Help text
-- | --
Virtual | When you schedule the hearing, the Veteran, POA, and Judge will receive an email with connection information for the virtual hearing.
Video, Central | The Veteran and POA will receive email reminders 7 and 3 days before the hearing.Caseflow won’t send notifications immediately after scheduling.
  - [ ] If the appeal does not have a POA, leave ", POA, " or " and POA" out of the help text

### Testing Plan

**Before All**
1.  Open a rails console and enable the feature flag `FeatureToggle.enable!(:collect_video_and_central_emails)`

**Video**
1. Shadow user `BVASYELLOW`: http://localhost:3000/test/users
2. Navigate to the hearing schedule: http://localhost:3000/hearings/schedule
3. Click the “Schedule Veteran” button at the top left
4. Select the St. Petersburg, FL RO from the dropdown
5. Click the “AMA Veterans Waiting” tab and click the name of one of the Veterans
6. On the Case Details page, click the “Schedule Veteran” option from the task list
7. Fill in the hearing location, date and time and then click the "Schedule" button
8. Open a console and locate the hearing that was created: `hearing=Appeal.find_by(uuid: "").hearings.last`
9. Ensure there were no email recipients created: `hearing.email_recipients.count`
10. Repeat steps 4-7, but this time input an appellant email before clicking schedule
11. Repeat steps 8-9 and ensure that this time there is an appellant email created
10. Repeat steps 4-7, but this time input an representative email before clicking schedule
11. Repeat steps 8-9 and ensure that this time there is an representative email created
10. Repeat steps 4-7, but this time input both a representative email and an appellant email before clicking schedule
11. Repeat steps 8-9 and ensure that this time there are both a representative email and an appellant email created

*Virtual**
1. Shadow user `BVASYELLOW`: http://localhost:3000/test/users
2. Navigate to the hearing schedule: http://localhost:3000/hearings/schedule
3. Click the “Schedule Veteran” button at the top left
4. Select the St. Petersburg, FL RO from the dropdown
5. Click the “AMA Veterans Waiting” tab and click the name of one of the Veterans
6. On the Case Details page, click the “Schedule Veteran” option from the task list
7. Change the request type to "Virtual"
7. Fill in the hearing location, date and time as well as the appellant email and timezone and then click the "Schedule" button
8. Reload the page and then scroll down to the hearing link that was just created and navigate to the details page
9. Ensure that the emails show up in the sent email events table
10. Repeat steps 4-8 but this time leave the appellant email blank and ensure that you receive an error message

2021-08-17 05:32 UTC, tomas-nava requested changes
I left a few suggestions & questions;

also, if I do the following:
- schedule a video hearing with appellant & representative tzs & emails
- go to the hearing's details page
- convert to virtual

... on the "Convert to Virtual Hearing" page, the appellant/rep timezones & emails do not match the email recipients I just created.

2021-08-17 05:32 UTC, tomas-nava commented on client/app/hearings/components/ScheduleVeteran.jsx
> +    requestType: assignHearingForm?.requestType || appeal?.readableHearingRequestType,
how & why will this requestType differ from the one defined on line 83?

2021-08-17 05:32 UTC, tomas-nava commented on client/app/hearings/components/ScheduleVeteran.jsx
> +    regionalOffice: assignHearingForm?.regionalOffice?.key || initialRegionalOffice,
Does this fix a bug? Were we leaving regionalOffice undefined in some cases?

2021-08-17 19:47 UTC, tomas-nava commented on client/app/hearings/components/ScheduleVeteranForm.jsx
> +    return appeal?.readableHearingRequestType ?? VIDEO_HEARING_LABEL;
This method is used to populate the hearing type dropdown and in certain cases (specifically a hearing converted to Central, then being converted to Virtual) was not populating with the correct values.

2021-08-17 19:47 UTC, tomas-nava commented on client/app/hearings/components/VirtualHearings/RepresentativeSection.jsx
> +            optional={!virtualHearing?.representativeEmail}
This is just used to toggle the rep timezone field as optional/required based on whether the rep email field has any text in it.

2021-08-18 00:05 UTC, tomas-nava approved these changes

2021-08-18 20:11 UTC, tomas-nava approved these changes

2021-08-18 20:11 UTC, tomas-nava commented on app/models/tasks/assign_hearing_disposition_task.rb
> +    email_recipients: nil
I suggest you name this param consistent with `virtual_hearing_attributes` above
```ruby
    email_recipients_attributes: nil
```

2021-08-19 15:30 UTC, rubaiyat22 approved these changes

2021-08-19 15:57 UTC, merged