Skip Creation of VeteranRecordRequest Task on Pre-Docket Appeals
department-of-veterans-affairs/caseflow pull request #16650
Opened 2021-08-18 15:35 UTC by Jeremy1026

Resolves [CASEFLOW-2179](https://vajira.max.gov/browse/CASEFLOW-2179)

### Description
Adds a check for VHA Issues before creating the VeteranRecordRequest task. Adds a test to ensure new functionality works as expected.

### Acceptance Criteria
- [ ] Code compiles correctly

2021-08-19 16:58 UTC, bgantick reviewed
Missing feature toggle? From the AC: "This will only happen when the pre-docket feature toggle is enabled"

2021-08-19 20:46 UTC, leikkisa requested changes
I agree with Brian's feedback re: adding the feature toggle, and added another note as well to not skip creating these tasks for other business lines

2021-08-19 20:46 UTC, leikkisa commented on app/models/appeal.rb
> +      next if vha_has_issues?
This will also inadvertently skip the VeteranRecordRequest creation for non-VHA business lines if the appeal has both VHA and non-VHA issues that would get a VeteranRecordRequestTask, so I think it makes more sense to update `requires_record_request_task?` in the RequestIssue model

2021-08-19 20:46 UTC, leikkisa commented on spec/models/appeal_spec.rb
> +    end
Once the update to still create these for non-VHA, a couple of good updates to the test would be to add an issue for something else (education, insurance, etc.), and then check that a VeteranRecordRequest assigned to VHA doesn't exist, but that one does exist for the businesss line on the other request issue

2021-08-25 13:19 UTC, Jeremy1026 commented on spec/models/appeal_spec.rb
> +    end
Added test for VHA and Non-VHA issues to ensure VeteranRecordRequest task gets created for non-VHA issue.

2021-08-25 13:20 UTC, Jeremy1026 commented on app/models/appeal.rb
> +      next if vha_has_issues?
Moved check to RequestIssue

2021-08-30 17:15 UTC, merged