update 10182 unrecognized appellant copy for HLRs and SCs
department-of-veterans-affairs/caseflow pull request #16675
Opened 2021-08-24 15:26 UTC by karinamzalez

Resolves [CASEFLOW-1285](https://vajira.max.gov/browse/CASEFLOW-1285)

- when intaking HLRs and SCs, user shouldn't be able to add an unlisted claimant. Removed the misleading copy when user is selecting an unrecognized appellant.

2021-08-24 15:53 UTC, nweinmeister commented on client/app/intake/components/SelectClaimant.jsx
> +  const allowNonVeteranClaimant = !['higher_level_review', 'supplemental_claim'].includes(formType);
Can you use these constants: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/intake/constants.js#L13 for the form types?

2021-08-24 15:56 UTC, nweinmeister commented on client/app/intake/components/SelectClaimant.jsx
> +  const allowNonVeteranClaimant = !['higher_level_review', 'supplemental_claim'].includes(formType);
Also I wonder if it might make more sense to say `[APPEAL.key].includes(formType)` to clarify the logic a little and make it more obvious for if/when we allow non veteran claimants to these other forms? Just a thought

2021-08-24 17:57 UTC, nanotone requested changes
This looks good! Could you add a feature test for this, or potentially reïnstate the test that you had commented out [here](https://github.com/department-of-veterans-affairs/caseflow/pull/16400/files#diff-6c2339f5198315076003b9d3cc14e5b908daac7ffd89450c38ba318c0383daaeR136) in the earlier PR?

2021-08-30 16:59 UTC, nanotone approved these changes
Looks great now! :shipit:

2023-03-28 12:32 UTC, closed without merging