Remove Unrecognized Appellant Appeals from StuckAppealsChecker Alert
department-of-veterans-affairs/caseflow pull request #16759
Opened 2021-09-16 19:53 UTC by eileen-nava

### Description
During the PI, I focused on reducing the number of appeals that show up in the StuckAppealsCheckerAlert.  Four appeals that currently show up in the alert have unrecognized appellants.  It was intentional to not have a dispatch task for these appeals, because we didn't want the board to send out a letter.  However, at some point in the future a bva dispatch task will need to be completed.  To 

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`)
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb`
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-09-17 14:37 UTC, yoomlam commented on spec/fixes/remove_unrecognized_appellant_cases_from_alert_spec.rb
> +        appeals with unrecognized appellants.")
```suggestion
                                instructions: "This task is on hold while Caseflow engineering devises a solution for " +
                                              "appeals with unrecognized appellants.")
```

2021-09-17 14:37 UTC, yoomlam commented on spec/fixes/remove_unrecognized_appellant_cases_from_alert_spec.rb
> +        expect(updated_query_result.count).to eq(0)
Nice!

2021-09-17 14:44 UTC, yoomlam commented on spec/fixes/remove_unrecognized_appellant_cases_from_alert_spec.rb
> +    DatabaseCleaner.clean_with(:truncation)
Why was this needed?
I suggest you use `shared_examples` and run it with each JSON file. For an example of how to pass an argument to `shared_examples`, see https://github.com/department-of-veterans-affairs/caseflow/blob/fad743b50cc8195367af236959118a705340cea1/spec/controllers/hearings/hearing_day_controller_spec.rb#L69 or https://github.com/department-of-veterans-affairs/caseflow/blob/03003613e96444f0ab43f1d795399e625a1ba4a0/spec/feature/queue/team_management_spec.rb#L48

2021-09-17 14:52 UTC, yoomlam requested changes
Looks great! Left a suggestion to restructure the spec file to be more Ruby-ist.

As for the remedy, there's a slight concern that we/Foxtrot can deal with if necessary. The `BvaDispatchTask` is auto-assigned to a user (I believe it's round-robin algorithm). There's a chance that by the time we complete the `EngineeringTask`, it shouldn't be assigned to that user for any number of reasons. I suppose at that point, the Board can cancel and reassign the task, or we can cancel the org `BvaDispatchTask` and recreate it so that it can be auto-assigned.

2021-09-17 20:39 UTC, eileen-nava commented on spec/fixes/remove_unrecognized_appellant_cases_from_alert_spec.rb
> +    DatabaseCleaner.clean_with(:truncation)
> DatabaseCleaner.clean_with(:truncation)
> Why was this needed?

Very good question!  When I first wrote the test I had one context block and I imported each other appeal in their own separate `let` statements.  This setup broke the test because some of the imports created the same organization more than once, which violated database constraints.

Then I tried to do a separate context block for each appeal, because I thought that each context block would have a separate state and not violate database constraints.  But, I hit the same problem.  After more fiddling, I added the `DatabaseCleaner.clean_with(:truncation)`

You're right that `shared_examples` is more Ruby-esque, and I did the suggested refactor.  Thanks for suggesting it. 👍

2021-09-17 20:42 UTC, eileen-nava commented
> As for the remedy, there's a slight concern that we/Foxtrot can deal with if necessary. The `BvaDispatchTask` is auto-assigned to a user (I believe it's round-robin algorithm). There's a chance that by the time we complete the `EngineeringTask`, it shouldn't be assigned to that user for any number of reasons. I suppose at that point, the Board can cancel and reassign the task, or we can cancel the org `BvaDispatchTask` and recreate it so that it can be auto-assigned.

Yup, you're right, `BvaDispatchTask` is auto-assigned using the `next_assignee` [method](https://github.com/department-of-veterans-affairs/caseflow/blob/346b7cc17c8b904727f797ae70f6190d5521e865/app/models/round_robin_task_distributor.rb#L41) that the `BvaDispatchTaskDistributor` inherits from the `RoundRobinTaskDistributor`.  I think your proposed solution is sound.

2021-09-17 20:47 UTC, yoomlam commented on spec/fixes/remove_unrecognized_appellant_cases_from_alert_spec.rb
> +    DatabaseCleaner.clean_with(:truncation)
Hmmm. I have this code https://github.com/department-of-veterans-affairs/caseflow/blob/40f890c9d334f8682f42cc276db821c8323bad68/lib/helpers/sanitized_json_configuration.rb#L306-L311
that should reuse records (of certain record types) if they already exist. Do you recall which records violated the DB constraints?

2021-09-22 15:27 UTC, eileen-nava commented
@yoomlam Is this PR ready to be merged or are additional changes required?  I responded to your feedback about making the rspec more Rubyesque.

2021-09-22 15:35 UTC, yoomlam approved these changes
Good to go!

2021-09-22 16:10 UTC, merged