Establish Back-end logic to identify a Contested Claim
department-of-veterans-affairs/caseflow pull request #16777
Opened 2021-09-22 21:23 UTC by meckila-navapbc

Resolves CASEFLOW-2235

### Description
Add backend logic to identify a contested claim (related [Epic](https://vajira.max.gov/browse/CASEFLOW-1626))

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Tests pass

### Testing Plan

2021-09-23 16:54 UTC, allthesignals approved these changes
Not sure how helpful my review will be to you — I only had a few questions for my benefit, but it makes sense to me as someone without much domain/product knowledge!

2021-09-23 16:54 UTC, allthesignals commented on app/models/appeal.rb
> +    matching_issue_categories = Constants::ISSUE_CATEGORIES.values.flatten.select do |category|
How do constants work? I see the constants.rb initializer, but I'm having trouble inferring why flatten needs to happen here (assuming `ISSUE_CATEGORIES` is a hash)...

2021-09-23 16:54 UTC, allthesignals commented on app/models/appeal.rb
> +  def contested_claim?
my (naive) interpretation of this method is that it broadens the definition of a "contested claim" to include "Contested Claims" (obvious) as well as "Apportionment" (not as obvious). Why does "apportionment" also mean "contested"?

2021-09-23 16:54 UTC, allthesignals commented on app/models/appeal.rb
> +  def contested_claim?
Separate question: is there a relationship between `request_issues` (which I'm guessing is a database column bc I don't see it defined on the model directly) and the `ISSUE_CATEGORIES` constants?

2021-09-23 16:54 UTC, allthesignals commented on spec/models/appeal_spec.rb
> +    let(:appeal) { create(:appeal, request_issues: request_issues) }
I'll need to brush up on my Rails testing framework but is this create mock models?

2021-09-23 17:36 UTC, karinamzalez requested changes

2021-09-23 17:36 UTC, karinamzalez commented on spec/models/appeal_spec.rb
> +    context "when issue category falls under contested claim and category contains string 'Contested Claim'" do
Awesome that we're thoroughly testing the instances where the method would return true! Since the title of this spec and the next one are pre-pended with the same text, maybe we can wrap the two in a separate context like: 

```suggestion
   context "when issue category falls under contested claim"  do 
      it "returns true if category contains 'Contested Claim" do 
         ...
      end
       it "returns true if category contains 'Apportionment'" do 
         ...
      end
 end
```

This way, all of the truthy specs are nested under the same context and we can easily add more in the future.

2021-09-23 17:36 UTC, karinamzalez commented on app/models/appeal.rb
> +  def contested_claim?
great job with this method @meckila-navapbc ! -- looks good to me :)

2021-09-24 16:57 UTC, meckila-navapbc commented on spec/models/appeal_spec.rb
> +    let(:appeal) { create(:appeal, request_issues: request_issues) }
That's the general idea. Here we're using a factory to create an appeal based on the appeal model

2021-09-24 16:58 UTC, meckila-navapbc commented on spec/models/appeal_spec.rb
> +    context "when issue category falls under contested claim and category contains string 'Contested Claim'" do
Ah, this makes sense to group the truth blocks

2021-09-24 22:33 UTC, karinamzalez approved these changes

2021-09-24 22:49 UTC, merged