2584/update assigned to
department-of-veterans-affairs/caseflow pull request #16968
Opened 2021-11-17 20:20 UTC by eileen-nava

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-11-17 20:40 UTC, eileen-nava commented on app/models/appeal.rb
>        tasks.active.visible_in_queue_table_view,
I don’t love the `assigned_to_location` method in `task.rb`.  It feels tangled to in line 177 return `COPY::CASE_LIST_TABLE_POST_DECISION_LABEL` based on root_task’s status, rather than returning that from root_task’s `assigned_to_label` method.  When I removed this conditional (see earlier commits on this PR) and tried to put the logic in root_task’s `assigned_to_label` method, tests broke for dispatched appeals.

I’m interested in critical feedback about possible refactors.

2021-11-17 20:43 UTC, eileen-nava commented on app/models/tasks/root_task.rb
> +    COPY::CASE_LIST_TABLE_UNASSIGNED_LABEL
I'm unclear if "case storage" should ever display as "assigned to."  I couldn't find any situations where it should, so I removed it entirely from both this method and `COPY.json`.

2021-11-18 15:10 UTC, yoomlam commented on spec/fixes/assigned_to_search_results_spec.rb
>        expect(appeal.status.status).to eq :unknown
I'm going to see if we can do better than `:unknown` for `appeal.status.status`.

2021-11-18 15:20 UTC, yoomlam requested changes
Initial review, requesting trivial edits.

2021-11-18 15:20 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +      it "returns unassigned" do
```suggestion
      it "returns Unassigned" do
```

2021-11-18 15:20 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +        it "returns unassigned because it does not include nonactionable tasks in its determinations" do
```suggestion
        it "returns Unassigned because it does not include actionable tasks" do
```
or simply
```suggestion
        it "returns Unassigned" do
```

2021-11-18 15:20 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +      describe "when there is an actionable task with an assignee" do
How did you fix the flake?

2021-11-18 15:20 UTC, yoomlam commented on spec/models/legacy_appeal_spec.rb
> +        it "returns unassigned" do
```suggestion
        it "returns Unassigned" do
```

2021-11-18 15:20 UTC, yoomlam commented on spec/models/tasks/root_task_spec.rb
> +      it "returns unassigned" do
```suggestion
      it "returns Unassigned" do
```

2021-11-18 15:20 UTC, yoomlam commented on spec/models/tasks/root_task_spec.rb
> +      it "returns unassigned" do
```suggestion
      it "returns Unassigned" do
```

2021-11-18 15:29 UTC, yoomlam commented on spec/models/appeal_spec.rb
>        end
Note to self: if only the RootTask is open (`on_hold` or `in_progress`), the `assigned_to_location` should be `"Unassigned"`.

2021-11-18 15:32 UTC, yoomlam commented on spec/models/legacy_appeal_spec.rb
>            it "returns Case storage because it does not include nonactionable tasks in its determinations" do
```suggestion
          it "returns Unassigned" do
```

2021-11-18 15:42 UTC, yoomlam commented on app/models/tasks/root_task.rb
> +    COPY::CASE_LIST_TABLE_UNASSIGNED_LABEL
I asked Mike: https://github.com/department-of-veterans-affairs/dsva-vacols/issues/204#issuecomment-972984536

2021-11-18 15:58 UTC, yoomlam commented on app/models/appeal.rb
>        tasks.active.visible_in_queue_table_view,
I presume you mean `appeal.rb` instead of `task.rb`. Are you saying that you'd prefer to delete line 177 and refactor that logic elsewhere?

2021-11-18 17:00 UTC, eileen-nava commented on app/models/appeal.rb
>        tasks.active.visible_in_queue_table_view,
I do mean `appeal.rb` instead of `task.rb`.  That was a typo on my part.  🤦‍♀️ 

> Are you saying that you'd prefer to delete line 177 and refactor that logic elsewhere?

Yes.  I already tried to do this [here](https://github.com/department-of-veterans-affairs/caseflow/pull/16968/commits/4b8cb9a12eff3421f8117bbd9e957ca2c86f146a#L98) for commit "add unassigned to assigned to options."  However, when I removed this guard statement, the incorrect "assigned to" value showed for dispatched appeals.  (See below screenshot from the failure of `spec/fixes/assigned_to_search_results_spec.rb`.)

![Screen Shot 2021-11-18 at 11 44 42 AM](https://user-images.githubusercontent.com/80347702/142458854-10027465-85ba-4728-a3d7-bbe96f70df10.png)

This failure happened because `return tasks.most_recently_updated&.assigned_to_label if tasks.any?` returned "South Dakota Department of Veterans Affairs".

2021-11-18 17:04 UTC, eileen-nava commented on spec/models/appeal_spec.rb
> +        it "returns unassigned because it does not include nonactionable tasks in its determinations" do
I'm confused..... Was the it statement incorrect before?

2021-11-18 17:05 UTC, eileen-nava commented on spec/models/appeal_spec.rb
> +      describe "when there is an actionable task with an assignee" do
When I ran this test, it wasn't flaking.  I ran it 50 times using `ensure_stable` and it never failed.

2021-11-18 17:41 UTC, yoomlam commented on app/models/appeal.rb
>        tasks.active.visible_in_queue_table_view,
Now that I understand your concern...

> It feels tangled to in line 177 return COPY::CASE_LIST_TABLE_POST_DECISION_LABEL based on root_task’s status

My initial thought is that `appeal.rb` querying the root_task's status is "okay" (acceptable but maybe not ideal), given that the appeal is evaluating the `assigned_to_location`. A RootTask should exist for all AMA appeals, and the RootTask is special in that it acts more like a container and isn't assigned to any specific org or user.

With that said, let me try modifying `root_task.rb` similar to your commit.

2021-11-18 17:49 UTC, yoomlam commented on app/models/appeal.rb
>        tasks.active.visible_in_queue_table_view,
The UI is showing "South Dakota Department of Veterans Affairs" because of line 187:
```ruby
    # this condition is no longer needed since we only want active or on hold tasks
    return tasks.most_recently_updated&.assigned_to_label if tasks.any?
```
We could delete the line (given sentiment in the code comment) or change it to:
```ruby
    return tasks.open.most_recently_updated&.assigned_to_label if tasks.any?
```

2021-11-18 17:56 UTC, yoomlam commented on app/models/appeal.rb
>        tasks.active.visible_in_queue_table_view,
I went ahead and pushed a commit of the 2nd option.

2021-11-18 17:58 UTC, yoomlam commented on spec/fixes/assigned_to_search_results_spec.rb
>        expect(appeal.status.status).to eq :unknown
I asked Mike: https://github.com/department-of-veterans-affairs/dsva-vacols/issues/204#issuecomment-972984536

2021-11-18 17:59 UTC, yoomlam commented on spec/models/appeal_spec.rb
> +        it "returns unassigned because it does not include nonactionable tasks in its determinations" do
The `describe` already states "when there are no other tasks". I don't think the "because it does not include actionable tasks" adds any more information.

2021-11-18 18:02 UTC, yoomlam reviewed
Pending passing tests (due to my commit) and Mike's response, the code looks great!

2021-11-18 19:05 UTC, eileen-nava commented on spec/models/appeal_spec.rb
> +        it "returns unassigned because it does not include nonactionable tasks in its determinations" do
That makes sense! 👍

2021-11-18 20:17 UTC, yoomlam commented on app/models/appeal.rb
>        tasks.active.visible_in_queue_table_view,
Reverting my changes and moving them to a separate PR.

2021-11-18 20:35 UTC, yoomlam commented
This PR addresses https://github.com/department-of-veterans-affairs/dsva-vacols/issues/204.

2021-11-18 23:03 UTC, yoomlam approved these changes
Let's merge this. Any changes based on Mike's response can be submitted in a separate PR.

2021-11-19 17:55 UTC, merged