Jrobinson/add migrations to health status
department-of-veterans-affairs/caseflow pull request #17012
Opened 2021-12-02 16:59 UTC by JoelRobinson-Tista

Resolves #{github issue number}

### Description
Add database migration status to `health-check`

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2021-12-02 23:24 UTC, yoomlam commented
This is unfamiliar code to me. How can we test the code changes?

2021-12-03 14:56 UTC, JoelRobinson-Tista commented
It adds some additional JSON to health-check. 

I just started a deployment of this branch to UAT. It should be finished around 10:05 EST.
You can view the change at:
https://certification.cf.uat.ds.va.gov/health-check

2021-12-03 16:06 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
> +    { migrations: migrations, pending_migrations: pending_migrations }
Move `pending_migrations` closer to the top of the page since `migrations` is a long list.
```suggestion
    { pending_migrations: pending_migrations, migrations: migrations }
```

2021-12-03 16:06 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
> +      migrations << { status: status, version: version, name: name }
Do you want/need to include all the migrations or just the ones that are pending?

2021-12-03 16:09 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
> +    pending_migrations = false
Is `pending_migrations` an accurate term? Wondering if `incomplete_migrations` is better.

2021-12-03 16:11 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
> +  def check_migrations
More Rubyist:
```suggestion
  def migration_status
```

2021-12-03 16:21 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
> +      migrations << { status: status, version: version, name: name }
With those changes, this looks much cleaner:
![image](https://user-images.githubusercontent.com/55255674/144636480-81ae9d79-32d5-4a04-b777-3405f6196702.png)

2021-12-03 16:26 UTC, JoelRobinson-Tista commented on app/controllers/health_checks_controller.rb
> +    pending_migrations = false
I [did a Google search](https://www.google.com/search?q=rails+migrations+pending+OR+incomplete&sxsrf=AOaemvK2AJlohsDlExEnO0Fx7Bwa1-P9TA%3A1638548605386&ei=fUSqYYXyFserqtsPtaSksAk&ved=0ahUKEwjFpMichcj0AhXHlWoFHTUSCZYQ4dUDCA4&oq=rails+migrations+pending+OR+incomplete&gs_lcp=Cgdnd3Mtd2l6EAwyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsANKBAhBGABKBghEGIHABUoECEMYA1AAWABgrDRoA3ACeACAAQCIAQCSAQCYAQCgAQLIAQjAAQE&sclient=gws-wiz). `pending` looks to be the most common way of describing it.

2021-12-03 16:26 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
>      render(json: body, status: :ok)
Should the `status` be `ok` if `pending_migrations = true`?

2021-12-03 16:34 UTC, JoelRobinson-Tista commented on app/controllers/health_checks_controller.rb
>      render(json: body, status: :ok)
That just tells the page to return a 200 status code. Under any circumstances I think we'd want that.

2021-12-03 18:44 UTC, yoomlam requested changes
Suggestions to make it more Rubyist.

2021-12-03 18:44 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
> +    }.merge(Rails.application.config.build_version || {}).merge(migrations)
```suggestion
    }.merge(Rails.application.config.build_version || {}).merge(migration_status)
```
and line 11 can be deleted

2021-12-03 18:44 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
> +    { pending_migrations: pending_migrations, migrations: migrations }
```suggestion
    migrations = ActiveRecord::Base.connection.migration_context.migrations_status.map do |status, version, name|
      { status: status, version: version, name: name } unless status == "up"
    end
    { pending_migrations: migrations.any?, migrations: migrations }
```

2021-12-03 21:46 UTC, yoomlam commented on app/controllers/health_checks_controller.rb
> +    end
```suggestion
    migrations = ActiveRecord::Base.connection.migration_context.migrations_status.map do |status, version, name|
     { status: status, version: version, name: name } unless status == "up"
    end.compact
```

2021-12-03 22:07 UTC, yoomlam approved these changes

2021-12-06 14:00 UTC, merged