Caseflow 5066 sync changehearingrequesttypetask with representative change
department-of-veterans-affairs/caseflow pull request #17218
Opened 2022-04-29 18:45 UTC by j-n-t-l

Resolves #[CASEFLOW-5066](https://vajira.max.gov/browse/CASEFLOW-5066)
Description
As a newly appointed rep I need to the ability Veteran with a new representative - when the representative of an appeal changes, the change hearing request type task is reassigned to the new representative

Update Appellant Representation Job needs to be updated to ensure the ChangeHearingRequestTypeTask for a given Appeal is assigned to the correct VSO user when there is a change in representation for the appeal.

Acceptance Criteria

When the representative of an appeal changes:
- [ ] the change hearing request type task is unassigned from the prior representative (can no longer convert to virtual)
- [ ] the change hearing request type task is assigned to the new representative (can convert to virtual)

2022-04-29 18:48 UTC, ksross-va approved these changes
LGTM!

Just for traceability, this PR is a slight revision to this one, due to a change noticed after the merge: https://github.com/department-of-veterans-affairs/caseflow/pull/17212

2022-04-29 19:38 UTC, ksross-va requested changes
Spec tests are failing now that the `after_save` and `after_destroy` are running. 

spec/workflows/initial_tasks_factory_spec.rb will need to be updated

2022-04-29 20:02 UTC, ksross-va commented
A note for anyone else reviewing this PR - ignore these file changes:

- app/controllers/idt/api/v2/appeals_controller.rb
- app/models/decision_document.rb
- lib/tasks/ci.rake
- spec/controllers/idt/api/v2/appeals_controller_spec.rb
- spec/jobs/dispatch_email_job_spec.rb
- spec/models/decision_document_spec.rb

These were pulled in from master at a point when master was ahead of the feature branch, so those are not actually changes made by this PR. These changes _are_ now in the feature branch so I didn't think it worthwhile to revert.

2022-05-03 16:06 UTC, j-n-t-l commented on app/models/tasks/change_hearing_request_type_task.rb
> +  # rubocop:disable Metrics/MethodLength
start of my changes

2022-05-03 16:06 UTC, j-n-t-l commented on app/models/tasks/change_hearing_request_type_task.rb
> +  # rubocop:disable Metrics/MethodLength
start of my changes

2022-05-03 16:06 UTC, j-n-t-l commented on .codeclimate.yml
> +    - 'app/models/tasks/change_hearing_request_type_task.rb'
my change

2022-05-03 16:06 UTC, j-n-t-l commented on .codeclimate.yml
> +    - 'app/models/tasks/change_hearing_request_type_task.rb'
my change

2022-05-03 16:07 UTC, j-n-t-l commented on app/models/bgs_power_of_attorney.rb
> +  after_save :update_changehearingrequesttype_task, if: :update_changehearingrequesttype_enabled?
everything in this file are my changes

2022-05-03 16:07 UTC, j-n-t-l commented on app/models/bgs_power_of_attorney.rb
> +  after_save :update_changehearingrequesttype_task, if: :update_changehearingrequesttype_enabled?
everything in this file are my changes

2022-05-03 16:14 UTC, j-n-t-l commented on app/views/queue/index.html.erb
>        poa_button_refresh: FeatureToggle.enabled?(:poa_button_refresh, user: current_user),
this file has my changes

2022-05-03 16:14 UTC, j-n-t-l commented on app/views/queue/index.html.erb
>        poa_button_refresh: FeatureToggle.enabled?(:poa_button_refresh, user: current_user),
this file has my changes

2022-05-03 16:24 UTC, j-n-t-l commented on spec/models/bgs_power_of_attorney_spec.rb
this file has my changes

2022-05-03 16:24 UTC, j-n-t-l commented on spec/models/bgs_power_of_attorney_spec.rb
this file has my changes

2022-05-06 17:21 UTC, j-n-t-l commented on app/models/tasks/change_hearing_request_type_task.rb
> +      assigned_to_type: Organization.name
Should be assigned_to_type: User.name

2022-05-12 15:13 UTC, ajspotts commented on .codeclimate.yml
> +    - 'app/models/tasks/change_hearing_request_type_task.rb'
```suggestion
```

2022-06-09 19:18 UTC, closed without merging