Ki/appeals 7009
department-of-veterans-affairs/caseflow pull request #17362
Opened 2022-08-08 17:52 UTC by isaiahsaucedo

Resolves #{[APPEALS-7009](https://vajira.max.gov/browse/APPEALS-7009)}

### Description
This PR is in accordance to the acceptance criteria given by APPEALS-7009. Two tables are created. The first table is defined as notification_events, and the second table is defined as notifications.  The tables will be used to store data for retrieval of statuses and events triggered by VANotify. 

### Acceptance Criteria
- [ ] A database table exists that stores the Template ids as a look up table with the following structure:
       Name: notification_events
       columns:
            event_type: string comment: non nullable
            template_id: uuid comment: non nullable
    Primary Key: column: event_type
- [ ] A database table exists that stores the notification information with the following structure:
Name: notifications
columns:
id: serial comments: non nullable
appeals_id: string comments: non nullable
appeals_type: string comments: non nullable
event_type: string comments: non nullable
event_date: date comments: non nullable
participant_id: string comments: 
notified_at: timestamp comments: non nullable
notification_type: string comments: non nullable
email_notification_status: string comments: 
sms_notification_status: string comments: 
recipient_email: string comments:
recipient_phone_number: string comments:
notification_content: text non nullable
created_at: timestamp comments:
updated_at: timestamp comments:
Primary Key:
column: id auto incremental
Indexes:
index1: participant_id and appeals_id and appeals_type
foreign_keys:
event_type -> event_type of event lookup table
- [ ] A model exists for notification_events
- [ ] A model exists for notifications

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2022-08-09 19:33 UTC, jshields13 requested changes

2022-08-09 19:33 UTC, jshields13 commented on db/migrate/20220804135348_add_indexes_to_notifications.rb
> +class AddIndexesToNotifications < Caseflow::Migration
Get rid of singular indexes on line 4 and 5 and create a single index that combines appeals_id and appeals_type

example:
` t.index ["source_type", "source_id"], name: "index_end_product_establishments_on_source_type_and_source_id"`

2022-08-10 12:58 UTC, KiMauVA commented on db/migrate/20220804135348_add_indexes_to_notifications.rb
> +class AddIndexesToNotifications < Caseflow::Migration
Updated using the newer add_safe_index convention

2022-08-11 11:38 UTC, jshields13 approved these changes

2022-08-11 17:18 UTC, jshields13 approved these changes

2022-08-11 17:18 UTC, merged