Aaron willis/appeals 7004
department-of-veterans-affairs/caseflow pull request #17361
Opened 2022-08-08 13:05 UTC by Aaron-Willis

### Description
Created Module that houses method overrides that will notify appellants of tracked status changes.

2022-08-08 18:13 UTC, jshields13 commented on app/models/appellant_notification.rb
> +
We need to break all these out into their own file

I suggest the folder setup to be app/models/prepend/va_notify

2022-08-08 18:15 UTC, jshields13 commented on app/models/appellant_notification.rb
> +      if claimant == nil
use claimanbt.nil? in place of == nil
to adhear to linting rules

2022-08-08 18:16 UTC, jshields13 commented on app/models/appellant_notification.rb
> +    if appeal != nil
!var.nil?

2022-08-08 18:20 UTC, jshields13 commented on app/models/appellant_notification.rb
> +  #Module to notify appellant when an appeal gets docketed
need spa ce from #

2022-08-08 18:23 UTC, jshields13 commented on app/models/appellant_notification.rb
> +    @@template_name = self.name.split("::")[1]
Try to fix linting error (may be OBE when broken out)

2022-08-08 18:54 UTC, jshields13 reviewed
Game plan:
- Create file structure app/models/prepend/va_notify
- Break out each prepend method into its own .rb (see Warroom module for example)
- Clean up linting errors
- Remove feature flag from index.html.erb

2022-08-08 20:50 UTC, ThorntonMatthewD commented
```bash
git fetch origin && git diff-tree -r --no-commit-id --name-only HEAD origin/master | grep '\.rb$' | xargs bundle exec rubocop -a --force-exclusion
```

Running that in your caseflow directory will get rid of most of the whitespace issues for you.

2022-08-12 20:06 UTC, mroberts14 commented on app/models/prepend/va_notify/appellant_notification.rb
> +    queue = Shoryuken::Client.queues(ActiveJob::Base.queue_name_prefix + "_send_notifications")
might need "_send_notifications.fifo" here

```
[root@ip-x-x-104-86 src]# /opt/caseflow-certification/src/bin/bundle exec shoryuken sqs ls
Queue                                                  Messages Available    Messages Inflight    Last Modified
...
caseflow_uat_receive_notifications.fifo                0                     0                    2022-08-12 12:55:47 -0400
caseflow_uat_receive_notifications_dead_letter.fifo    0                     0                    2022-08-12 12:55:43 -0400
caseflow_uat_send_notifications.fifo                   0                     0                    2022-08-10 17:30:01 -0400
caseflow_uat_send_notifications_dead_letter.fifo       0                     0                    2022-08-10 17:28:59 -0400
....
```

2022-08-12 20:08 UTC, mroberts14 commented on config/initializers/shoryuken.rb
> +  Shoryuken::Client.sqs.create_queue({ queue_name: ActiveJob::Base.queue_name_prefix + '_receive_notifications' })
Might need to add `.fifo` to the end of these.

```
[root@ip-x-x-104-86 src]# /opt/caseflow-certification/src/bin/bundle exec shoryuken sqs ls
Queue                                                  Messages Available    Messages Inflight    Last Modified
...
caseflow_uat_receive_notifications.fifo                0                     0                    2022-08-12 12:55:47 -0400
caseflow_uat_receive_notifications_dead_letter.fifo    0                     0                    2022-08-12 12:55:43 -0400
caseflow_uat_send_notifications.fifo                   0                     0                    2022-08-10 17:30:01 -0400
caseflow_uat_send_notifications_dead_letter.fifo       0                     0                    2022-08-10 17:28:59 -0400
....
```

2022-08-15 13:29 UTC, mroberts14 commented on app/models/prepend/va_notify/appellant_notification.rb
> +      queue_url: "caseflow_development_send_notifications",
Does the `.fifo` tag need to be added hear as well as the queue is named `caseflow_<env>_send_notifications.fifo` within AWS?

2022-08-15 13:31 UTC, mroberts14 commented on config/initializers/shoryuken.rb
> +  Shoryuken::Client.sqs.create_queue({ queue_name: ActiveJob::Base.queue_name_prefix + '_receive_notifications' })
This has been fixed. Thank you

2022-08-23 18:23 UTC, jshields13 requested changes

2022-08-23 18:23 UTC, jshields13 commented on app/models/prepend/va_notify/appellant_notification.rb
> +      participant_id = appeal.claimant_participant_id || AppellantNotification.legacy_non_vet_claimant_id(appeal)
Break this logic out into the parent method of the call stack and pass in the participant id into thi function to avoid calling it twice

2022-08-25 11:46 UTC, jshields13 commented on app/models/prepend/va_notify/appeal_decision_mailed.rb
> -    super
@Aaron-Willis @msteele96 @j-n-t-l What is this doing?

2022-08-25 12:12 UTC, msteele96 commented on app/models/prepend/va_notify/appeal_decision_mailed.rb
> -    super
We are capturing the return value of super and storing it in rtn, then doing our notification work, and returning the original value. Some of the rspec was failing because there were other methods involved that needed to use the return value from super and they were instead getting nil because our notification process does not return anything.

2022-08-26 11:48 UTC, jshields13 approved these changes

2022-08-26 13:32 UTC, merged