Sudhir/appeals 8475
department-of-veterans-affairs/caseflow pull request #17419
Opened 2022-08-30 23:35 UTC by samasudhirreddy

Resolves #{8475}

### Description
Distribute cases from all dockets for priority
### Acceptance Criteria
Oldest priority and priority legacy hearing cases tied to a VLJ are collected, shuffled together, and distributed in the order they were placed. 
VLJ's are distributed cases starting with oldest till hit batch size for a judge.

2022-08-31 13:27 UTC, zurbergram commented on app/models/concerns/all_case_distribution.rb
> +      distribute_genpop_priority_appeals_from_all_dockets_by_age_to_limit(@rem, style: "request")
This is not correct, see https://github.com/department-of-veterans-affairs/caseflow/pull/17417

2022-08-31 13:28 UTC, zurbergram reviewed
Missing unit test for `app/models/concerns/all_case_distribution.rb`

There is not a removal of proportions code.
`priority_push_distribution` was not changed.
Priority code in `requested_distribution` was not changed.

2022-09-06 13:55 UTC, zurbergram commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    @distributions = distribute_priority_appeals
This is incorrect. Old calls should not be removed, instead the feature toggle `acd_distribute_all` should be used to determine which code is executed.

2022-09-06 13:55 UTC, zurbergram commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +              "#{@distributions.map { |distribution| distribution.statistics['batch_size'] }.sum}"
This change is outside the scope of the story. https://vajira.max.gov/browse/APPEALS-8482 covers slack notification updates

2022-09-06 13:55 UTC, zurbergram commented on app/jobs/push_priority_appeals_to_judges_job.rb
> -  # Distribute all priority cases tied to a judge without limit
Old code should not be removed, see AC#4

2022-09-06 13:55 UTC, zurbergram commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    ready_priority_appeals_count - target_distributions_for_eligible_judges.values.sum
There will be no priority targets for `acd_distribute_all`, limit is batch_size for each VLJ. Do not change existing code's functionality

2022-09-06 13:55 UTC, zurbergram commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +        target = (distribution_counts.sum + ready_priority_appeals_count) / distribution_counts.count
There will be no priority targets for `acd_distribute_all`, limit is batch_size for each VLJ. Do not change existing code's functionality

2022-09-06 13:55 UTC, zurbergram commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +        target = (distribution_counts.sum + ready_priority_appeals_count) / distribution_counts.count
There will be no priority targets for `acd_distribute_all`, limit is batch_size for each VLJ. Do not change existing code's functionality

2022-09-06 14:48 UTC, zurbergram requested changes
Changes required in:
- `app/jobs/push_priority_appeals_to_judges_job.rb`
- `app/models/concerns/all_case_distribution.rb`
- `distribute_appeals` methods in the docket classes

2022-09-08 13:12 UTC, zurbergram requested changes
Changes requested in 
- app/jobs/push_priority_appeals_to_judges_job.rb
- app/models/concerns/all_case_distribution.rb
- app/models/docket.rb

Please answer questions from previous review
- In app/models/vacols/case_docket.rb
  - Does this cover the "legacy hearings tied to VLJ who held the hearing last" and all other legacy priority cases?
- In app/models/concerns/all_case_distribution.rb
  - Which class is judge defined in?

2022-09-08 13:12 UTC, zurbergram commented on app/models/concerns/all_case_distribution.rb
> +      end
Still missing updates to deal with the issue that priority does not currently sort by AMA `receipt_date` when distributing because of https://github.com/department-of-veterans-affairs/caseflow/blob/development/app/models/docket.rb#L109

Proportions should continue to order this way for Priority but "By Docket Date" should be swapped to `receipt_date`

2022-09-12 14:36 UTC, zurbergram commented on app/models/docket.rb
> +    if FeatureToggle.enabled?(:acd_distribute_all, user: RequestStore.store[:current_user])
can this be passed down as a parameter instead?

To limit number of places in code we are referencing the feature toggle

2022-09-12 16:32 UTC, samasudhirreddy commented on app/models/docket.rb
> +    if FeatureToggle.enabled?(:acd_distribute_all, user: RequestStore.store[:current_user])
You are excepting me  to pass inside of docker or to docket ?

2022-09-12 16:45 UTC, zurbergram commented on app/models/docket.rb
> +    if FeatureToggle.enabled?(:acd_distribute_all, user: RequestStore.store[:current_user])
Ignore

2022-09-12 16:46 UTC, zurbergram commented
Wanting on a response from business about using Priority Target

2022-09-12 17:21 UTC, zurbergram requested changes
Changes requested in

- app/jobs/push_priority_appeals_to_judges_job.rb

Please answer questions from previous review

- In app/models/vacols/case_docket.rb
  - Does this cover the "legacy hearings tied to VLJ who held the hearing last" and all other legacy priority cases?
- In app/models/concerns/all_case_distribution.rb
  - Which class is judge defined in?

2022-09-12 17:21 UTC, zurbergram commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +    eligible_judge_target_distributions_with_leftovers.map do |judge_id, target|
This is incorrect, any judge who is able to receive priority cases and has not hit their batch_size should be distributed priority cases.  Priority Target and other proportions related code is not being used when distributing priority cases for "by docket date" algorithm.

2022-09-13 19:37 UTC, samasudhirreddy commented on app/models/docket.rb
> +  def age_of_n_oldest_priority_appeals_available_to_judge(_, num)
> Changes requested in
> 
> * app/jobs/push_priority_appeals_to_judges_job.rb
> 
> Please answer questions from previous review
> 
> * In app/models/vacols/case_docket.rb
>   
>   * Does this cover the "legacy hearings tied to VLJ who held the hearing last" and all other legacy priority cases?
        Yes it Does
> * In app/models/concerns/all_case_distribution.rb
>   
>   * Which class is judge defined in?

Judges are not I updated with self

2022-09-13 20:11 UTC, samasudhirreddy commented
> Changes requested in
> 
> * app/jobs/push_priority_appeals_to_judges_job.rb
> 
> Please answer questions from previous review
> 
> * In app/models/vacols/case_docket.rb
>   
>   * Does this cover the "legacy hearings tied to VLJ who held the hearing last" and all other legacy priority cases?
        Yes Does
> * In app/models/concerns/all_case_distribution.rb
>   
>   * Which class is judge defined in?
        Self

2022-09-14 14:22 UTC, zurbergram commented on app/jobs/push_priority_appeals_to_judges_job.rb
> +      ).tap { |distribution| distribution.distribute!(distribution.batch_size) }
Limit should be batch_size minus current cases 

See methods here to get counts
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/distribution.rb#L81-L89

2022-09-16 13:11 UTC, zurbergram requested changes
Not accounting for `judge_legacy_tasks` and unused code left in a class

2022-09-16 18:04 UTC, zurbergram approved these changes

2022-09-16 20:26 UTC, merged