APPEALS-8476
department-of-veterans-affairs/caseflow pull request #17417
Opened 2022-08-30 19:05 UTC by craigrva

Resolves [APPEALS-8476](https://vajira.max.gov/browse/APPEALS-8476) 

### Description
- Added feature toggles to point to all_case_distribution.rb
- Added methods to get {limit} number of appeals from all dockets, sort by age only, then get the oldest {limit} number of appeals and distribute them for non-priority genpop appeals
- Added BFDNOD (Notice of Disagreement date; correlated to receipt_date in Caseflow) to the VACOLS SQL queries since that is the date we should be sorting by
- Added condition “is not null” for BFAC/BFDNOD in SELECT_READY_APPEALS to prevent the query from getting cases from VACOLS with incomplete data that shouldn’t be counted. Without this, the cases would be used in the above methods and selected as ready, but without those columns will not be selected by the distribution queries. This would cause the request_distribution to eventually distribute nothing, since the same VACOLS cases would take up the spots as the oldest appeals but would never be distributed properly
- Modified several seed files to ensure that VACOLS cases get created with values for BFAC and BFDNOD so that testable data is seeded; without this change, zero nonpriority genpop cases would be seeded in VACOLS

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Running a request distribution from a judge in Caseflow distributes nonpriority cases based only on age instead of proportions

### Testing Plan
1. Go to Caseflow
2. Select a judge user who can be assigned cases (BVAEBECKER, BVAAABSHIRE are two examples)
3. Go to queue and switch views to the 'Assign team cases' view
4. If cases are available to assign, assign them to attorneys until there are less than three awaiting assignment
5. Click 'Request more cases'
6. Ensure the 'Distribution Complete' banner appears and distributed cases populate on the page

2022-08-31 13:15 UTC, zurbergram requested changes
Is `deduct_distributed_actuals_from_remaining_docket_proportions(:legacy, :hearing)` still needed at https://github.com/department-of-veterans-affairs/caseflow/blob/craig/APPEALS-8275/app/models/concerns/all_case_distribution.rb#L59 ?

Is there any other proportions code in this file for non-priority that can be removed?

Missing unit tests for `app/models/concerns/all_case_distribution.rb`

2022-08-31 13:15 UTC, zurbergram commented on app/models/concerns/all_case_distribution.rb
> +      distribute_genpop_nonpriority_appeals_from_all_dockets_by_age_to_limit(@rem, style: "request")
`@remaining_docket_proportions.all_zero?` is this being used or updated anymore?
Same with comments related to proportions above.

2022-08-31 13:41 UTC, craigrva commented on app/models/concerns/all_case_distribution.rb
> +      distribute_genpop_nonpriority_appeals_from_all_dockets_by_age_to_limit(@rem, style: "request")
I removed each of those; I thought they were used in ama_statistics, but that uses the original docket_proportions instead of @remaining_docket_proportions

2022-09-06 15:16 UTC, zurbergram requested changes
Changes required in:

- `distribute_appeals` methods in the Legacy docket class

Please make sure rspec unit tests are passing before requesting review again.

2022-09-06 15:16 UTC, zurbergram commented on app/models/docket.rb
> +  def age_of_n_oldest_nonpriority_appeals_available_to_judge(_, num)
method name is not accurate as judge is not used

2022-09-06 15:16 UTC, zurbergram commented on app/models/dockets/hearing_request_docket.rb
> +  def age_of_n_oldest_nonpriority_appeals_available_to_judge(_, num)
method name is not accurate as judge is not used

2022-09-06 15:16 UTC, zurbergram commented on app/models/vacols/case_docket.rb
> +      where (VLJ = ? or VLJ is null)
Does this cover the "legacy hearings tied to VLJ who held the hearing last" and all other legacy cases?

2022-09-06 15:16 UTC, zurbergram commented on app/models/concerns/all_case_distribution.rb
> +        dockets[docket].distribute_appeals(self, limit: number_of_appeals_to_distribute, priority: false, style: style)
Need to make updates to the Legacy `distribute_appeals` methods to ensure that sorting is done by BFDNOD.

Recommend adding adding an argument to the methods with default value that triggers current code, so calls from from `all_case_distribution` will have to explicitly say use `receipt_date` for AMA or `BFDNOD` for Legacy

2022-09-06 15:46 UTC, craigrva commented on app/models/concerns/all_case_distribution.rb
> +        dockets[docket].distribute_appeals(self, limit: number_of_appeals_to_distribute, priority: false, style: style)
I added the sorting to the SELECT_NONPRIORITY_APPEALS constant at https://github.com/department-of-veterans-affairs/caseflow/blob/craig/APPEALS-8275/app/models/vacols/case_docket.rb#L120, which will pre-sort the cases so that the oldest are first when they reach the distribute_appeals method. I think that's simpler than passing arguments through, since we'd have to deal with those arguments in the AMA streams as well. Also, changing that constant won't affect the way the methods that use it function.

2022-09-06 15:47 UTC, zurbergram commented on app/models/concerns/all_case_distribution.rb
> +        dockets[docket].distribute_appeals(self, limit: number_of_appeals_to_distribute, priority: false, style: style)
🤦

2022-09-06 15:48 UTC, craigrva commented on app/models/vacols/case_docket.rb
> +      where (VLJ = ? or VLJ is null)
Yes, the hearings are joined as VLJ, where VLJ is the STAFF.SATTYID field which is the same as the vacols_attorney_id on the caseflow Judge model. If a hearing was held it will be joined and VLJ will have the ID, otherwise the field is null.

2022-09-06 15:51 UTC, craigrva commented on app/models/docket.rb
> +  def age_of_n_oldest_nonpriority_appeals_available_to_judge(_, num)
I added a comment to the method, the reason for this is that the method name needs to match between AMA docket models and legacy_docket.rb, and the legacy_docket.rb method does need the judge value so I named it to reflect that portion.

2022-09-06 15:51 UTC, craigrva commented on app/models/dockets/hearing_request_docket.rb
> +  def age_of_n_oldest_nonpriority_appeals_available_to_judge(_, num)
I added a comment to the method, the reason for this is that the method name needs to match between AMA docket models and legacy_docket.rb, and the legacy_docket.rb method does need the judge value so I named it to reflect that portion.

2022-09-06 15:54 UTC, craigrva commented on app/models/concerns/all_case_distribution.rb
> +    num_oldest_nonpriority_appeals_for_judge_by_docket(judge, limit).each do |docket, number_of_appeals_to_distribute|
Judge is a value on the parent distribution object, rubocop gave me a warning about a redundant 'self' when I wrote it as self.judge. I changed the method to pass 'self' in, then adjusted the wording on num_oldest_nonpriority_appeals_for_judge_by_docket to reflect what is actually being passed in and used

2022-09-06 17:45 UTC, zurbergram approved these changes
LGTM

2022-09-06 21:10 UTC, merged