Hotfix/APPEALS-9359
department-of-veterans-affairs/caseflow pull request #17551
Opened 2022-10-05 19:19 UTC by minhazur9

Resolves APPEALS-9359

### Description
Added in a job for polling for legacy appeals that have been recently docketed. Added feature flags to disable "appeal docketed" events and emails and made changes to Notifications table

### Database Changes
- [ ] Added in new email_enabled column to Notifications table 
- [ ] Made notified_at column nullable for Notification

2022-10-07 18:04 UTC, jshields13 approved these changes

2022-10-07 18:06 UTC, jshields13 approved these changes

2022-10-07 19:09 UTC, zurbergram commented on app/controllers/api/v1/jobs_controller.rb
> +  # available jobs supported by this endpoint
This doesn't belong here anymore, new location is https://github.com/department-of-veterans-affairs/caseflow/blob/master/config/initializers/scheduled_jobs.rb

2022-10-11 20:56 UTC, zurbergram requested changes
do `git checkout origin/master app/controllers/api/v1/jobs_controller.rb`

2022-10-12 13:55 UTC, zurbergram approved these changes

2022-10-13 14:12 UTC, closed without merging