Billy s/appeals 9136
department-of-veterans-affairs/caseflow pull request #17581
Opened 2022-10-13 20:39 UTC by brstockton50

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2022-10-24 19:01 UTC, TylerBroyles requested changes

2022-10-24 20:06 UTC, brstockton50 commented on client/app/intake/components/SelectClaimant.jsx
> +      isNotRamp && !VBMS_BENEFIT_TYPES.includes(benefitType) && featureToggles.hlrScUnrecognizedClaimants
Thanks!

2022-10-24 20:07 UTC, brstockton50 commented on client/app/intake/components/SelectClaimant.jsx
> +        {showClaimantNotListedOption ? SELECT_NON_LISTED_CLAIMANT_LABEL : SELECT_CLAIMANT_LABEL}
thanks

2022-10-24 20:55 UTC, brstockton50 commented on client/app/intake/components/SelectClaimant.stories.js
> +export const HLRWithVBMSBenTypes = Template.bind({});
I think I understand what you are saying.  I have a question though.  Storybook displays by component and SelectClaimant is its own component but is dependent on the benefit type which is a different  component.  The benefit type component does not have any StoryBook files written so I am having a hard time picturing how to make the storybook file interactive.  Would the BenefitType Storybook need to be created as well? Or am I completely missing something simple here?

2022-10-24 21:03 UTC, TylerBroyles commented on client/app/intake/components/SelectClaimant.jsx
> +      isNotRamp && !VBMS_BENEFIT_TYPES.includes(benefitType) && featureToggles.hlrScUnrecognizedClaimants
Actually after thinking about it a bit. This logic won't work for appeals if the feature is turned off. It needs to be updated. I think this might work
```suggestion
      ((isNotRamp && featureToggles.hlrScUnrecognizedClaimants) || isAppeal) && !VBMS_BENEFIT_TYPES.includes(benefitType)
```

2022-10-25 13:01 UTC, brstockton50 commented on client/app/intake/components/SelectClaimant.jsx
> +      isNotRamp && !VBMS_BENEFIT_TYPES.includes(benefitType) && featureToggles.hlrScUnrecognizedClaimants
I will make this change and test it to see if it is functioning correctly.  Thank you so much for noticing it and pointing it out!

2022-10-25 13:27 UTC, brstockton50 commented on client/app/intake/components/SelectClaimant.jsx
> +      isNotRamp && !VBMS_BENEFIT_TYPES.includes(benefitType) && featureToggles.hlrScUnrecognizedClaimants
I made this change and it is working great on both 10182 and HLR/SC forms

2022-10-28 18:38 UTC, merged