Janet/appeals 10317
department-of-veterans-affairs/caseflow pull request #17744
Opened 2022-11-21 19:50 UTC by j-n-t-l

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2022-12-05 18:47 UTC, jshields13 requested changes

2022-12-05 18:47 UTC, jshields13 commented on app/jobs/quarterly_notifications_job.rb
> +        AppellantNotification.notify_appellant(appeal, "Postponement of hearing")
AppellantNotification.notify_appellant(appeal, "Postponement of hearing") every time you send a notification it will just be a be AppellantNotification.notify_appellant(appeal, "Quarterly Notification") every time. In this job we can only send Quarterly Notifications so we shouldn't have any other notification got off

2022-12-05 18:47 UTC, jshields13 commented on app/models/prepend/va_notify/privacy_act_complete.rb
> +  end
Did you story also added privacy act logic or is this from another's branch?

2022-12-05 18:50 UTC, j-n-t-l commented on app/jobs/quarterly_notifications_job.rb
> +        AppellantNotification.notify_appellant(appeal, "Postponement of hearing")
Oh I added those in to make testing easier but I forgot to change them back, sorry

2022-12-05 18:51 UTC, j-n-t-l commented on app/models/prepend/va_notify/privacy_act_complete.rb
> +  end
This is adding the callback to privacy act pending and complete just like how Aaron did his for ihp

2022-12-07 13:06 UTC, jshields13 requested changes

2022-12-07 13:06 UTC, jshields13 commented on client/app/queue/caseEvaluation/calculateDaysWorked.js
> +// import { extendMoment } from 'moment-range';
Commented out code shoudl be removed

2022-12-07 13:06 UTC, jshields13 commented on client/app/queue/caseEvaluation/calculateDaysWorked.js
>    return rangeA.start.isSame(rangeB.start, 'day') && rangeA.end.isSame(rangeB.end, 'day');
I don;t think thsi is your change and should not be in your PR

2022-12-07 13:06 UTC, jshields13 commented on client/app/queue/selectors.js
>  import Moment from 'moment';
I don't think this file is your PR either?

2022-12-07 13:06 UTC, jshields13 commented on spec/jobs/quarterly_notifications_job.rb
> +# frozen_string_literal: true
This file should be named spec/jobs/quarterly_notifications_job_spec.rb

2022-12-07 13:09 UTC, jshields13 commented on app/jobs/quarterly_notifications_job.rb
> +  end
I think we need some error handling as well. What are we doing if 16 or 18 does not find an appeal would kill the whole job I think thughts @msteele96 @minhazur9 ?

2022-12-07 18:19 UTC, j-n-t-l commented on app/jobs/quarterly_notifications_job.rb
> +  end
I added a fail statement, not sure if anything else is needed.

2022-12-07 18:36 UTC, msteele96 commented on app/jobs/quarterly_notifications_job.rb
> +        fail Caseflow::Error::AppealNotFound, "IDT Standard Error ID: " + SecureRandom.uuid + " The appeal was unable to be found."
IDT?

2022-12-07 18:39 UTC, j-n-t-l commented on app/jobs/quarterly_notifications_job.rb
> +        fail Caseflow::Error::AppealNotFound, "IDT Standard Error ID: " + SecureRandom.uuid + " The appeal was unable to be found."
oops lol

2022-12-08 17:31 UTC, jshields13 approved these changes

2022-12-08 17:31 UTC, merged