MattT/APPEALS-12483
department-of-veterans-affairs/caseflow pull request #17805
Opened 2022-12-09 16:11 UTC by ThorntonMatthew

# WIP

2022-12-09 20:44 UTC, ThorntonMatthew commented on app/controllers/decision_reviews_controller.rb
> +  helper_method :in_progress_tasks, :completed_tasks, :apply_task_serializer, :business_line, :task
I've added `:apply_task_serializer` here as digital "duct tape" to allow for the existing implementation of the decision review queues on the frontend to continue working properly. It will need to be removed, along with `:in_progress_tasks` and `:completed_tasks` in [APPEALS-12480](https://vajira.max.gov/browse/APPEALS-12480).

2022-12-09 20:44 UTC, ThorntonMatthew commented on app/views/decision_reviews/index.html.erb
> +      inProgressTasks: apply_task_serializer(in_progress_tasks),
Both of these will be removed completely in [APPEALS-12480](https://vajira.max.gov/browse/APPEALS-12480).

2022-12-09 20:47 UTC, ThorntonMatthew commented on spec/factories/task.rb
> +      factory :higher_level_review_vha_task, class: DecisionReviewTask do
This factory, and the accompanying trait, were provided by @TylerBroyles.

2022-12-13 00:08 UTC, ThorntonMatthew commented on app/controllers/decision_reviews_controller.rb
> +          in_progress_tasks: apply_task_serializer(in_progress_tasks),
These will be removed in [APPEALS-12480](https://vajira.max.gov/browse/APPEALS-12480). For now, they are needed in order to allow decision review tasks to be completed.

2022-12-13 20:46 UTC, ThorntonMatthew commented on app/controllers/concerns/decision_review_queue_pagination_concern.rb
> +    tasks.map { |task| task.ui_hash.merge(business_line: business_line_slug) }
`ui_hash` needs to be flipped to `expanded_ui_hash` after being merged with APPEALS-12481.

2022-12-13 20:46 UTC, ThorntonMatthew commented on app/controllers/concerns/decision_review_queue_pagination_concern.rb
> +    tasks.map { |task| task.ui_hash.merge(business_line: business_line_slug) }
Using `expanded_ui_hash` causes a plethora of rspec failures as is, which is why it isn't present at this time.

2022-12-15 20:58 UTC, TylerBroyles requested changes
Looks good overall just a couple of comments here and there.

2022-12-15 20:58 UTC, TylerBroyles commented on client/app/queue/utils.js
>      assignedTo: {
Something I tried out but it might be just as gross (or more since it's using truthy logic trickery) as using nullsafe operators on everything
`      assignedTo:{
          ...task.attributes.assignedBy && {
          firstName: task.attributes.assigned_by.first_name,
          lastName: task.attributes.assigned_by.last_name,
          cssId: task.attributes.assigned_by.css_id,
          pgId: task.attributes.assigned_by.pg_id,
      }
}`

2022-12-15 20:58 UTC, TylerBroyles commented on spec/controllers/decision_reviews_controller_spec.rb
> +    subject { get :index, params: query_params, format: :json }
Interesting Rails magic for get requests.

2022-12-15 21:01 UTC, ThorntonMatthew commented on app/controllers/decision_reviews_controller.rb
> +      :filter,
Thanks for the heads up!

2022-12-15 21:02 UTC, ThorntonMatthew commented on app/models/serializers/work_queue/decision_review_task_serializer.rb
I really like this idea! Thanks!

2022-12-15 21:27 UTC, ThorntonMatthew commented on app/models/serializers/work_queue/decision_review_task_serializer.rb
Done!

2022-12-15 21:28 UTC, ThorntonMatthew commented on app/models/tasks/decision_review_task.rb
> +  def expanded_ui_hash
Thanks! I removed expanded_ui_hash and just have apply_task_serializer using serialize_task directly now. I put a comment on that method detailing its use for in the DR queues.

2022-12-15 21:29 UTC, ThorntonMatthew commented on app/controllers/concerns/decision_review_queue_pagination_concern.rb
> +    tasks.map { |task| task.expanded_ui_hash.merge(business_line: business_line_slug) }
Moved that bad boy!

2022-12-16 13:53 UTC, ThorntonMatthew commented on client/app/queue/selectors.js
> +import { taskIsActive, taskIsOnHold, getAllChildrenTasks } from './utils';
All changes in this file are ESLint/CC fixes.

2022-12-16 14:48 UTC, ThorntonMatthew commented on client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
> -  getAttorneyTasksForJudgeTask,
ESLint fix

2022-12-16 14:51 UTC, ThorntonMatthew commented on client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
> -  getAttorneyTasksForJudgeTask,
This was an unused import.

2022-12-16 15:08 UTC, TylerBroyles approved these changes
Looks good to me! I guess we will find out if we missed anything when we smash the branches together.

2023-01-10 20:57 UTC, merged