aaron/appeals-12007-v2
department-of-veterans-affairs/caseflow pull request #17814
Opened 2022-12-13 16:58 UTC by Aaron-Willis

Resolves #{APPEALS-12007}

### Description
Added Appeal Status for quarterly notifications.

### Acceptance Criteria
- [x] The Quarterly notification job sends out statuses to the appellant of each appeal through VA Notify
- [x] VA Notify service can accept a status string and send that status for quarterly notifications.
- [x] The email and sms sending functions are updated to take an optional status parameter
- [x] The email and sms api requests will be updated to include the status in the personalisation of the json body

### Testing Plan
1. https://vajira.max.gov/browse/APPEALS-12579
### Test Execution
1. https://vajira.max.gov/secure/XrayExecuteTest!default.jspa?testExecIssueKey=APPEALS-12584&testIssueKey=APPEALS-12579
2. https://vajira.max.gov/browse/APPEALS-12584

2022-12-13 19:59 UTC, jshields13 approved these changes

2022-12-14 14:06 UTC, jshields13 requested changes

2022-12-14 14:06 UTC, jshields13 commented on app/jobs/send_notification_job.rb
> -      if appeal&.appellant_is_not_veteran
Why remove the .&? @Aaron-Willis

2022-12-14 15:22 UTC, Aaron-Willis commented on app/jobs/send_notification_job.rb
> -      if appeal&.appellant_is_not_veteran
I updated the first name logic and added the safety navigator.

2022-12-14 20:10 UTC, jshields13 approved these changes

2022-12-14 20:11 UTC, merged