MattT/APPEALS-12465
department-of-veterans-affairs/caseflow pull request #17858
Opened 2022-12-16 23:11 UTC by ThorntonMatthew

Resolves [APPEALS-12465](https://vajira.max.gov/browse/APPEALS-12465)

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2022-12-19 04:29 UTC, ThorntonMatthew commented on app/controllers/concerns/generic_task_pagination_concern.rb
> +    tasks.map(&:serialize_task)
This method throws a CC issue due to a code smell. The method itself will be removed in APPEALS-12480 as it will no longer be needed (`.map(&:serialize_task)` can be tacked onto `paginate_tasks(task_list)` on line L22).

2022-12-19 04:29 UTC, ThorntonMatthew commented on app/controllers/concerns/generic_task_pagination_concern.rb
> +    tasks.map(&:serialize_task)
`serialize_task` does need called on each task- that hasn't changed.

2022-12-19 04:32 UTC, ThorntonMatthew commented on app/models/serializers/work_queue/decision_review_task_serializer.rb
> +    object[:issues_count] || request_issues(object).active_or_ineligible.size
This removes all of the additional `SELECT COUNT(*) FROM request_issues` queries that were made each time a task was serialized. Credit to @TylerBroyles for detailing this in his research.

2022-12-20 18:54 UTC, TylerBroyles requested changes
Overall looks great. I like how you tidied up some of the repeated code and I like the implementation. I added a couple of comments only one of which really needs any follow up. Let me know which method you like better and I'll approve it either way.

2022-12-20 18:54 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +
I'm not sure how I feel about a concern that will probably never be reused anywhere else. I don't really like it but I also don't really like the alternative of stuffing it all into the BusinessLine class. A mixin might be okay but that's basically just a concern as well. Up to you what you decide to do with this.

2022-12-20 18:54 UTC, TylerBroyles commented on app/models/serializers/work_queue/decision_review_task_serializer.rb
> +    object[:issue_count] || request_issues(object).active_or_ineligible.size
This was one of my main time saves on the serialization. It only gets harder for [APPEALS-12466](https://vajira.max.gov/browse/APPEALS-12466) after this one. I'm not sure too many more can be done so we will need to make sure that ticket is still valid since this is already in here now. Depending on how searching/ordering is implemented we might also be able to get away with avoiding some of the veteran method calls, but I think that will be the extent of it. There might be some other places that some additional queries can be cleaned up but that will probably be it for the decision_review_task_serializer.

2022-12-20 18:54 UTC, TylerBroyles commented on spec/models/business_line_spec.rb
> -        task.appeal.update!(request_issues: [])
This original test would still pass with the union version of the bge task query. However, this definitely more accurately reflects the state of the data from what you seem to have seen the production database. Either way is fine with me.

2022-12-20 18:54 UTC, TylerBroyles commented on spec/models/business_line_spec.rb
> +        expect(subject.map(&:id)).to match_array(
Ah the annoying consequences of a polymorphic, multi-object hash masquerading as a Task.

2022-12-20 18:54 UTC, TylerBroyles commented on app/models/concerns/decision_review_tasks_concern.rb
> +
```suggestion

  # Specific case for BoardEffectuationGrantTasks
  def board_grant_effectuation_tasks
    Task.select(Task.arel_table[Arel.star], issue_count)
      .open
      .left_joins(ama_appeal: :request_issues)
      .where(Task.arel_table[:type].eq(BoardGrantEffectuationTask.name))
      .where(assigned_at: id)
      .group("tasks.id")
      .arel
  end
  
```
Here's the union version of this query. It's a bit faster but not by a significant margin whatsoever. It does clean up some of the where clause logic and will exactly mimic the original query even for no request issues even if that isn't a likely scenario. You can decide what to do after playing around with it

2022-12-20 18:54 UTC, TylerBroyles commented on app/models/concerns/decision_review_tasks_concern.rb
> +    union_query = Arel::Nodes::Union.new(
```suggestion
     appeals_query = if FeatureToggle.enabled?(:board_grant_effectuation_task, user: :current_user)
                                   Arel::Nodes::Union.new(appeals_on_request_issues, board_grant_effectuation_tasks)
                                 else
                                   appeals_on_request_issues
                                 end

    union_query = Arel::Nodes::Union.new(
```
Then based on the union query you could handle the feature toggle in here or elsewhere to just add one additional union for the board effectuation grant tasks. Then you can remove the board grant constraint and the additional where clause logic for all of the queries. I'm throwing it in here so you can see which you like better. Like I mentioned earlier the difference isn't too extreme. Here are some benchmarks using the Benchmark gem.

Over 1000 iterations
                           User          System        Total            Real
Where version: 4.293778   0.381416   4.675194 (  6.697919)
Union version:  1.727327   0.008100   1.735427 (  1.734830)

Over a single iteration
                           User          System        Total            Real
Where version: 0.009100   0.019873   0.028973 (  0.046698)
Union version:  0.002734   0.000336   0.003070 (  0.003072)

Like I said they are both very quick over a single iteration.

2022-12-20 20:59 UTC, TylerBroyles approved these changes
Looks good to me. I think this is good to be the version of the query that we use for everything going forward.

2023-01-05 02:04 UTC, closed without merging