MattT/APPEALS-12468
department-of-veterans-affairs/caseflow pull request #17888
Opened 2022-12-22 16:28 UTC by ThorntonMatthew

Resolves [APPEALS-12468](https://vajira.max.gov/browse/APPEALS-12468)

# WIP

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2022-12-29 20:12 UTC, ThorntonMatthew commented on app/controllers/concerns/generic_task_pagination_concern.rb
> -  def apply_task_serializer(tasks)
So long, `apply_task_serializer`!

2022-12-29 20:14 UTC, ThorntonMatthew commented on app/views/decision_reviews/show.html.erb
> +      taskFilterDetails: task_filter_details,
These props need to be supplied to the individual task pages since navigating back to the DR queue by either the hyperlink on the Caseflow logo, or by completing a DR task, does a `router.push` to the DR queue table instead of a hard-reload.

2022-12-30 13:30 UTC, ThorntonMatthew commented on app/controllers/concerns/generic_task_pagination_concern.rb
> -  def apply_task_serializer(tasks)
(Cleanup work)

2022-12-30 13:30 UTC, ThorntonMatthew commented on app/controllers/decision_reviews_controller.rb
> +        render json: { message: "Task #{task_id} was updated successfully." }, status: :ok
Cleanup work to allow for completing decision review tasks.

2022-12-30 13:31 UTC, ThorntonMatthew commented on app/models/serializers/work_queue/decision_review_task_serializer.rb
> +      activeRequestIssues: skip_acquiring_request_issues || request_issues(object).active.map(&:serialize)
A small serializer optimization.

2022-12-30 13:32 UTC, ThorntonMatthew commented on app/views/decision_reviews/index.html.erb
> -      inProgressTasks: apply_task_serializer(in_progress_tasks),
Removed the task-related props as they're no longer in use.

2022-12-30 13:32 UTC, ThorntonMatthew commented on client/app/nonComp/actions/task.js
> -            inProgressTasks: formatTasks(response.body.in_progress_tasks),
Tasks are no longer updated via the response from completing a task (QueueTable has that responsibility now) so these task key-pairs have been removed.

2022-12-30 13:34 UTC, ThorntonMatthew commented on client/app/nonComp/reducers/index.js
> -  state.inProgressTasks = formatTasks(serverNonComp.inProgressTasks);
The NonComp reducer no longer receives tasks from the view (.erb file). This unnecessary code has been removed.

2022-12-30 13:36 UTC, ThorntonMatthew commented on spec/controllers/decision_reviews_controller_spec.rb
> -        expect(response_data["in_progress_tasks"]).to eq([])
Tasks are no longer sent in the response after completing a decision review task. The related assertions have been removed from our spec tests. There are newer tests, further down the file, that test the route that tasks are now drawn from in this controller.

2022-12-30 13:36 UTC, ThorntonMatthew commented on spec/factories/supplemental_claim.rb
> +    transient do
Fixes an issue where veterans were not being generated whenever a supplemental claim with a VHA issue was created via a factory.

2022-12-30 13:39 UTC, ThorntonMatthew commented on spec/feature/intake/higher_level_review/edit_spec.rb
> +        expect(page).to have_current_path("/decision_reviews/education", ignore_query: true)
Any expectation that has had `ignore_query: true` added to it was failing due to the new search query parameters that now exist in decision review queue URLs (ex: `?tab=in_progress&page=1`). These search query parameters bear no consequence on these pre-existing tests, so they have been instructed to overlook those. This allows numerous tests to now pass. ✔️

2022-12-30 13:44 UTC, ThorntonMatthew commented
This branch is based off of the branches for #17805, #17858, and #17893 due to its dependencies on those bodies of work. All three (at the time of me writing this) have not yet been merged into our feature branch, and any changes to any of them will need to be reflected in this branch as well.

2023-01-05 22:50 UTC, TylerBroyles requested changes
Looks amazing overall. There's only one small change involving the filter name to make it look exactly the same as production.

2023-01-05 22:50 UTC, TylerBroyles commented on client/app/nonComp/components/NonCompTabs.jsx
> -        tasks={this.props.completedTasks} />
Nice catch on these two properties.

2023-01-05 22:50 UTC, TylerBroyles commented on spec/controllers/decision_reviews_controller_spec.rb
> +      let(:in_progress_tasks) { in_progress_hlr_tasks + in_progress_sc_tasks }
Nice job noticing that this test file did not cover Supplemental Claims.

2023-01-05 22:50 UTC, TylerBroyles commented on spec/models/business_line_spec.rb
> +    context "Filtering by nultiple columns" do
```suggestion
    context "Filtering by multiple columns" do
```

2023-01-05 22:50 UTC, TylerBroyles commented on client/app/nonComp/util/index.js
> +    columnName: 'searchable',
```suggestion
    type: true,
    columnName: 'type',
```
This will make the filter name identical to how it is on production currently.

2023-01-05 23:16 UTC, ThorntonMatthew commented on client/app/nonComp/util/index.js
> +    columnName: 'searchable',
Thank you for pointing this out!

2023-01-05 23:23 UTC, ThorntonMatthew commented on spec/models/business_line_spec.rb
> +  def add_veteran_and_request_issues_to_decision_reviews(tasks)
Not for the HLR and SC tasks. The VRR tasks in the in-progress task tabs tests will still need veterans and request issues added to their appeals, however.

I've removed `add_veteran_and_request_issues_to_decision_reviews` in the `let`s for the HLR and SC tasks.

2023-01-06 15:36 UTC, TylerBroyles approved these changes
Looks great! Really fantastic job on this one.

2023-01-11 23:02 UTC, merged