APPEALS-13122: Created models, migration, factories and updated specs
department-of-veterans-affairs/caseflow pull request #17949
Opened 2023-01-20 22:21 UTC by bvni

Resolves #{github issue number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2023-01-23 22:20 UTC, TylerBroyles requested changes
First pass is good. I think we will need to account for a few more use cases and add some more rails/active record model generation syntax.

2023-01-23 22:20 UTC, TylerBroyles commented on db/migrate/20230112214407_create_membership_requests.rb
> +      t.datetime :closed_at_datetime
```suggestion
      t.datetime :closed_at
```
I don't think the _datetime is necessary

2023-01-23 22:20 UTC, TylerBroyles commented on db/schema.rb
> +    t.bigint "user_id"
I don't know if this should be bigint or integer. It's used as both types in a lot of different tables. Might be a question we need to bring up to the whole development team.

2023-01-23 22:20 UTC, TylerBroyles commented on db/schema.rb
> +    t.string "closed_by_user_id"
This should be an integer since it's a user id association.

2023-01-23 22:20 UTC, TylerBroyles commented on spec/models/membership_request_spec.rb
> +  let(:membership_request) { build(:membership_request) }
I would test the object creation without the factory to verify that it works. MembershipRequest.new and then save the newly created instance variable to test how a real controller would use the object.

2023-01-24 00:39 UTC, bvni commented on db/schema.rb
> +    t.bigint "user_id"
@TylerBroyles It automatically used bigint in the schema.rb. If you see the migration i didnt mention whether it should be int or bigint. it only has `belongs_to :user`

2023-01-24 00:43 UTC, bvni commented on app/models/membership_request.rb
> +  belongs_to :user
so are we going to have 2 more columns added to the table? @TylerBroyles

2023-01-24 00:47 UTC, bvni commented on app/models/membership_request.rb
> +  validates :status, presence: true
i am confused. where did the created_by_user and created_at date fields come. do you mean closed_by_user_id and closed_at fields?

2023-01-24 14:42 UTC, TylerBroyles commented on app/models/membership_request.rb
> +  validates :status, presence: true
Created at comes from the rails helper method t.timestamps in the migration script. It's also present in the schema. I think it's a fine candidate for validation since there should always be a created at time. You can't really create a request without a user/organization  so those are also pretty good candidates for validation on_create.

2023-01-24 14:45 UTC, TylerBroyles commented on app/models/membership_request.rb
> +  belongs_to :user
In the schema there is already a closed_by_user_id so it is present to some degree. However, it needs to be indicated by rails so you get all the necessary reflection code to use active record properly. So there probably needs to be a created_by user and a closed_by or (decision_by) user belongs to statement.

2023-01-24 14:47 UTC, TylerBroyles commented on db/schema.rb
> +    t.bigint "user_id"
Interesting, that's fine. Bigint is probably more future proof and if that is what it generated then I see no problems with it. It will probably be renamed though since there are going to be two fields that are different users when the model change is made.

2023-01-25 21:34 UTC, bvni commented on app/models/membership_request.rb
> +  validates :status, presence: true
created_at time gets assigned automatically when a new record is created. its a rails helper. so, i dont think we need a validation for it. it will be present no matter what if a record is present.

2023-01-25 22:05 UTC, bvni commented on app/models/membership_request.rb
> +  }
made this as default in database. for some reason i kept getting error 

```
rails enum undefined method `each_with_index' for :assigned:symbol

2023-01-25 22:08 UTC, bvni commented on app/models/membership_request.rb
> +  belongs_to :user
Addressed this.

2023-01-25 22:09 UTC, bvni commented on spec/models/membership_request_spec.rb
> +  let(:membership_request) { build(:membership_request) }
this is updated.

2023-01-25 22:29 UTC, TylerBroyles commented on app/models/membership_request.rb
> +  }
It seems like that syntax only works in Rails 6.1+ and that's why it errors. The only way I can think to do it with a model method without that is on the before save hooks and that's not worth it. The database/schema is a fine place to do it.

2023-01-26 00:03 UTC, TylerBroyles requested changes
I think this covers all of our use cases now. I just have a few comments about the migration script and some validation on the status attribute. The spec test is also failing for me I'm not sure why yet. The factory bot definition also needs to be updated to reflect the new key names.

2023-01-26 16:58 UTC, bvni commented on spec/factories/membership_request.rb
> +    closed_at_datetime { Faker::Date.backward }
I guess we should do this, when we actually work on the decided_by task. I will just update the field names for now here.

2023-01-26 16:59 UTC, bvni commented on spec/models/membership_request_spec.rb
> +        expect(membership_request.errors.full_messages).to be_present
now the status is default, we dont even need this. i dont see this happening ever. so this is not required

2023-01-26 17:00 UTC, bvni commented on spec/factories/membership_request.rb
> +    status { "assigned" }
will update this.

2023-01-26 17:05 UTC, bvni commented on db/schema.rb
> +    t.integer "requested_by"
done.

2023-01-26 17:06 UTC, bvni commented on app/models/membership_request.rb
> +  validates :requestor, presence: true
the status is now defaulted to "assigned". so it wont ever be null.

2023-01-26 17:09 UTC, bvni commented on app/models/membership_request.rb
> +  belongs_to :requestor, class_name: "User", foreign_key: :requested_by
in that case what does the following columns are used for `requested_by and decided_by` these will have the ids of the users. unless we want to change the columns to `requested_id and decided_id`

2023-01-26 19:09 UTC, TylerBroyles commented on app/models/membership_request.rb
> +  belongs_to :requestor, class_name: "User", foreign_key: :requested_by
Generally you have keys that reflect the association name. For instance, the migration script generated organization_id for the t.references organization. If the migration generated a key for requestor, it would probably be requestor_id and a bigint based on the foreign key to the user table. I generally don't like to rename foreign keys unless they are specifically different for a good reason.

If the migration script instead said t.references requestor and t.references decider then it would properly create the keys based on what is defined in the model class. If you wanted the same key names, then you could rename the assocations to requested_by and decided_by and not have to list a foreign key in the model. You can do it whatever way you want, I just prefer them to match unless there's a good reason.

2023-01-26 19:23 UTC, bvni commented on spec/models/membership_request_spec.rb
> +        expect(membership_request.errors.full_messages).to be_present
added this validation.

2023-01-26 21:24 UTC, TylerBroyles requested changes
There are still a couple of things. Mostly due to how rails implemented references in the migrations. You have to manually specify the foreign_key attribute to be true to get it to generate.

2023-01-26 23:16 UTC, bvni commented on db/migrate/20230112214407_create_membership_requests.rb
> +      t.integer :requested_by, index: true, comment: "The requestor for this membership"
This makes sense. I always thought that we can only say `t.references` for a table that exists. Thanks for this. I am updating it.

2023-01-27 19:03 UTC, TylerBroyles requested changes
Just a couple of comment changes to clarify some of the meaning of the database columns.

2023-01-27 19:03 UTC, TylerBroyles commented on db/migrate/20230126230602_create_membership_requests.rb
> +      t.references :requestor, foreign_key: { to_table: :users }, comment: "The requestor for this membership"
```suggestion
      t.references :requestor, foreign_key: { to_table: :users }, comment: "The User that is requesting access to the organization"
```

2023-01-27 19:03 UTC, TylerBroyles commented on db/migrate/20230126230602_create_membership_requests.rb
> +      t.references :decider, foreign_key: { to_table: :users }, index: false, null: true, comment: "The user who decides the membership_request"
```suggestion
      t.references :decider, foreign_key: { to_table: :users }, index: false, null: true, comment: "The user who decides the status of the membership request"
```

2023-01-27 19:03 UTC, TylerBroyles commented on db/migrate/20230126230602_create_membership_requests.rb
> +      t.datetime :decided_at, comment: "The time when the membership request was decided at"
```suggestion
      t.datetime :decided_at, comment: "The date and time when the deider user made a decision about the membership request"
```

2023-01-27 19:10 UTC, TylerBroyles submitted a review, later dismissed
Looks good to me. Great job!

2023-01-30 20:49 UTC, ajspotts approved these changes

2023-01-30 20:50 UTC, merged