APPEALS-12726 - DB Creation Updates
department-of-veterans-affairs/caseflow pull request #17994
Opened 2023-01-27 21:02 UTC by KiMauVA

Resolves #{12726}

### Description
Migrations for new DB table  "cavc_remands_appellant_substitutions".  Includes Foreign Keys from AC and FK validations.

### Acceptance Criteria
- [X] Code compiles correctly

### Testing Plan
1. Go to ...
TBD

### Database Changes
*Only for Schema Changes*

* [X] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [X] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [X] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [X] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [?] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [X] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [X] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [?] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [?] Post this PR in #appeals-schema with a summary
* [X] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

2023-02-01 16:59 UTC, kristeja requested changes
@KiMauVA  Where are we storing the boolean data for the new question "Is there a substitute appellant?"

2023-02-01 16:59 UTC, kristeja commented on db/migrate/20230125153945_create_cavc_remands_appellant_substitutions_table.rb
> +      t.datetime   :updated_at, comment: "Timestamp when substitution was changed"
@KiMauVA  instead of adding created_at and updated_at manually you can just use `t.timestamps` that creates both created_at and updated_at. so you can get rid of line 10 and 11 and just add `t.timestamps` to the migration.

2023-02-02 16:20 UTC, KiMauVA commented on db/migrate/20230125153945_create_cavc_remands_appellant_substitutions_table.rb
> +      t.datetime   :updated_at, comment: "Timestamp when substitution was changed"
Updated with additional boolean and cleaned up the _created_at_ and _updated_at_ columns by just using the **t.timestamps** call instead.

2023-02-03 15:04 UTC, KiMauVA commented
> @KiMauVA Where are we storing the boolean data for the new question "Is there a substitute appellant?"

There's a new column called "appellant_is_substituted" that holds a boolean value for whether the appellant is currently substituted or not.

2023-02-15 03:14 UTC, merged