APPEALS-13125: Cancel membership request and notify requestors
department-of-veterans-affairs/caseflow pull request #18199
Opened 2023-03-08 12:58 UTC by bvni

Resolves #{[13125](https://vajira.max.gov/browse/APPEALS-13125)}

### Description
When a user is added in team management page and if the user has existing membership requests, then the membership requests will get canceled and they are notified with approval emails from [APPEALS-13136](https://vajira.max.gov/browse/APPEALS-13136) and [APPEALS-13138](https://vajira.max.gov/browse/APPEALS-13138)

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Login into case flow
2. search for user camo admin
3. Then select the `VHA CAMO team management` option from the top corner dropdown
4. Now add a user that has membership request.
5. The membership request will be canceled and the users are notified with approval emails from [APPEALS-13136](https://vajira.max.gov/browse/APPEALS-13136) and [APPEALS-13138](https://vajira.max.gov/browse/APPEALS-13138)

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

### Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Post this PR in #appeals-schema with a summary
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2023-03-08 13:14 UTC, bvni commented on app/mailers/membership_request_mailer.rb
> +    @requested_groups = ""
Can you point me to the table/column where i can pull this data from.

cc: @ajspotts @TylerBroyles

2023-03-08 19:05 UTC, ajspotts commented on app/mailers/membership_request_mailer.rb
> +    @requested_groups = ""
@bvni I think we would need to reference a few areas:

- `requesting_org_name`: we have an `organization` [association](https://github.com/department-of-veterans-affairs/caseflow/blob/b1568e29e28734c83039e6d7db32081d7d00da99/app/models/membership_request.rb#L4) on the `MembershipRequest` model, so you should be able to call `membership_request.organization.name` to retrieve that
- `accessible_groups`: we also have an `organizations` [association](https://github.com/department-of-veterans-affairs/caseflow/blob/b1568e29e28734c83039e6d7db32081d7d00da99/app/models/user.rb#L14) on the `User` model, so once you have the user you should be able to just call `user.organizations` to retrieve an array of the orgs that the user is a member of
- `requested_groups`: we also now have a `membership_requests` [association](https://github.com/department-of-veterans-affairs/caseflow/blob/b1568e29e28734c83039e6d7db32081d7d00da99/app/models/user.rb#L15) on the User model as well, so similarly you should be able to call `user.membership_requests` to retrieve those

2023-03-15 19:02 UTC, TylerBroyles requested changes
Here's some quick changes that will fix the tests and some other comments.

2023-03-15 19:02 UTC, TylerBroyles commented on client/app/queue/OrganizationUsers.jsx
> +        membershipRequests: this.state.membershipRequests.filter((mr) => parseInt(mr.userId) !== parseInt(value.id)),
Linting error fix. parseInt needs a base. I'm not sure it's necessary to cast it as an integer however since it should be the same value in both instances.

```suggestion
        membershipRequests: this.state.membershipRequests.filter((mr) => parseInt(mr.userId, 10) !== parseInt(value.id, 10)),
```

2023-03-16 15:46 UTC, TylerBroyles requested changes
I left a few more suggestions, mostly just some cleanup of additional code that isn't used in the test. We will figure out the email logic after this round of changes.

2023-03-16 15:46 UTC, TylerBroyles commented on app/models/organization.rb
> +    user.membership_requests.where(organization_id: id).each do |membership_request|
We only care about cancelling the pending requests, which is requests that have a status of "assigned". Ideally. I think that there should only ever be 1 pending request for a user for a specific org (I added an index to support that idea), but I think doing .each here instead of .first or find_by is probably fine. 
```suggestion
    user.membership_requests.where(organization_id: id).assigned.each do |membership_request|
```

2023-03-16 15:46 UTC, TylerBroyles commented on app/models/organization.rb
> +      MembershipRequestMailer.vha_business_line_approval(membership_request).deliver_now
Yeah that's going to be a bit tricky, we might need to pull in that mailer method from 13136/13138 or make a new one for cancelling which uses the existing approval method from that story.

2023-03-16 15:46 UTC, TylerBroyles commented on spec/models/organization_spec.rb
> +        expect(membership_request.status).to eq 'cancelled'
```suggestion
        expect(membership_request.status).to eq "cancelled"
```

2023-03-16 15:46 UTC, TylerBroyles commented on spec/models/organization_spec.rb
> +    context "without membership_requests" do
You don't need this additional context since it doesn't do any setup and it's behavior should be the exact same as it was before this story.

2023-03-16 15:46 UTC, TylerBroyles commented on spec/models/organization_spec.rb
> +          requestor_id: user.id,
You don't have to give it the requestor id since, you are calling it with user.membership_requests. It already knows the user
```suggestion
```

2023-03-16 15:46 UTC, TylerBroyles commented on spec/models/organization_spec.rb
> +          organization_id: org.id
```suggestion
          organization: org
```

2023-03-16 15:46 UTC, TylerBroyles commented on spec/models/organization_spec.rb
> +        subject
```suggestion
```

2023-03-16 15:46 UTC, TylerBroyles commented on client/app/queue/OrganizationUsers.jsx
> +        membershipRequests: this.state.membershipRequests.filter((mr) => parseInt(mr.userId, 10) !== parseInt(value.id, 10)),
I don't think you need parseInt here. I don't see any reason why this filter function should be any different from the remaningUsers filter right above it.
```suggestion
        membershipRequests: this.state.membershipRequests.filter((request) => request.userId !== value.id),
```

2023-03-16 15:46 UTC, TylerBroyles commented on app/models/organization.rb
> +      membership_request.cancelled!
I think we should push the cancellation logic and emailing logic down to the membership_request model class. The cancellation is simple enough that it can be done here, but I think the email logic is a bit too specific to be in the organization class so I think pushing both down would be preferable.
Something like:
`membership_request.cancel_and_email`
or
`MembershipRequest.cancel_and_send_email`

We can figure out that after this round of changes though.

2023-03-16 23:58 UTC, bvni commented on client/app/queue/OrganizationUsers.jsx
> +        membershipRequests: this.state.membershipRequests.filter((mr) => parseInt(mr.userId, 10) !== parseInt(value.id, 10)),
we need this. I tested this without parseint, it failed. One is coming in string format, other is coming in integer format. so they are not matching and its not filtering the record from the ui after adding the user.

2023-03-17 00:17 UTC, bvni commented on client/app/queue/OrganizationUsers.jsx
> +        membershipRequests: this.state.membershipRequests.filter((mr) => parseInt(mr.userId, 10) !== parseInt(value.id, 10)),
another option is to update the serializer to send the userId in string format. so we can do `.to_s` and remove it here. let me know what you think.

2023-03-17 16:33 UTC, TylerBroyles commented on client/app/queue/OrganizationUsers.jsx
> +        membershipRequests: this.state.membershipRequests.filter((mr) => parseInt(mr.userId, 10) !== parseInt(value.id, 10)),
Hmm. It does seem to be an integer. We can just leave the parse int in then. The user that is added is serialized with the standard json return vs a fast json serializer like we are using and it seems to send id as a string rather than an integer.

2023-03-17 22:05 UTC, TylerBroyles approved these changes
Looks good to me.

2023-03-20 19:47 UTC, merged