Appeal-19614: Adding assigned, in_progress and completed predocketed …
department-of-veterans-affairs/caseflow pull request #18421
Opened 2023-04-04 14:58 UTC by pamatyatake2

…caseflow VhaCamo

Resolves  [Appeal-19614](https://vajira.max.gov/browse/APPEALS-19614)

### Description
Added Seeds for populating VhaCamo Organization queue to have 5 of each: 
  - Assigned
  - In Progress
  - Completed
- added 3 new methods to seeds/tasks.rb 
- added 1 new method to factories/task.rb

### Acceptance Criteria
- [ ] Code compiles correctly
- [ ] vha-camo should have pre-populated queues in all 3 tabs when switched to organization view.
- [ ] 
### Testing Plan
1. Switch user to be either CAMOUser or CAMOADMIN 
2.  Go to /organizations/vha-camo
3.  All three tabs should have task prepopulated.
4. When clicking on the Case Detail link all task should be redirected to the detail page. 

![image](https://user-images.githubusercontent.com/122557351/229832291-91c36bc2-ff59-4c5c-bf1a-d3e947235e3d.png)

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

2023-04-11 15:20 UTC, seancva requested changes

2023-04-11 15:20 UTC, seancva commented on db/seeds/tasks.rb
> +    def create_task_at_quality_review
This method is also defined on line 549

2023-04-11 16:30 UTC, pamatyatake2 commented on db/seeds/tasks.rb
> +        create(:vha_document_search_task,assigned_to: VhaCamo.singleton)
fixed

2023-04-12 15:28 UTC, seancva requested changes
There are no on hold appeals for the VHA Program Offices

2023-04-12 15:40 UTC, seancva requested changes
There is only 1 appeal in the Assigned tab for each of the VHA regional offices. There should be at least 5 in each of the tabs: Assigned, In Progress, On Hold, Completed for all of the 18 VHA Regional Offices
[Link to story](https://vajira.max.gov/browse/APPEALS-19623)

2023-04-12 16:54 UTC, seancva requested changes
According to this [jira ticket](https://vajira.max.gov/browse/APPEALS-19624), these users should be added to the VHA business line: VHAPOADMIN, VHAPOUSER, VISNADMIN, VISNUSER

2023-04-19 16:02 UTC, seancva approved these changes
LGTM

2023-04-28 19:40 UTC, closed without merging