Hotfix/appeals 15446
department-of-veterans-affairs/caseflow pull request #18547
Opened 2023-05-03 14:56 UTC by pamatyatake2

Resolves [APPEALS-15446](https://vajira.max.gov/browse/APPEALS-15446)

# Description
1. In Disposition Component, passed the expected format for decisionDate. 
2. Added a feature test `decision_review_spec.rb` 
3. Added a jest test to test `formatDateStrUtc` method
4. Added a StoryBook For in-process and completed TaskPage Component.

## Acceptance Criteria
- [x] Code compiles correctly
- [x] Decision dates appear in the decision date input field whenever visiting the task page for a completed decision review task.
- [x] Test coverage is added to protect against regressions
- [x] A storybook file for the TaskPage component is created that shows the Disposition child component.
## Testing Plan
1.  goto decision_reviews/vha
2.  Create  High level or supplemental Claim using intake new form button.
3.  search for veteran by id 
4.  select **Veterans health administrator** as benefit type, select other options and then click on continue. 
5.  on Add/Remove issue page, click on Add Issue button and  fill up necessary fills in the Modal. 
6. Click Next and then click **Establish Supplemental/HighLevel claim** button .
7. You should be redirected to decision_reviews/vha page with a new claim in in progress tab. 
8. Open the newly created claim from In Progress Tab.
9. Select Option in Disposition Dropdown, fill in Decision Description text area
10. Select Date in Date selector "remember the date", click on complete button. 
11. You Should be redirected to completed tab.
12. Click on the latest claim that you just completed. and scroll down to the button
13. You should see the date you selected in 10 to be present there as a read only option. 

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---
![image](https://user-images.githubusercontent.com/122557351/235724579-aa40d7f3-6e10-4883-ab67-75aefded1343.png)|![image](https://user-images.githubusercontent.com/122557351/235724937-453db3c3-ebdc-4399-83f7-052b12fb81bb.png)

## Storybook Story
*For Frontend (Presentationa) Components*
* [x] TaskPage.stories.js
* [x] TaskPage/Completed High Level Claims
* [x] TaskPage/In Progress High Level Claims

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [x] RSpec
- [x] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

2023-05-03 17:26 UTC, TylerBroyles requested changes
Great job! I only have a couple of comments.

2023-05-03 17:26 UTC, TylerBroyles commented on spec/feature/non_comp/decision_review_spec.rb
> +feature "Decision Review Task Page", :postgres do
Should these feature tests be a part of the dispositions_spec.rb file?

2023-05-03 17:26 UTC, TylerBroyles commented on client/app/nonComp/pages/TaskPage.stories.js
> +
```suggestion

```

2023-05-03 17:26 UTC, TylerBroyles commented on client/app/nonComp/components/Disposition.jsx
> +      decisionDate = formatDateStrUtc(appeal.decisionIssues[0].approxDecisionDate, 'YYYY-MM-DD');
I wonder if it is worth it to go update the DateSelector.jsx file to change the placeholder text to match 'YYYY-MM-DD' since it doesn't actually work with 'MM/DD/YYYY'?

2023-05-03 19:13 UTC, pamatyatake2 commented on client/app/nonComp/pages/TaskPage.stories.js
> +
removed

2023-05-03 19:14 UTC, pamatyatake2 commented on client/app/nonComp/components/Disposition.jsx
> +      decisionDate = formatDateStrUtc(appeal.decisionIssues[0].approxDecisionDate, 'YYYY-MM-DD');
Per Slack conversation, we do not need to worry about Placeholder since the display is in MM/DD/YYYY

2023-05-03 19:21 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2023-05-15 17:06 UTC, craigrva approved these changes
LGTM

2023-05-18 17:19 UTC, merged