TYLERB/APPEALS-16541: Ability to Filter with the Issue Type Column in Conventional Queues
department-of-veterans-affairs/caseflow pull request #18626
Opened 2023-05-19 16:14 UTC by TylerBroyles

Resolves [APPEALS-16541](https://vajira.max.gov/browse/APPEALS-16541)
Also Resolves [APPEALS-16539](https://vajira.max.gov/browse/APPEALS-16539)

# Description
Added the ability for a Caseflow user, to sort/filter the Issue Type(s) in the queue when processing a claim. It does this through the cached_appeals_table so this also updates the CachedAppealsService. Also added the ability to preserve a filter through page loads and across multiple tabs in queue.

## Acceptance Criteria
- [ ] Issue Type Filtering
  - [ ] Issue filter options counts
  - [ ] Filtering by options
    - [ ] Option with '|' in it
    - [ ] Two issue type options at the same time
    - [ ] Multiple different filters e.g. issue type and task type
  - [ ] Verify issue type filtering in Vha Camo queue and tabs
  - [ ] Verify issue type filtering in Vha Caregiver queue and tabs
  - [ ] Verify issue type filtering in Vha Program offices queue and tabs
 
- [ ] Issue Type Sorting
  - [ ] Issue type sorting ascending
  - [ ] Issue type sorting descending
  - [ ] Issue type sorting in all of the Vha Camo queue and tabs
  - [ ] Issue type sorting in all of the Vha Caregiver queue and tabs
  - [ ] Issue type sorting in all of the Vha program office queue and tabs
- [ ] Filter Preservation
  - [ ] Filter is preserved through page reloading
  - [ ] Filter is preserved between tabs
  - [ ] Filter is preserved when going between case details and the queue
  - [ ] Filter is preserved in Camo, Caregiver, and Program office queues and tabs 

## Testing Plan
1. Go to #{jira issue link} or list them below
2. Data setup
```ruby
```

3. Login as the CAMOADMIN user
4. Visit the camo queue through the ui or through the url /organizations/vha-camo
5. 

# Backend
## Database Changes
*Only for Schema Changes*
* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-06-05 14:32 UTC, csheepy requested changes

2023-06-05 16:08 UTC, csheepy commented on spec/models/organizations/vha_caregiver_support_spec.rb
>          it "VHA CSP organization queue tabs have 8 columns by default" do
```suggestion
        it "VHA CSP organization queue tabs have 9 columns by default" do
```

2023-06-05 16:19 UTC, csheepy submitted a review, later dismissed

2023-06-09 14:29 UTC, ajspotts approved these changes

2023-06-09 14:33 UTC, merged