SeanC/APPEALS-18736 Navigation for Veterans Health Administration Decision Review Queue Link
department-of-veterans-affairs/caseflow pull request #18641
Opened 2023-05-23 17:18 UTC by seancva

Resolves [APPEALS-18736](https://vajira.max.gov/browse/APPEALS-18736)
And is liked to [this PR in the frontend-toolkit repo](https://github.com/department-of-veterans-affairs/caseflow-frontend-toolkit/pull/102)

# Description
Added a link to the switch product navigation drop down menu for VHA decision review queue

## Acceptance Criteria
- [X] Code compiles correctly
- [X] When user selects the Veterans Health Administration Decision Review Queue menu option from the drop-down menu navigation, they will be directed to the VHA Decision Review Queue page.
- **If the user selects ‘VHA Decision Review Queue’ menu option:**
  - [X] While currently on an Individual Decision Review page, they will be returned to ‘Reviews needing action – In Progress’ page.
  - [X] While on the main VHA Decision Review Queue landing page, the page will refresh the ‘Reviews needing action – In Progress’ page.
- [X] If a user selects a menu navigation option, there will be no modals displayed if a user has entered data to the screen unless they select a ‘Cancel’ link related to their current process.
- [X] The DR queue link should only appear for VHA users who are members of the VHA business line.

## Testing Plan
1. Go to #{jira issue link} or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [X] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentationa) Components*
* [X] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [X] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-05-24 19:49 UTC, TylerBroyles requested changes
Good job. I left a couple of comments. The testing plan also needs to include the make client-install command.

2023-05-24 19:49 UTC, TylerBroyles commented on app/controllers/application_controller.rb
> +  def decision_reviews_vha
```suggestion
  def decision_reviews_vha_url
```

2023-05-24 19:49 UTC, TylerBroyles commented on spec/feature/switch_apps_spec.rb
> +        expect(page).to have_link(vha_user_links[1][:title], href: vha_user_links[1][:link], exact: true)
I think there should be at least one negative test. A user that is not VHA should not see the decision review link. This type of test could be added for intake as well.

2023-05-25 16:37 UTC, craigrva requested changes

2023-05-25 16:37 UTC, craigrva commented on spec/feature/switch_apps_spec.rb
> +    end
We should roll as many of these scenarios as possible into a single test run to reduce how long it takes to run the tests. Keeping all of the expectations is fine and we can add a comment with each one describing what the scenario currently says.

2023-05-25 16:37 UTC, craigrva commented on spec/feature/switch_apps_spec.rb
> +    end
Same as the comment above, roll as many of these scenarios into a single test as possible

2023-06-07 20:15 UTC, craigrva approved these changes

2023-06-07 20:16 UTC, merged