Tier 4 Automate Remediation Steps for Veteran Name
department-of-veterans-affairs/caseflow pull request #18651
Opened 2023-05-24 17:26 UTC by dmage20

Resolves #{jira issue link}

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan
1. Go to #{jira issue link} or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-05-24 20:10 UTC, jcroteau reviewed
Great job on this so far! I'm glad that you and Drew get to scout out this strange new land before I do (while I'm awaiting access to everything) 😄 

I don't have as much context yet as Noelle or others who have been on the project for a while, but I raised a few questions and suggestions.

Additionally, I didn't see very many tests in `/spec/lib/helpers` for the other scripts, but this might be a good opportunity to start expanding test coverage. Not sure what your comfort-level is with RSpec, but if you wanted any help with that, I'd be happy to pair with you on it 😃

2023-05-24 21:27 UTC, NoelleAd commented on lib/helpers/veteran_name_updater.rb
> +      end
Because there's only one update happening in this code clock it may be the case that this doesn't need to be wrapped in a transaction. It could probably be removed at Nate's discretion.

2023-05-24 21:29 UTC, NoelleAd commented on lib/helpers/veteran_name_updater.rb
> +    puts "#{veteran.first_name} #{veteran.middle_name} #{veteran.last_name}"
I think the console will show the veteran's name in the log either way. It makes it easier for Tier3 to validate the changes against VBMS after they run the script, but I'd differ to @nkutub and @jshields13

2023-05-24 21:40 UTC, NoelleAd commented on lib/helpers/veteran_name_updater.rb
> +      end
```
def update_cached_attributes!
    CACHED_BGS_ATTRIBUTES.each do |local_attr, bgs_attr|
      fetched_attr = bgs_record[bgs_attr]
      if bgs_attr == :date_of_death && fetched_attr.present?
        fetched_attr = begin
                         Date.strptime(fetched_attr, "%m/%d/%Y")
                       rescue ArgumentError
                         nil
                       end
      end
      self[local_attr] = fetched_attr
    end
    self.bgs_last_synced_at = Time.zone.now
    save!
  end
```
  
  is defined in /caseflow/app/models/veteran.rb
I think my original concern was if some of the attributes got updated in the 'each do' and then it failed before updating all of them. However, that may not be a real problem.

2023-05-25 03:21 UTC, jcroteau commented on lib/helpers/veteran_name_updater.rb
> +      end
>I think my original concern was if some of the attributes got updated in the 'each do' and then it failed before updating all of them. However, that may not be a real problem.

I agree that it won't be a problem here, since the attributes are merely being assigned during each iteration but are not persisted until the `save!` at the end, after the block is finished.

2023-05-25 03:57 UTC, jcroteau commented on lib/helpers/veteran_name_updater.rb
> +    puts "#{veteran.first_name} #{veteran.middle_name} #{veteran.last_name}"
I guess there may not be an issue with printing / logging of the veteran's name, per se, as long as the event is being audit logged appropriately for HIPAA compliance. I'm not yet familiar with how HIPAA audit logging is handled on this project. A preliminary code search of the `caseflow` repo didn't turn up anything obvious, but maybe it's being handled at the infrastructure level some how...

2023-05-25 21:03 UTC, jcroteau commented on lib/helpers/veteran_name_updater.rb
> +    puts "#{veteran.first_name} #{veteran.middle_name} #{veteran.last_name}"
Moved discussion to [Slack thread](https://benefits-int-delivery.slack.com/archives/C03ML6AG7V3/p1685048239541189).

2023-05-26 17:32 UTC, jcroteau commented on lib/helpers/veteran_name_updater.rb
> +    puts "#{veteran.first_name} #{veteran.middle_name} #{veteran.last_name}"
According to @jshields13 ([Slack thread](https://benefits-int-delivery.slack.com/archives/C03ML6AG7V3/p1685117567313669?thread_ts=1685048239.541189&cid=C03ML6AG7V3)):

>I see no issue putting PI printed out to the console as long as its stored properly if we keep it like copy pasting

So I guess we can keep with the status quo here for now.

I will take it as a task to look into HIPAA audit logging and whether it has implications for us on these SOP scripts.

2023-06-02 17:34 UTC, jcroteau requested changes
Left a few thoughts, which I'd also like @NoelleAd and/or @nkutub to weigh in on.

@dmage20 -- let me know if you'd like to have a huddle to discuss any of these things further.

2023-06-02 17:34 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +  class PersonNameUpdater
Based on the code you have here so far, and my lack of access to the JIRA ticket, I'm still unsure what the need is for updating a `Person` record. It does appear that there is some kind of relationship between `Veteran` and `Person`, but I'm not totally clear on what that is.

@NoelleAd or @nkutub , do you have any background on the relationship between `Veteran` and `Person`?

There isn't a formal ActiveRecord association between these two models, but I can see that both `Veteran` and `Person` have a `participant_id` (which could be used to link them), and also see there is a method [`Veteran #person`](https://github.com/department-of-veterans-affairs/caseflow/blob/533ceb3e9eacfd1571902dbb0b3a5c3cf92ec0fa/app/models/veteran.rb#L76-L78), which finds or creates a `Person` with the same `participant_id`.

If the domain model is that all `Veteran`s are `Person`s, and every `Veteran` record must have a `Person` record which is also in sync with BGS, then I'd say we should instead delegate to [`Person.find_or_create_by_participant_id`](https://github.com/department-of-veterans-affairs/caseflow/blob/ba0bf08c4d836e25b0a69889ad3c0e488a6b4f24/app/models/person.rb#L23-L32) instead of replicating any of that business logic here.

2023-06-02 17:34 UTC, jcroteau commented on lib/tasks/remediation.rake
> +  task :update_veterans_name, [:file_number] => :environment do |_task, args|
💡 Maybe something like the following (since we're updating more than just the name)?

```suggestion
  desc "Sync Veteran record with BGS"
  task :veteran_sync_with_bgs, [:file_number] => :environment do |_task, args|
```

2023-06-02 17:58 UTC, dmage20 commented on lib/helpers/manual_remediation.rb
> +  class VeteranNameUpdater
- In that case then the name would be something more like VeteranCachedAttributesUpdater because that is what it will do. That seems like a mouth full. I think for short the name you suggest works well. 
- For the person method because of how that model's update_cached_attibutes! only works when the field is `nil` I had to explicitly update and I only included the names. so for naming PersonSyncNameWithBGS could work

2023-06-02 19:02 UTC, dmage20 commented on lib/helpers/manual_remediation.rb
> +      end
testing in UAT with `Veteran.send(:find_by_file_number_and_sync, "file_number")`
it does work to align bgs with caseflow. If we could execute that way in the scrip to bypass "private" or make it a public method as you say JC

2023-06-02 19:06 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +  class VeteranNameUpdater
>For the person method because of how that model's update_cached_attibutes! only works when the field is nil I had to explicitly update and I only included the names.

🤔 Hmmm, I guess I'm not following. Can you elucidate?

2023-06-02 19:14 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +      end
If we're going to use that method, we definitely need to make it public. It's best to respect the privacy of `private` methods. When a method is private, it communicates to other developers that it's not being called outside of that class, and so it can be changed without regard to external callers. Making it public also encourages that method to be tested and for its interface to be stable, since it is being used elsewhere.

2023-06-04 19:38 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +  class VeteranNameUpdater
> > For the person method because of how that model's update_cached_attibutes! only works when the field is nil I had to explicitly update and I only included the names.
> 
> 🤔 Hmmm, I guess I'm not following. Can you elucidate?

Ahhh, okay. I see what you're saying. So [`Person #update_cached_attributes!`](https://github.com/department-of-veterans-affairs/caseflow/blob/ba0bf08c4d836e25b0a69889ad3c0e488a6b4f24/app/models/person.rb#L99-L104) calls `AssociatedBgsRecord #cached_or_fetched_from_bgs`, which performs a [conditional assignment](https://github.com/department-of-veterans-affairs/caseflow/blob/067a40e991e30f9f9b86c19eafd21231d41aa58b/app/models/concerns/associated_bgs_record.rb#LL96C30-L96C30) on the field, and thus will always save the currently cached value of the field if it is present. I had glossed over that on my first reading.

Well, that throws a wrench in things. This is definitely a departure from how [`Veteran #update_cached_attributes!`](https://github.com/department-of-veterans-affairs/caseflow/blob/533ceb3e9eacfd1571902dbb0b3a5c3cf92ec0fa/app/models/veteran.rb#L341-L355) works, which "busts the cache" on BGS attributes. 

I wonder if the way `Person #update_cached_attributes!` works is intentional or is a kind of "bug"? And this hints at a bigger question for me, which is how should data consistency between `Veteran`, `Person`, and BGS work ideally? And are we just putting band-aids over a bigger problem which needs to be properly addressed by the appropriate ART?

Whatever the case, I think that the logic for "cache-busting" BGS attributes on `Person` should probably reside in the `Person` model, alongside `#udpate_cached_attributes`, instead of in our little SOP script here, as it is core to the behavior of the `Person` model.

Let's open this up to the rest of the team.

CC: @raymond-hughes , @nkutub , @NoelleAd

2023-06-04 19:42 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +  class PersonNameUpdater
Also, see related discussion on current behavior of BGS attribute caching on `Person` [here](https://github.com/department-of-veterans-affairs/caseflow/pull/18651#discussion_r1217045014).

2023-06-04 21:44 UTC, nkutub commented on lib/helpers/manual_remediation.rb
> +  class VeteranNameUpdater
@jcroteau , these are good questions but I think are out of scope of this code review.

2023-06-04 21:48 UTC, nkutub commented on lib/helpers/manual_remediation.rb
> +      end
I agree, what we could also do is create a new public method on the class that calls the private method if we don't want to mess with the original method. but again for the scope of what we are doing , if you look at many of the remediation scripts, they are using the "send" to private methods. so with that said lets keep the scope of this code review to only address the remediation given the existing practice. We can log a new initiative to clean up all our send methods . I want to contain the risk by modifying the lowest number of lines of code given a remediation task.

2023-06-04 21:50 UTC, nkutub commented on lib/helpers/manual_remediation.rb
> +    def run_by_file_number(file_number)
I prefer the original

2023-06-04 21:53 UTC, nkutub commented on lib/helpers/manual_remediation.rb
> +  class PersonNameUpdater
I don't think this is related to this code review but more a training and knowledge question in general , this conversation should be moved to slack or wiki we can reference in future.

2023-06-05 14:26 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +  class VeteranNameUpdater
@nkutub 
>@jcroteau , these are good questions but I think are out of scope of this code review.

How so? (Not trying to be combative, just genuinely curious. I will admit that I'm kind of flying blind here, as I don't have access to the Jira story, nor have I been a part of the initial huddle conversations around this work.)

2023-06-05 14:50 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +      end
@nkutub 

>if you look at many of the remediation scripts, they are using the "send" to private methods

😢 

>so with that said lets keep the scope of this code review to only address the remediation given the existing practice. We can log a new initiative to clean up all our send methods . I want to contain the risk by modifying the lowest number of lines of code given a remediation task.

I'm totally sympathetic to minimizing scope / risk, however I think a line has to be drawn in the sand at some point on `send`-ing to private methods, and I don't see why that line shouldn't be drawn here. If this remediation were just a one-off thing which is guaranteed to only ever going to be used a handful of times, I supposed I could turn a blind eye.

>I want to contain the risk by modifying the lowest number of lines of code given a remediation task.

I'm with you. However, I do think sliding method `Veteran.find_by_file_number_and_sync` above the `private` keyword is pretty low risk. It is being called by several other class methods, which have tests on them, so that contains the risk, in my mind.

2023-06-05 15:01 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +  class PersonNameUpdater
@nkutub 
>I don't think this is related to this code review

I very respectfully disagree. As an impartial reader of this code, and the code it is related to (namely, the `Veteran` and `Person` models), I am not clear on the need for it or its intended use. That is not Daniel's fault. The relationship between `Veteran` and `Person` is ill-defined by those two models. If it requires "training" to understand that relationship, then that is a sign there is a deficiency in the code on those models.

I realize that adding an ActiveRecord association between these models is out of scope for this PR, and it is not what I'm calling for. But at a minimum, we should add some clarifying comments to our code here to educate the reader (so as to avoid the need for "training"). In order to add comments though, we need to have a clear understanding of that relationship.

2023-06-05 18:58 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +      end
So I spoke with Grant (Lowell Lewis) about making [`Veteran #find_by_file_number_and_sync`](https://github.com/department-of-veterans-affairs/caseflow/blob/533ceb3e9eacfd1571902dbb0b3a5c3cf92ec0fa/app/models/veteran.rb#L409C9-L431) a public method, and he pointed out that there was already a public method that kind of does the same thing (which I had admittedly overlooked, since its name isn't at all suggestive that it does any syncing)...

[`Veteran .find_by_file_number_or_ssn`](https://github.com/department-of-veterans-affairs/caseflow/blob/533ceb3e9eacfd1571902dbb0b3a5c3cf92ec0fa/app/models/veteran.rb#L375-L382).

If we call this method with kwarg `sync_name: true`, it is essentially the same thing as calling [`Veteran #find_by_file_number_and_sync`](https://github.com/department-of-veterans-affairs/caseflow/blob/533ceb3e9eacfd1571902dbb0b3a5c3cf92ec0fa/app/models/veteran.rb#L409C9-L431).

2023-06-05 19:04 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +  class PersonNameUpdater
I spoke offline with @nkutub about this, and we will raise the question and hopefully get an answer during our meeting tomorrow about the `Veteran` and `Person` relationship.

2023-06-05 19:06 UTC, jcroteau commented on lib/helpers/manual_remediation.rb
> +    def run_by_file_number(file_number)
I'm happy to leave it up to @dmage20 's discretion then.

2023-06-07 18:20 UTC, jcroteau commented on lib/tasks/remediation.rake
> +namespace :manual_remediation do
While pairing w/ Drew, we decided to create our own directory for remediation rake tasks (`lib/tasks/remediations`), to segregate Tier 4 remediations from other rake tasks, so I think it would be good to converge on that. 

If you don't mind, could you create that `lib/tasks/remediations` folder here in this branch (since it may ship before Drew's) and then create a dedicated `.rake` file for this task (`lib/tasks/remediations/veteran_sync_with_bgs.rake`)?  

The `require` in this file would then need to be updated accordingly, and the `namespace` would then need to be changed to `remediations`):

```suggestion
require_relative "../../helpers/veteran_sync_with_bgs"

namespace :remediations do
```

2023-06-12 18:59 UTC, jcroteau requested changes
Looking pretty good! I have a few more change requests and refactoring recommendations. After you incorporate those and update the specs accordingly, I can take a look at the specs.

I am still not sure what is the case for making a separate rake task to sync the `Person` record. Maybe @NoelleAd can chime in on this. Will Tier 3 necessarily know when they need to update a `Person` record? Is there ever a time when `Person` record needs to be synced but a `Veteran` doesn't?

2023-06-12 18:59 UTC, jcroteau commented on spec/lib/tasks/remediations/sync_attributes_with_bgs_spec.rb
> +end
👍

2023-06-13 14:29 UTC, dmage20 commented on lib/helpers/sync_attributes_with_bgs.rb
> +      end
suggestion incorporated into [PR](https://github.com/department-of-veterans-affairs/caseflow/pull/18651/commits/c0ef2b82d4cdca67e4b4b1baa8c978363591ac94)

2023-06-13 14:29 UTC, dmage20 commented on lib/helpers/sync_attributes_with_bgs.rb
> +      end
suggestion incorporated into [PR](https://github.com/department-of-veterans-affairs/caseflow/pull/18651/commits/c0ef2b82d4cdca67e4b4b1baa8c978363591ac94)

2023-06-13 14:29 UTC, dmage20 commented on lib/helpers/sync_attributes_with_bgs.rb
> +      end
suggestion incorporated into [PR](https://github.com/department-of-veterans-affairs/caseflow/pull/18651/commits/c0ef2b82d4cdca67e4b4b1baa8c978363591ac94)

2023-06-13 16:41 UTC, jcroteau reviewed
A couple suggestions on the specs. There are some other conventions that I'd like us to adopt from https://www.betterspecs.org/, but it might be easier to huddle up on this...

2023-06-13 16:41 UTC, jcroteau commented on lib/helpers/sync_attributes_with_bgs.rb
> +    def self.find_by_file_number_or_ssn(file_number)
🪡 Even though we are delegating to `Veteran.find_by_file_number_or_ssn`, I think the method name you had here before was preferable, as it is doing more than just finding a record.

2023-06-15 19:13 UTC, dmage20 commented on spec/lib/helpers/sync_attributes_with_bgs_spec.rb
>          expect(subject).to receive(:puts).with("Veteran Name: Bob  CORRECT")
[request addressed in this commit](https://github.com/department-of-veterans-affairs/caseflow/pull/18651/commits/fb544c36a0575dfbe2f1ab75f0347de8184e0392)

2023-06-15 21:59 UTC, jcroteau approved these changes
👏👏👏 LGTM! Great work on this! I know this first one was a bit of a slog, with plenty of scope creep (and arbitrary nit-picks on my part), but it will get easier as acceptance criteria become more explicit and static and standards more familiar.

Approving with the following caveats:

On the PR Description, it would be good to
- add a link to the related Jira story at the top,
- include some background motivating the need for these rake tasks,
- fix typo in your usage notes -- the namespace should be `remediations` (plural),
- be explicit in your Testing Plan, delineating each scenario and the steps for each. 
  - I've seen other's just link to the Testing Plan in the story, but I would like for us to have the test plan in the PR as well, as the test plan is related to the code, so it should be co-located with it.
  - For a simple example Testing Plan, you can reference [the one in my PR](https://github.com/department-of-veterans-affairs/caseflow/pull/18778#testing-plan).  For your case, I don't think you need separate sections for each environment, but maybe one section for each rake task, and then sub-sections for each scenario ("when veteran with file_number is not found", "when veteran exists", etc), and the steps to manually create the relevant records in VBMS and Caseflow so that you can run the tasks and test them.
- for any sections that got pulled into the PR template that are not relevant (ex. Frontend, Database Changes, Integrations, Monitoring, etc), they can be deleted (or ~~striked out~~)

For PR template checks that are relevant, check the ones that have been satisfied. For those that have not been satisfied, make any code changes necessary and then check them off.

For the Testing Plan, you may want to consult with @NoelleAd on what they usually do to set up data in UAT:
  - ❓ Do we need to create our own Veteran and Person records in VBMS and Caseflow, or should we just find pre-existing records and modify to our needs?

2023-06-21 14:47 UTC, jcroteau commented on lib/helpers/sync_attributes_with_bgs.rb
> +    def run_by_file_number(file_number)
Ah, I missed something in my review. I think we forgot to set the user in the request store here (and also in `PersonCacheUpdater #run_by_participant_id` below:

```ruby
RequestStore[:current_user] = User.system_user
```

2023-06-21 18:10 UTC, dmage20 commented on lib/helpers/sync_attributes_with_bgs.rb
> +    def run_by_file_number(file_number)
comment addressed in [commit](https://github.com/department-of-veterans-affairs/caseflow/pull/18651/commits/bc2dba076ec112962c06b0c0aa9ffd478435a756).

2023-06-21 18:57 UTC, jcroteau commented on lib/helpers/sync_attributes_with_bgs.rb
> +    def run_by_file_number(file_number)
😮 TIL! I've never seen nor used the `self.inherited` callback before.

I'm curious how it works in this case, though, and somewhat skeptical, since the classes nested within `SyncAttributesWithBGS` don't really inherit from it (or do they?).

Despite my skepticism, I think it would be good to add some examples to your specs to ensure that `RequestStore[:current_user] == User.system_user` when each of your methods are run.

2023-06-21 19:01 UTC, dmage20 commented on lib/helpers/sync_attributes_with_bgs.rb
> +    def run_by_file_number(file_number)
yes, they  the code block inside the self.inherited runs once when the any of the classes are created. But I will add a spec for it so that it clear.

2023-06-21 19:06 UTC, jcroteau commented on lib/helpers/sync_attributes_with_bgs.rb
> +    # @param [Boolean] sync_name set to true to update cached attributes.
I don't think we need this param in the comment, since it isn't a parameter of `#run_by_file_number`
```suggestion
```

2023-06-21 19:08 UTC, dmage20 commented on lib/helpers/sync_attributes_with_bgs.rb
> +    # @param [Boolean] sync_name set to true to update cached attributes.
okay noted

2023-06-22 14:57 UTC, jcroteau commented on lib/helpers/sync_attributes_with_bgs.rb
> +  end
Did you mean to remove this?

2023-06-22 14:59 UTC, jcroteau commented on spec/lib/helpers/sync_attributes_with_bgs_spec.rb
> +    end
❤️

2023-06-22 17:01 UTC, dmage20 commented on lib/helpers/sync_attributes_with_bgs.rb
> +  end
oh yes, I had a difficult time with git so this must have ended up getting added again.

2023-06-22 18:48 UTC, jcroteau commented
Thanks for addressing my concerns, @dmage20 !

I looked over the failing CI checks. The `caseflow_lint_job` failure can be ignored -- it's just calling out pre-existing vulnerabilities which are unrelated to your changes here.

For the [`codeclimate` failures](https://codeclimate.com/github/department-of-veterans-affairs/caseflow/pull/18651#), there are two Reek smells which we can ignore by adding a couple magic comments that include `:reek:FeatureEnvy` above the respective class definitions, like so:

```
  # Disable :reek:FeatureEnvy
  class VeteranCacheUpdater

  # [...]

  # Disable :reek:FeatureEnvy
  class PersonCacheUpdater
```

After you make this change, let's see if that makes the `codeclimate` action pass, and then I will re-approve.

2023-06-23 16:46 UTC, jcroteau approved these changes
🎈

2023-07-06 18:13 UTC, merged