b_reed/APPEALS-22837
department-of-veterans-affairs/caseflow pull request #18709
Opened 2023-06-06 18:00 UTC by breedbah

Resolves #{jira issue link}

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan
1. Go to #{jira issue link} or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentationa) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-06-08 20:32 UTC, msteele96 commented
Jira test case needs to be created and linked to this PR. Even if you are blocked by other stories in testing, lay out the steps and hold off on the execution until you are unblocked.

2023-06-08 21:05 UTC, msteele96 commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +      new_table = { table: {  id: 1,
Same question as above about table

2023-06-09 11:19 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +  skip_before_action :verify_authenticity_token, only: [:outcode]
Removed

2023-06-09 11:22 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    render json: { "Errors": ["Message": error_message], "Error UUID": error_uuid }
This gives me an error if I dont include the brackets

2023-06-14 12:45 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    new_response = { "table":
took the table key out, now matches the docs

2023-06-14 20:16 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    render json: { "Errors": ["Message": error_message], "Error UUID": error_uuid }
```suggestion
    render json: { message: error_message + " #{error_uuid}" }
```

I am not sure if we would be anticipating multiple errors in a single response. I could be mistaken, however.

2023-06-14 20:23 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +        render_error(404, "Distribution Does Not Exist At This Time", distribution_id)
Based on some changes with 21123, distributions will now be created prior to being established in Pacman. 

```suggestion
        render_error(404, "A distribution could not be located given the ID provided.", distribution_id)
```

As a result, I think the language should be tweaked a bit so that the client isn't thinking that it's a WIP.

2023-06-14 20:28 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +        render_error(400, "Participant With UUID Not Valid", distribution_id)
For the message here I think we can just pass along the message given to us by Pacman.

2023-06-14 20:36 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    formatted_response
```suggestion
    parsed_response.deep_transform_keys do |key|
      key.to_s.underscore.gsub(/e(\d)/, 'e_\1')
    end
```

2023-06-14 20:38 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +        render_error(404, "Distribution Does Not Exist At This Time", distribution_id)
Oh, I just saw the other 404 up top.

```json
{
  "id": 1234,
  "status": "PENDING_ESTABLISHMENT"
}
```

Something like that may be better here then. We have a record of it, but Pacman doesn't!

2023-06-14 20:44 UTC, ThorntonMatthew commented
![status-code-mismatch](https://github.com/department-of-veterans-affairs/caseflow/assets/99351305/9dfd16f8-4601-402b-a6a6-badf5aeac272)

The HTTP status code in the response doesn't seem to match what is in the response body.

2023-06-14 20:47 UTC, ThorntonMatthew commented
Now that our models are tables are set up, I think it may be good to remove this hardcoded ID check in the service: https://github.com/department-of-veterans-affairs/caseflow/blob/a67844ffd102364df48f2408d91231e6ac5a6917/lib/fakes/pacman_service.rb#L13-L19

2023-06-15 14:17 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    formatted_response
Updated

2023-06-15 14:17 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +        render_error(400, "Participant With UUID Not Valid", distribution_id)
Updated

2023-06-15 14:17 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +        render_error(404, "Distribution Does Not Exist At This Time", distribution_id)
Updated

2023-06-15 15:17 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    # Checks if the distribution id is blank and if it exists with the database
The method that mocks the distribution not found response is a private method within the PacManService.rb fakes so I cant directly call on it within an unless/if statement. I could take off the private restriction within the fakes to call it, and then i would be able to mimick the response. Unless you have a disfferent idea.

2023-06-15 22:47 UTC, ThorntonMatthew commented on lib/fakes/pacman_service.rb
>      end
```suggestion
    def get_distribution_request(distribution_id)
      unless VbmsDistribution.exists?(id: distribution_id)
        return distribution_not_found_response
      end

      fake_distribution_response(distribution_id)
    end
```

2023-06-15 23:21 UTC, ThorntonMatthew requested changes
A few more comments- mostly in the spec file.

2023-06-15 23:21 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +    end
https://rspec.info/features/6-0/rspec-rails/

Sample controller spec test (since the spec type is already marked as `:controller` on L12):
```suggestion
    context "when distribution_id is blank or invalid" do
      let(:distribution_id) { "" }
      let(:error_msg) do
        "[IDT] Http Status Code: 400, Distribution Does Not Exist Or Id is blank," \
          " (Distribution ID: ) #{uuid}"
      end
      let(:uuid) { "a9df0251-8350-464b-9aa4-a7d56a8ac173" }

      it "renders an error with status 400" do
        # Something like this may be necessary to make sure the UUID is predictable
        # if exact matching is desired. It definitely makes things easier!
        #
        # This and the let(:uuid) line could be placed in a higher scope so all error tests can reach it.
        allow(SecureRandom).to receive(:uuid).and_return(uuid)

        get :get_distribution, params: { distribution_id: distribution_id }

        expect(response.code).to eq "400"
        expect(JSON.parse(response.body)).to eq(
          "message" => error_msg
        )
      end
    end
```

This way the test hits everything from the routing, the params being parsed, and the full response and available for inspection in the exact form it will be seen by IDT clients.

2023-06-15 23:21 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +    context "when PacManService fails with a 404 error" do
See above comment

2023-06-15 23:21 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +      allow(SecureRandom).to receive(:uuid).and_return(error_uuid)
I didn't see this whenever I wrote my other comment. 😅

2023-06-15 23:21 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +        get :get_distribution, params: { distribution_id: distribution_id }
I also didn't see this whenever I wrote my first comment in the file. This is solid!

I swear I'm not afraid of the scrollbar.

2023-06-15 23:21 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    # Convert keys from camelCase to snake_case
🐫 💯

2023-06-15 23:21 UTC, ThorntonMatthew commented on lib/fakes/pacman_service.rb
>      end
This resolves a CodeClimate error

2023-06-16 10:52 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +        render_error(response_code, {"id": "#{distribution_id}", "status": "PENDING_ESTABLISHMENT"}, distribution_id)
I apologize, for some reason my rubocop didnt pick this up on my end

2023-06-16 18:57 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +        controller.get_distribution
I think this test could be improved using `get:` like this test: https://github.com/department-of-veterans-affairs/caseflow/blob/191daf6b446571da2ad0bcc95e8eb6c623cff8b4/spec/controllers/idt/api/v2/distributions_controller_spec.rb#L38

2023-06-16 18:57 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +        expect(controller).to receive(:render_error).with(500, error_message, distribution_id)
I think this test could be improved using `get:` like this test also: https://github.com/department-of-veterans-affairs/caseflow/blob/191daf6b446571da2ad0bcc95e8eb6c623cff8b4/spec/controllers/idt/api/v2/distributions_controller_spec.rb#L38

2023-06-16 18:58 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +      controller.send(:render_error, status, message, distribution_id)
I think this test could be improved using `get:` like this test also: https://github.com/department-of-veterans-affairs/caseflow/blob/191daf6b446571da2ad0bcc95e8eb6c623cff8b4/spec/controllers/idt/api/v2/distributions_controller_spec.rb#L38

2023-06-16 18:59 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +      allow(SecureRandom).to receive(:uuid).and_return(error_uuid)
This line can be removed now that it's up in the higher scope.

2023-06-16 19:04 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +      allow(VbmsDistribution).to receive(:exists?).with(id: distribution_id).and_return(true)
```suggestion
```

2023-06-16 19:04 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +      allow(controller).to receive(:params).and_return(distribution_id: distribution_id)
```suggestion
```

2023-06-16 19:06 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +        render_error(response_code, { "id": distribution_id, "status": "PENDING_ESTABLISHMENT" }, distribution_id)
```suggestion
        render json: { id: distribution_id, status: "PENDING_ESTABLISHMENT" }
```
I think for now we can treat this as not necessarily an error.

2023-06-20 18:53 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    render json: { id: distribution_id, response_status: "PENDING_ESTABLISHMENT" }, status: response_code
```suggestion
    render json: { id: distribution_id, status: "PENDING_ESTABLISHMENT" }, status: 200
```

The reason for this suggestion is so that the key name is the same as what is returned whenever a distro is successfully located in Pacman. I also think that we can return a 200 here and not forward the 404 along, as it's not an error.. yet (it will be if we can never establish the distribution remotely).

2023-06-20 18:54 UTC, ThorntonMatthew commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    render json: { id: distribution_id, response_status: "PENDING_ESTABLISHMENT" }, status: response_code
I suppose `response_code` wouldn't need to be a param any longer in this case.

2023-06-20 18:59 UTC, ThorntonMatthew commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +
```suggestion
    context "render_error" do
      let(:status) { 500 }
      let(:message) { "Internal Server Error" }
      let(:distribution_id) { "123456" }

      it "renders the error response with correct status, message, and distribution ID" do
        error_message = "[IDT] Http Status Code: #{status}, #{message}, (Distribution ID: #{distribution_id})"
        expect(Rails.logger).to receive(:error).with("#{error_message}Error ID: #{uuid}")
```

Since the mock for SecureRandom.uuid is on line 23 these parts can be removed to DRY things up.

2023-06-20 20:42 UTC, breedbah commented on app/controllers/idt/api/v2/distributions_controller.rb
> +    render json: { id: distribution_id, response_status: "PENDING_ESTABLISHMENT" }, status: response_code
This m,akes sense

2023-06-20 20:42 UTC, breedbah commented on spec/controllers/idt/api/v2/distributions_controller_spec.rb
> +
updated

2023-06-20 21:39 UTC, ThorntonMatthew approved these changes
LGTM!

2023-06-20 21:39 UTC, merged