APPEALS-23590 - Get Guard working with Spring, RSpec and Rubocop for TDD
department-of-veterans-affairs/caseflow pull request #18715
Opened 2023-06-07 01:12 UTC by jcroteau

Resolves https://jira.devops.va.gov/browse/APPEALS-23590

# Description

> [Guard](https://github.com/guard/guard) is a development tool that automates various tasks, such as running tests, by running custom rules whenever file or directories are modified.
> 
> There is a gem currently installed in the Caseflow project, called `guard-rspec`, which uses Guard to "automatically & intelligently launch specs when files are modified". 
> 
> This can be used during the development process to automate the running of relevant tests while writing code in service of a [Test Driven Development (TDD)](https://en.wikipedia.org/wiki/Test-driven_development) workflow.
> 
> Unfortunately, this gem is not currently working.

This PR aims to accomplish the following items:
- Make `guard-rspec` functional again for Caseflow development.
- Run [RuboCop](https://github.com/rubocop/rubocop) analysis after RSpec tests pass for immediate feedback on code style violations.
- Enable the running of both RSpec and Rubocop with [Spring](https://github.com/rails/spring), a Rails application preloader to speed up development.

## Acceptance Criteria

- `bundle exec guard` should no longer raise an error
- Both RSpec and RuboCop should be able to run with Spring
  - `bundle exec spring rspec`
  - `bundle exec spring rubocop` 
- The `Guardfile` should be set up to enable a "Red-Green-Refactor" workflow with RSpec and RuboCop
- While running, Guard should successfully pick up file change events and run the relevant RSpec tests and RuboCop analysis

## Testing Plan

### Development / Test environment

The following should only be performed in a local development/test environment, as the relevant dependencies are installed only in those environments (should not be in live / production envs).

#### Guard runs without errors
- [ ] In the Caseflow app root directory, run `bundle exec guard` and ensure no errors are raised.

#### Running Guard starts the Spring server
- [ ] In a separate terminal, from the Caseflow app root directory, run `bundle exec spring status` and confirm that it reports that Spring is running.

#### Guard runs RSpec test suite
- [ ] Back at the Guard prompt, hit the `Enter` key and confirm that specs start running. This will run the entire test suite if you let it.
- [ ] Stop the test runner by hitting `ctrl-C` (this might require repeatedly hitting `ctrl-C`)

#### Saving a change to a project file automatically runs the relevant RSpec tests and RuboCop
- [ ] Pick a random Rails model file that has RSpec tests
- [ ] Make a non-breaking change to the model (ex. Adding another empty line at the end of the file). 
- [ ] After saving the file, confirm that Guard automatically runs the relevant model specs.
- [ ] After all of the specs pass, RuboCop should analyze the file you just saved and report on any violations.

#### Exiting Guard leaves the Spring server running
- [ ] Exit out of Guard by typing `exit` at the Guard prompt.
- [ ] `bundle exec spring` should report that Spring is still running.

#### Cleanup
- [ ] Shut down Spring server by typing `bundle exec spring stop`

### UAT & Prod environment
#### Spring is not installed / Spring server does not run when Rails application boots up
- [ ] Deploy this branch (to UAT / Prod)
- [ ] From the Rails console, run `bundle exec spring status`
- [ ] You should get an error like:
```bash
bundler: command not found: spring
Install missing gem executables with `bundle install`
```

## Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

2023-06-07 18:53 UTC, jshields13 requested changes

2023-06-07 18:53 UTC, jshields13 commented on config/environments/test.rb
> +  config.cache_classes = false
Will this cause performance issues with the test?

2023-06-07 22:57 UTC, jcroteau commented on config/environments/test.rb
> +  config.cache_classes = false
This is a good question, and I don't know the answer. It's a valid concern, so I've added a commit to leave reloading enabled in CI test environments:

[🔧 Leave reloading (class caching) enabled in CI test environments](https://github.com/department-of-veterans-affairs/caseflow/pull/18715/commits/37c831743cfe67e32a1b71e3cf9b07a4e3af596d)

Here is where [`ENV['CI']` is set](https://github.com/department-of-veterans-affairs/caseflow/blob/5001552de93ef5d661af3bc208e16b32d0c228ce/.github/workflows/workflow.yml#L71) (in the `Caseflow Rspec Job` workflow).

2023-06-07 23:01 UTC, jcroteau commented
❌ The `caseflow_lint_job` is failing in CI, but the reported vulnerabilities are unrelated to and any of the dependencies touched in this PR...

2023-06-08 01:08 UTC, nkutub commented on config/environments/test.rb
> +  config.cache_classes = false
I rather the default be set to true and it be forced locally as false for TDD. This way if that ENV var is not set in pipeline it will not hurt the testing performance

2023-06-08 06:20 UTC, jcroteau commented on config/environments/test.rb
> +  config.cache_classes = false
@nkutub -- Good call. There are handful of other places where we check for `ENV["CI"]`, but it's better to be safe than sorry:

[🔧 Cache classes in *all* test environments by default](https://github.com/department-of-veterans-affairs/caseflow/pull/18715/commits/23a278ec819352237433233ede33aa896d579d0c)

2023-06-08 06:34 UTC, jcroteau commented
🕵️‍♂️ While testing this some more locally, I've observed some anomalous behavior with `guard`. 

For some specs (e.g. `spec/models/veteran_spec.rb`), all of the tests will pass on the first run, but they will fail on all subsequent runs. After stopping and restarting `spring`, the same thing reoccurs: first test run passes, all subsequent runs fail. 

It's the same specs that fail each time, so I'm thinking that the Spring reloading is not playing well with how we're writing some of our specs (or perhaps the application code being tested). 

There are some notes in the [Spring README.md](https://github.com/rails/spring/tree/v3.1.1#class-reloading) about potential issues cropping up in specs due to class reloading.

There is also a tip on how to watch Spring server logs to help with [troubleshooting](https://github.com/rails/spring/tree/v3.1.1#troubleshooting), which I'll likely take at look at as well.

🔬 I do want to get to the bottom of this before continuing with this PR, as this could be a major annoyance and would negate the whole point of using Guard in the first place...

2024-04-23 15:47 UTC, ThorntonMatthew commented
Closing due to inactivity as part of our post-PI cleanup effort. Feel free to reopen if this PR is still desired.

2024-04-23 15:47 UTC, closed without merging