Remove deprecated CertficationStats and DispatchStats code - APPEALS/25341
department-of-veterans-affairs/caseflow pull request #18999
Opened 2023-07-13 16:24 UTC by brandondorner

Resolves https://jira.devops.va.gov/browse/APPEALS-25341

# Description
Rework of the PRs https://github.com/department-of-veterans-affairs/caseflow/pull/18986 and https://github.com/department-of-veterans-affairs/caseflow/pull/18988

The `CertificationStats` and  the `DispatchStats` functionality has been deprecated from the app a few years ago but the code remains. It looks like it was intended to be removed at some point but it fell under the radar:
https://github.com/department-of-veterans-affairs/caseflow/issues/12991#issuecomment-578819666

So now we are finally removing the code from the codebase to hopefully clean it up a tiny bit.
This PR is specifically for removing the logic code. This [PR](https://github.com/department-of-veterans-affairs/caseflow/pull/18998) is for removing the obsolete specs.

We are also removing everything related to `StatsController`, `StatsContainer`, the stats route, and the show file. These are no longer needed as well since they were only used in conjunction with DispatchStats and CertficationStats.

We are essentially undoing parts of this commit: https://github.com/department-of-veterans-affairs/caseflow/commit/ef1dd8c3a0a6e092173f86c07bc6a532ac8cea01

The functionality of DispatchStats, CertificationStats, and the StatsContainer have all been deprecated and now are removed.
The original deprecation comes from these PRs: https://github.com/department-of-veterans-affairs/caseflow/pull/1193
https://github.com/department-of-veterans-affairs/caseflow/pull/11934
https://github.com/department-of-veterans-affairs/caseflow/issues/12991
https://github.com/department-of-veterans-affairs/caseflow/pull/13095

More specifically it looks like this was meant to be removed but was not per:
https://github.com/department-of-veterans-affairs/caseflow/issues/12991#issuecomment-578819666

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] There is no more code related to DispatchStats, CertificationStats, or StatsContainer (excluding the specs)

## Related PRs:
https://github.com/department-of-veterans-affairs/caseflow/pull/18986
https://github.com/department-of-veterans-affairs/caseflow/pull/18988

2023-07-14 18:45 UTC, brandondorner commented on app/controllers/test/users_controller.rb
> -        missing_docs: "/certifications/new/2771149",
`missing_docs` is not used anywhere else in the codebase but I am not _100%_ sure it should be removed so if I could get some eyes on this that would be much appreciated

2023-08-28 21:19 UTC, craigrva requested changes

2023-08-28 21:19 UTC, craigrva commented on app/controllers/test/users_controller.rb
> -        missing_docs: "/certifications/new/2771149",
This is for the local/demo page `/test/users`, under the "App selector" section. Clicking the Missing Docs link brings you to a specific certification. We should leave this line in.

2023-08-30 12:37 UTC, craigrva approved these changes
LGTM, nice work!

2023-09-12 19:03 UTC, merged