Pamatya/appeals 23401
department-of-veterans-affairs/caseflow pull request #19047
Opened 2023-07-21 17:41 UTC by pamatyatake2

Resolves [APPEALS-23401](https://jira.devops.va.gov/browse/APPEALS-23401)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-07-24 21:38 UTC, craigrva requested changes

2023-07-24 21:38 UTC, craigrva commented on app/views/decision_reviews/show.html.erb
> +      loadingPowerOfAttorney:{
Missing a space between the ':' and '{', I'm surprised that CodeClimate or lint didn't give a warning for it

2023-07-24 21:38 UTC, craigrva commented on client/app/nonComp/components/PowerOfAttorneyDecisionReview.jsx
> +      /* eslint-disable camelcase */
You can use `eslint-disable-next-line camelcase` instead of separately enabling and disabling for rules in a single line

2023-07-24 21:38 UTC, craigrva commented on client/app/nonComp/reducers/index.js
> +export const mapDataToInitialState = function (props = {}) {
Does your linter flag this for not having a space? I don't think I've seen a space in this syntax before, and it other instances of that in the application don't have the space

2023-07-24 21:38 UTC, craigrva commented on client/app/nonComp/reducers/index.js
> +    case ACTIONS.TASK_UPDATE_DECISION_ISSUES_START:
The lint job flagged this as well, but the `case` lines should be at the same indentation level as the `switch` line that defines the block

2023-07-24 21:38 UTC, craigrva commented on client/app/nonComp/reducers/index.js
> +      return update(state, { currentTab: { $set: action.payload.currentTab } });
Can you break this down into a multi-line return? It can fit on one line, but I think we should be consistent with the other reducer functions

2023-07-24 21:38 UTC, craigrva commented on client/app/nonComp/reducers/index.js
> +      return update(state, { loadingPowerOfAttorney: { $set: { error: action.payload.error } } });
Same as above comment about breaking this into a multi-line return instead of one line for consistency

2023-07-24 21:38 UTC, craigrva commented on client/app/queue/PowerOfAttorneyDetail.jsx
> +
Can you remove this whitespace and the whitespace on line 40 that was added?

2023-07-24 21:38 UTC, craigrva commented on spec/feature/non_comp/dispositions_spec.rb
> +    it "Decision Review should have Power of Attorney Section" do
I think that we should be testing to ensure that the component doesn't display on a non-VHA page. There's a test "displays dispositions page" that we could put an assertion into so that we don't have to write a new feature test for it (since they are slow)

2023-07-25 02:10 UTC, pamatyatake2 commented on client/app/nonComp/reducers/index.js
> +export const mapDataToInitialState = function (props = {}) {
my linter is actually inserting that space.  I think i might need to change my settings for linter

2023-07-25 02:17 UTC, pamatyatake2 commented on client/app/queue/PowerOfAttorneyDetail.jsx
> +
looks like my linter needs some fixing. Its looking for that space at line 40

2023-07-25 02:53 UTC, pamatyatake2 commented on app/models/higher_level_review.rb
> +  delegate :power_of_attorney, to: :claimant, allow_nil: true
done

2023-07-25 02:53 UTC, pamatyatake2 commented on app/models/supplemental_claim.rb
> +  delegate :power_of_attorney, to: :claimant, allow_nil: true
done

2023-07-25 02:53 UTC, pamatyatake2 commented on app/views/decision_reviews/index.html.erb
> +        poa_button_refresh: FeatureToggle.enable!(:poa_button_refresh)
fixed

2023-07-25 02:53 UTC, pamatyatake2 commented on app/views/decision_reviews/show.html.erb
> +          poa_button_refresh: FeatureToggle.enable!(:poa_button_refresh)
fixed

2023-07-25 02:54 UTC, pamatyatake2 commented on app/views/decision_reviews/show.html.erb
> +      loadingPowerOfAttorney:{
fixed

2023-07-25 02:54 UTC, pamatyatake2 commented on client/app/nonComp/components/PowerOfAttorneyDecisionReview.jsx
> +      /* eslint-disable camelcase */
changed.

2023-07-25 02:54 UTC, pamatyatake2 commented on client/app/nonComp/reducers/index.js
> +export const mapDataToInitialState = function (props = {}) {
fixed. auto saving was messing this up

2023-07-25 02:54 UTC, pamatyatake2 commented on client/app/nonComp/reducers/index.js
> +    case ACTIONS.TASK_UPDATE_DECISION_ISSUES_START:
done, auto save was messing this up when saving.

2023-07-25 02:55 UTC, pamatyatake2 commented on client/app/nonComp/reducers/index.js
> +      return update(state, { currentTab: { $set: action.payload.currentTab } });
done

2023-07-25 02:55 UTC, pamatyatake2 commented on client/app/nonComp/reducers/index.js
> +      return update(state, { loadingPowerOfAttorney: { $set: { error: action.payload.error } } });
done

2023-07-25 02:55 UTC, pamatyatake2 commented on spec/feature/non_comp/dispositions_spec.rb
> +    it "Decision Review should have Power of Attorney Section" do
added an assertion.

2023-07-25 13:31 UTC, craigrva approved these changes
LGTM

2023-07-26 20:30 UTC, merged