Add `Alert` banner for issues with no decision date - APPEALS/19548
department-of-veterans-affairs/caseflow pull request #19063
Opened 2023-07-25 20:03 UTC by brandondorner

https://jira.devops.va.gov/browse/APPEALS-19548

# Description
From the Jira Epic:
Value Statement: "As a VHA Intake user, I need the ability to bypass the required Decision Date entry for a HLR/SC if the information is not provided, so that I may proceed with the intake of the claim."

As a result of allowing the user to save issues with no decision date, we want to alert the user with a banner to the outcome of saving without a decision date.

Steps done in this PR:
1. Remove re-routing for issues w/o decision dates
2. Add NoDecisionBanner to IssueList component
3. Create Storybook to test normal functionality and NoDecisionDate issue functionality
4. The stories are testing:
a. The basic issueSectionRow functionality
b. issueSectionRow when the issue has no decision date
(The next steps are some code rework that doesn't add functionality but improves on some code debt)
5. Extract `issueSectionRow` to its own file (More notes on this in commit)
6. Move `addIssues.jsx` into the `addIssues` folder (More notes on this in commit)

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Issues that have a decision date are shown and can be interacted with as normal
- [ ] The user can navigate to the "Edit Issues" page without being redirected when there is an issue without a decision date present
- [ ] An issue without a decision date has a banner displayed below it
- [ ] The addIssues/editIssues functionality is unchanged and tests related to this pass

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

## SCREENSHOTS
 ### BEFORE
![image](https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/fd4e1877-5ba0-40c6-be10-d826c59a8730)

### AFTER
![image](https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/1338dab9-79fb-4efd-b0ef-9ac72fea897a)

## Storybook Story
- [ ] Basic IssueSectionRow
- [ ] No decision date IssueSectionRow

## QA

- For creating an issue with no decision date I can show you how to set this up locally but I am not sure how to do this in the app. If we can do it locally ping me, if not we may have to reach out in slack

2023-07-25 20:06 UTC, brandondorner commented on client/app/intake/pages/addIssues/addIssues.jsx
> +import RemoveIssueModal from '../../components/RemoveIssueModal';
One thing that could be done in the future is we can use more absolute paths where possible instead of relative paths so that in the future when files and folders get moved around we don't have to edit file paths.

But that's not any high priority or anything like that

2023-07-25 20:09 UTC, brandondorner commented on client/app/intake/pages/addIssues/addIssues.jsx
> +import RemoveIssueModal from '../../components/RemoveIssueModal';
One thing that could be done in the future is we can use more absolute paths where possible instead of relative paths so that in the future when files and folders get moved around we don't have to edit file paths.

But that's not any high priority or anything like that

2023-07-25 20:09 UTC, brandondorner commented on client/app/intake/pages/addIssues/addIssues.jsx
> -          rowObjects = rowObjects.concat(issueSectionRow(sectionIssues, ' ', key));
The `key` prop is no longer needed as it was removed in this PR: https://github.com/department-of-veterans-affairs/caseflow/commit/53c38dc8c6ebed1497d415dc63eb4329ee38a2a3#diff-436abc11b87388cbb002f8c77be37f09bd84ebc1ff2fb837687380289096125fL311

But not here

2023-07-25 20:09 UTC, brandondorner commented on client/app/intake/pages/addIssues/issueSectionRow/issueSectionRow.jsx
> +        {showPreDocketBanner && <Alert message={COPY.VHA_PRE_DOCKET_ADD_ISSUES_NOTICE} type="info" />}
The Jira ticket suggested adding the no decision date banner here alongside the showPreDocketBanner but it has to be in the IssueList component since each issue needs to have the logic whether to or to not display the no decision date banner

2023-07-25 21:23 UTC, TylerBroyles requested changes
I think this might be slightly out of sync with the feature branch because of that pact act rollback.

2023-07-25 21:23 UTC, TylerBroyles commented on client/app/intake/pages/addIssues/addIssues.jsx
> +import RemoveIssueModal from '../../components/RemoveIssueModal';
Yeah I agree. There's slight downsides to not using relative, but I think it's worth it to avoid all the headache that comes with maintaining relative routes.

2023-07-25 21:23 UTC, TylerBroyles commented on client/app/intake/pages/addIssues/issueSectionRow/issueSectionRow.jsx
> +        {showPreDocketBanner && <Alert message={COPY.VHA_PRE_DOCKET_ADD_ISSUES_NOTICE} type="info" />}
Yeah it has to go down into IssueList or somewhere further down the component since it's specific to each issue.

2023-07-26 13:39 UTC, brandondorner commented on app/models/cavc_dashboard.rb
> +        rai.description.gsub(/#\d+\z/, "").rstrip == ri.description && rai.benefit_type == ri.benefit_type
Yep it was based off of the wrong branch

2023-07-26 14:09 UTC, brandondorner commented on client/app/intake/pages/addIssues/addIssues.jsx
> +import RemoveIssueModal from '../../components/RemoveIssueModal';
For sure for sure, there are some where it makes sense to have relative paths but for the most part absolute causes less headaches

2023-07-26 14:58 UTC, TylerBroyles requested changes
Looks good. Almost everything looks great from a code perspective. I added a few comments that we will likely need to get some feedback on, but that's about all I noticed. Good job!

2023-07-26 14:58 UTC, TylerBroyles commented on client/app/intake/components/IssueList.jsx
> +const alertStyling = css({
It looks like the font size in the designs is closer to size of the issue description text which is roughly 17px I think.

2023-07-26 14:58 UTC, TylerBroyles commented on client/app/intake/constants.js
> -  REQUEST_ISSUE_MISSING_DECISION_DATE: '/missing_decision_date',
I'm not sure if this is still needed for other types of decision reviews or appeals other than the VHA claim reviews. I also don't know how much of this they are changing for the pact/mst work to allow more extensive editing of issues.

2023-07-26 14:58 UTC, TylerBroyles commented on client/app/intake/pages/addIssues/addIssues.jsx
> -  requestIssuesWithoutDecisionDates(intakeData) {
Same as the routing comment. I am not sure flat out removing this is the intended behavior for all claim reviews and appeals. VHA claim reviews pretty much only deal with 1 type of issue which is a nonrating request issue. There are other types like contestable issues and rating issues which have different uses and implications. This method is poorly named, but it seems to also be checking for the ratingIsuseReferenceId and the isUnidentified property. I don't have enough domain knowledge to definitively say that these things can be removed without consequences.

2023-07-26 14:58 UTC, TylerBroyles commented on client/app/intake/pages/addIssues/addIssues.jsx
> -          rowObjects = rowObjects.concat(issueSectionRow(sectionIssues, ' ', key));
Good catch. Javascript really just does not care about a lot of things. Who needs well defined function parameters anyhow.

2023-07-26 14:58 UTC, TylerBroyles commented on client/app/intakeEdit/IntakeEditFrame.jsx
> -                  <PageRoute
Same as the other routing comments. Not sure if it is fine to just totally remove it for all types of appeal/reviews.

2023-07-26 15:04 UTC, brandondorner commented on client/app/intake/constants.js
> -  REQUEST_ISSUE_MISSING_DECISION_DATE: '/missing_decision_date',
We can leave it in if everybody feels like it should stay but as of now `REQUEST_ISSUE_MISSING_DECISION_DATE` as well as `/missing_decision_date` isn't found anywhere else in the codebase so I felt it should be removed then added back in later if/when the route is needed

2023-07-26 15:13 UTC, brandondorner commented on client/app/intake/pages/addIssues/addIssues.jsx
> -  requestIssuesWithoutDecisionDates(intakeData) {
Ah I see what you are saying
I could change 
```
   return !requestIssues.every((issue) => issue.ratingIssueReferenceId ||
      issue.isUnidentified || issue.decisionDate);
  }
```
to 
```
   return !requestIssues.every((issue) => issue.ratingIssueReferenceId ||
      issue.isUnidentified);
  }
```

and I feel like that would resolve it.
What do you/y'all think?

2023-07-26 16:30 UTC, brandondorner commented on client/app/intake/components/IssueList.jsx
> +const alertStyling = css({
Good catch, it's been updated with a new commit.

2023-07-26 16:34 UTC, brandondorner commented on client/COPY.json
> +  "VHA_NO_DECISION_DATE_BANNER": "This claim will be saved, but cannot be worked on until a decision date is added to this issue.",
Yeah they look different between Jira, Figma, and this wireframe https://bipuiux.invisionapp.com/console/share/TEYKNBUH6Z5/982144987

2023-07-26 16:35 UTC, brandondorner commented on client/app/intake/components/IssueList.jsx
> +const alertStyling = css({
![image](https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/2b7b3e75-8b01-49c2-999a-adf7c183dd27)

2023-07-26 16:54 UTC, TylerBroyles commented on client/app/intake/pages/addIssues/addIssues.jsx
> -  requestIssuesWithoutDecisionDates(intakeData) {
It might be fine along with a rename of the method to do that. I don't know if the missing decision date warning/routing error is still something that other business lines or organizations want. All I know is that VHA doesn't care about it anymore (and potentially others given the pact/mst changes that apparently are in limbo).

2023-07-26 17:33 UTC, brandondorner commented on client/app/intake/pages/addIssues/addIssues.jsx
> -  requestIssuesWithoutDecisionDates(intakeData) {
Okay sounds good, I'll update it to that and we can bring it up to BA/UX

2023-07-26 18:10 UTC, brandondorner commented on client/app/intake/components/IssueList.jsx
> +          const showNoDecisionDateBanner = editPage && !issue.date;
This should be fine as ` const showNoDecisionDateBanner = !issue.date;` since the routing updates I've made in regards to your comments.

We will continue to reroute unless it is a vha page so the `IssueList` component will only show when there is no decisionDate if it's a VHA type issue

2023-07-26 18:10 UTC, brandondorner commented on client/app/intake/constants.js
> -  REQUEST_ISSUE_MISSING_DECISION_DATE: '/missing_decision_date',
Updated and left in, this can be looked at in the future

2023-07-26 18:12 UTC, brandondorner commented on client/app/intake/pages/addIssues/addIssues.jsx
> -  requestIssuesWithoutDecisionDates(intakeData) {
I went and added `intakeData.benefitType !== 'vha'` and left everything else the same

2023-07-26 19:03 UTC, TylerBroyles approved these changes
Looks good to me! Good Job.

2023-08-01 13:54 UTC, ajspotts commented on client/COPY.json
> +  "VHA_NO_DECISION_DATE_BANNER": "This claim will be saved, but cannot be worked on until a decision date is added to this issue.",
Wording has been confirmed with design/business

2023-08-01 13:54 UTC, ajspotts approved these changes

2023-08-01 18:20 UTC, ajspotts approved these changes

2023-08-01 18:22 UTC, ajspotts approved these changes

2023-08-01 18:22 UTC, merged