Adding a rails initializer for monitoring deprecation warnings
department-of-veterans-affairs/caseflow pull request #19078
Opened 2023-07-28 05:19 UTC by AnandEdara

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-07-29 00:48 UTC, jcroteau reviewed
First off, really nice work on this! 👏 
- I was not aware of `ActiveSupport::Deprecation.behavior` , so thank you for brining it to my attention! 💚
- I also think you made a good decision to emit a warning to the application log as well, since messages to Sentry and/or Slack could fail.

Instead of polluting your PR with a bunch of comments, I've pushed up a [branch with a refactor and a spec](https://github.com/department-of-veterans-affairs/caseflow/pull/19084/files) for your consideration. Happy to go through it with you and the reasons behind my decisions. After that, you're welcome to incorporate our agreed changes into your PR here.

A few more overall suggestions:
- [x] The PR title should have format `devname/APPEALS-XXXX <description>`. 
    - So in this case `aedara/APPEALS-26087 Setup monitoring for deprecation warnings`.
- [x] I think it would be good to finish filling out the template in the PR description. 
- [x] A Jira Test issue (Xray test) is required on all new code (per our contract)
  - [x] In preparation for that, it would be good if you were to write out the manual steps for your test plan under the **Testing Plan** section. 
    - For this, a simple test of accessing the Rails console, executing `ActiveSupport::Deprecation.warn("test deprecation warning")`, and checking that Sentry and the `#appeals-deprecation-alerts` Slack channel received messages should be sufficient.
  - [x] I can work with you on creating a Jira Test story if you haven't done this before.
- [x] It's generally good practice to add test coverage whenever possible, even for "little things" like this. It helps keeps our SimpleCov score high, so that future Rails upgraders will thank us 😄 


Also, before we test this in UAT, I think we'll need to wait until we have a resolution to the [UAT no-op guard clause in `SlackService #send_notification`](https://benefits-int-delivery.slack.com/archives/C02KREHBTPC/p1690581460602559?thread_ts=1690567554.069639&cid=C02KREHBTPC):

**app/services/slack_service.rb**
```ruby
def send_notification(msg, title = "", channel = DEFAULT_CHANNEL)
  return unless url && (aws_env != "uat")
```

2023-08-03 17:39 UTC, jcroteau requested changes

2023-08-03 17:39 UTC, jcroteau commented on config/initializers/deprecation_alerts.rb
You can remove this file now, since we've replaced it with `DeprecationWarningSubscriber`

2023-08-03 17:41 UTC, AnandEdara commented on config/initializers/deprecation_alerts.rb
Ok I will do that

2023-08-03 18:02 UTC, jcroteau approved these changes

2023-08-04 19:03 UTC, jcroteau reviewed
We tested successfully in UAT, but there is one small improvement we can make to the Slack alert titles...

2023-08-04 19:03 UTC, jcroteau commented on config/initializers/deprecation_warning_subscriber.rb
> +      .send_notification(event.payload[:message], SLACK_ALERT_TITLE, SLACK_ALERT_CHANNEL)
Currently, the alerts look like this in [DSVA `#appeals-deprecation-alerts`](https://dsva.slack.com/archives/C05L7AMMV62):


<img width="632" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/3683255/8dd9249d-8a40-44b1-83a8-871516b06262">

It's not immediately obvious which environment they are coming from.

Let's add some more detail to the Slack alert title, maybe so that it reads like

```
Deprecation Warning - caseflow (uat)
```

```suggestion
    slack_alert_title = "Deprecation Warning - #{APP_NAME} (#{ENV['DEPLOY_ENV']})"
    
    SlackService
      .new(url: ENV["SLACK_DISPATCH_ALERT_URL"])
      .send_notification(event.payload[:message], slack_alert_title, SLACK_ALERT_CHANNEL)
```

2023-08-04 19:03 UTC, jcroteau commented on config/initializers/deprecation_warning_subscriber.rb
> +  SLACK_ALERT_TITLE = "Deprecation Warning"
```suggestion
  APP_NAME = "caseflow"
```

2023-08-07 17:20 UTC, jcroteau commented on spec/initializers/deprecation_warning_subscriber_spec.rb
> +    let(:app_name") { "caseflow" }
```suggestion
    let(:app_name) { "caseflow" }
```

2023-08-07 18:34 UTC, jcroteau approved these changes
⭐

2023-08-08 18:53 UTC, jcroteau commented
### UAT Results
This was tested successfully in UAT.
See resultant Sentry event at https://sentry.uat.appeals.va.gov/sentry/caseflow-uat/issues/4298

Also, a message was posted successfully to DSVA `#appeals-deprecation-alerts` channel:

<img width="635" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/3683255/74f20f09-c20b-4f1d-bc1c-cf4e73bdc115">

2023-08-15 18:55 UTC, merged