APPEALS-19550: Add Decision Date to existing issue
department-of-veterans-affairs/caseflow pull request #19153
Opened 2023-08-08 20:49 UTC by brandondorner

Resolves https://jira.devops.va.gov/browse/APPEALS-19550

# Description
Add the ability to add a decision date to an existing issue that does not have a decision date.

This is done by:
1. Creating the `AddDecisionDateModal` component and its accompanying reducer/action submit logic.
2. Creating the `addDecisionDateModalVisible` toggle and its accompanying reducer/action logic
3. Adding `addDecisionDateModalVisible` and `AddDecisionDateModal` to `issueList.jsx` and `addIssues.jsx` to show the modal when prompted.
4. Add backend changes that allow for editing of an issue's decision_date attribute

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Related tests pass
- [ ] A user can now add a decision date to an existing issue that does not have a decision date. (Further notes in QA section below)

# Frontend
## User Facing Changes

https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/da69cc22-2293-4519-8bf9-95b87a6f4bbd

## Storybook Story
Story for `AddDecisionDateModal`:
![Screenshot 2023-08-08 at 3 33 27 PM](https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/42d304dc-52ef-4571-8eb4-c197e4b885fb)

# Backend
- Add ability to edit an issue's decision_date attribute

# QA
At `/higher_level_reviews/{CLAIM_UUID}/edit`
#### If an issue already has a decisionDate
- [ ] There will be no "Add Decision Date" action available to select for that issue. And subsequently no `AddDecisionDateModal`
#### If an existing issue does not have a decisionDate
- [ ] There will be an "Add Decision Date" option
- [ ] Clicking this option will open the AddDecisionDateModal
- [ ] Selecting a date and clicking save should result in the issue having an updated decision date
- [ ] The "Save" button should be disabled if there is no decision date selected or there if a user manually enters a date in the future which is prohibited.
- [ ] The cancel buttons work to close the modal

#### Other tests to try
- [ ] Can edit multiple issue decision dates at the same time
- [ ] Can edit a decision date while adding/removing/withdrawing other issues in the same save and maintaining functionality
- [ ] At At `/higher_level_reviews/{CLAIM_UUID}/edit` a user can click "Add Issue", not select a decision date, click "Add Issue" then go on to edit the decision date after the issue has been added to the list.
- [ ] Can still remove/edit/withdrawal and do any other action to an issue as normally expected

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [x] RSpec
- [x] Jest

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

### Error Handling
- [ ] If a user manually overrides the date input validation and sends a decision_date that is in the future to the backend, there will be an error thrown and the decision_date will not be updated.

2023-08-09 21:39 UTC, TylerBroyles requested changes
Looks good so far. I added a few comments. Let me know what you think.

2023-08-09 21:39 UTC, TylerBroyles commented on client/app/intake/components/IssueList.jsx
> +      options.push({ displayText: 'Add decision date', value: 'add_decision_date' });
This option value should maybe be kebab case, but I don't actually know the best practice for this. Underscores are already being used all over the place so I don't think it matters too much anyhow.

2023-08-09 21:39 UTC, TylerBroyles commented on client/app/intake/pages/addIssues/addIssues.jsx
> +      issueAddDecisionDateIndex: 0,
We can possibly skip adding this to the state variables of this component. If we passed the index to the toggleAddDecisionDateModal() and use that to set the activeIssue then we could use that redux state value everywhere instead of the component state variable. Some of the modals work that way and some work using their own custom indexes. Either way is probably fine.

2023-08-09 21:39 UTC, TylerBroyles commented on client/app/intakeEdit/reducers/index.js
> +    addDecisionDateModalVisible: false,
Is this needed here and in all 3 review types' individual reducer files?

2023-08-10 14:23 UTC, brandondorner commented on client/app/intake/components/AddDecisionDateModal/AddDecisionDateModal.jsx
> +            Issue decription:
Yeah there were inconsistencies in the figma designs on the casing so I just went with "Issue description" to match the casing of the other labels

2023-08-10 14:27 UTC, brandondorner commented on client/app/intake/components/AddDecisionDateModal/AddDecisionDateModal.jsx
> +    dispatch(addDecisionDate({ decisionDate, index }));
I think I would prefer it to be in the same file it is used just for separation of concerns purposes

2023-08-10 14:35 UTC, brandondorner commented on client/app/intake/components/IssueList.jsx
> +      options.push({ displayText: 'Add decision date', value: 'add_decision_date' });
Yeah the reason I went with snake_case is that above there is a usage of snake_case for `undo_correction` and I was just following the example that was already laid out. I'm not fully sure which one is best practices either

2023-08-10 14:41 UTC, brandondorner commented on client/app/intakeEdit/reducers/index.js
> +    addDecisionDateModalVisible: false,
Nope you are right, pulling them out now

2023-08-10 14:42 UTC, brandondorner commented on client/app/intake/pages/addIssues/addIssues.jsx
> +      issueAddDecisionDateIndex: 0,
I think for the sake of getting it over the line in this sprint I'll just keep it in for now if it's fine

2023-08-10 15:21 UTC, TylerBroyles approved these changes
Looks good to me! Good job.

2023-08-17 14:48 UTC, ajspotts commented
Closed in favor of https://github.com/department-of-veterans-affairs/caseflow/pull/19175

2023-08-17 14:48 UTC, closed without merging