Test - Dorner/appeals 19551
department-of-veterans-affairs/caseflow pull request #19206
Opened 2023-08-17 15:56 UTC by brandondorner

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-08-17 20:57 UTC, TylerBroyles requested changes
Looks good to me. I added some comments mostly for the feature test.

2023-08-17 20:57 UTC, TylerBroyles commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
>        expect(task.status).to eq("assigned")
```suggestion
      expect(task.reload.status).to eq("assigned")
```

2023-08-17 20:57 UTC, TylerBroyles commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
>        task.reload
```suggestion
```

2023-08-17 20:57 UTC, TylerBroyles commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
> +      expect(task.status).to eq("assigned")
```suggestion
      expect(task.reload.status).to eq("assigned")
```

2023-08-17 20:57 UTC, TylerBroyles commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
> +      task.reload
```suggestion
```

2023-08-17 20:57 UTC, TylerBroyles commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
> +
```suggestion
expect(page).to have_content(past_date)
```

2023-08-17 20:57 UTC, TylerBroyles commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
> +      # Check that removing all issues without a decision date will now show Establish
The other shared examples already tests removal so it isn't necessary here unless we want to consolidate all of the tests into one giant shared example.

2023-08-17 20:57 UTC, TylerBroyles commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
There's some commented out setup code at the top of this file that can be removed as well.
` let!(:current_user) do
  User.authenticate!(roles: ["Mail Intake"])
  end
`

2023-08-17 20:57 UTC, TylerBroyles commented on client/app/intake/components/IssueList.jsx
> +          displayText: issue.editedDecisionDate ? 'Edit decision date' : 'Add decision date',
Did they want it to swap between add and edit or did they always want it to say edit decision date? That's really the only functionality question I have.

2023-08-17 21:01 UTC, brandondorner commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
> +      # Check that removing all issues without a decision date will now show Establish
Ah I didn't see the test for removal, I'll pull this one out

2023-08-17 21:02 UTC, brandondorner commented on client/app/intake/components/IssueList.jsx
> +          displayText: issue.editedDecisionDate ? 'Edit decision date' : 'Add decision date',
I thought I remember bringing it up in the BA/UX review but I could be mistaken
I'll message Oluchi about it

2023-08-17 21:11 UTC, brandondorner commented on client/app/intake/components/IssueList.jsx
> +          displayText: issue.editedDecisionDate ? 'Edit decision date' : 'Add decision date',
Oluchi said it's good to go 👍

2023-08-17 21:28 UTC, brandondorner commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
> +      click_on("Add issue")
Yeah I think it would be dice to have some testing of the add issue button and modal. Plus it's only like 6 lines of code so leaving it in wouldn't be a huge tradeoff

2023-08-17 22:06 UTC, TylerBroyles requested changes
Last thing. That expect statement I suggested was probably not specific enough to check if the field was actually being prepopulated correctly.

2023-08-17 22:06 UTC, TylerBroyles commented on spec/feature/intake/vha_hlr_sc_enter_issue_no_decision_date_spec.rb
> +
I think this is actually an incorrect expect statement. I think this could actually be matching the text behind the modal which is not what we want.
I think this will actually make sure that the modal date input text is correct.
```      
within ".cf-modal-body" do
  expect(page).to have_content("Edit Decision Date")
  expect(page).to have_field("#decision-date", text: past_date)
end
```

2023-08-18 15:30 UTC, TylerBroyles approved these changes
Looks good to me. Good job!

2023-08-23 15:03 UTC, merged