APPEALS-29105 Fix Deprecation Warning: Controller-level `force_ssl` is deprecated and will be removed from Rails 6.1 [pre Rails 6.1]
department-of-veterans-affairs/caseflow pull request #19328
Opened 2023-08-31 14:26 UTC by AnandEdara

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/appeals-29105)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/appeals-29105) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-09-07 17:58 UTC, jcroteau reviewed
A few things left to address:
- See the comments below
- There are a LOT of tests failing in CI. I don't see how they would be related to our changes here (since our changes only affect `production` environments), so maybe try merging in the lastest `master` to kick off a fresh CI build?

2023-09-07 17:58 UTC, jcroteau commented on app/controllers/api/application_controller.rb
> -  force_ssl if: :ssl_enabled?
We also need to remove the method `#ssl_enabled?` from this class, since it has no other callers.

2023-09-07 17:58 UTC, jcroteau commented on app/controllers/application_base_controller.rb
> -  force_ssl if: :ssl_enabled?
We also need to remove the method `#ssl_enabled?` from this class, since it has no other callers.

2023-09-08 17:10 UTC, AnandEdara commented on app/controllers/application_base_controller.rb
> -  force_ssl if: :ssl_enabled?
https://github.com/department-of-veterans-affairs/caseflow/pull/19328/commits/9b321c45b1169e3f6198577954313dab17fea131

2023-09-08 17:10 UTC, AnandEdara commented on app/controllers/api/application_controller.rb
> -  force_ssl if: :ssl_enabled?
https://github.com/department-of-veterans-affairs/caseflow/pull/19328/commits/b16d1e9ce185eb797503ad33d5d8cef4a05cb75b

2023-09-19 16:18 UTC, jcroteau commented on app/policies/ssl_redirect_exclusion_policy.rb
> +                                 ]).freeze
Looks like [codeclimate is still being a menace](https://codeclimate.com/github/department-of-veterans-affairs/caseflow/pull/19328) 😆

Have you tried just making this an `Array` to get around the indentation issues? 
Given there are only 5 elements here, I don't think there will be any meaningful performance differences between accessing a `Set` versus an `Array`.

```suggestion
class SslRedirectExclusionPolicy
  EXEMPT_PATH_PATTERNS = [
    %r{^/api/metadata$},
    %r{^/health-check$},
    %r{^/idt/api/v1/},
    %r{^/api/docs/v3/},
    %r{^/idt/api/v2/}
  ].freeze
```

2023-09-22 15:33 UTC, jcroteau requested changes
🧪 This still needs a test plan before it can be approved. Everything else looks good to go, though.

2023-10-03 01:33 UTC, jcroteau commented
For the test plan, it would be good indicate the specific routes you're going to request.

- **For example:** To test one of the `/api/docs/v3/*` routes, you could do the following from the command line:

```
curl -I http://localhost:3000/api/docs/v3/decision_reviews
```
- and expect that the response is `HTTP/1.1 200 OK`.


- Do the above for the following, replacing `<host>` with the appropriate host for the environment you are testing in (eg. locally it would be `localhost:3000`):
  - `http://<host>/api/docs/v3/decision_reviews`
  - `http://<host>/api/metadata`
  - `http://<host>/health-check`

---

- For an `/idt/api/v1/*` route, it's a little trickier, because you need a user with the appropriate role and an auth token.

- From the Rails console:
```ruby
user = User.active.with_role("Admin Intake").first
key, token = Idt::Token.generate_one_time_key_and_proposed_token
Idt::Token.activate_proposed_token(key, user.css_id)
token
```

- Copy the `token` value, then from the CLI:

(replace `<host>` and `<token>`)
```
curl -I -H "TOKEN: <token>" http://<host>/idt/api/v1/user
```

- and expect to get response `HTTP/1.1 200 OK`.

---

- For an `/idt/api/v2/*` route, you can do the following:

- Generate another token, as you did above:

```ruby
user = User.active.with_role("Admin Intake").first
key, token = Idt::Token.generate_one_time_key_and_proposed_token
Idt::Token.activate_proposed_token(key, user.css_id)
token
```

- Find an `Appeal` id

```ruby
appeal_id = Appeal.first.id
```

(replace `<host>`, `<token>` and `<appeal_id>`)
```
curl -I -H "TOKEN: <token>" http://<host>/idt/api/v2/appeals/<appeal_id>
```
- and expect to get response `HTTP/1.1 200 OK`.

---

To test a route that _should_ redirect for SSL:

(replace `<host>`)
```
curl -i  http://<host>/queue 
```

- expect to get response `HTTP/1.1 301 Moved Permanently` , `Location: https://localhost/queue`

2023-10-11 17:25 UTC, jcroteau commented
As discussed previously, let's add regex `/Controller-level force_ssl is deprecated and will be removed from Rails 6.1/` to the `RAILS_6_1_FIXED_DEPRECATION_WARNING_REGEXES` array in the `DisallowedDeprecations` module (similarly to the other deprecation fixes you've done so far ([example](https://github.com/department-of-veterans-affairs/caseflow/pull/19496/files)) and also add the appropriate test steps for that to our test plan.

2023-10-12 14:37 UTC, jcroteau requested changes

2023-10-12 14:54 UTC, jcroteau commented on app/services/deprecation_warnings/disallowed_deprecations.rb
> +    /Controller-level force_ssl is deprecated and will be removed from Rails 6\.1/
I think we'll need the back-ticks around `force_ssl` in order to match the [deprecation warning](https://github.com/rails/rails/blob/4701a50b586a440d118dce29c9a48bfb306ade5c/actionpack/lib/action_controller/metal/force_ssl.rb#L21C1-L22). Otherwise, this will not work as intended.

```suggestion
    /Controller-level `force_ssl` is deprecated and will be removed from Rails 6\.1/
```

2023-10-12 14:59 UTC, jcroteau reviewed
Also, thanks for updating the Jira test plan. 

When you can, would you update the **Testing Plan** section on this PR to match what you have in the Jira Test plan?

2023-10-13 19:00 UTC, jcroteau approved these changes
🎈

2024-04-23 15:50 UTC, ThorntonMatthew commented
Closing due to inactivity as part of our post-PI cleanup effort. Feel free to reopen if this PR is still desired.

2024-04-23 15:50 UTC, closed without merging

2024-04-24 19:16 UTC, jcroteau commented
Superseded by https://github.com/department-of-veterans-affairs/caseflow/pull/21453