remove featuretoggle useAMAActivationDate
department-of-veterans-affairs/caseflow pull request #19542
Opened 2023-09-21 13:13 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-09-22 21:08 UTC, TylerBroyles requested changes
Alright I'm done with the first pass. I left some comments. I noticed that there are still several reducers and other spots in redux where the feature toggle is still being referenced. The only one that I am unsure about is the form context and the yup validation for the ramp refiling, but I think all the others can be removed like you already have done. Let me know what you think.

2023-09-25 13:14 UTC, pamatyatake2 commented on spec/feature/intake/review_page_spec.rb
> +      find("label", text: "Bob Vance", match: :prefer_exact).click
this was failing before for some validation reason. after i fixed that validation i forgot to revert this change.

2023-09-25 13:15 UTC, pamatyatake2 commented on spec/feature/intake/veteran_name_caching_spec.rb
> +      Fakes::BGSService.get_veteran_record(veteran.file_number)
yes, test failure. for some reason it was feature toggle removing was causing this step to fail.

2023-09-25 14:07 UTC, pamatyatake2 commented on app/models/decision_review.rb
> +    if intake
nope, i do not think so

2023-09-25 19:45 UTC, TylerBroyles requested changes
Looks good. There's a couple of code climate issues left to fix, but that's about all I notice.

2023-09-25 19:45 UTC, TylerBroyles commented on app/models/decision_review.rb
> +    Constants::DATES["AMA_ACTIVATION"].to_date
This is causing a code climate issue now since it doesn't use any instance data. You could remove the method and just use Constants::DATES["AMA_ACTIVATION"].to_date in the two places I see this method being used. As far as I can tell it is only being referenced once in request issues and once in this file.  There's also another definition that is exactly the same in the base_contestable_issues_controller file.

You could also pull it out into a module and include it in the decision review and base contestable issues controller files.

2023-09-25 19:45 UTC, TylerBroyles commented on spec/feature/intake/veteran_name_caching_spec.rb
> +      Fakes::BGSService.get_veteran_record(veteran.file_number)
I still don't see why this would be happening unless it was related to the Timecop.freeze(post_ramp_start_date) moving from 2017 to the ama activiation date of 2019.

2023-09-25 20:48 UTC, pamatyatake2 commented
Closing this out since the feature toggle is not always being used and ticket is blocked

2023-09-25 20:48 UTC, closed without merging