changing deprecated functions to componentdidupdate
department-of-veterans-affairs/caseflow pull request #19579
Opened 2023-09-26 18:02 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-09-27 18:33 UTC, pamatyatake2 commented on client/test/app/hearings/components/__snapshots__/ScheduleVeteranForm.test.js.snap
> +                            "label": "St. Petersburg regional office",
Not sure if updating these snapshot was a great idea

2023-09-27 18:34 UTC, pamatyatake2 commented on client/app/certification/ConfirmHearing.jsx
> +  resetState: PropTypes.func,
mostly added these as linter in github was complaining for some reason

2023-09-27 18:34 UTC, pamatyatake2 commented on client/app/certification/DocumentsCheck.jsx
> +          <a href={`/certifications/${match.params.vacols_id}/check_documents`}>refresh this page.</a></p>
Added these space as linter wasn't happy about it.

2023-09-27 22:20 UTC, TylerBroyles requested changes
I added some comments about why I think they jest snapshot was failing. I also added a couple more comments about a few of the other method changes. Let me know if you have any questions.

2023-09-27 22:20 UTC, TylerBroyles commented on client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx
> -  UNSAFE_componentWillMount() {
This should maybe be in a componentDidMount(), but it's hard to imagine this happening on a rerender, but I guess it's possible?

2023-09-27 22:20 UTC, TylerBroyles commented on client/app/reader/PdfViewer.jsx
> +  componentDidUpdate = (nextProps) => {
There's already a componentDidUpdate function above this one so it should be added to that instead of redeclaring it. I am not 100% sure but I assume this would override the previous definition.

2023-09-27 22:20 UTC, TylerBroyles commented on client/app/reader/PdfFile.jsx
> -  UNSAFE_componentWillReceiveProps(nextProps) {
There's already a componentDidUpdate in this file. I'm also not sure if this should be in there or not. It seems to be directly setting state which is probably supposed to be static getDerivedStateFromProps(nextProps, prevState) instead of componentDidUpdate. Either way redefining it is bad.

2023-09-27 22:20 UTC, TylerBroyles commented on client/app/reader/PdfUIPageNumInput.jsx
> +  componentDidUpdate = (nextProps) => {
I think this one is okay.

2023-09-28 04:58 UTC, pamatyatake2 commented on client/app/components/SearchableDropdown.jsx
> -  // eslint-disable-next-line camelcase
I did tried this method as well, as it was causing some specs to fail. due to which i had to revert and use ComponentDidUpdate instead.

2023-09-28 19:55 UTC, TylerBroyles requested changes
Quick note for the PdfFile.jsx file. I think the intent of the original code was more closely aligned to what componentDidUpdate would be doing after re rendering I think.

2023-09-28 19:55 UTC, TylerBroyles commented on client/app/reader/PdfFile.jsx
> +  static getDerivedStateFromProps(nextProps, prevProps) {
On second thought. I would put all of this into the onComponentUpdate instead of getDerivedState because derivedState uses props and state, but the code seems to be deciding between the old and new props so the original intent was probably more aligned with the functionality of the onComponentUpdate lifecycle functions.

The state is being updated directly via the attributes instead of through the setState function. This function is also static so it shouldn't have access to the this keyword so it would have to be rewritten to use it properly.

2023-09-28 21:04 UTC, TylerBroyles requested changes
I think if we are trying to change it in a consistent way then we have to make these changes as well to see if they are valid.

2023-09-28 21:04 UTC, TylerBroyles commented on client/app/reader/PdfViewer.jsx
>        this.props.handleSelectCurrentPdf(nextDocId);
This might be the same situation where the nextDocId should be this.props, but the this.selectedDocId() function already grabs this.props so maybe setting it using that would be fine and then changing nextDocId to be prevDocId.

```
const nextDocId = this.selectedDocId();
const prevDocId = Number(prevProps.match.params.docId);

if (nextDocId !== prevDocId) {
  this.props.handleSelectCurrentPdf(nextDocId);
}
```

2023-09-28 22:46 UTC, TylerBroyles approved these changes
I added one possible suggestion. It looks good to me though. Good job.

2023-09-28 22:46 UTC, TylerBroyles commented on client/app/components/SearchableDropdown.jsx
> +    if (prevProps !== this.props) {
```suggestion
    if (prevProps.value !== this.props.value) {
```

2023-10-11 14:36 UTC, craigrva approved these changes

2023-10-11 18:18 UTC, merged