Min/APPEALS-31484
department-of-veterans-affairs/caseflow pull request #19713
Opened 2023-10-12 20:50 UTC by minhazur9

Resolves [APPEALS-31484](https://jira.devops.va.gov/browse/APPEALS-31484)

# Description
Added in a check for if veteran lives in us that returns the Pittsburgh RO if not

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Adds a method #veteran_lives_in_usa? to check if country code is USA in app/services/va_dot_gov_address_validator/validations.rb similar to #veteran_lives_in_texas?
- [ ] Add a conditional to #closest_regional_office within app/services/va_dot_gov_address_validator.rb
Utilize #veteran_lives_in_usa? to return Pittsburgh RO code for foreign residing veterans (RO71)

## Testing Plan
1. Go to https://jira.devops.va.gov/browse/APPEALS-32417

- [ ] For feature branches merging into master: Was this deployed to UAT?

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

2023-10-13 13:51 UTC, jefftmarks commented on app/services/va_dot_gov_address_validator/validations.rb
> +  def veteran_lives_in_usa?
You have access to `address` as a variable inside this file because it's delegated from `appeal` [here](https://github.com/department-of-veterans-affairs/caseflow/blob/50440e61e2a3c30a1583d3dd9bb36e046c245786/app/services/va_dot_gov_address_validator.rb#L15). Try and see if `address.country` works

2023-10-18 21:06 UTC, msteele96 requested changes

2023-10-18 21:06 UTC, msteele96 commented on app/services/va_dot_gov_address_validator.rb
> +      return "RO56" if appellant_lives_in_phillipines?
```suggestion
      return "RO58" if appellant_lives_in_phillipines?
```

2023-10-24 19:37 UTC, msteele96 requested changes
Another one keystroke edit. This should be the last one

2023-10-24 19:37 UTC, msteele96 commented on spec/services/va_dot_gov_address_validator_spec.rb
> +      it "returns RO71" do
```suggestion
      it "returns RO11" do
```

2023-10-24 19:47 UTC, msteele96 approved these changes

2023-10-24 20:03 UTC, merged