APPEALS/30242 - Add Generate task report button to `ReviewPage`
department-of-veterans-affairs/caseflow pull request #19738
Opened 2023-10-16 19:31 UTC by brandondorner

For: https://jira.devops.va.gov/browse/APPEALS-30243

# Description
Add a button that navigates a user to the `decision_reviews/report` url.

I removed some classNames that had some questionable css properties in it and made it more simple using flex and gap.

Also a note that the test in this commit won't pass until https://github.com/department-of-veterans-affairs/caseflow/pull/19695 is merged in.

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] The Generate task report button navigates you to the `/decision_reviews/report` url. (note this url will be broken until the above PR is merged in but all we are testing is that we get navigated to that url.)
- [ ] The Generate task report button is only displayed to vha users
- [ ] The buttons are presented correctly both for both VHA and non-VHA pages

## Testing Plan
#### VHA
1. Log in as ACBAUERVVHAH
2. Go to `/decision_reviews/vha`
3. See the Generate task button
4. Clicking this button should bring you to the `decision_reviews/report` url. 

#### Non-VHA
1. Log in as NCA_QUEUE_USER_PARVEEN
2. Go to `/decision_reviews/nca`
3. The Generate task report button should not be displayed

## Screenshots
VHA :
<img width="1506" alt="Screenshot 2023-10-16 at 2 28 18 PM" src="https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/b760b5db-793e-43bb-a3af-a92bae40ccbe">

NON-VHA
<img width="1506" alt="Screenshot 2023-10-16 at 2 24 58 PM" src="https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/f7686257-b09a-4b06-87bd-1bca42ea66b5">

2023-10-16 19:32 UTC, brandondorner commented on spec/feature/non_comp/reviews_spec.rb
> +    end
This test will fail until https://github.com/department-of-veterans-affairs/caseflow/pull/19695 is merged in

2023-10-16 21:29 UTC, TylerBroyles requested changes
I added a couple of comments related to the link functionality. Great job on the CSS.

2023-10-16 21:29 UTC, TylerBroyles commented on client/app/nonComp/pages/ReviewPage.jsx
> +              window.location.href = '/decision_reviews/report';
This should be a react route. It also shouldn't display for non admin users.

2023-10-16 21:29 UTC, TylerBroyles commented on spec/feature/non_comp/reviews_spec.rb
> +      click_on "Generate task report"
This might have to be adjusted a bit due to the admin thing. Easiest way is to add a context before block and make the user admin.

2023-10-17 22:21 UTC, TylerBroyles requested changes
Added a few more comments although most were just variable naming for better clarity. One comment is a slightly different approach to restricting access to the report generation page. Let me know what you think. Nice job adding the admin seeds file.

2023-10-17 22:21 UTC, TylerBroyles commented on app/views/decision_reviews/index.html.erb
> +      isVhaAdmin: business_line.user_is_admin?(current_user)
```suggestion
      userIsAdmin: business_line.user_is_admin?(current_user)
```

2023-10-17 22:21 UTC, TylerBroyles commented on client/app/nonComp/pages/ReviewPage.jsx
> +  isVhaAdmin: PropTypes.bool,
```suggestion
  userIsAdmin: PropTypes.bool,
```

2023-10-17 22:21 UTC, TylerBroyles commented on client/app/nonComp/pages/ReviewPage.jsx
> +    isVhaAdmin: state.isVhaAdmin
```suggestion
    userIsAdmin: state.userIsAdmin
```

2023-10-17 22:21 UTC, TylerBroyles commented on db/seeds/users.rb
> +      %w[VHAADMIN ACBAUERVVHAH PTBRADFAVBAS].each do |name|
```suggestion
      %w[VHAADMIN ACBAUERVVHAH PTBRADFAVBAS].each do |css_id|
```

2023-10-17 22:21 UTC, TylerBroyles commented on db/seeds/users.rb
> +        vha_admin = User.find_by_css_id_or_create_with_default_station_id(name)
```suggestion
        vha_admin = User.find_by_css_id_or_create_with_default_station_id(css_id)
```

2023-10-17 22:21 UTC, TylerBroyles commented on client/app/nonComp/pages/ReviewPage.jsx
> +          {this.props.isVhaAdmin ? <Button
Now we have an interesting question. Should only VHA get this functionality? If so then we can either scope it using the this.props.businessLineUrl === 'vha' && this.props.userIsAdmin. We could also use the Vha business line to set the config options by adding a value into businessLineConfig named something like {canGenerateReports: true}, or {enableReporting: true}, or {changeHistory: true} and then if any other business lines want this in the future it will be easy to turn on and off. Let me know what you think about that.

2023-10-18 14:48 UTC, brandondorner commented on app/views/decision_reviews/index.html.erb
> +      isVhaAdmin: business_line.user_is_admin?(current_user)
I've updated it to `isUserVhaAdmin` to maintain the boolean naming convention of starting the variable with is/has

2023-10-18 14:51 UTC, brandondorner commented on client/app/nonComp/pages/ReviewPage.jsx
> +          {this.props.isVhaAdmin ? <Button
I ended up going with 
``` jsx
 {this.props.businessLineUrl === 'vha' && this.props.isUserVhaAdmin ? <Button
            classNames={secondaryButtonClassNames}
            onClick={() => {
              this.props.history.push('/decision_reviews/report');
            }}
            styling={compReviewButtonStyling}
          >
            Generate task report
          </Button> :
            null }
```

I think it's easier to do it here than to mess with config options

I think if other business lines want it in the future we can decide if we want to refactor it then

2023-10-18 16:10 UTC, TylerBroyles requested changes
I think the admin variable should not be named specifically for Vha since it can be any business line admin. I also left a comment about the url route, that I think might need to be changed.

2023-10-18 16:10 UTC, TylerBroyles commented on app/views/decision_reviews/index.html.erb
> +      isUserVhaAdmin: business_line.user_is_admin?(current_user)
I still don't think this should be specific to VhaAdmin. This should be isBusinessLineAdmin or something along those lines.

2023-10-18 16:10 UTC, TylerBroyles commented on client/app/nonComp/pages/ReviewPage.jsx
> +              this.props.history.push('/decision_reviews/report');
I think this should include the business line url.
```javascript
 `/decision_reviews/${this.props.businessLineUrl}/report`
 ```

2023-10-18 16:49 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2023-10-18 21:08 UTC, TylerBroyles submitted a review, later dismissed
Re-approval after seed changes.

2023-10-19 15:53 UTC, TylerBroyles submitted a review, later dismissed

2023-10-24 16:33 UTC, craigrva approved these changes
LGTM

2023-10-25 18:36 UTC, merged