Pamatya/appeals 28454
department-of-veterans-affairs/caseflow pull request #19768
Opened 2023-10-20 20:09 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-10-23 15:06 UTC, brandondorner commented on client/app/nonComp/components/Disposition.jsx
> +          {disableDispositionSelection && COPY.VHA_DISPOSITION_INCOMPLETE_TASK_BANNER_TEXT}
This is nitpicky so feel free to ignore it but it's becoming best practice to avoid using `&&` inside JSX since it can cause unintended rendering. In this case it probably doesn't matter since `disableDispositionSelection` should always be a bool but if you want to get in the habit you could use a ternary instead

```jsx
          {disableDispositionSelection ? COPY.VHA_DISPOSITION_INCOMPLETE_TASK_BANNER_TEXT : null}
```

2023-10-23 15:06 UTC, brandondorner commented on client/app/nonComp/components/Disposition.jsx
> +            {displayVhaNonAdminContent && alertContent}
Same comment as above regarding ternary vs && in jsx

2023-10-23 15:06 UTC, brandondorner commented on client/app/nonComp/components/Disposition.jsx
> +    let emailTemplate = COPY.VHA_REQUEST_TO_CAMO_EMAIL_TEMPLATE.replace('#__LINK_TO_CLAIM__#', window.location.href);
This is nitpicky but if the variables aren't reassigned they should be `const`

2023-10-23 15:48 UTC, craigrva requested changes

2023-10-23 15:48 UTC, craigrva commented on app/views/decision_reviews/index.html.erb
> +      vhaAdminEmailAddress:  Rails.env.production? ? "VHABENEFITAPPEALS@va.gov" : "BID_APPEALS_UAT@bah.com"
For checking if we are in the UAT environment, we would need to run `Rails.deploy_env?(:uat)` because UAT and Production both use `:production` as their Rails.env. 

With ProdTest being set up, we should actually do something like `!Rails.deploy_env?(:prod) ? {UAT email} : {Production email}` so that we don't end up accidentally using the prod address in ProdTest

2023-10-23 15:48 UTC, craigrva commented on app/views/decision_reviews/show.html.erb
> +      vhaAdminEmailAddress:  Rails.env.production? ? "VHABENEFITAPPEALS@va.gov" : "BID_APPEALS_UAT@bah.com",
Same as above comment

2023-10-23 15:48 UTC, craigrva commented on client/COPY.json
> +  "VHA_UAT_EMAIL_ADDRESS": "BID_APPEALS_UAT@bah.com",
We should use this for the view props as well if we're defining it here

2023-10-23 17:13 UTC, pamatyatake2 commented on app/views/decision_reviews/show.html.erb
> +      vhaAdminEmailAddress:  Rails.env.production? ? "VHABENEFITAPPEALS@va.gov" : "BID_APPEALS_UAT@bah.com",
honestly, i was using it before but then i removed it for some reason, then i forgot to revert it. I have implemented it as suggested. 
thanks for the feedback

2023-10-23 17:13 UTC, pamatyatake2 commented on app/views/decision_reviews/index.html.erb
> +      vhaAdminEmailAddress:  Rails.env.production? ? "VHABENEFITAPPEALS@va.gov" : "BID_APPEALS_UAT@bah.com"
Changed as suggested.

2023-10-23 17:14 UTC, pamatyatake2 commented on client/app/nonComp/components/Disposition.jsx
> +    let emailTemplate = COPY.VHA_REQUEST_TO_CAMO_EMAIL_TEMPLATE.replace('#__LINK_TO_CLAIM__#', window.location.href);
Thanks, Changed as suggested.

2023-10-23 17:14 UTC, pamatyatake2 commented on client/app/nonComp/components/Disposition.jsx
> +            {displayVhaNonAdminContent && alertContent}
Thanks, Changed as suggested.

2023-10-23 17:14 UTC, pamatyatake2 commented on client/app/nonComp/components/Disposition.jsx
> +          {disableDispositionSelection && COPY.VHA_DISPOSITION_INCOMPLETE_TASK_BANNER_TEXT}
Thanks, changed as suggested.

2023-10-23 17:17 UTC, brandondorner approved these changes
Nice!

2023-10-23 18:58 UTC, craigrva approved these changes
LGTM

2023-11-01 19:43 UTC, pamatyatake2 commented
Closing this PR since no longer relevant for now.

2023-11-01 19:43 UTC, closed without merging