Pamatya/appeals 30888
department-of-veterans-affairs/caseflow pull request #19843
Opened 2023-10-31 17:57 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-10-31 21:03 UTC, brandondorner requested changes
Most of the requested changes are minor things so it's looking good on the first read through! 👍

2023-10-31 21:03 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.jsx
> +    <fieldset className="checkbox" style={{ paddingLeft: '30px' }}>
There's some css overlap going on here but from the looks of it that is coming from the `Checkbox` component itself. This can potentially be fixed messing with `inputProps` or `styling` but if it requires a big refactor from `Checkbox` it can probably be looked past.

<img width="225" alt="Screenshot 2023-10-31 at 3 54 34 PM" src="https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/c25e434b-f574-4573-ad26-931bdf0806b4">

I also don't think the `{' '}` below is required. Removing it has no affect on my local view. Let me know if I'm wrong

2023-10-31 21:25 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.stories.js
> +import ReportPage from './ReportPage';
This is an example of a relative path import that is okay. Since it is a direct sibling and these files will always be next to each other we shouldn't need one here

2023-11-01 14:41 UTC, pamatyatake2 commented on client/app/nonComp/pages/ReportPage.jsx
> +    <fieldset className="checkbox" style={{ paddingLeft: '30px' }}>
So the overlay looks like its application wide, and it on focus, do we want to override it  
```// Override USWDS v1 focus properties with USWDS v2 styling
*:focus,
a:focus,
.usa-focus {
  outline: .25rem solid $color-focus-outline;
}

[type=radio]:focus + label::before,
[type=checkbox]:focus + label::before {
  outline: .25rem solid $color-focus-outline;
  outline-offset: 6px;
}```

2023-11-01 15:09 UTC, brandondorner commented on client/constants/REPORT_TYPE_CONSTANTS.json
> +      "label": "Event Type/Action",
I think this needs to be `Event / Action` according to the figma: https://www.figma.com/proto/RXSI2bkWAIFLeB392yYzlM/PI-13(FY23Q3)%3AVHA?node-id=2400-5307&starting-point-node-id=1332%3A3806

2023-11-01 15:15 UTC, brandondorner commented on client/test/app/nonComp/pages/ReportPage.test.js
> +      await selectEvent.select(screen.getByLabelText('Report Type'), ['Status', 'Event Type/Action']);
Will have to update this line with the text changes requested above

2023-11-01 15:18 UTC, brandondorner requested changes

2023-11-01 15:18 UTC, brandondorner commented on client/test/app/nonComp/pages/ReportPage.test.js
> +import REPORT_TYPE_CONSTANTS from 'constants/REPORT_TYPE_CONSTANTS.json'
The linter is gonna complain here with no semicolon

2023-11-01 19:44 UTC, pamatyatake2 commented on client/test/app/nonComp/pages/ReportPage.test.js
> +      await selectEvent.select(screen.getByLabelText('Report Type'), ['Status', 'Event Type/Action']);
updated

2023-11-02 21:21 UTC, brandondorner requested changes

2023-11-02 21:21 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.jsx
> +          handleSubmit={methods.handleSubmit(onSubmit)}
This could be `handleSubmit(onSubmit)` since it is extrapolated from methods above 
```
  const { reset, watch, formState, control, handleSubmit } = methods;

```

It currently causes a linter issue since `handleSubmit` by itself is not being used right now

2023-11-02 21:21 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.jsx
> +  const onSubmit = (data) => console.log(data);
This may be a duplicate since this instance isn't being called anywhere

2023-11-03 12:49 UTC, craigrva approved these changes

2023-11-03 12:49 UTC, craigrva commented on client/app/nonComp/pages/ReportPage.jsx
> +    <fieldset className="checkbox" style={{ paddingLeft: '30px' }}>
This is a good find but definitely out of scope for this work. I will make a note of it and bring it to the UX team and see what they think of it.

2023-11-03 13:34 UTC, brandondorner approved these changes

2023-11-07 17:28 UTC, merged