TYLERB/APPEALS-31150: Create Change History service class and queries for compiling data for Change History report
department-of-veterans-affairs/caseflow pull request #19859
Opened 2023-11-02 16:03 UTC by TylerBroyles

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-11-06 16:34 UTC, craigrva requested changes

2023-11-06 16:34 UTC, craigrva commented on app/models/organizations/business_line.rb
> +        " AND tasks.status IN ('assigned', 'in_progress', 'on_hold', 'completed') "
I think that we can drop the `else` from this block. We need to account for `cancelled` tasks as well, because that's how the task closes when removing all request issues from a claim. We could add that, but in that case we'd be just filtering out tasks with a status of `splited` and splits don't apply to HLRs/SCs as far as I know, so it's just more leg work the DB would be doing for no real gain.

2023-11-06 16:34 UTC, craigrva commented on app/models/organizations/business_line.rb
> +    def user_id_filter
Our UserSerializer doesn't provide the ID value to the front end, only the CSS_ID. We can change that to provide the ID or swap the filter column here to CSS_ID, the exact change doesn't matter so much IMO.

2023-11-06 16:34 UTC, craigrva commented on app/models/organizations/business_line.rb
> +        INNER JOIN intakes ON tasks.appeal_type = intakes.detail_type
We talked about swapping this to a `left join` in slack, I just didn't want to forget about it on a future review

2023-11-06 16:34 UTC, craigrva commented on app/services/claim_change_history/claim_history_service.rb
> +    reset_processing_attributes
Is this something that is necessary? As far as I can see we are creating a new instance of this service for generate report call in the controller, so I'm not sure what the deal with this is.

2023-11-06 16:34 UTC, craigrva commented on app/models/organizations/business_line.rb
> +    def days_waiting_filter
I feel like we can really simplify this portion, but I'm not 100% certain on how it would fit into the rest of the query:

- We can drop the `current_time_string` assignment from Rails and use `CURRENT_TIMESTAMP` in Postgres
- Doing the above will let us change to `CURRENT_TIMESTAMP - tasks.assigned_at` which will give us an interval to work with
- Instead of `number_of_days.to_i`, we can do `'#{number_of_days}'::interval` (preserving the single quotes for PG syntax
- With intervals, the 'between' case could be written as (semi-pseudocode) `BETWEEN start_days::interval AND end_days::interval` 

Would it still work with everything else if we simplify it like that?

2023-11-06 16:45 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        " AND tasks.status IN ('assigned', 'in_progress', 'on_hold', 'completed') "
Adding a simple where clause on an index generally only ever speeds up a query since it's reducing the amount of rows it needs to scan, but I would have to run the query planner on it to truly know. I added in "cancelled" to the else for now.

2023-11-06 16:48 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        INNER JOIN intakes ON tasks.appeal_type = intakes.detail_type
Yep. Already updated that.

2023-11-06 16:54 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +    def user_id_filter
That's unfortunate. I can update it to CSS_ID, but will have to change it everywhere that tests id right now so that might take some time if that's what we want to do.

2023-11-06 17:16 UTC, craigrva commented on app/models/organizations/business_line.rb
> +    def user_id_filter
If it's in more than just this spot of the code, we can make it easy and add id to the UserSerializer

2023-11-06 17:19 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +    def days_waiting_filter
I was using an ::interval at some point, but I think I swapped it to make the date math more closely relate to how it works in the days waiting calculation in the UI. Every time I tried to do = 17 days if it was 17 days it would never match up with intervals even if I was trying to extract the date from the interval and do the comparison on that. So I just went with a more numeric thing that I could round as I needed to. If we can get it to work with intervals I have no problems with that.
Below is the closest I can get to the same thing with intervals.
```
AND DATE_TRUNC('day', CURRENT_TIMESTAMP) - DATE_TRUNC('day', tasks.assigned_at + interval '12 hours') #{operator} '#{number_of_days} days'::interval
```

2023-11-06 17:33 UTC, almorbah commented on app/controllers/decision_reviews_controller.rb
> +    return render "errors/404" unless business_line.can_generate_claim_history
I thoughts around making this in to a helper method `def can_generate_claim_history?` that returns `true` or `false`

2023-11-06 17:47 UTC, TylerBroyles commented on app/controllers/decision_reviews_controller.rb
> +    return render "errors/404" unless business_line.can_generate_claim_history
This wasn't really even part of this story, it was just missing for some reason after merging from the feature branch. All that method returns is a true or false depending on subclass implementation, but they naming could be changed to ? and probably should.

2023-11-15 15:23 UTC, craigrva requested changes

2023-11-15 16:07 UTC, craigrva approved these changes

2023-11-17 18:12 UTC, merged