APPEALS-30937 - ‘Days Waiting’ condition for report
department-of-veterans-affairs/caseflow pull request #19870
Opened 2023-11-03 14:05 UTC by csheepy

Resolves [APPEALS-30937](https://jira.devops.va.gov/browse/APPEALS-30937)

# Description
Adds the Days Waiting component content

Adds validation and error messages to the conditions section and report type dropdown

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Additional condition option: Days Waiting 
    - [ ] Drop-down options for ‘Time Range’ type include:
        - [ ] Less than
        - [ ] More than
        - [ ] Equal to
        - [ ] Between
    - [ ] One text box is included to decipher option for Less than, More than, Equal to option.
    - [ ] Two text boxes are included to decipher option for Between range. 

## Testing Plan

1. Log in as ACBAUERVVHAH, navigate to /decision_reviews/vha/report
2. Add a condition and select Days Waiting
3. For Time Range: Less than, More than, and Equal to should have one number field called 'Number of days'. Between should have two number fields for 'Min days' and 'Max days'

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

<img width="1115" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/17840614/c15c3d41-d023-40f3-9e69-1c2f9f0e0854">
<img width="1085" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/17840614/84368f6d-7670-4949-965b-0034187fd9ea">

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-11-06 17:56 UTC, brandondorner requested changes

2023-11-06 17:56 UTC, brandondorner commented on client/app/nonComp/components/ReportPage/ConditionDropdown.jsx
> +  const filteredOptions = determineOptions();
I feel if we are passing this function down to be immediately called on all conditions we should either make the determineOptions function initialization wrapped in a useCallback (probably will have to move the ` let conds = watch('conditions');` line outside the callback
or
wrap determineOptions in a useMemo and rename it "options" or something else and pass down the returned array instead of a function.

Let me know if you agree/disagree or need help with this

2023-11-06 17:56 UTC, brandondorner commented on client/app/nonComp/components/ReportPage/Conditions/DaysWaiting.jsx
> +          return value;
I don't think this return is needed, again let me know if I am missing something

2023-11-06 17:56 UTC, brandondorner commented on client/app/nonComp/components/ReportPage/Conditions/DaysWaiting.jsx
> +          return value;
Same here as above

2023-11-06 17:56 UTC, brandondorner commented on client/app/nonComp/components/ReportPage/Conditions/DaysWaiting.jsx
> +  const valueTwoContent = () => {
I think we should either have this return value displayed directly in the jsx or have it be its own component.
The reason being this is a function that has no parameters or conditionals and the return value will always be the same as if we had this directly in the jsx

I vote for having it directly in the jsx but if you want to keep it as a separate component i would fix the casing to match React components `valueTwoContent` -> `ValueTwoContent`

2023-11-06 17:56 UTC, brandondorner commented on client/app/nonComp/components/ReportPage/Conditions/DaysWaiting.jsx
> +export const DaysWaiting = ({ control, register, name }) => {
There's currently no validation to check if the values has been selected or if min days is less than max days. I'm not sure if this will be done in another ticket to add validation for all of them but I'm just bringing it up here in case

2023-11-06 17:59 UTC, brandondorner commented
There's also an issue where clicking "Remove condition" not only removes the condition you have selected but also unintentionally clears the state of all other conditions inputs. This also happens on my branch so I'm gonna make a commit on my branch to resolve that and you can cherry pick it

2023-11-07 22:03 UTC, csheepy commented on client/app/components/SearchableDropdown.jsx
> +    PropTypes.shape({ current: PropTypes.instanceOf(Object) }),
feels too broad but couldn't figure out how to reference the StateManager that it actually is

2023-11-09 15:43 UTC, brandondorner submitted a review, later dismissed
Nice!

There will most likely be merge conflicts between this PR and mine but we can cross that bridge when we get to it

2023-11-09 20:16 UTC, craigrva approved these changes

2023-11-09 20:17 UTC, brandondorner submitted a review, later dismissed

2023-11-13 18:36 UTC, brandondorner submitted a review, later dismissed

2023-11-15 18:48 UTC, merged