APPEALS-30938 | Add DecisionReviewType condition for `ReportPage`
department-of-veterans-affairs/caseflow pull request #19876
Opened 2023-11-03 19:56 UTC by brandondorner

Jira: https://jira.devops.va.gov/browse/APPEALS-30938

Main Jira effort: https://jira.devops.va.gov/browse/APPEALS-26499

# Description
- Add the `DecisionReviewType` condition field inputs for the Generate Task Report effort.
- Refactor `ConditionContent` rendering
   1. Add a "middle content" section that is conditionally displayed.
This displays the "includes" text for all but the `daysWaiting`
condition. As a result of this some css changes were made to correctly
display this text.

   2. Remove the getConditionContent() function and instead change that
to a memoized conditionContent variable. I can't find an article on it
but I was taught to avoid calling functions that render React
components within jsx. I believe it caused rendering/state issues but
idk I can't find anything on it so who knows. At the least this should
have better performance using useMemo

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Tests pass
- [ ] There should be an additional condition option: Decision Review Type 
- [ ] The checkbox options for Decision Review Type are Higher-Level Reviews and Supplemental Claims
- [ ] The data gets correctly set and can be seen in the console log on submit of the form.

## Testing Plan
1. Log in as VHAADMIN1
2. Go to `decision_reviews/vha/report`
3. Click Add Condition
4. Select Decision Review Type
5. See the checkbox fields and interact with them
6. Click submit and check the dev tools console to see if the correct data was logged

## Design Note:
The implemented changes are slightly different than the designs in Figma. The designs in Figma assume a larger width of the main app container than what currently exists in our app. As a result the elements becomes squished when trying to match the figma exactly. Instead I have taken some design liberties to wrap certain elements when the screen width gets too small. Although this is not in the designs I presume this will be fine. Screen share can be seen below:

Uploading Screen Recording 2023-11-03 at 2.49.17 PM.mov…

2023-11-03 20:41 UTC, roberttravispierce commented
Nice work Brandon. This got my attention: 
>The designs in Figma assume a larger width of the main app container than what currently exists in our app.

We should address this and remedy, it seems like to me; or is this a one-off situation?

2023-11-06 14:47 UTC, brandondorner commented
> Nice work Brandon. This got my attention:
> 
> > The designs in Figma assume a larger width of the main app container than what currently exists in our app.
> 
> We should address this and remedy, it seems like to me; or is this a one-off situation?

@roberttravispierce Yeah this is a recurring problem that should be fixed
I brought it up once but I don't think it got any traction

2023-11-07 19:21 UTC, TylerBroyles requested changes
Looks good. I left a few comments about the checkboxes and some variables, but not much.

2023-11-07 20:06 UTC, brandondorner commented on client/app/nonComp/components/ReportPage/Conditions/DecisionReviewType.jsx
> +  name: PropTypes.string,
Yeah it will be

2023-11-07 20:06 UTC, brandondorner commented on client/app/styles/_noncomp.scss
> +        @media screen and (min-width: 1440px) {
Thanks! I actually don't mind doing a lot of css stuff so if y'all ever have css problems send them my way

2023-11-07 20:26 UTC, brandondorner commented on client/app/nonComp/components/ReportPage/Conditions/DecisionReviewType.jsx
> +    label: 'Higher Level Reviews',
It's now "Higher-Level Reviews"

2023-11-07 20:38 UTC, brandondorner commented on client/test/app/nonComp/components/reportPage/DecisionReviewType.test.js
> +      <ReportPage />
Good point, I've moved these tests into the ReportPage.test.js file

2023-11-07 23:35 UTC, TylerBroyles requested changes
Looks good. Nice job. I left a comment about the useMemo hook since it's not behaving as intended and I added a small comment about the checkbox values if we wanted the value to more closely match the expected database value. There are also some linting errors, most of which are because our linter does not know what gap: 8px; is. You can either disable linter check inline, add an exemption in the linting file, or update the linter itself so it will know about the property.

2023-11-07 23:35 UTC, TylerBroyles commented on client/app/nonComp/components/ReportPage/ConditionContainer.jsx
> +  const conditionContent = useMemo(() => {
This memo unfortunately doesn't do anything because variableOptions are being redeclared every time the ConditionContainer is being re-rendered.  If you move those options outside of the component, then it will memo this correctly. Clicking on the checkboxes still causes a re-render of every single condition container which is not ideal, but it at least doesn't re-render itself. This form is pretty lightweight so even if we don't memoize anything at all it will still be okay.

2023-11-07 23:35 UTC, TylerBroyles commented on client/app/nonComp/components/ReportPage/Conditions/DecisionReviewType.jsx
> +    name: 'HigherLevelReviews'
If you want it to match what the database will be expecting then it is singularized. We could always parse it out later if we needed to, but I figure it's easy enough to change here.
```suggestion
    name: 'HigherLevelReview'
```

2023-11-07 23:35 UTC, TylerBroyles commented on client/app/nonComp/components/ReportPage/Conditions/DecisionReviewType.jsx
> +    name: 'SupplementalClaims'
Same as above
```suggestion
    name: 'SupplementalClaim'
```

2023-11-08 16:28 UTC, TylerBroyles approved these changes
Looks good to me. Nice job!

2023-11-09 20:44 UTC, TylerBroyles submitted a review, later dismissed
Looks good.

2023-11-14 15:57 UTC, almorbah reviewed
Nice work Brandon

2023-11-17 13:37 UTC, merged