WIP-Connect Ineligible Judge list to AMA docket for hearing held
department-of-veterans-affairs/caseflow pull request #19934
Opened 2023-11-13 17:25 UTC by shruthisibi

<(https://jira.devops.va.gov/browse/APPEALS-31630) to reflect the URL of the Jira item this PR is associated with -->
Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/APPEALS-31630)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-11-13 18:07 UTC, craigrva requested changes

2023-11-13 18:07 UTC, craigrva commented on app/models/docket.rb
> +        .where("css_id IN (?)", ineligible_judges_cssid_cache)
This `non_genpop_for_judge` method is only checking on CAVC Remand appeals which are out of scope for this effort, so it can be removed from this portion.

2023-11-13 18:07 UTC, craigrva commented on app/models/docket.rb
> +        .where("css_id IN (?)", ineligible_judges_cssid_cache)
For this method (and the `nonpriority` method above it) we don't necessarily have the User table joined, so it will probably error out. I think these checks should be moved to the HearingRequestDocket, because the genpop checks when running `not_genpop_appeals` will always bring in a value for `judge_id` that we can compare the ID value to. In this case, it is only getting the actual ID of the user, not the CSS_ID, so we would need to use that ID instead of the CSS_ID for these checks.

2023-11-13 18:07 UTC, craigrva commented on app/models/docket.rb
> +    def self.ineligible_judges_cssid_cache
I think that this needs to be declared in the Docket class itself, not the Scopes module

2023-11-16 16:37 UTC, calvincostaBAH commented on app/queries/hearing_request_distribution_query.rb
> +        .where("judge_id IN (?)", ineligible_judges_id_cache)
This line here makes it so that it only returns cases that are tied to an ineligible judge. it should be the opposite. Not sure if we want to change this method to specifically not include cases tied to ineligible judges but if we did, you would need to check for `"judge_id NOT IN ineligible_judges_id_cache"`. Also, the ineligible_judges_id_cache method is in a different file so you will need to call it directly within the docket.rb file or may need to move it to this file.

2023-11-16 18:00 UTC, craigrva requested changes
The check on line 45 will need to be modified. There is no intention of disabling the `use_by_docket_date` FeatureToggle, and that check is specifically written to never bother looking at the hearings to determine if there is an affinity to the current judge.

You can test these methods in the rails console by commenting the `private` line to make them public methods, and then passing the appropriate values in:
```
base_relation = HearingRequestDocket.new.ready_nonpriority_appeals # this can be priority or nonpriority, but right now the seed file is creating the cases as nonpriority
judge = User.find_by_css_id "BVABDANIEL" # a judge who is active, so that we can test to see if a hearing affinity is bypassed and distributed to this judge if the judge associated with the hearing is inactive
hrdq = HearingRequestDistributionQuery.new(base_relation: base_relation, genpop: "any", judge: judge, use_by_docket_date: false) # changing genpop here will let you test the three distinct paths for appeals with hearing affinity. also, use_by_docket_date needs to be false right now because it is changing what methods are being called to specifically _not_ check for tied cases.

hrdq.ineligible_judges_id_cache # gets the cache values
hrdq.call # runs the query based on the passed in parameters
```

2023-11-16 18:00 UTC, craigrva commented on app/queries/hearing_request_distribution_query.rb
> +    Rails.cache.fetch("case_distribution_ineligible_judges").pluck(:id).reject(&:blank?)
`pluck` and `reject` need to be behind safe operators or it will error out when there isn't any valid entires in the cache

2023-11-16 18:00 UTC, craigrva commented on debug.log
> +[1113/105134.464:ERROR:icu_util.cc(252)] Couldn't mmap icu data file
This file needs to be de-staged

2023-11-16 18:00 UTC, craigrva commented on app/queries/hearing_request_distribution_query.rb
> +        .where("judge_id not IN (?)", ineligible_judges_id_cache)
Using active record here is causing the `.where` to operate directly on the **appeal object**, not adding it to the query. You should be able to follow the line above to provide it values that will cause active record to generate the where portion of the SQL correctly.

Also, this check is going to need to be wrapped in an OR method ([docs here](https://guides.rubyonrails.org/active_record_querying.html#or-conditions)) because chaining `.where` implicitly handles it as an AND. We want the hearings held by the judge, _or_ hearings held by an ineligible judge.

2023-11-16 21:34 UTC, calvincostaBAH commented on app/queries/hearing_request_distribution_query.rb
> +        .where("judge_id not IN (?)", ineligible_judges_id_cache)
Should the OR method for ineligible judges be done before or after the hearing affinity check on the next line. I assume the method check should be after since we shouldn't care about the affinity if they are tied to an ineligible judge. if we do it before the check it will only return cases of ineligible judges where there hearing affinity is still active.

2023-11-20 14:47 UTC, craigrva requested changes

2023-11-20 14:47 UTC, craigrva commented on app/queries/hearing_request_distribution_query.rb
> +        .where("1 = ?", FeatureToggle.enabled?(:acd_cases_tied_to_judges_no_longer_with_board) ? 1 : 0))
We shouldn't be modifying this method to include ineligible judges. The way it is currently called in the code (when not using `by_docket_date`) would cause cases to be selected twice during a distribution query.

2023-11-20 14:47 UTC, craigrva commented on app/queries/hearing_request_distribution_query.rb
> +          .where("1 = ?", FeatureToggle.enabled?(:acd_cases_tied_to_judges_no_longer_with_board) ? 1 : 0)))
We shouldn't be modifying this method to include ineligible judges. The way it is currently called in the code (when not using by_docket_date) would cause cases to be selected twice during a distribution query.

2023-11-20 15:19 UTC, craigrva commented on app/queries/hearing_request_distribution_query.rb
> +          .where("1 = ?", FeatureToggle.enabled?(:acd_cases_tied_to_judges_no_longer_with_board) ? 1 : 0))
The SQL generated by this is:
```
SELECT "appeals".* FROM "appeals"
	INNER JOIN "tasks" ON "tasks"."appeal_id" = "appeals"."id" AND "tasks"."appeal_type" = $1
	INNER JOIN "claimants" ON "claimants"."decision_review_id" = "appeals"."id" AND "claimants"."decision_review_type" = $2
	LEFT OUTER JOIN people on people.participant_id = claimants.participant_id
	LEFT OUTER JOIN advance_on_docket_motions on advance_on_docket_motions.person_id = people.id
WHERE "appeals"."docket_type" = $3
	AND (people.date_of_birth > '1948-11-20 14:38:27.614507' or people.date_of_birth is null)
	AND NOT (appeals.stream_type = 'court_remand')
	AND "hearings"."disposition" = $4
	AND 1=0
	AND (1 = 1)
GROUP BY appeals.id
	HAVING (count(case when tasks.type = 'RootTask' and tasks.status not in ('completed','cancelled') then 1 end) >= 1)
	AND (count(case when tasks.type = 'DistributionTask' and tasks.status = 'assigned' then 1 end) >= 1)
	AND (count(case when advance_on_docket_motions.granted and advance_on_docket_motions.created_at > appeals.established_at then 1 end) = 0)
ORDER BY appeals.receipt_date
[["appeal_type", "Appeal"], ["decision_review_type", "Appeal"], ["docket_type", "hearing"], ["disposition", "held"]]
```
Which throws an error:
`ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "hearings"`
The way this is written isn't joining the hearings table at any point, which is causing the error.

2023-11-20 16:23 UTC, craigrva commented on app/queries/hearing_request_distribution_query.rb
> +        tied_to_ineligible_judge
This needs to be implemented differently. The `with_held_hearings` method above returns **all** hearings with a held disposition, so it will already be getting all of those. We need to change this so that with the feature toggle enabled we aren't returning all held hearings, and instead only the ones that the judge held or were held by judges that are on the ineligible judges list.

2023-11-28 04:15 UTC, kristeja submitted a review, later dismissed
🚢

2023-11-28 04:28 UTC, kristeja approved these changes

2023-11-28 04:29 UTC, merged