Add ‘Issue Type’ condition for report
department-of-veterans-affairs/caseflow pull request #19941
Opened 2023-11-14 14:01 UTC by roberttravispierce

Resolves [‘Issue Type’ condition for report](https://jira.devops.va.gov/browse/APPEALS-30939)

# Description
Please explain the changes you made here.

## Acceptance Criteria
#### Additional condition option: Issue Type 
 ##### Drop-down options for Issue type include:
 *** Beneficiary Travel
 *** Caregiver | Eligibility
 *** Caregiver | Tier Level
 *** Caregiver | Revocation/Discharge
 *** Caregiver | Other
 *** Clothing Allowance
 *** Medical and Dental Care Reimbursement
 *** Initial Eligibility and Enrollment in VHA Healthcare
 *** Eligibility for Dental Treatment
 *** CHAMPVA
 *** Camp Lejune Family Member
 *** Foreign Medical Program
 *** Spina Bifida Treatment (Non-Compensation)
 *** Continuing Eligibility/Income Verification Match (IVM)
 *** Other
 *** Prosthetics | Other (not clothing allowance)
 ##### User can type to search or select more options from the drop-down selection to include all desired options.
 ##### User can remove any selected Issue type displayed via the 'X' next to each selection. 
 #### Form validation: 
 ##### At least one type must be selected if condition is added 

- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-12-04 17:03 UTC, TylerBroyles requested changes
I left some comments. Let me know what you think.

2023-12-04 17:03 UTC, TylerBroyles commented on client/app/nonComp/components/ReportPage/Conditions/IssueType.jsx
> +  const nameIssueTypeCodes = `${name}.options.issueTypeCodes`;
This name probably needs to match up everywhere with the error codes and schema so it should probably be changed to issueTypes or the errors schema needs to be changed to issueTypeCodes: errorStuff
```suggestion
  const nameIssueTypeCodes = `${name}.options.issueTypes`;
```

2023-12-04 17:03 UTC, TylerBroyles commented on client/app/nonComp/components/ReportPage/Conditions/IssueType.jsx
> +        defaultValue={field.options.issueTypeCodes ?? []}
Same thing as above
```suggestion
        defaultValue={field.options.issueTypes ?? []}
```

2023-12-04 17:11 UTC, brandondorner commented on client/app/styles/_noncomp.scss
> +      .issue-type-container {
If we use `report-page-multi-select-dropdown` we don't need `issue-type-container`

2023-12-06 17:59 UTC, brandondorner requested changes

2023-12-06 17:59 UTC, brandondorner commented on client/test/app/nonComp/pages/ReportPage.test.js
> +      // console.log(generateTaskReport);
There's a few stray comments in here that could be removed

2023-12-06 18:04 UTC, brandondorner approved these changes

2023-12-06 18:10 UTC, brandondorner approved these changes

2023-12-13 13:58 UTC, craigrva approved these changes

2023-12-13 13:58 UTC, merged