APPEALS-30940 | Create `IssueDisposition` component for Generate Task Report
department-of-veterans-affairs/caseflow pull request #20005
Opened 2023-11-21 20:01 UTC by brandondorner

Resolves https://jira.devops.va.gov/browse/APPEALS-30940
Main Jira effort: https://jira.devops.va.gov/browse/APPEALS-26499

# Description
Create the `IssueDisposition` inputs for Generate Task Report.

## Acceptance Criteria
- [ ] Drop-down options for Issue Disposition include:
        Blank
        Granted
        Denied
        Dismissed
        DTA Error
        Withdrawn
- [ ] User can type to search or select more options from the drop-down selection to include all desired options.
- [ ] User can remove any selected Issue Disposition displayed via the 'X' next to each selection. 
Form validation: 
- [ ] At least one type must be selected if condition is added 

## Testing Plan
1. Log in as VHAADMIN1
2. Go to decision_reviews/vha/report
3. Select Event / Action for Report type
4. Click Add Condition
5. Select Issue Disposition
6. Interact with inputs and check if that works
7. Check validation
8. Click submit and check the dev tools console to see if the correct data was logged

## Screenshots

![Screenshot 2023-11-21 at 1 58 39 PM](https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/930f9f13-003b-4202-b041-e72a526d6f1f)

![Screenshot 2023-11-21 at 1 58 57 PM](https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/9d39f9a7-5f3d-4847-ac92-ffa7360c39b4)

2023-11-24 16:20 UTC, seancva requested changes

2023-11-24 16:20 UTC, seancva commented on client/test/app/nonComp/pages/ReportPage.test.js
> +  it('passes a11y testing', async () => {
This is a duplicate test and I think it should be removed, however I think it originated in [this PR](https://github.com/department-of-veterans-affairs/caseflow/pull/19951) and so should probably be removed there.

2023-11-24 19:16 UTC, seancva approved these changes
LGTM!

2023-11-27 17:25 UTC, craigrva requested changes

2023-11-27 17:25 UTC, craigrva commented on client/app/nonComp/components/ReportPage/Conditions/IssueDisposition.jsx
> +const ISSUE_DISPOSITION_LIST = [
We should extract these options to one of the constants files, REPORT_TYPE_CONSTANTS.json has some of them already.

2023-11-27 17:25 UTC, craigrva commented on client/app/styles/_noncomp.scss
> +        .usa-input-error-message {
We aren't removing the bold from the text as that would move us from AAA to AA for WCAG accessibility standards.

2023-11-27 17:37 UTC, brandondorner commented on client/app/styles/_noncomp.scss
> +        .usa-input-error-message {
Updated, I've been told to flip flop the bold and unbold a couple times in the BA/UX reviews so this will be nice to know we have a standard to follow

2023-11-27 17:45 UTC, craigrva approved these changes

2023-12-01 20:21 UTC, merged