add script and rspec file for 'something went wrong' stuck job
department-of-veterans-affairs/caseflow pull request #20054
Opened 2023-11-28 20:17 UTC by zborgesva

Resolves "Write the script for BE: The system has encountered an unknown error" APPEALS-27642

# Description
Handles an error that appears on decision documents. 

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-11-30 16:09 UTC, nicorithner-bah requested changes

2023-11-30 23:28 UTC, nkutub commented on app/jobs/system_encountered_unknown_error_job.rb
> +    return if decision_docs_with_errors.blank?
there does not seem to be enough error handling here , there is too much that can go wrong and you are not rescuing anything

2023-12-04 15:50 UTC, nkutub commented on app/jobs/system_encountered_unknown_error_job.rb
> +    decision_docs_with_errors.each do |single_decision_document|
this is an example of what can blow up if decision_docs_with_errors is nil .each will throw a nil exception

2023-12-06 18:52 UTC, ronwabVa commented on app/jobs/system_encountered_unknown_error_job.rb
> +    !valid_epes.include?(false)
Not a huge fan of negations. Can we write this differently? This is confusing.

2023-12-06 18:59 UTC, ronwabVa commented on app/jobs/system_encountered_unknown_error_job.rb
> +  def process_decision_document(decision_document)
Please rename one of these methods.. You have `process_decision_document` and `process_decision_documentS`...

2023-12-06 19:15 UTC, ronwabVa commented on app/jobs/system_encountered_unknown_error_job.rb
> +      end
personal preference.. I would extract the ActiveRecord::Base.... into a method and call it here..

2023-12-06 19:16 UTC, AdamShawBAH commented on app/jobs/system_encountered_unknown_error_job.rb
> +    @stuck_job_report_service = StuckJobReportService.new
instead of using attr_reader we have been calling super as a override check and just using the stuck job report service instance throughout. Both work, but Nate has indicated this format for our jobs

2023-12-06 19:17 UTC, ronwabVa commented on app/jobs/system_encountered_unknown_error_job.rb
> +  def valid_decision_document?(decision_document)
Personal preference  I would move `upload_documents_to_vbms` and `valid_decision_documents`  and have htem after `process_decision_documents`

2023-12-06 19:25 UTC, ronwabVa commented on spec/jobs/system_encountered_unknown_error_job_spec.rb
> +    let!(:decision_doc_with_error) do
We dont need to create a new decision doc or epe. We can simply update the one that we created at the top. Try as much as possible not to create new data unless you absolutely need to. IF for whatever reason you get an error that the decision_document or records dont exist. use `let!` Not best code practice but it will get you past the error
`decision_document.update(error: "some text").`

2023-12-06 19:26 UTC, ronwabVa commented on spec/jobs/system_encountered_unknown_error_job_spec.rb
> +    let!(:epe) do
same here. No need to create new one. Simply update

2023-12-06 19:26 UTC, ronwabVa commented on spec/jobs/system_encountered_unknown_error_job_spec.rb
> +    let!(:decision_document) do
same here. No need to create new one. Simply update

2023-12-06 19:26 UTC, ronwabVa commented on spec/jobs/system_encountered_unknown_error_job_spec.rb
> +    let!(:epe) do
same here. No need to create new one. Simply update

2023-12-06 19:28 UTC, ronwabVa commented on spec/jobs/system_encountered_unknown_error_job_spec.rb
> +      subject.perform
How can we confirm that the upload was successful?
Hint: Use the uploaded_at date. Test that the date has been updated.

2023-12-06 19:30 UTC, ronwabVa commented on spec/jobs/system_encountered_unknown_error_job_spec.rb
> +  context "When there are one or more EPE's that belong to a decision document" do
Can we test this with multiple records? Please add tests for the following
1. Multiple DDs with errors that all get cleared.
2. Multiple DDs with errors. Some get cleaered others do not. 
3.

2023-12-06 21:24 UTC, zborgesva commented on app/jobs/system_encountered_unknown_error_job.rb
> +    raise error
Nate and I discussed this and essentially we use raise here in order to stop the execution and prevent further errors from occurring in this process.. further discussion would be great though if you have any other thoughts...

2023-12-08 14:09 UTC, ronwabVa commented on spec/jobs/system_encountered_unknown_error_job_spec.rb
> +      expect(decision_document.reload.updated_at).to be_within(10.seconds).of(my_time)
You could use  to freeze time
before do
    Timecop.freeze(Time.zone.now)
  end

2023-12-08 16:49 UTC, zborgesva commented on spec/jobs/system_encountered_unknown_error_job_spec.rb
> +      decision_document.update!(processed_at: nil)
Determined it was unnecessary as there are tests in place elsewhere that test the S3 logs

2023-12-11 14:19 UTC, ronwabVa approved these changes

2023-12-11 14:24 UTC, nicorithner-bah approved these changes
thank you Zack!

2023-12-11 16:38 UTC, closed without merging