Pamatya/appeals 35672
department-of-veterans-affairs/caseflow pull request #20100
Opened 2023-12-04 18:39 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-12-06 17:31 UTC, TylerBroyles requested changes
Looks good. I only had a couple of small comments. Let me know what you think.

2023-12-06 17:31 UTC, TylerBroyles commented on app/models/request_issue.rb
> +    save! if has_changes_to_save?
Isn't has_changes_to_save? redundant here? It should never have any external changes to save because this is an after create hook which should only ever happen one time and so all the changes should have already been saved. It also should always have changes that need to be saved because of the line right above this one
```ruby
  self.decision_date_added_at = created_at
```

2023-12-06 17:31 UTC, TylerBroyles commented on spec/models/request_issue_spec.rb
> +      Timecop.freeze(Time.utc(2023, 4, 26, 12, 0, 0))
You don't technically need Timecop here since the test could just check to see if decision_date_added_at is equal to the request_issue.created_at time. It's fine either way though.

2023-12-06 20:49 UTC, almorbah commented on app/models/request_issue.rb
> +    save! if has_changes_to_save?
There is no No Direct Triggering of The after_create callback itself, it does not trigger a save action. It's a hook that's called after the record has been saved (specifically after it's been created for the first time).
Indirect Changes and save, However, it's possible to change the state of the object within the after_create block. If you modify the object and explicitly call save within this callback, it will trigger a save.

We may want to look into a `before_create` or `after_commit on: create` we we can set the `self.decision_date_added_at = created_at` before the object get saved. 

I think thats why ` save! if has_changes_to_save?` is being used here.

2023-12-07 05:51 UTC, pamatyatake2 commented on app/models/request_issue.rb
> +    save! if has_changes_to_save?
I do not think `save! is has_changes_to_save?` is redundant here. I think its only saving the value only if there are any changes that needs to be saved else it should ignore it I agree it should have saved this value like in hlr and sc but for some reason i had to add this line for the 10182 to work.  Do let me know if there is a better way to do it.

2023-12-07 05:51 UTC, pamatyatake2 commented on spec/models/request_issue_spec.rb
> +      Timecop.freeze(Time.utc(2023, 4, 26, 12, 0, 0))
I removed the Timecop and tested it against created_at.

2023-12-19 19:38 UTC, merged