ACD Cases tied to judges no longer with the board or otherwise ineligible Seed data file refactor
department-of-veterans-affairs/caseflow pull request #20104
Opened 2023-12-05 09:25 UTC by kristeja

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-12-05 22:48 UTC, craigrva requested changes

2023-12-05 22:48 UTC, craigrva commented on spec/factories/user.rb
> +    trait :judge_role do
This role isn't a thing. Use the existing `:judge` trait and it will create the user with the correct relations and roles for Caseflow to consider them a judge

2023-12-05 22:48 UTC, craigrva commented on spec/factories/user.rb
> +        organization = JudgeTeam.for_judge(judge) || JudgeTeam.create_for_judge(judge)
This shouldn't be done as a trait in the user factory because the data won't match production data. Use the `:judge_team` factory to createa a judge team with a different admin, and then add a new user to that organization.

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +      # n is (@file_number + 1) because @file_number is incremented before using it in factories in calling methods
These comments should be kept with the relevant code

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +    def initialize
Initializing all of the instance variables should be done at the same time so that they only have to search for the starting file number one time, and so they are synchronized. Right now the numbers in the group `300_000_000` will have different ending numbers than the rest of the cases created in this seed because the Hearings seed also starts at `300_000_000`. Initializing all of them at once will ensure that they stay grouped as we are expecting.

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +      @active_judge ||= User.find_by(css_id: "BVAAABSHIRE")
We should create a new judge for this specific seed file instead of relying on one from another file. We also want to consider having multiple judges, one for each different scenario, so that we aren't creating hundreds of cases which are all tied to the same judge.

You should use the user factory with the traits `:judge`, and `:with_vacols_judge_record` if they will also be tied to legacy cases.

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +    def inactive_cf_user_and_inactive_admin_judge_team
This isn't creating a judge team. Use the user factory and the `:judge` trait, then you can make the user inactive with `{user}.update_status!('inactive')` and Caseflow will automatically inactivate the user's JudgeTeam.

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +      @active_cf_user_and_non_admin_judge_team ||= create(:user, :with_non_admin_judge_team, :judge_role)
See the comment on the user factory for how you should set this

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +      @active_cf_user_and_inactive_judge_team ||= create(:user, :with_inactive_judge_team, :judge_role)
`:with_inactive_judge_team` isn't going to create the user with how it exists in prod, use the `:judge` trait then make the JudgeTeam inactive with something like `JudgeTeam.for_judge(user).inactive!`. The `:with_inactive_judge_team` trait should be removed from the factory

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +      correspondent = create(:correspondent, snamef: veteran.first_name, snamel: veteran.last_name, ssalut: "")
You should add the `ssn` field to this, it can be the same as the file number because that's how legacy cases used to be created in prod.

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +      create(:staff, :inactive_judge, sdomainid: inactive_cf_user_and_inactive_admin_judge_team.css_id)
When you create the judge in Caseflow, use the trait `:with_vacols_judge_record` to create this record for you with the correct links

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +             :advanced_on_docket_due_to_motion,
Either add this trait to creating appeals ready to distributed for more than 60 days, or remove it from this one.

2023-12-05 22:48 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +      Timecop.travel(1.day.ago)
We should switch this to something like 45 days so that we can test the AMA affinity levers during UAT.

2023-12-06 06:05 UTC, kristeja commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +    def initialize
@craigrva I followed based on the mural test plan but do we want it use starting from `300_000_000` for all the test scenarios with incrementing the number?

2023-12-06 14:16 UTC, craigrva commented on db/seeds/cases_tied_to_judges_no_longer_with_board.rb
> +    def initialize
The mural test plan was just an example, we can change which numbers we start with as necessary. We don't want all of the scenarios starting from `300_000_000` so that they can be distinguished, but we want the last numbers, basically the thousands digits, to line up. When we generate the data set one time the file numbers should all end with similar digits, and then if we run it a second time the thousands digits increment to signal which particular run of the seed data that the case was created as a part of.

2023-12-27 00:48 UTC, merged