APPEALS-14737 | Fix pagination page persistence bug on `NonComp`
department-of-veterans-affairs/caseflow pull request #20188
Opened 2023-12-12 21:00 UTC by brandondorner

Jira: https://jira.devops.va.gov/browse/APPEALS-14737

Jira Description:
Pagination-related options are ingested from URL query parameters upon initial load of the decision review queue page here in `NonCompTabs.jsx`. The values contained within tabPaginationOptions are not kept up to date with changes in the query parameters, however.

This causes issues to arise if a user navigates to the decision review queue using a URL with query parameters that may be incompatible with one/all tabs.

For example, if a user were to go to the VHA's DR queue via /vha?tab=completed&page=10, because the page number of 10 is placed into tabPagiationOptions and never updated, each time a user switches tabs they'll be taken to the 10th page. If one of the tabs does not have 10 pages worth of tasks, this will cause users to be brought to a blank queue page.

# Description
Pass down a new `checkIfPageChanged` onChange function to the TabWindow component. This new function now updates the `tabPaginationOptions.page ` value whenever a new tab is selected.

Added a feature test to confirm the bug has been removed

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Selecting a new tab resets the page value in the query params to 1
- [ ] Selecting the current tab will persist the current page value

## Testing Plan
At `/decision_reviews/vha`
1. Go to a tab with pagination values and select the highest number page you can
2. Navigate to a tab with less pages and see that the page number resets to the first page
3. Confirm that the page number in the url query params matches.

## Screenshots
Before:
![image](https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/beb1ccac-7078-4edf-888f-1f0b3a47f278)

After:
![image](https://github.com/department-of-veterans-affairs/caseflow/assets/51007432/98b06959-14cc-48ef-a25a-dce98adcecd3)

2023-12-12 22:57 UTC, TylerBroyles requested changes
Great job on this one. I don't have anything to add except a bit of clarity around the comment and function name.

2023-12-12 22:57 UTC, TylerBroyles commented on client/app/nonComp/components/NonCompTabs.jsx
> +  const checkIfPageChanged = (value) => {
I think this function should be renamed to something a bit more clear. Maybe something like resetPageNumberOnTabChange or another way to convey what it actually does. I would expect a function named like this to return a boolean or something similar.

2023-12-12 22:57 UTC, TylerBroyles commented on client/app/nonComp/components/NonCompTabs.jsx
> +    // This is to prevent situations where Viewing 31-45 of 1 total gets displayed and prevents successful api requests
```suggestion
    // This is to prevent situations where Viewing 31-45 of 1 total gets displayed and blocks user navigation
```

2023-12-13 15:18 UTC, TylerBroyles submitted a review, later dismissed
Looks good to me. Great job.

2023-12-14 21:27 UTC, craigrva approved these changes

2023-12-14 21:28 UTC, merged