APPEALS-32252 Create Case Distro Algorithm Control Admin UI
department-of-veterans-affairs/caseflow pull request #20302
Opened 2023-12-21 18:54 UTC by amybids

Resolves [Create Case Distro Algorithm Control Admin UI](https://jira.devops.va.gov/browse/APPEALS-32252)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2023-12-29 15:03 UTC, zurbergram commented on app/controllers/application_controller.rb
> +    if current_user.present? && current_user&.organizations && current_user&.organizations&.any?(&:users_can_view_levers?)
Bad coding practices, this check already exists and not correctly using `&`

2023-12-29 15:04 UTC, zurbergram commented on app/controllers/case_distribution_levers_controller.rb
> +    if @acd_group_organization.user_is_admin?(current_user)
bad ruby coding practices, should be using `unless` to reduce nesting within if/else statements

2023-12-29 15:06 UTC, zurbergram commented on app/controllers/case_distribution_levers_controller.rb
> +      if errors.empty?
Bad coding practice, this check is being made twice with no reason for it to be separated

2024-01-01 15:13 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +import { css } from 'glamor';
This is an unsupported library and should not be used. Use classnames only

2024-01-01 15:15 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +    '& .cf-form-int-input': { width: 'auto', display: 'inline-block', position: 'relative' },
Bad practice to define static css inside a component

2024-01-01 15:15 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +            if (validationResponse.statement === 'DUPLICATE') {
Bad practice to use magic strings

2024-01-01 15:16 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +                leverStore.dispatch({
Bad practice to define redux actions in a component.

2024-01-01 15:16 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +                leverStore.dispatch({
Bad practice to not define repeated lines of code as a reusable function

2024-01-01 16:57 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +              leverStore.dispatch({
Bad practice to not define repeated lines of code as a reusable function

2024-01-01 16:58 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +              leverStore.dispatch({
Bad practice to not define repeated lines of code as a reusable function

2024-01-01 16:58 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +      leverStore.dispatch({
Bad practice to not define repeated lines of code as a reusable function

2024-01-01 16:59 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +    if (dataType === 'number') {
Bad practice to use magic strings

2024-01-01 17:00 UTC, zurbergram commented on client/app/caseflowDistribution/components/AffinityDays.jsx
> +                <div key={`${lever.item}-${index}-${option.item}`}>
Pull the else element out to its own function to improve readability

2024-01-01 17:01 UTC, zurbergram commented on client/app/caseflowDistribution/components/BatchSize.jsx
> +  const leverNumberDiv = css({
Bad practice to define static css in components.
Glamor no longer receives updates, classnames is better to use.

2024-01-01 17:02 UTC, zurbergram commented on client/app/caseflowDistribution/components/BatchSize.jsx
> +            leverStore.dispatch({
Bad practice to not define a function for reusable code.
Redux actions belong in their own file to follow repo practices.

This occurs numerous times in this file

2024-01-01 17:24 UTC, zurbergram commented on client/app/caseflowDistribution/reducers/Levers/leversReducer.js
> +import * as Constants from './leversActionTypes';
Repo practice to import this as ACTIONS to distinguish between Redux Action strings and other static strings

2024-01-01 17:29 UTC, zurbergram commented on client/app/components/ToggleSwitch/ToggleSwitch.module.scss
> +.toggleButton {
File is name incorrectly and in wrong location.
Repo practice is to put these files in client/app/styles.
Repo practice is to name these like `_toggle_switch.scss`

2024-01-01 17:30 UTC, zurbergram commented on client/app/components/ToggleSwitch/ToggleSwitch.module.scss
> +	background: #0071BC;
Using hex value will cause linting errors.
All colors should be using variable names.
Unless UX has specifically said the color doesn't already exist within Caseflow a variable for this color should be available to use.

2024-01-01 17:32 UTC, zurbergram commented on client/app/styles/caseDistribution/StaticLevers.module.scss
> +.titleStyling {
File is named incorrectly.
Repo practice is to name these like `_component_name.scss`

2024-01-01 17:33 UTC, zurbergram commented on client/app/styles/caseDistribution/LeverHistory.module.scss
> +$historytablebordercolor: #d6d7d9;
File is named incorrectly.
Repo practice is to name these like `_component_name.scss`

Using hex value will cause linting errors.
All colors should be using variable names.
Unless UX has specifically said the color doesn't already exist within Caseflow a variable for this color should be available to use.

2024-01-01 17:34 UTC, zurbergram commented on client/app/styles/caseDistribution/InteractableLevers.module.scss
> +$border-color: #e4e2e0;
File is named incorrectly.
Repo practice is to name these like `_component_name.scss`

Using hex value will cause linting errors.
All colors should be using variable names.
Unless UX has specifically said the color doesn't already exist within Caseflow a variable for this color should be available to use.

2024-01-01 17:34 UTC, zurbergram commented on client/app/styles/caseDistribution/ExclusionTable.module.scss
> +$exclusion-table-header-color: #d3d3d3;
File is named incorrectly.
Repo practice is to name these like `_component_name.scss`

Using hex value will cause linting errors.
All colors should be using variable names.
Unless UX has specifically said the color doesn't already exist within Caseflow a variable for this color should be available to use.

2024-01-01 17:36 UTC, zurbergram commented on client/app/components/ToggleSwitch/ToggleSwitch.jsx
> +import styles from './ToggleSwitch.module.scss';
This isn't repo practice. 
Scss file should be imported into client/app/styles/app.scss which will make the css available

2024-01-01 17:38 UTC, zurbergram commented on client/app/caseflowDistribution/index.jsx
> +    const staticLevers = [
All of these magic strings and grouping should not be occurring here.
This should be stored in the database table and levers should come from backend pre-grouped

2024-01-01 17:39 UTC, zurbergram commented on client/app/caseflowDistribution/index.jsx
> +      levers: JSON.parse(JSON.stringify(this.props.acd_levers)),
This does nothing as you are converting an object to a JSON string just to convert back to an object

2024-01-01 17:44 UTC, zurbergram commented on client/app/caseflowDistribution/index.jsx
> +    const sectionTitles = [
Why is this defined here?
This appears to only be used in client/app/caseflowDistribution/components/DocketTimeGoals.jsx

2024-01-01 17:45 UTC, zurbergram commented on client/app/caseflowDistribution/index.jsx
> +/* eslint-disable react/prop-types */
This file has way too much going on in it.
There's code that should have been stored in database.
There's code that is not even used till several components down.
This file is not a common place to stash everything.
See https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/index.jsx

2024-01-01 17:48 UTC, zurbergram commented on client/app/caseflowDistribution/components/StaticLeversWrapper.jsx
> +import styles from 'app/styles/caseDistribution/StaticLevers.module.scss';
This isn't repo practice.
Scss file should be imported into client/app/styles/app.scss which will make the css available

2024-01-01 17:48 UTC, zurbergram commented on client/app/caseflowDistribution/components/StaticLever.jsx
> +import styles from 'app/styles/caseDistribution/StaticLevers.module.scss';
This isn't repo practice.
Scss file should be imported into client/app/styles/app.scss which will make the css available

2024-01-01 17:49 UTC, zurbergram commented on client/app/caseflowDistribution/components/StaticLever.jsx
> +    case 'boolean':
Magic string usage.

2024-01-01 17:50 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverModal.jsx
> +  if (changedLever.data_type === 'radio' || changedLever.data_type === 'radio') {
Magic string usage.

2024-01-01 17:50 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverModal.jsx
> +import styles from 'app/styles/caseDistribution/InteractableLevers.module.scss';
This isn't repo practice.
Scss file should be imported into client/app/styles/app.scss which will make the css available

2024-01-01 17:54 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverModal.jsx
> +import React, { useState, useEffect } from 'react';
File has way to much going on it.
All code relating to making API calls or using dispatch should be in the Redux Actions file

2024-01-01 17:55 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverInputValidation.jsx
> +  let maxValue = 999;
Magic value.
This should exist as we define maximum values in the database for each lever and should only be using those.

2024-01-01 17:56 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverInputValidation.jsx
> +    if (lever.data_type === 'radio') {
Magic String usage.

2024-01-01 17:56 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverInputValidation.jsx
> +        statement: 'DUPLICATE',
Magic string usage.

2024-01-01 17:57 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverHistory.jsx
> +import styles from 'app/styles/caseDistribution/LeverHistory.module.scss';
This isn't repo practice.
Scss file should be imported into client/app/styles/app.scss which will make the css available

2024-01-01 17:57 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverHistory.jsx
> +      // let selectedOption = lever.options.find((option) => option.item === lever.value);
Remove commented out code

2024-01-01 17:58 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverButtonsWrapper.jsx
> +import { css } from 'glamor';
Glamor is no longer receiving updates.
Bad practice to define css inside components.
Should be defined in scss files that follow repo practices.

2024-01-01 17:59 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverButtons.jsx
> +      style={{ background: 'none', color: 'blue', 'font-weight': '300' }}
Bad practice to define css in components.

2024-01-01 17:59 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverButtons.jsx
> +  leverStore.dispatch({
Redux related code should go in redux specific files.

2024-01-01 18:01 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverButtons.jsx
> +  window.location.reload(false);
Bad practice. this should not be done. 
If you are having to do this it indicates a problem with how Redux is used and wired into the page and its. components.

2024-01-01 18:02 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverAlertBanner.jsx
> +import styles from 'app/styles/caseDistribution/InteractableLevers.module.scss';
This isn't repo practice.
Scss file should be imported into client/app/styles/app.scss which will make the css available

2024-01-01 18:02 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverAlertBanner.jsx
> +    ${type === 'success' ? styles.leverAlertBannerSuccess : styles.leverAlertBannerError}`;
Magic string usage.
This could have been a boolean

2024-01-01 18:04 UTC, zurbergram commented on client/app/caseflowDistribution/components/LeverAlertBanner.jsx
> +import React, { useEffect } from 'react';
https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/client/src/components/AlertBanner.jsx should be used in this component.
See https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/FnodBanner.jsx for an example

2024-01-01 18:06 UTC, zurbergram commented on client/app/caseflowDistribution/components/ExclusionTable.jsx
> +          <th className={styles.tableHeaderStyling}>Legacy Appeals</th>
Strings should be defined in COPY.json so they can be reused throughout application

2024-01-01 18:06 UTC, zurbergram commented on client/app/caseflowDistribution/components/ExclusionTable.jsx
> +import styles from 'app/styles/caseDistribution/ExclusionTable.module.scss';
This isn't repo practice.
Scss file should be imported into client/app/styles/app.scss which will make the css available

2024-01-01 18:07 UTC, zurbergram commented on client/app/caseflowDistribution/components/DocketTimeGoals.jsx
> +import styles from 'app/styles/caseDistribution/InteractableLevers.module.scss';
This isn't repo practice.
Scss file should be imported into client/app/styles/app.scss which will make the css available.
Glamor should not be used as it is no longer receiving updates.

2024-01-01 18:08 UTC, zurbergram commented on client/app/caseflowDistribution/components/DocketTimeGoals.jsx
> +  const leverNumberDiv = css({
Bad practice to define static css in components.

2024-01-01 18:09 UTC, zurbergram commented on client/app/caseflowDistribution/components/DocketTimeGoals.jsx
> +import React, { useState } from 'react';
File has numerous bad practices.
Magic Strings.
Redux code not in a redux specific file.
Repeated code and reused code not defined in a function.

2024-01-01 18:17 UTC, zurbergram requested changes
This PR has much work to be done before it can be approved to merged into production or a UAT branch.

There are numerous bad practices being done, numerous failings to follow repo practices and there are multiple places where code is repeated instead of pulled out into reusable functions.

2024-02-09 21:32 UTC, craigrva commented on app/models/organizations/cda_control_group.rb
> +class CDAControlGroup < Organization
We should define `can_receive_task?` as false for this Org to follow convention with other orgs like this

2024-02-10 00:05 UTC, zurbergram commented on app/models/organizations/cda_control_group.rb
> +class CDAControlGroup < Organization
Created ACD: CDAControlGroup should define can_receive_task? https://jira.devops.va.gov/browse/APPEALS-40117
to address this

2024-04-23 15:57 UTC, ThorntonMatthew commented
Closing due to inactivity as part of our post-PI cleanup effort. Feel free to reopen if this PR is still desired.

2024-04-23 15:57 UTC, closed without merging