preventing free text
department-of-veterans-affairs/caseflow pull request #20505
Opened 2024-01-16 14:29 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-01-16 22:20 UTC, pamatyatake2 commented on app/models/decision_review_intake.rb
> +      unless request_params[:benefit_type] == "vha"
this is a temporary solution to fix the error that i was getting while trying to save the intake.

2024-01-17 15:03 UTC, brandondorner requested changes
Very good, just some nitpicky requests

2024-01-17 17:03 UTC, TylerBroyles reviewed
Left a couple of notes. Two of them directly impact functionality and it result in some inadvertent behavior changes.

2024-01-17 17:03 UTC, TylerBroyles commented on client/app/intake/addPOA/utils.js
> +  // ...sharedValidation
A lot of the validations on the form won't work correctly if the // ...sharedValidation rules are commented out for more than just this use case.

2024-01-17 17:03 UTC, TylerBroyles commented on client/app/intake/addPOA/AddPoaPage.jsx
> +  const benefitType = intakeData?.benefitType;
I don't think Appeals will have benefit type at this point right? So this might be a bit of an issue.

2024-01-18 17:17 UTC, pamatyatake2 commented on client/app/intake/addPOA/AddPoaPage.jsx
> +  const benefitType = intakeData?.benefitType;
after discussion, we determined that we do not need to worry about Appeals for now.

2024-01-18 20:16 UTC, TylerBroyles reviewed
I left a couple of comments, but really only one that might be worth looking at.

2024-01-18 20:16 UTC, TylerBroyles commented on client/app/intake/addPOA/utils.js
> +  return benType === 'vha' ? schemaHlrOrScVHA : schemaHLROrScOther;
I would just fully name this thing benefitType since it doesn't really save you much typing. 

Apart from that, this is a bit weird because the Claimant page and the PoA page both use this schema but the only reason it matters for the PoA page is because we are passing benefit type there. The claimant page would also have a benefit type 'vha' if it were given to the react hook form at that point. So really benefit type in this case is acting as a double boolean that represents both benefitType and something similar to isPoAPage = true. I'm not sure what the best way to make that less coupled is.

2024-01-18 20:25 UTC, pamatyatake2 commented on client/app/intake/addPOA/utils.js
> +  return benType === 'vha' ? schemaHlrOrScVHA : schemaHLROrScOther;
Change the benType to benefitType. Since Claimant Page is using yup validation from this page ` client/app/intake/addClaimant/utils.js`

2024-01-19 00:51 UTC, TylerBroyles approved these changes
Looks good to me. Good job.

2024-01-19 14:17 UTC, brandondorner approved these changes

2024-01-22 17:38 UTC, merged