Ricky/appeals-37556
department-of-veterans-affairs/caseflow pull request #20502
Opened 2024-01-12 22:07 UTC by Blake-Manus

Resolves [APPEALS-37556](https://jira.devops.va.gov/browse/JIRA-37556)

# Description
Updated redux to properly store lever history. Moved formatting for Lever History away from component and into util file. Automatically refreshes the history section after save without refreshing the page. Fixes the ordering of the lever history to be from newest to oldest. Fixes grouping of levers based on timestamps.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-37556) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-01-13 05:34 UTC, amybids commented on app/controllers/case_distribution_levers_controller.rb
> +    render json: { errors: errors, successful: errors.empty?, lever_history: lever_history, levers: CaseDistributionLever.all.group_by(&:lever_group) }
when you're formatting this, please put errors and successful on their own line.

2024-01-13 05:34 UTC, amybids commented on client/app/caseDistribution/components/CaseDistributionContent.jsx
> +            <LeverHistory leverStore={leverStore} />
you can take leverStore out here

2024-01-13 05:35 UTC, amybids commented on client/app/caseDistribution/components/LeverHistory.jsx
>    leverStore: PropTypes.any,
You don't need the leverStore here either

2024-01-13 05:38 UTC, amybids commented on client/app/caseDistribution/reducers/levers/leversReducer.js
> -  case ACTIONS.SAVE_LEVERS:
Let's look at this together, but SAVE_LEVERS here looks more correct for the current usage than LOAD_LEVERS

2024-01-13 05:39 UTC, amybids commented on client/app/caseDistribution/utils.js
> +export const formateTimestamp = (entry) => {
spelling error formatTimestamp.

2024-01-16 13:32 UTC, zurbergram commented on client/app/caseDistribution/components/LeverHistory.jsx
> +            <td className={styles.historyTableStyling}>{entry.user_id}</td>
This is incorrect, use `user_css_id`
```suggestion
            <td className={styles.historyTableStyling}>{entry.user_css_id}</td>
```

2024-01-16 13:33 UTC, zurbergram commented on client/app/caseDistribution/reducers/levers/leversActionTypes.js
> -  SAVE_LEVERS: 'SAVE_LEVERS',
Why is this removed?

2024-01-16 13:34 UTC, zurbergram requested changes
This PR has several issues in it and is changing already existing code that works

2024-01-16 13:36 UTC, zurbergram commented on client/app/caseDistribution/reducers/levers/leversActions.js
> +          type: ACTIONS.LOAD_LEVERS,
This is incorrect, SAVE_LEVERS is a distinct action separate from LOAD_LEVERS

2024-01-16 13:36 UTC, zurbergram commented on client/app/caseDistribution/reducers/levers/leversActions.js
> +            levers: resp.levers,
repeated property

2024-01-16 13:42 UTC, zurbergram commented on client/app/caseDistribution/reducers/levers/leversActions.js
> +export const loadLevers = (levers, historyList) =>
This function is for loading only levers.
Either rename function or create a separate one for loading the history

2024-01-18 13:32 UTC, zurbergram commented on app/controllers/case_distribution_levers_controller.rb
> +      successful: errors.empty?,
Need to remove this change as successful is determined on frontend not on backend

2024-01-22 18:54 UTC, amybids requested changes

2024-01-22 18:54 UTC, amybids commented on client/app/caseDistribution/utils.js
> +export const formatTimestamp = (entry) => {
Something like this might be easier to read:

export const formatTimestamp = (entry) => {
  const dateEntry = new Date(entry);
  const formattedDate = dateEntry.toLocaleDateString(‘en-US’, {
    weekday: ‘short’,
    year: ‘numeric’,
    month: ‘short’,
    day: ‘numeric’
  }) + ` ${dateEntry.getHours()}:${dateEntry.getMinutes()}:${dateEntry.getSeconds()}`;
  return formattedDate;
};

2024-01-23 14:30 UTC, amybids approved these changes

2024-01-24 05:53 UTC, merged