Min/APPEALS-31621
department-of-veterans-affairs/caseflow pull request #20523
Opened 2024-01-17 15:35 UTC by minhazur9

Resolves [APPEALS-31621](https://jira.devops.va.gov/browse/APPEALS-31621)

# Description
Added model for the transcription_transaction table

## Acceptance Criteria
- [ ] Code compiles correctly
Create a new Model called transcription_transaction_model
a "template" Model
- [ ] many transcription_transactions can have 1 transcript
- [ ] many transcription_transactions can have 1 appeal
- [ ] many transcription_transactions can belong to 1 docket
- [ ] belongs_to :transcription
- [ ] methods to upload retrieved files from Webex to S3 locations
- [ ] Audio files to transcript_audio
- [ ] Raw VTT files to transcript_raw
- [ ] method to update transcription file status
- [ ] method to download transcription files from S3 to local
Create a new Controller called transcription_transactions_controller
a "template" Controller methods of
- [ ] index, new
- [ ] update
- [ ] create

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

2024-01-18 18:16 UTC, ammitche2 commented
thank you!

2024-01-19 14:12 UTC, msteele96 requested changes
In addition to the other comment, could you pull in latest from feature? I'm hoping these commits will fix a couple of the strange rspec failures.

2024-01-19 14:12 UTC, msteele96 commented on app/models/hearings/transcription_file.rb
> +  belongs_to :transcript
I don't see a Transcript object in Caseflow for this to belong to

2024-01-19 14:46 UTC, minhazur9 commented on app/models/hearings/transcription_file.rb
> +  belongs_to :transcript
The AC stated this model is associated with a transcript. Is there any plans for a model object for Transcript? Or was it just a mistake?

2024-01-19 17:38 UTC, msteele96 approved these changes

2024-01-19 17:39 UTC, merged