Div/appeals 38389
department-of-veterans-affairs/caseflow pull request #20579
Opened 2024-01-23 18:41 UTC by divyadasari-va

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/APPEALS-38389)

# Description
Seed data for creating correspondences with different Tasks

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-01-24 20:42 UTC, wmedders21 commented on app/models/task.rb
> +    unless [Constants.TASK_STATUSES.assigned, Constants.TASK_STATUSES.completed].include?(status)
I would suggest making this an overriding method in CorrespondenceTask.rb rather than change the method in Task.rb

2024-01-25 15:40 UTC, divyadasari-va commented on app/models/task.rb
> +    unless [Constants.TASK_STATUSES.assigned, Constants.TASK_STATUSES.completed].include?(status)
So when I am generating CavcCorrespondenceMailTask to completed, then the following error is throwing at this line!! SO that requires modifying that line. Will that cause any issue ??? 

Caseflow::Error::InvalidStatusOnTaskCreate: Task status has to be 'assigned' on create for CavcCorrespondenceMailTask
from /appeals/caseflow/app/models/task.rb:967:in `status_is_valid_on_create'

2024-01-26 20:54 UTC, zurbergram commented on app/models/correspondence.rb
> +    # CorrespondenceRootTaskFactory.new(self).create_root_and_sub_tasks!
Why is this being removed? 
This should be happening on the creation of all Correspondences, any seed data that is created should modified like they are going through the UI

2024-01-26 20:55 UTC, zurbergram commented on app/models/tasks/correspondence_task.rb
> +    puts "DEBUG: type=#{type}, status=#{status}"
Remove this unless it is needed for testing, afterwards it should be removed

2024-01-26 20:58 UTC, zurbergram commented on db/seeds/helpers/seed_helpers.rb
> +  def create_review_package_task(correspondence, status:)
This should not be happening, all Correspondences get these upon creation by default

2024-01-26 20:59 UTC, zurbergram commented on db/seeds/helpers/seed_helpers.rb
> +  def create_correspondence_root_task(correspondence, status:)
This should not be happening, all Correspondences get these upon creation by default

2024-01-26 21:00 UTC, zurbergram commented on db/seeds/helpers/seed_helpers.rb
> +    ReassignPackageTask.create!(
A Correspondence cannot have more than one of these tasks.  If this is not already enforced by code it should be added.

2024-01-26 21:01 UTC, zurbergram commented on db/seeds/helpers/seed_helpers.rb
> +    ReviewPackageTask.create!(
This should not be happening, all Correspondences get these upon creation by default

2024-01-26 21:01 UTC, zurbergram commented on db/seeds/helpers/seed_helpers.rb
> +    review_package_task = ReviewPackageTask.create!(
This should not be happening, all Correspondences get these upon creation by default

2024-01-26 21:03 UTC, zurbergram requested changes
There are several changes in here that break how Correspondence Tasks are handle that need to be reverted. 

We should not be changing how code works to support seed data.

2024-01-29 18:40 UTC, zurbergram approved these changes

2024-01-30 14:19 UTC, merged