Pamatya/appeals 31067
department-of-veterans-affairs/caseflow pull request #20708
Opened 2024-02-05 18:23 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-02-07 19:58 UTC, TylerBroyles requested changes
Looks good. I left a few comments. Let me know what you think.

2024-02-07 19:58 UTC, TylerBroyles commented on app/controllers/decision_reviews_controller.rb
> +    events
Does this even really need to be a method if it's just a one liner? Unless it was because code climate was yelling about some nonsense. You could also wrap the metrics call into this method and pull it out of the controller action to clean it up a bit.

```suggestion
    ClaimHistoryService.new(business_line, task_id: task_id).build_events
```

2024-02-07 19:58 UTC, TylerBroyles commented on client/app/nonComp/actions/changeHistorySlice.js
> +      console.log(response.body);
```suggestion
```

2024-02-07 19:58 UTC, TylerBroyles commented on client/app/nonComp/actions/changeHistorySlice.js
> +  getIndividiualHistory: {
I don't really like the name getIndividualHistory. Maybe something like fetchIndividualHistory. The redux state should be indifferent to the type of request that was used for the call.

2024-02-07 19:58 UTC, TylerBroyles commented on client/app/nonComp/pages/ClaimHistoryPage.jsx
> +  const businessLineUrl = useSelector((state) => state.nonComp.businessLineUrl);
I'm gonna show you something cool that I saw recently. It's an easy way to group selectors. You can use it if you want. It's not as useful with only two selectors but it definitely makes it cleaner if you start to have more.

```jsx
    const { businessLineUrl, task } = useSelector((state) => state.nonComp);
```

2024-02-07 19:58 UTC, TylerBroyles commented on spec/controllers/decision_reviews_controller_spec.rb
> +          res = JSON.parse(response.body)
This should be a bit more DRY in case we want to expand on these tests or add more.
```ruby
expected_events = [
  { "taskID" => task_event.id, "eventType" => "added_issue", "claimType" => "Higher-Level Review", "readableEventType" => "Added Issue" },
  { "eventType" => "claim_creation", "readableEventType" => "Claim created" },
  { "eventType" => "completed_disposition", "readableEventType" => "Completed disposition" }
]

expected_events.each_with_index do |expected_attributes, index|
  expected_attributes.each do |key, value|
    expect(res[index]["attributes"][key]).to eq value
  end
end
```

2024-02-07 19:58 UTC, TylerBroyles commented on client/app/nonComp/actions/changeHistorySlice.js
> +      return thunkApi.fulfillWithValue(response.body);
This is going to leave the events in their serialized state which will be something like the code snippet below in the redux store.
```
{
  '0': {
    id: '3e0012a5-6b0a-4ed8-a186-f4514fe1b43f',
    type: 'change_history_event',
    attributes: {
      taskID: 26030,
      eventType: 'added_issue',
      eventUser: 'V. ',
      eventDate: '2023-12-14 22:46:40.164066',
      claimType: 'Supplemental Claim',
      readableEventType: 'Added Issue',
      claimantName: 'Bob Smithbarton',
      details: {
        benefitType: 'vha',
        issueType: 'Caregiver | Eligibility',
        issueDescription: 'idk',
        decisionDate: '2023-12-07',
        disposition: null,
        decisionDescription: null,
        withdrawalRequestDate: null
      }
    }
  }
}
```
It would be much nicer if all of the attributes were flattened up to the top level so you could loop through using something like a standard map
 
 ```javascript
 events.map((event) => event.eventType)
 ```

2024-02-13 23:29 UTC, TylerBroyles approved these changes
Looks good to me. Good job!

2024-02-20 16:47 UTC, brandondorner approved these changes

2024-02-20 18:09 UTC, merged