APPEALS-30239 - Create and Format ‘View History’ table
department-of-veterans-affairs/caseflow pull request #20791
Opened 2024-02-12 18:18 UTC by csheepy

Resolves [APPEALS-30239](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Frontend component for individual claim history table

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Write components(s) to create table with data.
    - [ ] History is sorted from most recent to oldest activity.
    - [ ] Data is sorted in rows and aligned to columns with the following headers: Date and Time, User, Activity, Details.
    - [ ] Information can be sorted ascending/descending based on Date and Time, User or Activity.
    - [ ] Information can be filtered by User or Activity columns.
    - [ ] Up to 15 activities will display on each page and subsequent pages will be created accordingly.

## Testing Plan

1. Log in as VHAADMIN 
2. Navigate to VHA decision review queue and pick an in progress task
3. Click the view history button
4. A table should appear with dummy data
5. Verify the correct default sort, column names, etc from the AC

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue
<img width="1216" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/17840614/8a56106d-c302-4740-bc7b-500aaf4c3ff1">
<img width="1135" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/17840614/ff7cfb03-1262-4e38-a6e0-b6a4cd1ac5d2">

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-02-12 21:24 UTC, almorbah approved these changes
Looks good to me

2024-02-12 22:43 UTC, TylerBroyles requested changes
Looks pretty good. There are some events that probably won't show up right now and some queue table oddities but overall good job.

2024-02-12 22:43 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +  const addedIssueFragment = (details) => {
You could make this a bit more dry by converting this into a react fragment itself and reusing it in the completed disposition fragment and the withdrawn issue fragment.

```jsx
  const AddedIssueFragment = (details) => {
    return <React.Fragment>
      <b>Benefit type: </b>{details.benefitType}<br />
      <b>Issue type: </b>{details.issueType}<br />
      <b>Issue description: </b>{details.issueDescription}<br />
      <b>Decision date: </b>{details.decisionDate}<br />
    </React.Fragment>;
  };
  
  // Then you can use it like this
  const withdrewIssueFragment = (details) => {
    return <React.Fragment>
      <AddedIssueFragment {...details} />
      <b>Withdrawal request date: </b>{details.withdrawalRequestDate}<br />
    </React.Fragment>;
  };

```

2024-02-12 22:43 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +        valueName: 'Activity',
The user column and the Activity column need one additional property since they use client side filters. If you do not give them the full tableData, they will only be able to build the filters from the 15 tasks on the current page which will not be correct. This situation is pretty unlikely to occur on this page since 16+ events is a lot for one claim, but it could happen. Of course, the dummyData variable will have to be changed to use the real events later. 

You will also need the anyFiltersAreSet: true property if you want the clear filters link inside of the filter popup to work for some reason that I don't remember right now.

```jsx
  tableData: dummyData,
  anyFiltersAreSet: true,
```

2024-02-12 22:43 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +    slowReRendersAreOk
We should be able to get rid of the slowReRendersAreOk since all of the events will have a uuid that we can use as a key so something like this will work eventually. You could even throw an id into your dummy data and just generate a uuid for now with the uuidv4() function that I think we should have available.

```jsx
getKeyForRow={(_rowNumber, event) => event.id}
```

2024-02-12 22:43 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +    columns={[
We might want to pull these columns out of here and make their definitions elsewhere (either in another file or as constants above it) to slim down the QueueTable tag and separate the column logic from it a bit.

2024-02-12 22:43 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +    case 'Claim created':
There are a few event cases that are missing.

1. :added_decision_date - which is identical in the UI to added_issue other than a different event type name
2. Cancelled task - which is very similar to claim closed except it has no decision date since it was cancelled. All the other wording is exactly the same except probably the readable event type but I'm not even 100% sure about that.
3. Removed issue - Should be the same as added issue I think, but with Removed request date: eventDate. This one is missing from the UI figma since it was discovered/remembered later and I unfortunately don't remember where the slack thread for it was.

2024-02-13 21:34 UTC, TylerBroyles requested changes
Looking good. There are a couple of mismatches in the case statement, but that's about all that I see.

2024-02-13 21:34 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +    case 'Claim status - In progress':
You might have to use the event types instead of the readable names anyhow because of cancelled (if we care since cancelled tasks shouldn't be reachable in the UI anyhow), but the P in Progress is capitalized in the readable name I think.

```suggestion
    case 'Claim status - In Progress':
```

2024-02-13 21:34 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +    case 'Cancelled task':
There's an unfortunate problem with this. In the spreadsheet they wanted the readable name for cancel to also be "Claim closed". Then again, they might not even care enough and to be honest they could never get to this page for a cancelled task anyhow since it doesn't show up in the UI like it would in the spreadsheet.

2024-02-13 21:34 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +    case 'Added issue':
This is actually Added Issue, but I don't think it should be since it should probably match the other issue types that are lower cased. If you change it in the claim history event it will fix it here, but I think some tests might need to be altered.

2024-02-13 22:11 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2024-02-22 16:00 UTC, brandondorner submitted a review, later dismissed

2024-02-22 19:43 UTC, brandondorner approved these changes

2024-02-22 19:44 UTC, merged