Your Correspondence - In Progress Tab
department-of-veterans-affairs/caseflow pull request #20888
Opened 2024-02-20 18:17 UTC by Rnmarshall93

Resolves [Your Correspondence - In Progress Tab](https://jira.devops.va.gov/browse/APPEALS-35479)

# Description
This PR introduces a functional In Progress tab for the correspondence page. It contains sorting functionality for each of the columns as well as filtering for VA DOR and Task type.

## Acceptance Criteria
- [x] Code compiles correctly

## Testing Plan

1. Enter the correspondence queue with user JOLLY_POSTMAN
2. Navigate to the in progress tab.
3. use the up and down arrows on each column to verify that its respective row is being sorted from A-Z or Z-A depending on which toggle you have active (It starts with A-Z)
4. Open the receipt date filter, this has 4 options to test. Between dates, after date, before date, and on date.
5. Fill in the date picker with some data on the table, and ensure that the amount of items within the column are updated to match.
6. Select any of the types of filter available for the task filter, and after checking it, ensure that only that type remained in the table.

# Frontend
## User Facing Changes
 - [x] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 
<img width="1285" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/110805785/99c9c438-c8b4-43f2-9831-12af79a4190f">
|
<img width="1301" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/110805785/f6c2fe3c-2f32-49b2-b0cd-f1f9d0afb418">

code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [X] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [X] No new code climate issues added

2024-02-20 18:20 UTC, wmedders21 commented on app/models/task_filter.rb
> +    # binding.pry
remove comment

2024-02-20 18:21 UTC, wmedders21 commented on app/models/queue_column.rb
> +    nil
a method that returns nil?

2024-02-21 02:55 UTC, jimfoley25 commented on app/models/tasks/correspondence_task_filter.rb
> +  end
```
  def filter_by_va_dor(date_info)
    date_type, first_date, second_date = date_info.split(",")

    case date_type
    when "0"
      filter_between_dates(first_date, second_date)
    when "1"
      filter_before_date(first_date)
    when "2"
      filter_after_date(first_date)
    when "3"
      filter_on_date(first_date)
    end
  end

  private

  def filter_between_dates(start_date, end_date)
    tasks.joins(:appeal)
         .where("correspondences.va_date_of_receipt > ? AND correspondences.va_date_of_receipt < ?",
                Time.zone.parse(start_date),
                Time.zone.parse(end_date))
  end

  def filter_before_date(date)
    tasks.joins(:appeal).where("correspondences.va_date_of_receipt < ?", Time.zone.parse(date))
  end

  def filter_after_date(date)
    tasks.joins(:appeal).where("correspondences.va_date_of_receipt > ?", Time.zone.parse(date))
  end

  def filter_on_date(date)
    tasks.joins(:appeal).where("DATE(correspondences.va_date_of_receipt) = (?)", Time.zone.parse(date))
  end
```

2024-02-21 03:01 UTC, jimfoley25 commented on app/models/tasks/correspondence_task_filter.rb
> +  end
```
def filtered_tasks
  va_dor_params = filter_params.select { |param| param.include?('col=vaDor') }
  task_column_params = filter_params.select { |param| param.include?('col=taskColumn') }

  va_dor_params.each do |param|
    value_hash = Rack::Utils.parse_nested_query(param).deep_symbolize_keys
    @tasks = filter_by_va_dor(value_hash[:val])
  end

  task_column_params.each do |param|
    value_hash = Rack::Utils.parse_nested_query(param).deep_symbolize_keys
    @tasks = filter_by_task(value_hash[:val])
  end

  @tasks
end
```

2024-02-21 14:08 UTC, HunJerBAH requested changes
This is fantastic!! Really well written. Just a handful of comments to remove and one suggestion for refactoring the test cases to be within queue_helper.rb for other table work.

2024-02-21 14:08 UTC, HunJerBAH commented on client/app/queue/components/TaskTableColumns.jsx
> +    // enableFilter: true,
remove comment please!

2024-02-21 14:08 UTC, HunJerBAH commented on spec/feature/queue/correspondence/correspondence_cases_spec.rb
> +      visit "/queue/correspondence?tab=correspondence_in_progress&page=1&sort_by=vaDor&order=asc"
Maybe not a lift for this PR, but with the amount of column testing we need to do for our table work, these test cases could probably be put into the **queue_helper.rb** so that we can reuse them with the other tabs.

2024-02-21 14:17 UTC, HunJerBAH commented
There seems to be a failing snapshot. Please run `cd ~/appeals/caseflow/client && yarn jest` to find out which snapshot is failing. Once you know the failing test, you can update the snapshot by running:
`cd ~/appeals/caseflow/client && yarn jest --updateSnapshot test/app/path/to/file/here`.
If you are already in the /client directory after the first command, you can just run the yarn jest --update command.

There are also some tests that need to be updated in:
1. `add_related_correspondence_spec`
2. `submit_intake_form_spec`
3. `correspondence_controller_spec`
4. `mail_tasks_confirm_spec`
5. `intake_spec.rb`
6. `tasks_related_to_an_existing_appeal_spec`
7. `correspondence_cases_spec`
8.  `correspondence_intake_processor_spec`
9. `correspondence_documents_efolder_uploader_spec`
to have an `appeal_id` since the new relationship was added to the correspondence_task model.

2024-02-21 14:19 UTC, HunJerBAH commented on app/models/tasks/correspondence_task.rb
> +  belongs_to :appeal, class_name: "Correspondence", foreign_key: :appeal_id
This might be my own ignorance, but why is this relation being set to `appeal` instead of `correspondence`? Is it so that the tasks will play nice with the correspondence model?

I see this `appeal_id` association is causing issues with our tests, so I wanted to make sure this won't be an issue for us in the future if we add this association.

2024-02-21 21:24 UTC, jimfoley25 approved these changes

2024-02-21 22:57 UTC, merged