APPEALS-31187
department-of-veterans-affairs/caseflow pull request #20950
Opened 2024-02-26 19:29 UTC by csheepy

Resolves [APPEALS-31187](https://jira.devops.va.gov/browse/APPEALS-31187)

# Description
Updates the change history table to use the backend data

## Acceptance Criteria
- [ ] Code compiles correctly
- [x] All controller methods for individual claim history view are updated to no longer return mock data, if required
- [ ] All front-end methods are updated to not use a mock request body, if required
- [x] Modify change history workflow to call appropriate service class methods and coordinate the flow of real data from request to response, if required 

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below
2. Log in as VHAADMIN
3. Navigate to the decision review queue and click one
4. Click the view history button
5. verify that the claim history table now shows the data for that individual claim instead of dummy data

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

<img width="1180" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/17840614/022356f0-3acc-4cb8-97d5-4b5ddff74929">

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-02-27 15:58 UTC, TylerBroyles requested changes
Looks pretty solid. The completed task status is missing decision date data. It was probably left out of that particular block because it wasn't needed for anything besides issue or disposition data in the CSV. I assume that is supposed to be the disposition date, but I'm not really sure.

![Uploading image.png…]()

2024-02-28 16:30 UTC, pamatyatake2 commented on app/services/claim_change_history/claim_history_event.rb
> +      end
minor nitpicking i think this method can be refactored.

2024-02-28 16:35 UTC, pamatyatake2 commented on app/services/claim_change_history/claim_history_service.rb
> +  def today_with_1_day_buffer
any specific reason for adding 1 day buffer?

2024-02-28 16:43 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_service.rb
> +  def today_with_1_day_buffer
It fixes flaky tests. If you start with a date in the future by 1 full day then it will always match the current day. It's never a problem since you can't create things in the future.

2024-02-28 16:48 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_event.rb
> +      end
Yeah if you just do DateTime.parse it's roughly the same thing. It's also slow as dirt.

2024-02-28 17:43 UTC, pamatyatake2 submitted a review, later dismissed
LGTM

2024-02-28 18:18 UTC, TylerBroyles submitted a review, later dismissed

2024-02-29 19:28 UTC, brandondorner approved these changes

2024-02-29 20:17 UTC, merged