APPEALS-39907
department-of-veterans-affairs/caseflow pull request #20952
Opened 2024-02-26 20:16 UTC by breedbah

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-03-01 14:25 UTC, msteele96 reviewed
Just wanted to get ahead of things and do a quick review here. I noticed that x-ray tests are still being written too. Looking forward to seeing a sample show up in my inbox.

2024-03-01 14:25 UTC, msteele96 commented on app/mailers/transcript_file_issues_mailer.rb
> +                   "https://caseflowdemo.com/queue/appeals/#{appeal_id}"
This is no longer the link for the main demo instance. It is now https://demo.appeals.va.gov/ and you must be on GFE and VPN

2024-03-01 14:25 UTC, msteele96 commented on app/mailers/transcript_file_issues_mailer.rb
> +                 when :prod, :prodtest, :preprod
We're going to want separate urls for each env in the prod cluster

2024-03-01 14:25 UTC, msteele96 commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +  def perform(id:, file_name:)
Why are we adding a file_name and not using it?

2024-03-01 14:25 UTC, msteele96 commented on app/jobs/hearings/download_transcription_file_job.rb
> +  end
hearing.external_id checks if it is legacy or ama and then grabs either uuid or vacols_id whichever is appropriate

2024-03-01 14:25 UTC, msteele96 commented on app/jobs/hearings/get_webex_recordings_list_job.rb
> +    to = 1.day.ago.in_time_zone("America/New_York").end_of_day
This will need to be updated at a later point, we are still deciding between the transition to a webhook or just a faster interval of running the job. Currently we will exceed the maximum amount of recordings we can pull in one GET recording list call

2024-03-01 14:25 UTC, msteele96 commented on app/jobs/hearings/get_webex_recordings_list_job.rb
> +    to = 1.day.ago.in_time_zone("America/New_York").end_of_day
More of an FYI than anything else

2024-03-01 15:57 UTC, breedbah commented on app/mailers/transcript_file_issues_mailer.rb
> +                 when :prod, :prodtest, :preprod
All seperated

2024-03-01 16:25 UTC, breedbah commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +  def perform(id:, file_name:)
I think its being used on line 78

def send_file(topic, extension, link)
    file_name = create_file_name(topic, extension)
    Hearings::DownloadTranscriptionFileJob.perform_later(download_link: link, file_name: file_name)
 end

2024-03-01 16:27 UTC, breedbah commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +  def perform(id:, file_name:)
Nevermind, still looking into that one

2024-03-01 16:39 UTC, breedbah commented on app/jobs/hearings/download_transcription_file_job.rb
> +  end
File_name is needed so we can access the docket number which is one of the things we are rendering in the template

2024-03-01 16:39 UTC, breedbah commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +  def perform(id:, file_name:)
File_name is needed so we can access the docket number which is one of the things we are rendering in the template

2024-03-01 18:35 UTC, msteele96 requested changes

2024-03-01 18:35 UTC, msteele96 commented on app/jobs/hearings/get_webex_recordings_list_job.rb
> +      topic_num += 1
What is the topics for?

2024-03-01 18:35 UTC, msteele96 commented on app/views/layouts/transcript_file_issues.html.erb
> +    <h1><%= @subject %></h1>
```suggestion
```

2024-03-01 18:35 UTC, msteele96 commented on app/mailers/transcript_file_issues_mailer.rb
> +  default cc: "OITAppealsHelpDesk@va.gov"
Can we send to a different address in every env except prod?

2024-03-01 18:35 UTC, msteele96 commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +    appeal_id = Appeal.find_by(stream_docket_number: docket_number)&.uuid || VACOLS::Folder.find_by(tinum: docket_number)&.ticknum
Is docket number guaranteed to be unique? @minhazur9

2024-03-01 18:35 UTC, msteele96 commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +  def perform(id:, file_name:)
@minhazur9 can you answer this?

2024-03-01 18:35 UTC, msteele96 commented on app/jobs/hearings/download_transcription_file_job.rb
> +    hearing.external_id
```suggestion
    hearing.appeal.external_id
```

2024-03-01 18:35 UTC, msteele96 commented on app/jobs/hearings/download_transcription_file_job.rb
> +    hearing.external_id
my bad on the first suggestion

2024-03-01 18:35 UTC, msteele96 commented on app/jobs/hearings/get_webex_recordings_list_job.rb
> +      topic_num += 1
@minhazur9

2024-03-01 19:43 UTC, minhazur9 commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +    appeal_id = Appeal.find_by(stream_docket_number: docket_number)&.uuid || VACOLS::Folder.find_by(tinum: docket_number)&.ticknum
Did some research and it looks like its not. Multiple appeals can have the same docket number which means they are in different appeal streams. Getting the appeal through the hearing id portion of the route may be a better option

2024-03-01 20:01 UTC, minhazur9 commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +  def perform(id:, file_name:)
Yeah, the file_name needs to be there as an argument so we have a way to access appeal info for the link. We extract the docket number and hearing id from the name

2024-03-01 20:09 UTC, minhazur9 commented on app/mailers/transcript_file_issues_mailer.rb
> +  default cc: "OITAppealsHelpDesk@va.gov"
I think so but what should be the address?

2024-03-01 20:11 UTC, minhazur9 commented on app/jobs/hearings/get_webex_recordings_list_job.rb
> +      topic_num += 1
topics is how we are extracting the docket number and hearing id so we can get the appeal

2024-03-01 20:19 UTC, minhazur9 commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +    appeal_id = Appeal.find_by(stream_docket_number: docket_number)&.uuid || VACOLS::Folder.find_by(tinum: docket_number)&.ticknum
Pushed up new changes on this portion of the code. Will be checking if an AMA appeal with this docket number exists first and then get the appeal through the hearing_id or legacy appeal if not

2024-03-04 16:51 UTC, msteele96 commented on app/jobs/hearings/get_webex_recordings_details_job.rb
> +                end
Requesting a slight refactor for readability. Can we find the hearing by itself and store that as a variable, then find the appeal_id by doing hearing.appeal.external_id?

2024-03-04 20:21 UTC, msteele96 commented on app/mailers/transcript_file_issues_mailer.rb
> +                 when :staging
```suggestion
                 when :uat
```

2024-03-04 20:22 UTC, msteele96 commented on app/mailers/transcript_file_issues_mailer.rb
> +                 when :staging
I just saw that we use this as the deploy env in other places in code

2024-03-04 20:25 UTC, msteele96 commented on app/mailers/transcript_file_issues_mailer.rb
> +                 when :staging
and confirmed the result in the UAT console

2024-03-04 20:45 UTC, msteele96 commented on app/mailers/transcript_file_issues_mailer.rb
> +    "BID_Appeals_UAT@bah.com"
@minhazur9 Just.messaged you about this, let's limit this to UAT only. We don't want to send prodtest data to a non VA address

2024-03-04 21:20 UTC, breedbah commented on app/mailers/transcript_file_issues_mailer.rb
> +    "BID_Appeals_UAT@bah.com"
updated

2024-03-04 21:20 UTC, breedbah commented on app/mailers/transcript_file_issues_mailer.rb
> +                 when :staging
updated

2024-03-04 21:20 UTC, breedbah commented on app/mailers/transcript_file_issues_mailer.rb
> +    when :staging
updated

2024-03-06 13:05 UTC, msteele96 submitted a review, later dismissed

2024-03-07 16:32 UTC, msteele96 approved these changes

2024-03-07 16:32 UTC, merged