Piedram/appeals 40988
department-of-veterans-affairs/caseflow pull request #20992
Opened 2024-02-29 19:06 UTC by piedram

Resolves [APPEALS-40988](https://jira.devops.va.gov/browse/APPEALS-40988)

# Description
As a Caseflow Developer, I need to update seed data to populate the NOD column when seeding correspondences, so that we can test NOD and NON NOD correspondences

## Acceptance Criteria
- [ ] Code compiles correctly

In the create_correspondences method in db/seeds/correspondence.rb, add a new block that generates correspondences where: NOD is true and status is 'unassigned'

## Testing Plan

After running the new migration and executing the seed file for correspondence check if
- [] new column `nod` in `correspondence table` the value by default is `false`.
- [] new correspondence value is created in the  `correspondence table `  with a nod column like `true` when package_document_type_id = 15.

![image (37)](https://github.com/department-of-veterans-affairs/caseflow/assets/110848569/4303210b-63b1-46ac-95de-8d8f344c9dcd)

![image (38)](https://github.com/department-of-veterans-affairs/caseflow/assets/110848569/f30f0330-ceab-4276-aa8f-59d6944406ff)

-[] status is 'unassigned'.

![image (39)](https://github.com/department-of-veterans-affairs/caseflow/assets/110848569/b1168174-4e1e-42e6-95ec-f2ec144ca7e0)

2024-03-04 15:14 UTC, cacevesva requested changes

2024-03-04 15:14 UTC, cacevesva commented on app/services/correspondence_auto_assign_logger.rb
> +      @batch.num_nod_packages_assigned += 1
Refactor Instance variables:
Reek Violation
  [4]:InstanceVariableAssumption: CorrespondenceAutoAssignLogger assumes too much for instance variable '@batch'

2024-03-04 15:14 UTC, cacevesva commented on app/services/correspondence_auto_assign_logger.rb
> +      @batch.num_nod_packages_unassigned += 1
Refactor Instance variables:
Reek Violation
  [4]:InstanceVariableAssumption: CorrespondenceAutoAssignLogger assumes too much for instance variable '@batch'

2024-03-04 22:02 UTC, piedram commented on app/services/correspondence_auto_assign_logger.rb
> +      @batch.num_nod_packages_unassigned += 1
Done

2024-03-04 22:02 UTC, piedram commented on app/services/correspondence_auto_assign_logger.rb
> +      @batch.num_nod_packages_assigned += 1
Done!

2024-03-05 17:00 UTC, cacevesva commented on db/schema.rb
> +    t.index ["package_document_type_id"], name: "index_correspondences_on_package_document_type_id"
Is this suppose to be there or was added in?
I think this needs to be removed.

2024-03-06 18:03 UTC, cacevesva approved these changes

2024-03-06 18:03 UTC, merged