Sean c/appeals 35194 3
department-of-veterans-affairs/caseflow pull request #21001
Opened 2024-03-01 19:02 UTC by seancva

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-03-05 17:16 UTC, TylerBroyles requested changes
Looks great. Functionality is all there, my only comments (other than the developer comment in the Jira item) are about the tests.

2024-03-05 17:16 UTC, TylerBroyles commented on spec/feature/queue/judge_assignment_spec.rb
> +      safe_click "#Assign-task-button-id-1"
These should really be click_button "Submit" or "Task assign" using the constant like the other two test files. It's okay to use ids for hard to reach fields that have variable text, but for a button that should always be the same, I think we should use it's value.

2024-03-05 17:16 UTC, TylerBroyles commented on spec/feature/queue/scm_judge_assignment_spec.rb
> +          expect(page).to have_content("Task reassigned to #{judge_two.full_name}", wait: 10)
I would remove these waits. These tests have never been flaky on the test suite and they run fine locally for me without the waits.

2024-03-05 17:16 UTC, TylerBroyles commented on spec/fixes/investigate_scm_cant_reassign_spec.rb
> +      safe_click "#Assign-task-button-id-1"
Same as the above testing comments, although I don't really know what this "fixes" directory is.

2024-03-05 17:16 UTC, TylerBroyles commented on spec/models/tasks/specialty_case_team_assign_task_spec.rb
> +  describe ".available_actions" do
This might have to be updated based on that admin task action later.

2024-03-05 17:16 UTC, TylerBroyles commented on spec/feature/queue/specialty_case_team_queue_spec.rb
> +          safe_click "#Assign-task-button-id-1"
Same thing as the rest of the test comments.

2024-03-05 17:16 UTC, TylerBroyles commented on spec/feature/queue/specialty_case_team_queue_spec.rb
> +        expect(find("h1")).to have_content("Specialty Case Team cases")
This should be grouped together with the other scenario. There's no reason to have two setups for a couple of text checks.

2024-03-05 21:01 UTC, TylerBroyles submitted a review, later dismissed
Looks good to me. Good job.

2024-03-07 16:14 UTC, TylerBroyles approved these changes
Looks good!

2024-03-08 20:01 UTC, brandondorner approved these changes

2024-03-08 20:01 UTC, merged