APPEALS-38744 Update AMA Hearing Case Affinity Days Lever
department-of-veterans-affairs/caseflow pull request #21013
Opened 2024-03-04 17:39 UTC by kristeja

Resolves [APPEALS-38744](https://jira.devops.va.gov/browse/APPEALS-38744)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-03-04 20:24 UTC, craigrva requested changes

2024-03-04 20:24 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +      .where("distribution_task.assigned_at <= ?", 0.days.ago)
`.where("distribution_task.assigned_at <= ?", 0.days.ago)` is functionally the same as doing `.where("distribution_task.assigned_at <= ?", Time.zone.now)`. The `assigned_at` value for the distribution_task will never be greater than `Time.zone.now`, so this filter isn't really doing anything for us.

Also, we have the method `with_held_hearings` which filters using `.where(hearings: { disposition: "held" })`, so you're probably better off using and chaining from that method instead of adding the same call here

2024-03-04 20:24 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +    where.not(hearings: { disposition: "held", judge_id: HearingRequestDistributionQuery.ineligible_judges_id_cache })
`where.not` negates the entire clause in the parenthesis, so the resulting WHERE portion of the SQL looks like this:
`...AND "hearings"."disposition" = 'held' AND "hearings"."disposition" != 'held'...` which filters out every record on the table.

The ineligible judges work causes AMA hearing cases where the hearing was held by an ineligible judge to be distributed regardless of time waiting. Any cases where a hearing was held by an eligible judge are either being filtered through `most_recent_held_hearings_exceeding_affinity_threshold` or by using the `not_genpop_appeals` method call in the HearingRequestDistributionQuery. We shouldn't be trying to distribute anything that is still within its affinity window in the `only_genpop_appeals` method.

2024-03-04 20:31 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +    CaseDistributionLever.send(lever) == "infinite"
There are methods `omit?` and `infinite?` on the CaseDistributionLever model that check this

2024-03-06 04:21 UTC, kristeja commented on app/models/concerns/distribution_scopes.rb
> +    []
the reason why we are returning an empty array in the end: when the lever value is omit then it will return `nil` and It will break while distributing the appeals as we are doing flatten on main result, but not compact.

2024-03-27 18:05 UTC, closed without merging