IsaiahB/appeals-42953
department-of-veterans-affairs/caseflow pull request #21318
Opened 2024-04-01 17:36 UTC by IsaiahBar

Resolves [CorrespondencesAppeal model does not follow naming convention](https://jira.devops.va.gov/browse/APPEALS-42953)

# Description
Change naming covention of CorrespondenceAppeal model

## Acceptance Criteria
- [ ] Code compiles correctly

2024-04-01 18:27 UTC, wmedders21 requested changes

2024-04-01 18:27 UTC, wmedders21 commented on db/migrate/20231204193100_create_correspondences_appeals.rb
> +class CreateCorrespondenceAppeals < Caseflow::Migration
Can't change lines of a previous migration - need to make a new migration

2024-04-01 18:27 UTC, wmedders21 commented on db/migrate/20231204195133_add_safe_indices_to_correspondences_appeals.rb
> +class AddSafeIndicesToCorrespondenceAppeals < Caseflow::Migration
Can't change lines of a previous migration - need to make a new migration

2024-04-01 18:27 UTC, wmedders21 commented on app/models/correspondences_appeal.rb
> +class CorrespondenceAppeal < ApplicationRecord
the file name must also be updated to correspondence_appeal.rb

2024-04-01 18:27 UTC, wmedders21 commented on spec/models/correspondences_appeal_spec.rb
> +RSpec.describe CorrespondenceAppeal, type: :model do
Update the file name to correspondence_appeal_spec.rb

2024-04-02 19:14 UTC, HunJerBAH commented on db/migrate/20240401185955_create_correspondence_appeals.rb
> +end
I think this extra `end` is preventing the migration from running and causing the test failures.

2024-04-03 17:56 UTC, closed without merging