Conditionally render banner alerts based on which environment it is deployed on
department-of-veterans-affairs/caseflow pull request #21367
Opened 2024-04-10 14:15 UTC by seanrpa

Resolves [Add visual indication for which non-production environment is being accessed](https://jira.devops.va.gov/browse/APPEALS-36292)

# Description
I'm conditionally rendering alerts in the QueueApp component of different types and message indicating which env it is deployed to.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-04-12 15:41 UTC, craigrva requested changes

2024-04-12 15:41 UTC, craigrva commented on client/app/components/AppFrame.jsx
> +    {env === 'prodtest' && (<Alert type="error">This is the {env} environment!</Alert>)}
I think that it might make more sense to try and consolidate these into a single alert type, and check to see if the env isn't `prod`. After looking at it locally, I think making the type "warning" would be best to cover all environments to get more color contrast than "info" and make it more obvious to us than "success"

2024-04-16 13:43 UTC, seanrpa commented on client/app/components/AppFrame.jsx
> +    {env === 'prodtest' && (<Alert type="error">This is the {env} environment!</Alert>)}
Consolidated, `demo` has slightly different language so I'll add another component for that. Otherwise, I've cut the repeats down.

2024-09-11 19:21 UTC, craigrva requested changes

2024-09-11 19:21 UTC, craigrva commented on client/app/queue/QueueApp.jsx
> +
Whitespace that can be removed

2024-09-11 19:21 UTC, craigrva commented on client/app/components/Alert.jsx
> +
Whitespace that can be removed

2024-09-17 18:01 UTC, craigrva approved these changes

2024-09-18 20:26 UTC, craigrva requested changes

2024-09-18 20:26 UTC, craigrva commented on client/app/styles/_main.scss
> +  color: $color-gray-dark !important;
`!important` is causing a lint warning: https://github.com/department-of-veterans-affairs/caseflow/actions/runs/10928191204/job/30336038575?pr=21367#step:7:2

I don't know exactly which styles are overriding this, but is there a way that we can get the specificity up without using `!important`?

2024-09-18 20:40 UTC, seanrpa commented on client/app/styles/_main.scss
> +  color: $color-gray-dark !important;
Adding a more specific class worked.

2024-09-25 18:34 UTC, craigrva approved these changes

2024-09-26 13:51 UTC, merged