APPEALS-44187: Factory Bot Additions
department-of-veterans-affairs/caseflow pull request #21438
Opened 2024-04-23 13:59 UTC by isaiahsaucedo

Resolves [APPEALS-44187](https://jira.devops.va.gov/browse/APPEALS-44187)

# Description
Factory bot additions for CAVC appeals to prep seed data tasks towards 4317

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-05-09 19:06 UTC, craigrva requested changes
These are the new things I’ve seen that I think we’ll need to have:
- BFCORKEY should be the same between both cases
- BFCORLID should be the same between both cases
- folder.titrnum = brieff.bfcorlid
- original case should have a BFMEMID value (can be any VLJ’s SATTYID unless specified when creating)
- original case's BFAC = 1
- original case's BFDC = 3
- original case's BFCURLOC = ‘99’
- new case's BFCURLOC = ‘81’ (to put it in the distribution pool unless specified when creating)
- the CORRES record should have a SSN

2024-05-10 14:15 UTC, craigrva commented on spec/factories/vacols/case.rb
> +            vacols_case.case_issues[i] = case_issue.attributes.except("issaduser", "issadtime", "issmduser",
Will this block need to be updated like the `folder_attributes` above it for the `.except` call to work? I think it will also need a call to `.save` after setting the attributes

2024-05-10 14:32 UTC, isaiahsaucedo commented on spec/factories/vacols/case.rb
> +            vacols_case.case_issues[i] = case_issue.attributes.except("issaduser", "issadtime", "issmduser",
Good callout - Yeah I think I was seeing the correct attributes because I had been testing this with byebug so attributes are stored in memory. I updated to .save

2024-05-14 18:31 UTC, craigrva requested changes

2024-05-14 18:31 UTC, craigrva commented on spec/factories/vacols/case.rb
> +                vacols_case.bfattid = if evaluator.attorney
The `vacols_case` needs to have a `.save` added in this block after setting the BFMEMID and BFATTID or it won't be persisted.

2024-05-14 18:31 UTC, craigrva commented on spec/factories/vacols/correspondent.rb
> +      ssn { nil }
This shouldn't be in a transient block. Transients are generally used for passing in attributes that aren't actually a part of the model, but since SSN is a real attribute on the model it shouldn't be a transient. With how you're providing it through the case factory it should work without modifying this factory.

2024-05-14 19:40 UTC, isaiahsaucedo commented on spec/factories/vacols/case.rb
> +                vacols_case.bfattid = if evaluator.attorney
added .save

2024-05-14 19:40 UTC, isaiahsaucedo commented on spec/factories/vacols/correspondent.rb
> +      ssn { nil }
removed transient

2024-05-17 16:16 UTC, craigrva approved these changes

2024-05-17 20:00 UTC, merged