Pending Request Issues seeds, factories and query update
department-of-veterans-affairs/caseflow pull request #21437
Opened 2024-04-23 13:40 UTC by pamatyatake2

Resolves [APPEALS-40021](https://jira.devops.va.gov/browse/APPEALS-40021)

# Description
This PR work is to set the stage for creating a issue_modification_requests table and model with active record associations and be able to pull those issue_modification_requests by updating some of the business line query sql code, populate the newly created Pending Task Tab with seed data and determining the status of a claim/task to be pending if it is set to "active" 

1. Created a migration table - `Issue_modification_request`
2. created model for IssueModificationRequest
3. created seeds for Issue Modification Request.
4. modified query to return IssueModificationRequest records for pending tab and also the count.
5. wrote spec to test the query modification.

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Create issue_modification_requests table
- [ ] Determine the status of a claim to be pending if it is "in_progress" and has the presence of pending requests
- [ ] Create accompanying seed data and factories
- [ ] Display number in ‘Pending Request’ column to pending request count

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below
2. Open your SQL editor and run ` SELECT * FROM issue_modification_requests` -> this query should run without issue, 
3. testing seeds `bundle exec rails runner scripts/run_seed_data_file.rb IssueModificationRequest` -> In the SQL editor you can run (each of these should return 5 each) and you can change the decision_review_type to 'SupplementalClaim' and it should return same output.
```
SELECT count(*) FROM issue_modification_requestswhere request_type = 'Withdrawal' and decision_review_type = 'HigherLevelReview'

SELECT count(*) FROM issue_modification_requestswhere request_type = 'Addition' and decision_review_type = 'HigherLevelReview'

SELECT count(*) FROM issue_modification_requestswhere request_type = 'removal' and decision_review_type = 'HigherLevelReview'

SELECT count(*) FROM issue_modification_requestswhere request_type = 'Modification' and decision_review_type = 'HigherLevelReview'
```
4. Testing query modification to include - pending_request_issue 
``` 
 vha = VhaBusinessLine.singleton
vha.pending_task() 
# this should return all the records in from the table -> task table which has issue_modification_requests. 

vha.pending_tasks(filters: ["col=decisionReviewType&val=HigherLevelReview"])

vha.pending_tasks(filters: ["col=decisionReviewType&val=HigherLevelReview"]).count #to test the filtration
=> Expect 20 DecisionReviewTask of appeal_type: HigherLevelReview 

vha.pending_tasks(filters: ["col=decisionReviewType&val=SupplementalClaim"]).count 
=> Expect 2o DecisionReviewTask of appeal_type: SupplementalClaim 
```

6. 
7. - [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-04-26 21:42 UTC, TylerBroyles requested changes
This is great start. Nice job on the factory and seeding files. I have some comments about how the table is setup and it's corresponding model class. I also left a comment about the query. Let me know if you have any questions.

2024-04-26 21:42 UTC, TylerBroyles commented on app/models/pending_request_issue.rb
> +
We will need a few more associations defined in this class. At least one for each type of user that interacts with the request
```ruby
    belongs_to :requestor, class_name: "User"
    belongs_to :decider, class_name: "User", optional: true
```
If you don't have these then you can't reference the association through active record like below
```
# Or whatever we name the associations
PendingRequestIssue.first.created_by
PendingRequestIssue.first.updated_by 
```

2024-04-26 21:42 UTC, TylerBroyles commented on spec/factories/pending_request_issue.rb
> +    trait :pending_status do
I'm not sure we really need these status traits since you can set the status easily by just using something like
```ruby
FactoryBot.create(:pending_request_issue, status: :pending)
```

2024-04-26 21:42 UTC, TylerBroyles commented on app/queries/appeals_updated_since_query.rb
> +    pending_request_issues
I think this is fine since I don't think we care about this ETL::Appeal table for now. We aren't even going to allow this functionality for appeals at the moment.

2024-04-26 21:42 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +    def pending_issue_filter(query_type)
You don't need to pass in query_type since it's an accessor on the class.

```suggestion
    def pending_issue_filter
```

2024-04-26 21:42 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +      "pending_request_issues.id IS NOT NULL"
I don't think this clause is sufficient for what we want to do. The pending tab should contain tasks that have at least one active request issue ("pending" or "assigned" whichever we go with), but it shouldn't care about closed pending requests that have been denied, accepted, or cancelled.

The in progress tab should contain tasks that have no active modification requests, but if it has requests it should not show up and I don't think this works for that scenario either.

2024-04-29 13:28 UTC, almorbah commented on app/models/pending_request_issue.rb
> +  enum status: {
Would `pending: "pending"` translate to `assigned: "assigned"` in this case?

2024-04-29 14:37 UTC, almorbah commented on app/models/organizations/business_line.rb
> +    def pending_issue_filter(query_type)
Thats right... good pointing that out

2024-04-29 14:40 UTC, almorbah commented on db/migrate/20240422172720_pending_request_issue.rb
> +      t.string "status", comment: "status of the pending task"
Ahh yes

2024-04-29 20:11 UTC, pamatyatake2 commented on app/models/organizations/vha_business_line.rb
> +    [:incomplete, :in_progress, :completed, :pending]
leaving it here as well,

2024-04-29 20:13 UTC, pamatyatake2 commented on app/models/queue_tab.rb
> +  def pending_tasks
removed

2024-04-30 15:49 UTC, almorbah commented on app/models/organizations/business_line.rb
> +      "pending_request_issues.id IS NOT NULL"
`pending_request_issues.id IS NOT NULL AND pending_request_issues.status = "pending"`

2024-04-30 16:06 UTC, pamatyatake2 commented on db/migrate/20240422172720_pending_request_issue.rb
> +      t.bigint "decision_review_id", comment: "decision_issues.decision_review_id"
renaming this to "issue_modification_request" and the decision_review reference is handled using ` t.references :decision_review, polymorphic: true, null: true, index: {name: :index_issue_modification_requests_decision_review}`

2024-04-30 16:07 UTC, pamatyatake2 commented on db/migrate/20240422172720_pending_request_issue.rb
> +      t.references :updated_by, index: true, foreign_key: { to_table: :users }
done.

2024-04-30 16:07 UTC, pamatyatake2 commented on db/schema.rb
> +    t.index ["request_issue_id"], name: "index_pending_request_issues_on_request_issue_id"
t.references :decision_review, polymorphic: true, null: true, index: {name: :index_issue_modification_requests_decision_review}

2024-04-30 16:07 UTC, pamatyatake2 commented on spec/factories/pending_request_issue.rb
> +    trait :pending_status do
removed.

2024-04-30 17:29 UTC, almorbah commented on db/migrate/20240429215736_create_issue_modification_request.rb
>        t.string "request_type", limit: 20, comment:  "Pending Request Type"
Should  `request_type` be `default: "Addition"` upon initial creation? 
And we should probably change the `comment:...` text

2024-04-30 18:20 UTC, almorbah commented on app/models/organizations/business_line.rb
> +        AND COALESCE(issue_modification_requests.status, 'assigned') = 'assigned'"
Do we want to use `COALESCE()`? It returns the first non-null value in a list.
shouldn't we be getting all `issue_modification_requests with status = 'assigned'`

2024-04-30 18:28 UTC, pamatyatake2 commented on app/models/organizations/business_line.rb
> +        AND COALESCE(issue_modification_requests.status, 'assigned') = 'assigned'"
Well, using COALESCE shouldn't hurt. its like a safeguard but i am ok with removing it if you have a strong opinion about it. My reason for using COALESCE here is that if in case issue_modification_requests.status is null by any reason ( which might not be possible at all) then it would still bring those null status into pending tab.

2024-04-30 18:43 UTC, almorbah commented on app/models/organizations/business_line.rb
> +        AND COALESCE(issue_modification_requests.status, 'assigned') = 'assigned'"
I don't have a strong opinion about it. I was reading the definition of `COALESCE()` which stated it would return the first non-null value in a list, so I wondered if it would change the expected return values.  https://www.w3schools.com/sql/trysqlserver.asp?filename=trysql_func_sqlserver_coalesce.

2024-04-30 21:06 UTC, pamatyatake2 commented on app/models/organizations/business_line.rb
> +        AND COALESCE(issue_modification_requests.status, 'assigned') = 'assigned'"
my reason for adding COALESCE here is if in case `issue_modification_request.status` is null then i want that to be displayed in pending tab. probability of `status` column being  null is really low as we have added the default value to be `assigned`. so with coalesce if `issue_modification_request.status` is not null then it will always return its value from the column.  And if its null then it will return 'assigned' which will make that statement true and display it in the pending tab.

2024-04-30 21:19 UTC, almorbah commented on app/models/organizations/business_line.rb
> +        AND COALESCE(issue_modification_requests.status, 'assigned') = 'assigned'"
Thank you for this explanation

2024-05-01 14:42 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        AND COALESCE(issue_modification_requests.status, 'assigned') = 'assigned'"
Status should not ever be null. That should be a database constraint on the table imo.

2024-05-01 15:26 UTC, pamatyatake2 commented on app/models/organizations/business_line.rb
> +        AND COALESCE(issue_modification_requests.status, 'assigned') = 'assigned'"
yeah, it should never be null, and coalesce was only a safeguarding. I removed it.

2024-05-01 16:05 UTC, TylerBroyles requested changes
I left some more comments mostly around the migration and model class this time. Let me know what you think.

2024-05-01 16:05 UTC, TylerBroyles commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.datetime "approved_at", null: true, comment: "Timestamp when the request issue was closed. The reason it was closed is in closed_status."
This is decided_at in membership requests so I'm not sure if we want to copy that or not. Naming it approved_at is a bit odd since it can technically be rejected or cancelled instead of approved.

2024-05-01 16:05 UTC, TylerBroyles commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.text "decision_text", null: true, comment: "Description"
Is this the field for the admin to enter a reason for accepting or denying a request? Or is it something else? If it is the former then it should match the naming convention of the approved at field.

2024-05-01 16:23 UTC, pamatyatake2 commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.string "benefit_type", limit: 20, null: true, comment: "decision_issues.benefit_type"
Benefit types here are supposed to be VHA, compensation, education etc.  saw it being used in some other table as well so decided to use it. but i have removed it now.

2024-05-01 17:06 UTC, pamatyatake2 commented on app/models/organizations/business_line.rb
> +    # :reek:ControlParameter
removed

2024-05-01 17:06 UTC, pamatyatake2 commented on app/models/organizations/business_line.rb
> +      if @query_type == :pending
removed

2024-05-01 17:06 UTC, pamatyatake2 commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.datetime "request_date", null: true, comment: "Requested Date"
request_date removed

2024-05-01 17:06 UTC, pamatyatake2 commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.text "request_reason", null: true, comment: "request reason"
removed.

2024-05-01 20:04 UTC, almorbah submitted a review, later dismissed
This turned out to be a very nice Code! Great feedback and communication.

2024-05-01 21:13 UTC, TylerBroyles requested changes
I left a few more comments. These are mostly related to the query and the business line model. Let me know if you have any questions.

2024-05-01 21:13 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        "COALESCE(issue_modification_requests.status, '') <> 'assigned'"
I still don't think clause is restrictive enough for what we want. An example would be a task that has an HLR with 3 issue modification requests. Two are assigned, but one is approved. The database query would return 3 rows because it's a left join. The first two rows will not match because the exclusion clause <> assigned would not match. However, the 3rd row would match because it is approved so therefore the task would show up in the in_progress_tasks query. 

This query also technically affects completed and incomplete tasks as well even though that should never happen which is something to consider even though they use different task states and so it shouldn't be an issue due to that.

2024-05-01 21:13 UTC, TylerBroyles commented on spec/factories/issue_modification_request.rb
> +    decider_id { User.last.id }
decider should probably be set via a trait. When a decider is added, it should probably also update the decided_at timestamp field. We might want to make a save hook of some sort to handle that.

2024-05-01 21:13 UTC, TylerBroyles commented on spec/models/business_line_spec.rb
> +                  created_by_id: user.id,
This has to be changed to reflect the association name changes. I also prefer using the association itself and objects rather than ids when assigning fields e.g.

```ruby
requestor: user,
decider: user

# instead of
requestor_id: user.id
decider_id: user.id
```
It should also probably be impossible for those two to be the same user since one should be a non admin and the other should be an admin, but that's a different discussion.

2024-05-01 21:19 UTC, pamatyatake2 commented on spec/models/business_line_spec.rb
> +                  created_by_id: user.id,
I made the change in supplemental claim section and forgot to change it in hlr.

2024-05-02 16:08 UTC, TylerBroyles requested changes
I added some comments and suggestions about the database comments and fields. Let me know what you think.

2024-05-02 16:08 UTC, TylerBroyles commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.string "nonrating_issue_category", null: true, comment: "issue category decision_issues.non_rating_issue_category"
```suggestion
      t.string "nonrating_issue_category", null: true, comment: "The nonrating issue category of the request issue that is being modified or added by the request"
```

2024-05-02 16:08 UTC, TylerBroyles commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.datetime "withdrawal_date", null: true, comment: "if request issue was withdrawn then we save it as withdrawal date "
```suggestion
      t.datetime "withdrawal_date", null: true, comment: "The withdrawal date for issue modification requests with a request type of withdrawal"
```

2024-05-02 16:08 UTC, TylerBroyles commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.string "status", default: "assigned", comment: "status of the pending task"
```suggestion
      t.string "status", default: "assigned", comment: "The status of the issue modifications request. The possible status values are assigned, approved, denied, and cancelled"
```

2024-05-02 16:08 UTC, TylerBroyles commented on db/migrate/20240429215736_create_issue_modification_request.rb
> +      t.references :decider, index: true, foreign_key: { to_table: :users }, comment: "The user who decides approval/denial of requested issues"
```suggestion
      t.references :decider, index: true, foreign_key: { to_table: :users }, comment: "The user who decides approval/denial of the issue modification request."
```

2024-05-02 16:59 UTC, TylerBroyles requested changes
Looks good to me. Great job!

2024-05-02 16:59 UTC, TylerBroyles submitted a review, later dismissed
Looks good to me. Great job!

2024-05-06 15:33 UTC, brandondorner approved these changes

2024-05-06 15:35 UTC, merged