[APPEALS-43849]Update CAVC Affinity Implementation for AMA Dockets to…
department-of-veterans-affairs/caseflow pull request #21456
Opened 2024-04-25 02:12 UTC by samasudhirreddy

… Account for Omit/Infinity

Resolves [APPEALS-43849](https://jira.devops.va.gov/browse/JIRA-43849)

# Description
Update CAVC Affinity Implementation for AMA Dockets to Account for Omit/Infinity

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-04-25 14:30 UTC, craigrva requested changes

2024-04-25 14:30 UTC, craigrva commented on app/models/docket.rb
>    def adjust_for_genpop(scope, genpop, judge)
We don't actually use the `adjust_for_genpop` method now, it is a leftover from the prior distribution algorithm:
`scope = adjust_for_genpop(scope, genpop, judge) if judge.present? && !use_by_docket_date?`

`use_by_docket_date?` will always be true, so `adjust_for_genpop` doesn't get run. These changes should go into the `adjust_for_affinity` method.

2024-04-25 14:58 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +          JudgeTeam.judges_with_exclude_appeals_from_affinity.push(judge&.id).compact
Pushing the judge's ID into this array will cause appeals to be selected twice by the query if they are tied to the judge, becuase in `non_genpop_with_case_distribution_lever` the `genpop_base_query` is already filtering for the judge' ID

2024-04-25 15:03 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +        .where("appeals.stream_type != ?", Constants.AMA_STREAM_TYPES.court_remand)
If the lever is set to `omit`, it functionally means that all CAVC Remands are always genpop, so we don't want to filter them out at all. I think that just returning `genpop_base_query` will work here.

2024-04-25 15:05 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +      genpop_base_query
If the lever is set to omit, it functionally means that all CAVC Remands are always genpop, so in this case we would want to not return _anything_ from this method. Chaining `.none` onto the `genpop_base_query` will make the non-genpop portion of the query not return anything.

2024-04-26 15:10 UTC, craigrva requested changes

2024-04-26 15:10 UTC, craigrva commented on app/models/docket.rb
> +      result = result.or(genpop_base_query.tied_to_ineligible_judge)
This is going to add another query to execute and we want to avoid that for efficiency, so we should look at putting it into the `genpop` method in distribution_scopes.rb. There's already a check for `JudgeTeam.judges_with_exclude_appeals_from_affinity` for the `original_judge_task.assigned_to_id`; if we can combine the arrays from both the excluded judge check and ineligible judge check into a single array, that should take care of it:
```
[*JudgeTeam.judges_with_exclude_appeals_from_affinity, *HearingRequestDistributionQuery.ineligible_judges_id_cache]
```
We may need to account for the feature toggles before putting them into a single array as well.

2024-04-29 11:56 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +      genpop_base_query.none
Addressed

2024-04-29 11:56 UTC, samasudhirreddy commented on app/models/docket.rb
> +      result = result.or(genpop_base_query.tied_to_ineligible_judge)
Addressed

2024-04-29 20:26 UTC, craigrva approved these changes

2024-04-30 18:13 UTC, merged