Ryan/appeals 35475
department-of-veterans-affairs/caseflow pull request #21514
Opened 2024-04-30 20:00 UTC by sulak-j

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] On the Organization Management page permissions for the organization are listed next to each user
- [ ] At the top of the section the sentence "User Permissions"
- [ ] Each permission for an organization has a checkbox followed by its description
- [ ] The checkbox is checked if the listed user has the permission for the organization
- [ ] Deselection of permission will remove the permission from the user
- [ ] Upon selection of permission, the permission is granted to the user
- [ ] If user has admin rights, any default admin permissions are displayed, checked, and grayed out
- [ ] permission is not selectable
- [ ] If organization does not have permissions for users, the UI is not displayed
- [ ] On the Inbound Ops Organization Management page permissions for the organization are listed next to each user
- [ ] Under the "Edit current team members" header, the "Add/Remove admin rights" sentence is updated:
- Grants the ability to manage team membership and perform superuser actions. 
- [ ] Each permission for an organization has a checkbox followed by its description
Superuser: Split, Merge, Reassign
- default admin permission
Auto-Assignment
- If selected, an additional checkbox appears labeled: Receive "NOD Mail"

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-05-01 11:38 UTC, HunJerBAH commented on app/controllers/organizations/users_controller.rb
> +    # binding.pry
old pry left over

2024-05-01 13:30 UTC, HunJerBAH commented on client/app/queue/OrganizationUsers.jsx
> +          </div>
I think this container should be wrapped in a conditional so that if there are no organization permissions, the div doesn't show.

2024-05-01 13:33 UTC, HunJerBAH commented on client/app/queue/OrganizationUsers.jsx
> +  // http://localhost:3000/organizations/inbound-ops-team/test
comment should be updated or removed

2024-05-01 13:36 UTC, HunJerBAH commented on client/app/queue/OrganizationUsers.jsx
> +      const checkBoxInState = this.state.toggledCheckboxes.find((oup) => oup.permissionName == permission && oup.userId === id);
trip === needed between `oup.permissionName == permission` on line 92

2024-05-03 11:45 UTC, HunJerBAH commented on app/controllers/organizations/users_controller.rb
> +    # organization_user_permission = OrganizationUserPermission.find_by(organizations_user_id: user_id, organization_permission_id: org_permission.id)
might need to remove old comment if no longer relevant

2024-05-03 11:52 UTC, HunJerBAH commented on app/controllers/organizations/users_controller.rb
> +    else
I'm not sure if we want to shoehorn a user into having a permission if the checker denies them. I would rather an error kicks back or displays instead. Users on the page should pass the `can?` check since they are OrganizationUsers of the org on the team management page. In the off chance this method is needed in other parts of the project in the future, I think we should protect against a user not being an OrganizationUser of an org and a permission tries to get passed to them.

2024-05-03 11:55 UTC, HunJerBAH commented on app/models/user.rb
> +      end
This join table logic is getting pretty dicey to bridge **user > organizations_user > organization_user_permissions > organization_permissions**. We might need to refactor how permissions are set up or add some foreign key relationships to prevent these type of queries.

2024-05-03 11:56 UTC, HunJerBAH commented on app/services/organization_user_permission_checker.rb
> +  # user - an OrganizationUser object
great comment!

2024-05-03 11:59 UTC, HunJerBAH commented on client/app/queue/OrganizationUsers.jsx
> +      console.log(error)
might want `console.error(error)` to highlight this is an error.

2024-05-03 14:08 UTC, HunJerBAH commented on config/routes.rb
> +    # resources :test, only: [:modify_user_permission], controller: 'organizations/users'
remove test path please!

2024-05-03 14:09 UTC, HunJerBAH commented on db/schema.rb
> +    t.boolean "default_for_admin"
`null: false, default: false` doesn't seem to be showing in the schema like it is in the migration. You might need to run `bundle exec rails db:migrate` and push up the schema changes. If none happen, we might have to rollback this migration and re-run it so create the correct schema changes.

2024-05-03 14:11 UTC, HunJerBAH commented on client/constants/ORGANIZATION_PERMISSIONS.json
> +  "superuser" : {
Outside the scope of this PR, but we will probably want to move organization permissions to a SQL table so that we can add permissions without having to deploy new code.

2024-05-03 14:12 UTC, HunJerBAH commented on spec/models/organization_permission_spec.rb
> +orgUserPermissions# frozen_string_literal: true
might be a funky copy here that needs to be removed.

2024-05-03 18:09 UTC, zurbergram commented on app/controllers/organizations/users_controller.rb
> +    org_users = OrganizationsUser.where(organization_id: organization.id)
can't you get this list from the organization itself?

2024-05-03 18:11 UTC, zurbergram commented on app/controllers/organizations/users_controller.rb
> +        .where(organizations_user_id: org_user.id).pluck(:permission, :permitted, :user_id)
all of this seems incorrect, the organization ActiveRecord object should have been setup so that pulling things from the database tables individually shouldn't be necessary

2024-05-03 18:13 UTC, zurbergram commented on app/controllers/organizations/users_controller.rb
> +    org_permission = OrganizationPermission.find_by(permission: permission_name)
permission might not be unique, we should be able to `organization.organization_permissions` to find permissions for the organization and then filter those

2024-05-03 18:26 UTC, zurbergram commented on client/app/queue/OrganizationUsers.jsx
> +    };
use optional chaining `?` to reduce the statements

2024-05-03 18:27 UTC, zurbergram commented on client/app/queue/OrganizationUsers.jsx
> +          </div>
Agreed, it's better to return null instead of hidden element when something is not needed at all

2024-05-03 18:28 UTC, zurbergram commented on client/app/styles/queue/_organization_users.scss
> +  border-top-color: gray;
This is not a USWDS color

2024-05-03 18:30 UTC, zurbergram commented on client/constants/ORGANIZATION_PERMISSIONS.json
> +  }
Please undo this

This is not the intention of this file, this file exists only to list the names of permissions so we don't have magic strings floating around

All of these properties should exist on the `organization_permissions` table when doing `find_by_permission` for the values here

2024-05-03 18:33 UTC, zurbergram commented on client/constants/ORGANIZATION_PERMISSIONS.json
> +  }
Specific initial properties would go in `db/seeds/correspondence_auto_assign.rb`

2024-05-03 18:34 UTC, zurbergram commented on client/constants/ORGANIZATION_PERMISSIONS.json
> +  "superuser" : {
There's already a SQL table called `organization_permissions`

2024-05-03 18:48 UTC, tradesmanhelix commented on app/controllers/organizations/users_controller.rb
> +    org_permission = OrganizationPermission.find_by(permission: permission_name)
This is not quite how `OrganizationPermissions` work. You need an organization filter here as well.

I.e., `my_perm` can belong to organizations A, B, and C. Using `find_by` with name as the only filter will return the first match, which may or may not be the permission for the correct organization. Does that make sense?

2024-05-03 18:50 UTC, tradesmanhelix commented on app/controllers/organizations/users_controller.rb
> +    user_id = params[:userId]
Agree - there is a more efficient way of gathering this data. If you have an organization, it's trivial to get all of its permissions and all of the users with permissions for that organization.

2024-05-03 18:59 UTC, tradesmanhelix commented on app/controllers/organizations/users_controller.rb
> +    target_user = OrganizationsUser.find_by(user_id: user_id)
FWIW, these models were not built out correctly.

We should have used `references` in the migration that created this table to get this table to reference `users`. Once the correct associations are added to the models, Rails will automatically link them, so instead we can just do:

```
user = User.find(user_id_param) || current_user
target_user = OrganizationsUser.find_by(user: user)
```

I.e., we can just use models and forgo the `_id` part since Rails handles that for us. It makes for much cleaner code and helps us think in terms of related models.

Not something that needs addressed here, just want to point it out so we can hopefully use more conventional DB migration patterns in the future.

2024-05-03 19:00 UTC, tradesmanhelix commented on app/controllers/organizations/users_controller.rb
> +    if org_permission_checker.can?(
This should probably just be a private method:

```
def org_user_permission_cheker
  @org_user_permission_cheker ||= OrganizationUserPermissionChecker.new
end
```

2024-05-06 18:23 UTC, Rnmarshall93 commented on app/controllers/organizations/users_controller.rb
> +    org_permission = OrganizationPermission.find_by(permission: permission_name)
That was a really good point, I didn't think about it that way. Thank you for the clarification!

2024-05-06 22:17 UTC, Rnmarshall93 commented on client/app/queue/OrganizationUsers.jsx
> +        });
The Checkbox component only accepts styling in the form of an object, so I think its possible to move away from glamor on this, but getting it to pull out of a css file itself seems like we're going to have to refactor the Checkbox component.

2024-05-06 22:19 UTC, HunJerBAH commented on client/constants/ORGANIZATION_PERMISSIONS.json
> +  }
We can set up something similar to ACD did with lever seeding: https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/seeds/case_distribution_levers.rb#L109

2024-05-07 15:26 UTC, Rnmarshall93 commented on app/models/organization_permission.rb
> +      Constants.ORGANIZATION_PERMISSIONS.to_h
this was a mistake on creating seed data, reverting

2024-05-09 15:51 UTC, zurbergram commented on app/controllers/organizations/users_controller.rb
> +    ).find(organization.id)
Is this necessary you already have the organization record and referencing it's relationships will load them if they're not already loaded?

2024-05-09 15:56 UTC, zurbergram commented on config/routes.rb
> +get '/organizations/users/update_permission', to: 'organizations/users#modify_user_permission'
Linting issue

Is there not a namespace for `/organizations`?

2024-05-09 22:42 UTC, cacevesva requested changes

2024-05-09 22:42 UTC, cacevesva commented on Gemfile
git checkout feature/APPEALS-36284 -- Gemfile

To restore the file so it disappers.

2024-05-09 22:42 UTC, cacevesva commented on Gemfile.lock
git checkout feature/APPEALS-36284 -- Gemfile

To restore the file so it disappers.

2024-05-09 22:42 UTC, cacevesva commented on app/controllers/organizations/users_controller.rb
> +    if org_user_permission_cheker.can?(
org_user_permission_checker vs org_user_permission_cheker

possible method name issue.

2024-05-09 23:11 UTC, cacevesva commented on app/controllers/organizations/users_controller.rb
> +    )
Might want to double check your indentation

2024-05-09 23:27 UTC, cacevesva commented on db/seeds/correspondence_auto_assign.rb
Try running:
rubocop db/seeds/correspondence_auto_assign.rb
reek db/seeds/correspondence_auto_assign.rb

Please fix the offenses.

Thanks

2024-05-09 23:35 UTC, cacevesva commented on spec/controllers/organizations/users_controller_spec.rb
> +    let(:params) { { user_id = user.user_id
user_id, org_url, org_permission

Are these local variables used?

2024-05-09 23:37 UTC, cacevesva commented on spec/controllers/organizations/users_controller_spec.rb
> +    # before do
I would remove old comments

2024-05-09 23:37 UTC, cacevesva commented on spec/controllers/organizations/users_controller_spec.rb
> +  # describe "PATCH /users/#modify_user_permission" do
Please remove old comments

2024-05-09 23:42 UTC, cacevesva commented on spec/feature/queue/correspondence/inbound_ops_team_management_spec.rb
> +      scenario "Adds and removes uesr permissions" do
uesr vs user typo

2024-05-10 14:18 UTC, Rnmarshall93 commented on spec/controllers/organizations/users_controller_spec.rb
> +    let(:params) { { user_id = user.user_id
They weren't, these were a part of tests that didn't get deleted when they were moved to the correct file, fixed now 👍

2024-05-14 19:04 UTC, HunJerBAH approved these changes
Great work! This one was a bear

2024-05-14 19:37 UTC, cacevesva approved these changes

2024-05-14 20:00 UTC, merged