APPEALS-36333 first iteration of docket time goal and prior to goal
department-of-veterans-affairs/caseflow pull request #21523
Opened 2024-05-01 18:07 UTC by kristeja

Resolves [APPEALS-36333](https://jira.devops.va.gov/browse/APPEALS-36333)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-05-02 14:14 UTC, craigrva requested changes

2024-05-02 14:14 UTC, craigrva commented on app/models/dockets/hearing_request_docket.rb
> +  def docket_time_goal
`docket_time_goal` and `start_distribution_prior_to_goal` could be defined in docket.rb and use the `docket_type` parameter to determine which lever to get, but that would require changing the name of the lever `ama_hearings_docket_time_goals` because the hearing docket isn't called "hearings", it is called "hearing", so that lever isn't named correctly. If we don't want to do that, then this is fine to make it work.

2024-05-02 14:14 UTC, craigrva commented on app/models/dockets/hearing_request_docket.rb
> +    if calculate_days_for_time_goal_with_prior_to_goal > 0
This is better off being defined and called from the distribution_scopes.rb file. For the direct review and evidence submission dockets it doesn't make a big difference, but `.call` from the HearingRequestDistributionQuery will run the actual queries and then provide the results to this method which will then run another query on the result set.

2024-05-02 14:14 UTC, craigrva commented on app/models/docket.rb
> +    return docket_time_goal - start_distribution_prior_to_goal if docket_time_goal > 0
This throws `TypeError: String can't be coerced into Integer` when run

2024-05-13 17:48 UTC, craigrva requested changes

2024-05-13 17:48 UTC, craigrva commented on app/models/docket.rb
> +    docket_type == "hearing" ? "hearings" : docket_type
Fix the lever naming in seed file and in DISTRIBUTION.json instead of putting a band-aid on this

2024-05-13 17:48 UTC, craigrva commented on app/models/docket.rb
> -    ready_priority_nonpriority_appeals(priority: true, ready: true).limit(num).map(&:receipt_date)
`ready_priority_nonpriority_appeals` is where we are checking if dockets are disabled, so it can't be pulled out of here. Move the check/query you have in `nonpriority_appeals_with_time_goal` into that method instead.

2024-05-13 17:48 UTC, craigrva commented on app/models/docket.rb
> +    docket_time_goal - start_distribution_prior_to_goal if docket_time_goal > 0
If this is zero it is returning `nil` to the calling method, which is raising `NoMethodError: undefined method `>' for nil:NilClass`

2024-05-13 17:48 UTC, craigrva commented on app/models/docket.rb
> +    @start_distribution_prior_to_goal ||= CaseDistributionLever.public_send(
The return from the method being sent is already an integer, so `to_i` isn't needed. Also, this isn't accounting for the lever being disabled by the user in the UI.

2024-05-13 17:48 UTC, craigrva commented on app/models/dockets/hearing_request_docket.rb
> +    nonpriority_appeals_with_time_goal
Like the docket.rb file above, `ready_priority_nonpriority_appeals` is where we are checking if dockets are disabled, so it can't be pulled out of here.

2024-05-17 16:20 UTC, kristeja commented on app/models/docket.rb
> +    @start_distribution_prior_to_goal ||= CaseDistributionLever.public_send(
@craigrva we are actually converting it to `to_s` [here](https://github.com/department-of-veterans-affairs/caseflow/blob/ee2d6d293a700f04bd635324211ef20564d58a1f/db/seeds/case_distribution_levers.rb#L36) in the seed file. so when we are calculating the value in this method `calculate_days_for_time_goal_with_prior_to_goal ` it throws an error. so we had to convert it to `to_i`

2024-05-23 15:48 UTC, craigrva requested changes

2024-05-23 15:48 UTC, craigrva commented on app/models/docket.rb
> +    @start_distribution_prior_to_goal ||= CaseDistributionLever.public_send(
`ama_direct_review_start_distribution_prior_to_goals` is listed in the `INTEGER_LEVERS` constant in the CaseDistributionLever model, so it is coming back as an integer because of the [method_missing](https://github.com/department-of-veterans-affairs/caseflow/blob/a2d5731e6c6e919f8f0439c3b9e3490a334f4a4c/app/models/case_distribution_lever.rb#L180) override on that class regardless of what the datatype in the database is. The other docket's distribution prior to goals lever should be added to the INTEGER_LEVERS constant so that it is consistent between the dockets

2024-05-23 15:48 UTC, craigrva commented on app/models/docket.rb
> +  def calculate_days_for_time_goal_with_prior_to_goal
How is this going to account for the lever being disabled in the UI?

2024-05-23 17:44 UTC, zurbergram commented on db/seeds/case_distribution_levers.rb
> +            item: Constants.DISTRIBUTION.ama_hearing_docket_time_goals,
Renaming these values is going to require a database migration

2024-05-23 17:46 UTC, zurbergram commented on spec/models/docket_spec.rb
> +        allow_any_instance_of(Docket).to receive(:calculate_days_for_time_goal_with_prior_to_goal).and_return(0)
This is a method defined in `app/models/docket.rb` why are we mocking this out?

2024-05-30 18:28 UTC, zurbergram commented on lib/tasks/update_caste_distribution_levers.rake
> +    CaseDistributionLever.find_by_item("ama_hearings_docket_time_goals")
Why are we doing this different than how https://jira.devops.va.gov/browse/APPEALS-43681 is handling updates?

2024-05-30 18:29 UTC, zurbergram commented on lib/tasks/update_caste_distribution_levers.rake
> +    CaseDistributionLever.find_by_item("ama_hearings_docket_time_goals")
This task appears to be causing tests to fail

2024-05-30 18:38 UTC, zurbergram commented on app/models/docket.rb
Above should be fixed from
```
    lever = CaseDistributionLever.find_by_item(Constants::DISTRIBUTION[lever_item])
    lever_value = lever&.value
```
to
```
    lever_value = CaseDistributionLever.public_send(lever_item)
```

2024-06-06 18:40 UTC, amybids submitted a review, later dismissed

2024-06-10 02:18 UTC, amybids approved these changes

2024-06-10 02:18 UTC, merged