Sudhir/appeals 43851
department-of-veterans-affairs/caseflow pull request #21613
Opened 2024-05-10 04:40 UTC by samasudhirreddy

Resolves [APPEALS-43851](https://jira.devops.va.gov/browse/JIRA-43851)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-05-10 04:43 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +      results = results.or(priority.where("advance_on_docket_motions.created_at < ?", CaseDistributionLever.cavc_aod_affinity_days.days.ago))
@craigrva I was trying to modify genpop method and I am getting below error
<img width="1429" alt="Screen Shot 2024-05-09 at 11 43 27 PM" src="https://github.com/department-of-veterans-affairs/caseflow/assets/108430298/fa7c17c5-a8c3-4d70-ae46-1c2811e09a1f">

2024-05-10 15:06 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +      results = results.or(priority.where("advance_on_docket_motions.created_at < ?", CaseDistributionLever.cavc_aod_affinity_days.days.ago))
This error comes up if the joins aren't the same between the first query and what is in the `.or()` call. I think that the order of chaining in the docket `appeals()` method might matter here because we need to look at AOD status now as part of the affinity checks, and moving the `scoped_for_priority` and `scope.nonpriority` might fix the incompatible query error. I can pull the branch to my local and look at it as well.

2024-05-13 03:28 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +          exclude_affinity_and_ineligible_judge_ids
In Infinite scenario which column I need to use to filter the results with judge id's ?

2024-05-13 15:09 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +          exclude_affinity_and_ineligible_judge_ids
If a lever is set to infinite, then the genpop query for that group of CAVC appeals should return nothing because they would always be considered non-genpop.

The way the logic for cases for judges with exclude affinity and ineligible judges is being inserted should also be removed from these parts of the query generation, because those would always be considered genpop regardless of what the lever is set to. The way it is done in the [hearing request distribution query](https://github.com/department-of-veterans-affairs/caseflow/blob/Sudhir/APPEALS-43851/app/queries/hearing_request_distribution_query.rb#L57-L77) is a good example. It doesn't check for excluded or ineligible judges inside the lever queries, it does it afterward and adds that as another `.or()` in the final query generation.

2024-05-14 01:55 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +          exclude_affinity_and_ineligible_judge_ids
Addressed

2024-05-14 01:55 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +      results = results.or(priority.where("advance_on_docket_motions.created_at < ?", CaseDistributionLever.cavc_aod_affinity_days.days.ago))
Addressed

2024-05-14 14:38 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +    if FeatureToggle.enabled?(:acd_exclude_from_affinity)
This is a good way to add those checks. We just need to remove `exclude_affinity_and_ineligible_judge_ids` from the other methods which are generating a query (`generate_genpop_cavc_affinity_days_lever_query`, `genpop`) so that it isn't selecting the same case multiple times.

2024-05-14 14:42 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +        .none
Thinking on this and looking at how the query previously was, I don't think that `.none` is how we should do it. The `generate_genpop_cavc_affinity_days_lever_query` method does this:
```
genpop_base_query
        .where(
          "appeals.stream_type != ? OR original_judge_task.assigned_to_id in (?)",
          Constants.AMA_STREAM_TYPES.court_remand,
```
and I think that keeping the `stream_type !=` clause is necessary since we will want non-CAVC appeals to still be passed through this query.

2024-05-14 14:42 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +      results1 = genpop_base_query.where("advance_on_docket_motions.created_at < ?", CaseDistributionLever.cavc_aod_affinity_days.to_i.days.ago)
This doesn't need to be assigned to a variable, and the `.to_i` is not necessary; calling the lever method will should automatically return it as an integer.

2024-05-14 14:46 UTC, craigrva requested changes
We are going to need similar changes in the `non_genpop_with_case_distribution_lever` method as well to separate the queries for the `cavc_affinity_days` and `cavc_aod_affinity_days` levers

2024-05-14 16:33 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +    if FeatureToggle.enabled?(:acd_exclude_from_affinity)
Addressed

2024-05-14 16:33 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +        .none
Addressed

2024-05-14 16:33 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +      results1 = genpop_base_query.where("advance_on_docket_motions.created_at < ?", CaseDistributionLever.cavc_aod_affinity_days.to_i.days.ago)
Addressed

2024-05-14 16:40 UTC, craigrva requested changes
This is definitely close to what we need, there's one more big thing for it. In the various generate methods for each lever type, we need to make them mutually exclusive. [Here](https://github.com/department-of-veterans-affairs/caseflow/blob/Sudhir/APPEALS-43851/app/queries/hearing_request_distribution_query.rb#L92) in the hearing request distribution query is an existing example of it. The `ama_non_aod_hearing_appeals` and `ama_aod_hearing_appeals` methods are being chained to make the aod/not-aod generate methods be mutually exclusive. I think that we can actually just re-use those methods and chain them in the new generate methods that you've created. When doing that, we will want to rename those methods to not specify _hearing_ appeals and instead be docket-agnostic (ie `ama_non_aod_appeals` or `ama_aod_appeals`.

2024-05-14 16:40 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +      non_genpop_for_judge(judge)
`non_genpop_for_judge` is currently hard coded to use the `cavc_affinity_days` lever, but in this spot it needs to use `cavc_aod_affinity_days`

2024-05-14 16:40 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
>        genpop
I think we should do this the same way that it is being done with the `generate_genpop_cavc_aod_affinity_days_lever_query` method where it is starting with `genpop_base_query` and then chaining the `.where` inside of this method. That way it's consistent and more readable, instead of having the `genpop` method work for only some appeals.

2024-05-15 13:54 UTC, craigrva requested changes

2024-05-15 13:54 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +      genpop_base_query
This will need to have `.ama_aod_appeals` chained as well to keep the two lever sets mutually exclusive

2024-05-15 13:54 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +  def generate_genpop_cavc_affinity_days_lever_query
Each potential return from the `if` block needs to have `.ama_non_aod_appeals` chained to it so that the queries are mutually exclusive.

2024-05-15 13:54 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +      non_genpop_for_judge(judge, CaseDistributionLever.cavc_aod_affinity_days)
Each potential return from the if block needs to have .ama_non_aod_appeals chained to it so that the queries are mutually exclusive. That does include chaining it before `.none` in the omit path.

2024-05-15 13:54 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +  def generate_non_genpop_cavc_affinity_days_lever_query(judge)
Each potential return from the if block needs to have .ama_non_aod_appeals chained to it so that the queries are mutually exclusive. That does include chaining it before `.none` in the omit path.

2024-05-15 16:55 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +      genpop_base_query
Addressed

2024-05-15 16:55 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +  def generate_genpop_cavc_affinity_days_lever_query
Addressed

2024-05-15 16:55 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +      non_genpop_for_judge(judge, CaseDistributionLever.cavc_aod_affinity_days)
Addressed

2024-05-15 16:56 UTC, samasudhirreddy commented on app/models/concerns/distribution_scopes.rb
> +  def generate_non_genpop_cavc_affinity_days_lever_query(judge)
Addressed

2024-05-15 17:43 UTC, craigrva requested changes

2024-05-15 17:43 UTC, craigrva commented on app/models/concerns/distribution_scopes.rb
> +      .ama_non_aod_appeals
We can't chain `.ama_non_aod_appeals` here because this method is being used in both the non_aod and aod logic, `.ama_non_aod_appeals` will need to be chained in the methods that are calling it.

2024-05-16 14:04 UTC, craigrva requested changes
We need to assume that test failures are because of our code changes, unless we can prove otherwise. Only if we prove that can we change the assertions or the data setup. We may need to continue to set or change the `cavc_aod_affinity_days` lever but the `cavc_affinity_days` lever was always affecting this test file, so that one shouldn't need to be adjusted.

2024-05-16 14:04 UTC, craigrva commented on spec/models/dockets/hearing_request_docket_spec.rb
> +             ready_aod_tied_to_other_judge_in_window.uuid,
This appeal should not be distributed based on the test description

2024-05-17 17:50 UTC, craigrva requested changes

2024-05-17 17:50 UTC, craigrva commented on app/models/case_distribution_lever.rb
> +    #{Constants.DISTRIBUTION.cavc_aod_affinity_days}
Can you also add `Constants.DISTRIBUTION.ama_hearing_case_aod_affinity_days` to this list? I'm not sure why it wasn't put there when it was originally added.

2024-05-17 18:07 UTC, samasudhirreddy commented on spec/models/dockets/hearing_request_docket_spec.rb
> +        create_ready_aod_appeal(tied_judge: requesting_judge_no_attorneys, created_date: 20.days.ago)
Addressed

2024-05-17 18:07 UTC, samasudhirreddy commented on spec/models/dockets/hearing_request_docket_spec.rb
> +             ready_aod_tied_to_other_judge_in_window.uuid,
Addressed

2024-05-17 18:07 UTC, samasudhirreddy commented on app/models/case_distribution_lever.rb
> +    #{Constants.DISTRIBUTION.cavc_aod_affinity_days}
Addressed

2024-05-17 18:48 UTC, craigrva requested changes

2024-05-17 18:48 UTC, craigrva commented on spec/models/docket_spec.rb
>                expect(subject).to include appeal
Change this assertion as well, because the way it is written will allow extra appeals to be selected and this test won't catch that as long as it contains the three listed. Checking the array for its values will prevent that: 
```
expect(subject).to match_array([appeal, denied_aod_motion_appeal, inapplicable_aod_motion_appeal])
```

2024-05-17 18:59 UTC, samasudhirreddy commented on spec/models/docket_spec.rb
>                expect(subject).to include appeal
Addressed

2024-05-17 19:40 UTC, craigrva approved these changes

2024-05-17 21:13 UTC, merged