41642 - Intake: task creation
department-of-veterans-affairs/caseflow pull request #21636
Opened 2024-05-14 18:11 UTC by IsaiahBar

Resolves [Intake: task creation](https://jira.devops.va.gov/browse/APPEALS-41642)

# Description
Limit Correspondence Task creation to only users within Inbound Ops Team so that, when reports are created to view all created tasks during intake, it will be only Inbound Ops users who created the tasks

2024-05-15 18:01 UTC, HunJerBAH commented on spec/controllers/tasks_controller_spec.rb
> +        InboundOpsTeam = create(:user)
This needs to be a user instead of the organization

2024-05-15 18:25 UTC, HunJerBAH commented on app/models/user.rb
> +  scope :inbound_ops_team_user, -> { joins(:organizations).where(organizations: { type: InboundOpsTeam.name }) }
might want to add an s on the end of inbound_ops_team_users since this is a plural relation.

2024-05-15 18:28 UTC, HunJerBAH commented on db/seeds/correspondence_auto_assign.rb
> +        { css_id: "INBOUND_OPS_TEAM_USER_U3", full_name: "Ocean Breeze" }
line 124 is `MailTeam.singleton.add_user(u)` and will need to be updated to `InboundOpsTeam.singleton.add_user(u)`

2024-05-15 18:29 UTC, HunJerBAH commented on db/seeds/queue_correspondences.rb
> +    def inbound_ops_team_user
The changes in this file can be reverted since we already have users for correspondence created in db/seeds/correspondence_auto_assign.rb

2024-05-15 18:30 UTC, HunJerBAH commented on db/seeds/users.rb
> +      create_inbound_ops_team_user
The changes in this file can be reverted since we already have users for correspondence created in db/seeds/correspondence_auto_assign.rb

2024-05-15 18:31 UTC, HunJerBAH commented on app/models/tasks/correspondence_task.rb
> +      MergePackageTask.name,
These package actions can be removed since they aren't needed.

2024-05-17 16:50 UTC, HunJerBAH commented on app/models/tasks/correspondence_task.rb
> +  def before_create
this namespace needs to be changed and called in line 7 in the `before_create` callback similar to `verify_org_task_unique` method.

2024-05-17 17:16 UTC, HunJerBAH requested changes
Some changes needed to keep plurality and naming consistent from before/after, but otherwise good work!

2024-05-17 17:16 UTC, HunJerBAH commented on client/app/queue/correspondence/CorrespondenceCases.jsx
> +          inboundOpsTeamUser={props.inboundOpsTeamUser}
line 256 needs to be updated to `inboundOpsTeamUsers={props.inboundOpsTeamUsers}` since this is a plural array of CSS IDs

2024-05-17 17:16 UTC, HunJerBAH commented on client/app/queue/correspondence/CorrespondenceCases.jsx
> +  inboundOpsTeamUser: PropTypes.arrayOf(string),
needs to be updated to `inboundOpsTeamUsers: PropTypes.arrayOf(string)` since this is a plural array of CSS IDs

2024-05-17 17:16 UTC, HunJerBAH commented on client/app/queue/correspondence/correspondenceReducer/correspondenceConstants.js
> +  LOAD_INBOUND_OPS_TEAM_USER: 'LOAD_INBOUND_OPS_TEAM_USER',
needs to be updated to `LOAD_INBOUND_OPS_TEAM_USERS: 'LOAD_INBOUND_OPS_TEAM_USERS'` since this action loads plural users.

2024-05-17 17:16 UTC, HunJerBAH commented on client/app/queue/correspondence/correspondenceReducer/correspondenceReducer.js
> +  case ACTIONS.LOAD_INBOUND_OPS_TEAM_USER:
needs to be updated to `LOAD_INBOUND_OPS_TEAM_USERS: 'LOAD_INBOUND_OPS_TEAM_USERS'` since this action loads plural users.

2024-05-17 17:16 UTC, HunJerBAH commented on client/app/queue/correspondence/correspondenceReducer/correspondenceReducer.js
> +        $set: action.payload.inboundOpsTeamUser
needs to be updated to `$set: action.payload.inboundOpsTeamUsers` since this action loads plural users.

2024-05-22 14:02 UTC, HunJerBAH commented on app/models/user.rb
> +  end
Added check to check if a user is a system user

2024-05-22 14:03 UTC, HunJerBAH commented on app/models/task.rb
> -      return true if parent.appeal_type == Correspondence.name && MailTeam.singleton.user_has_access?(user)
This was validating if the user has access to the actions on the task. Since we are overriding with correspondence checks, this feels like the wrong place for this check, so we removed it.

2024-05-29 15:43 UTC, zurbergram approved these changes

2024-05-29 16:35 UTC, HunJerBAH submitted a review, later dismissed

2024-05-29 16:48 UTC, merged