Added tests and added logic to account for sct distribution
department-of-veterans-affairs/caseflow pull request #21709
Opened 2024-05-22 16:48 UTC by aferencz1987VA

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [x] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-05-22 17:42 UTC, raymond-hughes requested changes

2024-05-22 17:42 UTC, raymond-hughes commented on app/models/tasks/docket_switch/docket_switch_mail_task.rb
> +      if !parent_task.appeal.distributed_to_a_judge? || parent_task.appeal.specialty_case_team_assign_task?
Should this be 

`if !parent_task.appeal.distributed_to_a_judge? || !parent_task.appeal.specialty_case_team_assign_task?`

adding back in the ! for the specialty_case_team_assign_task

2024-05-22 17:42 UTC, raymond-hughes commented on app/models/tasks/mail_task.rb
> +      if !parent_task.appeal.distributed_to_a_judge? || parent_task.appeal.specialty_case_team_assign_task?
Same question here

2024-05-22 17:42 UTC, raymond-hughes commented on spec/factories/appeal.rb
Do we need this factory anymore?

2024-05-22 18:06 UTC, ajspotts commented on app/models/tasks/docket_switch/docket_switch_mail_task.rb
> +      if !parent_task.appeal.distributed_to_a_judge? || parent_task.appeal.specialty_case_team_assign_task?
👋 @aferencz1987VA hi my curiosity got the best of me 😄 

The bug [ticket](https://jira.devops.va.gov/browse/APPEALS-46182) references the `HearingRelatedMailTask` task [type](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/hearing_related_mail_task.rb), which I see inherits from `MailTask` so I understand the changes to that model.

However it seems that `DocketSwitchMailTask` also directly inherits from `MailTask` as well.  Admittedly I'm a little bit rusty and could be missing some context but it looks like the two `parent_if_blocking_task` methods are identical.  So I guess my question would be do we even need `parent_if_blocking_task` here if it's written the exact same way in `MailTask`?

2024-05-23 14:34 UTC, aferencz1987VA commented on app/models/tasks/docket_switch/docket_switch_mail_task.rb
> +      if !parent_task.appeal.distributed_to_a_judge? || parent_task.appeal.specialty_case_team_assign_task?
That was the same question I had for Raymond. I would imagine that it does not need to exist. I didnt write the original method so I didnt want to remove it without approval.

2024-05-23 15:14 UTC, aferencz1987VA commented on spec/factories/appeal.rb
Yes. While we have some stuff stubbed out, it still uses the factory.

2024-05-23 19:02 UTC, raymond-hughes approved these changes

2024-05-23 19:46 UTC, raymond-hughes approved these changes

2024-05-24 12:44 UTC, raymond-hughes approved these changes

2024-05-28 17:08 UTC, merged