removed eventing from create claim review
department-of-veterans-affairs/caseflow pull request #21718
Opened 2024-05-23 12:57 UTC by buddylove954

Resolves [Removing Claim Reviews (HLRs/Supplemental Claims) that's currently stored within the Event Records table in Caseflow.](https://jira.devops.va.gov/browse/APPEALS-45482)

# Description
This PR removes the creation of HLR and Supplemental claim event records

## Acceptance Criteria

- [x] There are no more backfill records created for HLRs/Supplemental Claims
- [x] Rspec test are updated to verify that the relationship works

## Testing Plan

1. Go to [Test Plan Link](https://jira.devops.va.gov/browse/APPEALS-46433)
2. Go to [XRAY Plan Link](https://jira.devops.va.gov/secure/XrayExecuteTest!default.jspa?testExecIssueKey=APPEALS-46434&testIssueKey=APPEALS-46433)

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [x] RSpec

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [x] No new code climate issues added

2024-05-28 15:34 UTC, jtsangVA commented on app/services/events/decision_review_created/create_intake.rb
> +require_dependency "events/event_record"
Why is this needed?

2024-05-28 18:28 UTC, jtsangVA commented on app/services/events/decision_review_created/create_intake.rb
> +require_dependency "events/event_record"
It shouldn't need that since it was passing before. Isn't that method also deprecated in Rails 6?

2024-05-28 18:29 UTC, jtsangVA approved these changes

2024-05-28 19:52 UTC, jtsangVA requested changes
Please also update `event_record_spec` to remove cases where HLR/SC creates an event_record

2024-05-30 14:21 UTC, jtsangVA commented on spec/models/events/event_record_spec.rb
> -      expect(higher_level_review.from_decision_review_created_event?).to eq(true)
We don't want to remove this method, it's required to track the DRCE models

2024-05-31 20:20 UTC, nkutub submitted a review, later dismissed

2024-06-03 13:45 UTC, jtsangVA submitted a review, later dismissed

2024-06-03 15:18 UTC, nkutub approved these changes

2024-06-03 16:21 UTC, merged