J hoang/appeals 40897 v2
department-of-veterans-affairs/caseflow pull request #21839
Opened 2024-06-06 18:55 UTC by jonathanh-va

Resolves [APPEALS-40987](https://jira.devops.va.gov/browse/APPEALS-40987)

# Description

- Moved actions related to issue modification requests into a new file
- Created a new modal that prompts a VHA Admin to confirm their changes when approving an issue modification request. (The actual approval functionality will be done in a different ticket.)
- On submission of this modal 
  - The pending issue modification request will be converted to a request issue object and then added to the state `addedIssues` that is stored in redux. This will allow the newly created request issue to appear in the Requested Issues section of the edit page.
  - The pending issue modification request will be removed from the Pending admin review section of the edit page.
  - The original issue from the pending issue modification request will be removed from `addedIssues`.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan
1. Open rails console `rails c` or `make c`
2. Run the following:
```
veteran = Generators::Veteran.build(file_number: "34634567", first_name: "TESTCONFIRM", last_name: "MODIFICATIONPERSON");nil

in_progress_hlr = FactoryBot.create(:higher_level_review,
           :with_vha_issue,
           :with_end_product_establishment,
           :processed,
           benefit_type: "vha",
           veteran: veteran,
           claimant_type: :veteran_claimant);nil

in_progress_hlr.create_business_line_tasks!
in_progress_hlr.reload

modified_request_issue = FactoryBot.create(:request_issue,
                                            benefit_type: "vha",
                                            nonrating_issue_category: "CHAMPVA",
                                            nonrating_issue_description: "A description of the newly added issue",
                                            decision_review: in_progress_hlr,
                                            decision_date: Time.zone.now - 10.days);nil

FactoryBot.create(:issue_modification_request,
                  decision_review: in_progress_hlr,
                  request_type: :modification,
                  nonrating_issue_category: "Camp Lejune Family Member",
                  nonrating_issue_description: "Newly modified issue description",
                  decision_date: modified_request_issue.decision_date,
                  request_issue: modified_request_issue);nil

# UUID of the claim review
in_progress_hlr.uuid
```
3. Go to Caseflow and login as a VHA Admin (VHAADMIN or VHAADMIN2)
4. Go to `/higher_level_reviews/{UUID}/edit` or you can access this page from the UI by
    - Your Queue
    - Switch product OR Switch Views
    - VHA Decision Review Queue OR Veterans Health Administration team cases (depending on previous step)
    - Pending Tasks
    - Click on the new claimant that we created in step 2.
5. Click on the dropdown for the pending modification request
6. Click on "Review issue modification request"
7. Click on "Submit request"
8. Confirm the new modal appears with the correct issues information
9. Click on "Confirm"
10. Confirm that the new issue appears in the section for "Requested issues" with the correct issue information
11. Confirm that the pending issue modification request has been removed from the "Pending admin review" section

# Frontend

## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue
![Screenshot 2024-06-06 at 10 49 02 AM](https://github.com/department-of-veterans-affairs/caseflow/assets/111081469/12201243-14ce-4c49-bac0-4cc2f71a77f3)

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the applicatio [...]

2024-06-07 16:02 UTC, TylerBroyles requested changes
This looks good. I left some comments about some minor changes and some notes about some possible larger ones that you don't have to do if you don't want to.

2024-06-07 16:02 UTC, TylerBroyles commented on client/app/intake/components/ConfirmPendingRequestIssueModal.jsx
> +          onClick: () => onSubmit()
I'm pretty sure you can just pass a reference here.
```suggestion
          onClick: onSubmit
```

2024-06-10 13:14 UTC, jonathanh-va commented on client/app/intake/reducers/common.js
> +    if (action.payload.issueModificationRequest === null) {
Thinking if I should add a new action to update the status of the pending issue request upon confirmation instead of deletion and then update the pending admin review section to display issue modification requests that are only 'assigned'

2024-06-10 13:15 UTC, jonathanh-va commented on client/app/intake/util/issueModificationRequests.js
> +    decisionDate: formatDateStr(issueModificationRequest.decisionDate),
Nope we do not, I removed the method

2024-06-10 13:15 UTC, jonathanh-va commented on client/app/intakeEdit/components/RequestCommonComponents/RequestIssueFormWrapper.jsx
> +      const decisionDate = formatDateStr(issueModificationRequest.decisionDate) ||
Nope we do not, removed the method

2024-06-10 14:13 UTC, TylerBroyles commented on client/app/intake/reducers/common.js
> +    if (action.payload.issueModificationRequest === null) {
That is currently my plan on how I think it's probably going to work in the end. Otherwise, you lose the information of what action was decided for the pending request whether it was approved, cancelled, or denied.

2024-06-10 18:00 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2024-06-10 18:10 UTC, TylerBroyles requested changes
I left a couple more comments, but that's all I noticed.

2024-06-10 18:10 UTC, TylerBroyles commented on client/app/intake/components/ConfirmPendingRequestIssueModal.jsx
> +    dispatch(removeIssue(indexOfOriginalIssue));
This should only happen if the checkbox is selected to remove the original issue right?

2024-06-10 18:10 UTC, TylerBroyles commented on client/app/intake/actions/issueModificationRequest.js
> +export const moveToPendingReviewSection = (issueModificationRequest, index) => (
I think moveToPendingReviewSection and removeFromPendingReviewSection should use the same function signature e.g. if index is first in one it should be first in both. Maybe index first since updatePendingReview is also (identifier, object)

2024-06-11 00:16 UTC, jonathanh-va commented on client/app/intake/components/ConfirmPendingRequestIssueModal.jsx
> +    dispatch(removeIssue(indexOfOriginalIssue));
Yes only if the checkbox is selected. For now the placement is incorrect but once the checkbox is implemented this should be moved.

2024-06-11 15:05 UTC, TylerBroyles commented on client/app/intake/components/ConfirmPendingRequestIssueModal.jsx
> +    dispatch(removeIssue(indexOfOriginalIssue));
Well you could do it here since you know it will switch based on the boolean value in the pendingIssueModificationRequest, but it's fine to leave to whoever implements that.

2024-06-11 15:06 UTC, TylerBroyles submitted a review, later dismissed
Looks good to me. Great job!

2024-06-11 19:14 UTC, closed without merging