Al/APPEALS-45335
department-of-veterans-affairs/caseflow pull request #22228
Opened 2024-07-18 15:23 UTC by almorbah

Resolves [APPEAL-45335](https://jira.devops.va.gov/browse/APPEALS-45335)

# Description
As a VHA user, I need to include the Reassign Cases to CAMO events/actions and status during selection of filters on the Generate task report so that I can generate a report with all VHA decision review history. 

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

BEFORE:
<img width="1501" alt="Screenshot 2024-07-16 at 10 59 01 AM" src="https://github.com/user-attachments/assets/3d8530cf-e644-4ded-a45a-6e3d35d75567">

AFTER:
<img width="1510" alt="Screenshot 2024-07-16 at 10 44 05 AM" src="https://github.com/user-attachments/assets/87a22a46-35f8-47a2-a33f-b6e08e413d1e">

BEFORE:
<img width="1512" alt="Screenshot 2024-07-16 at 10 59 34 AM" src="https://github.com/user-attachments/assets/17228ff1-e978-45c7-82ca-a0504077f205">

AFTER:
<img width="960" alt="Screenshot 2024-07-16 at 11 00 36 AM" src="https://github.com/user-attachments/assets/a697b083-cd7d-4268-ab41-03212766c73d">

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-07-18 20:15 UTC, TylerBroyles requested changes
Functionality looks good. I left a couple of comments about some differences from the figma and one where it looks like there's a lot of repeated code. Let me know if you have any questions.

2024-07-18 20:15 UTC, TylerBroyles commented on client/app/nonComp/pages/ReportPage.jsx
> +            <h4>System</h4>
These 3 sections are all duplicated code except for the H4 tag. I think it can be DRY'd up a bit.

2024-07-18 20:15 UTC, TylerBroyles commented on client/constants/REPORT_TYPE_CONSTANTS.json
>    "SPECTIFIC_EVENT_OPTIONS": [
```suggestion
  "SPECIFIC_EVENT_OPTIONS": [
```

2024-07-18 20:15 UTC, TylerBroyles commented on client/app/nonComp/pages/ReportPage.jsx
> +        {errorMessage ? <div className="usa-input-error-message">{ errorMessage }</div> : null}
The error line looks a bit weird with 3 sets of checkbox css classes now
![image](https://github.com/user-attachments/assets/e249d354-ca2e-40fa-8d0f-3f46aeb096d4)

2024-07-18 20:15 UTC, TylerBroyles commented on client/constants/REPORT_TYPE_CONSTANTS.json
> +          "label": "Approval Of Request",
The capitalization is different from the figma for all of the request checkbox labels. Only the first word is capitalized for all of these options.

2024-07-18 20:16 UTC, brandondorner requested changes

2024-07-18 20:16 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.jsx
> +  paddingRight: '25rem',
I did some tinkering and I think we should remove the paddingRight and justifyContent and instead replace it with `gap: 3em`.

With the 25rem and space-between combined it starts to look a little squished on smaller screens that we still need to account for (small laptop screens)

Before:
<img width="526" alt="image" src="https://github.com/user-attachments/assets/0cfe9ea0-f3e3-4338-a75d-302cd5ec63dc">

After:
<img width="526" alt="Screenshot 2024-07-18 at 2 38 55 PM" src="https://github.com/user-attachments/assets/2da326b1-66fb-454f-aede-67d1acbab046">


You can tinker with `3em` a little if you want but it looks the closest to the design I could get while still looking good on smaller laptop screens.

2024-07-18 20:16 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.jsx
> +  paddingRight: '25rem',
The checkboxes also get a little out of sync as the text start wrapping but I don't think this is a big deal for now. We'll see if design feels otherwise but I'm fine not bringing it up

2024-07-18 20:16 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.jsx
> +const OuterContainerStyling = css({
`OuterContainerStyling` - `outerContainerStyling` to match the others in this file

2024-07-18 20:34 UTC, almorbah commented on client/app/nonComp/pages/ReportPage.jsx
> +        {errorMessage ? <div className="usa-input-error-message">{ errorMessage }</div> : null}
Let me ask Heather what is the take on this

2024-07-18 20:38 UTC, almorbah commented on client/app/nonComp/pages/ReportPage.jsx
> +  paddingRight: '25rem',
Roger that - yes, I agree with you. I was trying to match the Figma as much as possible

2024-07-19 02:13 UTC, almorbah commented on client/app/nonComp/pages/ReportPage.jsx
> +        {errorMessage ? <div className="usa-input-error-message">{ errorMessage }</div> : null}
I changed it to be one line to the left of the page

2024-07-19 02:14 UTC, almorbah commented on client/app/nonComp/pages/ReportPage.jsx
> +            <h4>System</h4>
I made a new local component that is reusable

2024-07-19 18:25 UTC, almorbah commented on client/app/nonComp/pages/ReportPage.jsx
> +        {errorMessage ? <div className="usa-input-error-message">{ errorMessage }</div> : null}
<img width="1512" alt="Screenshot 2024-07-19 at 12 47 27 PM" src="https://github.com/user-attachments/assets/0fc69310-708c-4bf2-86ea-509c55332d87">
I got back from Heather to make this error as such!

2024-07-22 16:54 UTC, brandondorner requested changes

2024-07-22 16:54 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.jsx
> -    control,
Breaking some of this component out seems to have caused a breakage in functionality

<img width="1174" alt="Screenshot 2024-07-22 at 11 53 14 AM" src="https://github.com/user-attachments/assets/82ea0842-9644-4df1-9dc8-ee38e1608b39">


It looks like only the most recent clicked checkbox group gets processed. This causes validation issues and only accounts for one checkbox group (System, General, Requests) at a time

2024-07-22 16:54 UTC, brandondorner commented on client/app/nonComp/pages/ReportPage.jsx
> +              header= "System"
This is nitpicky style stuff but `header= "System"` -> `header="System"` and the same for the other two CheckBoxes component uses

2024-07-22 17:18 UTC, pamatyatake2 commented on client/app/nonComp/pages/ReportPage.jsx
> +          {errorMessage ? <div className="usa-input-error-message">{ errorMessage }</div> : null}
I think you will need to add that ```<Alert >``` here as well for specificStatus

2024-07-22 17:45 UTC, almorbah commented on client/app/nonComp/pages/ReportPage.jsx
> +          {errorMessage ? <div className="usa-input-error-message">{ errorMessage }</div> : null}
The UX Team wanted that part of the code to preview this type of error displayed. I'll double check again.

2024-07-24 15:21 UTC, TylerBroyles requested changes
I only noticed one small thing. The functionality and error handling ui looks great.

2024-07-24 15:21 UTC, TylerBroyles commented on client/app/nonComp/pages/ReportPage.jsx
> +      <h4>{header}</h4>
It probably shouldn't generate an empty heading 4 tag if there is no header since it doesn't make sense from a DOM perspective and it adds a bit of spacing that otherwise wouldn't be there.

2024-07-24 15:24 UTC, almorbah commented on client/app/nonComp/pages/ReportPage.jsx
> +      <h4>{header}</h4>
alright i can solve that by `{header && <h4>{header}</h4> }`

2024-07-24 15:45 UTC, TylerBroyles submitted a review, later dismissed
Looks good to me. Great job!

2024-07-24 15:46 UTC, brandondorner approved these changes

2024-07-24 19:56 UTC, pamatyatake2 submitted a review, later dismissed
LTGM

2024-07-24 20:10 UTC, brandondorner submitted a review, later dismissed

2024-07-25 16:14 UTC, brandondorner approved these changes

2024-07-25 16:14 UTC, merged