adding logic to bring in issue-modification request and updating the …
department-of-veterans-affairs/caseflow pull request #22238
Opened 2024-07-18 22:50 UTC by pamatyatake2

…csv logic

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-07-25 23:42 UTC, TylerBroyles requested changes
This looks really solid. You did a great job on it. I left some comments about various things but I mainly focused on the SQL and the event creation for now. Let me know if you have any questions.

2024-07-25 23:42 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +          get_claim_status.current_claim_status,
I don't think get_claim_status and current_claim_status are very well named alias's for what this is actually doing. It's an array of all issue modification request statuses for the decision review id and type that is being joined. Given the way that it is being used I think it might even be better to return a boolean true or false if it is currently in a pending state or not.

2024-07-25 23:42 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        INNER JOIN LATERAL (
We might be able to do something like this since we only care about if it's "pending" or not. I didn't test this out much since it's more of a theory thing to trim some redundant parsing in the ruby for a variable that should already be known by that point.
```sql
INNER JOIN LATERAL (
  SELECT CASE
    WHEN EXISTS (
      SELECT 1
      FROM issue_modification_requests imr
      WHERE imr.decision_review_id = request_issues.decision_review_id
        AND imr.decision_review_type = request_issues.decision_review_type
        AND imr.status = 'assigned'
    ) THEN true
    ELSE false
  END AS current_claim_status
) get_claim_status ON true;
```

2024-07-25 23:42 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        LEFT JOIN issue_modification_requests imr ON imr.decision_review_id = tasks.appeal_id
I don't like the double join that much because of all the coalescing that it requires. I wonder if we couldn't group these into a CTE or even a single lateral join with an or WHERE/ON clause. We probably need to do a bit of testing on it to see which way ends up faster. If it's not much different then reducing the coalescing would be nice unless I'm wrong about the indexes. We could also do a select double join union and then join to the union (maybe laterally) and that might avoid it as well.

2024-07-25 23:42 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_event.rb
> +    def create_pending_status_events(change_data)
This isn't good enough to properly represent the appeal state from in_progress -> pending -> in_progress more than a single cycle. I don't know how to do it right now either though.

2024-07-25 23:42 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_event.rb
> +        imr_versions.map do |version|
Since this is just a dumb loop to push all edited events it will make an edited event for every action that happens to an existing issue modification request. If a user approves it will generate and edited even if it all they did was approve it. Likewise for denial and cancellation. I'm not sure if we want that behavior or not.

2024-07-26 14:03 UTC, pamatyatake2 commented on app/services/claim_change_history/claim_history_event.rb
> +      request_event_type = "request_#{change_data['issue_modification_request_status']}"
You are correct here, i straight up went with rejection so all the event were created for rejection. instead of denied so i will have to update that.

2024-07-26 14:15 UTC, pamatyatake2 commented on app/services/claim_change_history/claim_history_event.rb
> +        imr_versions.map do |version|
I think i will use this method for overall status, edit and approval/denial.

2024-07-30 23:51 UTC, TylerBroyles requested changes
I left a bunch more comments. The event parsing looks better now that it does not have editing events for all decisions. Let me know if you want to discuss anything.

2024-07-30 23:51 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_service.rb
> +    if task_id &&
This whole if block can probably be extracted to another method to process the standalone pending event if any modification requests are still pending on a task's claim. It can probably be moved into the above if block as well since it also is directly tied to the !is_processed boolean.

2024-07-30 23:51 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_service.rb
> +    @processed_issue_modification_task_ids = Set.new
This should probably have a attr_reader for it as well and maybe a comment about what it is actually doing. It's the tracker for a singular task to add on the standalone pending event if there are any pending issue modification requests on an individual task's claim. It's a bit hard to infer that this is only for tracking the pending state of a task from just the name of the variable alone.

2024-08-01 16:16 UTC, pamatyatake2 commented on app/services/claim_change_history/claim_history_event.rb
> +      cancelled: "Claim closed",
per Heather, this should only be in description not in the activity.

2024-08-02 14:51 UTC, TylerBroyles requested changes
I left some more comments. Functionality seems all good to me except the pending filtering so this is mostly code cleanup now. Let me know if you have any questions.

2024-08-02 14:51 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_event.rb
> +      # if decided date is nil and status is cancelled then we should display edited info and edited user.
Does this comment still make sense here? It doesn't seem to have much to do with what this hash is showing.

2024-08-02 14:51 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_service.rb
> +  # been processed so that it prevents the duplicate entry of pending event based on change_ data.
I would move this down into the method where the processed_issue_modification_task_id is being used.
```suggestion
  # been processed so that it prevents the duplicate entry of pending event based on change_data.
```

2024-08-02 14:59 UTC, pamatyatake2 commented on app/models/organizations/business_line.rb
> +        LEFT JOIN users updator ON updator.id = itv.version_updated_by_id::int
I removed this updater. and used requestor and decider from issue_modification_request

2024-08-02 16:10 UTC, pamatyatake2 commented on app/services/claim_change_history/claim_history_service.rb
> +       !change_data["version_has_status"] && !is_processed
removed.

2024-08-02 16:11 UTC, pamatyatake2 commented on app/services/claim_change_history/claim_history_event.rb
> +      addition: "What do we want to add here? " # Questions to be asked
removed.

2024-08-06 14:54 UTC, TylerBroyles requested changes
Just a couple of comments while I test out the other stuff.

2024-08-06 14:54 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        LEFT JOIN versions v on v.id = itv.first_id AND v.item_type = 'IssueModificationRequest'
Do we have to rejoin to versions here since we already have the array_agg of all the versions for each IMR coming from the first CTE join?

2024-08-06 14:54 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_event.rb
> +    def same_transaction?(change_data)
This method name reads as a generic method when it's really more of a specific method for determining if issue modification requests were in the same transaction as the previous issue modification request. I would just make the name a little more reflective of what it is actually comparing.

2024-08-07 00:30 UTC, TylerBroyles submitted a review, later dismissed
Whew. Looks good to me. Thanks for sticking with it. I only left one optional comment. If you decide to act on it, let me know and I'll approve it again.

2024-08-07 00:30 UTC, TylerBroyles commented on app/services/claim_change_history/claim_history_event.rb
> +      if (imr_last_decided_row?(change_data) &&
If you move the boolean check into another method and use that here it fixes the complexity warnings. If you decide to do it, let me know and I'll approve it again.

```ruby
    def create_in_progress_status_event(change_data)
      in_progress_system_hash_events = pending_system_hash
        .merge("event_date" => (change_data["decided_at"] ||
          change_data["issue_modification_request_updated_at"]))

      if should_create_imr_in_progress_status_event?(change_data)
        from_change_data(:in_progress, change_data.merge(in_progress_system_hash_events))
      end
    end

    def should_create_imr_in_progress_status_event?(change_data)
      (imr_last_decided_row?(change_data) &&
        (!imr_decided_in_same_transaction?(change_data) || change_data["previous_imr_decided_at"].nil?)) ||
        (change_data["previous_imr_created_at"].nil? ||
          !imr_created_in_same_transaction?(change_data) &&
          %w[cancelled denied approved].include?(change_data["issue_modification_request_status"]))
    end
```

2024-08-07 14:03 UTC, TylerBroyles approved these changes
Reapproval

2024-08-13 15:15 UTC, brandondorner approved these changes

2024-08-13 15:15 UTC, merged