Combination/appeals 50951 50966 50980
department-of-veterans-affairs/caseflow pull request #22250
Opened 2024-07-22 16:11 UTC by calvincostaBAH

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-07-25 16:58 UTC, craigrva requested changes

2024-07-25 16:58 UTC, craigrva commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +  context "#should_distribute?" do
I don't think that we need to have these tests since we aren't overriding the inherited method

2024-07-25 16:58 UTC, craigrva commented on spec/models/vacols/aoj_case_docket_spec.rb
> +  context ".nod_count" do
We should be able to remove this test as well

2024-07-25 16:58 UTC, craigrva commented on spec/models/vacols/aoj_case_docket_spec.rb
> +  context ".nonpriority_decisions_per_year" do
We should be able to remove this test as well

2024-07-25 16:58 UTC, craigrva commented on spec/repositories/aoj_appeal_repository_spec.rb
> +describe AojAppealRepository, :all_dbs do
We need to look at this test file to see what needs updated and removed. The test data wasn't changed to be `BFAC = 3` so I'm not sure if it is really doing anything for us.

2024-07-25 16:58 UTC, craigrva commented on app/models/vacols/aoj_case_docket.rb
> +      case when APPEALS.BFAC = '7' then 1 else 0 end CAVC, PREV_TYPE_ACTION,
I think this needs to be updated for the value of `PREV_TYPE_ACTION` because the BFAC will never be 7 here. I also am making a note to check the usage of this because I think it is only for generating the appeals ready to distribute CSV and I'm not sure how we should handle that yet

2024-07-25 16:58 UTC, craigrva commented on app/models/vacols/aoj_case_docket.rb
> +        case when APPEALS.BFAC = '7' then 1 else 0 end CAVC, PREV_TYPE_ACTION,
I think this also needs to be updated for the value of `PREV_TYPE_ACTION` because the BFAC will never be 7 here

2024-07-25 18:40 UTC, craigrva requested changes

2024-07-25 18:40 UTC, craigrva commented on app/repositories/aoj_appeal_repository.rb
> +    def regular_non_aod_docket_count
We should be able to remove this because the existing method in `case_docket` will cover both legacy and legacy AOJ appeals

2024-07-25 18:40 UTC, craigrva commented on app/repositories/aoj_appeal_repository.rb
> +    def docket_counts_by_month
We should be able to remove this because the existing method in `case_docket` will cover both legacy and legacy AOJ appeals

2024-07-25 18:42 UTC, seanrpa commented on app/repositories/aoj_appeal_repository.rb
> +    def docket_counts_by_month
removed

2024-07-25 18:42 UTC, seanrpa commented on app/repositories/aoj_appeal_repository.rb
> +    def regular_non_aod_docket_count
gone

2024-07-25 18:45 UTC, craigrva requested changes

2024-07-25 18:45 UTC, craigrva commented on app/models/dockets/aoj_legacy_docket.rb
> +  def ready_priority_nonpriority_legacy_appeals(priority: false)
We should be able to remove this since this docket will be disabled by the legacy docket lever

2024-07-25 18:45 UTC, craigrva commented on app/models/dockets/aoj_legacy_docket.rb
> +  def distribute_appeals(distribution, style: "push", priority: false, genpop: "any", limit: 1, range: nil)
Since this doesn't change from the parent `legacy_docket` and calls methods that are redefined here, can we remove it?

2024-07-26 12:32 UTC, craigrva approved these changes

2024-07-26 13:40 UTC, merged