APPEALS-51087: Rewrite Api::V1::VaNotifyController#notification_update Controller Action to No Longer Utilize Redis
department-of-veterans-affairs/caseflow pull request #22295
Opened 2024-07-25 15:02 UTC by noahhansen-gov

https://jira.devops.va.gov/browse/APPEALS-51087

# Description
Please explain the changes you made here.
As a Board user who reviews notification audit records, I need all pertinent information (including statuses and recipient information) to be persisted correctly so that a comprehensive audit trail can be intact around all Veteran correspondence
## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-07-25 17:21 UTC, ammitche2 commented
.

2024-07-26 03:34 UTC, ThorntonMatthew requested changes
Please review my comments whenever you have a moment and let me know what you think. Thank you!

2024-07-26 03:34 UTC, ThorntonMatthew commented on app/controllers/api/v1/va_notify_controller.rb
> +    send "notification_update"
```suggestion
    send_sqs_message
    render json: { message: "Email Notification successfully updated: ID #{required_params[:id]}" }
```

What do you think about getting rid of the `notification_update` method and leaving this one?

2024-07-26 03:34 UTC, ThorntonMatthew commented on app/controllers/api/v1/va_notify_controller.rb
> +    Rails.logger.error("#{error.message}\n#{error.backtrace.join("\n")}")
In the error message, could you please add the external id and notification type in case we need to search for them in the logs?

2024-07-26 03:34 UTC, ThorntonMatthew commented on app/controllers/api/v1/va_notify_controller.rb
> +      "#{notification_type_param}_update": "#{id_param}:#{status_param}"
These two key-value pairs will not be looked at on the other side of the workflow and can be removed.

2024-07-26 03:34 UTC, ThorntonMatthew commented on app/controllers/api/v1/va_notify_controller.rb
> +    render json: { message: "Email Notification successfully updated: ID #{required_params[:id]}" }
`"Email Notification...`

Could the hard-coded "Email" word be replaced with the interpolation of the value of `params[:notification_type]`? That way SMS ones will pop up as well.

2024-07-26 03:34 UTC, ThorntonMatthew commented on app/controllers/api/v1/va_notify_controller.rb
> +      message_group_id: "VANotifyStatusUpdate"
What do you think about making this a constant and then us updating the ProcessNotificationStatusUpdateJob's [filter_messages_by_group_id method](https://github.com/department-of-veterans-affairs/caseflow/blob/c60bf5fee59cbcc0d98d3d620f1590dd58a3ea02/app/jobs/process_notification_status_updates_job.rb#L199-L201) to pull it in as what's being compared to. That way they'd be guaranteed to be in sync (unless someone really did some "reconfigurations").

2024-07-26 03:34 UTC, ThorntonMatthew commented on app/controllers/api/v1/va_notify_controller.rb
> +  def notification_update
A YARD doc comment on this controller action would be helpful in case others ever had to come and revisit this part of the code. We've updated it 3 times so far in the last year or so, so we'll likely be back!

2024-07-26 15:23 UTC, ThorntonMatthew approved these changes

2024-07-26 15:23 UTC, merged