SeanC/APPEALS-42317 | Migrate existing Supplemental Claim Remands to Remand records via script
department-of-veterans-affairs/caseflow pull request #22359
Opened 2024-07-31 16:27 UTC by seancva

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-08-01 16:37 UTC, TylerBroyles requested changes
I left a couple of comments. Once those are addressed an we decide on how to handle the Remands view I'll review it again. Let me know if you have any questions.

2024-08-01 16:37 UTC, TylerBroyles commented on spec/models/supplemental_claim_spec.rb
> +          expect(supplemental_claim.type).to eq(SupplementalClaim.name)
This is really testing the .new method rather than the valid? method. It shouldn't be placed in here since it's essentially testing a let variable.

2024-08-01 16:37 UTC, TylerBroyles commented on db/migrate/20240723152034_backfill_supplemental_claims_type_column.rb
> +class BackFillSupplementalClaimsTypeColumn < Caseflow::Migration[6.0]
I think changing the version of this to [6.0] does weird things since it's subclassed. I'm still not sure if the project as a whole has decided to skip over Caseflow::Migration or not since it still uses [5.1]. We might have to ask about that since some migrations still inherit from it and some that are using AR Migration [6.0].

2024-08-01 16:37 UTC, TylerBroyles commented on db/migrate/20240723152034_backfill_supplemental_claims_type_column.rb
> +          SET type=(CASE WHEN decision_review_remanded_id IS NOT NULL THEN 'Remand'
This is not good enough since we have to avoid changing DTA errors to Remands. You have to make sure the type is appeal instead of HLR.

2024-08-01 16:37 UTC, TylerBroyles commented on db/migrate/20240723152034_backfill_supplemental_claims_type_column.rb
> +          SET type='';
The type should probably be set back to "SupplementalClaim" since ActiveRecord really does not like a blank type field. We also have a default "SupplementalClaim" on that column in the schema so I'm not sure how that would work out to be honest.

2024-08-06 14:37 UTC, TylerBroyles requested changes
One small comment about batching, but other than that looks good.

2024-08-06 14:37 UTC, TylerBroyles commented on db/migrate/20240723152034_backfill_supplemental_claims_type_column.rb
> +      execute <<-SQL
If you are going to do the down in batches then the up should probably also be in batches.
```ruby
    SupplementalClaim.in_batches do |batch|
      batch.update_all(
        <<-SQL.squish
          type = CASE
                  WHEN decision_review_remanded_id IS NOT NULL AND decision_review_remanded_type = 'Appeal' THEN 'Remand'
                  ELSE 'SupplementalClaim'
                 END
        SQL
      )
```

2024-08-06 15:32 UTC, TylerBroyles commented on db/migrate/20240723152034_backfill_supplemental_claims_type_column.rb
> +    SupplementalClaim.in_batches.update_all type: 'SupplementalClaim'
That's roughly the same thing as what already happens with update_all. It translates down to that SQL but in batches of 1000.

2024-08-06 16:12 UTC, TylerBroyles approved these changes
Looks good to me. Nice job!

2024-08-09 20:05 UTC, brandondorner approved these changes

2024-08-09 20:05 UTC, merged