J hoang/appeals 44940
department-of-veterans-affairs/caseflow pull request #22428
Opened 2024-08-08 04:54 UTC by jonathanh-va

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-08-09 17:46 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        remand_task_ids AS (
This works but will be a bit worse for performance than just adding a clause to the SupplementalClaim union like below. Remands are already included via the appeal_type "SupplementalClaim" so a subquery seems like an extra bit of work that the query shouldn't have to do.
```sql
-- Add this if the claim type filter includes Remand
WHERE supplemental_claims.type = 'Remand'
```

2024-08-10 05:08 UTC, jonathanh-va commented on spec/models/business_line_spec.rb
> +          expect(subject.entries.count).to eq(2)
Correcto, fixed this 👍

2024-08-12 20:25 UTC, TylerBroyles requested changes
Left a couple of small comments about the filter, but that should be the last things I have to discuss.

2024-08-12 20:25 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        if query_params[:claim_type].include?(Remand.name) && query_params[:claim_type].include?(SupplementalClaim.name)
I think the entire sc_type_filter can be covered by this line
```ruby
" AND #{where_clause_from_array(SupplementalClaim, :type, query_params[:claim_type]).to_sql} "
```
which will roughly generate something like below if you set a filter for hlrs and remands which is perfectly valid sql
```sql
AND "supplemental_claims"."type" IN ('HigherLevelReview', 'Remand')
```

2024-08-12 20:25 UTC, TylerBroyles commented on app/models/organizations/business_line.rb
> +        # claim_type_filter, -> this now runs only for HLR query
You can either leave it the way you have it or return the claim type filter back to running for both blocks for sql and doing a specific check for remands.

It might end up looking something like this
```ruby
    def claim_type_filter
      if query_params[:claim_type].present?
        temp_claim_types = query_params[:claim_type].dup

        if query_params[:claim_type].include?(Remand.name)
          temp_claim_types.push "SupplementalClaim"
        end

        " AND #{where_clause_from_array(Task, :appeal_type, temp_claim_types).to_sql} "
      else
        " AND tasks.appeal_type IN ('HigherLevelReview', 'SupplementalClaim' ) "
      end
    end
```
This requires a bit less conditional handling between the two and it's still valid sql. I'm not sure how it might affect the query to not have the base appeal type filter on the query since it might use that to exclude Appeals in some check (probably not too likely due to the tasks assigned to index though)

2024-08-12 22:12 UTC, jonathanh-va commented on app/models/organizations/business_line.rb
> +        # claim_type_filter, -> this now runs only for HLR query
thank you for the suggestion, I went ahead and implemented it the way you suggested. Looks so much better than all the conditionals

2024-08-13 13:51 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2024-08-15 20:14 UTC, brandondorner approved these changes

2024-08-15 20:14 UTC, merged