APPEALS-52892: For all legacy appeal states/notifications check status in VACOLS
department-of-veterans-affairs/caseflow pull request #22455
Opened 2024-08-12 16:05 UTC by noahhansen-gov

Resolves [For all legacy appeal states/notifications check status in VACOLS](https://jira.devops.va.gov/browse/APPEALS-52892)

# Description
An additional check is made within AppellantNotification#handle_errors
This check ensures that an appeal is active before sending a notification
Both Appeal and LegacyAppeal have access to the "active?" method that returns a boolean
If an appeal is active, the notification continues as normal
if an appeal is NOT active, we abort any further action with that notification

## Acceptance Criteria
- [x] Code compiles correctly

## Testing Plan
spec tests

# Best practices

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [x] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [x] No new code climate issues added

2024-08-13 13:50 UTC, msteele96 requested changes

2024-08-13 13:50 UTC, msteele96 commented on spec/models/appellant_notification_spec.rb
> +          InitialTasksFactory.new(task.appeal).create_root_and_sub_tasks!
I'd like to move this to a before block for the context block. For ease of use you can `let(:appeal) { task.appeal }` in with the rest of them

2024-08-13 13:50 UTC, msteele96 commented on app/models/prepend/va_notify/appellant_notification.rb
> +    fail InactiveAppealError, appeal["uuid"] if !appeal.active?
2 minor changes here:

1. UUID is for AMA only. We need to use external_id which handles both AMA and Legacy
2. When you pass the argument can you use `appeal.external_id` so we're consistent across the codebase

2024-08-13 13:50 UTC, msteele96 commented on app/models/prepend/va_notify/appellant_notification.rb
> +    def status
Does this do anything?

2024-08-13 15:14 UTC, noahhansen-gov commented on app/models/prepend/va_notify/appellant_notification.rb
> +    def status
This helps with the error message `AppellantNotification::InactiveAppealError: The appeal status is inactive for appeal with id 2096907`

2024-08-15 15:27 UTC, msteele96 approved these changes

2024-08-15 16:53 UTC, merged