Al/APPEALS-45334 Individual change history table which includes Reassign Cases to CAMO events
department-of-veterans-affairs/caseflow pull request #22483
Opened 2024-08-14 17:07 UTC by almorbah

Resolves [APPEALS-45334](https://jira.devops.va.gov/browse/APPEALS-45334)

# Description
 As a VHA user, I need to view an individual change history table which includes Reassign Cases to CAMO events/actions and status so that I can review a comprehensive VHA decision review history. 

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-08-15 17:09 UTC, brandondorner requested changes

2024-08-15 17:09 UTC, brandondorner commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +    const requestModificationDetails = { ...details, ...requestDetails };
This could be 
```
    const requestModificationDetails = { ...details, ... modificationRequestDetails };

```

No need for `requestDetails`

2024-08-15 17:09 UTC, brandondorner commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +    const RequestIssueModificationDetails = { ...requestDetails, ...detailsExtended };
Similar to above, you can do
```
    const RequestIssueModificationDetails = { ... modificationRequestDetails, ...detailsExtended };

```
and get rid of `requestDetails`

Also this should be camel case
`requestIssueModificationDetails`

2024-08-15 18:17 UTC, brandondorner requested changes

2024-08-15 18:17 UTC, brandondorner commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +      setIsOpen((isOpen) => !isOpen);
This should be 
```
      setIsOpen(!isOpen);
```

2024-08-15 18:17 UTC, brandondorner commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +      setIsOpen((isOpen) => !isOpen);
And the eslint line can be removed after this

2024-08-15 18:20 UTC, brandondorner requested changes

2024-08-15 18:20 UTC, brandondorner commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +      break;
Not a big deal either way but I don't think we need a `break` in the default case

`break` keeps the switch case to continue going down the chain but since we are at the end of the chain I don't think it's needed

2024-08-16 02:08 UTC, TylerBroyles requested changes
Nice job covering all the scenarios. Most of the feedback is around making the code more DRY since it seems like a lot of the html lines/snippets are very similar to each other. There are also a few instances of the wrong variables being used and possibly some overlap on new and old issue content that we might need to clarify a bit. Let me know if you have any questions.

2024-08-16 02:08 UTC, TylerBroyles commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +        { chunk.includes(requestIssueModificationDetails.eventType) ? <OriginalDetailsFragments {...row} /> : null }
The row that's being passed down here is being used in almost the same way as the details in the fragments above so we might want to double check again that the old/new issue information is correct in all of the cases that need both.

2024-08-16 13:49 UTC, pamatyatake2 commented on spec/feature/non_comp/individual_claim_history_spec.rb
> +    dropdown_filter.find("label", text: "Approval of request - issue addition (1)", match: :prefer_exact).click
We can convert this sort and dropdown logic to a separate method so that it can be reuse everywhere making it DRY. Some thing like
```
def click_filter_option(filter_text)
sort = find("[aria-label='Filter by Activity']").click
    sort.click

    dropdown_filter = page.find(class: "cf-dropdown-filter")
    dropdown_filter.find("label", text: filter_text, match: :prefer_exact).click
end
```

2024-08-16 13:57 UTC, pamatyatake2 commented on spec/feature/non_comp/individual_claim_history_spec.rb
> +    expect(table_row).to have_content("Approval of request - issue modification")
We can write this expectation as a separate method passing table_row and array or expectation_hash. something like below and it can help with DRYing the code

expect_attributes(table_row, ["Approval of request - issue modification", " Request decision" ]) 
`def expect_attributes(table_row, expected_value_array)
    expected_value_array.each do | expected_value|
      expect(table_row).to have_content(expected_value)
    end
  end`

2024-08-16 14:09 UTC, pamatyatake2 commented on spec/feature/non_comp/individual_claim_history_spec.rb
> +  scenario "To have all event types" do
This particular test seems to be slow (i think its because of the double loop being used). Apart from that most of the other test seems to cover almost all of the scenario you added, due to which this test seems to be redundant. May be there is a way to simplify what you are trying to test it here and a little faster as well.

2024-08-16 14:13 UTC, almorbah commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +      setIsOpen((isOpen) => !isOpen);
Ohh cool - I was wondering what that lint error meant

2024-08-16 16:33 UTC, almorbah commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +      <b>Current issue description: </b>{details.newIssueDescription}<br />
yes, good catch! It needs to be:
```
<b>Current issue description: </b>{details.issueDescription}<br />
<b>New issue description: </b>{details.newIssueDescription}<br />
```

2024-08-16 18:20 UTC, almorbah commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +        <b>New issue type: </b>{details.newIssueType}<br />
This page is convoluted enough with lot of edge cases to account for. I would rather not extract these in this instance because it will not be as easy or clear for future changes.

2024-08-16 18:28 UTC, almorbah commented on spec/feature/non_comp/individual_claim_history_spec.rb
> +  scenario "To have all event types" do
@brandondorner We had this tested a while back when this file was create https://github.com/department-of-veterans-affairs/caseflow/pull/20646/commits/d8c32994110c61f7528d25546750f58f349ab337#diff-39d930ea71448231b993f4612aeca15a0d6658e4fbf0b0ff5bd5471c42e8441d so to preserve the test to check event types I modified it. I am open to suggestion

2024-08-16 18:28 UTC, almorbah commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +        { chunk.includes(requestIssueModificationDetails.eventType) ? <OriginalDetailsFragments {...row} /> : null }
Yes I will double them

2024-08-16 18:33 UTC, almorbah commented on spec/feature/non_comp/individual_claim_history_spec.rb
> +    expect(table_row).to have_content("Approval of request - issue modification")
In this instance I personally rather not dry this code up because I would be rather have better/clearer readability of each test scenario for the reader. 
https://softwareengineering.stackexchange.com/questions/194504/should-my-code-be-dry-or-readable-if-it-cant-be-both

2024-08-16 22:36 UTC, TylerBroyles requested changes
Left some more comments. It's looking a lot more DRY now. It's still a bit too repetitive for my tastes, but I can understand the reasoning behind not consolidating methods too much more than this.

2024-08-16 22:36 UTC, TylerBroyles commented on spec/feature/non_comp/individual_claim_history_spec.rb
>    scenario "display the claim history table" do
This capybara test is honestly testing way too much stuff. The individual claim history page is almost entirely UI related so it can be extensively tested via jest. All of this filtering testing is also retesting existing QueueTable functionality when all that this component really needs to check is if event data coming from the backend (or staged for testing) gets rendered with the correct html fragments and information.

All that aside. It's a very very slow test because for every single scenario it is recreating all of the database objects and then regenerating the event tree every single time. If we are going to use a capybara test for this, we either need to combine all the scenarios into one or two big tests to avoid setup since the data isn't changing anyhow or create a shared setup that is not blown away between each test iteration.

2024-08-16 22:36 UTC, TylerBroyles commented on spec/feature/non_comp/individual_claim_history_spec.rb
> +    expect(table_row).to have_content("New issue type:")
I don't think there's much point in checking for text in a capybara test without also checking if the data that was staged matches as well e.g. the issue type and description for new issue and current issue are actually different values.

2024-08-19 14:16 UTC, almorbah commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +      component = <WithdrawalRequestedIssueFormat {...requestIssueModificationDetails} />;
@TylerBroyles are you suggesting I break `/>` for all of them?

2024-08-19 14:26 UTC, almorbah commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +  const CancellationRequestedIssueFragment = (details) => {
Yes, indeed those are the same! I can refactor them! But I'm thinking about a shared name that would make sense for both

2024-08-19 14:35 UTC, almorbah commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +  const CancellationRequestedIssueFragment = (details) => {
are you opposed to me

```
  const CancellationRequestedIssueFragment = (details) => {
    originalRequestedIssueModificationFragment(details);
  };
```

2024-08-19 15:15 UTC, almorbah commented on client/app/nonComp/components/IndividualClaimHistoryTable.jsx
> +      <b>New issue type: </b>{details.newIssueType}<br />
I am a bit confused here because i was going off this segment from the document Heather shared with me
<img width="925" alt="Screenshot 2024-08-19 at 10 15 13 AM" src="https://github.com/user-attachments/assets/507d775d-f03f-450f-b41f-039f0334cd5f">

2024-08-20 00:11 UTC, almorbah commented on spec/feature/non_comp/individual_claim_history_spec.rb
> +    expect(table_row).to have_content("New issue type:")
I tried to tie back the date to the field but because I am creating a bunch of objects to capture all the different event types and filtering the table. I am having a hard time tying back the object's data to the field, where Im testing the dynamic table structure here.

2024-08-20 14:35 UTC, almorbah commented on spec/feature/non_comp/individual_claim_history_spec.rb
>    scenario "display the claim history table" do
I managed to make this a nice big concise test where the objects are created and all the event types are tested and that dropped the time to run all of them to less 18 sec right now

2024-08-23 19:01 UTC, TylerBroyles requested changes
I only have one more thing to suggest for the test, but that's about it.

2024-08-24 00:13 UTC, TylerBroyles approved these changes
Everything looks good to me for now.

2024-08-24 00:16 UTC, TylerBroyles approved these changes
Everything looks good to me for now.

2024-08-28 15:53 UTC, merged