APPEALS-50370 Implement feature toggle and logic to control disablement of edit page
department-of-veterans-affairs/caseflow pull request #22494
Opened 2024-08-15 13:01 UTC by kshiflett88

Resolves [APPEALS-50370](https://jira.devops.va.gov/browse/APPEALS-53198)

# Description
Added `remove_comp_and_pen_inntake` featureToggle to: 
  - app/views/higher_level_reviews/edit.html.erb
  - app/views/supplemental_claims/edit.html.erb
Added logic to `client/app/intakeEdit/IntakeEditFrame.jsx` for whether or not editing should be disabled based on benefit type and whether or not the featureToggle mentioned prior is enabled.

## Acceptance Criteria
- [x] Code compiles correctly

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [x] No new code climate issues added

2024-08-15 13:58 UTC, mattray-gov requested changes

2024-08-15 13:58 UTC, mattray-gov commented on client/app/intakeEdit/IntakeEditFrame.jsx
> +    return false;
Can we refactor this to use a ternary operator? Like `return (our conditional) ? true : false` ?

2024-08-15 13:58 UTC, mattray-gov commented on client/app/intakeEdit/IntakeEditFrame.jsx
> +                          disableEditingForCompAndPen={disableEditingForCompensationAndPension()}
Can we include our new prop like this: `{...props, newProp={newProp()}}` ?

2024-08-15 17:59 UTC, kshiflett88 commented on client/app/intakeEdit/IntakeEditFrame.jsx
> +                          disableEditingForCompAndPen={disableEditingForCompensationAndPension()}
@mattray-gov no this will not work, the newProp needs to be outside of the spread {..props}

2024-08-15 17:59 UTC, kshiflett88 commented on client/app/intakeEdit/IntakeEditFrame.jsx
> +    return false;
yup can refactor that

2024-08-22 19:25 UTC, mattray-gov approved these changes

2024-08-22 19:27 UTC, merged