Initial commit of Affinity_date_count
department-of-veterans-affairs/caseflow pull request #22609
Opened 2024-08-26 15:33 UTC by samasudhirreddy

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into master: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-08-28 17:59 UTC, craigrva requested changes

2024-08-28 17:59 UTC, craigrva commented on app/models/dockets/aoj_legacy_docket.rb
> +  def appeal_affinity(appeal)
This should be inherited from the `LegacyDocket` class and doesn't need to be redefined

2024-08-28 17:59 UTC, craigrva commented on app/models/vacols/aoj_case_docket.rb
> +      where (VLJ IS NULL or #{ineligible_judges_sattyid_cache}) AND (PREV_TYPE_ACTION = '7')
These clauses don't seem right. With the current setup of the `affinity_date_count` method in the docket classes, this will need to retrieve and return every ready priority appeal. Then those appeals can be sent through other filter methods, similar to how the `cavc_affinity_filter` (and other legacy affinity filters) have been implemented.

2024-08-28 17:59 UTC, craigrva commented on app/models/dockets/aoj_legacy_docket.rb
> +                    appeal_affinity(appeal)&.affinity_start_date.nil? ||
We should find the appeal affinity and set it to a variable here, then check the variable. As it is written, this will execute two queries to get the affinity start date if it is not nil. The same thing applies to the `else` portion of this if block.

2024-09-02 17:38 UTC, samasudhirreddy commented on app/models/dockets/aoj_legacy_docket.rb
> +  def appeal_affinity(appeal)
Addressed

2024-09-02 17:38 UTC, samasudhirreddy commented on app/models/vacols/aoj_case_docket.rb
> +      where (VLJ IS NULL or #{ineligible_judges_sattyid_cache}) AND (PREV_TYPE_ACTION = '7')
Addressed

2024-09-02 17:38 UTC, samasudhirreddy commented on app/models/dockets/aoj_legacy_docket.rb
> +                    appeal_affinity(appeal)&.affinity_start_date.nil? ||
Addressed

2024-09-03 15:11 UTC, craigrva requested changes

2024-09-03 15:11 UTC, craigrva commented on app/models/dockets/legacy_docket.rb
> +  def find_appeal_affinity(appeal)
It doesn't look like this method is being used anymore, if it isn't then it should be removed

2024-09-04 13:08 UTC, craigrva requested changes

2024-09-04 13:08 UTC, craigrva commented on app/models/dockets/legacy_docket.rb
> +      priority_appeals_affinity_date_count(in_window).size
Can we move this `.size` call to the downstream method so that it is consistent with the nonpriority method?

2024-09-04 13:08 UTC, craigrva commented on app/models/vacols/case_docket.rb
> +        if appeal["bfac"] == "7" && appeal["aod"] == "0"
Looking at this again, I think we might need to either add a where clause to the SQL above or reject appeals which are not CAVC. In this case, appeals which are not CAVC but are AOD (`BFAC <> '7' and AOD == '1'`) would be put through the `else` portion of this block. Theoretically they wouldn't have an `AppealAffinity` to check for, but I don't think we should rely on that to get an accurate count.

We also will want to add appeals which are not CAVC but are AOD to the tests for this method to confirm that we are correctly handling this situation.

2024-09-05 13:13 UTC, craigrva requested changes

2024-09-05 13:13 UTC, craigrva commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +          expect(docket.affinity_date_count(false, true)).to eq(5)
There are not 5 priority cases being created, so this assertion can't be correct.

2024-09-05 13:13 UTC, craigrva commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +          expect(docket.affinity_date_count(false, false)).to eq(5)
Same as the comment above, there are not 5 nonpriority cases so this cannot be correct.

2024-09-05 13:13 UTC, craigrva commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +          expect(docket.affinity_date_count(true, true)).to eq(2)
I think that this assertion is correct but the data that it is checking isn't, so I think that it is passing by accident. Once the data creation is fixed, we'll need to ensure that we are double checking that this is passing.

2024-09-05 13:13 UTC, craigrva commented on app/models/vacols/case_docket.rb
> +        elsif appeal["bfac"] != "7" && appeal["aod"] == 1
This isn't correct. If BFAC is not '7' for a non-AOJ legacy appeal, then it is not a CAVC remand and cannot have an affinity.

2024-09-05 13:13 UTC, craigrva commented on app/models/vacols/case_docket.rb
> +        else
I would expect that any changes to the conditionals to filter cases by BFAC/AOD for the `in_window` condition would apply to the ones that are not as well.

2024-09-05 21:19 UTC, samasudhirreddy commented on app/models/vacols/case_docket.rb
> +        else
Addressed

2024-09-05 21:19 UTC, samasudhirreddy commented on app/models/vacols/case_docket.rb
> +        elsif appeal["bfac"] != "7" && appeal["aod"] == 1
Addressed

2024-09-05 21:20 UTC, samasudhirreddy commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +          expect(docket.affinity_date_count(true, false)).to eq(2)
Addressed

2024-09-05 21:20 UTC, samasudhirreddy commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +          expect(docket.affinity_date_count(false, false)).to eq(5)
Addressed

2024-09-05 21:20 UTC, samasudhirreddy commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +          expect(docket.affinity_date_count(false, true)).to eq(5)
Addressed

2024-09-05 21:20 UTC, samasudhirreddy commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +  def create_aoj_aod_cavc_ready_priority_case_1
Addressed

2024-09-05 21:20 UTC, samasudhirreddy commented on spec/models/dockets/legacy_docket_spec.rb
> +          expect(docket.affinity_date_count(true, true)).to eq(3)
Addressed

2024-09-05 21:20 UTC, samasudhirreddy commented on app/models/vacols/case_docket.rb
> +        if appeal["bfac"] == "7" && appeal["aod"] == "0"
Addressed

2024-09-06 13:13 UTC, craigrva requested changes

2024-09-06 13:13 UTC, craigrva commented on spec/models/dockets/aoj_legacy_docket_spec.rb
> +          expect(docket.affinity_date_count(true, false)).to eq(0)
We should have a case in this test where it is nonpriority and in its affinity window to validate that this method returns appeals as expected

2024-09-06 13:13 UTC, craigrva commented on app/models/vacols/case_docket.rb
> +          false
I think that we would want this to be true. Since an appeal is being selected by case docket is not AOJ, and in this condition in the IF block it is not CAVC, then it doesn't have an affinity. For distributing cases we would consider that to be out of its affinity window because it is genpop, but for reporting in statistics it makes sense to not count them if there isn't a reason that they would be an affinity appeal.

2024-09-06 13:37 UTC, calvincostaBAH commented on app/models/vacols/case_docket.rb
> +          false
If we want to collect all out of window appeals in this else code block, shouldn't we return false (appeal.reject! == false) for cases that are not CAVC since we know they don't have an appeal affinity? This would leave the non-CAVC appeals in the out of window count. We did switch the methods select! and reject! placements from what they were before if that helps haha

2024-09-06 16:09 UTC, craigrva commented on app/models/vacols/case_docket.rb
> +          false
We ultimately decided that we would leave this as "false" because it will act as a catch-all for appeals which are not in an affinity window. This does mean that some appeals which could not possibly in an affinity window will be counted here, but that is not inconsistent with the behavior of these methods for the AMA dockets and legacy AOJ appeals.

2024-09-09 12:08 UTC, merged