Create new job for workflow to pull Transcription files back from specified endpoint folder
department-of-veterans-affairs/caseflow pull request #22761
Opened 2024-09-09 16:53 UTC by piedram

Resolves [APPEALS-43247](https://jira.devops.va.gov/browse/APPEALS-43247)

# Description
1. Caseflow downloads 'returned' work from each QAT endpoint
2. Gem for communicating with BOX added to config
3. Working with the box API refer to GET ([https://api.box.com/2.0/files/:file_id/content](https://developer.box.com/guides/downloads/file/))
4. Upload the file to S3.
   4.1. Returned PDF files to AWS S3 bucket transcript_pdf
   4.2. Returned Work Order XLS file to AWS S3 bucket transcript_text
   4.3. Returned Doc file(s) to AWS S3 bucket transcript_text
   4.1. PDF files added to AWS S3 bucket transcript_pdf
5. In Caseflow updates/create entry in  transcription_files table
   5.1. If a record for the current file already exists, then the following fields will be updated:
    - updated_at: Current timestamp of the record creation/update taking place. This will be done automatically by Rails.
    - date_upload_aws: The current date and time.
    - date_returned_box: The created_at timestamp for a file that provided by the parameters sent to the job.
    
   5.2. If a record for the current file does not already exits:
    - The following fields will be populated within a new record in the transcription_files table:
    - file_type: Extension of file (pdf, doc, rtf, etc..)
    - file_name: Name of file
    - hearing (will automatically map to hearing_id and hearing_type): a Hearing/LegacyHearing object that this file is associated with the file. The ID and type should be available from the file name.
    - transcription_id: ID of a transcription record that this file is associated with.
    - file_status: Either "Successful upload (AWS)" or "Failed upload (AWS)" depending on how the upload to AWS S3 went.
    - docket_number: Docket number of the associated hearing. Should be available in the file name.
    - aws_link: URL of file in S3 (if the upload was successful)

## Acceptance Criteria
- [x] Code compiles correctly

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [x] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [x] No new code climate issues added

2024-09-19 13:44 UTC, ThorntonMatthew requested changes

2024-09-19 14:08 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +    @files_info.collect do |current_file|
Done!

2024-09-19 14:11 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +  shoryuken_options retry_intervals: [3.seconds, 30.seconds, 5.minutes, 30.minutes, 2.hours, 5.hours]
Done!

2024-09-19 14:11 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +  include Shoryuken::Worker
Done!

2024-09-19 15:46 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +    docket_number = @file_name.split("_")[0]
done!

2024-09-19 16:15 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +        cleanup_tmp_file
Done!

2024-09-19 16:16 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +  end
Done!

2024-09-19 16:16 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +  end
Done!

2024-09-19 16:38 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +      end
done!

2024-09-23 15:31 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +      @file_name = current_file[:name]
Done!

2024-09-23 15:32 UTC, piedram commented on spec/jobs/hearings/va_box_download_job_spec.rb
> +RSpec.describe Hearings::VaBoxDownloadJob, type: :job do
Done!

2024-09-24 12:19 UTC, ThorntonMatthew commented on app/jobs/hearings/monitor_box_job.rb
> +    Hearings::VaBoxDownloadJob.perform_now(files)
```suggestion
    Hearings::VaBoxDownloadJob.perform_later(files)
```
This will allow for the next job to run asynchronously and independently of the first.

2024-09-24 12:23 UTC, ThorntonMatthew commented on lib/fakes/va_box_service.rb
> +    binding.pry
```suggestion
    binding.pry
```

2024-09-24 12:24 UTC, ThorntonMatthew commented on spec/jobs/hearings/va_box_download_job_spec.rb
> +    it "call job to download file and upload to S3 and create/update in transciption_table" do
This test has reported a failure.

2024-09-24 12:38 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +        box_service = ExternalApi::VaBoxService.new
Could this be moved outside of the .collect loop?

2024-09-24 12:47 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +  end
```suggestion
      begin
        box_service.download_file(current_file[:id], tmp_folder)
        if file_extension == "zip"
          unzip_file(tmp_folder, current_file)
        else
          upload_s3_modified_transcription_file(tmp_folder, current_file)
        end
      rescue StandardError => error
        Rails.logger.error "Error to download the file #{file_name} from Box: #{error.message}"
        raise BoxDownloadError
      ensure
        # Delete the downloaded file from tmp/ if it exists.
      end
    end
  end
```
We will want to make sure that we clean up any downloaded files whether the operations on the file succeeded or not.

2024-09-24 12:48 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +      @file_status = "Successful upload (AWS)"
Could this please be made a non-instance variable? I think it can be confusing to have this same variable being changed by a couple of different areas.

2024-09-24 12:49 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +    @transcript_text = (extract_file_extension(file_name) == "pdf") ? "transcript_pdf" : "transcript_text"
https://github.com/department-of-veterans-affairs/caseflow/pull/22761/files#r1773281333

Same this here. I think it'd be good to make `@transcript_text` a non-instance variable.

2024-09-24 12:54 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +    upload_to_s3(file_path, file_name)
This method invocation throws an error if the file does not exist on the local machine. I think there should be a check to see if the file is there before proceeding.

2024-09-24 13:10 UTC, ThorntonMatthew commented on lib/fakes/va_box_service.rb
> +  def download_file(id, tmp_folder)
Could this method be updated to save a file to the `tmp/` folder?

2024-09-24 13:15 UTC, ThorntonMatthew commented on spec/jobs/hearings/monitor_box_job_spec.rb
> +  describe "#poll_box_dot_com_for_new_files" do
I've updated the [VA Box Service initializer](https://github.com/department-of-veterans-affairs/caseflow/blob/feature/APPEALS-49620-and-APPEALS-49626/config/initializers/va_box_service.rb) to only return the fake service whenever in a spec. This should now be possible:
1. All mentions of `ExternalApi::VaBoxService` are removed in favor of `VaBoxService`
2. The subject in this file is reverted
3. The entire monitor + download files workflow will utilize the fake service.

2024-09-24 13:34 UTC, ThorntonMatthew commented on spec/jobs/hearings/va_box_download_job_spec.rb
> +    it "call job to download file and upload to S3 and create/update in transciption_table" do
This file only covers the "happy path" and should be expanded.

Additional test ideas:
- File I/O errors in the job (causing certain methods to throw SystemCallErrors or out-of-space errors)
- Passing in poorly formatted `file_info` and seeing that the job handles it gracefully
- Testing what happens if a .zip file's information is provided
- Passing in a file with an unrecognized extension
- S3 upload failure

2024-09-24 13:36 UTC, ThorntonMatthew commented on spec/jobs/hearings/va_box_download_job_spec.rb
> +    it "call job to download file and upload to S3 and create/update in transciption_table" do
I am not sure if it's flakey, or if it's something else.

2024-09-24 13:45 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +      end
Done!

2024-09-24 13:52 UTC, piedram commented on app/jobs/hearings/monitor_box_job.rb
> +    Hearings::VaBoxDownloadJob.perform_now(files)
Done!

2024-09-24 13:53 UTC, piedram commented on lib/fakes/va_box_service.rb
> +    binding.pry
Done!

2024-09-24 14:12 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +  end
Done

2024-09-24 14:13 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +    @transcript_text = (extract_file_extension(file_name) == "pdf") ? "transcript_pdf" : "transcript_text"
Done

2024-09-24 14:16 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +        box_service = ExternalApi::VaBoxService.new
Done

2024-09-24 15:33 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +    info["hearing_type"] = file_name.split("_")[2].split(".")[0]
I think we may want to validate that the hearing exists before proceeding with creating TranscriptionFile records.

2024-09-25 02:56 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +      @file_status = "Successful upload (AWS)"
Done!

2024-10-02 16:40 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +        raise BoxDownloadError
I think instead of raising an exception here that it would make more sense to go to the next file in the `.collect` loop. This way all files in `file_info` would still be attempted even if only a subset of them had issues downloading or uploading.

2024-10-02 16:43 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +    transcription_id = Hearing.find(current_information["id"])&.transcription&.id
We will need to be able to locate both `Hearing` and `LegacyHearing` object depending on what `hearing_type`'s value is.

2024-10-02 16:53 UTC, ThorntonMatthew commented on app/jobs/hearings/va_box_download_job.rb
> +      end
I don't think `File.exist?` throws an exception, so in order to hit the rescue block you may want to throw a `fail` in an else block to indicate if a file could not be located.

2024-10-02 19:36 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +    transcription_id = Hearing.find(current_information["id"])&.transcription&.id
Done

2024-10-02 19:47 UTC, piedram commented on app/jobs/hearings/va_box_download_job.rb
> +      end
done

2024-10-15 17:54 UTC, mchbidwell approved these changes
Moving through to complete, will revisit with APPEALS-60687

2024-10-15 17:55 UTC, merged