APPEALS-45336
department-of-veterans-affairs/caseflow pull request #23174
Opened 2024-10-10 16:40 UTC by csheepy

Resolves [APPEALS-45336 Creation of Saved Searches page and ‘View saved searches’ button on Generate task report page](https://jira.devops.va.gov/browse/APPEALS-45336)

# Description
Creates a blank Saved Searches page and button to reach it from the reports page

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] Creation of ‘View saved searches’ button on Generate task report page 
    - [ ] On click, routes to new Saved Searches page (/report/searches) 
- [ ] Creation of Saved Searches page 
    - [ ] Page should only be accessible by VHA Admins 
    - [ ] Creation of links/button: 
        - [ ] < Back to Generate task report 

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below
2. Log in as VHAADMIN
3. Go to http://localhost:3000/decision_reviews/vha/report and verify the presence of View saved searches
4. Click View saved searches and verify the new page and back link

- [ ] For feature branches merging into main: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/main/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-10-10 20:43 UTC, TylerBroyles requested changes
Looks great. Most of my comments are about testing and test setup so let me know if you have any issues with it.

2024-10-10 20:43 UTC, TylerBroyles commented on client/test/app/nonComp/Personnel.test.js
> +      <Router>
I wonder if we shouldn't pull this out into a shared condition setup since it's repeated for most of the condition test setups. If it ends up being more trouble than it's worth, don't worry about it though.

2024-10-10 20:43 UTC, TylerBroyles commented on config/routes.rb
> +    get "report/searches", to: "decision_reviews#generate_report", on: :member, as: :saved_searches, format: false
I actually don't think we need this route for this react route and page load to work. I would leave it for the SavedSearches controller story since it will probably be responsible for most of the actions on this page.

2024-10-10 20:43 UTC, TylerBroyles commented on spec/feature/non_comp/report_page_spec.rb
> +  it "should have a link that leads to saved searches" do
This can be added a step to the previous test since we are doing an extra test setup and tear down to click a single link.  I would also add an expectation that verifies actual text on the page instead of just the URL since it tends to be a little more reliable. I'm not sure if url checks wait or not in every situation.

2024-10-10 20:43 UTC, TylerBroyles commented on spec/feature/non_comp/saved_searches_spec.rb
> +    expect(page).to have_content("Saved Searches")
Same as above. I would combined these two tests to avoid setup and tear down for a single expectation.

2024-10-10 20:43 UTC, TylerBroyles commented on client/app/nonComp/pages/SavedSearches.jsx
> +      Select a search you previously saved or look for ones others have saved by switching between the tabs.
```suggestion
        Select a search you previously saved or look for ones others have saved by switching between the tabs.
```

2024-10-10 20:43 UTC, TylerBroyles commented on client/app/nonComp/pages/SavedSearches.jsx
> +  const BACK_LINK_TEXT = 'Back to Generate task report';
I would probably go ahead and pull this out into a constants file. You can either add it into the copy.json or create one for SavedSearches in the client side since we will probably have quite a few string variables by the end of this. Up to you.

2024-10-10 21:12 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2024-10-11 13:45 UTC, brandondorner requested changes
Looks great, all minor things requested

2024-10-11 13:45 UTC, brandondorner commented on client/app/nonComp/pages/SavedSearches.jsx
> +SavedSearches.propTypes = {
If this is empty I say we pull it out and only add it back in once props are introduced

2024-10-11 13:45 UTC, brandondorner commented on client/app/nonComp/pages/SavedSearches.jsx
> +import Link from '../../components/Link';
I'd prefer this to be `import Link from 'app/components/Link';` but it's nitpicky I get it

2024-10-11 13:45 UTC, brandondorner commented on client/app/nonComp/pages/SavedSearches.jsx
> +      <NonCompLayout >
```suggestion
      <NonCompLayout>
```

2024-10-11 13:45 UTC, brandondorner commented on docs/features/APPEALS-45267-notes.md
> +# Development Notes for Feature Work `APPEALS-45267`
I know you didn't add this but can we delete this file in this PR

2024-10-11 13:55 UTC, brandondorner submitted a review, later dismissed

2024-10-11 18:49 UTC, brandondorner approved these changes

2024-10-15 13:39 UTC, brandondorner approved these changes

2024-10-15 13:41 UTC, merged