Al/appeals 45662
department-of-veterans-affairs/caseflow pull request #23173
Opened 2024-10-10 14:12 UTC by almorbah

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/APPEALS-45662)

# Description
This is a new SavedSearch model for all relevant associations.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into main: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/main/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-10-10 21:09 UTC, TylerBroyles requested changes
Looks good. The migrations and class seems to work for me how I would expect it to. I left a few comments so let me know if you have any questions.

2024-10-10 21:09 UTC, TylerBroyles commented on db/migrate/20241007150227_create_saved_searches.rb
> +      t.string :search_name
I think search_name and search_description should probably just be name and description since there's already context given to it based on the model name e.g. saved_searches.name instead of saved_searches.search_name. It just reads a bit redundant and makes it a bit trickier to use.

```suggestion
      t.string :name
```

2024-10-10 21:09 UTC, TylerBroyles commented on db/schema.rb
> +    t.datetime "updated_at", precision: 6, null: false
I'm not sure that this added the foreign key or not usually there's something at the bottom of the schema file like this
```
add_foreign_key "metrics", "users"
```

2024-10-10 21:09 UTC, TylerBroyles commented on app/models/saved_search.rb
> +class SavedSearch < CaseflowRecord
I had something that came to mind when I was looking over this. I wonder if it's worth sub classing this model to something like UserSavedSearch < ClaimHistorySavedSearch. This seems like a pretty reusable model and that way we would be able to put specific restraints e.g. the 10 limit or validations on the actual json values specific to that one page/form and then if another form/page ever wanted to use it they could add their own implementation. I just thought it might be worth discussing.

2024-10-11 13:50 UTC, almorbah commented on app/models/saved_search.rb
> +  validates :search_description, presence: true, length: { maximum: 1000 }
<img width="306" alt="Screenshot 2024-10-11 at 8 49 38 AM" src="https://github.com/user-attachments/assets/92e7b5fc-b714-46a7-9b79-ad84c2b07d49">
After double checking it looks like we do have a filed that captures search description.

2024-10-15 17:16 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2024-10-16 13:46 UTC, TylerBroyles approved these changes
Reapproved after feature branch merges.

2024-10-16 15:15 UTC, brandondorner approved these changes

2024-10-16 15:16 UTC, merged