Pamatya/appeals 45665
department-of-veterans-affairs/caseflow pull request #23198
Opened 2024-10-11 17:47 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into main: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/main/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-10-15 17:41 UTC, almorbah approved these changes

2024-10-15 18:25 UTC, brandondorner requested changes

2024-10-15 18:25 UTC, brandondorner commented on client/app/queue/components/SearchTable.jsx
> +        strongLabel
strongLabel isn't needed since we are hiding the label

2024-10-15 18:25 UTC, brandondorner commented on client/app/queue/components/SearchTable.jsx
> +  const onChange = (row) => {
This is a personal preference but I would rename this so it's a little more self explanatory
Maybe something like onSearchChange or onSavedSearchChange

2024-10-15 18:25 UTC, brandondorner commented on client/app/queue/components/SearchTable.jsx
> +
Can we remove these two empty lines in the imports please

2024-10-15 18:25 UTC, brandondorner commented on client/app/queue/components/SearchTable.jsx
> +      header: '',
Instead of an empty string I believe we can just remove these attributes altogether (name and header)

2024-10-15 18:25 UTC, brandondorner commented on client/app/queue/components/SearchTable.jsx
> +        // onChange={onChange}
```suggestion
```

2024-10-15 18:25 UTC, brandondorner commented on client/app/queue/components/SearchTable.jsx
> +        onChange={(val) => onChange(row, val)}
You're passing in two parameters here when the function only accepts one

We should be good to just pass in row so we don't need `value` at all

2024-10-15 18:25 UTC, brandondorner commented on client/app/queue/components/SearchTable.jsx
> +    dispatch(setSavedParams(row));
This is setting the `row` as the savedParams which looks like 
```
{
    "id": 1,
    "name": "Search Name",
    "description": "Search Description is interesting to be done. Long Desciption goes here. how long is too long",
    "createdAt": "2024-07-10",
    "userId": 12,
    "userCssId": "VHAADMIN",
    "userFullName": "VHAADMIN",
    "saved_params": {
        "report_type": "event_type_action",
        "timing": {
            "range": "after",
            "start_date": "2024-10-07T06:00:00.000Z"
        }
    }
}
```

when I think we should instead just be setting the actual searchParams so that it looks like

```
{
        "report_type": "event_type_action",
        "timing": {
            "range": "after",
            "start_date": "2024-10-07T06:00:00.000Z"
        }
}
```

It can be done like this still but we would just have some extra data that I don't believe we'll need

I would love some extra eyes and opinions on this one as well

2024-10-15 18:46 UTC, TylerBroyles requested changes
Looks good overall. The redux selector seems to work nicely. There are several small things and console warnings that we probably need to take care of, but that's about it.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/nonComp/actions/savedSearchSlice.js
> +    setSavedParams: (state, action) => {
I think this reducer/action should be named a little differently. I would expect setSavedParams to be the thunk that actually saves the filter rather than the action that is for selecting a saved search from the queue table. Maybe something like `setSavedSearch` or `selectSavedSearch` would be more appropriate.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/nonComp/pages/SavedSearches.jsx
> +      disable: false,
The disable key isn't necessary since it's enabled by default without it and we aren't doing any sort of dynamic disabling.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +      header: 'Search Description',
This is just 'Description' in the designs.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +        // onChange={onChange}
```suggestion
```

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +    casesPerPage={10}
Something weird is happening with the 10 casesPerPage option. It's showing 10 but the total should be 12 which is correct but the and the second page shows 16 and 17 for some reason I assume because it's 15+2 and maybe it's missing another property somewhere. Are we supposed to limit it to 10 per page instead of the normal 15? Since the designs don't specify I would ask or just leave it at 15.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +    taskPageApiEndpoint={searchPageApiEndpoint}
useTaskPagesApi and searchPageApiEndpoint are mutually exclusive e.g. if searchPageApiEndpoint is set then useTaskPagesApi has to be true for it to do anything. I don't think we will be going through queue table's backend retrieval for this but we might.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +    dispatch(setSavedParams(row));
This is for the row selection not for saving the params.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +        onChange={(val) => onChange(row, val)}
If you really want to pare it down you can just send the function itself as a handler, but it might have to change a little bit.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +  return (<QueueTable
QueueTable needs either one `getKeyForRow` or `slowReRendersAreOk` or it throws tons of console warnings. I would prefer coming up with some unique row key personally.

2024-10-15 18:46 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +      valueFunction: (row) => <RadioField
This radio field is throwing a controlled to uncontrolled react console warning/error as well right now when you select one of the radio options. It still works but it's not happy about it.

2024-10-15 18:47 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +      columnName: 'Admin',
Those are only used for filtering afaik so don't need them here.

2024-10-15 18:51 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +      header: '',
Depends if it uses that for aria information. I think it does so we probably need a header.

2024-10-16 00:15 UTC, TylerBroyles requested changes
I left a few more comments mostly around some minor UX questions.

2024-10-16 00:15 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +  // getKeyForRow = (index, task) => task.id
```suggestion
```

2024-10-16 00:15 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +    casesPerPage={15}
15 is the implied default if you leave this parameter out so I don't think we need it anymore.

```suggestion
```

2024-10-16 00:15 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +    defaultSort= {{
We don't have to have a default sort, but I would ask if they want one since the UI doesn't seem to start in any particular order.

2024-10-16 00:15 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +      valueFunction: (row) => row.userCssId,
Based on the UX designs this is probably going to be user name rather than CSSID since it has spaces. I would ask if they want a particular value/format for this.

2024-10-16 00:15 UTC, TylerBroyles commented on client/app/queue/components/SearchTable.jsx
> +      valueFunction: (row) => row.createdAt,
UX designs show the date format in MM/DD/YYYY format. I think it's very likely to assume the date that is passed up from the backend will be an iso8601 timestamp and it will probably need to be formatted to match the designs.

2024-10-16 13:34 UTC, pamatyatake2 commented on client/app/queue/components/SearchTable.jsx
> +    defaultSort= {{
AC6: > Default sort top to bottom based on most recent save to earliest

2024-10-16 16:27 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2024-10-16 16:30 UTC, brandondorner approved these changes

2024-10-18 16:33 UTC, brandondorner approved these changes

2024-10-18 16:34 UTC, merged