Vinner57/appeals 42571
department-of-veterans-affairs/caseflow pull request #23212
Opened 2024-10-14 04:04 UTC by vinner57

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into main: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/main/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-10-16 16:07 UTC, HunJerBAH commented on app/services/correspondence_intake_processor.rb
>      intake_params[:related_correspondence_uuids]&.map do |uuid|
the `intake_params[:related_correspondence_uuids]` seems to have changed to `intake_params[:priorMailIds]`, so either the value on the frontend in or the value in this method will need to be changed.

2024-10-16 16:10 UTC, HunJerBAH commented on app/controllers/correspondence_details_controller.rb
> +      render json: { related_appeals: @correspondence.appeal_ids }, status: :created
It might be a beefy response, but if you update the frontend with `correspondence: serialized_correspondence`, you can update the entire redux store with the correspondence and appeal relations.

2024-10-16 16:11 UTC, HunJerBAH commented on app/services/correspondence_intake_processor.rb
> +    Rails.logger.debug "intaaake rela #{intake_params}"
logger can be removed

2024-10-16 16:19 UTC, HunJerBAH commented on app/services/correspondence_intake_processor.rb
> +      .where(appeal_id: intake_params[:unselected_appeal_ids])
since this uses direct params in a `where` clause, the `intake_params` should be sanitized in a `permit` block similar to the [correspondence_details_controller.rb#correspondence_params](https://github.com/department-of-veterans-affairs/caseflow/blob/feature/APPEALS-60433/app/controllers/correspondence_details_controller.rb#L94) to prevent [SQL injection](https://rails-sqli.org/)

2024-10-16 16:19 UTC, HunJerBAH commented on app/services/correspondence_intake_processor.rb
> +    Rails.logger.debug "relaaated appeals  #{intake_params}"
debugger can be removed, please!

2024-10-16 16:22 UTC, HunJerBAH commented on client/app/queue/correspondence/details/CorrespondenceDetails.jsx
> +      return ApiUtil.patch(`/queue/correspondence/${correspondence.uuid}/update_correspondence`, payload).
We should be able to consolidate the 3 `update_correspondence` calls in this workflow to a single call. The values for selected/unselected correspondences and selected/unselected appeals can be put into a single `payload` so that only one call needs to happen.

2024-10-16 19:02 UTC, HunJerBAH requested changes
Few changes in comments but looking good so far!

2024-10-17 15:27 UTC, vinner57 commented on app/services/correspondence_intake_processor.rb
>      intake_params[:related_correspondence_uuids]&.map do |uuid|
updated accordingly

2024-10-17 15:29 UTC, vinner57 commented on app/services/correspondence_intake_processor.rb
> +      .where(appeal_id: intake_params[:unselected_appeal_ids])
updated accordingly

2024-10-17 15:30 UTC, vinner57 commented on app/services/correspondence_intake_processor.rb
> +    Rails.logger.debug "relaaated appeals  #{intake_params}"
removed

2024-10-17 15:30 UTC, vinner57 commented on client/app/queue/correspondence/details/CorrespondenceDetails.jsx
> +      return ApiUtil.patch(`/queue/correspondence/${correspondence.uuid}/update_correspondence`, payload).
updated accordingly

2024-10-17 17:08 UTC, HunJerBAH approved these changes
Great work on this!

2024-10-17 18:07 UTC, merged