Al/appeals 45664
department-of-veterans-affairs/caseflow pull request #23279
Opened 2024-10-18 15:49 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into main: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/main/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-10-24 18:23 UTC, TylerBroyles requested changes
Looks good. I left a lot of comments around around naming conventions and small things like that so if you have any questions let me know.

2024-10-24 18:23 UTC, TylerBroyles commented on app/views/saved_searches/index.html.erb
> +<% content_for :full_page_content do %>
Neither of these erb files are currently being used by the current implementation of the routes and SavedSearch page. They also contain a bunch of stuff required for the decision review queue but not necessarily elsewhere (if this controller were ever used in a different location) which is fine for now.

2024-10-24 18:23 UTC, TylerBroyles commented on app/controllers/saved_searches_controller.rb
> +  def verify_vha_admin
If another org user tried to use this controller it would fail right now since this is a hard scope to VHA only. A more generic version would be something like checking for an organization admin

2024-10-24 19:07 UTC, almorbah commented on app/models/saved_search.rb
> +  scope :all_saved_searches, -> { order(created_at: :desc) }
more descriptive than `all_saved_searches`?

2024-10-24 19:08 UTC, almorbah commented on app/models/saved_search.rb
> +  scope :my_saved_searches, ->(user) { where(user_id: user).order(created_at: :desc) }
I like `for_user_seaches` maybe

2024-10-24 19:11 UTC, almorbah commented on app/serializers/saved_search_serializer.rb
> +    object.user.full_name
I can add a safety operator here

2024-10-24 19:36 UTC, almorbah commented on client/app/nonComp/pages/SavedSearches.jsx
> -      key: 'my_saved_searches',
@pamatyatake2 let revert this change here

2024-10-24 19:40 UTC, almorbah commented on app/controllers/saved_searches_controller.rb
> +  include ValidationConcern
It might be not necessary to have this `include ValidationConcern` since we are using `params.require(:search).permit(PERMITTED_PARAMS)` in the controller

2024-10-24 19:44 UTC, almorbah commented on app/controllers/saved_searches_controller.rb
> +    searches = SavedSearch.all_saved_searches
I think that would be by default since only VHA users are the ones saving searches. we currently don't have an association between `SavedSearch` and `BusinessLine` to make this happen. It's bad engineering practice to write code based on future assumed business requirements.

2024-10-24 19:54 UTC, almorbah commented on app/controllers/saved_searches_controller.rb
> +    @search = current_user.saved_searches.find(params[:id])
Are we assuming that Vha users with use e.g postman to make a API call the frontend UI limited uses from attempting a scenario like this one. But for extra safety we can add `rescue ActiveRecord::RecordNotFound` if this endpoint returns a 404 status code

2024-10-25 16:24 UTC, brandondorner submitted a review, later dismissed

2024-10-25 18:36 UTC, TylerBroyles requested changes
Looks good overall. I noticed a couple of small things around the index/show html methods and some cleanup that we might want to address.

2024-10-25 18:36 UTC, TylerBroyles commented on app/controllers/saved_searches_controller.rb
> +    @organization ||= BusinessLine.find_by(url: params[:decision_review_business_line_slug])
The decision_review_business_line_slug is not included in any of your routes so it's not going to know what this :decision_review_business_line_slug param is.  It would have to be using the :business_line_slug param from the routes.
Something like this might work
```
@organization ||= Organization.find_by(url: params[:business_line_slug] || params[:organization_slug])
```

2024-10-25 18:36 UTC, TylerBroyles commented on app/views/saved_searches/index.html.erb
> +    savedSearches: {
This index.html.erb file should probably render the serialized searches from the index action in the controller. Otherwise it's just spent computation time serializing those saved searches for no reason.

2024-10-25 18:36 UTC, TylerBroyles commented on app/views/saved_searches/show.html.erb
> +    savedSearches: {
Same comment as above. If the show serializes a search it would need to render it somewhere in this html file to make it available to the frontend.

2024-10-25 18:36 UTC, TylerBroyles commented on spec/controllers/saved_searches_controller_spec.rb
> +  let(:user) { create(:user, :vha_admin_user, :with_saved_search_reports) }
I think the :vha_admin_user trait already creates adds the user to the VhaBusienssLine so you probably don't have to add it later `non_comp_org.add_user(user)`

2024-10-25 18:36 UTC, TylerBroyles commented on spec/controllers/saved_searches_controller_spec.rb
> +  let(:vha_business_line) { VhaBusinessLine.singleton }
vha_business_line and non_comp_org can probably be combined into one variable since they are doing the same thing.

2024-10-25 18:36 UTC, TylerBroyles commented on spec/controllers/saved_searches_controller_spec.rb
> +    context "VHA user creating saved search" do
```suggestion
    context "VHA admin user creating saved search" do
```

2024-10-25 18:36 UTC, TylerBroyles commented on spec/controllers/saved_searches_controller_spec.rb
> +    context "VHA user saved search not exists" do
```suggestion
    context "VHA admin user saved search not exists" do
```

2024-10-25 18:36 UTC, TylerBroyles commented on config/routes.rb
> +    resources :saved_searches, only: [:index, :create, :destroy, :show]
This still does not match the current SavedSearches page url which is `/decision_reviews/business_line_slug/report/searches`. This route would match `/decision_reviews/business_line_slug/searches`. Is that the intention?

2024-10-26 00:40 UTC, TylerBroyles requested changes
I noticed one last thing, but that should be it.

2024-10-26 00:40 UTC, TylerBroyles commented on app/serializers/saved_search_serializer.rb
> +  attribute :name
We probably also need to serialize the id since that will be what we are sending back to the backend when we are deleting a saved search.

2024-10-28 13:32 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2024-10-29 14:40 UTC, merged