Min/APPEALS-63928
department-of-veterans-affairs/caseflow pull request #23478
Opened 2024-11-12 18:01 UTC by minhazur9

Resolves [APPEALS-63928](https://jira.devops.va.gov/browse/APPEALS-63928)

# Description
Creation of Table to Track Amendments to the "Schedulable" Cutoff Date

## Acceptance Criteria
- [ ] Code compiles correctly
- [ ] A migration is generated that performs the following actions:
   - [ ] Defines the creation of a table named schedulable_cutoff_dates
       - [ ] It contains the following columns:
                - [ ] id (primary key)
                - [ ] created_at (timestamp)
                - [ ] created_by_id (foreign key to the users table)
                - [ ] cutoff_date (date)
   - [ ] Defines a down step that drops the table.

## Testing Plan
1. Go to [APPEALS-64440](https://jira.devops.va.gov/browse/APPEALS-64440)

- [ ] For feature branches merging into main: Was this deployed to UAT?

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

2024-11-12 19:39 UTC, prernadevbah commented on db/migrate/20241107185559_create_schedulable_cutoff_dates.rb
> +  def down
If we have a migration using the change method, I don't think we need to specify a down method as well. As per this article, the rollback for any create_table migration, should automatically drop the table- https://medium.com/@kevinkarma55/rails-active-record-migration-change-method-vs-up-down-method-eaba011de3e9 . I did see that adding a drop method was included in the AC, but maybe we could change this migration to a up-down, or remove the down method if we want to keep it as a change method.

2024-11-13 13:33 UTC, ThorntonMatthew requested changes

2024-11-13 13:33 UTC, ThorntonMatthew commented on spec/factories/schedulable_cutoff_dates.rb
> +    end
```suggestion
    created_by_id { create(:user).id }
```
I think something like this would allow for the factory to be run on its own without params.

2024-11-13 13:33 UTC, ThorntonMatthew commented on spec/factories/schedulable_cutoff_dates.rb
> +    id { 1 }
```suggestion
    sequence(:id)
```
This will prevent a pkey collision whenever running the factory multiple times.

2024-11-13 13:33 UTC, ThorntonMatthew commented on app/models/schedulable_cutoff_date.rb
> +class SchedulableCutoffDate < ApplicationRecord
```suggestion
class SchedulableCutoffDate < CaseflowRecord
```
This will allow for this class/table to be picked up by our ERD diagraming workflows.

2024-11-13 15:33 UTC, minhazur9 commented on spec/factories/schedulable_cutoff_dates.rb
> +    id { 1 }
I've opted to just get rid of the id from the factory, the pk should automatically be sequenced

2024-11-13 15:51 UTC, ThorntonMatthew approved these changes

2024-11-13 15:57 UTC, merged