Caching State and Country of Residence for Veterans with Pending Hearings PostgreSQL Data Store
department-of-veterans-affairs/caseflow pull request #23473
Opened 2024-11-12 15:17 UTC by prernadevbah

Resolves [Caching State and Country of Residence for Veterans with Pending Hearings PostgreSQL Data Store](https://jira.devops.va.gov/browse/JIRA-59240)

# Description
Changes to cache the state and country of residence for veterans with pending hearings in PostgreSQL-
- Added a migration with new columns for the veterans table to track the state and country of residence
- Added a new job to populate the veterans table columns with the available information

## Acceptance Criteria
- [x] Code compiles correctly
- [x] The system updates the “veterans” table to have the following three new columns (via a migration):
    - state_of_residence (TEXT)
       - Column comment is added to indicate that this column can contain state, territory, or district abbreviations.
    - country_of_residence (TEXT)
    - residence_location_last_checked_at (TIMESTAMPTZ)
- [x] An ActiveJob class is created that updates up to 5,000 Veterans' state and country information.
    - It is a subclass of [CaseflowJob](https://github.com/department-of-veterans-affairs/caseflow/blob/5033a6472cef5100fd8d1b5a226ab649c68184fb/app/jobs/caseflow_job.rb)
    - It will likely run once per hour (execution schedule is handled by [APPEALS-59452](https://jira.devops.va.gov/browse/APPEALS-59452))
    - The system checks for veterans table records with:
      - null state_of_residence
      - null country_of_residence
      - Outdated data (over a week old) which is determined by comparing the current datetime to residence_location_last_checked_at.
    - Address information is gathered from BGS/CRP DB for these records and persisted to the database.
      - Accessible by calling veteran.address
    - RequestStore[:current_user] must be set prior to this request being made. See [this module](https://github.com/department-of-veterans-affairs/caseflow/blob/051cef8af9334db2f73a0c275f30851c0726eb73/app/jobs/hearings/ensure_current_user_is_set.rb#L3-L7) for how this has been addressed previously.
      - state_of_residence will contain either the state, territory, or district a Veteran resides within.
        - veteran.address.state
      - country_of_residence will contain the country a Veteran resides within.
        - veteran.address.country
    - The residence_location_last_checked_at value is set to the current timestamp.
    - SQL updates are done in multithreaded fashion and/or done in batches for efficient performance.
    - The 5k limit for number of Veterans to have address information pulled per job execution should be an environment variable so that we can adjust this figure.
    - The job gracefully handles any network request errors
    - Errors are logged appropriately
    - Errors encountered with one/some records should not prevent others from being processed.
- [x] A key-value pair is added to the SCHEDULED_JOBS hash in [config/initializers/scheduled_jobs.rb](https://github.com/department-of-veterans-affairs/caseflow/blob/1158b8e8a78c68e649d35a99c98d0ee0262fb085/config/initializers/scheduled_jobs.rb)
  - Key: The name of the Job class in snake_case
  - Value: The name of the Job class

## Testing Plan

1. Go to [APPEALS-64433](https://jira.devops.va.gov/browse/APPEALS-64433)

- [ ] For feature branches merging into main: Was this deployed to UAT?

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [x] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/main/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [x] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

# Best practices
## Code Documentation Updates
- [x] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [x] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Error Handling
- [x] Are errors being caught and handled gracefully?
- [x] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

2024-11-12 19:44 UTC, noahhansen-gov requested changes
Some comments for ya!

2024-11-12 19:44 UTC, noahhansen-gov commented on db/migrate/20241104122031_add_region_details_to_veterans.rb
> +    add_column :veterans, :country_of_residence, :text, comment: "The most recently known country of residence of the veteran"
Can we use `string` instead of text. Just want to be consistent with the rest of the table

2024-11-12 19:44 UTC, noahhansen-gov commented on spec/jobs/check_veteran_residence_location_job_spec.rb
> +  subject { described_class.perform_now }
Let's use this instead of `perform_now`. @ThorntonMatthew has talked about situations where `perform_now` works but `perform_later` doesn't. This can be imported with this: `include ActiveJob::TestHelper`

`perform_enqueued_jobs { described_class.perform_later }`

2024-11-12 19:44 UTC, noahhansen-gov commented on spec/jobs/check_veteran_residence_location_job_spec.rb
> +
Can you wrap all the tests in `describe #perform` in here so we know which method were testing?

2024-11-12 19:44 UTC, noahhansen-gov commented on spec/jobs/check_veteran_residence_location_job_spec.rb
> +      expect(vet_after_job_run.country_of_residence).to eq "US"
If there's ever a situation where `vet_before_job_run.state_of_residence` and `vet_before_job_run.country_of_residence` will equal 'FL' and 'US' respectively then we need to rewrite this test to ensure that it cannot be true and delete lines 32 and 33.

2024-11-12 19:44 UTC, noahhansen-gov commented on spec/jobs/check_veteran_residence_location_job_spec.rb
> +      subject
since were changing `subject` to be `perform_later`, this line and line 51 will need to be changed to `perform_now`. I don't think able to check whether a class receives instance method calls when using `perform_later`.

That being said, don't fix what ain't broke 🤷

2024-11-12 19:48 UTC, noahhansen-gov commented on app/jobs/check_veteran_residence_location_job.rb
> +  def retrieve_veterans
Need test coverage for this

2024-11-12 19:48 UTC, noahhansen-gov commented on app/jobs/check_veteran_residence_location_job.rb
> +  def batch_update_veterans(vet_updates)
Need test coverage for this

2024-11-12 19:56 UTC, prernadevbah commented on db/migrate/20241104122031_add_region_details_to_veterans.rb
> +    add_column :veterans, :country_of_residence, :text, comment: "The most recently known country of residence of the veteran"
I put it as text to match the AC, but I'm open to changing it to 'string'

2024-11-12 20:29 UTC, prernadevbah commented on spec/jobs/check_veteran_residence_location_job_spec.rb
> +      expect(vet_after_job_run.country_of_residence).to eq "US"
We are creating the vet in the "before" section of the spec test. There should not be a scenario in which the state_of_residence and country_of residence are populated before the job run, since the test data will be cleaned up after each test is run

2024-11-12 20:30 UTC, prernadevbah commented on spec/jobs/check_veteran_residence_location_job_spec.rb
> +      expect(vet_after_job_run.country_of_residence).to eq "US"
^ At least as far as the current tests are concerned. If we're concerned about the test data, I can add an "after section to clean it up and make sure the veteran is deleted again after each test

2024-11-12 21:06 UTC, prernadevbah commented on app/jobs/check_veteran_residence_location_job.rb
> +                                residence_location_last_checked_at: Time.zone.now }
I don't think there should be any significant issues with using `Time.zone.now` vs `Time.now`
From this link- https://github.com/forem/forem/issues/282

`Time.now` = a Ruby method that uses server time.
`Time.zone.now` = a Rails method that uses the Rails app time.

I ended up using `Time.zone.now` since the residence_location_last_checked_at column is a timestampwithtz.
If we're concerned about the rails app time and the server time potentially being out of sync, I'm open to updating it.

2024-11-13 15:33 UTC, noahhansen-gov commented on db/migrate/20241104122031_add_region_details_to_veterans.rb
> +    add_column :veterans, :country_of_residence, :text, comment: "The most recently known country of residence of the veteran"
@ThorntonMatthew what are your thoughts here? Am I splitting hairs too much?

2024-11-13 16:47 UTC, noahhansen-gov commented on spec/jobs/check_veteran_residence_location_job_spec.rb
> +      expect(vet_after_job_run.country_of_residence).to eq "US"
@ThorntonMatthew Could also use your opinion here!

2024-11-15 13:38 UTC, ThorntonMatthew requested changes

2024-11-15 13:38 UTC, ThorntonMatthew commented on app/jobs/check_veteran_residence_location_job.rb
> +    end
```suggestion
  RESIDENCE_LOCATION_PROCESS_LIMIT = ENV.fetch("RESIDENCE_LOCATION_BATCH_SIZE", 2500).to_i
```

[ENV.fetch](https://ruby-doc.org/core-2.7.2/ENV.html#method-c-fetch) allows for specifying a default value.

2024-11-15 13:38 UTC, ThorntonMatthew commented on app/jobs/check_veteran_residence_location_job.rb
> +  VET_UPDATE_BATCH_PROCESS_LIMIT = ENV["VET_UPDATE_BATCH_SIZE"].nil? ? 100 : ENV["VET_UPDATE_BATCH_SIZE"].to_i
```suggestion
  VET_UPDATE_BATCH_PROCESS_LIMIT = ENV.fetch("VET_UPDATE_BATCH_SIZE", 100).to_i
```
The same can apply here.

2024-11-15 13:38 UTC, ThorntonMatthew commented on app/jobs/check_veteran_residence_location_job.rb
> +      batch_update_veterans(vet_updates.compact) unless vet_updates.compact.empty?
Something I noticed during our troubleshooting of the tests is that if `log_error(error)` is encountered during any iteration then the return value is `false`. I wonder if this line needs to be something like:
```ruby
batch_update_veterans(vet_updates.compact) unless vet_updates.filter { !!_1 }.empty?
```
That'll only keep around truthy values before checking if the set is empty.

2024-11-15 13:38 UTC, ThorntonMatthew commented on db/migrate/20241104122031_add_region_details_to_veterans.rb
> +    add_column :veterans, :country_of_residence, :text, comment: "The most recently known country of residence of the veteran"
Since text and string (varchar) are the same under the hood in Postgres I think it's fine to leave it as text.

2024-11-15 13:38 UTC, ThorntonMatthew commented on lib/generators/veteran.rb
> +        residence_location_last_checked_at: nil
```suggestion
                    pay_grade: "E5" }]
```
I am wondering, since this information isn't returned by BGS, if these three lines should be included here.

```ruby
Generators::Veteran.build(fl_vet_attrs).update(
  state_of_residence: "FL"
  country_of_residence: "USA",
  residence_location_last_checked_at: nil
).save!
```
I think something like this would allow the generator to operate truer to form.
```

2024-11-15 16:38 UTC, ThorntonMatthew approved these changes

2024-11-15 18:03 UTC, merged