Details: Correspondence and Appeals Tasks: Add Task Action: Other motion
department-of-veterans-affairs/caseflow pull request #23584
Opened 2024-11-20 22:37 UTC by sulak-j

Resolves [Details: Correspondence and Appeals Tasks: Add Task Action: Other motion](https://jira.devops.va.gov/browse/APPEALS-54933)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into main: Was this deployed to UAT?

2024-11-27 22:04 UTC, sulak-j commented on client/app/queue/correspondence/details/CorrespondenceDetails.jsx
if block on 234 replaced the other if block in the file, but was later reverted and part of the block was missed. This code was a logical redundancy, and we removed it here due to lint errors for too many return statements.

2024-11-29 14:14 UTC, HunJerBAH commented on app/controllers/correspondence_tasks_controller.rb
> +        notes: params[:return_reason]
Can this value be added to `correspondence_tasks_params` and called here instead? We want to sanitize our params when we can. Thank you!

2024-11-29 14:32 UTC, HunJerBAH commented on app/models/tasks/correspondence/correspondence_task.rb
> +      ReturnToInboundOpsTask.name
In the [Wiki](https://github.com/department-of-veterans-affairs/caseflow/wiki/Correspondence-Statuses), we want this to show up in the **Action Required** tab, so this will need to be moved to `self.package_action_task_names`.

2024-11-29 15:28 UTC, HunJerBAH approved these changes
Great job!

2024-11-29 18:40 UTC, HunJerBAH commented on app/controllers/correspondence_tasks_controller.rb
>    end
The `@task` call in `change_task_type_params` seems outdated and needs to be swapped out for `correspondence_task` since the refactor. This is causing a few failing tests and I think they will be resolved once this is added in.

2024-11-29 18:41 UTC, HunJerBAH requested changes
A change needs to be made in the correspondence_tasks_controller, and that should fix the few failing tests.

2024-12-02 17:56 UTC, HunJerBAH approved these changes

2024-12-02 18:18 UTC, merged