[APPEALS-64823]Add task action to move an appeal from a VLJ to an att…
department-of-veterans-affairs/caseflow pull request #23594
Opened 2024-11-21 17:54 UTC by samasudhirreddy

…orney for rewrite

Resolves [APPEALS-64823](https://jira.devops.va.gov/browse/APPEALS-64823)

# Description
Add task action to move an appeal from a VLJ to an attorney for rewrite

## Acceptance Criteria
When the SCM group member is on the Case Details page of the selected legacy appeal that is currently awaiting a decision and has a current active task of Review, they can select _Return to attorney_ from the actions menu associated for the Review task. 
Once they select the action, they are redirected to the Assign Task modal.
The user must select an active attorney, VLJs/AVLJs from the drop down indicating the recipient of the appeal. 
If they do not, the get the "This field is required" message on the modal if they click the Submit button
The user must add text in the Comments text box.
If they do not, the get the "Instructions field is required" message on the modal when they click the Submit button
Clicking Cancel returns the user to the Case Details page.
All of this work is made available/unavailable through the NAME OF feature flag

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into main: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/main/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-11-21 18:07 UTC, calvincostaBAH commented on app/models/legacy_tasks/judge_legacy_decision_review_task.rb
> +  def legacy_blocked_special_case_movement(user)
This method is not needed for your scenario as it is only required for scenario 1 to cancel blocking tasks

2024-11-21 18:22 UTC, calvincostaBAH commented on app/repositories/task_action_repository.rb
> +      attorney = task.appeal.assigned_attorney
not sure if this is correctly grabbing the appeals assigned attorney since it is a legacy appeal so please double check, but if so you would like to add the attorney variable to the data like so `selected: attorney,`

2024-11-21 18:23 UTC, calvincostaBAH requested changes
Left some comments for you to go over including removing some unnecessary methods. Let me know if you have any questions

2024-11-22 15:16 UTC, craigrva requested changes

2024-11-22 15:16 UTC, craigrva commented on app/views/queue/index.html.erb
> +      legacy_case_movement_vlj_to_atty_for_rewrite: FeatureToggle.enabled?(:legacy_case_movement_vlj_to_atty_for_rewrite, user: current_user)
If we aren't using `legacy_case_movement_vlj_to_atty_for_rewrite` in the frontend code, it doesn't need to be passed through here.

2024-11-22 15:16 UTC, craigrva commented on app/models/legacy_tasks/judge_legacy_decision_review_task.rb
> +      actions << Constants.TASK_ACTIONS.LEGACY_RETURN_TO_ATTORNEY.to_h
I am not seeing this task action unless the SpecialCaseMovementTeam user is assigned the appeal. I checked appeal 790000001 as a SCM user and didn't see it, checked the appeal as BVACOTBJUDGE and didn't see it, but saw it once I added BVACOTBJUDGE to the SCM organization

2024-11-22 16:35 UTC, craigrva requested changes

2024-11-22 16:35 UTC, craigrva commented on app/models/legacy_tasks/judge_legacy_decision_review_task.rb
> +    if SpecialCaseMovementTeam.singleton.user_has_access?(current_user)
An extra comment here, we should use `.can_act_on_behalf_of_judges?` instead of `Organizationn.user_has_access?`. The functionality is the same, but `can_act_on_behalf_of_judges?` is a preexisting method which is more clear/semantic about why the user has access to that action.

Also, this action should be behind a feature toggle, and this is probably the best spot to put that toggle.

2024-11-25 14:21 UTC, craigrva commented on app/repositories/task_action_repository.rb
> +    def legacy_return_to_attorney_data(task, _user = nil)
Two things with this method:
1. There's a lint warning
2. I think that it is beneficial to provide a default value for "selected", that default being the attorney who wrote the original decision. If it isn't too much work then I think we should add it now, but if it is something that will push this work back then we can leave it as it is now.

2024-11-25 14:50 UTC, samasudhirreddy commented on app/repositories/task_action_repository.rb
> +    def legacy_return_to_attorney_data(task, _user = nil)
I have fixed the lint issues and addressed the two points. I will push this work when I start working on the backend ticket.

2024-11-25 19:23 UTC, craigrva requested changes

2024-11-26 19:02 UTC, craigrva requested changes

2024-11-26 19:02 UTC, craigrva commented on client/app/queue/AssignToView.jsx
> +                errorMessage={highlightFormItems && highlightInvalidFormItems ? 'This field is required' : null}
`highlightInvalidFormItems` should be updated to `this.state.selectedValue === null`, as seen in [this PR](https://github.com/department-of-veterans-affairs/caseflow/pull/23609/files#diff-cfea69905ecdb58c11f616df6c4c2e61323341563ed217b406ef3c0ac0e2d12aR331). The validation wasn't working correctly (the message would remain on the modal even after selecting an assignee), but Sean has it fixed on his branch already.

2024-11-26 22:37 UTC, craigrva approved these changes

2024-11-27 22:26 UTC, merged