Upload method for 'Errors Found and Corrected'
department-of-veterans-affairs/caseflow pull request #23607
Opened 2024-11-22 20:06 UTC by piedram

Resolves [APPEALS-64078](https://jira.devops.va.gov/browse/APPEALS-64078)

# Description
As a Caseflow User I need to be able to click the submit button to upload the "final PDF" to the correct Appellants eFolder in VBMS so that the final PDF Transcript is uploaded Appellants eFolder in VBMS.

As a Caseflow Developer I need to;

1. Create a new method on submit for 'Errors Found and Corrected' To Upload the PDF file "selected" by the End User from tmp
- Upload the file to S3 and replace the previous file for the Hearing/Appellant
       DocketNumber_interenalHearingID_HearingClassName.pdf
- Found in the transcription_files table, aws_link column for the pdf file
- Upload the the same PDf file to the Appellants eFolder location in VBMS

## Acceptance Criteria
- [x] Code compiles correctly

# Frontend
1. Open claseflow demo application.
2. Login like a admin Hearing
3. Go to demo/hearings/transcription_files
4. Switch the view and select `Hearing Admin Team cases`
5. Select any hearing with a Review Transcript task open
6. In the action Select `Errors found and corrected`
7. Choose the folder to upload
8. Add description in the text area and click `Upload to VBMS`

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [x] RSpec
- [ ] Jest
- [ ] Other

2024-11-25 16:31 UTC, wmedders21 commented on app/controllers/tasks_controller.rb
> +  def error_found_upload_transcription_to_vbms
Should refactor to keep much of this logic abstracted out of the tasks_controller - much of whats going on here is not the responsibility of the tasks_controller. Method length is too long. Ruby methods should be 10 lines or less.

2024-11-25 16:34 UTC, wmedders21 commented on app/controllers/tasks_controller.rb
> +      raise BoxDownloadJobFileUploadError
Sounds like incorrect error class - this upload doesn't seem related to a BoxDownloadJob

2024-11-26 06:41 UTC, piedram commented on app/controllers/tasks_controller.rb
> +  def s3_location(file_name)
Done

2024-11-26 06:42 UTC, piedram commented on app/controllers/tasks_controller.rb
> +      raise BoxDownloadJobFileUploadError
Done

2024-11-26 06:42 UTC, piedram commented on app/controllers/tasks_controller.rb
> +  def error_found_upload_transcription_to_vbms
Done

2024-11-26 14:59 UTC, wmedders21 commented on app/controllers/tasks_controller.rb
> +  def split_filename(filename)
I think we will want _file underscore name_ "file_name" to be consistent throughout this file, rather than having both "filename" and "file_name"

2024-11-26 15:02 UTC, wmedders21 commented on app/controllers/tasks_controller.rb
> +    return unless task.type == "ReviewTranscriptTask" && task.status == "in_progress"
does this method know what "task" is yet?

2024-11-26 15:07 UTC, wmedders21 commented on app/controllers/tasks_controller.rb
> +    Task.where(id: task.id).update_all(
task.update!...

We already have the task - no need to call `where` - and `update_all` would imply there are multiples, be since we're querying on `id`, there can only be one.

2024-11-26 15:12 UTC, wmedders21 commented on app/controllers/tasks_controller.rb
> +  def change_status_review_transcript_task
This method name should reflect exactly whats going on - perhaps `complete_transcription_review`. Since this is updating the status in a specific way, and also updating transcriptions.

2024-11-26 15:16 UTC, wmedders21 commented on app/controllers/tasks_controller.rb
> +  S3_BUCKET = "vaec-appeals-caseflow"
this isn't being used here anymore and can be removed

2024-11-26 15:18 UTC, piedram commented on app/controllers/tasks_controller.rb
> +  S3_BUCKET = "vaec-appeals-caseflow"
Done

2024-11-26 15:19 UTC, piedram commented on app/controllers/tasks_controller.rb
> +  def split_filename(filename)
done

2024-11-26 15:20 UTC, piedram commented on app/controllers/tasks_controller.rb
> +  def change_status_review_transcript_task
Done

2024-11-26 15:21 UTC, wmedders21 commented on app/controllers/tasks_controller.rb
> +      tasks: json_tasks(task.appeal.tasks.includes(*task_includes))[:data]
I don't believe this is the correct json response we want to return after this call. `json_tasks` is meant to populate a queue table and is a large response with a lot of data. I don't see how the front end would be using any data from this response other than an ok status.

2024-11-26 15:22 UTC, piedram commented on app/controllers/tasks_controller.rb
> +    Task.where(id: task.id).update_all(
Done

2024-11-26 15:50 UTC, piedram commented on app/controllers/tasks_controller.rb
> +      tasks: json_tasks(task.appeal.tasks.includes(*task_includes))[:data]
done

2024-12-04 19:28 UTC, mchbidwell reviewed
tasks_controller has an extra end statement in it, looks to be around L279

2024-12-05 21:08 UTC, Lee-Whittaker-VA reviewed
I've got a few comments and suggestions on code issues below.

2024-12-05 21:08 UTC, Lee-Whittaker-VA commented on app/workflows/transcription_file_upload.rb
> +
It seems line 40 is triggering errors. I think it may be missing a comma, assuming it wasn't reached before your implementation.

```ruby
raise FileUploadError, "Amazon S3 service responded with error: #{error}"
```

2024-12-06 18:07 UTC, Lee-Whittaker-VA approved these changes
Looks good to me.

2024-12-11 20:21 UTC, Lee-Whittaker-VA requested changes
See comments on controller.

2024-12-11 20:21 UTC, Lee-Whittaker-VA commented on app/controllers/tasks_controller.rb
> +  def cancel_review_transcript_task
We've got `cancel_review_transcript_task` in here twice. You'll need to do some refactoring/renaming

2024-12-11 20:55 UTC, mchbidwell approved these changes

2024-12-11 20:55 UTC, mchbidwell approved these changes

2024-12-11 21:03 UTC, mchbidwell approved these changes

2024-12-12 19:06 UTC, Lee-Whittaker-VA submitted a review, later dismissed

2024-12-13 14:00 UTC, Lee-Whittaker-VA approved these changes

2024-12-13 15:25 UTC, Lee-Whittaker-VA approved these changes

2024-12-16 16:04 UTC, merged