Pamatya/appeals 45671 2
department-of-veterans-affairs/caseflow pull request #23602
Opened 2024-11-22 18:02 UTC by pamatyatake2

Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/JIRA-12345)

# Description
Please explain the changes you made here.

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan

1. Go to [Jira Issue/Test Plan Link](https://jira.devops.va.gov/browse/JIRA-12345) or list them below

- [ ] For feature branches merging into main: Was this deployed to UAT?

# Frontend
## User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

## Storybook Story
*For Frontend (Presentation) Components*
* [ ] Add a [Storybook](https://github.com/department-of-veterans-affairs/caseflow/wiki/Documenting-React-Components-with-Storybook) file alongside the component file (e.g. create `MyComponent.stories.js` alongside `MyComponent.jsx`)
* [ ] Give it a title that reflects the component's location within the overall Caseflow hierarchy
* [ ] Write a separate story (within the same file) for each discrete variation of the component

# Backend
## Database Changes
*Only for Schema Changes*

* [ ] Add typical timestamps (`created_at`, `updated_at`) for new tables
* [ ] Update column comments; include a "PII" prefix to indicate definite or potential [PII data content](https://github.com/department-of-veterans-affairs/appeals-team/blob/main/caseflow-team/0-how-we-work/pii-handbook.md#what-is-pii)
* [ ] Have your migration classes inherit from `Caseflow::Migration`, especially when adding indexes (use `add_safe_index`) (see [Writing DB migrations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations))
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Perform query profiling (eyeball Rails log, check bullet and fasterer output)
* [ ] For queries using raw sql was an explain plan run by System Team
* [ ] Add appropriate indexes (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Run `make check-fks`; add any missing foreign keys or add to `config/initializers/immigrant.rb` (see [Record associations and Foreign Keys](https://github.com/department-of-veterans-affairs/caseflow/wiki/Record-associations-and-Foreign-Keys))
* [ ] Add `belongs_to` for associations to enable the [schema diagrams](https://department-of-veterans-affairs.github.io/caseflow/task_trees/schema/schema_diagrams) to be automatically updated
* [ ] Document any non-obvious semantics or logic useful for interpreting database data at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

## Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
  * [ ] Check that calls are wrapped in MetricService record block
* [ ] Check that all configuration is coming from ENV variables
  * [ ] Listed all new ENV variables in description
  * [ ] Worked with or notified System Team that new ENV variables need to be set
* [ ] Update Fakes
* [ ] For feature branches: Was this tested in Caseflow UAT

# Best practices
## Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

## Monitoring, Logging, Auditing, Error, and Exception Handling Checklist

### Monitoring
- [ ] Are performance metrics (e.g., response time, throughput) being tracked?
- [ ] Are key application components monitored (e.g., database, cache, queues)?
- [ ] Is there a system in place for setting up alerts based on performance thresholds?

### Logging
- [ ] Are logs being produced at appropriate log levels (debug, info, warn, error, fatal)?
- [ ] Are logs structured (e.g., using log tags) for easier querying and analysis?
- [ ] Are sensitive data (e.g., passwords, tokens) redacted or omitted from logs?
- [ ] Is log retention and rotation configured correctly?
- [ ] Are logs being forwarded to a centralized logging system if needed?

### Auditing
- [ ] Are user actions being logged for audit purposes?
- [ ] Are changes to critical data being tracked ?
- [ ] Are logs being securely stored and protected from tampering or exposing protected data?

### Error Handling
- [ ] Are errors being caught and handled gracefully?
- [ ] Are appropriate error messages being displayed to users?
- [ ] Are critical errors being reported to an error tracking system (e.g., Sentry, ELK)?
- [ ] Are unhandled exceptions being caught at the application level ?

### Exception Handling
- [ ] Are custom exceptions defined and used where appropriate?
- [ ] Is exception handling consistent throughout the codebase?
- [ ] Are exceptions logged with relevant context and stack trace information?
- [ ] Are exceptions being grouped and categorized for easier analysis and resolution?

2024-11-26 04:27 UTC, TylerBroyles requested changes
Looks good overall. I have a few minor things about redux but nothing major.

2024-11-26 04:27 UTC, TylerBroyles commented on client/app/nonComp/components/ReportPage/SaveLimitReachedModal.jsx
> +  const onRadioSelect = (val) => {
If we extracted some of the handlers out and passed in the searches, then we wouldn't have to include any selectors or dispatch imports in this modal at all. It's a trade off, and it does make the selected search a bit harder to use though so it might not be worth it in the end.

2024-11-26 04:27 UTC, TylerBroyles commented on client/test/app/nonComp/components/SaveLimitReachedModal.test.js
> +import savedSearchesData from '../../../data/nonComp/savedSearchesData';
Same comment about mixing url import types.

2024-11-26 15:15 UTC, pamatyatake2 commented on client/app/nonComp/actions/savedSearchSlice.js
> +      thunkApi.dispatch(fetchedSearches({ organizationUrl }));
so after count of the search becomes 10 we had to do page refresh for Save Limit Reached Modal to populate. by adding it here it was populating without page load. if you have any suggestion on how we can accomplish that, that would be awesome. thank you

2024-11-27 21:41 UTC, TylerBroyles requested changes
Looks great. There's only a couple of small things that I noticed like the linting error, but other than that it's basically ready for BA/UX.

2024-11-27 21:41 UTC, TylerBroyles commented on client/app/nonComp/components/ReportPage/SaveLimitReachedModal.jsx
> +    const selectedData = userSearches.find((search) => parseInt(search.id) === parseInt(val));
```suggestion
    const selectedData = userSearches.find((search) => parseInt(search.id, 10) === parseInt(val, 10));
```

2024-11-27 21:41 UTC, TylerBroyles commented on client/app/nonComp/components/ReportPage/SaveLimitReachedModal.jsx
> +    // eslint-disable-next-line radix
```suggestion
```

2024-11-27 22:43 UTC, TylerBroyles approved these changes
Looks good to me. Great job!

2024-11-29 16:16 UTC, brandondorner approved these changes

2024-12-03 17:53 UTC, almorbah commented on app/controllers/saved_searches_controller.rb
> +                    status: :created
extra space here

2024-12-03 18:00 UTC, pamatyatake2 commented on app/controllers/saved_searches_controller.rb
> +                    status: :created
its not extra space its the alignment for Robocop to be happy.

2024-12-03 18:02 UTC, almorbah commented on client/app/nonComp/components/ReportPage/SaveLimitReachedModal.stories.js
> +  },
NitPick: linting cleanup

2024-12-03 18:04 UTC, almorbah approved these changes
Minor comments but looks good over all

2024-12-03 18:56 UTC, merged