Create Mark Packet Complete endpoint
department-of-veterans-affairs/caseflow pull request #23735
Opened 2024-12-09 21:30 UTC by Rnmarshall93

Resolves [Create Mark Packet Complete endpoint](https://jira.devops.va.gov/browse/APPEALS-59077)

# Description
This PR creates an endpoint _api/v1/cmp/packet_ that allows the user to create CmpMailPacket objects and store them in the database via a post request. Once created, the CmpDocument that matched the provided UUID on the packet will be updated to be associated.

## Acceptance Criteria
- [X] Code compiles correctly

## Testing Plan
1. Execute the bruno tests provided in the separate PR, these will generate a success and two failures.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [X] RSpec
- [ ] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [X] No new code climate issues added

2024-12-09 22:35 UTC, tradesmanhelix requested changes

2024-12-09 22:35 UTC, tradesmanhelix commented on app/controllers/api/v1/cmp_controller.rb
> +    if !/^[1-9]{1}\d{3}-\d{2}-\d{2}$/.match?(packet_params[:va_dor])
Would recommend moving this validation into the model. That way, any other place in the code that attempts to save to this property will have to pass this validation.

It's pretty easy to do. Check out the `date_of_receipt_must_be_a_date` method in `app/models/cmp_document.rb`.

2024-12-09 22:35 UTC, tradesmanhelix commented on app/models/cmp_document.rb
> +    errors.add(:date_of_receipt, "date_of_receipt must be a valid date")
Having trouble understanding these changes. Maybe we can sync in a huddle re. this?

Looks like it might also be causing a failure in `spec/requests/api/v1/cmp_controller_spec.rb`.

2024-12-09 22:35 UTC, tradesmanhelix commented on spec/requests/api/v1/cmp_controller_spec.rb
> +        CmpDocument.create!(cmp_doc_data)
We should use the FactoryBot factories for this.

There is already a `CmpDocument` factory here: `spec/factories/cmp_documents.rb`. You can use it in your tests like this:

```
# The ! tells Rspec to create the object; otherwise, it's only created when actually
# accessed (for the sake of speed) but this can cause issues, so if you know you need
# it use ! and it will always be created for you and exist when your test runs
let!(:cmp_doc) { create(:cmp_document) }
```

You can set individual properties of the object if need be; otherwise, the values from the factory will be used:
```
let(:my_packet_uuid) { SecureRandom.uuid }
let!(:cmp_doc) { create(:cmp_document, packet_uuid: my_packet_uuid) }
```

2024-12-09 22:35 UTC, tradesmanhelix commented on spec/requests/api/v1/cmp_controller_spec.rb
> +        expect(response.status == 200)
It's also not a bad practice to verify the properties of the created object, just be sure objects' properties are being properly mapped (see lines 80-86 above for an example).

2024-12-09 22:35 UTC, tradesmanhelix commented on spec/requests/api/v1/cmp_controller_spec.rb
> +        expect(response.status == 500)
Should we maybe return a 422 `unprocessable_entity` here? I think 500 is more for when our code errors, whereas 422 means we understood the request but couldn't comply due to an issue with the provided data.

Also, it looks like `unprocessable_entity` is what the controller is returning.

2024-12-09 22:35 UTC, tradesmanhelix commented on spec/requests/api/v1/cmp_controller_spec.rb
> +        expect(response.status == 200)
Would recommend using `have_http_status` (https://rspec.info/features/6-0/rspec-rails/matchers/have-http-status-matcher/):

`expect(response).to have_http_status(:ok)`

2024-12-09 22:35 UTC, tradesmanhelix commented on spec/requests/api/v1/cmp_controller_spec.rb
> +        expect(response.status == 500)
Also another good place to use https://rspec.info/features/6-0/rspec-rails/matchers/have-http-status-matcher/.

2024-12-09 22:35 UTC, tradesmanhelix commented on spec/requests/api/v1/cmp_controller_spec.rb
> +    let!(:cmp_packet_number) { 1 }
If this isn't a value that's tested later, would recommend `Faker::Number.within(range: 1..10)` or equivalent.

If it needs to be tested, probably best practice to make it a named value like:
```
let(:cmp_packet_number_val) { Faker::Number.within(range: 1..10) }
let!(:cmp_packet_number) { cmp_packet_number_val }

...

expect(cmp_packet.cmp_packet_number).to eq cmp_packet_number_val
```

2024-12-09 22:35 UTC, tradesmanhelix commented on app/controllers/api/v1/cmp_controller.rb
> +      cmp_doc = CmpDocument.find_by(cmp_document_uuid: new_packet[:packet_uuid])
I think this may need to be `new_packet.packet_uuid`.

2024-12-09 22:35 UTC, tradesmanhelix commented on app/controllers/api/v1/cmp_controller.rb
> +      cmp_doc = CmpDocument.find_by(cmp_document_uuid: new_packet[:packet_uuid])
Is it an error state if the `CmpDocument` can't be found? If so, may want to update this method's logic to ensure that the `CmpDocument` before creating the `CmpMailPacket`.

2024-12-10 14:28 UTC, zurbergram commented on db/migrate/20241202132509_add_cmp_packet_id_to_cmp_mail_packet.rb
> +    add_reference :cmp_mail_packets, :cmp_mail_packet, foreign_key: true, index: false, null: true
What is this `add_reference` doing?

2024-12-10 14:30 UTC, zurbergram requested changes
Please see comments on PR

2024-12-10 21:29 UTC, Rnmarshall93 commented on db/migrate/20241202132509_add_cmp_packet_id_to_cmp_mail_packet.rb
> +    add_reference :cmp_mail_packets, :cmp_mail_packet, foreign_key: true, index: false, null: true
This add_reference was to support the relationship between CmpDocument and CmpPacket, but was made due to me misreading the AC. It should have been removed and not in the PR.

2024-12-11 21:14 UTC, tradesmanhelix requested changes
A couple of minor things but looking 👌

2024-12-11 21:14 UTC, tradesmanhelix commented on app/controllers/api/v1/cmp_controller.rb
> +      unprocessable_response("Cmp document could now be created.", new_document)
Slight typo `now -> not`.

2024-12-11 21:14 UTC, tradesmanhelix commented on db/schema.rb
Looks like this file might still have some unneeded changes. Maybe try this?

`git checkout origin/feature/APPEALS-57449 -- db/schema.rb`

That should update the file to match the feature branch.

2024-12-12 18:04 UTC, zurbergram submitted a review, later dismissed

2024-12-12 18:17 UTC, zurbergram approved these changes

2024-12-13 18:04 UTC, zurbergram approved these changes

2024-12-13 18:08 UTC, merged