Add a Base View for the National Hearing Queue
department-of-veterans-affairs/caseflow pull request #23747
Opened 2024-12-10 16:38 UTC by prernadevbah

Resolves [Add a Base View for the National Hearing Queue](https://jira.devops.va.gov/browse/APPEALS-65175)

# Description
Adding a new page and routing to display a base view that the NHQ will eventually be displayed on

## Acceptance Criteria
- [ ] Code compiles correctly

## Testing Plan
1. Go to [APPEALS-67400](https://jira.devops.va.gov/browse/APPEALS-67400)

# Best practices
## Code Documentation Updates
- [x] Add or update code comments at the top of the class, module, and/or component.

## Tests
### Test Coverage
Did you include any test coverage for your code? Check below:
- [ ] RSpec
- [x] Jest
- [ ] Other

### Code Climate
Your code does not add any new code climate offenses? If so why?
- [ ] No new code climate issues added

2024-12-10 22:26 UTC, ThorntonMatthew requested changes

2024-12-10 22:26 UTC, ThorntonMatthew commented on db/schema.rb
> +
```suggestion
```

This can be removed.

2024-12-10 22:26 UTC, ThorntonMatthew commented on app/controllers/hearings/national_hearing_queue_controller.rb
> +      format.json { queue_entries }
```suggestion
```
This will be added in Q2.

2024-12-10 22:26 UTC, ThorntonMatthew commented on app/views/national_hearing_queue/index.html.erb
> +  }) %>
AC 3 specifies which of these props are desired for the NHQ. Hopefully they're all of the ones we need... At any rate, most of these I know we don't need (since the NHQ is pretty much blank). Would you mind whittling these down?

2024-12-10 22:26 UTC, ThorntonMatthew commented on client/test/app/queue/nationalHearingQueue/NationalHearingQueueContainer.test.js
> +describe('NationalHearingQueueContainer', () => {
Thanks for getting this going! I'm sure we'll be in here a lot!

2024-12-10 23:00 UTC, prernadevbah commented on app/views/national_hearing_queue/index.html.erb
> +  }) %>
I ended up having to add the userRole prop as well for the QueueApp component but other than that the remaining props should be up-to-date with AC 3 now

2024-12-10 23:27 UTC, ThorntonMatthew commented on client/app/queue/QueueApp.jsx
> +              title="National Hearing Scheduling Queue | Caseflow"
```suggestion
              title="National Hearings Scheduling Queue | Caseflow"
```

2024-12-11 22:09 UTC, ThorntonMatthew approved these changes

2024-12-12 15:49 UTC, merged